=pod

=head1 NAME



B<XPA: Public Access to Data and Algorithms>



=head1 SYNOPSIS




This document is the Table of Contents for XPA.



=head1 DESCRIPTION





The XPA messaging system provides seamless communication between many
kinds of Unix programs, including X programs and Tcl/Tk programs.  It
also provides an easy way for users to communicate with XPA-enabled
programs by executing XPA client commands in the shell or by utilizing
such commands in scripts.  Because XPA works both at the programming
level and the shell level, it is a powerful tool for unifying any
analysis environment: users and programmers have great flexibility in
choosing the best level or levels at which to access XPA services, and
client access can be extended or modified easily at any time.


A program becomes an XPA-enabled server by defining named points of
public access through which data and commands can be exchanged with
other client programs (and users).  Using standard TCP sockets as a
transport mechanism, XPA supports both single-point and broadcast
messaging to and from these servers.  It supports direct communication
between clients and servers, or indirect communication via an
intermediate message bus emulation program. Host-based access control
is implemented, as is as the ability to communicate with XPA servers
across a network.


XPA implements a layered interface that is designed to be useful both
to software developers and to users.  The interface consists of a
library of XPA client and server routines for use in C/C++ programs and
a suite of high-level user programs built on top of these libraries.
Using the XPA library, access points can be added to Tcl/Tk programs,
Xt programs, or to Unix programs that use the XPA event loop or any
event loop based on select().  Client access subroutines can be added
to any Tcl/Tk, Xt, or Unix program. Client access also is supported at
the command line via a suite of high-level programs.


Choose from the following topics:



=over 4

 


=item *

Introduction to XPA
[xpaintro(n)]


=item *

Access Point Names and Templates
[xpatemplate(n)]


=item *

Getting Common Information About Access Points
[xpacommon(n)]


=item *

Communication Methods
[xpamethod(n)]


=item *

Communication Between Hosts
[xpainet(n)]


=item *

Distinguishing Users
[xpausers(n)]



=item *

XPA User Programs


=over 4




=item *

xpaget: get data and info
[xpaget(1)]


=item *

xpaset: send data and info
[xpaset(1)]


=item *

xpainfo: send info alert
[xpainfo(1)]


=item *

xpaaccess: get access point info
[xpaaccess(1)]


=item *

xpamb: message bus emulation
[xpamb(1)]


=item *

xpans: the XPA name server
[xpans(1)]


=back





=item *

XPA Server Routines


=over 4




=item *

XPANew: define a new access point
[xpanew(3)]


=item *

XPACmdNew: define a new command access point
[xpacmdnew(3)]


=item *

XPACmdAdd: add a command
[xpacmdadd(3)]


=item *

XPACmdDel: delete a command
[xpacmddel(3)]


=item *

XPAInfoNew: define an info access point
[xpainfonew(3)]


=item *

XPAFree: free an access point
[xpafree(3)]


=item *

XPAMainLoop: event loop for select server
[xpamainloop(3)]


=item *

XPAPoll: poll for XPA events
[xpapoll(3)]


=item *

XPACleanup: release reserved XPA memory
[xpacleanup(3)]


=item *

XPA Server Macros: accessing structure internals
[xpamacros(3)]


=item *

XPA Race Conditions: how to avoid them
[xparace(3)]


=item *

XPA Out of Memory (OOM) errors
[xpaoom(3)]


=back





=item *

XPA Client Routines


=over 4




=item *

XPAOpen: open a persistent client connection
[xpaopen(3)]


=item *

XPAClose: close persistent client connection
[xpaclose(3)]


=item *

XPAGet: get data
[xpaget(3)]


=item *

XPASet: send data or commands
[xpaset(3)]


=item *

XPAInfo: send an info alert
[xpainfo(3)]


=item *

XPAGetFd: get data and write to an fd
[xpagetfd(3)]


=item *

XPASetFd: read data from and fd and send
[xpasetfd(3)]


=item *

XPANSLookup: look up an access point
[xpanslookup(3)]


=item *

XPAAccess: get access info
[xpaaccess(3)]


=item *

The XPA/Xt Interface: Xt interface to XPA
[xpaxt(n)]


=item *

The XPA/Tcl Interface: Tcl interface to XPA
[xpatcl(n)]


=back





=item *

Tailoring the XPA Environment


=over 4




=item *

Environment Variables
[xpaenv(n)]


=item *

Access Control
[xpaacl(n)]


=back





=item *

Miscellaneous


=over 4





=item *

Where to Find Example/Test Code


=item *

User Changes Between XPA 1.0 and 2.0


=item *

API Changes Between XPA 1.0 and 2.0


=item *

What Does XPA Stand For, Anyway?


=back





=back

 




=cut
