[section {Bugs, Ideas, Feedback}]
[vset TRACKER http://core.tcl.tk/tklib/reportlist]
[vset LABEL   {Tklib Trackers}]

This document, and the package it describes, will undoubtedly contain
bugs and other problems.

Please report such in the category [emph [vset CATEGORY]] of the
[uri [vset TRACKER] [vset LABEL]].

Please also report any ideas for enhancements you may have for either
package and/or documentation.
