#!/bin/sh

if [ x$1 != x ]; then
  FILE=$1
  echo "checking $FILE ..."
else
  echo "checking stdin ..."
fi

egrep -v 'REV|EXACT|SUM|OPROG|NPROG|FILE|block factor does|0a1,2|\*\*\*|^ *$|^foo|idx|^tboxell|^\)|^HERE\)\]' $FILE
