#!/bin/tcsh -f
rm -f foo.idx foo.noidx

# setenv FILTER_PTYPE c
setenv FILTER_IDX_DEBUG 0

setenv FILTER_IDX_ACTIVATE 1
date >> foo.idx
funtests >>& foo.idx
date >> foo.idx

setenv FILTER_IDX_ACTIVATE 0
date > foo.noidx
funtests >>& foo.noidx
date >> foo.noidx



