// Copyright (C) 1999-2018
// Smithsonian Astrophysical Observatory, Cambridge, MA, USA
// For conditions of distribution and use, see copyright notice in "copyright"

#ifndef __xml_h__
#define __xml_h__

#define XMLNUMCOL 34

enum XMLColName {XMLSHAPE,XMLX,XMLY,XMLXV,XMLYV,XMLR,XMLR2,XMLRV,XMLRV2,XMLANG,XMLANGV,XMLTILE,XMLCOLOR,XMLWIDTH,XMLTEXT,XMLFONT,XMLSELECT,XMLHIGHLITE,XMLEDIT,XMLMOVE,XMLROTATE,XMLDELETE,XMLFIXED,XMLINCLUDE,XMLSOURCE,XMLDASH,XMLDASHLIST,XMLTAG,XMLPARAM,XMLPARAM2,XMLPARAM3,XMLPARAM4,XMLPARAM5,XMLCOMMENT};

#endif
