#!/bin/sh

if [ ! -r foo.fits ]; then
  ln -s $HOME/data/snr.ev foo.fits
fi

FUN_FORMAT='x=%4d y=%4d pha=%3d pi=%3d dx=%4d dy=%4d'
export FUN_FORMAT

echo fundisp foo.fits"'[$1]'" | tee foo.log
echo " " | tee -a foo.log
../fundisp foo.fits"[$1]" | tee -a foo.log



