#include "ast.h"
#include "ast_err.h"
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#define nx 150
#define ny 100
#define k 4
#define npos 10
#define tol 1.0E-11

static int read_values( FILE *in, int nval, double values[ static 1 ],
                        const char *name ) {
   int i;
   for( i = 0; i < nval; i++ ) {
      if( fscanf( in, "%lf", &values[ i ] ) != 1 ) {
         astError( AST__INTER, "Failed to read %s[%d]", name, i );
         return 0;
      }
   }
   return 1;
}

static void check_coeffs( int errcode, const double got[ static nx*ny ],
                          const double expected[ static nx*ny ] ) {
   int i;
   for( i = 0; i < nx*ny; i++ ) {
      if( got[ i ] != expected[ i ] ) {
         astError( AST__INTER, "Error %d: %d %.20g %.20g", errcode, i,
                   got[ i ], expected[ i ] );
         return;
      }
   }
}

static void check_forward( const double uexp[ static npos ],
                           const double vexp[ static npos ],
                           const double uout[ static npos ],
                           const double vout[ static npos ] ) {
   int i;
   for( i = 0; i < npos && astOK; i++ ) {
      if( uexp[ i ] == AST__BAD ) {
         if( uout[ i ] != AST__BAD ) {
            astError( AST__INTER, "Error 1: %d : %.20g != AST__BAD",
                      i, uout[ i ] );
         }
      } else if( vexp[ i ] == AST__BAD ) {
         if( vout[ i ] != AST__BAD ) {
            astError( AST__INTER, "Error 2: %d : %.20g != AST__BAD",
                      i, vout[ i ] );
         }
      } else if( uout[ i ] == AST__BAD ) {
         astError( AST__INTER, "Error 3: %d : AST__BAD != %.20g",
                   i, uexp[ i ] );
      } else if( vout[ i ] == AST__BAD ) {
         astError( AST__INTER, "Error 4: %d : AST__BAD != %.20g",
                   i, vexp[ i ] );
      } else if( fabs( uout[ i ] - uexp[ i ] ) > tol*fabs( uexp[ i ] ) ) {
         astError( AST__INTER, "Error 5: %d : %.20g != %.20g",
                   i, uout[ i ], uexp[ i ] );
      } else if( fabs( vout[ i ] - vexp[ i ] ) > tol*fabs( vexp[ i ] ) ) {
         astError( AST__INTER, "Error 6: %d : %.20g != %.20g",
                   i, vout[ i ], vexp[ i ] );
      }
   }
}

static void check_reverse( const double xin[ static npos ], const double yin[ static npos ],
                           const double uout[ static npos ], const double vout[ static npos ],
                           const double xrec[ static npos ], const double yrec[ static npos ] ) {
   int i;
   for( i = 0; i < npos && astOK; i++ ) {
      if( uout[ i ] != AST__BAD && vout[ i ] != AST__BAD ) {
         if( fabs( xrec[ i ] - xin[ i ] ) > tol*fabs( xin[ i ] ) ||
             fabs( yrec[ i ] - yin[ i ] ) > tol*fabs( yin[ i ] ) ) {
            astError( AST__INTER,
                      "Error 7: %d (%.20g,%.20g)->(%.20g,%.20g) (%.20g,%.20g)\n",
                      i, uout[ i ], vout[ i ], xrec[ i ], yrec[ i ],
                      xin[ i ], yin[ i ] );
         }
      } else if( xrec[ i ] != AST__BAD || yrec[ i ] != AST__BAD ) {
         astError( AST__INTER,
                   "Error 8: %d (%.20g,%.20g)->(%.20g,%.20g) (%.20g,%.20g)\n",
                   i, uout[ i ], vout[ i ], xrec[ i ], yrec[ i ],
                   xin[ i ], yin[ i ] );
      }
   }
}

int main( void ){

   AstSplineMap *sm;
   double tx[nx+k], ty[ny+k], cu[nx*ny], cv[nx*ny], uout[npos], vout[npos],
          xrec[npos], yrec[npos], cu2[nx*ny], cv2[nx*ny];

   double xin[npos] = { 0.0, 12.5, 12.0, 1.0, 15.0, 1.0, 95.0, 149.5, 151.2, 77.77 };
   double yin[npos] = { -1.0, 8.8, 8.0, 1.0, 15.0, 76.0, 100.0, 99.8, 82.3, 54.3 };

/* Transformed positions generated by scipy.interpolate.RectBivariateSpline
   (but with the the values for out-of-bounds inputs set to AST__BAD
   since CMLIB - used inside AST - does not extrapolate values at such
   points). */
   double uexp[npos] = { AST__BAD, 12.049767072857646, 11.921107191183191, 1.7788366846173014, 14.441169003602148,
                         0.30566103317717114, 95.244648802952383, 147.72545905681767,
                         AST__BAD, 77.68709057730592 };

   double vexp[npos] = { AST__BAD, 6.4394741329528635, 5.788762120688823,
                         1.5841275134629758, 14.580876752701611, 77.43010929535424,
                         102.70789955663800, 99.94739777629977, AST__BAD,
                         57.237295512435686 };

/* Read the spline data from a text file. This data is created by using
   scipy.interpolate.RectBivariateSpline to fit a spline to known arrays.
   The array coefficients generated by SciPy are stored in transposed order
   compared to those generated by CMLIB. The C API for the SplineMap
   constructor assumes the coefficients are order according to the SciPy
   method, but the Fortran API assumes they are ordered according to the
   CMLIB method. That's why we need both a C and a Fortran tester for
   SplineMap. */
/* The fixture data file lives in the source directory, which the test
   harness points at via the 'srcdir' environment variable (falling back to
   the current directory for a plain in-source run). */
   const char *srcdir = getenv( "srcdir" );
   char fname[ PATH_MAX ];
   FILE *in;
   if( !srcdir || !*srcdir ) srcdir = ".";
   snprintf( fname, sizeof( fname ), "%s/"
             "fixtures/programs/testsplinemap/2dspline_c.dat", srcdir );
   in = fopen( fname, "r" );
   if( !in ){
      astError( AST__INTER, "Could not open file '%s'", fname );
   } else {

      read_values( in, nx + k, tx, "tx" );
      read_values( in, ny + k, ty, "ty" );
      read_values( in, nx*ny, cu, "cu" );
      read_values( in, nx*ny, cv, "cv" );

      fclose( in );
   }

/* Create a SplineMap from these values. */
   sm = astSplineMap( k, k, nx, ny, tx, ty, cu, cv, " " );

/* Test retrieving the coeffs */
   astSplineCoeffs( sm, 1, nx*ny, cu2 );
   astSplineCoeffs( sm, 2, nx*ny, cv2 );
   if( astOK ) check_coeffs( 100, cu2, cu );
   if( astOK ) check_coeffs( 101, cv2, cv );

/* Transform a set of points. */
   astTran2( sm, npos, xin, yin, 1, uout, vout );
   if( astOK ) {
      check_forward( uexp, vexp, uout, vout );
   }

/* Transform them back again. */
   astTran2( sm, npos, uout, vout, 0, xrec, yrec );
   if( astOK ) {
      check_reverse( xin, yin, uout, vout, xrec, yrec );
   }


/* An order-1 (piecewise-constant) spline has no first derivative in its
   B-spline representation, so the Jacobian used by the iterative inverse
   is singular everywhere.  The inverse transformation must report this by
   returning AST__BAD for every point, without raising an AST error. */
   if( astOK ) {
      double tx1[2] = { 0.0, 1.0 };
      double ty1[2] = { 0.0, 1.0 };
      double cu1[1] = { 1.5 };
      double cv1[1] = { 2.5 };
      double uin1[1] = { 0.5 };
      double vin1[1] = { 0.5 };
      double xrec1[1], yrec1[1];

      AstSplineMap *sm1 = astSplineMap( 1, 1, 1, 1, tx1, ty1, cu1, cv1, " " );
      astTran2( sm1, 1, uin1, vin1, 0, xrec1, yrec1 );
      if( !astOK ) {
         printf( "Error 9: order-1 inverse raised an AST error\n" );
      } else if( xrec1[ 0 ] != AST__BAD || yrec1[ 0 ] != AST__BAD ) {
         astError( AST__INTER, "Error 10: order-1 inverse gave (%.20g,%.20g), "
                   "expected AST__BAD", xrec1[ 0 ], yrec1[ 0 ] );
      }
      sm1 = astAnnul( sm1 );
   }

   if( astOK ) {
      printf(" All SplineMap (C API) tests passed\n");
   } else {
      printf("SplineMap (C API) tests failed\n");
   }
   return astOK ? 0 : 1;

}
