::msgcat::mcset cs {2D} 
::msgcat::mcset cs {3D View} 
::msgcat::mcset cs {3D} 
::msgcat::mcset cs {A postscript generation error has occurred} [encoding convertfrom iso8859-2 {Chyba pøi generování postscriptu}]
::msgcat::mcset cs {AIP} 
::msgcat::mcset cs {Abort} [encoding convertfrom iso8859-2 {Pøeru¹it}]
::msgcat::mcset cs {About SAOImageDS9} 
::msgcat::mcset cs {About} [encoding convertfrom iso8859-2 {O programu}] 
::msgcat::mcset cs {Acknowledgment} [encoding convertfrom iso8859-2 {Podìkování}]
::msgcat::mcset cs {Add} [encoding convertfrom iso8859-2 {Pøidat}]
::msgcat::mcset cs {Advanced} [encoding convertfrom iso8859-2 {Dal¹í nastavení}]
::msgcat::mcset cs {Aligned} 
::msgcat::mcset cs {Align} [encoding convertfrom iso8859-2 {Zarovnat}]
::msgcat::mcset cs {All Columns} [encoding convertfrom iso8859-2 {V¹echny sloupce}]
::msgcat::mcset cs {All Rows} [encoding convertfrom iso8859-2 {V¹echny øádky}]
::msgcat::mcset cs {All} [encoding convertfrom iso8859-2 {V¹e}]
::msgcat::mcset cs {Always save files during Backup} [encoding convertfrom iso8859-2 {V¾dy ulo¾it soubory pøi zálohování}]
::msgcat::mcset cs {Amplifier} [encoding convertfrom iso8859-2 {Zesilovaè}]
::msgcat::mcset cs {An error has occurred during backup} [encoding convertfrom iso8859-2 {Chyba pøi poøizování zálohy}]
::msgcat::mcset cs {An error has occurred during restore} [encoding convertfrom iso8859-2 {Chyba pøi obnovì zálohy}]
::msgcat::mcset cs {An error has occurred invoking the Analysis task} [encoding convertfrom iso8859-2 {Chyba pøi spou¹tìní Analýzy}]
::msgcat::mcset cs {An error has occurred while creating image.} [encoding convertfrom iso8859-2 {Chyba pøi vytváøení obrázku.}]
::msgcat::mcset cs {An error has occurred while creating the image. Please be sure that the ds9 window is in the upper left corner of the default screen and the entire window is visible.} [encoding convertfrom iso8859-2 {Chyba pøi vytváøení obrázku. Prosím ujistìte se ¾e okno s DS9tkou je ve vrchním levém rohu výchozí obrazovky a ¾e je celé viditelné.}]
::msgcat::mcset cs {An error has occurred while creating the image. Please be sure that the entire image window is visible on the screen.} [encoding convertfrom iso8859-2 {Chyba pøi vytváøení obrázku. Prosím ujistìte se na obrazovce je zobrazené celé okno s obrázkem}]
::msgcat::mcset cs {An error has occurred while printing} [encoding convertfrom iso8859-2 {Pøi tisku se vyskytla chyba}]
::msgcat::mcset cs {An error has occurred while reading image.} [encoding convertfrom iso8859-2 {Chyba pøi ètení obrázku.}]
::msgcat::mcset cs {An error has occurred while saving} [encoding convertfrom iso8859-2 {Chyba pøi ukládání souboru}]
::msgcat::mcset cs {An error has occurred while writing image.} 
::msgcat::mcset cs {An internal error has been detected} [encoding convertfrom iso8859-2 {Byla detekována vnitøní chyba programu}]
::msgcat::mcset cs {Analysis Command Log} [encoding convertfrom iso8859-2 {Poøizovat záznam analytických pøíkazù}]
::msgcat::mcset cs {Analysis Commands} [encoding convertfrom iso8859-2 {Analytické pøíkazy}]
::msgcat::mcset cs {Analysis File} [encoding convertfrom iso8859-2 {Analytický soubor}]
::msgcat::mcset cs {Analysis Log} [encoding convertfrom iso8859-2 {Záznam èinnosti analytický pøíkazù}]
::msgcat::mcset cs {Analysis} [encoding convertfrom iso8859-2 {Analýza}]
::msgcat::mcset cs {Angle Complement} [encoding convertfrom iso8859-2 {Doplnìk úhlu}]
::msgcat::mcset cs {Angles} [encoding convertfrom iso8859-2 {Úhly}]
::msgcat::mcset cs {Angle} [encoding convertfrom iso8859-2 {Úhel}]
::msgcat::mcset cs {Annuli} [encoding convertfrom iso8859-2 {Kruhù}]
::msgcat::mcset cs {Annulus} [encoding convertfrom iso8859-2 {Kruh}]
::msgcat::mcset cs {Apply} [encoding convertfrom iso8859-2 {Pou¾ít}]
::msgcat::mcset cs {ArcMin} [encoding convertfrom iso8859-2 {úhlových minut}]
::msgcat::mcset cs {ArcSec} [encoding convertfrom iso8859-2 {úhlových sekund}]
::msgcat::mcset cs {Architecture} [encoding convertfrom iso8859-2 {Architektura}]
::msgcat::mcset cs {Archives} 
::msgcat::mcset cs {Array} 
::msgcat::mcset cs {Arrow} [encoding convertfrom iso8859-2 {©ipka}]
::msgcat::mcset cs {Asteroids} 
::msgcat::mcset cs {Astronomy} [encoding convertfrom iso8859-2 {Astronomie}]
::msgcat::mcset cs {At Startup} [encoding convertfrom iso8859-2 {Pøi spu¹tìní}]
::msgcat::mcset cs {At least 2 different catalogs are required} 
::msgcat::mcset cs {Auto Centroid} [encoding convertfrom iso8859-2 {Automatické centrování}]
::msgcat::mcset cs {Auto Plot 2D} [encoding convertfrom iso8859-2 {Automatický 2D graf}]
::msgcat::mcset cs {Auto Plot 3D} [encoding convertfrom iso8859-2 {Automatický 3D graf}]
::msgcat::mcset cs {Auto Plot Statistics} 
::msgcat::mcset cs {Auto Plot} [encoding convertfrom iso8859-2 {Automatický graf}]
::msgcat::mcset cs {Autoload FITS Regions} [encoding convertfrom iso8859-2 {Automaticky nahrát FITS oblasti}]
::msgcat::mcset cs {Autoload} [encoding convertfrom iso8859-2 {Automatické nahrávání}]
::msgcat::mcset cs {Automatic} [encoding convertfrom iso8859-2 {Automatické}]
::msgcat::mcset cs {Average} [encoding convertfrom iso8859-2 {Prùmìr}]
::msgcat::mcset cs {Axes Number} 
::msgcat::mcset cs {Axes Order} 
::msgcat::mcset cs {Axes Title} 
::msgcat::mcset cs {Axes} [encoding convertfrom iso8859-2 {Osy}]
::msgcat::mcset cs {Axis Length} [encoding convertfrom iso8859-2 {Délka osy}]
::msgcat::mcset cs {Axis Numbers} [encoding convertfrom iso8859-2 {Èíslování osy}]
::msgcat::mcset cs {Axis Title} 
::msgcat::mcset cs {Axis} [encoding convertfrom iso8859-2 {Osy}]
::msgcat::mcset cs {Azimuth} [encoding convertfrom iso8859-2 {Azimut}]
::msgcat::mcset cs {Background Color} [encoding convertfrom iso8859-2 {Barva pozadí}]
::msgcat::mcset cs {Background} [encoding convertfrom iso8859-2 {Pozadí}]
::msgcat::mcset cs {Backup} [encoding convertfrom iso8859-2 {Záloha}]
::msgcat::mcset cs {Back} [encoding convertfrom iso8859-2 {Zpìt}]
::msgcat::mcset cs {Bar Plot Tool} 
::msgcat::mcset cs {Bias} 
::msgcat::mcset cs {Bin 3rd Column} [encoding convertfrom iso8859-2 {Binuj tøetí sloupec}]
::msgcat::mcset cs {Bin Center} [encoding convertfrom iso8859-2 {Binuj støed}]
::msgcat::mcset cs {Bin Columns} [encoding convertfrom iso8859-2 {Binuj sloupce}]
::msgcat::mcset cs {Bin Filter} [encoding convertfrom iso8859-2 {Filtr binování}]
::msgcat::mcset cs {Bin Fit} 
::msgcat::mcset cs {Bin In} 
::msgcat::mcset cs {Bin Out} 
::msgcat::mcset cs {Binning Parameters} [encoding convertfrom iso8859-2 {Parametry binování}]
::msgcat::mcset cs {Bin} 
::msgcat::mcset cs {Black} [encoding convertfrom iso8859-2 {Èerná}]
::msgcat::mcset cs {Blank/Inf/NaN Color} [encoding convertfrom iso8859-2 {Barva nedefinovaných pixelù}]
::msgcat::mcset cs {Blink Frames} [encoding convertfrom iso8859-2 {Problikávej snímky}]
::msgcat::mcset cs {Blink Interval} [encoding convertfrom iso8859-2 {Interval problikávání snímkù}]
::msgcat::mcset cs {Blink} [encoding convertfrom iso8859-2 {Problikávat}]
::msgcat::mcset cs {Block Fit} 
::msgcat::mcset cs {Block In} [encoding convertfrom iso8859-2 {Zmen¹it}]
::msgcat::mcset cs {Block Out} [encoding convertfrom iso8859-2 {Zvìt¹it}]
::msgcat::mcset cs {Block Parameters} 
::msgcat::mcset cs {Block} 
::msgcat::mcset cs {Blue} [encoding convertfrom iso8859-2 {Modrá}]
::msgcat::mcset cs {Bold} [encoding convertfrom iso8859-2 {Tuènì}]
::msgcat::mcset cs {Border} [encoding convertfrom iso8859-2 {Okraj}]
::msgcat::mcset cs {Bottom} 
::msgcat::mcset cs {Box Annulus} 
::msgcat::mcset cs {Box Panda} 
::msgcat::mcset cs {BoxCircle} 
::msgcat::mcset cs {Boxcar} 
::msgcat::mcset cs {Box} [encoding convertfrom iso8859-2 {Obdélník}]
::msgcat::mcset cs {Broadcast} 
::msgcat::mcset cs {Browser} [encoding convertfrom iso8859-2 {Prohlí¾eè}]
::msgcat::mcset cs {Browse} [encoding convertfrom iso8859-2 {Prohlí¾et}]
::msgcat::mcset cs {Buffer} 
::msgcat::mcset cs {Buttonbar} 
::msgcat::mcset cs {Buttons} [encoding convertfrom iso8859-2 {Tlaèítka}] 
::msgcat::mcset cs {Bytes} 
::msgcat::mcset cs {CMYK} 
::msgcat::mcset cs {Can Delete} 
::msgcat::mcset cs {Can Edit} 
::msgcat::mcset cs {Can Move} 
::msgcat::mcset cs {Can Rotate} 
::msgcat::mcset cs {Cancelled} 
::msgcat::mcset cs {Cancel} [encoding convertfrom iso8859-2 {Zru¹it}]
::msgcat::mcset cs {Cap} 
::msgcat::mcset cs {Catalog Server} [encoding convertfrom iso8859-2 {Katalogový server}]
::msgcat::mcset cs {Catalog Tool} [encoding convertfrom iso8859-2 {Katalogový nástroj}]
::msgcat::mcset cs {Catalogs} [encoding convertfrom iso8859-2 {Katalogy}]
::msgcat::mcset cs {Catalog} [encoding convertfrom iso8859-2 {Katalog}]
::msgcat::mcset cs {Catrom} 
::msgcat::mcset cs {Cat} 
::msgcat::mcset cs {Center Image} [encoding convertfrom iso8859-2 {Vycentruj obrázek}]
::msgcat::mcset cs {Center Non-modal Dialogs} 
::msgcat::mcset cs {Center} [encoding convertfrom iso8859-2 {Støed}]
::msgcat::mcset cs {Centroid Parameters} [encoding convertfrom iso8859-2 {Parametry centroidu}]
::msgcat::mcset cs {Centroid} [encoding convertfrom iso8859-2 {Vystøedit}]
::msgcat::mcset cs {Circle} [encoding convertfrom iso8859-2 {Kru¾nice}]
::msgcat::mcset cs {Clear All} [encoding convertfrom iso8859-2 {Vyma¾ v¹e}]
::msgcat::mcset cs {Clear Analysis Commands} [encoding convertfrom iso8859-2 {Vyma¾ analytické pøíkazy}]
::msgcat::mcset cs {Clear Cache} 
::msgcat::mcset cs {Clear Data} 
::msgcat::mcset cs {Clear External Analysis Commands?} 
::msgcat::mcset cs {Clear Filter} [encoding convertfrom iso8859-2 {Vynuluvoat filtr}]
::msgcat::mcset cs {Clear Frame} [encoding convertfrom iso8859-2 {Vyèistit snímek}]
::msgcat::mcset cs {Clear Preferences?} [encoding convertfrom iso8859-2 {Smazat nastavení?}]
::msgcat::mcset cs {Clear Preferences} [encoding convertfrom iso8859-2 {Smazat nastavení}]
::msgcat::mcset cs {Clear} [encoding convertfrom iso8859-2 {Vyèistit}]
::msgcat::mcset cs {Click to Center} [encoding convertfrom iso8859-2 {Klinout na centrování}]
::msgcat::mcset cs {Close} [encoding convertfrom iso8859-2 {Zavøít}]
::msgcat::mcset cs {Colorbar Size} [encoding convertfrom iso8859-2 {Velikost colorbaru}]
::msgcat::mcset cs {Colorbar} [encoding convertfrom iso8859-2 {©kálování barev}]
::msgcat::mcset cs {Colormap Parameters} 
::msgcat::mcset cs {Colormap} 
::msgcat::mcset cs {Color} [encoding convertfrom iso8859-2 {Barva}]
::msgcat::mcset cs {Columns} [encoding convertfrom iso8859-2 {Sloupce}]
::msgcat::mcset cs {Column} [encoding convertfrom iso8859-2 {Sploupec}]
::msgcat::mcset cs {Comets} 
::msgcat::mcset cs {Command not allowed} 
::msgcat::mcset cs {Command} [encoding convertfrom iso8859-2 {Pøíkaz}]
::msgcat::mcset cs {Compass} [encoding convertfrom iso8859-2 {Kompas}]
::msgcat::mcset cs {Composite Region} [encoding convertfrom iso8859-2 {Spojit oblasti}]
::msgcat::mcset cs {Composite} 
::msgcat::mcset cs {Compression} [encoding convertfrom iso8859-2 {Komprese}]
::msgcat::mcset cs {Configure} [encoding convertfrom iso8859-2 {Konfigurace}]
::msgcat::mcset cs {Connect Directly} 
::msgcat::mcset cs {Connect SAMP} 
::msgcat::mcset cs {Connect Using Web Proxy} 
::msgcat::mcset cs {Connect} [encoding convertfrom iso8859-2 {Pøipoji}]
::msgcat::mcset cs {Console} 
::msgcat::mcset cs {Contacting Image Server} 
::msgcat::mcset cs {Contour Parameters} [encoding convertfrom iso8859-2 {Parametry obrysu}]
::msgcat::mcset cs {Contour Paste} 
::msgcat::mcset cs {Contour Save} 
::msgcat::mcset cs {Contours} [encoding convertfrom iso8859-2 {Obrysy}]
::msgcat::mcset cs {Contour} [encoding convertfrom iso8859-2 {Obrys}]
::msgcat::mcset cs {Contrast} [encoding convertfrom iso8859-2 {Kontrast}]
::msgcat::mcset cs {Convert to Polygons} [encoding convertfrom iso8859-2 {Zmìnit na obdélníky}]
::msgcat::mcset cs {Coordinate Grid Parameters} [encoding convertfrom iso8859-2 {Nastavení møí¾ky}]
::msgcat::mcset cs {Coordinate Grid} [encoding convertfrom iso8859-2 {Møí¾ka}]
::msgcat::mcset cs {Coordinate System} [encoding convertfrom iso8859-2 {Systém koordinátù}]
::msgcat::mcset cs {Coordinates} [encoding convertfrom iso8859-2 {Koordináty}] 
::msgcat::mcset cs {Coordinate} [encoding convertfrom iso8859-2 {Koordinát}]
::msgcat::mcset cs {Copy Contours} 
::msgcat::mcset cs {Copy to Regions} [encoding convertfrom iso8859-2 {Kopíruj do oblastí}]
::msgcat::mcset cs {Copy} [encoding convertfrom iso8859-2 {Kopíruj}]
::msgcat::mcset cs {Create Movie} [encoding convertfrom iso8859-2 {Vytvoøit video}]
::msgcat::mcset cs {Create New Frame on Download} 
::msgcat::mcset cs {Create} [encoding convertfrom iso8859-2 {Vytvoøit}]
::msgcat::mcset cs {Crop Parameters} [encoding convertfrom iso8859-2 {Parametry oøezávání}]
::msgcat::mcset cs {Crop} [encoding convertfrom iso8859-2 {Výøez}]
::msgcat::mcset cs {Crosshair Parameters} 
::msgcat::mcset cs {Crosshair To} [encoding convertfrom iso8859-2 {Zamìøovaè na}]
::msgcat::mcset cs {Crosshair} [encoding convertfrom iso8859-2 {Zamìøovaè}]
::msgcat::mcset cs {Cross} [encoding convertfrom iso8859-2 {Køí¾}]
::msgcat::mcset cs {Cubehelix} 
::msgcat::mcset cs {Cube} [encoding convertfrom iso8859-2 {Krychle}]
::msgcat::mcset cs {Cubic} 
::msgcat::mcset cs {Current Frame} [encoding convertfrom iso8859-2 {Souèasný obrázek}]
::msgcat::mcset cs {Current Range} [encoding convertfrom iso8859-2 {Souèasný rozsah}]
::msgcat::mcset cs {Current} [encoding convertfrom iso8859-2 {Souèasný}]
::msgcat::mcset cs {Cursor} [encoding convertfrom iso8859-2 {Kurzor}]
::msgcat::mcset cs {Cut} [encoding convertfrom iso8859-2 {Vyøíznout}]
::msgcat::mcset cs {Cyan} [encoding convertfrom iso8859-2 {Azurová}]
::msgcat::mcset cs {DMS} 
::msgcat::mcset cs {DPI} 
::msgcat::mcset cs {DS9 has detected a newer version of a backup file and therefore will not process this file.} [encoding convertfrom iso8859-2 {Program na¹el novou verzi zálo¾ního souboru a tedy tento soubor nebude zpracován.}]
::msgcat::mcset cs {DS9 has detected a newer version of a preferences file.} 
::msgcat::mcset cs {DS9 has detected an older backup file, do you wish to continue?} [encoding convertfrom iso8859-2 {DS9 detekovala starou verzi zálo¾ního souboru, chcete pokraèovat?}]
::msgcat::mcset cs {DS9 has detected an older preferences file, do you wish to update?} [encoding convertfrom iso8859-2 {Starý konfiguraèní soubor, chcete ho zaktualizovat?}]
::msgcat::mcset cs {DS9 will complete the initialization process} [encoding convertfrom iso8859-2 {DS9 dokonèí inticializaèní proces}]
::msgcat::mcset cs {Dash} 
::msgcat::mcset cs {Data Format} [encoding convertfrom iso8859-2 {Formát dat}]
::msgcat::mcset cs {Dataset Name} 
::msgcat::mcset cs {Dataset} [encoding convertfrom iso8859-2 {Soubor dat}]
::msgcat::mcset cs {Data} 
::msgcat::mcset cs {Decrease} [encoding convertfrom iso8859-2 {Zmen¹it}]
::msgcat::mcset cs {Default All Files} [encoding convertfrom iso8859-2 {Vychozí pro v¹echny soubory}]
::msgcat::mcset cs {Default Format} 
::msgcat::mcset cs {Default Length} 
::msgcat::mcset cs {Default} [encoding convertfrom iso8859-2 {Výchozí}]
::msgcat::mcset cs {Degrees} [encoding convertfrom iso8859-2 {Stupnì}]
::msgcat::mcset cs {Delete All Frames?} [encoding convertfrom iso8859-2 {Smazat v¹echny snímky?}]
::msgcat::mcset cs {Delete All Frames} [encoding convertfrom iso8859-2 {Smazat v¹echny snímky}]
::msgcat::mcset cs {Delete All Groups?} [encoding convertfrom iso8859-2 {Smazat v¹echny skupiny?}]
::msgcat::mcset cs {Delete All Groups} [encoding convertfrom iso8859-2 {Smazat v¹echny skupiny}]
::msgcat::mcset cs {Delete All Regions?} [encoding convertfrom iso8859-2 {Smazat v¹echny oblasti?}]
::msgcat::mcset cs {Delete All Regions} [encoding convertfrom iso8859-2 {Smazat v¹echny oblasti}]
::msgcat::mcset cs {Delete All} [encoding convertfrom iso8859-2 {Smazat v¹e}]
::msgcat::mcset cs {Delete Color Tags} 
::msgcat::mcset cs {Delete Frame} [encoding convertfrom iso8859-2 {Smazat snímek}]
::msgcat::mcset cs {Delete Group} [encoding convertfrom iso8859-2 {Smazat skupiny}]
::msgcat::mcset cs {Delete Selected Regions} [encoding convertfrom iso8859-2 {Smazat vybrané oblasti}]
::msgcat::mcset cs {Delete} [encoding convertfrom iso8859-2 {Smazat}]
::msgcat::mcset cs {Depth} [encoding convertfrom iso8859-2 {Hloubka}]
::msgcat::mcset cs {Detector} [encoding convertfrom iso8859-2 {Detektor}]
::msgcat::mcset cs {Dialog Box} [encoding convertfrom iso8859-2 {Dialogové okno}]
::msgcat::mcset cs {Diameter} 
::msgcat::mcset cs {Diamond} [encoding convertfrom iso8859-2 {Diamant}]
::msgcat::mcset cs {Dimension} [encoding convertfrom iso8859-2 {Rozmìr}]
::msgcat::mcset cs {Direction} 
::msgcat::mcset cs {Disconnect} 
::msgcat::mcset cs {Display Header} 
::msgcat::mcset cs {Display Size} [encoding convertfrom iso8859-2 {Velikost displeje}]
::msgcat::mcset cs {Dissolve} 
::msgcat::mcset cs {Distance} [encoding convertfrom iso8859-2 {Vzdálenost}]
::msgcat::mcset cs {Done} 
::msgcat::mcset cs {Download Colormap} 
::msgcat::mcset cs {Download VOTABLE format if available} 
::msgcat::mcset cs {Drag to Center} 
::msgcat::mcset cs {Duplicate Data} 
::msgcat::mcset cs {East} [encoding convertfrom iso8859-2 {Východ}]
::msgcat::mcset cs {Ecliptic} [encoding convertfrom iso8859-2 {Ekliptikální}]
::msgcat::mcset cs {Edit Group Name} 
::msgcat::mcset cs {Edit} [encoding convertfrom iso8859-2 {Úpravy}]
::msgcat::mcset cs {Elevation} 
::msgcat::mcset cs {Ellipse Annulus} 
::msgcat::mcset cs {Ellipse Panda} 
::msgcat::mcset cs {Ellipse} [encoding convertfrom iso8859-2 {Elipsa}]
::msgcat::mcset cs {Elliptical Annulus} 
::msgcat::mcset cs {Elliptical Gaussian} 
::msgcat::mcset cs {Elliptical Panda} 
::msgcat::mcset cs {Enable Confirmation Dialogs} 
::msgcat::mcset cs {Enable} [encoding convertfrom iso8859-2 {Povolit}]
::msgcat::mcset cs {End} [encoding convertfrom iso8859-2 {Ukonèit}]
::msgcat::mcset cs {Enter Color} [encoding convertfrom iso8859-2 {Zadejte barvu}] 
::msgcat::mcset cs {Enter Font Size} 
::msgcat::mcset cs {Enter Group Name} 
::msgcat::mcset cs {Enter Search Expression} 
::msgcat::mcset cs {Enter URL} 
::msgcat::mcset cs {Entry} 
::msgcat::mcset cs {Equal Area} 
::msgcat::mcset cs {Equal Distance} 
::msgcat::mcset cs {Equal Spacing} 
::msgcat::mcset cs {Equal Value} 
::msgcat::mcset cs {Error code was returned} 
::msgcat::mcset cs {Error} 
::msgcat::mcset cs {Examine Frame} 
::msgcat::mcset cs {Examine} [encoding convertfrom iso8859-2 {Prozkoumat}]
::msgcat::mcset cs {Exam} 
::msgcat::mcset cs {Exclude} 
::msgcat::mcset cs {Exit} [encoding convertfrom iso8859-2 {Ukonèi}]
::msgcat::mcset cs {Export Array} 
::msgcat::mcset cs {Export} [encoding convertfrom iso8859-2 {Ulo¾it jako}]
::msgcat::mcset cs {Extention} 
::msgcat::mcset cs {Exterior Axes} 
::msgcat::mcset cs {Exterior Numerics} 
::msgcat::mcset cs {FAQ} 
::msgcat::mcset cs {FK4} 
::msgcat::mcset cs {FK5} 
::msgcat::mcset cs {Factor} [encoding convertfrom iso8859-2 {Faktor}]
::msgcat::mcset cs {File not Found or Unable to load FITS data MIME type} [encoding convertfrom iso8859-2 {Soubor nenalezen nebo není mo¾né nahrát daný FITS MIME typ}]
::msgcat::mcset cs {Filename} [encoding convertfrom iso8859-2 {Název souboru}]
::msgcat::mcset cs {File} [encoding convertfrom iso8859-2 {Soubor}]
::msgcat::mcset cs {Fill} 
::msgcat::mcset cs {Filter} [encoding convertfrom iso8859-2 {Filtr}]
::msgcat::mcset cs {Find Next} [encoding convertfrom iso8859-2 {Najít dal¹í}]
::msgcat::mcset cs {Find} [encoding convertfrom iso8859-2 {Najít}]
::msgcat::mcset cs {First Frame} [encoding convertfrom iso8859-2 {První snímek}]
::msgcat::mcset cs {First} [encoding convertfrom iso8859-2 {První}]
::msgcat::mcset cs {Fits} 
::msgcat::mcset cs {Fixed in Size} 
::msgcat::mcset cs {Flat} 
::msgcat::mcset cs {Flip} 
::msgcat::mcset cs {Font} [encoding convertfrom iso8859-2 {Znak}]
::msgcat::mcset cs {For more information, use --help} [encoding convertfrom iso8859-2 {Pro více informací, pou¾ijte --help}]
::msgcat::mcset cs {Format} [encoding convertfrom iso8859-2 {Formát}]
::msgcat::mcset cs {Forward} [encoding convertfrom iso8859-2 {Vpøed}]
::msgcat::mcset cs {Found} [encoding convertfrom iso8859-2 {Nalezeno}]
::msgcat::mcset cs {Frame Information} [encoding convertfrom iso8859-2 {Informace o snímku}]
::msgcat::mcset cs {Frame Parameters} [encoding convertfrom iso8859-2 {Parametry snímku}]
::msgcat::mcset cs {Frames} [encoding convertfrom iso8859-2 {Snímky}]
::msgcat::mcset cs {Frame} [encoding convertfrom iso8859-2 {Snímek}]
::msgcat::mcset cs {From} [encoding convertfrom iso8859-2 {Od}]
::msgcat::mcset cs {Front} [encoding convertfrom iso8859-2 {První}]
::msgcat::mcset cs {Full Range} [encoding convertfrom iso8859-2 {Plný rozsah}]
::msgcat::mcset cs {Function} [encoding convertfrom iso8859-2 {Funkce}]
::msgcat::mcset cs {GUI Font} [encoding convertfrom iso8859-2 {Font GUI}]
::msgcat::mcset cs {Galactic} [encoding convertfrom iso8859-2 {Galaktické}]
::msgcat::mcset cs {Gap} 
::msgcat::mcset cs {Gaussian} 
::msgcat::mcset cs {General} 
::msgcat::mcset cs {Generate} [encoding convertfrom iso8859-2 {Vygeneruj}]
::msgcat::mcset cs {Generating Regions} 
::msgcat::mcset cs {Get Information} [encoding convertfrom iso8859-2 {Získej informace}]
::msgcat::mcset cs {Gist} 
::msgcat::mcset cs {Global Properties} 
::msgcat::mcset cs {Global} 
::msgcat::mcset cs {Goto Frame} [encoding convertfrom iso8859-2 {Bì¾ na snímek}]
::msgcat::mcset cs {Graph Horz} 
::msgcat::mcset cs {Graph Parameters} 
::msgcat::mcset cs {Graph Vert} 
::msgcat::mcset cs {Graphics} 
::msgcat::mcset cs {Graphs} [encoding convertfrom iso8859-2 {Grafy}]
::msgcat::mcset cs {Graph} [encoding convertfrom iso8859-2 {Graf}]
::msgcat::mcset cs {Grayscale} [encoding convertfrom iso8859-2 {Stupnì ¹edi}]
::msgcat::mcset cs {Green} [encoding convertfrom iso8859-2 {Zelená}]
::msgcat::mcset cs {Grid Gap} 
::msgcat::mcset cs {Grid} [encoding convertfrom iso8859-2 {Møí¾ka}]
::msgcat::mcset cs {Groove} 
::msgcat::mcset cs {Groups} [encoding convertfrom iso8859-2 {Skupiny}]
::msgcat::mcset cs {HMS} 
::msgcat::mcset cs {HTTP} 
::msgcat::mcset cs {Header} [encoding convertfrom iso8859-2 {Hlavièka}]
::msgcat::mcset cs {Height} [encoding convertfrom iso8859-2 {Vý¹ka}]
::msgcat::mcset cs {Help Desk} [encoding convertfrom iso8859-2 {Podpora}]
::msgcat::mcset cs {Help Me Choose} 
::msgcat::mcset cs {Help} [encoding convertfrom iso8859-2 {Nápovìda}]
::msgcat::mcset cs {Hide All} [encoding convertfrom iso8859-2 {Skryj v¹echny}]
::msgcat::mcset cs {Highlite} 
::msgcat::mcset cs {High} [encoding convertfrom iso8859-2 {Vysoký}]
::msgcat::mcset cs {Histogram Equalization} [encoding convertfrom iso8859-2 {Vyrovnání histogramu}]
::msgcat::mcset cs {Histogram} 
::msgcat::mcset cs {Horizontal Graph} [encoding convertfrom iso8859-2 {Horizontální graf}]
::msgcat::mcset cs {Horizontal Layout} [encoding convertfrom iso8859-2 {Horizontální rozlo¾ení}]
::msgcat::mcset cs {Horizontal} 
::msgcat::mcset cs {IAU Location Code} 
::msgcat::mcset cs {ICRS} 
::msgcat::mcset cs {Identification} 
::msgcat::mcset cs {If} 
::msgcat::mcset cs {Image Servers} 
::msgcat::mcset cs {Image} [encoding convertfrom iso8859-2 {Obrázek}]
::msgcat::mcset cs {Import Array} 
::msgcat::mcset cs {Import} 
::msgcat::mcset cs {Include} 
::msgcat::mcset cs {Increase} 
::msgcat::mcset cs {Information Panel} [encoding convertfrom iso8859-2 {Informaèní panel}]
::msgcat::mcset cs {Information} [encoding convertfrom iso8859-2 {Detaily}]
::msgcat::mcset cs {Initialize XPA} 
::msgcat::mcset cs {Inner} 
::msgcat::mcset cs {Instrument FOV} [encoding convertfrom iso8859-2 {Zorné pole dalekohledù}]
::msgcat::mcset cs {Interior Axes} 
::msgcat::mcset cs {Interior Numerics} 
::msgcat::mcset cs {Internal Parse Error} 
::msgcat::mcset cs {Interval} 
::msgcat::mcset cs {Invalid Column Name} 
::msgcat::mcset cs {Invalid WCS} 
::msgcat::mcset cs {Invalid formated multipart/mixed mime type message} 
::msgcat::mcset cs {Invert Colormap} 
::msgcat::mcset cs {Invert Selection} [encoding convertfrom iso8859-2 {Vybrat doplnìk}]
::msgcat::mcset cs {Invert} [encoding convertfrom iso8859-2 {Pøeklopit}]
::msgcat::mcset cs {Italic} [encoding convertfrom iso8859-2 {Kurzíva}]
::msgcat::mcset cs {Items Found} 
::msgcat::mcset cs {Iteration} 
::msgcat::mcset cs {JPEG Quality Factor} [encoding convertfrom iso8859-2 {Kvalita JPEGu}]
::msgcat::mcset cs {Keep-Alive} 
::msgcat::mcset cs {Keyboard} [encoding convertfrom iso8859-2 {Klávesnice}]
::msgcat::mcset cs {Keyword} 
::msgcat::mcset cs {Labels} [encoding convertfrom iso8859-2 {Oznaèení}]
::msgcat::mcset cs {Label} [encoding convertfrom iso8859-2 {Oznaèení}]
::msgcat::mcset cs {Landscape} [encoding convertfrom iso8859-2 {Horizontálnì}]
::msgcat::mcset cs {Language} [encoding convertfrom iso8859-2 {Jazyk}]
::msgcat::mcset cs {Last Frame} [encoding convertfrom iso8859-2 {Poslední snímek}]
::msgcat::mcset cs {Last} [encoding convertfrom iso8859-2 {Poslední}]
::msgcat::mcset cs {Layout Horz} 
::msgcat::mcset cs {Layout Vert} 
::msgcat::mcset cs {Layout} [encoding convertfrom iso8859-2 {Rozvr¾ení}]
::msgcat::mcset cs {Left} [encoding convertfrom iso8859-2 {Vlevo}]
::msgcat::mcset cs {Legal} 
::msgcat::mcset cs {Legend Title} 
::msgcat::mcset cs {Legend} 
::msgcat::mcset cs {Length} [encoding convertfrom iso8859-2 {Délka}]
::msgcat::mcset cs {Letter} 
::msgcat::mcset cs {Levels} [encoding convertfrom iso8859-2 {Úrovnì}]
::msgcat::mcset cs {Level} [encoding convertfrom iso8859-2 {Úroveò}]
::msgcat::mcset cs {Limits} 
::msgcat::mcset cs {Line Plot Tool} 
::msgcat::mcset cs {Linear} [encoding convertfrom iso8859-2 {Linární}]
::msgcat::mcset cs {Line} 
::msgcat::mcset cs {List Data} 
::msgcat::mcset cs {List Regions} [encoding convertfrom iso8859-2 {Seznam oblastí}]
::msgcat::mcset cs {List} [encoding convertfrom iso8859-2 {Seznam}]
::msgcat::mcset cs {Load Analysis Commands} [encoding convertfrom iso8859-2 {Nahrát analytické pøíkazy}]
::msgcat::mcset cs {Load Color Tags} 
::msgcat::mcset cs {Load Colormap} 
::msgcat::mcset cs {Load Configuration} [encoding convertfrom iso8859-2 {Nahraj konfiguraci}]
::msgcat::mcset cs {Load Contour Levels} 
::msgcat::mcset cs {Load Contours} 
::msgcat::mcset cs {Load Contrast/Bias} 
::msgcat::mcset cs {Load Data} 
::msgcat::mcset cs {Load Mosaic} 
::msgcat::mcset cs {Load Regions} [encoding convertfrom iso8859-2 {Nahrát oblasti}]
::msgcat::mcset cs {Load Template} 
::msgcat::mcset cs {Load into All Frames} 
::msgcat::mcset cs {Load into Current Frame} 
::msgcat::mcset cs {Loading Catalog} 
::msgcat::mcset cs {Loading} 
::msgcat::mcset cs {Load} [encoding convertfrom iso8859-2 {Nahrát}]
::msgcat::mcset cs {Local} 
::msgcat::mcset cs {Lock Axes} 
::msgcat::mcset cs {Lock Bin} 
::msgcat::mcset cs {Lock Color} 
::msgcat::mcset cs {Lock Crop Amplifier} 
::msgcat::mcset cs {Lock Crop Detector} 
::msgcat::mcset cs {Lock Crop Image} 
::msgcat::mcset cs {Lock Crop None} 
::msgcat::mcset cs {Lock Crop Physical} 
::msgcat::mcset cs {Lock Crop WCS} 
::msgcat::mcset cs {Lock Crosshair Amplifier} 
::msgcat::mcset cs {Lock Crosshair Detector} 
::msgcat::mcset cs {Lock Crosshair Image} 
::msgcat::mcset cs {Lock Crosshair None} 
::msgcat::mcset cs {Lock Crosshair Physical} 
::msgcat::mcset cs {Lock Crosshair WCS} 
::msgcat::mcset cs {Lock Frame Amplifier} 
::msgcat::mcset cs {Lock Frame Detector} 
::msgcat::mcset cs {Lock Frame Image} 
::msgcat::mcset cs {Lock Frame None} 
::msgcat::mcset cs {Lock Frame Physical} 
::msgcat::mcset cs {Lock Frame WCS} 
::msgcat::mcset cs {Lock Limits} 
::msgcat::mcset cs {Lock Scale} 
::msgcat::mcset cs {Lock Slice Image} 
::msgcat::mcset cs {Lock Slice None} 
::msgcat::mcset cs {Lock Slice WCS} 
::msgcat::mcset cs {Lock Smooth} 
::msgcat::mcset cs {Lock} [encoding convertfrom iso8859-2 {Synchronizovat}]
::msgcat::mcset cs {Log Exponent} [encoding convertfrom iso8859-2 {Numerus logaritmu}]
::msgcat::mcset cs {Log} [encoding convertfrom iso8859-2 {Logaritmické}]
::msgcat::mcset cs {Low High} [encoding convertfrom iso8859-2 {Nejmen¹í Nejvìt¹í}]
::msgcat::mcset cs {Lower Left Back} 
::msgcat::mcset cs {Lower Left Front} 
::msgcat::mcset cs {Lower Right Back} 
::msgcat::mcset cs {Lower Right Front} 
::msgcat::mcset cs {Low} 
::msgcat::mcset cs {MIP} 
::msgcat::mcset cs {Magenta} 
::msgcat::mcset cs {Magnification} 
::msgcat::mcset cs {Magnifier} [encoding convertfrom iso8859-2 {Zvìt¹ovaè}]
::msgcat::mcset cs {Major Radius} 
::msgcat::mcset cs {Major Sigma} 
::msgcat::mcset cs {Major} 
::msgcat::mcset cs {Manual} 
::msgcat::mcset cs {Mask Parameters} [encoding convertfrom iso8859-2 {Nastavení masky}]
::msgcat::mcset cs {Match Axes} 
::msgcat::mcset cs {Match Bin} [encoding convertfrom iso8859-2 {Zarovnat bin}]
::msgcat::mcset cs {Match Catalog requires at least 1 row per catalog} 
::msgcat::mcset cs {Match Color} [encoding convertfrom iso8859-2 {Sladit barvu}]
::msgcat::mcset cs {Match Crop Amplifier} 
::msgcat::mcset cs {Match Crop Detector} 
::msgcat::mcset cs {Match Crop Image} 
::msgcat::mcset cs {Match Crop Physical} 
::msgcat::mcset cs {Match Crop WCS} 
::msgcat::mcset cs {Match Crosshair Amplifier} 
::msgcat::mcset cs {Match Crosshair Detector} 
::msgcat::mcset cs {Match Crosshair Image} 
::msgcat::mcset cs {Match Crosshair Physical} 
::msgcat::mcset cs {Match Crosshair WCS} 
::msgcat::mcset cs {Match Frame Amplifier} 
::msgcat::mcset cs {Match Frame Detector} 
::msgcat::mcset cs {Match Frame Image} 
::msgcat::mcset cs {Match Frame Physical} 
::msgcat::mcset cs {Match Frame WCS} 
::msgcat::mcset cs {Match Limits} 
::msgcat::mcset cs {Match Scale} [encoding convertfrom iso8859-2 {Zarovnat ¹kálování}]
::msgcat::mcset cs {Match Slice Image} 
::msgcat::mcset cs {Match Slice WCS} 
::msgcat::mcset cs {Match Smooth} 
::msgcat::mcset cs {Match} [encoding convertfrom iso8859-2 {Zarovnat}]
::msgcat::mcset cs {Math Function} 
::msgcat::mcset cs {Matplotlib} 
::msgcat::mcset cs {Max Rows} 
::msgcat::mcset cs {Maximum} 
::msgcat::mcset cs {Max} 
::msgcat::mcset cs {Menus and Buttons} 
::msgcat::mcset cs {Menu} [encoding convertfrom iso8859-2 {Nabídka}]
::msgcat::mcset cs {Message Log} 
::msgcat::mcset cs {Method} 
::msgcat::mcset cs {Min Max Parameters} 
::msgcat::mcset cs {Min Max} [encoding convertfrom iso8859-2 {Minimum Maximum}]
::msgcat::mcset cs {Minimum} 
::msgcat::mcset cs {Minor Radius} 
::msgcat::mcset cs {Minor Sigma} 
::msgcat::mcset cs {Minor} 
::msgcat::mcset cs {Minutes} 
::msgcat::mcset cs {Min} 
::msgcat::mcset cs {Mission} 
::msgcat::mcset cs {Mode} 
::msgcat::mcset cs {Mosaic IRAF Segment} 
::msgcat::mcset cs {Mosaic IRAF} 
::msgcat::mcset cs {Mosaic WCS Segment} 
::msgcat::mcset cs {Mosaic WCS} 
::msgcat::mcset cs {Mosaic WFPC2} 
::msgcat::mcset cs {Mosaic} 
::msgcat::mcset cs {Mouse Click Epsilon} 
::msgcat::mcset cs {Mouse Wheel Bin} 
::msgcat::mcset cs {Mouse Wheel Zoom} 
::msgcat::mcset cs {Move Back} 
::msgcat::mcset cs {Move First} 
::msgcat::mcset cs {Move Forward} 
::msgcat::mcset cs {Move Frame} [encoding convertfrom iso8859-2 {Pøesunout snímek}]
::msgcat::mcset cs {Move Last} 
::msgcat::mcset cs {Move to Back} [encoding convertfrom iso8859-2 {Pøesunout vzad}]
::msgcat::mcset cs {Move to Front} [encoding convertfrom iso8859-2 {Pøesunout vpøed}]
::msgcat::mcset cs {Movie} 
::msgcat::mcset cs {Multiple Extension Cube} 
::msgcat::mcset cs {Multiple Extension Frames} 
::msgcat::mcset cs {Multiple WCS} [encoding convertfrom iso8859-2 {Multi WCS}]
::msgcat::mcset cs {NRRD} 
::msgcat::mcset cs {Name Resolution} [encoding convertfrom iso8859-2 {Vyhledání objektu}]
::msgcat::mcset cs {Name Server} 
::msgcat::mcset cs {Name or Designation} 
::msgcat::mcset cs {Name} [encoding convertfrom iso8859-2 {Název}]
::msgcat::mcset cs {Native Dialog} 
::msgcat::mcset cs {New Features} [encoding convertfrom iso8859-2 {Nové vlasnosti}]
::msgcat::mcset cs {New Frame 3D} [encoding convertfrom iso8859-2 {Nový 3D snímek}]
::msgcat::mcset cs {New Frame RGB} [encoding convertfrom iso8859-2 {Nový barevný RGB snímek}]
::msgcat::mcset cs {New Frame each Time} 
::msgcat::mcset cs {New Frame} [encoding convertfrom iso8859-2 {Nový snímek}]
::msgcat::mcset cs {New Group} [encoding convertfrom iso8859-2 {Nová skupina}]
::msgcat::mcset cs {New} [encoding convertfrom iso8859-2 {Nový}]
::msgcat::mcset cs {Next Frame} [encoding convertfrom iso8859-2 {Dal¹í snímek}]
::msgcat::mcset cs {Next} [encoding convertfrom iso8859-2 {Dal¹í}]
::msgcat::mcset cs {No Catalog specified} 
::msgcat::mcset cs {No Data Available} 
::msgcat::mcset cs {No Items Found} 
::msgcat::mcset cs {No current frame} 
::msgcat::mcset cs {Non-zero} 
::msgcat::mcset cs {None} [encoding convertfrom iso8859-2 {Nic}]
::msgcat::mcset cs {Normal} 
::msgcat::mcset cs {North} [encoding convertfrom iso8859-2 {Sever}]
::msgcat::mcset cs {Not Found} 
::msgcat::mcset cs {Not Supported} 
::msgcat::mcset cs {Number of Samples} 
::msgcat::mcset cs {Number of Threads} 
::msgcat::mcset cs {Number of Ticks} 
::msgcat::mcset cs {Number} [encoding convertfrom iso8859-2 {Èíslo}]
::msgcat::mcset cs {Numerics} 
::msgcat::mcset cs {OK} [encoding convertfrom iso8859-2 {Budi¾}] 
::msgcat::mcset cs {Object} [encoding convertfrom iso8859-2 {Objekt}]
::msgcat::mcset cs {Open File} [encoding convertfrom iso8859-2 {Otevøít soubor}]
::msgcat::mcset cs {Open TCL Console} [encoding convertfrom iso8859-2 {Otevøít konzoly TCL}]
::msgcat::mcset cs {Open URL} [encoding convertfrom iso8859-2 {Otevøít URL}]
::msgcat::mcset cs {Open as} 
::msgcat::mcset cs {Open} [encoding convertfrom iso8859-2 {Otevøít}]
::msgcat::mcset cs {Operator} 
::msgcat::mcset cs {Orientation} 
::msgcat::mcset cs {Origin} 
::msgcat::mcset cs {Oscillate} 
::msgcat::mcset cs {Other Color} 
::msgcat::mcset cs {Other Font Size} 
::msgcat::mcset cs {Other} 
::msgcat::mcset cs {Outer} 
::msgcat::mcset cs {Overlap} 
::msgcat::mcset cs {PS Page Setup} 
::msgcat::mcset cs {PS Print} 
::msgcat::mcset cs {Page Setup} [encoding convertfrom iso8859-2 {Vlastnosti tisku}]
::msgcat::mcset cs {Page Source} 
::msgcat::mcset cs {Pan To} 
::msgcat::mcset cs {Pan Zoom Rotate Parameters} [encoding convertfrom iso8859-2 {Parametry prohlí¾ení a zvìt¹ení}]
::msgcat::mcset cs {Pan Zoom} 
::msgcat::mcset cs {Pan then Zoom} 
::msgcat::mcset cs {Panda} 
::msgcat::mcset cs {Panner} [encoding convertfrom iso8859-2 {Náhled snímku}]
::msgcat::mcset cs {Pan} [encoding convertfrom iso8859-2 {Posun}] 
::msgcat::mcset cs {Parameters} 
::msgcat::mcset cs {Password} 
::msgcat::mcset cs {Paste Contours} 
::msgcat::mcset cs {Paste} [encoding convertfrom iso8859-2 {Vlo¾it}]
::msgcat::mcset cs {Physical} [encoding convertfrom iso8859-2 {Fyzické}]
::msgcat::mcset cs {Pixel Distribution} 
::msgcat::mcset cs {Pixel Size} 
::msgcat::mcset cs {Pixel Table} [encoding convertfrom iso8859-2 {Pixel tabulka}]
::msgcat::mcset cs {Pixels} 
::msgcat::mcset cs {Planets} 
::msgcat::mcset cs {Play} 
::msgcat::mcset cs {Please Select a Region} 
::msgcat::mcset cs {Please change the file's permission to disable other users write access. Use anyway?} 
::msgcat::mcset cs {Please specify width, height, and either name or (ra,dec)} 
::msgcat::mcset cs {Plot 2D} 
::msgcat::mcset cs {Plot 3D} 
::msgcat::mcset cs {Plot Title} 
::msgcat::mcset cs {Plotting Regions} 
::msgcat::mcset cs {Plot} 
::msgcat::mcset cs {Plus} 
::msgcat::mcset cs {Pointer} [encoding convertfrom iso8859-2 {Ukazatel}]
::msgcat::mcset cs {Points} 
::msgcat::mcset cs {Point} 
::msgcat::mcset cs {Polygon} 
::msgcat::mcset cs {Portrait} 
::msgcat::mcset cs {Poster} 
::msgcat::mcset cs {Postscript Page Setup} 
::msgcat::mcset cs {Postscript Print} 
::msgcat::mcset cs {Postscript} 
::msgcat::mcset cs {Power} [encoding convertfrom iso8859-2 {Mocninové}]
::msgcat::mcset cs {Precision} 
::msgcat::mcset cs {Preferences} [encoding convertfrom iso8859-2 {Nastavení}]
::msgcat::mcset cs {Preserve During Load} [encoding convertfrom iso8859-2 {Zachovej pøi otevøení}]
::msgcat::mcset cs {Previous Frame} [encoding convertfrom iso8859-2 {Pøede¹lí snímek}]
::msgcat::mcset cs {Previous} [encoding convertfrom iso8859-2 {Pøedchozí}]
::msgcat::mcset cs {Prev} 
::msgcat::mcset cs {Print Coordinates} 
::msgcat::mcset cs {Print To} 
::msgcat::mcset cs {Printer} 
::msgcat::mcset cs {Print} [encoding convertfrom iso8859-2 {Vytisknout}]
::msgcat::mcset cs {Projection} 
::msgcat::mcset cs {Properties} [encoding convertfrom iso8859-2 {Vlastnosti}]
::msgcat::mcset cs {Property} 
::msgcat::mcset cs {Proxy Host} 
::msgcat::mcset cs {Proxy Port} 
::msgcat::mcset cs {Publication} 
::msgcat::mcset cs {Quadratic} 
::msgcat::mcset cs {RGB Array} 
::msgcat::mcset cs {RGB Cube} 
::msgcat::mcset cs {RGB Image} 
::msgcat::mcset cs {RGB} 
::msgcat::mcset cs {Radial Profile} 
::msgcat::mcset cs {Radial} 
::msgcat::mcset cs {Radius} 
::msgcat::mcset cs {Raised} 
::msgcat::mcset cs {Range} 
::msgcat::mcset cs {Redo} 
::msgcat::mcset cs {Red} 
::msgcat::mcset cs {Reference Manual} [encoding convertfrom iso8859-2 {Seznam pøíkazù}]
::msgcat::mcset cs {Reference} 
::msgcat::mcset cs {Refresh Frame} [encoding convertfrom iso8859-2 {Obnov snímek}]
::msgcat::mcset cs {Refresh} 
::msgcat::mcset cs {Region Parameters} [encoding convertfrom iso8859-2 {Parametry oblastí}]
::msgcat::mcset cs {Region} [encoding convertfrom iso8859-2 {Oblasti}]
::msgcat::mcset cs {Release Notes} [encoding convertfrom iso8859-2 {Informace o vydání}]
::msgcat::mcset cs {Release} 
::msgcat::mcset cs {Relief} 
::msgcat::mcset cs {Reload} 
::msgcat::mcset cs {Render} 
::msgcat::mcset cs {Repeat} 
::msgcat::mcset cs {Reset Colormap} 
::msgcat::mcset cs {Reset Frame} [encoding convertfrom iso8859-2 {Vynulovat nastavení snímku}]
::msgcat::mcset cs {Reset} 
::msgcat::mcset cs {Restore} [encoding convertfrom iso8859-2 {Obnovit}]
::msgcat::mcset cs {Retrieve} 
::msgcat::mcset cs {Return} 
::msgcat::mcset cs {Right} 
::msgcat::mcset cs {Roman} 
::msgcat::mcset cs {Rotate} {Rotovat} 
::msgcat::mcset cs {Rows} 
::msgcat::mcset cs {Row} 
::msgcat::mcset cs {Ruler} 
::msgcat::mcset cs {SAMP Image} 
::msgcat::mcset cs {SAMP Table} 
::msgcat::mcset cs {SAMP: not connected} 
::msgcat::mcset cs {SAMP} 
::msgcat::mcset cs {Sample Increment} 
::msgcat::mcset cs {Sample Parameters} 
::msgcat::mcset cs {Samples per Line} 
::msgcat::mcset cs {Sample} 
::msgcat::mcset cs {Save 3D Movie} 
::msgcat::mcset cs {Save Color Tags} 
::msgcat::mcset cs {Save Colormap} 
::msgcat::mcset cs {Save Configuration} 
::msgcat::mcset cs {Save Contour Levels} 
::msgcat::mcset cs {Save Contours} 
::msgcat::mcset cs {Save Contrast/Bias} 
::msgcat::mcset cs {Save Data} 
::msgcat::mcset cs {Save Image on Download} 
::msgcat::mcset cs {Save Image} [encoding convertfrom iso8859-2 {Ulo¾it snímek}]
::msgcat::mcset cs {Save Regions} [encoding convertfrom iso8859-2 {Ulo¾it oblasti}]
::msgcat::mcset cs {Save Template} [encoding convertfrom iso8859-2 {Ulo¾it ¹ablony}]
::msgcat::mcset cs {Save as} 
::msgcat::mcset cs {Save} [encoding convertfrom iso8859-2 {Ulo¾it}]
::msgcat::mcset cs {Scale Parameters} [encoding convertfrom iso8859-2 {Parametry ¹kálování}]
::msgcat::mcset cs {Scale and Limits} 
::msgcat::mcset cs {Scale} [encoding convertfrom iso8859-2 {©kálování}]
::msgcat::mcset cs {Scan} 
::msgcat::mcset cs {Scatter Plot Tool} 
::msgcat::mcset cs {Scope} 
::msgcat::mcset cs {Search for Catalogs} 
::msgcat::mcset cs {Searching for catalogs} 
::msgcat::mcset cs {Seconds} 
::msgcat::mcset cs {Segment} 
::msgcat::mcset cs {Select All} [encoding convertfrom iso8859-2 {Vybrat v¹echny}]
::msgcat::mcset cs {Select Coordinate System } 
::msgcat::mcset cs {Select None} [encoding convertfrom iso8859-2 {Zru¹it výbìr}]
::msgcat::mcset cs {Select} 
::msgcat::mcset cs {Send} 
::msgcat::mcset cs {Server} 
::msgcat::mcset cs {Sexagesimal} [encoding convertfrom iso8859-2 {©edesátkové}]
::msgcat::mcset cs {Shape} [encoding convertfrom iso8859-2 {Tvar}]
::msgcat::mcset cs {Show All} [encoding convertfrom iso8859-2 {Zobrazit v¹e}]
::msgcat::mcset cs {Show Command} 
::msgcat::mcset cs {Show Compass} 
::msgcat::mcset cs {Show Grid} 
::msgcat::mcset cs {Show Text} 
::msgcat::mcset cs {Show/Hide Frames} [encoding convertfrom iso8859-2 {Zobrazit/skrýt snímky}]
::msgcat::mcset cs {Show} 
::msgcat::mcset cs {Simple Cross} 
::msgcat::mcset cs {Simple Plus} 
::msgcat::mcset cs {Single Frame} [encoding convertfrom iso8859-2 {Jeden snímek}]
::msgcat::mcset cs {Single} [encoding convertfrom iso8859-2 {jeden}]
::msgcat::mcset cs {Sites} 
::msgcat::mcset cs {Size/Radius} 
::msgcat::mcset cs {Size} 
::msgcat::mcset cs {Skip First} 
::msgcat::mcset cs {Slice} 
::msgcat::mcset cs {Smooth Parameters} [encoding convertfrom iso8859-2 {Nastavení vyhlazení}]
::msgcat::mcset cs {Smoothness} 
::msgcat::mcset cs {Smooth} [encoding convertfrom iso8859-2 {Vyhlazení}]
::msgcat::mcset cs {Solid} 
::msgcat::mcset cs {Sorry, DS9 does not support} 
::msgcat::mcset cs {Sorry, DS9 requires a Truecolor8, Truecolor16, Truecolor24 visual be available} 
::msgcat::mcset cs {Sort} 
::msgcat::mcset cs {Source TCL} 
::msgcat::mcset cs {Source} 
::msgcat::mcset cs {Space Equal Distance} 
::msgcat::mcset cs {Space Equal Value} 
::msgcat::mcset cs {Spacing} 
::msgcat::mcset cs {Sqrt} 
::msgcat::mcset cs {Square Root} [encoding convertfrom iso8859-2 {Odmocninové}]
::msgcat::mcset cs {Squared} 
::msgcat::mcset cs {Square} 
::msgcat::mcset cs {Stacked} 
::msgcat::mcset cs {Starbase} 
::msgcat::mcset cs {Startup} 
::msgcat::mcset cs {Start} 
::msgcat::mcset cs {Statistics} 
::msgcat::mcset cs {Stats} 
::msgcat::mcset cs {Status} 
::msgcat::mcset cs {Step} 
::msgcat::mcset cs {Stop} 
::msgcat::mcset cs {Story of SAOImageDS9} 
::msgcat::mcset cs {Story} 
::msgcat::mcset cs {Sum} 
::msgcat::mcset cs {Sunken} 
::msgcat::mcset cs {Symbol Editor} 
::msgcat::mcset cs {Symbol} 
::msgcat::mcset cs {Tab-Separated-Value} 
::msgcat::mcset cs {Table} 
::msgcat::mcset cs {Tabloid} 
::msgcat::mcset cs {Tag Color} 
::msgcat::mcset cs {Task} 
::msgcat::mcset cs {Template} [encoding convertfrom iso8859-2 {©ablona}]
::msgcat::mcset cs {Text Font} 
::msgcat::mcset cs {Text} 
::msgcat::mcset cs {Then} 
::msgcat::mcset cs {Thickness} 
::msgcat::mcset cs {This analysis task is already running. Do you wish to kill it?} 
::msgcat::mcset cs {This function is not available.} 
::msgcat::mcset cs {This function is not currently supported for this port.} 
::msgcat::mcset cs {Tickmarks} 
::msgcat::mcset cs {Tile Frames} [encoding convertfrom iso8859-2 {Snímky do dla¾dic}]
::msgcat::mcset cs {Tile Parameters} [encoding convertfrom iso8859-2 {Parametry dla¾dic}]
::msgcat::mcset cs {Tile} [encoding convertfrom iso8859-2 {Dla¾dice}]
::msgcat::mcset cs {Times} 
::msgcat::mcset cs {Title} 
::msgcat::mcset cs {Tophat} 
::msgcat::mcset cs {Topographic} 
::msgcat::mcset cs {Top} 
::msgcat::mcset cs {To} 
::msgcat::mcset cs {Transparency} 
::msgcat::mcset cs {Triangle} 
::msgcat::mcset cs {Type} 
::msgcat::mcset cs {URL} 
::msgcat::mcset cs {Unable to connect directly: using Web Proxy} 
::msgcat::mcset cs {Unable to determine date of observation} 
::msgcat::mcset cs {Unable to evaluate filter} 
::msgcat::mcset cs {Unable to find SIAP window} 
::msgcat::mcset cs {Unable to find URL column} 
::msgcat::mcset cs {Unable to find catalog window} 
::msgcat::mcset cs {Unable to find plot window} 
::msgcat::mcset cs {Unable to load RGB image into a non-rgb frame} 
::msgcat::mcset cs {Unable to load region file} 
::msgcat::mcset cs {Unable to load} 
::msgcat::mcset cs {Unable to locate URL} 
::msgcat::mcset cs {Unable to match target with XPA Mime request} 
::msgcat::mcset cs {Unable to open file} 
::msgcat::mcset cs {Unable to process Analysis file} 
::msgcat::mcset cs {Unable to save RGB image from a non-rgb frame} 
::msgcat::mcset cs {Undo} [encoding convertfrom iso8859-2 {Zpìt}]
::msgcat::mcset cs {Unique} 
::msgcat::mcset cs {Unists} 
::msgcat::mcset cs {Units} 
::msgcat::mcset cs {Unknown Colormap} 
::msgcat::mcset cs {Unknown command} 
::msgcat::mcset cs {Update Filter} 
::msgcat::mcset cs {Update Group} 
::msgcat::mcset cs {Update from Current Crosshair} 
::msgcat::mcset cs {Update from Current Frame} 
::msgcat::mcset cs {Update} 
::msgcat::mcset cs {Upper Left Back} 
::msgcat::mcset cs {Upper Left Front} 
::msgcat::mcset cs {Upper Right Back} 
::msgcat::mcset cs {Upper Right Front} 
::msgcat::mcset cs {Use Authentication} 
::msgcat::mcset cs {Use Current Frame on Download} 
::msgcat::mcset cs {Use Internal Web Browser} 
::msgcat::mcset cs {Use Original Color/Width} 
::msgcat::mcset cs {Use Proxy} 
::msgcat::mcset cs {User Manual} [encoding convertfrom iso8859-2 {U¾ivatelský manuál}]
::msgcat::mcset cs {Username} 
::msgcat::mcset cs {User} [encoding convertfrom iso8859-2 {U¾ivatelské}]
::msgcat::mcset cs {Use} [encoding convertfrom iso8859-2 {Pou¾ívat}]
::msgcat::mcset cs {VO Server} 
::msgcat::mcset cs {VO} 
::msgcat::mcset cs {Value} [encoding convertfrom iso8859-2 {Hodnota}]
::msgcat::mcset cs {Vector} 
::msgcat::mcset cs {Vertical Graph} [encoding convertfrom iso8859-2 {Vertikální graf}]
::msgcat::mcset cs {Vertical Layout} [encoding convertfrom iso8859-2 {Vertikální rozlo¾ení}]
::msgcat::mcset cs {Vertical Text} 
::msgcat::mcset cs {Vertical} 
::msgcat::mcset cs {View} [encoding convertfrom iso8859-2 {Zobrazit}]
::msgcat::mcset cs {Virtual Observatory} [encoding convertfrom iso8859-2 {Virtuální Observatoø}]
::msgcat::mcset cs {WCS Parameters} [encoding convertfrom iso8859-2 {Detaily WCS}]
::msgcat::mcset cs {WCS} 
::msgcat::mcset cs {Wavelength} 
::msgcat::mcset cs {Web Browser} [encoding convertfrom iso8859-2 {Prohlí¾eè}]
::msgcat::mcset cs {White} 
::msgcat::mcset cs {Width} [encoding convertfrom iso8859-2 {Tlou¹»ka}]
::msgcat::mcset cs {Window} 
::msgcat::mcset cs {Words matching title, description} 
::msgcat::mcset cs {X Axis Title} 
::msgcat::mcset cs {X Grid} 
::msgcat::mcset cs {XPA Information} 
::msgcat::mcset cs {XPA not initialized} [encoding convertfrom iso8859-2]
::msgcat::mcset cs {XPA} 
::msgcat::mcset cs {X} 
::msgcat::mcset cs {Y Axis Title} 
::msgcat::mcset cs {Y Grid} 
::msgcat::mcset cs {Yellow} [encoding convertfrom iso8859-2 {®lutá}]
::msgcat::mcset cs {Y} 
::msgcat::mcset cs {Z Axis Scale} 
::msgcat::mcset cs {ZScale Parameters} [encoding convertfrom iso8859-2 {Parametry ZScale}]
::msgcat::mcset cs {Zero} [encoding convertfrom iso8859-2 {Nula}]
::msgcat::mcset cs {Zoom Fit} 
::msgcat::mcset cs {Zoom In} [encoding convertfrom iso8859-2 {Zvìt¹it}]
::msgcat::mcset cs {Zoom Out} [encoding convertfrom iso8859-2 {Zmen¹it}]
::msgcat::mcset cs {Zoom} [encoding convertfrom iso8859-2 {Zvìt¹ení}]
::msgcat::mcset cs {already connected} 
::msgcat::mcset cs {and} 
::msgcat::mcset cs {blue} [encoding convertfrom iso8859-2 {modrá}]
::msgcat::mcset cs {b} 
::msgcat::mcset cs {color} [encoding convertfrom iso8859-2 {barva}]
::msgcat::mcset cs {cool} [encoding convertfrom iso8859-2 {chlad}]
::msgcat::mcset cs {green} [encoding convertfrom iso8859-2 {zelená}]
::msgcat::mcset cs {grey} [encoding convertfrom iso8859-2 {¹edá}]
::msgcat::mcset cs {g} 
::msgcat::mcset cs {h5utils} 
::msgcat::mcset cs {heat} [encoding convertfrom iso8859-2 {horko}]
::msgcat::mcset cs {internal error} 
::msgcat::mcset cs {not connected} 
::msgcat::mcset cs {not} 
::msgcat::mcset cs {only} 
::msgcat::mcset cs {or center of data} 
::msgcat::mcset cs {rainbow} [encoding convertfrom iso8859-2 {duha}]
::msgcat::mcset cs {red} [encoding convertfrom iso8859-2 {èervená}]
::msgcat::mcset cs {rows of data have been downloaded. More may be available. You may wish to adjust the maximum allowed} [encoding convertfrom iso8859-2 {øádkù dat. Více jich mù¾e být k dispozici. Zkuste zmìnit povolené maximum}]
::msgcat::mcset cs {r} 
::msgcat::mcset cs {staircase} [encoding convertfrom iso8859-2 {schodi¹tì}]
::msgcat::mcset cs {standard} 
::msgcat::mcset cs {unable to locate HUB} 
::msgcat::mcset cs {x} 
::msgcat::mcset cs {} 
