::msgcat::mcset da {2D} 
::msgcat::mcset da {3D View} 
::msgcat::mcset da {3D} 
::msgcat::mcset da {A postscript generation error has occurred} [encoding convertfrom iso8859-1 {En fejl er opstået under postscript generering}]
::msgcat::mcset da {AIP} 
::msgcat::mcset da {Abort} 
::msgcat::mcset da {About SAOImageDS9} 
::msgcat::mcset da {About} {Om}
::msgcat::mcset da {Acknowledgment} {Tak}
::msgcat::mcset da {Add Bar Graph} 
::msgcat::mcset da {Add Graph} 
::msgcat::mcset da {Add Line Graph} 
::msgcat::mcset da {Add} [encoding convertfrom iso8859-1 {Tilføj}]
::msgcat::mcset da {Advanced} {Avanceret}
::msgcat::mcset da {Align} {Juster}
::msgcat::mcset da {All Columns} {Alle søjler}
::msgcat::mcset da {All Rows} [encoding convertfrom iso8859-1 {Alle rækker}]
::msgcat::mcset da {All} {Alle}
::msgcat::mcset da {Always save files during Backup} 
::msgcat::mcset da {Amplifier} [encoding convertfrom iso8859-1 {Forstærker}]
::msgcat::mcset da {An error has occurred during backup} 
::msgcat::mcset da {An error has occurred during restore} 
::msgcat::mcset da {An error has occurred invoking the Analysis task} [encoding convertfrom iso8859-1 {Fejl opstået ved kald til analyse program}]
::msgcat::mcset da {An error has occurred while creating} 
::msgcat::mcset da {An error has occurred while loading} 
::msgcat::mcset da {An error has occurred while printing} [encoding convertfrom iso8859-1 {Fejl opstået under udskrivning}]
::msgcat::mcset da {An error has occurred while saving} [encoding convertfrom iso8859-1 {Fejl opstået under gemning}]
::msgcat::mcset da {An internal error has been detected} 
::msgcat::mcset da {Analysis Command Log} {Analyse kommando logbog}
::msgcat::mcset da {Analysis Commands} [encoding convertfrom iso8859-1 {Analyse muligheder}]
::msgcat::mcset da {Analysis File} 
::msgcat::mcset da {Analysis Log} 
::msgcat::mcset da {Analysis} {Analyse}
::msgcat::mcset da {Angle Complement} [encoding convertfrom iso8859-1 {Komplementærvinkel}]
::msgcat::mcset da {Angles} {Vinkler}
::msgcat::mcset da {Angle} {Vinkel}
::msgcat::mcset da {Annuli} {Ringforme}
::msgcat::mcset da {Annulus} {Ringform}
::msgcat::mcset da {Apply} {Anvend}
::msgcat::mcset da {ArcMin} {Bueminutter}
::msgcat::mcset da {ArcSec} {Buesekunder}
::msgcat::mcset da {Architecture} {Arkitektur}
::msgcat::mcset da {Archives} 
::msgcat::mcset da {Array} 
::msgcat::mcset da {Arrow} {Pil}
::msgcat::mcset da {Asteroids} 
::msgcat::mcset da {Astronomy} 
::msgcat::mcset da {At Startup} 
::msgcat::mcset da {At least 2 different catalogs are required} 
::msgcat::mcset da {Auto Centroid} {Automatisk centroide}
::msgcat::mcset da {Auto Plot 2D} 
::msgcat::mcset da {Auto Plot 3D} 
::msgcat::mcset da {Auto Plot Statistics} 
::msgcat::mcset da {Auto Plot} 
::msgcat::mcset da {Autoload FITS Regions} [encoding convertfrom iso8859-1 {Indlæs automatisk FITS regioner}]
::msgcat::mcset da {Autoload} 
::msgcat::mcset da {Automatic} {Automatisk}
::msgcat::mcset da {Average} [encoding convertfrom iso8859-1 {Middelværdi}]
::msgcat::mcset da {Axes Number} 
::msgcat::mcset da {Axes Order} 
::msgcat::mcset da {Axes Range} 
::msgcat::mcset da {Axes Title} 
::msgcat::mcset da {Axes} {Akser}
::msgcat::mcset da {Axis Length} [encoding convertfrom iso8859-1 {Akse længde}]
::msgcat::mcset da {Axis Numbers} {Akse tal}
::msgcat::mcset da {Axis Title} 
::msgcat::mcset da {Axis} {Akser}
::msgcat::mcset da {Azimuth} 
::msgcat::mcset da {Background Color} {Baggrunds farve}
::msgcat::mcset da {Background} {Baggrund}
::msgcat::mcset da {Backup} 
::msgcat::mcset da {Back} {Tilbage}
::msgcat::mcset da {Bar Dataset} 
::msgcat::mcset da {Bar Plot Tool} 
::msgcat::mcset da {Bar Width} 
::msgcat::mcset da {Bar} 
::msgcat::mcset da {Behavior} 
::msgcat::mcset da {Bias} {Bias}
::msgcat::mcset da {Bin 3rd Column} [encoding convertfrom iso8859-1 {Bin 3dje søjle}]
::msgcat::mcset da {Bin Center} {Bin center}
::msgcat::mcset da {Bin Columns} [encoding convertfrom iso8859-1 {Bin søjler}]
::msgcat::mcset da {Bin Filter} {Bin filter}
::msgcat::mcset da {Bin Fit} 
::msgcat::mcset da {Bin In} 
::msgcat::mcset da {Bin Out} 
::msgcat::mcset da {Binning Parameters} {Parameter binning}
::msgcat::mcset da {Bins} 
::msgcat::mcset da {Bin} {Bin}
::msgcat::mcset da {Black} {Sort}
::msgcat::mcset da {Blank/Inf/NaN Color} {Blank/Inf/NaN farve}
::msgcat::mcset da {Blend} 
::msgcat::mcset da {Blink Frames} {Blink rammer}
::msgcat::mcset da {Blink Interval} {Blinke interval}
::msgcat::mcset da {Blink} {Blink}
::msgcat::mcset da {Block Fit} 
::msgcat::mcset da {Block In} {Bin ind}
::msgcat::mcset da {Block Out} {Bin ud}
::msgcat::mcset da {Block Parameters} 
::msgcat::mcset da {Block Pixel} 
::msgcat::mcset da {Block} {Bin}
::msgcat::mcset da {Blue} [encoding convertfrom iso8859-1 {Blå}]
::msgcat::mcset da {Bold} {Fed}
::msgcat::mcset da {Border Color} 
::msgcat::mcset da {Border Width} 
::msgcat::mcset da {Border} {Kant}
::msgcat::mcset da {Bottom} 
::msgcat::mcset da {Box Annulus} {Kasseformet ringform}
::msgcat::mcset da {Box Panda} {Kasseformet panda}
::msgcat::mcset da {BoxCircle} 
::msgcat::mcset da {Boxcar} {Kvadratisk kernel}
::msgcat::mcset da {Box} {Kasse}
::msgcat::mcset da {Broadcast} 
::msgcat::mcset da {Browser} 
::msgcat::mcset da {Browse} 
::msgcat::mcset da {Buffer} 
::msgcat::mcset da {Buttonbar} 
::msgcat::mcset da {Buttons} {Knapper}
::msgcat::mcset da {Bytes} 
::msgcat::mcset da {CMYK} 
::msgcat::mcset da {Can Delete} [encoding convertfrom iso8859-1 {Må slette}]
::msgcat::mcset da {Can Edit} [encoding convertfrom iso8859-1 {Må redigere}]
::msgcat::mcset da {Can Move} [encoding convertfrom iso8859-1 {Må flytte}]
::msgcat::mcset da {Can Rotate} [encoding convertfrom iso8859-1 {Må rotere}]
::msgcat::mcset da {Cancelled} 
::msgcat::mcset da {Cancel} {Slet}
::msgcat::mcset da {Cap} 
::msgcat::mcset da {Catalog Server} {Katalog server}
::msgcat::mcset da {Catalog Tool} {Katalog funktion} 
::msgcat::mcset da {Catalogs} {Kataloger}
::msgcat::mcset da {Catalog} {Katalog}
::msgcat::mcset da {Catrom} 
::msgcat::mcset da {Cat} 
::msgcat::mcset da {Center Dialogs} 
::msgcat::mcset da {Center Image} {Centrer billedet}
::msgcat::mcset da {Center} {Centrer}
::msgcat::mcset da {Centroid Parameters} 
::msgcat::mcset da {Centroid} {Centroide}
::msgcat::mcset da {Circle} {Cirkel}
::msgcat::mcset da {Clear All} {Fjern alt}
::msgcat::mcset da {Clear Analysis Commands} {Fjern analyse funktioner}
::msgcat::mcset da {Clear Cache} [encoding convertfrom iso8859-1 {Tøm cache}]
::msgcat::mcset da {Clear External Analysis Commands?} [encoding convertfrom iso8859-1 {Ryd ekstern analyse kommandoer?}]
::msgcat::mcset da {Clear Filter} {Fjern filter}
::msgcat::mcset da {Clear Frame} {Ryd ramme}
::msgcat::mcset da {Clear Preferences?} {Nulstil foretrukne?}
::msgcat::mcset da {Clear Preferences} {Nulstil foretrukne}
::msgcat::mcset da {Clear} {Fjern}
::msgcat::mcset da {Click to Center} {Klik for centrering}
::msgcat::mcset da {Close} {Luk}
::msgcat::mcset da {Colorbar Size} 
::msgcat::mcset da {Colorbar} {Farvekode}
::msgcat::mcset da {Colormap Parameters} {Farvetabel parametre}
::msgcat::mcset da {Colormap} {Farvetabel}
::msgcat::mcset da {Color} {Farve}
::msgcat::mcset da {Columns} [encoding convertfrom iso8859-1 {Søjler}]
::msgcat::mcset da {Column} [encoding convertfrom iso8859-1 {Søjle}]
::msgcat::mcset da {Comets} 
::msgcat::mcset da {Command not allowed} 
::msgcat::mcset da {Command} 
::msgcat::mcset da {Compass} {Kompas}
::msgcat::mcset da {Composite Region} 
::msgcat::mcset da {Composite} {Sammensat}
::msgcat::mcset da {Compression} {Komprimer}
::msgcat::mcset da {Configure} {Konfigurer}
::msgcat::mcset da {Connect SAMP} 
::msgcat::mcset da {Connect} 
::msgcat::mcset da {Console} {konsol}
::msgcat::mcset da {Contacting Server} 
::msgcat::mcset da {Contour Parameters} {Kontur parametre}
::msgcat::mcset da {Contour Paste} 
::msgcat::mcset da {Contour Save} 
::msgcat::mcset da {Contours} {Konturer}
::msgcat::mcset da {Contour} {Konturer}
::msgcat::mcset da {Contrast} {Kontrast}
::msgcat::mcset da {Control Panel} 
::msgcat::mcset da {Convert to Polygons} {Omdan til poygoner}
::msgcat::mcset da {Coordinate Grid Parameters} {Koordinatnetparametre}
::msgcat::mcset da {Coordinate Grid} {Koordinatnet}
::msgcat::mcset da {Coordinate System} {Koordinat system}
::msgcat::mcset da {Coordinates} {Koordinater}
::msgcat::mcset da {Coordinate} {Koordinat}
::msgcat::mcset da {Copy Contours} {Kopier konturer}
::msgcat::mcset da {Copy to Regions} {kopier til regioner}
::msgcat::mcset da {Copy} {Kopier} 
::msgcat::mcset da {Create Movie} 
::msgcat::mcset da {Create New Frame on Download} {Dan en ny ramme under hentning}
::msgcat::mcset da {Create} 
::msgcat::mcset da {Crop Parameters} 
::msgcat::mcset da {Crop} 
::msgcat::mcset da {Crosshair Parameters} 
::msgcat::mcset da {Crosshair To} [encoding convertfrom iso8859-1 {Trådkors til}]
::msgcat::mcset da {Crosshair} [encoding convertfrom iso8859-1 {Trådkors}]
::msgcat::mcset da {Cross} {Kryds}
::msgcat::mcset da {Cubehelix} 
::msgcat::mcset da {Cube} 
::msgcat::mcset da {Cubic} 
::msgcat::mcset da {Current Frame} {Denne ramme}
::msgcat::mcset da {Current Range} {Dette interval}
::msgcat::mcset da {Current} {Denne}
::msgcat::mcset da {Cursor} 
::msgcat::mcset da {Cut} [encoding convertfrom iso8859-1 {Beskær}]
::msgcat::mcset da {Cyan} {Cyan}
::msgcat::mcset da {DMS} 
::msgcat::mcset da {DPI} 
::msgcat::mcset da {DS9 has detected a newer version of a backup file and therefore will not process this file.} 
::msgcat::mcset da {DS9 has detected a newer version of a preferences file.} 
::msgcat::mcset da {DS9 has detected an older backup file, do you wish to continue?} 
::msgcat::mcset da {DS9 has detected an older preferences file, do you wish to update?} [encoding convertfrom iso8859-1 {DS9 har fundet en ældre fil med foretrukne indstillinger, ønsker du at opdatere?}]
::msgcat::mcset da {DS9 will complete the initialization process} [encoding convertfrom iso8859-1 {DS9 vil fuldføre initialiserings processen}]
::msgcat::mcset da {Darken} 
::msgcat::mcset da {Dash} {streg}
::msgcat::mcset da {Data Format} {Dataformat}
::msgcat::mcset da {Data must be ascii numeric values} 
::msgcat::mcset da {Dataset Name} 
::msgcat::mcset da {Dataset} [encoding convertfrom iso8859-1 {Datasæt}]
::msgcat::mcset da {Data} 
::msgcat::mcset da {Decrease} {Aftag}
::msgcat::mcset da {Default All Files} 
::msgcat::mcset da {Default Format} 
::msgcat::mcset da {Default Length} 
::msgcat::mcset da {Default} {Standard}
::msgcat::mcset da {Degrees} {Grader}
::msgcat::mcset da {Delay} 
::msgcat::mcset da {Delete All Frames?} {Slet alle rammer?}
::msgcat::mcset da {Delete All Frames} {Slet alle rammer}
::msgcat::mcset da {Delete All Groups?} {Slet alle grupper?}
::msgcat::mcset da {Delete All Groups} {Slet alle grupper}
::msgcat::mcset da {Delete All} {Slet alt}
::msgcat::mcset da {Delete Color Tags} 
::msgcat::mcset da {Delete Dataset} 
::msgcat::mcset da {Delete Frame} {Slet denne ramme}
::msgcat::mcset da {Delete Graph} 
::msgcat::mcset da {Delete Group} {Slet gruppe}
::msgcat::mcset da {Delete Load} 
::msgcat::mcset da {Delete Regions?} 
::msgcat::mcset da {Delete Regions} 
::msgcat::mcset da {Delete Selected Regions} [encoding convertfrom iso8859-1 {Slet valgte områder}]
::msgcat::mcset da {Delete Select} 
::msgcat::mcset da {Delete and Open Regions} 
::msgcat::mcset da {Delete} {Slet} 
::msgcat::mcset da {Depth} {Dybde}
::msgcat::mcset da {Detector} {Detektor}
::msgcat::mcset da {Dialog Box} {Dialog vindue}
::msgcat::mcset da {Diameter} 
::msgcat::mcset da {Diamond} {Ruder}
::msgcat::mcset da {Dimensions} 
::msgcat::mcset da {Dimension} {Dimension}
::msgcat::mcset da {Direction} 
::msgcat::mcset da {Disconnect} 
::msgcat::mcset da {Display Size} [encoding convertfrom iso8859-1 {Vis størrelse}]
::msgcat::mcset da {Dissolve} [encoding convertfrom iso8859-1 {Opløs}]
::msgcat::mcset da {Distance} 
::msgcat::mcset da {Done} 
::msgcat::mcset da {Download Colormap} 
::msgcat::mcset da {Drag to Center} [encoding convertfrom iso8859-1 {Træk til center}]
::msgcat::mcset da {Duplicate Dataset} 
::msgcat::mcset da {ENVI} 
::msgcat::mcset da {EPS} 
::msgcat::mcset da {East} [encoding convertfrom iso8859-1 {Øst}]
::msgcat::mcset da {Ecliptic} {Ekliptisk}
::msgcat::mcset da {Edit Group Name} {Rediger gruppe navn}
::msgcat::mcset da {Edit} {Rediger}
::msgcat::mcset da {Elevation} {Stigning}
::msgcat::mcset da {Ellipse Panda} {Ellipse Panda} 
::msgcat::mcset da {Ellipse} {Ellipse}
::msgcat::mcset da {Elliptical Annulus} {Elliptisk ringform}
::msgcat::mcset da {Elliptical Gaussian} 
::msgcat::mcset da {Elliptical Panda} {Elliptisk pandaform}
::msgcat::mcset da {Enable Confirmation Dialogs} [encoding convertfrom iso8859-1 {Aktiver bekræftelsesdialoger}]
::msgcat::mcset da {Enable} 
::msgcat::mcset da {End} {Afslut}
::msgcat::mcset da {Enter Color} {Angiv farve}
::msgcat::mcset da {Enter Font Size} 
::msgcat::mcset da {Enter Group Name} {Indtast gruppenavn}
::msgcat::mcset da {Enter Search Expression} [encoding convertfrom iso8859-1 {Angiv søgeudtryk}]
::msgcat::mcset da {Enter URL} 
::msgcat::mcset da {Entry} 
::msgcat::mcset da {Equal Area} {Samme areal}
::msgcat::mcset da {Equal Distance} {Samme afstand}
::msgcat::mcset da {Equal Spacing} 
::msgcat::mcset da {Equal Value} 
::msgcat::mcset da {Error code was returned} {Fejlkode blev returneret}
::msgcat::mcset da {Errorbar} 
::msgcat::mcset da {Error} {Fejl}
::msgcat::mcset da {Examine Frame} [encoding convertfrom iso8859-1 {Undersøg ramme}]
::msgcat::mcset da {Examine} [encoding convertfrom iso8859-1 {Undersøg}]
::msgcat::mcset da {Exam} 
::msgcat::mcset da {Exclude} {Udelad}
::msgcat::mcset da {Exit} {Luk}
::msgcat::mcset da {Export Array} 
::msgcat::mcset da {Export ENVI} 
::msgcat::mcset da {Export GIF} 
::msgcat::mcset da {Export JPEG} 
::msgcat::mcset da {Export NRRD} 
::msgcat::mcset da {Export PNG} 
::msgcat::mcset da {Export RGB Array} 
::msgcat::mcset da {Export TIFF} 
::msgcat::mcset da {Export} 
::msgcat::mcset da {Extension Data} 
::msgcat::mcset da {Extension not found} 
::msgcat::mcset da {Extensions} 
::msgcat::mcset da {Extension} 
::msgcat::mcset da {Exterior Axes} {Udvendige akser}
::msgcat::mcset da {Exterior Numerics} {Udvendige tal}
::msgcat::mcset da {FAQ} [encoding convertfrom iso8859-1 {Ofte Stillede Spørgsmål}]
::msgcat::mcset da {FITS} 
::msgcat::mcset da {FK4} 
::msgcat::mcset da {FK5} 
::msgcat::mcset da {FP} 
::msgcat::mcset da {Factor} 
::msgcat::mcset da {File not Found or Unable to load FITS data MIME type} [encoding convertfrom iso8859-1 {Filen blev ikke fundet, eller det var ikke muligt at åbne FITS data MIME filtype}]
::msgcat::mcset da {File not found} 
::msgcat::mcset da {Filename} {Filnavn}
::msgcat::mcset da {File} {Fil}
::msgcat::mcset da {Fill} 
::msgcat::mcset da {Filter} {Filter}
::msgcat::mcset da {Find Next} [encoding convertfrom iso8859-1 {Find næste}]
::msgcat::mcset da {Find} {Find}
::msgcat::mcset da {First Block} 
::msgcat::mcset da {First Frame} [encoding convertfrom iso8859-1 {Første ramme}]
::msgcat::mcset da {First} [encoding convertfrom iso8859-1 {Første}]
::msgcat::mcset da {Fits} 
::msgcat::mcset da {Fixed in Size} [encoding convertfrom iso8859-1 {Fastlåst størrelse}]
::msgcat::mcset da {Flip} 
::msgcat::mcset da {Font} {Skrifttype}
::msgcat::mcset da {Footprint Servers} 
::msgcat::mcset da {Footprint} 
::msgcat::mcset da {For more information, use --help} 
::msgcat::mcset da {Foreground} 
::msgcat::mcset da {Forground} 
::msgcat::mcset da {Format} {Format}
::msgcat::mcset da {Forward} {Videre}
::msgcat::mcset da {Found} {Fundet}
::msgcat::mcset da {Frame Information} {Information for ramme}
::msgcat::mcset da {Frame Parameters} 
::msgcat::mcset da {Frames} 
::msgcat::mcset da {Frame} {Ramme}
::msgcat::mcset da {From} 
::msgcat::mcset da {Front} {Foran}
::msgcat::mcset da {Full Range} {Hele intervallet}
::msgcat::mcset da {Function} {Funktion}
::msgcat::mcset da {GIF} 
::msgcat::mcset da {GUI} 
::msgcat::mcset da {Galactic} {Galaktisk}
::msgcat::mcset da {Gap} 
::msgcat::mcset da {Gaussian} {Gaussisk}
::msgcat::mcset da {General} {Generel}
::msgcat::mcset da {Generate} {Opret}
::msgcat::mcset da {Generating Regions} [encoding convertfrom iso8859-1 {danner områder}]
::msgcat::mcset da {Get Information} {Hent information}
::msgcat::mcset da {Gist} 
::msgcat::mcset da {Global Properties} 
::msgcat::mcset da {Global} {Global}
::msgcat::mcset da {Goto Frame} [encoding convertfrom iso8859-1 {Gå til ramme}]
::msgcat::mcset da {Goto Row} 
::msgcat::mcset da {Goto} 
::msgcat::mcset da {Graph Horz} {vandret graf}
::msgcat::mcset da {Graph Parameters} 
::msgcat::mcset da {Graph Vert} {lodret graf}
::msgcat::mcset da {Graphics} {Grafisk}
::msgcat::mcset da {Graphs} 
::msgcat::mcset da {Graph} {graf}
::msgcat::mcset da {Grayscale} [encoding convertfrom iso8859-1 {Gråskala}]
::msgcat::mcset da {Green} [encoding convertfrom iso8859-1 {Grøn}]
::msgcat::mcset da {Grid Gap} {Mellemrum i nettet}
::msgcat::mcset da {Grid} {Net}
::msgcat::mcset da {Groups} {Gupper}
::msgcat::mcset da {HMS} 
::msgcat::mcset da {HTTP} {HTTP}
::msgcat::mcset da {Header} {Hovede}
::msgcat::mcset da {Height} [encoding convertfrom iso8859-1 {Højde}]
::msgcat::mcset da {Help Desk} [encoding convertfrom iso8859-1 {Hjælp}]
::msgcat::mcset da {Help Me Choose} [encoding convertfrom iso8859-1 {Hjælp mig at vælge}]
::msgcat::mcset da {Help} [encoding convertfrom iso8859-1 {Hjælp}]
::msgcat::mcset da {Hide All} {Gem alle}
::msgcat::mcset da {Highlite} 
::msgcat::mcset da {High} [encoding convertfrom iso8859-1 {Høj}]
::msgcat::mcset da {Histogram Equalization} {Histogram udligning}
::msgcat::mcset da {Histogram} {Histogram}
::msgcat::mcset da {Horizontal Graph} {Vandret graf}
::msgcat::mcset da {Horizontal Layout} {Vandret layout}
::msgcat::mcset da {Horizontal} 
::msgcat::mcset da {IAU Location Code} 
::msgcat::mcset da {ICRS} 
::msgcat::mcset da {Identification} {Identifikation}
::msgcat::mcset da {If} {Hvis}
::msgcat::mcset da {Image Servers} 
::msgcat::mcset da {Image} {Billed}
::msgcat::mcset da {Import Array} 
::msgcat::mcset da {Import ENVI} 
::msgcat::mcset da {Import GIF} 
::msgcat::mcset da {Import JPEG} 
::msgcat::mcset da {Import NRRD} 
::msgcat::mcset da {Import PNG} 
::msgcat::mcset da {Import RGB Array} 
::msgcat::mcset da {Import Slice GIF} 
::msgcat::mcset da {Import Slice JPEG} 
::msgcat::mcset da {Import Slice PNG} 
::msgcat::mcset da {Import Slice TIFF} 
::msgcat::mcset da {Import TIFF} 
::msgcat::mcset da {Import} 
::msgcat::mcset da {Include} {Inkluder}
::msgcat::mcset da {Increase} [encoding convertfrom iso8859-1 {Forøg}]
::msgcat::mcset da {Information Panel} {Informations panel}
::msgcat::mcset da {Information} {Information}
::msgcat::mcset da {Initialize XPA} {Initialiser XPA}
::msgcat::mcset da {Inner} {Indre}
::msgcat::mcset da {Instrument FOV} {Instrument FOV} 
::msgcat::mcset da {Instrument} 
::msgcat::mcset da {Interior Axes} {Indre akser}
::msgcat::mcset da {Interior Numerics} {Indre tal}
::msgcat::mcset da {Internal Parse Error} 
::msgcat::mcset da {Interval} {Interval} 
::msgcat::mcset da {Invalid Column Name} 
::msgcat::mcset da {Invalid WCS} 
::msgcat::mcset da {Invalid formated multipart/mixed mime type message} {Forkert formatteret opdelt eller blandet mime type meddelelse}
::msgcat::mcset da {Invert Colormap} {Vend farvetabel}
::msgcat::mcset da {Invert Selection} {Inverter valg}
::msgcat::mcset da {Invert} {Inverter}
::msgcat::mcset da {Italic} {Kursiv}
::msgcat::mcset da {Items Found} {Emner fundet}
::msgcat::mcset da {Iteration} 
::msgcat::mcset da {JPEG Quality Factor} {JPEG kvalitetsfaktor}
::msgcat::mcset da {JPEG} 
::msgcat::mcset da {Keep-Alive} 
::msgcat::mcset da {Keyword} 
::msgcat::mcset da {Labels} {Etiketter}
::msgcat::mcset da {Label} {Etikette}
::msgcat::mcset da {Landscape} {Landskab}
::msgcat::mcset da {Language} {Sprog}
::msgcat::mcset da {Last Block} 
::msgcat::mcset da {Last Frame} {Sidste ramme}
::msgcat::mcset da {Last} {Sidste}
::msgcat::mcset da {Layout Horz} 
::msgcat::mcset da {Layout Vert} 
::msgcat::mcset da {Layout} 
::msgcat::mcset da {Left} 
::msgcat::mcset da {Legal} 
::msgcat::mcset da {Legend Position} 
::msgcat::mcset da {Legend Title} 
::msgcat::mcset da {Legend} 
::msgcat::mcset da {Length} [encoding convertfrom iso8859-1 {Længde}]
::msgcat::mcset da {Letter} 
::msgcat::mcset da {Levels} {Niveauer}
::msgcat::mcset da {Level} {Niveau}
::msgcat::mcset da {Lighten} 
::msgcat::mcset da {Limits} [encoding convertfrom iso8859-1 {Grænser}]
::msgcat::mcset da {Line Dataset} 
::msgcat::mcset da {Line Plot Tool} 
::msgcat::mcset da {Linear} [encoding convertfrom iso8859-1 {Lineær}]
::msgcat::mcset da {Line} {Linie}
::msgcat::mcset da {List Data} 
::msgcat::mcset da {List Regions} [encoding convertfrom iso8859-1 {Vis områder}]
::msgcat::mcset da {List Selected Regions} 
::msgcat::mcset da {List Select} 
::msgcat::mcset da {List} {Liste}
::msgcat::mcset da {Load Analysis Commands} [encoding convertfrom iso8859-1 {Indlæs analyse funktioner}]
::msgcat::mcset da {Load Color Tags} 
::msgcat::mcset da {Load Contour Levels} [encoding convertfrom iso8859-1 {Indlæs konturniveauer}]
::msgcat::mcset da {Load Contrast/Bias} [encoding convertfrom iso8859-1 {Indlæs kontrast/bias}]
::msgcat::mcset da {Load Data} [encoding convertfrom iso8859-1 {Indlæs data}]
::msgcat::mcset da {Load Mosaic} [encoding convertfrom iso8859-1 {Indlæs mosaik}]
::msgcat::mcset da {Load Template} [encoding convertfrom iso8859-1 {Indlæs skabelon}]
::msgcat::mcset da {Load into All} 
::msgcat::mcset da {Load into Current} 
::msgcat::mcset da {Loading Catalog} 
::msgcat::mcset da {Loading} 
::msgcat::mcset da {Load} [encoding convertfrom iso8859-1 {Indlæs}]
::msgcat::mcset da {Local} {Lokal}
::msgcat::mcset da {Lock Axes} 
::msgcat::mcset da {Lock Bin} 
::msgcat::mcset da {Lock Color} 
::msgcat::mcset da {Lock Crop Amplifier} 
::msgcat::mcset da {Lock Crop Detector} 
::msgcat::mcset da {Lock Crop Image} 
::msgcat::mcset da {Lock Crop None} 
::msgcat::mcset da {Lock Crop Physical} 
::msgcat::mcset da {Lock Crop WCS} 
::msgcat::mcset da {Lock Crosshair Amplifier} 
::msgcat::mcset da {Lock Crosshair Detector} 
::msgcat::mcset da {Lock Crosshair Image} 
::msgcat::mcset da {Lock Crosshair None} 
::msgcat::mcset da {Lock Crosshair Physical} 
::msgcat::mcset da {Lock Crosshair WCS} 
::msgcat::mcset da {Lock Frame Amplifier} 
::msgcat::mcset da {Lock Frame Detector} 
::msgcat::mcset da {Lock Frame Image} 
::msgcat::mcset da {Lock Frame None} 
::msgcat::mcset da {Lock Frame Physical} 
::msgcat::mcset da {Lock Frame WCS} 
::msgcat::mcset da {Lock Limits} 
::msgcat::mcset da {Lock Scale} 
::msgcat::mcset da {Lock Slice Image} 
::msgcat::mcset da {Lock Slice None} 
::msgcat::mcset da {Lock Slice WCS} 
::msgcat::mcset da {Lock Smooth} 
::msgcat::mcset da {Lock} [encoding convertfrom iso8859-1 {Lås}]
::msgcat::mcset da {Log Exponent} 
::msgcat::mcset da {Log} 
::msgcat::mcset da {Low High} [encoding convertfrom iso8859-1 {Lav høj}]
::msgcat::mcset da {Lower Left Back} 
::msgcat::mcset da {Lower Left Front} 
::msgcat::mcset da {Lower Right Back} 
::msgcat::mcset da {Lower Right Front} 
::msgcat::mcset da {Low} {lav}
::msgcat::mcset da {MIP} 
::msgcat::mcset da {Magenta} 
::msgcat::mcset da {Magnification} 
::msgcat::mcset da {Magnifier} [encoding convertfrom iso8859-1 {Forstørrelse}]
::msgcat::mcset da {Major Radius} 
::msgcat::mcset da {Major Sigma} 
::msgcat::mcset da {Major} 
::msgcat::mcset da {Manual} 
::msgcat::mcset da {Mask Parameters} {Maske parametre}
::msgcat::mcset da {Match Axes} 
::msgcat::mcset da {Match Bin} 
::msgcat::mcset da {Match Catalog requires at least 1 row per catalog} 
::msgcat::mcset da {Match Color} 
::msgcat::mcset da {Match Crop Amplifier} 
::msgcat::mcset da {Match Crop Detector} 
::msgcat::mcset da {Match Crop Image} 
::msgcat::mcset da {Match Crop Physical} 
::msgcat::mcset da {Match Crop WCS} 
::msgcat::mcset da {Match Crosshair Amplifier} 
::msgcat::mcset da {Match Crosshair Detector} 
::msgcat::mcset da {Match Crosshair Image} 
::msgcat::mcset da {Match Crosshair Physical} 
::msgcat::mcset da {Match Crosshair WCS} 
::msgcat::mcset da {Match Frame Amplifier} 
::msgcat::mcset da {Match Frame Detector} 
::msgcat::mcset da {Match Frame Image} 
::msgcat::mcset da {Match Frame Physical} 
::msgcat::mcset da {Match Frame WCS} 
::msgcat::mcset da {Match Limits} 
::msgcat::mcset da {Match Scale} 
::msgcat::mcset da {Match Slice Image} 
::msgcat::mcset da {Match Slice WCS} 
::msgcat::mcset da {Match Smooth} 
::msgcat::mcset da {Match} 
::msgcat::mcset da {Math Function} {Matematisk funktion}
::msgcat::mcset da {Matplotlib} 
::msgcat::mcset da {Max Rows} {Maks antal rækker}
::msgcat::mcset da {Maximum} 
::msgcat::mcset da {Max} {Maks}
::msgcat::mcset da {Menus and Buttons} 
::msgcat::mcset da {Menu} 
::msgcat::mcset da {Message Log} 
::msgcat::mcset da {Method} {Metode}
::msgcat::mcset da {Min Max Parameters} 
::msgcat::mcset da {Min Max} {Min Maks}
::msgcat::mcset da {Minimum} 
::msgcat::mcset da {Minor Radius} 
::msgcat::mcset da {Minor Sigma} 
::msgcat::mcset da {Minor} 
::msgcat::mcset da {Minutes} 
::msgcat::mcset da {Min} 
::msgcat::mcset da {Mission} 
::msgcat::mcset da {Mode} 
::msgcat::mcset da {Mosaic IRAF Segment} 
::msgcat::mcset da {Mosaic IRAF} 
::msgcat::mcset da {Mosaic WCS Segment} 
::msgcat::mcset da {Mosaic WCS} 
::msgcat::mcset da {Mosaic WFPC2} 
::msgcat::mcset da {Mosaic} 
::msgcat::mcset da {Mouse Click Epsilon} 
::msgcat::mcset da {Mouse Wheel Bin} 
::msgcat::mcset da {Mouse Wheel Zoom} 
::msgcat::mcset da {Move Back} {flyt tilbage} 
::msgcat::mcset da {Move First} {flyt forrest}
::msgcat::mcset da {Move Forward} {flyt frem}
::msgcat::mcset da {Move Frame} 
::msgcat::mcset da {Move Last} {flyt sidst}
::msgcat::mcset da {Move to Back} {Bag}
::msgcat::mcset da {Move to Front} {Foran}
::msgcat::mcset da {Movie} 
::msgcat::mcset da {Muliple Extension Cube} 
::msgcat::mcset da {Muliple Extension Frames} 
::msgcat::mcset da {Multiple Extension Cube} 
::msgcat::mcset da {Multiple Extension Frames} 
::msgcat::mcset da {Multiple WCS} {Multipel WCS}
::msgcat::mcset da {NAN} 
::msgcat::mcset da {NRRD} 
::msgcat::mcset da {Name Resolution} [encoding convertfrom iso8859-1 {Navnesøgning}]
::msgcat::mcset da {Name Server} {Navneserver}
::msgcat::mcset da {Name or Designation} {navn eller beskrivelse}
::msgcat::mcset da {Name} 
::msgcat::mcset da {Native Dialog} {Oprindelig dialog}
::msgcat::mcset da {New Features} {Nye egenskaber}
::msgcat::mcset da {New Frame 3D} {Ny ramme 3D}
::msgcat::mcset da {New Frame RGB} {Ny ramme (RGB)}
::msgcat::mcset da {New Frame each Time} {Ny ramme hver gang}
::msgcat::mcset da {New Frame} {Ny ramme}
::msgcat::mcset da {New Graph} 
::msgcat::mcset da {New Group} {Ny gruppe}
::msgcat::mcset da {New Plot} 
::msgcat::mcset da {New} {Ny}
::msgcat::mcset da {Next Block} 
::msgcat::mcset da {Next Frame} [encoding convertfrom iso8859-1 {Næste ramme}]
::msgcat::mcset da {Next} [encoding convertfrom iso8859-1 {Næste}]
::msgcat::mcset da {No Catalog specified} {Intet katalog er specificeret}
::msgcat::mcset da {No Data Available} 
::msgcat::mcset da {No Items Found} {Ingen emner er fundet}
::msgcat::mcset da {Non-NAN} 
::msgcat::mcset da {Non-Zero} 
::msgcat::mcset da {None} [encoding convertfrom iso8859-1 {Ingen}]
::msgcat::mcset da {Normal} {Normal}
::msgcat::mcset da {North} {Nord}
::msgcat::mcset da {Not Found} 
::msgcat::mcset da {Not Supported} 
::msgcat::mcset da {Not valid export format} 
::msgcat::mcset da {Notes} 
::msgcat::mcset da {Number of Samples} {Antal}
::msgcat::mcset da {Number of Threads} 
::msgcat::mcset da {Number of Ticks} 
::msgcat::mcset da {Number} {Antal}
::msgcat::mcset da {Numerics} {Talværdier}
::msgcat::mcset da {OK} 
::msgcat::mcset da {Object} {Objekt}
::msgcat::mcset da {ObsId} 
::msgcat::mcset da {Open File} {Åben fil}
::msgcat::mcset da {Open ME Cube} 
::msgcat::mcset da {Open ME Frames} 
::msgcat::mcset da {Open Mosaic IRAF Seg} 
::msgcat::mcset da {Open Mosaic IRAF} 
::msgcat::mcset da {Open Mosaic WCS Seg} 
::msgcat::mcset da {Open Mosaic WCS} 
::msgcat::mcset da {Open Mosaic WFPC2} 
::msgcat::mcset da {Open RGB Cube} 
::msgcat::mcset da {Open RGB Image} 
::msgcat::mcset da {Open Regions} 
::msgcat::mcset da {Open Slice} 
::msgcat::mcset da {Open TCL Console} [encoding convertfrom iso8859-1 {Åben TCL konsol}]
::msgcat::mcset da {Open URL} [encoding convertfrom iso8859-1 {Åben URL}]
::msgcat::mcset da {Open as} 
::msgcat::mcset da {Open} [encoding convertfrom iso8859-1 {Åben}]
::msgcat::mcset da {Operator} 
::msgcat::mcset da {Orientation} {Orientering}
::msgcat::mcset da {Origin} 
::msgcat::mcset da {Oscillate} 
::msgcat::mcset da {Other Color} 
::msgcat::mcset da {Other Font Size} 
::msgcat::mcset da {Other} {Anden}
::msgcat::mcset da {Outer} {Ydre}
::msgcat::mcset da {Overplot} 
::msgcat::mcset da {Override Color} 
::msgcat::mcset da {PNG} 
::msgcat::mcset da {PS Page Setup} {PS side opsætning}
::msgcat::mcset da {PS Print} {PS udskrift}
::msgcat::mcset da {Page Setup} [encoding convertfrom iso8859-1 {Side opsætning}]
::msgcat::mcset da {Page Source} {Side kilde}
::msgcat::mcset da {Pan To} {Flyt til}
::msgcat::mcset da {Pan Zoom Rotate Parameters} [encoding convertfrom iso8859-1 {Flyt Zoom Rotér parametre}]
::msgcat::mcset da {Pan Zoom} {Flyt Zoom}
::msgcat::mcset da {Pan then Zoom} {Flyt og derefter zoom}
::msgcat::mcset da {Panda} 
::msgcat::mcset da {Panner} {Oversigtskort}
::msgcat::mcset da {Pan} {Flyt}
::msgcat::mcset da {Parameters} {Parametre}
::msgcat::mcset da {Password} {Kodeord}
::msgcat::mcset da {Paste Contours} {Indsæt konturer}
::msgcat::mcset da {Paste} [encoding convertfrom iso8859-1 {Sæt ind}]
::msgcat::mcset da {Physical} {Fysisk}
::msgcat::mcset da {Pixel Distribution} {Pixelfordeling}
::msgcat::mcset da {Pixel Size} [encoding convertfrom iso8859-1 {Pixelstørrelse}]
::msgcat::mcset da {Pixel Table} {Pixel tabel}
::msgcat::mcset da {Pixels} {Pixler}
::msgcat::mcset da {Planets} 
::msgcat::mcset da {Play} {Afspil}
::msgcat::mcset da {Please Select a Region} 
::msgcat::mcset da {Please change the file's permission to disable other users write access. Use anyway?} 
::msgcat::mcset da {Please specify instruments} 
::msgcat::mcset da {Please specify radius and either name or (ra,dec)} 
::msgcat::mcset da {Please specify width, height, and either name or (ra,dec)} [encoding convertfrom iso8859-1 {angiv venligst bredde, højde, og enten navn eller (ra,dec)}]
::msgcat::mcset da {Plot 2D} 
::msgcat::mcset da {Plot 3D} 
::msgcat::mcset da {Plot Area} 
::msgcat::mcset da {Plot Control Panel} 
::msgcat::mcset da {Plot Tool} 
::msgcat::mcset da {Plotting Regions} [encoding convertfrom iso8859-1 {Plotte områder}]
::msgcat::mcset da {Plot} 
::msgcat::mcset da {Plus} 
::msgcat::mcset da {Pointer} {Pegepil}
::msgcat::mcset da {Points} {Punkter}
::msgcat::mcset da {Point} {Punkt}
::msgcat::mcset da {Polygon} {Polygon}
::msgcat::mcset da {Portrait} [encoding convertfrom iso8859-1 {Portræt}]
::msgcat::mcset da {Position} 
::msgcat::mcset da {Poster} {Plakat}
::msgcat::mcset da {Postscript} 
::msgcat::mcset da {Power} {Potenslov}
::msgcat::mcset da {Precision} 
::msgcat::mcset da {Preferences} {Foretrukne}
::msgcat::mcset da {Preserve During Load} [encoding convertfrom iso8859-1 {Bevar under indlæsning}]
::msgcat::mcset da {Previous Block} 
::msgcat::mcset da {Previous Frame} [encoding convertfrom iso8859-1 {Foregående ramme}]
::msgcat::mcset da {Previous} [encoding convertfrom iso8859-1 {Foregående}]
::msgcat::mcset da {Prev} 
::msgcat::mcset da {Print Coordinates} {Udskriv koordinater}
::msgcat::mcset da {Print To} {Udskriv til}
::msgcat::mcset da {Printer} {Printer}
::msgcat::mcset da {Print} {Udskriv}
::msgcat::mcset da {Prism Goto} 
::msgcat::mcset da {Prism} 
::msgcat::mcset da {Projection} {Projektion}
::msgcat::mcset da {Properties} {Egenskaber}
::msgcat::mcset da {Property} {Egenskab}
::msgcat::mcset da {Proxy Host} 
::msgcat::mcset da {Proxy Port} 
::msgcat::mcset da {Publication} {Publikation} 
::msgcat::mcset da {Quadratic} {Kvadratisk}
::msgcat::mcset da {RDB} 
::msgcat::mcset da {RGB Array} 
::msgcat::mcset da {RGB Cube} 
::msgcat::mcset da {RGB Image} 
::msgcat::mcset da {RGB} 
::msgcat::mcset da {Radial Profile} 
::msgcat::mcset da {Radius} 
::msgcat::mcset da {Range} 
::msgcat::mcset da {Redo} {Gentag sidste}
::msgcat::mcset da {Red} [encoding convertfrom iso8859-1 {Rød}]
::msgcat::mcset da {Reference Manual} 
::msgcat::mcset da {Reference} 
::msgcat::mcset da {Refresh Frame} {Opdater ramme}
::msgcat::mcset da {Refresh} {Opdater}
::msgcat::mcset da {Region Parameters} 
::msgcat::mcset da {Region} [encoding convertfrom iso8859-1 {Område}]
::msgcat::mcset da {Release Notes} {Frigvelsesnoter}
::msgcat::mcset da {Release} {Frigivelsesnoter}
::msgcat::mcset da {Reload} {Genhent}
::msgcat::mcset da {Render} 
::msgcat::mcset da {Repeat} 
::msgcat::mcset da {Reset Colormap} {Nulstil farvetabel}
::msgcat::mcset da {Reset Frame} {Nulstil ramme}
::msgcat::mcset da {Reset} {Nulstil}
::msgcat::mcset da {Restore} 
::msgcat::mcset da {Retrieve} {Hent}
::msgcat::mcset da {Return} 
::msgcat::mcset da {Right} 
::msgcat::mcset da {Roman} 
::msgcat::mcset da {Rotate} {Roter}
::msgcat::mcset da {Rows} [encoding convertfrom iso8859-1 {Rækker}]
::msgcat::mcset da {Row} 
::msgcat::mcset da {Ruler} {Lineal}
::msgcat::mcset da {SAMP Image} 
::msgcat::mcset da {SAMP Table} 
::msgcat::mcset da {SAMP: not connected} 
::msgcat::mcset da {SAMP} 
::msgcat::mcset da {Sample Increment} 
::msgcat::mcset da {Sample Parameters} 
::msgcat::mcset da {Samples per Line} {Udvalg per linie}
::msgcat::mcset da {Sample} 
::msgcat::mcset da {Save 3D Movie} 
::msgcat::mcset da {Save Color Tags} 
::msgcat::mcset da {Save Contour Levels} {Gem konturniveauer}
::msgcat::mcset da {Save Contrast/Bias} {Gem kontrast/bias}
::msgcat::mcset da {Save Data} {Gem data}
::msgcat::mcset da {Save Image EPS} 
::msgcat::mcset da {Save Image FITS} 
::msgcat::mcset da {Save Image GIF} 
::msgcat::mcset da {Save Image JPEG} 
::msgcat::mcset da {Save Image PNG} 
::msgcat::mcset da {Save Image TIFF} 
::msgcat::mcset da {Save Image on Download} 
::msgcat::mcset da {Save Image} {Gem billede}
::msgcat::mcset da {Save ME Cube} 
::msgcat::mcset da {Save Mosaic WCS Seg} 
::msgcat::mcset da {Save Mosaic WCS} 
::msgcat::mcset da {Save RGB Cube} 
::msgcat::mcset da {Save RGB Image} 
::msgcat::mcset da {Save Regions} [encoding convertfrom iso8859-1 {Gem områder}]
::msgcat::mcset da {Save Selected Regions} 
::msgcat::mcset da {Save Select} 
::msgcat::mcset da {Save Slice} 
::msgcat::mcset da {Save Template} {Gem skabelon}
::msgcat::mcset da {Save as} 
::msgcat::mcset da {Save} {Gem}
::msgcat::mcset da {Scale Parameters} {Skala parametre}
::msgcat::mcset da {Scale and Limits} 
::msgcat::mcset da {Scale} {Skala}
::msgcat::mcset da {Scan} {skan}
::msgcat::mcset da {Scatter Dataset} 
::msgcat::mcset da {Scatter Plot Tool} 
::msgcat::mcset da {Scope} [encoding convertfrom iso8859-1 {Gældende}]
::msgcat::mcset da {Screen} 
::msgcat::mcset da {Search for Catalogs} [encoding convertfrom iso8859-1 {søg efter kataloger}]
::msgcat::mcset da {Seconds} {Sekunder}
::msgcat::mcset da {Segment} 
::msgcat::mcset da {Select All} [encoding convertfrom iso8859-1 {Vælg alle}]
::msgcat::mcset da {Select Coordinate System } [encoding convertfrom iso8859-1 {vælg koordinat system}]
::msgcat::mcset da {Select Dataset} 
::msgcat::mcset da {Select Datatset} 
::msgcat::mcset da {Select Graph} 
::msgcat::mcset da {Select None} [encoding convertfrom iso8859-1 {Vælg ingen}]
::msgcat::mcset da {Send} 
::msgcat::mcset da {Server} {Server}
::msgcat::mcset da {Sexagesimal} 
::msgcat::mcset da {Shadow} 
::msgcat::mcset da {Shape} {Form}
::msgcat::mcset da {Show All} {Vis alle}
::msgcat::mcset da {Show Command} 
::msgcat::mcset da {Show Compass} 
::msgcat::mcset da {Show Grid} 
::msgcat::mcset da {Show Legend} 
::msgcat::mcset da {Show Text} {Vis tekst}
::msgcat::mcset da {Show/Hide Frames} {Vis/skjul rammer}
::msgcat::mcset da {Show} {Vis}
::msgcat::mcset da {Simple Cross} 
::msgcat::mcset da {Simple Image Access} 
::msgcat::mcset da {Simple Plus} 
::msgcat::mcset da {Single Frame} {Enkel ramme}
::msgcat::mcset da {Single} {Enkel}
::msgcat::mcset da {Sites} 
::msgcat::mcset da {Size/Radius} [encoding convertfrom iso8859-1 {Størrelse/Radius}]
::msgcat::mcset da {Size} {Størrelse}
::msgcat::mcset da {Skip First} [encoding convertfrom iso8859-1 {Overspring første}]
::msgcat::mcset da {Slice} 
::msgcat::mcset da {Smooth Parameters} {Udglatningsparametre}
::msgcat::mcset da {Smoothness} 
::msgcat::mcset da {Smooth} {Udglat}
::msgcat::mcset da {Sorry, DS9 does not support} [encoding convertfrom iso8859-1 {DS9 understøtter ikke}]
::msgcat::mcset da {Sorry, DS9 requires a Truecolor8, Truecolor16, Truecolor24 visual be available} 
::msgcat::mcset da {Sort} {Sorter}
::msgcat::mcset da {Source TCL} {Kilde TCL}
::msgcat::mcset da {Source} {Kilde}
::msgcat::mcset da {Space Equal Distance} 
::msgcat::mcset da {Space Equal Value} 
::msgcat::mcset da {Spacing} {Mellemrum}
::msgcat::mcset da {Sqrt} 
::msgcat::mcset da {Square Root} {Kvadratrod}
::msgcat::mcset da {Squared} {Kvadratisk}
::msgcat::mcset da {Square} 
::msgcat::mcset da {Starbase} 
::msgcat::mcset da {Startup} 
::msgcat::mcset da {Start} 
::msgcat::mcset da {Statistics} 
::msgcat::mcset da {Status} 
::msgcat::mcset da {Step} {Trin}
::msgcat::mcset da {Stop} 
::msgcat::mcset da {Story of SAOImageDS9} 
::msgcat::mcset da {Story} 
::msgcat::mcset da {Strip Parameters} 
::msgcat::mcset da {Strip Scale} 
::msgcat::mcset da {Strip} 
::msgcat::mcset da {Sum} 
::msgcat::mcset da {Symbol Editor} 
::msgcat::mcset da {Symbol} 
::msgcat::mcset da {TIFF} 
::msgcat::mcset da {TSV} 
::msgcat::mcset da {Tab-Separated-Value} 
::msgcat::mcset da {Table} 
::msgcat::mcset da {Tabloid} 
::msgcat::mcset da {Tag Color} 
::msgcat::mcset da {Template} 
::msgcat::mcset da {Text} {Tekst}
::msgcat::mcset da {Theme} 
::msgcat::mcset da {Then} [encoding convertfrom iso8859-1 {Så}]
::msgcat::mcset da {Thickness} {Tykkelse}
::msgcat::mcset da {This analysis task is already running. Do you wish to kill it?} {Denne analyseopgave kører allerede - skal den stoppes?}
::msgcat::mcset da {This function is not available.} 
::msgcat::mcset da {This function is not currently supported for this port.} 
::msgcat::mcset da {Tickmarks} {Afmærkninger}
::msgcat::mcset da {Tile Frames} {Mosaik rammer}
::msgcat::mcset da {Tile Parameters} {Mosaik parametre}
::msgcat::mcset da {Tile} {Mosaik}
::msgcat::mcset da {Times} 
::msgcat::mcset da {Titles} 
::msgcat::mcset da {Title} {Titel}
::msgcat::mcset da {Tophat} 
::msgcat::mcset da {Topographic} 
::msgcat::mcset da {Top} 
::msgcat::mcset da {To} {Til}
::msgcat::mcset da {Transparency} 
::msgcat::mcset da {Triangle} 
::msgcat::mcset da {Type} 
::msgcat::mcset da {URL} 
::msgcat::mcset da {Unable to connect directly: using Web Proxy} 
::msgcat::mcset da {Unable to create FOV Region, celestial WCS Required} 
::msgcat::mcset da {Unable to determine date of observation} 
::msgcat::mcset da {Unable to evaluate filter} {kan ikke bestemme filter}
::msgcat::mcset da {Unable to find Footprint window} 
::msgcat::mcset da {Unable to find PRISM window} 
::msgcat::mcset da {Unable to find SIAP window} 
::msgcat::mcset da {Unable to find URL column} 
::msgcat::mcset da {Unable to find catalog window} {Kan ikke finde katalog vinduet}
::msgcat::mcset da {Unable to find plot window} {kan ikke finde plotte vinduet}
::msgcat::mcset da {Unable to find web window} 
::msgcat::mcset da {Unable to generate plot} 
::msgcat::mcset da {Unable to load RGB image into a non-rgb frame} {Kan ikke hente et RGB billede ind i en ikke-RGB ramme}
::msgcat::mcset da {Unable to load compressed region file} 
::msgcat::mcset da {Unable to load plot data} 
::msgcat::mcset da {Unable to load region file} 
::msgcat::mcset da {Unable to load} {Kan ikke hente}
::msgcat::mcset da {Unable to locate FOV Region} 
::msgcat::mcset da {Unable to locate URL} {Kan ikke finde URL}
::msgcat::mcset da {Unable to match target with XPA Mime request} 
::msgcat::mcset da {Unable to open file} [encoding convertfrom iso8859-1 {Kan ikke åbne fil}]
::msgcat::mcset da {Unable to save RGB image from a non-rgb frame} 
::msgcat::mcset da {Undo} {Fortryd}
::msgcat::mcset da {Unique} 
::msgcat::mcset da {Unists} 
::msgcat::mcset da {Units} {Enheder}
::msgcat::mcset da {Unknown Colormap} 
::msgcat::mcset da {Unknown command} 
::msgcat::mcset da {Update Filter} 
::msgcat::mcset da {Update Group} {Opdater gruppe}
::msgcat::mcset da {Update from Current Crosshair} [encoding convertfrom iso8859-1 {Opdater fra nuværende trådkors}]
::msgcat::mcset da {Update from Current Frame} [encoding convertfrom iso8859-1 {Opdater fra nuværende ramme}]
::msgcat::mcset da {Update} {Opdater}
::msgcat::mcset da {Upper Left Back} 
::msgcat::mcset da {Upper Left Front} 
::msgcat::mcset da {Upper Right Back} 
::msgcat::mcset da {Upper Right Front} 
::msgcat::mcset da {Use Authentication} [encoding convertfrom iso8859-1 {Anvend bekræftelse}]
::msgcat::mcset da {Use Current Frame on Download} {Brug nuværende ramme til download}
::msgcat::mcset da {Use Internal Web Browser} {Brug intern web browser}
::msgcat::mcset da {Use Original Color/Width} 
::msgcat::mcset da {Use Proxy} {Anvend proxy}
::msgcat::mcset da {Use Theme Colors} 
::msgcat::mcset da {Use background color instead of theme color} 
::msgcat::mcset da {User Manual} 
::msgcat::mcset da {Username} {Brugernavn}
::msgcat::mcset da {User} {Brugerdefineret}
::msgcat::mcset da {Use} {Anvend}
::msgcat::mcset da {VO Server} 
::msgcat::mcset da {VOTable} 
::msgcat::mcset da {VOT} 
::msgcat::mcset da {VO} 
::msgcat::mcset da {Value} [encoding convertfrom iso8859-1 {Værdi}]
::msgcat::mcset da {Vector} {Vektor}
::msgcat::mcset da {Vertical Graph} {Lodret graf}
::msgcat::mcset da {Vertical Layout} {Lodret layoyt}
::msgcat::mcset da {Vertical Text} {Lodret tekst}
::msgcat::mcset da {Vertical} 
::msgcat::mcset da {View} {Vis}
::msgcat::mcset da {Virtual Observatory} {Virtuelt Observatorium}
::msgcat::mcset da {WCS Parameters} 
::msgcat::mcset da {WCS} 
::msgcat::mcset da {Wavelength} [encoding convertfrom iso8859-1 {Bølgelængde}]
::msgcat::mcset da {Web Browser} 
::msgcat::mcset da {White} {Hvid}
::msgcat::mcset da {Width} {Bredde}
::msgcat::mcset da {Window} 
::msgcat::mcset da {Words matching title, description} {Ord tilpasset titel, beskrivelse }
::msgcat::mcset da {X Axis Title} 
::msgcat::mcset da {X Axis} 
::msgcat::mcset da {X Column} 
::msgcat::mcset da {X Error Column} 
::msgcat::mcset da {XPA Information} {XPA information}
::msgcat::mcset da {XPA not initialized} {XPA ikke startet}
::msgcat::mcset da {XPA} 
::msgcat::mcset da {X} 
::msgcat::mcset da {Y Axis Title} 
::msgcat::mcset da {Y Axis} 
::msgcat::mcset da {Y Column} 
::msgcat::mcset da {Y Error Column} 
::msgcat::mcset da {Yellow} {Gul}
::msgcat::mcset da {Y} 
::msgcat::mcset da {Z Axis Scale} 
::msgcat::mcset da {ZScale Parameters} 
::msgcat::mcset da {Zero} {Nul}
::msgcat::mcset da {Zoom Fit} 
::msgcat::mcset da {Zoom In} {Zoom ind}
::msgcat::mcset da {Zoom Out} {Zoom ud}
::msgcat::mcset da {Zoom} 
::msgcat::mcset da {already connected} 
::msgcat::mcset da {and} 
::msgcat::mcset da {b} 
::msgcat::mcset da {g} 
::msgcat::mcset da {h5utils} 
::msgcat::mcset da {hundredths second} 
::msgcat::mcset da {internal error} 
::msgcat::mcset da {not connected} 
::msgcat::mcset da {not} 
::msgcat::mcset da {only} 
::msgcat::mcset da {or center of data} {eller center for data}
::msgcat::mcset da {rows of data have been downloaded. More may be available. You may wish to adjust the maximum allowed} [encoding convertfrom iso8859-1 {rækker af data er blevet hentet. Der kan være flere tilgængelige. Du bør måske ændre det maksimalt tilladte antal}]
::msgcat::mcset da {r} 
::msgcat::mcset da {unable to locate HUB} 
::msgcat::mcset da {x} 
