# Clean UTF-8 Translation Catalog for Tcl 9
# Generated automatically from legacy da.msg

::msgcat::mcset da 2d 2d
::msgcat::mcset da 3d 3d
::msgcat::mcset da {A postscript generation error has occurred} {En fejl er opstået under postscript generering}
::msgcat::mcset da AIP AIP
::msgcat::mcset da Abort Abort
::msgcat::mcset da {About SAOImageDS9} {About SAOImageDS9}
::msgcat::mcset da About Om
::msgcat::mcset da Acknowledgment Tak
::msgcat::mcset da {Add Bar Graph} {Add Bar Graph}
::msgcat::mcset da {Add Graph} {Add Graph}
::msgcat::mcset da {Add Line Graph} {Add Line Graph}
::msgcat::mcset da {Add New Frame} {Add New Frame}
::msgcat::mcset da Add Tilføj
::msgcat::mcset da {Advanced Layout} {Advanced Layout}
::msgcat::mcset da Advanced Avanceret
::msgcat::mcset da {Align North Up} {Align North Up}
::msgcat::mcset da Align Juster
::msgcat::mcset da {All Columns} {Alle søjler}
::msgcat::mcset da {All Rows} {Alle rækker}
::msgcat::mcset da All Alle
::msgcat::mcset da {Always save files during Backup} {Always save files during Backup}
::msgcat::mcset da Amplifier Forstærker
::msgcat::mcset da {An error has occurred during backup} {An error has occurred during backup}
::msgcat::mcset da {An error has occurred during restore} {An error has occurred during restore}
::msgcat::mcset da {An error has occurred invoking the Analysis task} {Fejl opstået ved kald til analyse program}
::msgcat::mcset da {An error has occurred while creating} {An error has occurred while creating}
::msgcat::mcset da {An error has occurred while loading} {An error has occurred while loading}
::msgcat::mcset da {An error has occurred while printing} {Fejl opstået under udskrivning}
::msgcat::mcset da {An error has occurred while saving} {Fejl opstået under gemning}
::msgcat::mcset da {An internal error has been detected} {An internal error has been detected}
::msgcat::mcset da {Analysis Command Log} {Analyse kommando logbog}
::msgcat::mcset da {Analysis Commands} {Analyse muligheder}
::msgcat::mcset da {Analysis File} {Analysis File}
::msgcat::mcset da {Analysis Log} {Analysis Log}
::msgcat::mcset da Analysis Analyse
::msgcat::mcset da {Angle Complement} Komplementærvinkel
::msgcat::mcset da Angles Vinkler
::msgcat::mcset da Angle Vinkel
::msgcat::mcset da Annuli Ringforme
::msgcat::mcset da Annulus Ringform
::msgcat::mcset da Apply Anvend
::msgcat::mcset da ArcMin Bueminutter
::msgcat::mcset da ArcSec Buesekunder
::msgcat::mcset da Architecture Arkitektur
::msgcat::mcset da Archives Archives
::msgcat::mcset da Array Array
::msgcat::mcset da Arrow Pil
::msgcat::mcset da Asteroids Asteroids
::msgcat::mcset da Astronomy Astronomy
::msgcat::mcset da {At Startup} {At Startup}
::msgcat::mcset da {At least 2 different catalogs are required} {At least 2 different catalogs are required}
::msgcat::mcset da {Auto Centroid} {Automatisk centroide}
::msgcat::mcset da {Auto Plot 2D} {Auto Plot 2D}
::msgcat::mcset da {Auto Plot 3D} {Auto Plot 3D}
::msgcat::mcset da {Auto Plot Statistics} {Auto Plot Statistics}
::msgcat::mcset da {Auto Plot} {Auto Plot}
::msgcat::mcset da {Auto Recovery} {Auto Recovery}
::msgcat::mcset da {Autoload FITS Regions} {Indlæs automatisk FITS regioner}
::msgcat::mcset da Autoload Autoload
::msgcat::mcset da Automatic Automatisk
::msgcat::mcset da Average Middelværdi
::msgcat::mcset da {Axes Number} {Axes Number}
::msgcat::mcset da {Axes Order} {Axes Order}
::msgcat::mcset da {Axes Range} {Axes Range}
::msgcat::mcset da {Axes Title} {Axes Title}
::msgcat::mcset da Axes Akser
::msgcat::mcset da {Axis Length} {Akse længde}
::msgcat::mcset da {Axis Numbers} {Akse tal}
::msgcat::mcset da {Axis Title} {Axis Title}
::msgcat::mcset da Axis Akser
::msgcat::mcset da Azimuth Azimuth
::msgcat::mcset da {Background Color} {Baggrunds farve}
::msgcat::mcset da Background Baggrund
::msgcat::mcset da Backup Backup
::msgcat::mcset da Back Tilbage
::msgcat::mcset da {Bar Dataset} {Bar Dataset}
::msgcat::mcset da {Bar Plot Tool} {Bar Plot Tool}
::msgcat::mcset da {Bar Width} {Bar Width}
::msgcat::mcset da Bar Bar
::msgcat::mcset da {Basic Layout} {Basic Layout}
::msgcat::mcset da Basic Basic
::msgcat::mcset da Behavior Behavior
::msgcat::mcset da Bias Bias
::msgcat::mcset da {Bin 3rd Column} {Bin 3dje søjle}
::msgcat::mcset da {Bin Center} {Bin center}
::msgcat::mcset da {Bin Columns} {Bin søjler}
::msgcat::mcset da {Bin Filter} {Bin filter}
::msgcat::mcset da {Bin Fit} {Bin Fit}
::msgcat::mcset da {Bin In} {Bin In}
::msgcat::mcset da {Bin Out} {Bin Out}
::msgcat::mcset da {Binning Parameters} {Parameter binning}
::msgcat::mcset da Bins Bins
::msgcat::mcset da Bin Bin
::msgcat::mcset da Black Sort
::msgcat::mcset da {Blank/Inf/NaN Color} {Blank/Inf/NaN farve}
::msgcat::mcset da Blend Blend
::msgcat::mcset da {Blink Frames} {Blink rammer}
::msgcat::mcset da {Blink Interval} {Blinke interval}
::msgcat::mcset da Blink Blink
::msgcat::mcset da {Block Fit} {Block Fit}
::msgcat::mcset da {Block In} {Bin ind}
::msgcat::mcset da {Block Out} {Bin ud}
::msgcat::mcset da {Block Parameters} {Block Parameters}
::msgcat::mcset da {Block Pixel} {Block Pixel}
::msgcat::mcset da Block Bin
::msgcat::mcset da Blue Blå
::msgcat::mcset da Bold Fed
::msgcat::mcset da {Border Color} {Border Color}
::msgcat::mcset da {Border Width} {Border Width}
::msgcat::mcset da Border Kant
::msgcat::mcset da Bottom Bottom
::msgcat::mcset da {Box Annulus} {Kasseformet ringform}
::msgcat::mcset da {Box Panda} {Kasseformet panda}
::msgcat::mcset da BoxCircle BoxCircle
::msgcat::mcset da Boxcar {Kvadratisk kernel}
::msgcat::mcset da Box Kasse
::msgcat::mcset da {Bring to Front} {Bring to Front}
::msgcat::mcset da Broadcast Broadcast
::msgcat::mcset da Browser Browser
::msgcat::mcset da Browse Browse
::msgcat::mcset da Buffer Buffer
::msgcat::mcset da Buttonbar Buttonbar
::msgcat::mcset da Buttons Knapper
::msgcat::mcset da Bytes Bytes
::msgcat::mcset da CMYK CMYK
::msgcat::mcset da {Can Delete} {Må slette}
::msgcat::mcset da {Can Edit} {Må redigere}
::msgcat::mcset da {Can Move} {Må flytte}
::msgcat::mcset da {Can Rotate} {Må rotere}
::msgcat::mcset da Cancelled Cancelled
::msgcat::mcset da Cancel Slet
::msgcat::mcset da Cap Cap
::msgcat::mcset da {Catalog Server} {Katalog server}
::msgcat::mcset da {Catalog Tool} {Katalog funktion}
::msgcat::mcset da Catalogs Kataloger
::msgcat::mcset da Catalog Katalog
::msgcat::mcset da Catrom Catrom
::msgcat::mcset da Cat Cat
::msgcat::mcset da {Center Dialogs} {Center Dialogs}
::msgcat::mcset da {Center Image} {Centrer billedet}
::msgcat::mcset da Center Centrer
::msgcat::mcset da {Centroid Parameters} {Centroid Parameters}
::msgcat::mcset da Centroid Centroide
::msgcat::mcset da Circle Cirkel
::msgcat::mcset da {Clear All} {Fjern alt}
::msgcat::mcset da {Clear Analysis Commands} {Fjern analyse funktioner}
::msgcat::mcset da {Clear Cache} {Tøm cache}
::msgcat::mcset da {Clear External Analysis Commands?} {Ryd ekstern analyse kommandoer?}
::msgcat::mcset da {Clear Filter} {Fjern filter}
::msgcat::mcset da {Clear Frame} {Ryd ramme}
::msgcat::mcset da {Clear Preferences?} {Nulstil foretrukne?}
::msgcat::mcset da {Clear Preferences} {Nulstil foretrukne}
::msgcat::mcset da Clear Fjern
::msgcat::mcset da {Click to Center} {Klik for centrering}
::msgcat::mcset da Close Luk
::msgcat::mcset da {Colorbar Size} {Colorbar Size}
::msgcat::mcset da Colorbar Farvekode
::msgcat::mcset da {Colormap Parameters} {Farvetabel parametre}
::msgcat::mcset da Colormaps Colormaps
::msgcat::mcset da Colormap Farvetabel
::msgcat::mcset da Color Farve
::msgcat::mcset da Columns Søjler
::msgcat::mcset da Column Søjle
::msgcat::mcset da Comets Comets
::msgcat::mcset da {Command not allowed} {Command not allowed}
::msgcat::mcset da Command Command
::msgcat::mcset da Compass Kompas
::msgcat::mcset da {Composite Region} {Composite Region}
::msgcat::mcset da Composite Sammensat
::msgcat::mcset da Compression Komprimer
::msgcat::mcset da Configure Konfigurer
::msgcat::mcset da Connect Connect
::msgcat::mcset da Console konsol
::msgcat::mcset da {Contacting Server} {Contacting Server}
::msgcat::mcset da {Contour Parameters} {Kontur parametre}
::msgcat::mcset da {Contour Paste} {Contour Paste}
::msgcat::mcset da {Contour Save} {Contour Save}
::msgcat::mcset da Contours Konturer
::msgcat::mcset da Contour Konturer
::msgcat::mcset da Contrast Kontrast
::msgcat::mcset da {Control Panel} {Control Panel}
::msgcat::mcset da {Convert to Polygons} {Omdan til poygoner}
::msgcat::mcset da {Coordinate Grid Parameters} Koordinatnetparametre
::msgcat::mcset da {Coordinate Grid} Koordinatnet
::msgcat::mcset da {Coordinate System} {Koordinat system}
::msgcat::mcset da Coordinates Koordinater
::msgcat::mcset da Coordinate Koordinat
::msgcat::mcset da {Copy Contours} {Kopier konturer}
::msgcat::mcset da {Copy to Regions} {kopier til regioner}
::msgcat::mcset da Copy Kopier
::msgcat::mcset da {Create Composite Region} {Create Composite Region}
::msgcat::mcset da {Create Movie} {Create Movie}
::msgcat::mcset da {Create New Frame on Download} {Dan en ny ramme under hentning}
::msgcat::mcset da Create Create
::msgcat::mcset da {Crop Parameters} {Crop Parameters}
::msgcat::mcset da Crop Crop
::msgcat::mcset da {Crosshair Parameters} {Crosshair Parameters}
::msgcat::mcset da {Crosshair To} {Trådkors til}
::msgcat::mcset da Crosshair Trådkors
::msgcat::mcset da Cross Kryds
::msgcat::mcset da Cubehelix Cubehelix
::msgcat::mcset da Cube Cube
::msgcat::mcset da Cubic Cubic
::msgcat::mcset da {Current Frame} {Denne ramme}
::msgcat::mcset da {Current Range} {Dette interval}
::msgcat::mcset da Current Denne
::msgcat::mcset da Cursor Cursor
::msgcat::mcset da Cut Beskær
::msgcat::mcset da Cyan Cyan
::msgcat::mcset da DMS DMS
::msgcat::mcset da DPI DPI
::msgcat::mcset da {DS9 has detected a newer version of a backup file and therefore will not process this file.} {DS9 has detected a newer version of a backup file and therefore will not process this file.}
::msgcat::mcset da {DS9 has detected a newer version of a preferences file.} {DS9 has detected a newer version of a preferences file.}
::msgcat::mcset da {DS9 has detected an older backup file, do you wish to continue?} {DS9 has detected an older backup file, do you wish to continue?}
::msgcat::mcset da {DS9 has detected an older preferences file, do you wish to update?} {DS9 har fundet en ældre fil med foretrukne indstillinger, ønsker du at opdatere?}
::msgcat::mcset da {DS9 will complete the initialization process} {DS9 vil fuldføre initialiserings processen}
::msgcat::mcset da Darken Darken
::msgcat::mcset da Dash streg
::msgcat::mcset da {Data Format} Dataformat
::msgcat::mcset da {Data must be ascii numeric values} {Data must be ascii numeric values}
::msgcat::mcset da {Dataset Name} {Dataset Name}
::msgcat::mcset da Dataset Datasæt
::msgcat::mcset da Data Data
::msgcat::mcset da {Decrease Bin} {Decrease Bin}
::msgcat::mcset da {Decrease Block} {Decrease Block}
::msgcat::mcset da {Decrease Magnification} {Decrease Magnification}
::msgcat::mcset da {Decrease Zoom} {Decrease Zoom}
::msgcat::mcset da Decrease Aftag
::msgcat::mcset da {Default All Files} {Default All Files}
::msgcat::mcset da {Default Format} {Default Format}
::msgcat::mcset da {Default Length} {Default Length}
::msgcat::mcset da Default Standard
::msgcat::mcset da Degrees Grader
::msgcat::mcset da Delay Delay
::msgcat::mcset da {Delete All Frames?} {Slet alle rammer?}
::msgcat::mcset da {Delete All Frames} {Slet alle rammer}
::msgcat::mcset da {Delete All Groups?} {Slet alle grupper?}
::msgcat::mcset da {Delete All Groups} {Slet alle grupper}
::msgcat::mcset da {Delete All Load} {Delete All Load}
::msgcat::mcset da {Delete All and Open} {Delete All and Open}
::msgcat::mcset da {Delete All} {Slet alt}
::msgcat::mcset da {Delete Color Tags} {Delete Color Tags}
::msgcat::mcset da {Delete Dataset} {Delete Dataset}
::msgcat::mcset da {Delete Frame} {Slet denne ramme}
::msgcat::mcset da {Delete Graph} {Delete Graph}
::msgcat::mcset da {Delete Group} {Slet gruppe}
::msgcat::mcset da {Delete Selection} {Delete Selection}
::msgcat::mcset da {Delete Select} {Delete Select}
::msgcat::mcset da Delete Slet
::msgcat::mcset da Depth Dybde
::msgcat::mcset da Detector Detektor
::msgcat::mcset da {Dialog Box} {Dialog vindue}
::msgcat::mcset da Diameter Diameter
::msgcat::mcset da Diamond Ruder
::msgcat::mcset da Dimensions Dimensions
::msgcat::mcset da Dimension Dimension
::msgcat::mcset da Direction Direction
::msgcat::mcset da Disconnect Disconnect
::msgcat::mcset da {Display Size} {Vis størrelse}
::msgcat::mcset da {Dissolve Composite Region} {Dissolve Composite Region}
::msgcat::mcset da Dissolve Opløs
::msgcat::mcset da Distance Distance
::msgcat::mcset da Done Done
::msgcat::mcset da {Download Colormap} {Download Colormap}
::msgcat::mcset da {Drag to Center} {Træk til center}
::msgcat::mcset da {Duplicate Dataset} {Duplicate Dataset}
::msgcat::mcset da ENVI ENVI
::msgcat::mcset da EPS EPS
::msgcat::mcset da East Øst
::msgcat::mcset da Ecliptic Ekliptisk
::msgcat::mcset da {Edit Group Name} {Rediger gruppe navn}
::msgcat::mcset da {Edit Mode} {Edit Mode}
::msgcat::mcset da Edit Rediger
::msgcat::mcset da Elevation Stigning
::msgcat::mcset da {Ellipse Panda} {Ellipse Panda}
::msgcat::mcset da Ellipse Ellipse
::msgcat::mcset da {Elliptical Annulus} {Elliptisk ringform}
::msgcat::mcset da {Elliptical Gaussian} {Elliptical Gaussian}
::msgcat::mcset da {Elliptical Panda} {Elliptisk pandaform}
::msgcat::mcset da {Enable Confirmation Dialogs} {Aktiver bekræftelsesdialoger}
::msgcat::mcset da Enable Enable
::msgcat::mcset da End Afslut
::msgcat::mcset da {Enter Color} {Angiv farve}
::msgcat::mcset da {Enter Font Size} {Enter Font Size}
::msgcat::mcset da {Enter Group Name} {Indtast gruppenavn}
::msgcat::mcset da {Enter Search Expression} {Angiv søgeudtryk}
::msgcat::mcset da {Enter URL} {Enter URL}
::msgcat::mcset da Entry Entry
::msgcat::mcset da {Equal Area} {Samme areal}
::msgcat::mcset da {Equal Distance} {Samme afstand}
::msgcat::mcset da {Equal Spacing} {Equal Spacing}
::msgcat::mcset da {Equal Value} {Equal Value}
::msgcat::mcset da {Error code was returned} {Fejlkode blev returneret}
::msgcat::mcset da Errorbar Errorbar
::msgcat::mcset da Error Fejl
::msgcat::mcset da {Examine Frame} {Undersøg ramme}
::msgcat::mcset da Examine Undersøg
::msgcat::mcset da Exam Exam
::msgcat::mcset da Exclude Udelad
::msgcat::mcset da Exit Luk
::msgcat::mcset da {Export Array} {Export Array}
::msgcat::mcset da {Export ENVI} {Export ENVI}
::msgcat::mcset da {Export GIF} {Export GIF}
::msgcat::mcset da {Export HLS Array} {Export HLS Array}
::msgcat::mcset da {Export HSV Array} {Export HSV Array}
::msgcat::mcset da {Export JPEG} {Export JPEG}
::msgcat::mcset da {Export NRRD} {Export NRRD}
::msgcat::mcset da {Export PNG} {Export PNG}
::msgcat::mcset da {Export RGB Array} {Export RGB Array}
::msgcat::mcset da {Export TIFF} {Export TIFF}
::msgcat::mcset da Export Export
::msgcat::mcset da {Extension Data} {Extension Data}
::msgcat::mcset da {Extension not found} {Extension not found}
::msgcat::mcset da Extensions Extensions
::msgcat::mcset da Extension Extension
::msgcat::mcset da {Exterior Axes} {Udvendige akser}
::msgcat::mcset da {Exterior Numerics} {Udvendige tal}
::msgcat::mcset da FAQ {Ofte Stillede Spørgsmål}
::msgcat::mcset da FITS FITS
::msgcat::mcset da FK4 FK4
::msgcat::mcset da FK5 FK5
::msgcat::mcset da FP FP
::msgcat::mcset da Factor Factor
::msgcat::mcset da {Fade Frames} {Fade Frames}
::msgcat::mcset da {Fade Interval} {Fade Interval}
::msgcat::mcset da Fade Fade
::msgcat::mcset da {File Open} {File Open}
::msgcat::mcset da {File not Found or Unable to load FITS data MIME type} {Filen blev ikke fundet, eller det var ikke muligt at åbne FITS data MIME filtype}
::msgcat::mcset da {File not found} {File not found}
::msgcat::mcset da {Filename Format} {Filename Format}
::msgcat::mcset da Filename Filnavn
::msgcat::mcset da File Fil
::msgcat::mcset da Fill Fill
::msgcat::mcset da Filter Filter
::msgcat::mcset da {Find Next} {Find næste}
::msgcat::mcset da Find Find
::msgcat::mcset da {First Block} {First Block}
::msgcat::mcset da {First Frame} {Første ramme}
::msgcat::mcset da First Første
::msgcat::mcset da Fits Fits
::msgcat::mcset da {Fixed in Size} {Fastlåst størrelse}
::msgcat::mcset da Flip Flip
::msgcat::mcset da Font Skrifttype
::msgcat::mcset da {Footprint Servers} {Footprint Servers}
::msgcat::mcset da Footprint Footprint
::msgcat::mcset da {For more information, use --help} {For more information, use --help}
::msgcat::mcset da Foreground Foreground
::msgcat::mcset da Forground Forground
::msgcat::mcset da Format Format
::msgcat::mcset da Forward Videre
::msgcat::mcset da {Found Auto Backup, restore?} {Found Auto Backup, restore?}
::msgcat::mcset da Found Fundet
::msgcat::mcset da {Frame Information} {Information for ramme}
::msgcat::mcset da {Frame Layout} {Frame Layout}
::msgcat::mcset da {Frame Parameters} {Frame Parameters}
::msgcat::mcset da Frames Frames
::msgcat::mcset da Frame Ramme
::msgcat::mcset da From From
::msgcat::mcset da Front Foran
::msgcat::mcset da {Full Range} {Hele intervallet}
::msgcat::mcset da Function Funktion
::msgcat::mcset da GIF GIF
::msgcat::mcset da GUI GUI
::msgcat::mcset da Galactic Galaktisk
::msgcat::mcset da Gap Gap
::msgcat::mcset da Gaussian Gaussisk
::msgcat::mcset da General Generel
::msgcat::mcset da Generate Opret
::msgcat::mcset da {Generating Regions} {danner områder}
::msgcat::mcset da {Get Information} {Hent information}
::msgcat::mcset da {Get Region Info} {Get Region Info}
::msgcat::mcset da Gist Gist
::msgcat::mcset da {Global Properties} {Global Properties}
::msgcat::mcset da Global Global
::msgcat::mcset da {Goto First Frame} {Goto First Frame}
::msgcat::mcset da {Goto Frame} {Gå til ramme}
::msgcat::mcset da {Goto Last Frame} {Goto Last Frame}
::msgcat::mcset da {Goto Next Frame} {Goto Next Frame}
::msgcat::mcset da {Goto Previous Frame} {Goto Previous Frame}
::msgcat::mcset da {Goto Row} {Goto Row}
::msgcat::mcset da Goto Goto
::msgcat::mcset da {Graph Horz} {vandret graf}
::msgcat::mcset da {Graph Parameters} {Graph Parameters}
::msgcat::mcset da {Graph Vert} {lodret graf}
::msgcat::mcset da Graphics Grafisk
::msgcat::mcset da Graphs Graphs
::msgcat::mcset da Graph graf
::msgcat::mcset da Grayscale Gråskala
::msgcat::mcset da Green Grøn
::msgcat::mcset da {Grid Gap} {Mellemrum i nettet}
::msgcat::mcset da Grid Net
::msgcat::mcset da Groups Gupper
::msgcat::mcset da {HLS Array} {HLS Array}
::msgcat::mcset da {HLS Cube} {HLS Cube}
::msgcat::mcset da {HLS Image} {HLS Image}
::msgcat::mcset da HLS HLS
::msgcat::mcset da HMS HMS
::msgcat::mcset da {HSV Array} {HSV Array}
::msgcat::mcset da {HSV Cube} {HSV Cube}
::msgcat::mcset da {HSV Image} {HSV Image}
::msgcat::mcset da HSV HSV
::msgcat::mcset da HTTP HTTP
::msgcat::mcset da Header Hovede
::msgcat::mcset da Height Højde
::msgcat::mcset da {Help Desk} Hjælp
::msgcat::mcset da {Help Me Choose} {Hjælp mig at vælge}
::msgcat::mcset da Help Hjælp
::msgcat::mcset da {Hide All} {Gem alle}
::msgcat::mcset da Highlite Highlite
::msgcat::mcset da High Høj
::msgcat::mcset da {Histogram Equalization} {Histogram udligning}
::msgcat::mcset da Histogram Histogram
::msgcat::mcset da {Horizontal Graph} {Vandret graf}
::msgcat::mcset da {Horizontal Layout} {Vandret layout}
::msgcat::mcset da Horizontal Horizontal
::msgcat::mcset da {Hub not running} {Hub not running}
::msgcat::mcset da Hue Hue
::msgcat::mcset da {IAU Location Code} {IAU Location Code}
::msgcat::mcset da ICRS ICRS
::msgcat::mcset da Icons Icons
::msgcat::mcset da Identification Identifikation
::msgcat::mcset da If Hvis
::msgcat::mcset da Illustrate Illustrate
::msgcat::mcset da {Image Servers} {Image Servers}
::msgcat::mcset da Image Billed
::msgcat::mcset da {Import Array} {Import Array}
::msgcat::mcset da {Import ENVI} {Import ENVI}
::msgcat::mcset da {Import GIF} {Import GIF}
::msgcat::mcset da {Import HLS Array} {Import HLS Array}
::msgcat::mcset da {Import HSV Array} {Import HSV Array}
::msgcat::mcset da {Import JPEG} {Import JPEG}
::msgcat::mcset da {Import NRRD} {Import NRRD}
::msgcat::mcset da {Import PNG} {Import PNG}
::msgcat::mcset da {Import RGB Array} {Import RGB Array}
::msgcat::mcset da {Import Slice GIF} {Import Slice GIF}
::msgcat::mcset da {Import Slice JPEG} {Import Slice JPEG}
::msgcat::mcset da {Import Slice PNG} {Import Slice PNG}
::msgcat::mcset da {Import Slice TIFF} {Import Slice TIFF}
::msgcat::mcset da {Import TIFF} {Import TIFF}
::msgcat::mcset da Import Import
::msgcat::mcset da Include Inkluder
::msgcat::mcset da {Increase Bin} {Increase Bin}
::msgcat::mcset da {Increase Block} {Increase Block}
::msgcat::mcset da {Increase Magnification} {Increase Magnification}
::msgcat::mcset da {Increase Zoom} {Increase Zoom}
::msgcat::mcset da Increase Forøg
::msgcat::mcset da {Info Box} {Info Box}
::msgcat::mcset da {Information Panel} {Informations panel}
::msgcat::mcset da Information Information
::msgcat::mcset da {Initialize XPA} {Initialiser XPA}
::msgcat::mcset da Inner Indre
::msgcat::mcset da {Instrument FOV} {Instrument FOV}
::msgcat::mcset da Instrument Instrument
::msgcat::mcset da {Interior Axes} {Indre akser}
::msgcat::mcset da {Interior Numerics} {Indre tal}
::msgcat::mcset da {Internal Parse Error} {Internal Parse Error}
::msgcat::mcset da Interval Interval
::msgcat::mcset da {Invalid Column Name} {Invalid Column Name}
::msgcat::mcset da {Invalid WCS} {Invalid WCS}
::msgcat::mcset da {Invalid formated multipart/mixed mime type message} {Forkert formatteret opdelt eller blandet mime type meddelelse}
::msgcat::mcset da {Invert Colormap} {Vend farvetabel}
::msgcat::mcset da Invert Inverter
::msgcat::mcset da Italic Kursiv
::msgcat::mcset da {Items Found} {Emner fundet}
::msgcat::mcset da Iteration Iteration
::msgcat::mcset da {JPEG Quality Factor} {JPEG kvalitetsfaktor}
::msgcat::mcset da JPEG JPEG
::msgcat::mcset da Justify Justify
::msgcat::mcset da Keep-Alive Keep-Alive
::msgcat::mcset da Keyword Keyword
::msgcat::mcset da Labels Etiketter
::msgcat::mcset da Label Etikette
::msgcat::mcset da Landscape Landskab
::msgcat::mcset da Language Sprog
::msgcat::mcset da {Last Block} {Last Block}
::msgcat::mcset da {Last Frame} {Sidste ramme}
::msgcat::mcset da Last Sidste
::msgcat::mcset da Layout Layout
::msgcat::mcset da Left Left
::msgcat::mcset da Legal Legal
::msgcat::mcset da {Legend Position} {Legend Position}
::msgcat::mcset da {Legend Title} {Legend Title}
::msgcat::mcset da Legend Legend
::msgcat::mcset da Length Længde
::msgcat::mcset da Letter Letter
::msgcat::mcset da Levels Niveauer
::msgcat::mcset da Level Niveau
::msgcat::mcset da Lighten Lighten
::msgcat::mcset da Lightness Lightness
::msgcat::mcset da Limits Grænser
::msgcat::mcset da {Line Dataset} {Line Dataset}
::msgcat::mcset da {Line Plot Tool} {Line Plot Tool}
::msgcat::mcset da Linear Lineær
::msgcat::mcset da Line Linie
::msgcat::mcset da {List Data} {List Data}
::msgcat::mcset da {List Regions} {Vis områder}
::msgcat::mcset da {List Region} {List Region}
::msgcat::mcset da {List Selection} {List Selection}
::msgcat::mcset da {List Select} {List Select}
::msgcat::mcset da List Liste
::msgcat::mcset da {Load Analysis Commands} {Indlæs analyse funktioner}
::msgcat::mcset da {Load Color Tags} {Load Color Tags}
::msgcat::mcset da {Load Contour Levels} {Indlæs konturniveauer}
::msgcat::mcset da {Load Contrast/Bias} {Indlæs kontrast/bias}
::msgcat::mcset da {Load Data} {Indlæs data}
::msgcat::mcset da {Load Mosaic} {Indlæs mosaik}
::msgcat::mcset da {Load Template} {Indlæs skabelon}
::msgcat::mcset da {Load into All} {Load into All}
::msgcat::mcset da {Load into Current} {Load into Current}
::msgcat::mcset da {Loading Catalog} {Loading Catalog}
::msgcat::mcset da Loading Loading
::msgcat::mcset da Load Indlæs
::msgcat::mcset da Local Lokal
::msgcat::mcset da {Lock Axes} {Lock Axes}
::msgcat::mcset da {Lock Bin} {Lock Bin}
::msgcat::mcset da {Lock Color} {Lock Color}
::msgcat::mcset da {Lock Crop Amplifier} {Lock Crop Amplifier}
::msgcat::mcset da {Lock Crop Detector} {Lock Crop Detector}
::msgcat::mcset da {Lock Crop Image} {Lock Crop Image}
::msgcat::mcset da {Lock Crop None} {Lock Crop None}
::msgcat::mcset da {Lock Crop Physical} {Lock Crop Physical}
::msgcat::mcset da {Lock Crop WCS} {Lock Crop WCS}
::msgcat::mcset da {Lock Crosshair Amplifier} {Lock Crosshair Amplifier}
::msgcat::mcset da {Lock Crosshair Detector} {Lock Crosshair Detector}
::msgcat::mcset da {Lock Crosshair Image} {Lock Crosshair Image}
::msgcat::mcset da {Lock Crosshair None} {Lock Crosshair None}
::msgcat::mcset da {Lock Crosshair Physical} {Lock Crosshair Physical}
::msgcat::mcset da {Lock Crosshair WCS} {Lock Crosshair WCS}
::msgcat::mcset da {Lock Frame Amplifier} {Lock Frame Amplifier}
::msgcat::mcset da {Lock Frame Detector} {Lock Frame Detector}
::msgcat::mcset da {Lock Frame Image} {Lock Frame Image}
::msgcat::mcset da {Lock Frame None} {Lock Frame None}
::msgcat::mcset da {Lock Frame Physical} {Lock Frame Physical}
::msgcat::mcset da {Lock Frame WCS} {Lock Frame WCS}
::msgcat::mcset da {Lock Limits} {Lock Limits}
::msgcat::mcset da {Lock Scale} {Lock Scale}
::msgcat::mcset da {Lock Slice Image} {Lock Slice Image}
::msgcat::mcset da {Lock Slice None} {Lock Slice None}
::msgcat::mcset da {Lock Slice WCS} {Lock Slice WCS}
::msgcat::mcset da {Lock Smooth} {Lock Smooth}
::msgcat::mcset da Lock Lås
::msgcat::mcset da {Log Exponent} {Log Exponent}
::msgcat::mcset da Log Log
::msgcat::mcset da {Low High} {Lav høj}
::msgcat::mcset da {Lower Left Back} {Lower Left Back}
::msgcat::mcset da {Lower Left Front} {Lower Left Front}
::msgcat::mcset da {Lower Right Back} {Lower Right Back}
::msgcat::mcset da {Lower Right Front} {Lower Right Front}
::msgcat::mcset da Low lav
::msgcat::mcset da MIP MIP
::msgcat::mcset da Magenta Magenta
::msgcat::mcset da Magnification Magnification
::msgcat::mcset da Magnifier Forstørrelse
::msgcat::mcset da {Major Radius} {Major Radius}
::msgcat::mcset da {Major Sigma} {Major Sigma}
::msgcat::mcset da Major Major
::msgcat::mcset da Manual Manual
::msgcat::mcset da {Mask Parameters} {Maske parametre}
::msgcat::mcset da {Match Axes} {Match Axes}
::msgcat::mcset da {Match Bin} {Match Bin}
::msgcat::mcset da {Match Catalog requires at least 1 row per catalog} {Match Catalog requires at least 1 row per catalog}
::msgcat::mcset da {Match Color} {Match Color}
::msgcat::mcset da {Match Crop Amplifier} {Match Crop Amplifier}
::msgcat::mcset da {Match Crop Detector} {Match Crop Detector}
::msgcat::mcset da {Match Crop Image} {Match Crop Image}
::msgcat::mcset da {Match Crop Physical} {Match Crop Physical}
::msgcat::mcset da {Match Crop WCS} {Match Crop WCS}
::msgcat::mcset da {Match Crosshair Amplifier} {Match Crosshair Amplifier}
::msgcat::mcset da {Match Crosshair Detector} {Match Crosshair Detector}
::msgcat::mcset da {Match Crosshair Image} {Match Crosshair Image}
::msgcat::mcset da {Match Crosshair Physical} {Match Crosshair Physical}
::msgcat::mcset da {Match Crosshair WCS} {Match Crosshair WCS}
::msgcat::mcset da {Match Frame Amplifier} {Match Frame Amplifier}
::msgcat::mcset da {Match Frame Detector} {Match Frame Detector}
::msgcat::mcset da {Match Frame Image} {Match Frame Image}
::msgcat::mcset da {Match Frame Physical} {Match Frame Physical}
::msgcat::mcset da {Match Frame WCS} {Match Frame WCS}
::msgcat::mcset da {Match Frames on WCS} {Match Frames on WCS}
::msgcat::mcset da {Match Limits} {Match Limits}
::msgcat::mcset da {Match Scale} {Match Scale}
::msgcat::mcset da {Match Slice Image} {Match Slice Image}
::msgcat::mcset da {Match Slice WCS} {Match Slice WCS}
::msgcat::mcset da {Match Smooth} {Match Smooth}
::msgcat::mcset da Match Match
::msgcat::mcset da {Math Function} {Matematisk funktion}
::msgcat::mcset da {Matplotlib Cyclic} {Matplotlib Cyclic}
::msgcat::mcset da {Matplotlib Diverging} {Matplotlib Diverging}
::msgcat::mcset da {Matplotlib Sequential} {Matplotlib Sequential}
::msgcat::mcset da {Matplotlib Uniform} {Matplotlib Uniform}
::msgcat::mcset da {Max Rows} {Maks antal rækker}
::msgcat::mcset da Maximum Maximum
::msgcat::mcset da Max Maks
::msgcat::mcset da Median Median
::msgcat::mcset da {Menus and Buttons} {Menus and Buttons}
::msgcat::mcset da Menu Menu
::msgcat::mcset da {Message Log} {Message Log}
::msgcat::mcset da Metadata Metadata
::msgcat::mcset da Method Metode
::msgcat::mcset da {Min Max Parameters} {Min Max Parameters}
::msgcat::mcset da {Min Max} {Min Maks}
::msgcat::mcset da Minimum Minimum
::msgcat::mcset da {Minor Radius} {Minor Radius}
::msgcat::mcset da {Minor Sigma} {Minor Sigma}
::msgcat::mcset da Minor Minor
::msgcat::mcset da Minutes Minutes
::msgcat::mcset da Min Min
::msgcat::mcset da Mission Mission
::msgcat::mcset da Mode Mode
::msgcat::mcset da {Mosaic IRAF Segment} {Mosaic IRAF Segment}
::msgcat::mcset da {Mosaic IRAF} {Mosaic IRAF}
::msgcat::mcset da {Mosaic WCS Segment} {Mosaic WCS Segment}
::msgcat::mcset da {Mosaic WCS} {Mosaic WCS}
::msgcat::mcset da {Mosaic WFPC2} {Mosaic WFPC2}
::msgcat::mcset da Mosaic Mosaic
::msgcat::mcset da {Mouse Click Epsilon} {Mouse Click Epsilon}
::msgcat::mcset da {Mouse Wheel Bin} {Mouse Wheel Bin}
::msgcat::mcset da {Mouse Wheel Zoom} {Mouse Wheel Zoom}
::msgcat::mcset da {Move Back} {flyt tilbage}
::msgcat::mcset da {Move First} {flyt forrest}
::msgcat::mcset da {Move Forward} {flyt frem}
::msgcat::mcset da {Move Frame} {Move Frame}
::msgcat::mcset da {Move Front} {Move Front}
::msgcat::mcset da {Move Last} {flyt sidst}
::msgcat::mcset da {Move to Back} Bag
::msgcat::mcset da {Move to Front} Foran
::msgcat::mcset da Movie Movie
::msgcat::mcset da {Muliple Extension Cube} {Muliple Extension Cube}
::msgcat::mcset da {Muliple Extension Frames} {Muliple Extension Frames}
::msgcat::mcset da {Multi Colorbars} {Multi Colorbars}
::msgcat::mcset da {Multiple Colorbars} {Multiple Colorbars}
::msgcat::mcset da {Multiple Extension Cube} {Multiple Extension Cube}
::msgcat::mcset da {Multiple Extension Frames} {Multiple Extension Frames}
::msgcat::mcset da {Multiple WCS} {Multipel WCS}
::msgcat::mcset da NAN NAN
::msgcat::mcset da NRRD NRRD
::msgcat::mcset da {Name Resolution} Navnesøgning
::msgcat::mcset da {Name Server} Navneserver
::msgcat::mcset da {Name or Designation} {navn eller beskrivelse}
::msgcat::mcset da Name Name
::msgcat::mcset da {Native Dialog} {Oprindelig dialog}
::msgcat::mcset da {New Features} {Nye egenskaber}
::msgcat::mcset da {New Frame 3D} {Ny ramme 3D}
::msgcat::mcset da {New Frame HLS} {New Frame HLS}
::msgcat::mcset da {New Frame HSV} {New Frame HSV}
::msgcat::mcset da {New Frame RGB} {Ny ramme (RGB)}
::msgcat::mcset da {New Frame each Time} {Ny ramme hver gang}
::msgcat::mcset da {New Frame} {Ny ramme}
::msgcat::mcset da {New Graph} {New Graph}
::msgcat::mcset da {New Group} {Ny gruppe}
::msgcat::mcset da {New Plot} {New Plot}
::msgcat::mcset da New Ny
::msgcat::mcset da {Next Block} {Next Block}
::msgcat::mcset da {Next Frame} {Næste ramme}
::msgcat::mcset da Next Næste
::msgcat::mcset da {No Catalog specified} {Intet katalog er specificeret}
::msgcat::mcset da {No Data Available} {No Data Available}
::msgcat::mcset da {No Items Found} {Ingen emner er fundet}
::msgcat::mcset da Non-NAN Non-NAN
::msgcat::mcset da Non-Zero Non-Zero
::msgcat::mcset da None Ingen
::msgcat::mcset da Normal Normal
::msgcat::mcset da North Nord
::msgcat::mcset da {Not Found} {Not Found}
::msgcat::mcset da {Not Supported} {Not Supported}
::msgcat::mcset da {Not valid export format} {Not valid export format}
::msgcat::mcset da Notes Notes
::msgcat::mcset da {Number of Samples} Antal
::msgcat::mcset da {Number of Threads} {Number of Threads}
::msgcat::mcset da {Number of Ticks} {Number of Ticks}
::msgcat::mcset da Number Antal
::msgcat::mcset da Numerics Talværdier
::msgcat::mcset da OK OK
::msgcat::mcset da Object Objekt
::msgcat::mcset da ObsId ObsId
::msgcat::mcset da {Open File} {Åben fil}
::msgcat::mcset da {Open HLS Cube} {Open HLS Cube}
::msgcat::mcset da {Open HLS Image} {Open HLS Image}
::msgcat::mcset da {Open HSV Cube} {Open HSV Cube}
::msgcat::mcset da {Open HSV Image} {Open HSV Image}
::msgcat::mcset da {Open ME Cube} {Open ME Cube}
::msgcat::mcset da {Open ME Frames} {Open ME Frames}
::msgcat::mcset da {Open Mosaic IRAF Seg} {Open Mosaic IRAF Seg}
::msgcat::mcset da {Open Mosaic IRAF} {Open Mosaic IRAF}
::msgcat::mcset da {Open Mosaic WCS Seg} {Open Mosaic WCS Seg}
::msgcat::mcset da {Open Mosaic WCS} {Open Mosaic WCS}
::msgcat::mcset da {Open Mosaic WFPC2} {Open Mosaic WFPC2}
::msgcat::mcset da {Open Notepad} {Open Notepad}
::msgcat::mcset da {Open Prism} {Open Prism}
::msgcat::mcset da {Open RGB Cube} {Open RGB Cube}
::msgcat::mcset da {Open RGB Image} {Open RGB Image}
::msgcat::mcset da {Open Region File} {Open Region File}
::msgcat::mcset da {Open Regions} {Open Regions}
::msgcat::mcset da {Open Slice} {Open Slice}
::msgcat::mcset da {Open TCL Console} {Åben TCL konsol}
::msgcat::mcset da {Open URL} {Åben URL}
::msgcat::mcset da {Open as} {Open as}
::msgcat::mcset da Open Åben
::msgcat::mcset da Operator Operator
::msgcat::mcset da Orientation Orientering
::msgcat::mcset da Origin Origin
::msgcat::mcset da Oscillate Oscillate
::msgcat::mcset da {Other Color} {Other Color}
::msgcat::mcset da {Other Font Size} {Other Font Size}
::msgcat::mcset da Other Anden
::msgcat::mcset da Outer Ydre
::msgcat::mcset da Overplot Overplot
::msgcat::mcset da {Override Color} {Override Color}
::msgcat::mcset da PNG PNG
::msgcat::mcset da {PS Page Setup} {PS side opsætning}
::msgcat::mcset da {PS Print} {PS udskrift}
::msgcat::mcset da {Page Setup} {Side opsætning}
::msgcat::mcset da {Page Source} {Side kilde}
::msgcat::mcset da {Pan To} {Flyt til}
::msgcat::mcset da {Pan Zoom Rotate Parameters} {Flyt Zoom Rotér parametre}
::msgcat::mcset da {Pan Zoom} {Flyt Zoom}
::msgcat::mcset da {Pan then Zoom} {Flyt og derefter zoom}
::msgcat::mcset da {Pan to Center} {Pan to Center}
::msgcat::mcset da Panda Panda
::msgcat::mcset da Panner Oversigtskort
::msgcat::mcset da Pan Flyt
::msgcat::mcset da Parameters Parametre
::msgcat::mcset da Password Kodeord
::msgcat::mcset da {Paste Contours} {Indsæt konturer}
::msgcat::mcset da Paste {Sæt ind}
::msgcat::mcset da Percent Percent
::msgcat::mcset da Physical Fysisk
::msgcat::mcset da {Pixel Distribution} Pixelfordeling
::msgcat::mcset da {Pixel Size} Pixelstørrelse
::msgcat::mcset da {Pixel Table} {Pixel tabel}
::msgcat::mcset da Pixels Pixler
::msgcat::mcset da Planets Planets
::msgcat::mcset da Play Afspil
::msgcat::mcset da {Please Select a Region} {Please Select a Region}
::msgcat::mcset da {Please change the file's permission to disable other users write access. Use anyway?} {Please change the file's permission to disable other users write access. Use anyway?}
::msgcat::mcset da {Please specify instruments} {Please specify instruments}
::msgcat::mcset da {Please specify radius and either name or (ra,dec)} {Please specify radius and either name or (ra,dec)}
::msgcat::mcset da {Please specify width, height, and either name or (ra,dec)} {angiv venligst bredde, højde, og enten navn eller (ra,dec)}
::msgcat::mcset da {Plot 2D} {Plot 2D}
::msgcat::mcset da {Plot 3D} {Plot 3D}
::msgcat::mcset da {Plot Area} {Plot Area}
::msgcat::mcset da {Plot Control Panel} {Plot Control Panel}
::msgcat::mcset da {Plot Tool} {Plot Tool}
::msgcat::mcset da {Plotting Regions} {Plotte områder}
::msgcat::mcset da Plot Plot
::msgcat::mcset da Plus Plus
::msgcat::mcset da Pointer Pegepil
::msgcat::mcset da Points Punkter
::msgcat::mcset da Point Punkt
::msgcat::mcset da Polygon Polygon
::msgcat::mcset da Portrait Portræt
::msgcat::mcset da Position Position
::msgcat::mcset da Poster Plakat
::msgcat::mcset da Postscript Postscript
::msgcat::mcset da Power Potenslov
::msgcat::mcset da Precision Precision
::msgcat::mcset da Preferences Foretrukne
::msgcat::mcset da {Preserve During Load} {Bevar under indlæsning}
::msgcat::mcset da {Previous Block} {Previous Block}
::msgcat::mcset da {Previous Frame} {Foregående ramme}
::msgcat::mcset da Previous Foregående
::msgcat::mcset da Prev Prev
::msgcat::mcset da {Print Coordinates} {Udskriv koordinater}
::msgcat::mcset da {Print To} {Udskriv til}
::msgcat::mcset da Printer Printer
::msgcat::mcset da Print Udskriv
::msgcat::mcset da {Prism Goto} {Prism Goto}
::msgcat::mcset da Prism Prism
::msgcat::mcset da Projection Projektion
::msgcat::mcset da Properties Egenskaber
::msgcat::mcset da Property Egenskab
::msgcat::mcset da {Proxy Host} {Proxy Host}
::msgcat::mcset da {Proxy Port} {Proxy Port}
::msgcat::mcset da {Public ID} {Public ID}
::msgcat::mcset da Publication Publikation
::msgcat::mcset da Quadratic Kvadratisk
::msgcat::mcset da RDB RDB
::msgcat::mcset da {RGB Array} {RGB Array}
::msgcat::mcset da {RGB Cube} {RGB Cube}
::msgcat::mcset da {RGB Image} {RGB Image}
::msgcat::mcset da RGB RGB
::msgcat::mcset da {Radial Profile} {Radial Profile}
::msgcat::mcset da Radius Radius
::msgcat::mcset da Range Range
::msgcat::mcset da Redo {Gentag sidste}
::msgcat::mcset da Red Rød
::msgcat::mcset da {Reference Manual} {Reference Manual}
::msgcat::mcset da Reference Reference
::msgcat::mcset da {Refresh Frame} {Opdater ramme}
::msgcat::mcset da Refresh Opdater
::msgcat::mcset da {Region Color} {Region Color}
::msgcat::mcset da {Region Line Width} {Region Line Width}
::msgcat::mcset da {Region Parameters} {Region Parameters}
::msgcat::mcset da {Region Shape} {Region Shape}
::msgcat::mcset da Region Område
::msgcat::mcset da Registration Registration
::msgcat::mcset da {Release Notes} Frigvelsesnoter
::msgcat::mcset da Release Frigivelsesnoter
::msgcat::mcset da Reload Genhent
::msgcat::mcset da Render Render
::msgcat::mcset da Repeat Repeat
::msgcat::mcset da {Reset Colormap} {Nulstil farvetabel}
::msgcat::mcset da {Reset Frame} {Nulstil ramme}
::msgcat::mcset da Reset Nulstil
::msgcat::mcset da Restore Restore
::msgcat::mcset da Retrieve Hent
::msgcat::mcset da Return Return
::msgcat::mcset da Right Right
::msgcat::mcset da Roman Roman
::msgcat::mcset da Rotate Roter
::msgcat::mcset da Rows Rækker
::msgcat::mcset da Row Row
::msgcat::mcset da Ruler Lineal
::msgcat::mcset da {SAMP Connect} {SAMP Connect}
::msgcat::mcset da {SAMP Disconnect} {SAMP Disconnect}
::msgcat::mcset da {SAMP Hub Start} {SAMP Hub Start}
::msgcat::mcset da {SAMP Hub Stop} {SAMP Hub Stop}
::msgcat::mcset da {SAMP Hub} {SAMP Hub}
::msgcat::mcset da {SAMP Table} {SAMP Table}
::msgcat::mcset da {SAMP WebHub Start} {SAMP WebHub Start}
::msgcat::mcset da {SAMP: not connected} {SAMP: not connected}
::msgcat::mcset da SAMP SAMP
::msgcat::mcset da {Sample Increment} {Sample Increment}
::msgcat::mcset da {Sample Parameters} {Sample Parameters}
::msgcat::mcset da {Samples per Line} {Udvalg per linie}
::msgcat::mcset da Sample Sample
::msgcat::mcset da Saturation Saturation
::msgcat::mcset da {Save 3D Movie} {Save 3D Movie}
::msgcat::mcset da {Save Color Tags} {Save Color Tags}
::msgcat::mcset da {Save Contour Levels} {Gem konturniveauer}
::msgcat::mcset da {Save Contrast/Bias} {Gem kontrast/bias}
::msgcat::mcset da {Save Data} {Gem data}
::msgcat::mcset da {Save HLS Cube} {Save HLS Cube}
::msgcat::mcset da {Save HLS Image} {Save HLS Image}
::msgcat::mcset da {Save HSV Cube} {Save HSV Cube}
::msgcat::mcset da {Save HSV Image} {Save HSV Image}
::msgcat::mcset da {Save Image EPS} {Save Image EPS}
::msgcat::mcset da {Save Image FITS} {Save Image FITS}
::msgcat::mcset da {Save Image GIF} {Save Image GIF}
::msgcat::mcset da {Save Image JPEG} {Save Image JPEG}
::msgcat::mcset da {Save Image PNG} {Save Image PNG}
::msgcat::mcset da {Save Image TIFF} {Save Image TIFF}
::msgcat::mcset da {Save Image on Download} {Save Image on Download}
::msgcat::mcset da {Save Image} {Gem billede}
::msgcat::mcset da {Save ME Cube} {Save ME Cube}
::msgcat::mcset da {Save Mosaic WCS Seg} {Save Mosaic WCS Seg}
::msgcat::mcset da {Save Mosaic WCS} {Save Mosaic WCS}
::msgcat::mcset da {Save RGB Cube} {Save RGB Cube}
::msgcat::mcset da {Save RGB Image} {Save RGB Image}
::msgcat::mcset da {Save Region File} {Save Region File}
::msgcat::mcset da {Save Regions} {Gem områder}
::msgcat::mcset da {Save Selection} {Save Selection}
::msgcat::mcset da {Save Select} {Save Select}
::msgcat::mcset da {Save Slice} {Save Slice}
::msgcat::mcset da {Save Template} {Gem skabelon}
::msgcat::mcset da {Save as EPS} {Save as EPS}
::msgcat::mcset da {Save as PNG} {Save as PNG}
::msgcat::mcset da {Save as} {Save as}
::msgcat::mcset da Save Gem
::msgcat::mcset da {Scale Parameters} {Skala parametre}
::msgcat::mcset da {Scale and Limits} {Scale and Limits}
::msgcat::mcset da Scale Skala
::msgcat::mcset da {Scaling Option} {Scaling Option}
::msgcat::mcset da {Scaling Parameters} {Scaling Parameters}
::msgcat::mcset da Scan skan
::msgcat::mcset da {Scatter Dataset} {Scatter Dataset}
::msgcat::mcset da {Scatter Plot Tool} {Scatter Plot Tool}
::msgcat::mcset da {Scientific Colour Maps} {Scientific Colour Maps}
::msgcat::mcset da Scope Gældende
::msgcat::mcset da Screen Screen
::msgcat::mcset da {Search for Catalogs} {søg efter kataloger}
::msgcat::mcset da Seconds Sekunder
::msgcat::mcset da Second Second
::msgcat::mcset da Segment Segment
::msgcat::mcset da {Select All} {Vælg alle}
::msgcat::mcset da {Select Coordinate System } {vælg koordinat system}
::msgcat::mcset da {Select Dataset} {Select Dataset}
::msgcat::mcset da {Select Datatset} {Select Datatset}
::msgcat::mcset da {Select Graph} {Select Graph}
::msgcat::mcset da {Select None} {Vælg ingen}
::msgcat::mcset da {Send to Back} {Send to Back}
::msgcat::mcset da Send Send
::msgcat::mcset da Server Server
::msgcat::mcset da {Set Bin to 1} {Set Bin to 1}
::msgcat::mcset da {Set Block to 1} {Set Block to 1}
::msgcat::mcset da {Set Zoom to 1} {Set Zoom to 1}
::msgcat::mcset da Sexagesimal Sexagesimal
::msgcat::mcset da Shadow Shadow
::msgcat::mcset da Shape Form
::msgcat::mcset da {Show All} {Vis alle}
::msgcat::mcset da {Show Command} {Show Command}
::msgcat::mcset da {Show Compass} {Show Compass}
::msgcat::mcset da {Show Legend} {Show Legend}
::msgcat::mcset da {Show Text} {Vis tekst}
::msgcat::mcset da {Show/Hide Frames} {Vis/skjul rammer}
::msgcat::mcset da Show Vis
::msgcat::mcset da {Simple Cross} {Simple Cross}
::msgcat::mcset da {Simple Image Access} {Simple Image Access}
::msgcat::mcset da {Simple Plus} {Simple Plus}
::msgcat::mcset da {Single Frame} {Enkel ramme}
::msgcat::mcset da Single Enkel
::msgcat::mcset da Sites Sites
::msgcat::mcset da Size/Radius Størrelse/Radius
::msgcat::mcset da Size Størrelse
::msgcat::mcset da {Skip First} {Overspring første}
::msgcat::mcset da Slice Slice
::msgcat::mcset da {Smooth Parameters} Udglatningsparametre
::msgcat::mcset da Smoothness Smoothness
::msgcat::mcset da Smooth Udglat
::msgcat::mcset da {Sorry, DS9 does not support} {DS9 understøtter ikke}
::msgcat::mcset da {Sorry, DS9 requires a Truecolor8, Truecolor16, Truecolor24 visual be available} {Sorry, DS9 requires a Truecolor8, Truecolor16, Truecolor24 visual be available}
::msgcat::mcset da Sort Sorter
::msgcat::mcset da {Source TCL} {Kilde TCL}
::msgcat::mcset da Source Kilde
::msgcat::mcset da {Space Equal Distance} {Space Equal Distance}
::msgcat::mcset da {Space Equal Value} {Space Equal Value}
::msgcat::mcset da Spacing Mellemrum
::msgcat::mcset da Sqrt Sqrt
::msgcat::mcset da {Square Root} Kvadratrod
::msgcat::mcset da Squared Kvadratisk
::msgcat::mcset da Square Square
::msgcat::mcset da Starbase Starbase
::msgcat::mcset da Startup Startup
::msgcat::mcset da Start Start
::msgcat::mcset da Statistics Statistics
::msgcat::mcset da Status Status
::msgcat::mcset da Step Trin
::msgcat::mcset da Stop Stop
::msgcat::mcset da {Story of SAOImageDS9} {Story of SAOImageDS9}
::msgcat::mcset da Story Story
::msgcat::mcset da {Strip Parameters} {Strip Parameters}
::msgcat::mcset da {Strip Scale} {Strip Scale}
::msgcat::mcset da Strip Strip
::msgcat::mcset da Subscriptions Subscriptions
::msgcat::mcset da Sum Sum
::msgcat::mcset da {Symbol Editor} {Symbol Editor}
::msgcat::mcset da Symbol Symbol
::msgcat::mcset da TIFF TIFF
::msgcat::mcset da TSV TSV
::msgcat::mcset da Tab-Separated-Value Tab-Separated-Value
::msgcat::mcset da Table Table
::msgcat::mcset da Tabloid Tabloid
::msgcat::mcset da {Tag Color} {Tag Color}
::msgcat::mcset da {Tag New Region Group} {Tag New Region Group}
::msgcat::mcset da Template Template
::msgcat::mcset da Text Tekst
::msgcat::mcset da Theme Theme
::msgcat::mcset da Then Så
::msgcat::mcset da Thickness Tykkelse
::msgcat::mcset da {This analysis task is already running. Do you wish to kill it?} {Denne analyseopgave kører allerede - skal den stoppes?}
::msgcat::mcset da {This function is not available.} {This function is not available.}
::msgcat::mcset da {This function is not currently supported for this port.} {This function is not currently supported for this port.}
::msgcat::mcset da Tickmarks Afmærkninger
::msgcat::mcset da {Tile Frames} {Mosaik rammer}
::msgcat::mcset da {Tile Parameters} {Mosaik parametre}
::msgcat::mcset da Tile Mosaik
::msgcat::mcset da Times Times
::msgcat::mcset da Titles Titles
::msgcat::mcset da Title Titel
::msgcat::mcset da {Toggle Colorbar} {Toggle Colorbar}
::msgcat::mcset da {Toggle Contour} {Toggle Contour}
::msgcat::mcset da {Toggle Coordinate Grid} {Toggle Coordinate Grid}
::msgcat::mcset da {Toggle Horizontal Graph} {Toggle Horizontal Graph}
::msgcat::mcset da {Toggle Include/Exclude} {Toggle Include/Exclude}
::msgcat::mcset da {Toggle Smooth} {Toggle Smooth}
::msgcat::mcset da {Toggle Source/Background} {Toggle Source/Background}
::msgcat::mcset da {Toggle Vertical Graph} {Toggle Vertical Graph}
::msgcat::mcset da Tophat Tophat
::msgcat::mcset da Topographic Topographic
::msgcat::mcset da Top Top
::msgcat::mcset da To Til
::msgcat::mcset da Transition Transition
::msgcat::mcset da Transparency Transparency
::msgcat::mcset da Triangle Triangle
::msgcat::mcset da Type Type
::msgcat::mcset da URL URL
::msgcat::mcset da {Unable to connect directly: using Web Proxy} {Unable to connect directly: using Web Proxy}
::msgcat::mcset da {Unable to create FOV Region, celestial WCS Required} {Unable to create FOV Region, celestial WCS Required}
::msgcat::mcset da {Unable to determine date of observation} {Unable to determine date of observation}
::msgcat::mcset da {Unable to evaluate filter} {kan ikke bestemme filter}
::msgcat::mcset da {Unable to find Footprint window} {Unable to find Footprint window}
::msgcat::mcset da {Unable to find PRISM window} {Unable to find PRISM window}
::msgcat::mcset da {Unable to find SIAP window} {Unable to find SIAP window}
::msgcat::mcset da {Unable to find URL column} {Unable to find URL column}
::msgcat::mcset da {Unable to find catalog window} {Kan ikke finde katalog vinduet}
::msgcat::mcset da {Unable to find plot window} {kan ikke finde plotte vinduet}
::msgcat::mcset da {Unable to find web window} {Unable to find web window}
::msgcat::mcset da {Unable to generate plot} {Unable to generate plot}
::msgcat::mcset da {Unable to load FITS file} {Unable to load FITS file}
::msgcat::mcset da {Unable to load HLS image into a non-hls frame} {Unable to load HLS image into a non-hls frame}
::msgcat::mcset da {Unable to load HSV image into a non-hsv frame} {Unable to load HSV image into a non-hsv frame}
::msgcat::mcset da {Unable to load RGB image into a non-rgb frame} {Kan ikke hente et RGB billede ind i en ikke-RGB ramme}
::msgcat::mcset da {Unable to load compressed region file} {Unable to load compressed region file}
::msgcat::mcset da {Unable to load plot data} {Unable to load plot data}
::msgcat::mcset da {Unable to load region file} {Unable to load region file}
::msgcat::mcset da {Unable to load} {Kan ikke hente}
::msgcat::mcset da {Unable to locate FOV Region} {Unable to locate FOV Region}
::msgcat::mcset da {Unable to locate URL} {Kan ikke finde URL}
::msgcat::mcset da {Unable to match target with XPA Mime request} {Unable to match target with XPA Mime request}
::msgcat::mcset da {Unable to open file} {Kan ikke åbne fil}
::msgcat::mcset da {Unable to save HLS image from a non-hls frame} {Unable to save HLS image from a non-hls frame}
::msgcat::mcset da {Unable to save HSV image from a non-hsv frame} {Unable to save HSV image from a non-hsv frame}
::msgcat::mcset da {Unable to save RGB image from a non-rgb frame} {Unable to save RGB image from a non-rgb frame}
::msgcat::mcset da Undo Fortryd
::msgcat::mcset da Unique Unique
::msgcat::mcset da Units Enheder
::msgcat::mcset da {Unknown Colormap} {Unknown Colormap}
::msgcat::mcset da {Unknown command} {Unknown command}
::msgcat::mcset da {Update Filter} {Update Filter}
::msgcat::mcset da {Update Group} {Opdater gruppe}
::msgcat::mcset da {Update from Current Crosshair} {Opdater fra nuværende trådkors}
::msgcat::mcset da {Update from Current Frame} {Opdater fra nuværende ramme}
::msgcat::mcset da Update Opdater
::msgcat::mcset da {Upper Left Back} {Upper Left Back}
::msgcat::mcset da {Upper Left Front} {Upper Left Front}
::msgcat::mcset da {Upper Right Back} {Upper Right Back}
::msgcat::mcset da {Upper Right Front} {Upper Right Front}
::msgcat::mcset da {Use Authentication} {Anvend bekræftelse}
::msgcat::mcset da {Use Current Frame on Download} {Brug nuværende ramme til download}
::msgcat::mcset da {Use Internal Web Browser} {Brug intern web browser}
::msgcat::mcset da {Use Original Color/Width} {Use Original Color/Width}
::msgcat::mcset da {Use Proxy} {Anvend proxy}
::msgcat::mcset da {Use Theme Colors} {Use Theme Colors}
::msgcat::mcset da {Use background color instead of theme color} {Use background color instead of theme color}
::msgcat::mcset da {User Manual} {User Manual}
::msgcat::mcset da Username Brugernavn
::msgcat::mcset da User Brugerdefineret
::msgcat::mcset da Use Anvend
::msgcat::mcset da {VO Server} {VO Server}
::msgcat::mcset da VOTable VOTable
::msgcat::mcset da VOT VOT
::msgcat::mcset da VO VO
::msgcat::mcset da Value Værdi
::msgcat::mcset da Vector Vektor
::msgcat::mcset da {Vertical Graph} {Lodret graf}
::msgcat::mcset da {Vertical Layout} {Lodret layoyt}
::msgcat::mcset da {Vertical Text} {Lodret tekst}
::msgcat::mcset da Vertical Vertical
::msgcat::mcset da View Vis
::msgcat::mcset da {Virtual Observatory} {Virtuelt Observatorium}
::msgcat::mcset da {WCS Parameters} {WCS Parameters}
::msgcat::mcset da WCS WCS
::msgcat::mcset da Wavelength Bølgelængde
::msgcat::mcset da {Web Browser} {Web Browser}
::msgcat::mcset da White Hvid
::msgcat::mcset da Width Bredde
::msgcat::mcset da Window Window
::msgcat::mcset da {Words matching title, description} {Ord tilpasset titel, beskrivelse }
::msgcat::mcset da {X Axis Title} {X Axis Title}
::msgcat::mcset da {X Axis} {X Axis}
::msgcat::mcset da {X Column} {X Column}
::msgcat::mcset da {X Error Column} {X Error Column}
::msgcat::mcset da {XPA Information} {XPA information}
::msgcat::mcset da {XPA not initialized} {XPA ikke startet}
::msgcat::mcset da XPA XPA
::msgcat::mcset da X X
::msgcat::mcset da {Y Axis Title} {Y Axis Title}
::msgcat::mcset da {Y Axis} {Y Axis}
::msgcat::mcset da {Y Column} {Y Column}
::msgcat::mcset da {Y Error Column} {Y Error Column}
::msgcat::mcset da Yellow Gul
::msgcat::mcset da Y Y
::msgcat::mcset da {Z Axis Scale} {Z Axis Scale}
::msgcat::mcset da {ZScale Parameters} {ZScale Parameters}
::msgcat::mcset da Zero Nul
::msgcat::mcset da {Zoom Fit} {Zoom Fit}
::msgcat::mcset da {Zoom In} {Zoom ind}
::msgcat::mcset da {Zoom Out} {Zoom ud}
::msgcat::mcset da Zoom Zoom
::msgcat::mcset da {already connected} {already connected}
::msgcat::mcset da and and
::msgcat::mcset da b b
::msgcat::mcset da {found dead hub file, deleting} {found dead hub file, deleting}
::msgcat::mcset da {found existing hub} {found existing hub}
::msgcat::mcset da {full base} {full base}
::msgcat::mcset da full full
::msgcat::mcset da g g
::msgcat::mcset da h5utils h5utils
::msgcat::mcset da {hundredths second} {hundredths second}
::msgcat::mcset da h h
::msgcat::mcset da l l
::msgcat::mcset da minutes minutes
::msgcat::mcset da {not connected} {not connected}
::msgcat::mcset da not not
::msgcat::mcset da only only
::msgcat::mcset da {or center of data} {eller center for data}
::msgcat::mcset da {root base} {root base}
::msgcat::mcset da root root
::msgcat::mcset da {rows of data have been downloaded. More may be available. You may wish to adjust the maximum allowed} {rækker af data er blevet hentet. Der kan være flere tilgængelige. Du bør måske ændre det maksimalt tilladte antal}
::msgcat::mcset da r r
::msgcat::mcset da s s
::msgcat::mcset da {unable to create hub file} {unable to create hub file}
::msgcat::mcset da {unable to locate HUB} {unable to locate HUB}
::msgcat::mcset da {unable to open hub} {unable to open hub}
::msgcat::mcset da {unable to open web hub} {unable to open web hub}
::msgcat::mcset da v v
::msgcat::mcset da x x
