# Clean UTF-8 Translation Catalog for Tcl 9
# Generated automatically from legacy de.msg

::msgcat::mcset de 2d 2d
::msgcat::mcset de 3d 3d
::msgcat::mcset de {A postscript generation error has occurred} {Beim Erstellen von Postscript ist ein Fehler aufgetreten}
::msgcat::mcset de AIP AIP
::msgcat::mcset de Abort Abort
::msgcat::mcset de {About SAOImageDS9} {About SAOImageDS9}
::msgcat::mcset de About Über
::msgcat::mcset de Acknowledgment Danksagung
::msgcat::mcset de {Add Bar Graph} {Add Bar Graph}
::msgcat::mcset de {Add Graph} {Add Graph}
::msgcat::mcset de {Add Line Graph} {Add Line Graph}
::msgcat::mcset de {Add New Frame} {Add New Frame}
::msgcat::mcset de Add Hinzufügen
::msgcat::mcset de {Advanced Layout} {Advanced Layout}
::msgcat::mcset de Advanced Erweitert
::msgcat::mcset de {Align North Up} {Align North Up}
::msgcat::mcset de Align Ausrichten
::msgcat::mcset de {All Columns} {Alle spalten}
::msgcat::mcset de {All Rows} {Alle zeilen}
::msgcat::mcset de All Alles
::msgcat::mcset de {Always save files during Backup} {Always save files during Backup}
::msgcat::mcset de Amplifier Verstärker
::msgcat::mcset de {An error has occurred during backup} {An error has occurred during backup}
::msgcat::mcset de {An error has occurred during restore} {An error has occurred during restore}
::msgcat::mcset de {An error has occurred invoking the Analysis task} {Beim Aufrufen des Analysetasks ist ein Fehler aufgetreten}
::msgcat::mcset de {An error has occurred while creating} {An error has occurred while creating}
::msgcat::mcset de {An error has occurred while loading} {An error has occurred while loading}
::msgcat::mcset de {An error has occurred while printing} {Beim Drucken ist ein Fehler aufgetreten}
::msgcat::mcset de {An error has occurred while saving} {Beim Speichern ist ein Fehler aufgetreten}
::msgcat::mcset de {An internal error has been detected} {An internal error has been detected}
::msgcat::mcset de {Analysis Command Log} Analysebefehlslog
::msgcat::mcset de {Analysis Commands} {Analysis Commands}
::msgcat::mcset de {Analysis File} {Analysis File}
::msgcat::mcset de {Analysis Log} {Analysis Log}
::msgcat::mcset de Analysis Analyse
::msgcat::mcset de {Angle Complement} Komplementwinkel
::msgcat::mcset de Angles Winkel
::msgcat::mcset de Angle Winkel
::msgcat::mcset de Annuli Kreisringe
::msgcat::mcset de Annulus Kreisring
::msgcat::mcset de Apply Anwenden
::msgcat::mcset de ArcMin Bogenminute
::msgcat::mcset de ArcSec Bogensekunde
::msgcat::mcset de Architecture Architektur
::msgcat::mcset de Archives Archives
::msgcat::mcset de Array Array
::msgcat::mcset de Arrow Pfeil
::msgcat::mcset de Asteroids Asteroids
::msgcat::mcset de Astronomy Astronomy
::msgcat::mcset de {At Startup} {At Startup}
::msgcat::mcset de {At least 2 different catalogs are required} {At least 2 different catalogs are required}
::msgcat::mcset de {Auto Centroid} {Auto Centroid}
::msgcat::mcset de {Auto Plot 2D} {Auto Plot 2D}
::msgcat::mcset de {Auto Plot 3D} {Auto Plot 3D}
::msgcat::mcset de {Auto Plot Statistics} {Auto Plot Statistics}
::msgcat::mcset de {Auto Plot} {Auto Plot}
::msgcat::mcset de {Auto Recovery} {Auto Recovery}
::msgcat::mcset de {Autoload FITS Regions} {FITS-Regionen autom. laden}
::msgcat::mcset de Autoload Autoload
::msgcat::mcset de Automatic Automatisch
::msgcat::mcset de Average Mitteln
::msgcat::mcset de {Axes Number} {Axes Number}
::msgcat::mcset de {Axes Order} {Axes Order}
::msgcat::mcset de {Axes Range} {Axes Range}
::msgcat::mcset de {Axes Title} {Axes Title}
::msgcat::mcset de Axes Achsen
::msgcat::mcset de {Axis Length} Achsenlänge
::msgcat::mcset de {Axis Numbers} Achsenziffern
::msgcat::mcset de {Axis Title} {Axis Title}
::msgcat::mcset de Axis Achse
::msgcat::mcset de Azimuth Azimuth
::msgcat::mcset de {Background Color} Hintergrundfarbe
::msgcat::mcset de Background Hintergrund
::msgcat::mcset de Backup Backup
::msgcat::mcset de Back Zurück
::msgcat::mcset de {Bar Dataset} {Bar Dataset}
::msgcat::mcset de {Bar Plot Tool} {Bar Plot Tool}
::msgcat::mcset de {Bar Width} {Bar Width}
::msgcat::mcset de Bar Bar
::msgcat::mcset de {Basic Layout} {Basic Layout}
::msgcat::mcset de Basic Basic
::msgcat::mcset de Behavior Behavior
::msgcat::mcset de Bias Bias
::msgcat::mcset de {Bin 3rd Column} {Bin 3. Spalte}
::msgcat::mcset de {Bin Center} {Bin Zentrum}
::msgcat::mcset de {Bin Columns} {Bin Spalten}
::msgcat::mcset de {Bin Filter} {Bin Filter}
::msgcat::mcset de {Bin Fit} {Bin Fit}
::msgcat::mcset de {Bin In} {Bin In}
::msgcat::mcset de {Bin Out} {Bin Out}
::msgcat::mcset de {Binning Parameters} Binparameter
::msgcat::mcset de Bins Bins
::msgcat::mcset de Bin Bin
::msgcat::mcset de Black Schwarz
::msgcat::mcset de {Blank/Inf/NaN Color} {Leer/Inf/Nan Farbe}
::msgcat::mcset de Blend Blend
::msgcat::mcset de {Blink Frames} {Blinkende rahmen}
::msgcat::mcset de {Blink Interval} Blinkinterval
::msgcat::mcset de Blink Blinken
::msgcat::mcset de {Block Fit} {Block Fit}
::msgcat::mcset de {Block In} {Bin ein}
::msgcat::mcset de {Block Out} {Bin aus}
::msgcat::mcset de {Block Parameters} {Block Parameters}
::msgcat::mcset de {Block Pixel} {Block Pixel}
::msgcat::mcset de Block Bin
::msgcat::mcset de Blue Blau
::msgcat::mcset de Bold Fett
::msgcat::mcset de {Border Color} {Border Color}
::msgcat::mcset de {Border Width} {Border Width}
::msgcat::mcset de Border Begrenzung
::msgcat::mcset de Bottom Bottom
::msgcat::mcset de {Box Annulus} {Viereck ring}
::msgcat::mcset de {Box Panda} {Viereckiger panda}
::msgcat::mcset de BoxCircle BoxCircle
::msgcat::mcset de Boxcar Boxcar
::msgcat::mcset de Box Viereck
::msgcat::mcset de {Bring to Front} {Bring to Front}
::msgcat::mcset de Broadcast Broadcast
::msgcat::mcset de Browser Browser
::msgcat::mcset de Browse Auswählen
::msgcat::mcset de Buffer Puffer
::msgcat::mcset de Buttonbar Buttonbar
::msgcat::mcset de Buttons Schaltflächen
::msgcat::mcset de Bytes Bytes
::msgcat::mcset de CMYK CMYK
::msgcat::mcset de {Can Delete} {Kann löschen}
::msgcat::mcset de {Can Edit} {Kann bearbeiten}
::msgcat::mcset de {Can Move} {Kann bewegen}
::msgcat::mcset de {Can Rotate} {Kann rotieren}
::msgcat::mcset de Cancelled Cancelled
::msgcat::mcset de Cancel Abbrechen
::msgcat::mcset de Cap Cap
::msgcat::mcset de {Catalog Server} Katalogserver
::msgcat::mcset de {Catalog Tool} Katalogwerkzeug
::msgcat::mcset de Catalogs Kataloge
::msgcat::mcset de Catalog Katalog
::msgcat::mcset de Catrom Catrom
::msgcat::mcset de Cat Cat
::msgcat::mcset de {Center Dialogs} {Center Dialogs}
::msgcat::mcset de {Center Image} {Bild zentrieren}
::msgcat::mcset de Center Mittelpunkt
::msgcat::mcset de {Centroid Parameters} {Centroid Parameters}
::msgcat::mcset de Centroid Centroid
::msgcat::mcset de Circle Kreis
::msgcat::mcset de {Clear All} {Alle löschen}
::msgcat::mcset de {Clear Analysis Commands} {Analysebefehle löschen}
::msgcat::mcset de {Clear Cache} {Cache löschen}
::msgcat::mcset de {Clear External Analysis Commands?} {Externe Analysebefehle löschen?}
::msgcat::mcset de {Clear Filter} {Filter löschen}
::msgcat::mcset de {Clear Frame} {Rahmen freigeben}
::msgcat::mcset de {Clear Preferences?} {Voreinstellungen löschen?}
::msgcat::mcset de {Clear Preferences} {Voreinstellungen löschen}
::msgcat::mcset de Clear Löschen
::msgcat::mcset de {Click to Center} {Klicken zum Zentrieren}
::msgcat::mcset de Close Schließen
::msgcat::mcset de {Colorbar Size} {Colorbar Size}
::msgcat::mcset de Colorbar Farbbalken
::msgcat::mcset de {Colormap Parameters} Farbpalettenparameter
::msgcat::mcset de Colormaps Colormaps
::msgcat::mcset de Colormap Colormap
::msgcat::mcset de Color Farbe
::msgcat::mcset de Columns Spalten
::msgcat::mcset de Column Spalte
::msgcat::mcset de Comets Comets
::msgcat::mcset de {Command not allowed} {Command not allowed}
::msgcat::mcset de Command Command
::msgcat::mcset de Compass Kompass
::msgcat::mcset de {Composite Region} {Composite Region}
::msgcat::mcset de Composite Composite
::msgcat::mcset de Compression Kompression
::msgcat::mcset de Configure Konfigurieren
::msgcat::mcset de Connect Connect
::msgcat::mcset de Console Console
::msgcat::mcset de {Contacting Server} {Contacting Server}
::msgcat::mcset de {Contour Parameters} Konturenparameter
::msgcat::mcset de {Contour Paste} {Contour Paste}
::msgcat::mcset de {Contour Save} {Contour Save}
::msgcat::mcset de Contours Konturen
::msgcat::mcset de Contour Contour
::msgcat::mcset de Contrast Kontrast
::msgcat::mcset de {Control Panel} {Control Panel}
::msgcat::mcset de {Convert to Polygons} {Zu Polygonen konvertieren}
::msgcat::mcset de {Coordinate Grid Parameters} Koordinatennetzparameter
::msgcat::mcset de {Coordinate Grid} Koordinatennetz
::msgcat::mcset de {Coordinate System} Koordinatensystem
::msgcat::mcset de Coordinates Coordinates
::msgcat::mcset de Coordinate Koordinaten
::msgcat::mcset de {Copy Contours} {Konturen kopieren}
::msgcat::mcset de {Copy to Regions} {Zu Regionen kopieren}
::msgcat::mcset de Copy Kopieren
::msgcat::mcset de {Create Composite Region} {Create Composite Region}
::msgcat::mcset de {Create Movie} {Create Movie}
::msgcat::mcset de {Create New Frame on Download} {Neuen rahmen bei Download}
::msgcat::mcset de Create Create
::msgcat::mcset de {Crop Parameters} {Crop Parameters}
::msgcat::mcset de Crop Crop
::msgcat::mcset de {Crosshair Parameters} {Crosshair Parameters}
::msgcat::mcset de {Crosshair To} {Fadenkreuz auf}
::msgcat::mcset de Crosshair Fadenkreuz
::msgcat::mcset de Cross Kreuz
::msgcat::mcset de Cubehelix Cubehelix
::msgcat::mcset de Cube Cube
::msgcat::mcset de Cubic Cubic
::msgcat::mcset de {Current Frame} {Aktueller rahmen}
::msgcat::mcset de {Current Range} {Aktueller bereich}
::msgcat::mcset de Current Aktuell
::msgcat::mcset de Cursor Zeiger
::msgcat::mcset de Cut Ausschneiden
::msgcat::mcset de Cyan Zyan
::msgcat::mcset de DMS DMS
::msgcat::mcset de DPI DPI
::msgcat::mcset de {DS9 has detected a newer version of a backup file and therefore will not process this file.} {DS9 has detected a newer version of a backup file and therefore will not process this file.}
::msgcat::mcset de {DS9 has detected a newer version of a preferences file.} {DS9 has detected a newer version of a preferences file.}
::msgcat::mcset de {DS9 has detected an older backup file, do you wish to continue?} {DS9 has detected an older backup file, do you wish to continue?}
::msgcat::mcset de {DS9 has detected an older preferences file, do you wish to update?} {DS9 hat ein ältere Einstellungsdatei erkannt, möchten Sie aktualisieren?}
::msgcat::mcset de {DS9 will complete the initialization process} {DS9 wird den Initialisierungsprozeß vervollständigen}
::msgcat::mcset de Darken Darken
::msgcat::mcset de Dash Gestrichelt
::msgcat::mcset de {Data Format} Datenformat
::msgcat::mcset de {Data must be ascii numeric values} {Data must be ascii numeric values}
::msgcat::mcset de {Dataset Name} {Dataset Name}
::msgcat::mcset de Dataset Datensatz
::msgcat::mcset de Data Data
::msgcat::mcset de {Decrease Bin} {Decrease Bin}
::msgcat::mcset de {Decrease Block} {Decrease Block}
::msgcat::mcset de {Decrease Magnification} {Decrease Magnification}
::msgcat::mcset de {Decrease Zoom} {Decrease Zoom}
::msgcat::mcset de Decrease Absteigend
::msgcat::mcset de {Default All Files} {Default All Files}
::msgcat::mcset de {Default Format} {Default Format}
::msgcat::mcset de {Default Length} {Default Length}
::msgcat::mcset de Default Standard
::msgcat::mcset de Degrees Grad
::msgcat::mcset de Delay Delay
::msgcat::mcset de {Delete All Frames?} {Alle rahmen löschen?}
::msgcat::mcset de {Delete All Frames} {Alle rahmen löschen}
::msgcat::mcset de {Delete All Groups?} {Alle Gruppen löschen?}
::msgcat::mcset de {Delete All Groups} {Alle Gruppen löschen}
::msgcat::mcset de {Delete All Load} {Delete All Load}
::msgcat::mcset de {Delete All and Open} {Delete All and Open}
::msgcat::mcset de {Delete All} {Delete All}
::msgcat::mcset de {Delete Color Tags} {Delete Color Tags}
::msgcat::mcset de {Delete Dataset} {Delete Dataset}
::msgcat::mcset de {Delete Frame} {Rahmen löschen}
::msgcat::mcset de {Delete Graph} {Delete Graph}
::msgcat::mcset de {Delete Group} {Gruppe löschen}
::msgcat::mcset de {Delete Selection} {Delete Selection}
::msgcat::mcset de {Delete Select} {Delete Select}
::msgcat::mcset de Delete Löschen
::msgcat::mcset de Depth Tiefe
::msgcat::mcset de Detector Detektor
::msgcat::mcset de {Dialog Box} Dialogbox
::msgcat::mcset de Diameter Diameter
::msgcat::mcset de Diamond Raute
::msgcat::mcset de Dimensions Dimensions
::msgcat::mcset de Dimension Dimension
::msgcat::mcset de Direction Direction
::msgcat::mcset de Disconnect Disconnect
::msgcat::mcset de {Display Size} {Größe zeigen}
::msgcat::mcset de {Dissolve Composite Region} {Dissolve Composite Region}
::msgcat::mcset de Dissolve Dissolve
::msgcat::mcset de Distance Distance
::msgcat::mcset de Done Done
::msgcat::mcset de {Download Colormap} {Download Colormap}
::msgcat::mcset de {Drag to Center} {Ziehen zum zentrieren}
::msgcat::mcset de {Duplicate Dataset} {Duplicate Dataset}
::msgcat::mcset de ENVI ENVI
::msgcat::mcset de EPS EPS
::msgcat::mcset de East Osten
::msgcat::mcset de Ecliptic Ekliptisch
::msgcat::mcset de {Edit Group Name} {Gruppenname bearbeiten}
::msgcat::mcset de {Edit Mode} {Edit Mode}
::msgcat::mcset de Edit Bearbeiten
::msgcat::mcset de Elevation Elevation
::msgcat::mcset de {Ellipse Panda} {Ellipsen Panda}
::msgcat::mcset de Ellipse Ellipse
::msgcat::mcset de {Elliptical Annulus} {Elliptischer Kreisring}
::msgcat::mcset de {Elliptical Gaussian} {Elliptical Gaussian}
::msgcat::mcset de {Elliptical Panda} {Elliptischer Panda}
::msgcat::mcset de {Enable Confirmation Dialogs} {Bestätigungsdialoge einschalten}
::msgcat::mcset de Enable Enable
::msgcat::mcset de End Ende
::msgcat::mcset de {Enter Color} {Enter Color}
::msgcat::mcset de {Enter Font Size} {Enter Font Size}
::msgcat::mcset de {Enter Group Name} {Gruppenname eingeben}
::msgcat::mcset de {Enter Search Expression} {Enter Search Expression}
::msgcat::mcset de {Enter URL} {Enter URL}
::msgcat::mcset de Entry Entry
::msgcat::mcset de {Equal Area} {Gleiche Fläche}
::msgcat::mcset de {Equal Distance} {Gleicher Abstand}
::msgcat::mcset de {Equal Spacing} {Equal Spacing}
::msgcat::mcset de {Equal Value} {Equal Value}
::msgcat::mcset de {Error code was returned} {Fehlercode wurde zurückgegeben}
::msgcat::mcset de Errorbar Errorbar
::msgcat::mcset de Error Fehler
::msgcat::mcset de {Examine Frame} {Rahmen inspizieren}
::msgcat::mcset de Examine Inspizieren
::msgcat::mcset de Exam Exam
::msgcat::mcset de Exclude Ausschliessen
::msgcat::mcset de Exit Schließen
::msgcat::mcset de {Export Array} {Export Array}
::msgcat::mcset de {Export ENVI} {Export ENVI}
::msgcat::mcset de {Export GIF} {Export GIF}
::msgcat::mcset de {Export HLS Array} {Export HLS Array}
::msgcat::mcset de {Export HSV Array} {Export HSV Array}
::msgcat::mcset de {Export JPEG} {Export JPEG}
::msgcat::mcset de {Export NRRD} {Export NRRD}
::msgcat::mcset de {Export PNG} {Export PNG}
::msgcat::mcset de {Export RGB Array} {Export RGB Array}
::msgcat::mcset de {Export TIFF} {Export TIFF}
::msgcat::mcset de Export Export
::msgcat::mcset de {Extension Data} {Extension Data}
::msgcat::mcset de {Extension not found} {Extension not found}
::msgcat::mcset de Extensions Extensions
::msgcat::mcset de Extension Extension
::msgcat::mcset de {Exterior Axes} {Äußere Achsen}
::msgcat::mcset de {Exterior Numerics} {Äußere Ziffern}
::msgcat::mcset de FAQ FAQ
::msgcat::mcset de FITS FITS
::msgcat::mcset de FK4 FK4
::msgcat::mcset de FK5 FK5
::msgcat::mcset de FP FP
::msgcat::mcset de Factor Factor
::msgcat::mcset de {Fade Frames} {Fade Frames}
::msgcat::mcset de {Fade Interval} {Fade Interval}
::msgcat::mcset de Fade Fade
::msgcat::mcset de {File Open} {File Open}
::msgcat::mcset de {File not Found or Unable to load FITS data MIME type} {Datei nicht gefunden oder nicht möglich FITS-Daten MIME-Type zu laden}
::msgcat::mcset de {File not found} {File not found}
::msgcat::mcset de {Filename Format} {Filename Format}
::msgcat::mcset de Filename Dateiname
::msgcat::mcset de File Datei
::msgcat::mcset de Fill Fill
::msgcat::mcset de Filter Filter
::msgcat::mcset de {Find Next} {Nächsten finden}
::msgcat::mcset de Find Suchen
::msgcat::mcset de {First Block} {First Block}
::msgcat::mcset de {First Frame} {Erster rahmen}
::msgcat::mcset de First Erster
::msgcat::mcset de Fits Fits
::msgcat::mcset de {Fixed in Size} {Feste Größe}
::msgcat::mcset de Flip Flip
::msgcat::mcset de Font Font
::msgcat::mcset de {Footprint Servers} {Footprint Servers}
::msgcat::mcset de Footprint Footprint
::msgcat::mcset de {For more information, use --help} {For more information, use --help}
::msgcat::mcset de Foreground Foreground
::msgcat::mcset de Forground Forground
::msgcat::mcset de Format Format
::msgcat::mcset de Forward Vorwärts
::msgcat::mcset de {Found Auto Backup, restore?} {Found Auto Backup, restore?}
::msgcat::mcset de Found Gefunden
::msgcat::mcset de {Frame Information} Rahmeninformation
::msgcat::mcset de {Frame Layout} {Frame Layout}
::msgcat::mcset de {Frame Parameters} {Frame Parameters}
::msgcat::mcset de Frames Frames
::msgcat::mcset de Frame Rahmen
::msgcat::mcset de From From
::msgcat::mcset de Front Vor
::msgcat::mcset de {Full Range} {Ganzer Bereich}
::msgcat::mcset de Function Funktion
::msgcat::mcset de GIF GIF
::msgcat::mcset de GUI GUI
::msgcat::mcset de Galactic Galaktisch
::msgcat::mcset de Gap Gap
::msgcat::mcset de Gaussian Gauss
::msgcat::mcset de General Allgemein
::msgcat::mcset de Generate Herstellen
::msgcat::mcset de {Generating Regions} {Regionen erstellen}
::msgcat::mcset de {Get Information} Informationen
::msgcat::mcset de {Get Region Info} {Get Region Info}
::msgcat::mcset de Gist Gist
::msgcat::mcset de {Global Properties} {Global Properties}
::msgcat::mcset de Global Global
::msgcat::mcset de {Goto First Frame} {Goto First Frame}
::msgcat::mcset de {Goto Frame} {Goto Frame}
::msgcat::mcset de {Goto Last Frame} {Goto Last Frame}
::msgcat::mcset de {Goto Next Frame} {Goto Next Frame}
::msgcat::mcset de {Goto Previous Frame} {Goto Previous Frame}
::msgcat::mcset de {Goto Row} {Goto Row}
::msgcat::mcset de Goto Goto
::msgcat::mcset de {Graph Horz} {Graph Horz}
::msgcat::mcset de {Graph Parameters} {Graph Parameters}
::msgcat::mcset de {Graph Vert} {Graph Vert}
::msgcat::mcset de Graphics Grafik
::msgcat::mcset de Graphs Graphs
::msgcat::mcset de Graph Graph
::msgcat::mcset de Grayscale Graustufen
::msgcat::mcset de Green Grün
::msgcat::mcset de {Grid Gap} Gitterabstand
::msgcat::mcset de Grid Gitter
::msgcat::mcset de Groups Gruppen
::msgcat::mcset de {HLS Array} {HLS Array}
::msgcat::mcset de {HLS Cube} {HLS Cube}
::msgcat::mcset de {HLS Image} {HLS Image}
::msgcat::mcset de HLS HLS
::msgcat::mcset de HMS HMS
::msgcat::mcset de {HSV Array} {HSV Array}
::msgcat::mcset de {HSV Cube} {HSV Cube}
::msgcat::mcset de {HSV Image} {HSV Image}
::msgcat::mcset de HSV HSV
::msgcat::mcset de HTTP HTTP
::msgcat::mcset de Header Dateikopf
::msgcat::mcset de Height Höhe
::msgcat::mcset de {Help Desk} Hilfestelle
::msgcat::mcset de {Help Me Choose} {Hilf mir auswählen}
::msgcat::mcset de Help Hilfe
::msgcat::mcset de {Hide All} {Alle verstecken}
::msgcat::mcset de Highlite Highlite
::msgcat::mcset de High Hoch
::msgcat::mcset de {Histogram Equalization} Histogrammausgleich
::msgcat::mcset de Histogram Histogramm
::msgcat::mcset de {Horizontal Graph} Horizontaldarstellung
::msgcat::mcset de {Horizontal Layout} {Horizontales Layout}
::msgcat::mcset de Horizontal Horizontal
::msgcat::mcset de {Hub not running} {Hub not running}
::msgcat::mcset de Hue Hue
::msgcat::mcset de {IAU Location Code} {IAU Location Code}
::msgcat::mcset de ICRS ICRS
::msgcat::mcset de Icons Icons
::msgcat::mcset de Identification Kennzeichnung
::msgcat::mcset de If Wenn
::msgcat::mcset de Illustrate Illustrate
::msgcat::mcset de {Image Servers} {Image Servers}
::msgcat::mcset de Image Bild
::msgcat::mcset de {Import Array} {Import Array}
::msgcat::mcset de {Import ENVI} {Import ENVI}
::msgcat::mcset de {Import GIF} {Import GIF}
::msgcat::mcset de {Import HLS Array} {Import HLS Array}
::msgcat::mcset de {Import HSV Array} {Import HSV Array}
::msgcat::mcset de {Import JPEG} {Import JPEG}
::msgcat::mcset de {Import NRRD} {Import NRRD}
::msgcat::mcset de {Import PNG} {Import PNG}
::msgcat::mcset de {Import RGB Array} {Import RGB Array}
::msgcat::mcset de {Import Slice GIF} {Import Slice GIF}
::msgcat::mcset de {Import Slice JPEG} {Import Slice JPEG}
::msgcat::mcset de {Import Slice PNG} {Import Slice PNG}
::msgcat::mcset de {Import Slice TIFF} {Import Slice TIFF}
::msgcat::mcset de {Import TIFF} {Import TIFF}
::msgcat::mcset de Import Import
::msgcat::mcset de Include Einschliessen
::msgcat::mcset de {Increase Bin} {Increase Bin}
::msgcat::mcset de {Increase Block} {Increase Block}
::msgcat::mcset de {Increase Magnification} {Increase Magnification}
::msgcat::mcset de {Increase Zoom} {Increase Zoom}
::msgcat::mcset de Increase Aufsteigend
::msgcat::mcset de {Info Box} {Info Box}
::msgcat::mcset de {Information Panel} Informationsfeld
::msgcat::mcset de Information Informations
::msgcat::mcset de {Initialize XPA} {XPA initialisieren}
::msgcat::mcset de Inner Innerer
::msgcat::mcset de {Instrument FOV} Instrumentensichtfeld
::msgcat::mcset de Instrument Instrument
::msgcat::mcset de {Interior Axes} {Innere Achsen}
::msgcat::mcset de {Interior Numerics} {Innere Ziffern}
::msgcat::mcset de {Internal Parse Error} {Internal Parse Error}
::msgcat::mcset de Interval Intervall
::msgcat::mcset de {Invalid Column Name} {Invalid Column Name}
::msgcat::mcset de {Invalid WCS} {Invalid WCS}
::msgcat::mcset de {Invalid formated multipart/mixed mime type message} {Ungültig formatierter multipart/mixed MIME-Type}
::msgcat::mcset de {Invert Colormap} {Farbpalette invertieren}
::msgcat::mcset de Invert Invertieren
::msgcat::mcset de Italic Kursiv
::msgcat::mcset de {Items Found} {Items Found}
::msgcat::mcset de Iteration Iteration
::msgcat::mcset de {JPEG Quality Factor} {JPEG Qualitätsfaktor}
::msgcat::mcset de JPEG JPEG
::msgcat::mcset de Justify Justify
::msgcat::mcset de Keep-Alive Keep-Alive
::msgcat::mcset de Keyword Keyword
::msgcat::mcset de Labels Beschriftung
::msgcat::mcset de Label Label
::msgcat::mcset de Landscape Horizontal
::msgcat::mcset de Language Sprache
::msgcat::mcset de {Last Block} {Last Block}
::msgcat::mcset de {Last Frame} {Letzter rahmen}
::msgcat::mcset de Last Letzter
::msgcat::mcset de Layout Layout
::msgcat::mcset de Left Left
::msgcat::mcset de Legal Legal
::msgcat::mcset de {Legend Position} {Legend Position}
::msgcat::mcset de {Legend Title} {Legend Title}
::msgcat::mcset de Legend Legend
::msgcat::mcset de Length Länge
::msgcat::mcset de Letter Letter
::msgcat::mcset de Levels Niveaus
::msgcat::mcset de Level Niveau
::msgcat::mcset de Lighten Lighten
::msgcat::mcset de Lightness Lightness
::msgcat::mcset de Limits Grenzen
::msgcat::mcset de {Line Dataset} {Line Dataset}
::msgcat::mcset de {Line Plot Tool} {Line Plot Tool}
::msgcat::mcset de Linear Linear
::msgcat::mcset de Line Linie
::msgcat::mcset de {List Data} {List Data}
::msgcat::mcset de {List Regions} {Regionen auflisten}
::msgcat::mcset de {List Region} {List Region}
::msgcat::mcset de {List Selection} {List Selection}
::msgcat::mcset de {List Select} {List Select}
::msgcat::mcset de List Auflisten
::msgcat::mcset de {Load Analysis Commands} {Analysebefehle laden}
::msgcat::mcset de {Load Color Tags} {Load Color Tags}
::msgcat::mcset de {Load Contour Levels} {Kontourniveaus laden}
::msgcat::mcset de {Load Contrast/Bias} {Kontrast/Bias laden}
::msgcat::mcset de {Load Data} {Daten laden}
::msgcat::mcset de {Load Mosaic} {Mosaic laden}
::msgcat::mcset de {Load Template} {Vorlage laden}
::msgcat::mcset de {Load into All} {Load into All}
::msgcat::mcset de {Load into Current} {Load into Current}
::msgcat::mcset de {Loading Catalog} {Loading Catalog}
::msgcat::mcset de Loading Loading
::msgcat::mcset de Load Laden
::msgcat::mcset de Local Lokal
::msgcat::mcset de {Lock Axes} {Lock Axes}
::msgcat::mcset de {Lock Bin} {Lock Bin}
::msgcat::mcset de {Lock Color} {Lock Color}
::msgcat::mcset de {Lock Crop Amplifier} {Lock Crop Amplifier}
::msgcat::mcset de {Lock Crop Detector} {Lock Crop Detector}
::msgcat::mcset de {Lock Crop Image} {Lock Crop Image}
::msgcat::mcset de {Lock Crop None} {Lock Crop None}
::msgcat::mcset de {Lock Crop Physical} {Lock Crop Physical}
::msgcat::mcset de {Lock Crop WCS} {Lock Crop WCS}
::msgcat::mcset de {Lock Crosshair Amplifier} {Lock Crosshair Amplifier}
::msgcat::mcset de {Lock Crosshair Detector} {Lock Crosshair Detector}
::msgcat::mcset de {Lock Crosshair Image} {Lock Crosshair Image}
::msgcat::mcset de {Lock Crosshair None} {Lock Crosshair None}
::msgcat::mcset de {Lock Crosshair Physical} {Lock Crosshair Physical}
::msgcat::mcset de {Lock Crosshair WCS} {Lock Crosshair WCS}
::msgcat::mcset de {Lock Frame Amplifier} {Lock Frame Amplifier}
::msgcat::mcset de {Lock Frame Detector} {Lock Frame Detector}
::msgcat::mcset de {Lock Frame Image} {Lock Frame Image}
::msgcat::mcset de {Lock Frame None} {Lock Frame None}
::msgcat::mcset de {Lock Frame Physical} {Lock Frame Physical}
::msgcat::mcset de {Lock Frame WCS} {Lock Frame WCS}
::msgcat::mcset de {Lock Limits} {Lock Limits}
::msgcat::mcset de {Lock Scale} {Lock Scale}
::msgcat::mcset de {Lock Slice Image} {Lock Slice Image}
::msgcat::mcset de {Lock Slice None} {Lock Slice None}
::msgcat::mcset de {Lock Slice WCS} {Lock Slice WCS}
::msgcat::mcset de {Lock Smooth} {Lock Smooth}
::msgcat::mcset de Lock Arretieren
::msgcat::mcset de {Log Exponent} {Log Exponent}
::msgcat::mcset de Log Log
::msgcat::mcset de {Low High} {Niedrig Hoch}
::msgcat::mcset de {Lower Left Back} {Lower Left Back}
::msgcat::mcset de {Lower Left Front} {Lower Left Front}
::msgcat::mcset de {Lower Right Back} {Lower Right Back}
::msgcat::mcset de {Lower Right Front} {Lower Right Front}
::msgcat::mcset de Low Niedrig
::msgcat::mcset de MIP MIP
::msgcat::mcset de Magenta Magenta
::msgcat::mcset de Magnification Magnification
::msgcat::mcset de Magnifier Vergrößerungsglas
::msgcat::mcset de {Major Radius} {Major Radius}
::msgcat::mcset de {Major Sigma} {Major Sigma}
::msgcat::mcset de Major Groß
::msgcat::mcset de Manual Manuell
::msgcat::mcset de {Mask Parameters} Maskenparameter
::msgcat::mcset de {Match Axes} {Match Axes}
::msgcat::mcset de {Match Bin} {Match Bin}
::msgcat::mcset de {Match Catalog requires at least 1 row per catalog} {Match Catalog requires at least 1 row per catalog}
::msgcat::mcset de {Match Color} {Match Color}
::msgcat::mcset de {Match Crop Amplifier} {Match Crop Amplifier}
::msgcat::mcset de {Match Crop Detector} {Match Crop Detector}
::msgcat::mcset de {Match Crop Image} {Match Crop Image}
::msgcat::mcset de {Match Crop Physical} {Match Crop Physical}
::msgcat::mcset de {Match Crop WCS} {Match Crop WCS}
::msgcat::mcset de {Match Crosshair Amplifier} {Match Crosshair Amplifier}
::msgcat::mcset de {Match Crosshair Detector} {Match Crosshair Detector}
::msgcat::mcset de {Match Crosshair Image} {Match Crosshair Image}
::msgcat::mcset de {Match Crosshair Physical} {Match Crosshair Physical}
::msgcat::mcset de {Match Crosshair WCS} {Match Crosshair WCS}
::msgcat::mcset de {Match Frame Amplifier} {Match Frame Amplifier}
::msgcat::mcset de {Match Frame Detector} {Match Frame Detector}
::msgcat::mcset de {Match Frame Image} {Match Frame Image}
::msgcat::mcset de {Match Frame Physical} {Match Frame Physical}
::msgcat::mcset de {Match Frame WCS} {Match Frame WCS}
::msgcat::mcset de {Match Frames on WCS} {Match Frames on WCS}
::msgcat::mcset de {Match Limits} {Match Limits}
::msgcat::mcset de {Match Scale} {Match Scale}
::msgcat::mcset de {Match Slice Image} {Match Slice Image}
::msgcat::mcset de {Match Slice WCS} {Match Slice WCS}
::msgcat::mcset de {Match Smooth} {Match Smooth}
::msgcat::mcset de Match Match
::msgcat::mcset de {Math Function} {Math. Funktion}
::msgcat::mcset de {Matplotlib Cyclic} {Matplotlib Cyclic}
::msgcat::mcset de {Matplotlib Diverging} {Matplotlib Diverging}
::msgcat::mcset de {Matplotlib Sequential} {Matplotlib Sequential}
::msgcat::mcset de {Matplotlib Uniform} {Matplotlib Uniform}
::msgcat::mcset de {Max Rows} {Max. Reihen}
::msgcat::mcset de Maximum Maximum
::msgcat::mcset de Max Max
::msgcat::mcset de Median Median
::msgcat::mcset de {Menus and Buttons} {Menus and Buttons}
::msgcat::mcset de Menu Menu
::msgcat::mcset de {Message Log} {Message Log}
::msgcat::mcset de Metadata Metadata
::msgcat::mcset de Method Methode
::msgcat::mcset de {Min Max Parameters} {Min Max Parameters}
::msgcat::mcset de {Min Max} {Min Max}
::msgcat::mcset de Minimum Minimum
::msgcat::mcset de {Minor Radius} {Minor Radius}
::msgcat::mcset de {Minor Sigma} {Minor Sigma}
::msgcat::mcset de Minor Gering
::msgcat::mcset de Minutes Minutes
::msgcat::mcset de Min Min
::msgcat::mcset de Mission Mission
::msgcat::mcset de Mode Mode
::msgcat::mcset de {Mosaic IRAF Segment} {Mosaic IRAF Segment}
::msgcat::mcset de {Mosaic IRAF} {Mosaic IRAF}
::msgcat::mcset de {Mosaic WCS Segment} {Mosaic WCS Segment}
::msgcat::mcset de {Mosaic WCS} {Mosaic WCS}
::msgcat::mcset de {Mosaic WFPC2} {Mosaic WFPC2}
::msgcat::mcset de Mosaic Mosaic
::msgcat::mcset de {Mouse Click Epsilon} {Mouse Click Epsilon}
::msgcat::mcset de {Mouse Wheel Bin} {Mouse Wheel Bin}
::msgcat::mcset de {Mouse Wheel Zoom} {Mouse Wheel Zoom}
::msgcat::mcset de {Move Back} {Move Back}
::msgcat::mcset de {Move First} {Move First}
::msgcat::mcset de {Move Forward} {Move Forward}
::msgcat::mcset de {Move Frame} {Move Frame}
::msgcat::mcset de {Move Front} {Move Front}
::msgcat::mcset de {Move Last} {Move Last}
::msgcat::mcset de {Move to Back} {Nach hinten}
::msgcat::mcset de {Move to Front} {Nach vorne}
::msgcat::mcset de Movie Movie
::msgcat::mcset de {Muliple Extension Cube} {Muliple Extension Cube}
::msgcat::mcset de {Muliple Extension Frames} {Muliple Extension Frames}
::msgcat::mcset de {Multi Colorbars} {Multi Colorbars}
::msgcat::mcset de {Multiple Colorbars} {Multiple Colorbars}
::msgcat::mcset de {Multiple Extension Cube} {Multiple Extension Cube}
::msgcat::mcset de {Multiple Extension Frames} {Multiple Extension Frames}
::msgcat::mcset de {Multiple WCS} {Mehrere WCS}
::msgcat::mcset de NAN NAN
::msgcat::mcset de NRRD NRRD
::msgcat::mcset de {Name Resolution} Namensbestimmung
::msgcat::mcset de {Name Server} {Name Server}
::msgcat::mcset de {Name or Designation} {Name oder Bezeichnung}
::msgcat::mcset de Name Name
::msgcat::mcset de {Native Dialog} {Systemnativer Dialog}
::msgcat::mcset de {New Features} {Neue Eigenschaften}
::msgcat::mcset de {New Frame 3D} {New Frame 3D}
::msgcat::mcset de {New Frame HLS} {New Frame HLS}
::msgcat::mcset de {New Frame HSV} {New Frame HSV}
::msgcat::mcset de {New Frame RGB} {Neuer RGB rahmen}
::msgcat::mcset de {New Frame each Time} {Neuer rahmen jedes Mal}
::msgcat::mcset de {New Frame} {Neuer rahmen}
::msgcat::mcset de {New Graph} {New Graph}
::msgcat::mcset de {New Group} {Neue Gruppe}
::msgcat::mcset de {New Plot} {New Plot}
::msgcat::mcset de New Neu
::msgcat::mcset de {Next Block} {Next Block}
::msgcat::mcset de {Next Frame} {Nächster rahmen}
::msgcat::mcset de Next Nächster
::msgcat::mcset de {No Catalog specified} {Keine Katalog spezifiziert}
::msgcat::mcset de {No Data Available} {No Data Available}
::msgcat::mcset de {No Items Found} {Keine Objekte gefunden}
::msgcat::mcset de Non-NAN Non-NAN
::msgcat::mcset de Non-Zero Non-Zero
::msgcat::mcset de None Kein
::msgcat::mcset de Normal Normal
::msgcat::mcset de North Norden
::msgcat::mcset de {Not Found} {Not Found}
::msgcat::mcset de {Not Supported} {Not Supported}
::msgcat::mcset de {Not valid export format} {Not valid export format}
::msgcat::mcset de Notes Notes
::msgcat::mcset de {Number of Samples} {Anzahl der Stichproben}
::msgcat::mcset de {Number of Threads} {Number of Threads}
::msgcat::mcset de {Number of Ticks} {Number of Ticks}
::msgcat::mcset de Number Zahl
::msgcat::mcset de Numerics Numerics
::msgcat::mcset de OK OK
::msgcat::mcset de Object Objekt
::msgcat::mcset de ObsId ObsId
::msgcat::mcset de {Open File} {Datei öffnen}
::msgcat::mcset de {Open HLS Cube} {Open HLS Cube}
::msgcat::mcset de {Open HLS Image} {Open HLS Image}
::msgcat::mcset de {Open HSV Cube} {Open HSV Cube}
::msgcat::mcset de {Open HSV Image} {Open HSV Image}
::msgcat::mcset de {Open ME Cube} {Open ME Cube}
::msgcat::mcset de {Open ME Frames} {Open ME Frames}
::msgcat::mcset de {Open Mosaic IRAF Seg} {Open Mosaic IRAF Seg}
::msgcat::mcset de {Open Mosaic IRAF} {Open Mosaic IRAF}
::msgcat::mcset de {Open Mosaic WCS Seg} {Open Mosaic WCS Seg}
::msgcat::mcset de {Open Mosaic WCS} {Open Mosaic WCS}
::msgcat::mcset de {Open Mosaic WFPC2} {Open Mosaic WFPC2}
::msgcat::mcset de {Open Notepad} {Open Notepad}
::msgcat::mcset de {Open Prism} {Open Prism}
::msgcat::mcset de {Open RGB Cube} {Open RGB Cube}
::msgcat::mcset de {Open RGB Image} {Open RGB Image}
::msgcat::mcset de {Open Region File} {Open Region File}
::msgcat::mcset de {Open Regions} {Open Regions}
::msgcat::mcset de {Open Slice} {Open Slice}
::msgcat::mcset de {Open TCL Console} {Open TCL Console}
::msgcat::mcset de {Open URL} {URL Öffnen}
::msgcat::mcset de {Open as} {Open as}
::msgcat::mcset de Open Öffnen
::msgcat::mcset de Operator Operator
::msgcat::mcset de Orientation Orientierung
::msgcat::mcset de Origin Origin
::msgcat::mcset de Oscillate Oscillate
::msgcat::mcset de {Other Color} {Other Color}
::msgcat::mcset de {Other Font Size} {Other Font Size}
::msgcat::mcset de Other Andere
::msgcat::mcset de Outer Äußerer
::msgcat::mcset de Overplot Overplot
::msgcat::mcset de {Override Color} {Override Color}
::msgcat::mcset de PNG PNG
::msgcat::mcset de {PS Page Setup} {PS Page Setup}
::msgcat::mcset de {PS Print} {PS Print}
::msgcat::mcset de {Page Setup} Seitensetup
::msgcat::mcset de {Page Source} Seitenquelle
::msgcat::mcset de {Pan To} {Ausrichten auf}
::msgcat::mcset de {Pan Zoom Rotate Parameters} {Ausrichten zoomen rotieren}
::msgcat::mcset de {Pan Zoom} {Pan Zoom}
::msgcat::mcset de {Pan then Zoom} {Ausrichten dann Zoomen}
::msgcat::mcset de {Pan to Center} {Pan to Center}
::msgcat::mcset de Panda Panda
::msgcat::mcset de Panner Übersichtsfeld
::msgcat::mcset de Pan Ausrichtung
::msgcat::mcset de Parameters Parameter
::msgcat::mcset de Password Passwort
::msgcat::mcset de {Paste Contours} {Konturen einfügen}
::msgcat::mcset de Paste Einfügen
::msgcat::mcset de Percent Percent
::msgcat::mcset de Physical Physikalisch
::msgcat::mcset de {Pixel Distribution} Pixelverteilung
::msgcat::mcset de {Pixel Size} Pixelgröße
::msgcat::mcset de {Pixel Table} Pixeltabelle
::msgcat::mcset de Pixels Pixel
::msgcat::mcset de Planets Planets
::msgcat::mcset de Play Abspielen
::msgcat::mcset de {Please Select a Region} {Please Select a Region}
::msgcat::mcset de {Please change the file's permission to disable other users write access. Use anyway?} {Please change the file's permission to disable other users write access. Use anyway?}
::msgcat::mcset de {Please specify instruments} {Please specify instruments}
::msgcat::mcset de {Please specify radius and either name or (ra,dec)} {Please specify radius and either name or (ra,dec)}
::msgcat::mcset de {Please specify width, height, and either name or (ra,dec)} {Bitte Weite, Höhe und entweder Namen oder (RA,Dec) angeben}
::msgcat::mcset de {Plot 2D} {Plot 2D}
::msgcat::mcset de {Plot 3D} {Plot 3D}
::msgcat::mcset de {Plot Area} {Plot Area}
::msgcat::mcset de {Plot Control Panel} {Plot Control Panel}
::msgcat::mcset de {Plot Tool} {Plot Tool}
::msgcat::mcset de {Plotting Regions} {Regionen drucken}
::msgcat::mcset de Plot Plot
::msgcat::mcset de Plus Plus
::msgcat::mcset de Pointer Zeiger
::msgcat::mcset de Points Punkte
::msgcat::mcset de Point Punkt
::msgcat::mcset de Polygon Polygon
::msgcat::mcset de Portrait Vertikal
::msgcat::mcset de Position Position
::msgcat::mcset de Poster Poster
::msgcat::mcset de Postscript Postscript
::msgcat::mcset de Power Exp
::msgcat::mcset de Precision Precision
::msgcat::mcset de Preferences Einstellungen
::msgcat::mcset de {Preserve During Load} {Beim Laden beibehalten}
::msgcat::mcset de {Previous Block} {Previous Block}
::msgcat::mcset de {Previous Frame} {Vorheriger rahmen}
::msgcat::mcset de Previous Vorheriger
::msgcat::mcset de Prev Prev
::msgcat::mcset de {Print Coordinates} {Koordinaten drucken}
::msgcat::mcset de {Print To} Drucken
::msgcat::mcset de Printer Drucker
::msgcat::mcset de Print Drucken
::msgcat::mcset de {Prism Goto} {Prism Goto}
::msgcat::mcset de Prism Prism
::msgcat::mcset de Projection Projektion
::msgcat::mcset de Properties Eigenschaften
::msgcat::mcset de Property Eigenschaften
::msgcat::mcset de {Proxy Host} {Proxy Host}
::msgcat::mcset de {Proxy Port} {Proxy Port}
::msgcat::mcset de {Public ID} {Public ID}
::msgcat::mcset de Publication Veröffentlichung
::msgcat::mcset de Quadratic Quadratisch
::msgcat::mcset de RDB RDB
::msgcat::mcset de {RGB Array} {RGB Array}
::msgcat::mcset de {RGB Cube} {RGB Cube}
::msgcat::mcset de {RGB Image} {RGB Image}
::msgcat::mcset de RGB RGB
::msgcat::mcset de {Radial Profile} {Radial Profile}
::msgcat::mcset de Radius Radius
::msgcat::mcset de Range Range
::msgcat::mcset de Redo Wiederholen
::msgcat::mcset de Red Rot
::msgcat::mcset de {Reference Manual} Referenzhandbuch
::msgcat::mcset de Reference Referenz
::msgcat::mcset de {Refresh Frame} {Rahmen erneuern}
::msgcat::mcset de Refresh Refresh
::msgcat::mcset de {Region Color} {Region Color}
::msgcat::mcset de {Region Line Width} {Region Line Width}
::msgcat::mcset de {Region Parameters} {Region Parameters}
::msgcat::mcset de {Region Shape} {Region Shape}
::msgcat::mcset de Region Region
::msgcat::mcset de Registration Registration
::msgcat::mcset de {Release Notes} Versionshinweise
::msgcat::mcset de Release Version
::msgcat::mcset de Reload {Wieder laden}
::msgcat::mcset de Render Render
::msgcat::mcset de Repeat Repeat
::msgcat::mcset de {Reset Colormap} {Farbpalette zurücksetzen}
::msgcat::mcset de {Reset Frame} {Rahmen zurücksetzen}
::msgcat::mcset de Reset Reset
::msgcat::mcset de Restore Restore
::msgcat::mcset de Retrieve Suchen
::msgcat::mcset de Return Return
::msgcat::mcset de Right Right
::msgcat::mcset de Roman Roman
::msgcat::mcset de Rotate Rotieren
::msgcat::mcset de Rows Reihen
::msgcat::mcset de Row Row
::msgcat::mcset de Ruler Lineal
::msgcat::mcset de {SAMP Connect} {SAMP Connect}
::msgcat::mcset de {SAMP Disconnect} {SAMP Disconnect}
::msgcat::mcset de {SAMP Hub Start} {SAMP Hub Start}
::msgcat::mcset de {SAMP Hub Stop} {SAMP Hub Stop}
::msgcat::mcset de {SAMP Hub} {SAMP Hub}
::msgcat::mcset de {SAMP Table} {SAMP Table}
::msgcat::mcset de {SAMP WebHub Start} {SAMP WebHub Start}
::msgcat::mcset de {SAMP: not connected} {SAMP: not connected}
::msgcat::mcset de SAMP SAMP
::msgcat::mcset de {Sample Increment} {Sample Increment}
::msgcat::mcset de {Sample Parameters} {Sample Parameters}
::msgcat::mcset de {Samples per Line} {Stichproben pro Linie}
::msgcat::mcset de Sample Sample
::msgcat::mcset de Saturation Saturation
::msgcat::mcset de {Save 3D Movie} {Save 3D Movie}
::msgcat::mcset de {Save Color Tags} {Save Color Tags}
::msgcat::mcset de {Save Contour Levels} {Konturniveaus speichern}
::msgcat::mcset de {Save Contrast/Bias} {Kontrast/Bias speichern}
::msgcat::mcset de {Save Data} {Daten speichern}
::msgcat::mcset de {Save HLS Cube} {Save HLS Cube}
::msgcat::mcset de {Save HLS Image} {Save HLS Image}
::msgcat::mcset de {Save HSV Cube} {Save HSV Cube}
::msgcat::mcset de {Save HSV Image} {Save HSV Image}
::msgcat::mcset de {Save Image EPS} {Save Image EPS}
::msgcat::mcset de {Save Image FITS} {Save Image FITS}
::msgcat::mcset de {Save Image GIF} {Save Image GIF}
::msgcat::mcset de {Save Image JPEG} {Save Image JPEG}
::msgcat::mcset de {Save Image PNG} {Save Image PNG}
::msgcat::mcset de {Save Image TIFF} {Save Image TIFF}
::msgcat::mcset de {Save Image on Download} {Save Image on Download}
::msgcat::mcset de {Save Image} {Bild speichern}
::msgcat::mcset de {Save ME Cube} {Save ME Cube}
::msgcat::mcset de {Save Mosaic WCS Seg} {Save Mosaic WCS Seg}
::msgcat::mcset de {Save Mosaic WCS} {Save Mosaic WCS}
::msgcat::mcset de {Save RGB Cube} {Save RGB Cube}
::msgcat::mcset de {Save RGB Image} {Save RGB Image}
::msgcat::mcset de {Save Region File} {Save Region File}
::msgcat::mcset de {Save Regions} {Regionen speichern}
::msgcat::mcset de {Save Selection} {Save Selection}
::msgcat::mcset de {Save Select} {Save Select}
::msgcat::mcset de {Save Slice} {Save Slice}
::msgcat::mcset de {Save Template} {Vorlage speichern}
::msgcat::mcset de {Save as EPS} {Save as EPS}
::msgcat::mcset de {Save as PNG} {Save as PNG}
::msgcat::mcset de {Save as} {Save as}
::msgcat::mcset de Save Speichern
::msgcat::mcset de {Scale Parameters} Skalierungsparameter
::msgcat::mcset de {Scale and Limits} {Scale and Limits}
::msgcat::mcset de Scale Skalierung
::msgcat::mcset de {Scaling Option} {Scaling Option}
::msgcat::mcset de {Scaling Parameters} {Scaling Parameters}
::msgcat::mcset de Scan Abtastung
::msgcat::mcset de {Scatter Dataset} {Scatter Dataset}
::msgcat::mcset de {Scatter Plot Tool} {Scatter Plot Tool}
::msgcat::mcset de {Scientific Colour Maps} {Scientific Colour Maps}
::msgcat::mcset de Scope Anwendungsbereich
::msgcat::mcset de Screen Screen
::msgcat::mcset de {Search for Catalogs} {Nach Katalogen suchen}
::msgcat::mcset de Seconds Sekunden
::msgcat::mcset de Second Second
::msgcat::mcset de Segment Segment
::msgcat::mcset de {Select All} {Alle auswählen}
::msgcat::mcset de {Select Coordinate System } {Koordinatensystem auswählen}
::msgcat::mcset de {Select Dataset} {Select Dataset}
::msgcat::mcset de {Select Datatset} {Select Datatset}
::msgcat::mcset de {Select Graph} {Select Graph}
::msgcat::mcset de {Select None} {Nichts auswählen}
::msgcat::mcset de {Send to Back} {Send to Back}
::msgcat::mcset de Send Send
::msgcat::mcset de Server Server
::msgcat::mcset de {Set Bin to 1} {Set Bin to 1}
::msgcat::mcset de {Set Block to 1} {Set Block to 1}
::msgcat::mcset de {Set Zoom to 1} {Set Zoom to 1}
::msgcat::mcset de Sexagesimal Sexagesimal
::msgcat::mcset de Shadow Shadow
::msgcat::mcset de Shape Form
::msgcat::mcset de {Show All} {Alle zeigen}
::msgcat::mcset de {Show Command} {Show Command}
::msgcat::mcset de {Show Compass} {Show Compass}
::msgcat::mcset de {Show Legend} {Show Legend}
::msgcat::mcset de {Show Text} {Show Text}
::msgcat::mcset de {Show/Hide Frames} {Rahmen zeigen/verstecken}
::msgcat::mcset de Show Show
::msgcat::mcset de {Simple Cross} {Simple Cross}
::msgcat::mcset de {Simple Image Access} {Simple Image Access}
::msgcat::mcset de {Simple Plus} {Simple Plus}
::msgcat::mcset de {Single Frame} {Einzelner rahmen}
::msgcat::mcset de Single Einzeln
::msgcat::mcset de Sites Sites
::msgcat::mcset de Size/Radius Größe/Radius
::msgcat::mcset de Size Größe
::msgcat::mcset de {Skip First} {Erste überspringen}
::msgcat::mcset de Slice Slice
::msgcat::mcset de {Smooth Parameters} Glättungsparameter
::msgcat::mcset de Smoothness Smoothness
::msgcat::mcset de Smooth Glätten
::msgcat::mcset de {Sorry, DS9 does not support} {Sorry, DS9 unterstützt nicht}
::msgcat::mcset de {Sorry, DS9 requires a Truecolor8, Truecolor16, Truecolor24 visual be available} {Sorry, DS9 requires a Truecolor8, Truecolor16, Truecolor24 visual be available}
::msgcat::mcset de Sort Sortieren
::msgcat::mcset de {Source TCL} {Source TCL}
::msgcat::mcset de Source Quelle
::msgcat::mcset de {Space Equal Distance} {Space Equal Distance}
::msgcat::mcset de {Space Equal Value} {Space Equal Value}
::msgcat::mcset de Spacing Intervall
::msgcat::mcset de Sqrt Sqrt
::msgcat::mcset de {Square Root} Wurzel
::msgcat::mcset de Squared Quadratisch
::msgcat::mcset de Square Square
::msgcat::mcset de Starbase Starbase
::msgcat::mcset de Startup Startup
::msgcat::mcset de Start Start
::msgcat::mcset de Statistics Statistics
::msgcat::mcset de Status Status
::msgcat::mcset de Step Stufe
::msgcat::mcset de Stop Stop
::msgcat::mcset de {Story of SAOImageDS9} {Story of SAOImageDS9}
::msgcat::mcset de Story Story
::msgcat::mcset de {Strip Parameters} {Strip Parameters}
::msgcat::mcset de {Strip Scale} {Strip Scale}
::msgcat::mcset de Strip Strip
::msgcat::mcset de Subscriptions Subscriptions
::msgcat::mcset de Sum Summieren
::msgcat::mcset de {Symbol Editor} {Symbol Editor}
::msgcat::mcset de Symbol Symbol
::msgcat::mcset de TIFF TIFF
::msgcat::mcset de TSV TSV
::msgcat::mcset de Tab-Separated-Value Tab-Separated-Value
::msgcat::mcset de Table Table
::msgcat::mcset de Tabloid Tabloid
::msgcat::mcset de {Tag Color} {Tag Color}
::msgcat::mcset de {Tag New Region Group} {Tag New Region Group}
::msgcat::mcset de Template Template
::msgcat::mcset de Text Text
::msgcat::mcset de Theme Theme
::msgcat::mcset de Then dann
::msgcat::mcset de Thickness Dicke
::msgcat::mcset de {This analysis task is already running. Do you wish to kill it?} {Diese Analyse läuft bereits. Soll sie beendet werden?}
::msgcat::mcset de {This function is not available.} {This function is not available.}
::msgcat::mcset de {This function is not currently supported for this port.} {This function is not currently supported for this port.}
::msgcat::mcset de Tickmarks Achsenstriche
::msgcat::mcset de {Tile Frames} {Gekachelte rahmen}
::msgcat::mcset de {Tile Parameters} {Tile Parameters}
::msgcat::mcset de Tile Kacheln
::msgcat::mcset de Times Times
::msgcat::mcset de Titles Titles
::msgcat::mcset de Title Titel
::msgcat::mcset de {Toggle Colorbar} {Toggle Colorbar}
::msgcat::mcset de {Toggle Contour} {Toggle Contour}
::msgcat::mcset de {Toggle Coordinate Grid} {Toggle Coordinate Grid}
::msgcat::mcset de {Toggle Horizontal Graph} {Toggle Horizontal Graph}
::msgcat::mcset de {Toggle Include/Exclude} {Toggle Include/Exclude}
::msgcat::mcset de {Toggle Smooth} {Toggle Smooth}
::msgcat::mcset de {Toggle Source/Background} {Toggle Source/Background}
::msgcat::mcset de {Toggle Vertical Graph} {Toggle Vertical Graph}
::msgcat::mcset de Tophat Tophat
::msgcat::mcset de Topographic Topographic
::msgcat::mcset de Top Top
::msgcat::mcset de To Nach
::msgcat::mcset de Transition Transition
::msgcat::mcset de Transparency Transparency
::msgcat::mcset de Triangle Triangle
::msgcat::mcset de Type Typ
::msgcat::mcset de URL URL
::msgcat::mcset de {Unable to connect directly: using Web Proxy} {Unable to connect directly: using Web Proxy}
::msgcat::mcset de {Unable to create FOV Region, celestial WCS Required} {Unable to create FOV Region, celestial WCS Required}
::msgcat::mcset de {Unable to determine date of observation} {Unable to determine date of observation}
::msgcat::mcset de {Unable to evaluate filter} {Nicht möglich Filter zu evaluieren}
::msgcat::mcset de {Unable to find Footprint window} {Unable to find Footprint window}
::msgcat::mcset de {Unable to find PRISM window} {Unable to find PRISM window}
::msgcat::mcset de {Unable to find SIAP window} {Unable to find SIAP window}
::msgcat::mcset de {Unable to find URL column} {Unable to find URL column}
::msgcat::mcset de {Unable to find catalog window} {Nicht möglich Katalogfenster zu finden}
::msgcat::mcset de {Unable to find plot window} {Nicht möglich Plotfenster zu finden}
::msgcat::mcset de {Unable to find web window} {Unable to find web window}
::msgcat::mcset de {Unable to generate plot} {Unable to generate plot}
::msgcat::mcset de {Unable to load FITS file} {Unable to load FITS file}
::msgcat::mcset de {Unable to load HLS image into a non-hls frame} {Unable to load HLS image into a non-hls frame}
::msgcat::mcset de {Unable to load HSV image into a non-hsv frame} {Unable to load HSV image into a non-hsv frame}
::msgcat::mcset de {Unable to load RGB image into a non-rgb frame} {Nicht möglich RGB-Bild in nicht-RGB-rahmen zu laden}
::msgcat::mcset de {Unable to load compressed region file} {Unable to load compressed region file}
::msgcat::mcset de {Unable to load plot data} {Unable to load plot data}
::msgcat::mcset de {Unable to load region file} {Unable to load region file}
::msgcat::mcset de {Unable to load} {Nicht möglich zu laden}
::msgcat::mcset de {Unable to locate FOV Region} {Unable to locate FOV Region}
::msgcat::mcset de {Unable to locate URL} {Nicht möglich URL zu finden}
::msgcat::mcset de {Unable to match target with XPA Mime request} {Unable to match target with XPA Mime request}
::msgcat::mcset de {Unable to open file} {Nicht möglich Datei zu öffnen}
::msgcat::mcset de {Unable to save HLS image from a non-hls frame} {Unable to save HLS image from a non-hls frame}
::msgcat::mcset de {Unable to save HSV image from a non-hsv frame} {Unable to save HSV image from a non-hsv frame}
::msgcat::mcset de {Unable to save RGB image from a non-rgb frame} {Unable to save RGB image from a non-rgb frame}
::msgcat::mcset de Undo Rückgängig
::msgcat::mcset de Unique Unique
::msgcat::mcset de Units Einheiten
::msgcat::mcset de {Unknown Colormap} {Unknown Colormap}
::msgcat::mcset de {Unknown command} {Unknown command}
::msgcat::mcset de {Update Filter} {Update Filter}
::msgcat::mcset de {Update Group} {Gruppe aktualisieren}
::msgcat::mcset de {Update from Current Crosshair} {Vom aktuellen Fadenkreuz aktualisieren}
::msgcat::mcset de {Update from Current Frame} {Vom aktuellen rahmen aktualisieren}
::msgcat::mcset de Update Aktualisieren
::msgcat::mcset de {Upper Left Back} {Upper Left Back}
::msgcat::mcset de {Upper Left Front} {Upper Left Front}
::msgcat::mcset de {Upper Right Back} {Upper Right Back}
::msgcat::mcset de {Upper Right Front} {Upper Right Front}
::msgcat::mcset de {Use Authentication} {Authentifizierung verwenden}
::msgcat::mcset de {Use Current Frame on Download} {Aktuellen rahmen bei Download verwenden}
::msgcat::mcset de {Use Internal Web Browser} {Internen Webbrowser verwenden}
::msgcat::mcset de {Use Original Color/Width} {Use Original Color/Width}
::msgcat::mcset de {Use Proxy} {Proxy verwenden}
::msgcat::mcset de {Use Theme Colors} {Use Theme Colors}
::msgcat::mcset de {Use background color instead of theme color} {Use background color instead of theme color}
::msgcat::mcset de {User Manual} {User Manual}
::msgcat::mcset de Username Login
::msgcat::mcset de User Benutzer
::msgcat::mcset de Use Benutze
::msgcat::mcset de {VO Server} {VO Server}
::msgcat::mcset de VOTable VOTable
::msgcat::mcset de VOT VOT
::msgcat::mcset de VO VO
::msgcat::mcset de Value Wert
::msgcat::mcset de Vector Vektor
::msgcat::mcset de {Vertical Graph} Vertikaldarstellung
::msgcat::mcset de {Vertical Layout} {Vertikales layout}
::msgcat::mcset de {Vertical Text} {Vertikaler text}
::msgcat::mcset de Vertical Vertical
::msgcat::mcset de View Ansicht
::msgcat::mcset de {Virtual Observatory} {Virtual Observatory}
::msgcat::mcset de {WCS Parameters} {WCS Parameters}
::msgcat::mcset de WCS WCS
::msgcat::mcset de Wavelength Wellenlänge
::msgcat::mcset de {Web Browser} Webbrowser
::msgcat::mcset de White Weiß
::msgcat::mcset de Width Breite
::msgcat::mcset de Window Window
::msgcat::mcset de {Words matching title, description} {Worte im Titel, Bezeichnung}
::msgcat::mcset de {X Axis Title} {X Axis Title}
::msgcat::mcset de {X Axis} {X Axis}
::msgcat::mcset de {X Column} {X Column}
::msgcat::mcset de {X Error Column} {X Error Column}
::msgcat::mcset de {XPA Information} {XPA Information}
::msgcat::mcset de {XPA not initialized} {XPA nicht initialisiert}
::msgcat::mcset de XPA XPA
::msgcat::mcset de X X
::msgcat::mcset de {Y Axis Title} {Y Axis Title}
::msgcat::mcset de {Y Axis} {Y Axis}
::msgcat::mcset de {Y Column} {Y Column}
::msgcat::mcset de {Y Error Column} {Y Error Column}
::msgcat::mcset de Yellow Gelb
::msgcat::mcset de Y Y
::msgcat::mcset de {Z Axis Scale} {Z Axis Scale}
::msgcat::mcset de {ZScale Parameters} {ZScale Parameters}
::msgcat::mcset de Zero Zero
::msgcat::mcset de {Zoom Fit} {Zoom Fit}
::msgcat::mcset de {Zoom In} Hineinzoomen
::msgcat::mcset de {Zoom Out} Herauszoomen
::msgcat::mcset de Zoom Zoom
::msgcat::mcset de {already connected} {already connected}
::msgcat::mcset de and and
::msgcat::mcset de b b
::msgcat::mcset de {found dead hub file, deleting} {found dead hub file, deleting}
::msgcat::mcset de {found existing hub} {found existing hub}
::msgcat::mcset de {full base} {full base}
::msgcat::mcset de full full
::msgcat::mcset de g g
::msgcat::mcset de h5utils h5utils
::msgcat::mcset de {hundredths second} {hundredths second}
::msgcat::mcset de h h
::msgcat::mcset de l l
::msgcat::mcset de minutes minutes
::msgcat::mcset de {not connected} {not connected}
::msgcat::mcset de not not
::msgcat::mcset de only only
::msgcat::mcset de {or center of data} {oder Zentrum der Daten}
::msgcat::mcset de {root base} {root base}
::msgcat::mcset de root root
::msgcat::mcset de {rows of data have been downloaded. More may be available. You may wish to adjust the maximum allowed} {Datenreihen wurden heruntergeladen. Mehr sind vielleicht verfügbar. Sie können die maximale Anzahl anpassen.}
::msgcat::mcset de r r
::msgcat::mcset de s s
::msgcat::mcset de {unable to create hub file} {unable to create hub file}
::msgcat::mcset de {unable to locate HUB} {unable to locate HUB}
::msgcat::mcset de {unable to open hub} {unable to open hub}
::msgcat::mcset de {unable to open web hub} {unable to open web hub}
::msgcat::mcset de v v
::msgcat::mcset de x x
