::msgcat::mcset de {2D} 
::msgcat::mcset de {3D View} 
::msgcat::mcset de {3D} 
::msgcat::mcset de {A postscript generation error has occurred} {Beim Erstellen von Postscript ist ein Fehler aufgetreten} 
::msgcat::mcset de {AIP} 
::msgcat::mcset de {Abort} 
::msgcat::mcset de {About SAOImageDS9} 
::msgcat::mcset de {About} [encoding convertfrom iso8859-1 {Über}]
::msgcat::mcset de {Acknowledgment} {Danksagung}
::msgcat::mcset de {Add} [encoding convertfrom iso8859-1 {Hinzufügen}]
::msgcat::mcset de {Advanced} {Erweitert}
::msgcat::mcset de {Aligned} 
::msgcat::mcset de {Align} {Ausrichten}
::msgcat::mcset de {All Columns} {Alle spalten}
::msgcat::mcset de {All Rows} {Alle zeilen}
::msgcat::mcset de {All} {Alles}
::msgcat::mcset de {Always save files during Backup} 
::msgcat::mcset de {Amplifier} [encoding convertfrom iso8859-1 {Verstärker}]
::msgcat::mcset de {An error has occurred during backup} 
::msgcat::mcset de {An error has occurred during restore} 
::msgcat::mcset de {An error has occurred invoking the Analysis task} {Beim Aufrufen des Analysetasks ist ein Fehler aufgetreten}
::msgcat::mcset de {An error has occurred while creating image.} 
::msgcat::mcset de {An error has occurred while creating the image. Please be sure that the ds9 window is in the upper left corner of the default screen and the entire window is visible.} 
::msgcat::mcset de {An error has occurred while creating the image. Please be sure that the entire image window is visible on the screen.} 
::msgcat::mcset de {An error has occurred while printing} {Beim Drucken ist ein Fehler aufgetreten}
::msgcat::mcset de {An error has occurred while reading image.} 
::msgcat::mcset de {An error has occurred while saving} {Beim Speichern ist ein Fehler aufgetreten}
::msgcat::mcset de {An error has occurred while writing image.} 
::msgcat::mcset de {An internal error has been detected} 
::msgcat::mcset de {Analysis Command Log} {Analysebefehlslog}
::msgcat::mcset de {Analysis Commands} 
::msgcat::mcset de {Analysis File} 
::msgcat::mcset de {Analysis Log} 
::msgcat::mcset de {Analysis} {Analyse}
::msgcat::mcset de {Angle Complement} {Komplementwinkel}
::msgcat::mcset de {Angles} {Winkel}
::msgcat::mcset de {Angle} {Winkel}
::msgcat::mcset de {Annuli} {Kreisringe} 
::msgcat::mcset de {Annulus} {Kreisring}
::msgcat::mcset de {Apply} {Anwenden}
::msgcat::mcset de {ArcMin} {Bogenminute}
::msgcat::mcset de {ArcSec} {Bogensekunde}
::msgcat::mcset de {Architecture} {Architektur}
::msgcat::mcset de {Archives} 
::msgcat::mcset de {Array} 
::msgcat::mcset de {Arrow} {Pfeil}
::msgcat::mcset de {Asteroids} 
::msgcat::mcset de {Astronomy} 
::msgcat::mcset de {At Startup} 
::msgcat::mcset de {At least 2 different catalogs are required} 
::msgcat::mcset de {Auto Centroid} 
::msgcat::mcset de {Auto Plot 2D} 
::msgcat::mcset de {Auto Plot 3D} 
::msgcat::mcset de {Auto Plot Statistics} 
::msgcat::mcset de {Auto Plot} 
::msgcat::mcset de {Autoload FITS Regions} {FITS-Regionen autom. laden}
::msgcat::mcset de {Autoload} 
::msgcat::mcset de {Automatic} {Automatisch} 
::msgcat::mcset de {Average} {Mitteln}
::msgcat::mcset de {Axes Number} 
::msgcat::mcset de {Axes Order} 
::msgcat::mcset de {Axes Title} 
::msgcat::mcset de {Axes}  {Achsen}
::msgcat::mcset de {Axis Length} [encoding convertfrom iso8859-1 {Achsenlänge}]
::msgcat::mcset de {Axis Numbers} {Achsenziffern}
::msgcat::mcset de {Axis Title} 
::msgcat::mcset de {Axis} {Achse}
::msgcat::mcset de {Azimuth} 
::msgcat::mcset de {Background Color} {Hintergrundfarbe} 
::msgcat::mcset de {Background} {Hintergrund} 
::msgcat::mcset de {Backup} 
::msgcat::mcset de {Back}  [encoding convertfrom iso8859-1 {Zurück}]
::msgcat::mcset de {Bar Plot Tool} 
::msgcat::mcset de {Bias} 
::msgcat::mcset de {Bin 3rd Column} {Bin 3. Spalte} 
::msgcat::mcset de {Bin Center} {Bin Zentrum} 
::msgcat::mcset de {Bin Columns} {Bin Spalten} 
::msgcat::mcset de {Bin Filter} 
::msgcat::mcset de {Bin Fit} 
::msgcat::mcset de {Bin In} 
::msgcat::mcset de {Bin Out} 
::msgcat::mcset de {Binning Parameters} {Binparameter}
::msgcat::mcset de {Bin} 
::msgcat::mcset de {Black} {Schwarz}
::msgcat::mcset de {Blank/Inf/NaN Color} {Leer/Inf/Nan Farbe}
::msgcat::mcset de {Blink Frames} {Blinkende rahmen}
::msgcat::mcset de {Blink Interval} {Blinkinterval}
::msgcat::mcset de {Blink} {Blinken}
::msgcat::mcset de {Block Fit} 
::msgcat::mcset de {Block In} {Bin ein}
::msgcat::mcset de {Block Out} {Bin aus}
::msgcat::mcset de {Block Parameters} 
::msgcat::mcset de {Block} {Bin}
::msgcat::mcset de {Blue} {Blau}
::msgcat::mcset de {Bold} {Fett}
::msgcat::mcset de {Border} {Begrenzung}
::msgcat::mcset de {Bottom} 
::msgcat::mcset de {Box Annulus} {Viereck ring}
::msgcat::mcset de {Box Panda} {Viereckiger panda}
::msgcat::mcset de {BoxCircle} 
::msgcat::mcset de {Boxcar} 
::msgcat::mcset de {Box} {Viereck}
::msgcat::mcset de {Broadcast} 
::msgcat::mcset de {Browser} 
::msgcat::mcset de {Browse} [encoding convertfrom iso8859-1 {Auswählen}]
::msgcat::mcset de {Buffer} {Puffer}
::msgcat::mcset de {Buttonbar} 
::msgcat::mcset de {Buttons} [encoding convertfrom iso8859-1 {Schaltflächen}]
::msgcat::mcset de {Bytes} 
::msgcat::mcset de {CMYK} 
::msgcat::mcset de {Can Delete} {Kann löschen}
::msgcat::mcset de {Can Edit} {Kann bearbeiten}
::msgcat::mcset de {Can Move} {Kann bewegen}
::msgcat::mcset de {Can Rotate} {Kann rotieren}
::msgcat::mcset de {Cancelled} 
::msgcat::mcset de {Cancel} {Abbrechen}
::msgcat::mcset de {Cap} 
::msgcat::mcset de {Catalog Server}  {Katalogserver}
::msgcat::mcset de {Catalog Tool} {Katalogwerkzeug}
::msgcat::mcset de {Catalogs} {Kataloge}
::msgcat::mcset de {Catalog} {Katalog}
::msgcat::mcset de {Catrom} 
::msgcat::mcset de {Cat} 
::msgcat::mcset de {Center Image} {Bild zentrieren}
::msgcat::mcset de {Center Non-modal Dialogs} 
::msgcat::mcset de {Center} {Mittelpunkt}
::msgcat::mcset de {Centroid Parameters} 
::msgcat::mcset de {Centroid} 
::msgcat::mcset de {Circle} {Kreis}
::msgcat::mcset de {Clear All} [encoding convertfrom iso8859-1 {Alle löschen}]
::msgcat::mcset de {Clear Analysis Commands} [encoding convertfrom iso8859-1 {Analysebefehle löschen}]
::msgcat::mcset de {Clear Cache} [encoding convertfrom iso8859-1 {Cache löschen}]
::msgcat::mcset de {Clear Data} [encoding convertfrom iso8859-1 {Daten löschen}]
::msgcat::mcset de {Clear External Analysis Commands?} [encoding convertfrom iso8859-1 {Externe Analysebefehle löschen?}]
::msgcat::mcset de {Clear Filter} [encoding convertfrom iso8859-1 {Filter löschen}]
::msgcat::mcset de {Clear Frame} {Rahmen freigeben}
::msgcat::mcset de {Clear Preferences?} [encoding convertfrom iso8859-1 {Voreinstellungen löschen?}]
::msgcat::mcset de {Clear Preferences} [encoding convertfrom iso8859-1 {Voreinstellungen löschen}]
::msgcat::mcset de {Clear} [encoding convertfrom iso8859-1 {Löschen}]
::msgcat::mcset de {Click to Center} {Klicken zum Zentrieren}
::msgcat::mcset de {Close} [encoding convertfrom iso8859-1 {Schließen}]
::msgcat::mcset de {Colorbar Size} 
::msgcat::mcset de {Colorbar} {Farbbalken}
::msgcat::mcset de {Colormap Parameters} {Farbpalettenparameter}
::msgcat::mcset de {Colormap} 
::msgcat::mcset de {Color} {Farbe}
::msgcat::mcset de {Columns} {Spalten}
::msgcat::mcset de {Column} {Spalte} 
::msgcat::mcset de {Comets} 
::msgcat::mcset de {Command not allowed} 
::msgcat::mcset de {Command} 
::msgcat::mcset de {Compass} {Kompass}
::msgcat::mcset de {Composite Region} 
::msgcat::mcset de {Composite} 
::msgcat::mcset de {Compression} {Kompression} 
::msgcat::mcset de {Configure} {Konfigurieren}
::msgcat::mcset de {Connect Directly} {Direkt verbinden}
::msgcat::mcset de {Connect SAMP} 
::msgcat::mcset de {Connect Using Web Proxy} [encoding convertfrom iso8859-1 {Für Verbindung Webproxy verwenden}] 
::msgcat::mcset de {Connect} 
::msgcat::mcset de {Console} 
::msgcat::mcset de {Contacting Image Server} 
::msgcat::mcset de {Contour Parameters} {Konturenparameter}
::msgcat::mcset de {Contour Paste} 
::msgcat::mcset de {Contour Save} 
::msgcat::mcset de {Contours} {Konturen}
::msgcat::mcset de {Contour} 
::msgcat::mcset de {Contrast} {Kontrast}
::msgcat::mcset de {Convert to Polygons} {Zu Polygonen konvertieren}
::msgcat::mcset de {Coordinate Grid Parameters} {Koordinatennetzparameter}
::msgcat::mcset de {Coordinate Grid} {Koordinatennetz}
::msgcat::mcset de {Coordinate System} {Koordinatensystem}
::msgcat::mcset de {Coordinates} 
::msgcat::mcset de {Coordinate} {Koordinaten}
::msgcat::mcset de {Copy Contours} {Konturen kopieren}
::msgcat::mcset de {Copy to Regions} {Zu Regionen kopieren}
::msgcat::mcset de {Copy} {Kopieren}
::msgcat::mcset de {Create Movie} 
::msgcat::mcset de {Create New Frame on Download} {Neuen rahmen bei Download}
::msgcat::mcset de {Create} 
::msgcat::mcset de {Crop Parameters} 
::msgcat::mcset de {Crop} 
::msgcat::mcset de {Crosshair Parameters} 
::msgcat::mcset de {Crosshair To}  {Fadenkreuz auf}
::msgcat::mcset de {Crosshair} {Fadenkreuz}
::msgcat::mcset de {Cross} {Kreuz}
::msgcat::mcset de {Cubehelix} 
::msgcat::mcset de {Cube} 
::msgcat::mcset de {Cubic} 
::msgcat::mcset de {Current Frame} {Aktueller rahmen}
::msgcat::mcset de {Current Range} {Aktueller bereich}
::msgcat::mcset de {Current} {Aktuell}
::msgcat::mcset de {Cursor} {Zeiger}
::msgcat::mcset de {Cut} {Ausschneiden}
::msgcat::mcset de {Cyan} {Zyan}
::msgcat::mcset de {DMS} 
::msgcat::mcset de {DPI} 
::msgcat::mcset de {DS9 has detected a newer version of a backup file and therefore will not process this file.} 
::msgcat::mcset de {DS9 has detected a newer version of a preferences file.} 
::msgcat::mcset de {DS9 has detected an older backup file, do you wish to continue?} 
::msgcat::mcset de {DS9 has detected an older preferences file, do you wish to update?} [encoding convertfrom iso8859-1 {DS9 hat ein ältere Einstellungsdatei erkannt, möchten Sie aktualisieren?}]
::msgcat::mcset de {DS9 will complete the initialization process} [encoding convertfrom iso8859-1 {DS9 wird den Initialisierungsprozeß vervollständigen}]
::msgcat::mcset de {Dash} {Gestrichelt}
::msgcat::mcset de {Data Format} {Datenformat}
::msgcat::mcset de {Dataset Name} 
::msgcat::mcset de {Dataset} {Datensatz}
::msgcat::mcset de {Data} 
::msgcat::mcset de {Decrease} {Absteigend}
::msgcat::mcset de {Default All Files} 
::msgcat::mcset de {Default Format} 
::msgcat::mcset de {Default Length} 
::msgcat::mcset de {Default} {Standard}
::msgcat::mcset de {Degrees} {Grad}
::msgcat::mcset de {Delete All Frames?} [encoding convertfrom iso8859-1 {Alle rahmen löschen?}]
::msgcat::mcset de {Delete All Frames} [encoding convertfrom iso8859-1 {Alle rahmen löschen}]
::msgcat::mcset de {Delete All Groups?} [encoding convertfrom iso8859-1 {Alle Gruppen löschen?}]
::msgcat::mcset de {Delete All Groups} [encoding convertfrom iso8859-1 {Alle Gruppen löschen}]
::msgcat::mcset de {Delete All Regions?} [encoding convertfrom iso8859-1 {Alle Regionen löschen?}]
::msgcat::mcset de {Delete All Regions} [encoding convertfrom iso8859-1 {Alle Regionen löschen}]
::msgcat::mcset de {Delete All} 
::msgcat::mcset de {Delete Color Tags} 
::msgcat::mcset de {Delete Frame} [encoding convertfrom iso8859-1 {Rahmen löschen}]
::msgcat::mcset de {Delete Group} [encoding convertfrom iso8859-1 {Gruppe löschen}]
::msgcat::mcset de {Delete Selected Regions} [encoding convertfrom iso8859-1 {Ausgewählte Regionen löschen}]
::msgcat::mcset de {Delete} [encoding convertfrom iso8859-1 {Löschen}]
::msgcat::mcset de {Depth} {Tiefe}
::msgcat::mcset de {Detector} {Detektor}
::msgcat::mcset de {Dialog Box} {Dialogbox}
::msgcat::mcset de {Diameter} 
::msgcat::mcset de {Diamond} {Raute}
::msgcat::mcset de {Dimension} 
::msgcat::mcset de {Direction} 
::msgcat::mcset de {Disconnect} 
::msgcat::mcset de {Display Header} 
::msgcat::mcset de {Display Size} [encoding convertfrom iso8859-1 {Größe zeigen}]
::msgcat::mcset de {Dissolve} 
::msgcat::mcset de {Distance} 
::msgcat::mcset de {Done} 
::msgcat::mcset de {Download Colormap} 
::msgcat::mcset de {Download VOTABLE format if available} 
::msgcat::mcset de {Drag to Center} {Ziehen zum zentrieren}
::msgcat::mcset de {Duplicate Data} 
::msgcat::mcset de {East} {Osten}
::msgcat::mcset de {Ecliptic} {Ekliptisch}
::msgcat::mcset de {Edit Group Name} {Gruppenname bearbeiten}
::msgcat::mcset de {Edit} {Bearbeiten}
::msgcat::mcset de {Elevation} 
::msgcat::mcset de {Ellipse Annulus} 
::msgcat::mcset de {Ellipse Panda} {Ellipsen Panda}
::msgcat::mcset de {Ellipse} 
::msgcat::mcset de {Elliptical Annulus} {Elliptischer Kreisring}
::msgcat::mcset de {Elliptical Gaussian} 
::msgcat::mcset de {Elliptical Panda} {Elliptischer Panda}
::msgcat::mcset de {Enable Confirmation Dialogs} [encoding convertfrom iso8859-1 {Bestätigungsdialoge einschalten}]
::msgcat::mcset de {Enable} 
::msgcat::mcset de {End} {Ende}
::msgcat::mcset de {Enter Color} 
::msgcat::mcset de {Enter Font Size} 
::msgcat::mcset de {Enter Group Name} {Gruppenname eingeben}
::msgcat::mcset de {Enter Search Expression} 
::msgcat::mcset de {Enter URL} 
::msgcat::mcset de {Entry} 
::msgcat::mcset de {Equal Area} [encoding convertfrom iso8859-1 {Gleiche Fläche}]
::msgcat::mcset de {Equal Distance} {Gleicher Abstand}
::msgcat::mcset de {Equal Spacing} 
::msgcat::mcset de {Equal Value} 
::msgcat::mcset de {Error code was returned} [encoding convertfrom iso8859-1 {Fehlercode wurde zurückgegeben}]
::msgcat::mcset de {Error} {Fehler}
::msgcat::mcset de {Examine Frame} {Rahmen inspizieren}
::msgcat::mcset de {Examine} {Inspizieren}
::msgcat::mcset de {Exam} 
::msgcat::mcset de {Exclude} {Ausschliessen}
::msgcat::mcset de {Exit} [encoding convertfrom iso8859-1 {Schließen}]
::msgcat::mcset de {Export Array} 
::msgcat::mcset de {Export} 
::msgcat::mcset de {Extention} 
::msgcat::mcset de {Exterior Axes} [encoding convertfrom iso8859-1 {Äußere Achsen}]
::msgcat::mcset de {Exterior Numerics} [encoding convertfrom iso8859-1 {Äußere Ziffern}]
::msgcat::mcset de {FAQ} 
::msgcat::mcset de {FK4} 
::msgcat::mcset de {FK5} 
::msgcat::mcset de {Factor} 
::msgcat::mcset de {File not Found or Unable to load FITS data MIME type} [encoding convertfrom iso8859-1 {Datei nicht gefunden oder nicht möglich FITS-Daten MIME-Type zu laden}]
::msgcat::mcset de {Filename} {Dateiname}
::msgcat::mcset de {File} {Datei}
::msgcat::mcset de {Fill} 
::msgcat::mcset de {Filter} 
::msgcat::mcset de {Find Next} [encoding convertfrom iso8859-1 {Nächsten finden}]
::msgcat::mcset de {Find} {Suchen}
::msgcat::mcset de {First Frame} {Erster rahmen}
::msgcat::mcset de {First} {Erster}
::msgcat::mcset de {Fits} 
::msgcat::mcset de {Fixed in Size} [encoding convertfrom iso8859-1 {Feste Größe}]
::msgcat::mcset de {Flat} 
::msgcat::mcset de {Flip} 
::msgcat::mcset de {Font} 
::msgcat::mcset de {For more information, use --help} 
::msgcat::mcset de {Format} 
::msgcat::mcset de {Forward} [encoding convertfrom iso8859-1 {Vorwärts}]
::msgcat::mcset de {Found} {Gefunden}
::msgcat::mcset de {Frame Information} {Rahmeninformation}
::msgcat::mcset de {Frame Parameters} 
::msgcat::mcset de {Frames} 
::msgcat::mcset de {Frame} {Rahmen}
::msgcat::mcset de {From} 
::msgcat::mcset de {Front} {Vor}
::msgcat::mcset de {Full Range} {Ganzer Bereich}
::msgcat::mcset de {Function} {Funktion}
::msgcat::mcset de {GUI Font} 
::msgcat::mcset de {Galactic} {Galaktisch}
::msgcat::mcset de {Gap} 
::msgcat::mcset de {Gaussian} {Gauss}
::msgcat::mcset de {General} {Allgemein}
::msgcat::mcset de {Generate} {Herstellen}
::msgcat::mcset de {Generating Regions} {Regionen erstellen}
::msgcat::mcset de {Get Information} {Informationen}
::msgcat::mcset de {Gist} 
::msgcat::mcset de {Global Properties} 
::msgcat::mcset de {Global} 
::msgcat::mcset de {Goto Frame} 
::msgcat::mcset de {Graph Horz} 
::msgcat::mcset de {Graph Parameters} 
::msgcat::mcset de {Graph Vert} 
::msgcat::mcset de {Graphics} {Grafik}
::msgcat::mcset de {Graphs} 
::msgcat::mcset de {Graph} 
::msgcat::mcset de {Grayscale} {Graustufen}
::msgcat::mcset de {Green} [encoding convertfrom iso8859-1 {Grün}]
::msgcat::mcset de {Grid Gap} {Gitterabstand}
::msgcat::mcset de {Grid} {Gitter}
::msgcat::mcset de {Groove} 
::msgcat::mcset de {Groups} {Gruppen}
::msgcat::mcset de {HMS} 
::msgcat::mcset de {HTTP} 
::msgcat::mcset de {Header} {Dateikopf}
::msgcat::mcset de {Height} [encoding convertfrom iso8859-1 {Höhe}]
::msgcat::mcset de {Help Desk} {Hilfestelle}
::msgcat::mcset de {Help Me Choose} [encoding convertfrom iso8859-1 {Hilf mir auswählen}]
::msgcat::mcset de {Help} {Hilfe}
::msgcat::mcset de {Hide All} {Alle verstecken}
::msgcat::mcset de {Highlite} 
::msgcat::mcset de {High} {Hoch}
::msgcat::mcset de {Histogram Equalization} {Histogrammausgleich}
::msgcat::mcset de {Histogram} {Histogramm}
::msgcat::mcset de {Horizontal Graph} {Horizontaldarstellung}
::msgcat::mcset de {Horizontal Layout} {Horizontales Layout}
::msgcat::mcset de {Horizontal} 
::msgcat::mcset de {IAU Location Code} 
::msgcat::mcset de {ICRS} 
::msgcat::mcset de {Identification} {Kennzeichnung}
::msgcat::mcset de {If} {Wenn}
::msgcat::mcset de {Image Servers} 
::msgcat::mcset de {Image} {Bild}
::msgcat::mcset de {Import Array} 
::msgcat::mcset de {Import} 
::msgcat::mcset de {Include} {Einschliessen}
::msgcat::mcset de {Increase} {Aufsteigend}
::msgcat::mcset de {Information Panel} {Informationsfeld}
::msgcat::mcset de {Information} {Informations}
::msgcat::mcset de {Initialize XPA} {XPA initialisieren}
::msgcat::mcset de {Inner} {Innerer}
::msgcat::mcset de {Instrument FOV} {Instrumentensichtfeld}
::msgcat::mcset de {Interior Axes} {Innere Achsen}
::msgcat::mcset de {Interior Numerics} {Innere Ziffern}
::msgcat::mcset de {Internal Parse Error} 
::msgcat::mcset de {Interval} {Intervall}
::msgcat::mcset de {Invalid Column Name} 
::msgcat::mcset de {Invalid WCS} 
::msgcat::mcset de {Invalid formated multipart/mixed mime type message} [encoding convertfrom iso8859-1 {Ungültig formatierter multipart/mixed MIME-Type}]
::msgcat::mcset de {Invert Colormap} {Farbpalette invertieren}
::msgcat::mcset de {Invert Selection} {Auswahl umkehren}
::msgcat::mcset de {Invert} {Invertieren}
::msgcat::mcset de {Italic} {Kursiv}
::msgcat::mcset de {Items Found} 
::msgcat::mcset de {Iteration} 
::msgcat::mcset de {JPEG Quality Factor} [encoding convertfrom iso8859-1 {JPEG Qualitätsfaktor}]
::msgcat::mcset de {Keep-Alive} 
::msgcat::mcset de {Keyboard} {Tastatur}
::msgcat::mcset de {Keyword} 
::msgcat::mcset de {Labels} {Beschriftung}
::msgcat::mcset de {Label} 
::msgcat::mcset de {Landscape} {Horizontal}
::msgcat::mcset de {Language} {Sprache}
::msgcat::mcset de {Last Frame} {Letzter rahmen}
::msgcat::mcset de {Last} {Letzter}
::msgcat::mcset de {Layout Horz} 
::msgcat::mcset de {Layout Vert} 
::msgcat::mcset de {Layout} 
::msgcat::mcset de {Left} 
::msgcat::mcset de {Legal} 
::msgcat::mcset de {Legend Title} 
::msgcat::mcset de {Legend} 
::msgcat::mcset de {Length} [encoding convertfrom iso8859-1 {Länge}]
::msgcat::mcset de {Letter} 
::msgcat::mcset de {Levels} {Niveaus}
::msgcat::mcset de {Level} {Niveau}
::msgcat::mcset de {Limits} {Grenzen}
::msgcat::mcset de {Line Plot Tool} 
::msgcat::mcset de {Linear} 
::msgcat::mcset de {Line} {Linie}
::msgcat::mcset de {List Data} 
::msgcat::mcset de {List Regions} {Regionen auflisten}
::msgcat::mcset de {List} {Auflisten}
::msgcat::mcset de {Load Analysis Commands} {Analysebefehle laden}
::msgcat::mcset de {Load Color Tags} 
::msgcat::mcset de {Load Colormap} {Farbpalette laden}
::msgcat::mcset de {Load Configuration} {Konfiguration laden}
::msgcat::mcset de {Load Contour Levels} {Kontourniveaus laden}
::msgcat::mcset de {Load Contours} {Konturen laden}
::msgcat::mcset de {Load Contrast/Bias} {Kontrast/Bias laden}
::msgcat::mcset de {Load Data} {Daten laden}
::msgcat::mcset de {Load Mosaic} {Mosaic laden}
::msgcat::mcset de {Load Regions} {Regionen laden}
::msgcat::mcset de {Load Template} {Vorlage laden}
::msgcat::mcset de {Load into All Frames} 
::msgcat::mcset de {Load into Current Frame} 
::msgcat::mcset de {Loading Catalog} 
::msgcat::mcset de {Loading} 
::msgcat::mcset de {Load} {Laden}
::msgcat::mcset de {Local} {Lokal}
::msgcat::mcset de {Lock Axes} 
::msgcat::mcset de {Lock Bin} 
::msgcat::mcset de {Lock Color} 
::msgcat::mcset de {Lock Crop Amplifier} 
::msgcat::mcset de {Lock Crop Detector} 
::msgcat::mcset de {Lock Crop Image} 
::msgcat::mcset de {Lock Crop None} 
::msgcat::mcset de {Lock Crop Physical} 
::msgcat::mcset de {Lock Crop WCS} 
::msgcat::mcset de {Lock Crosshair Amplifier} 
::msgcat::mcset de {Lock Crosshair Detector} 
::msgcat::mcset de {Lock Crosshair Image} 
::msgcat::mcset de {Lock Crosshair None} 
::msgcat::mcset de {Lock Crosshair Physical} 
::msgcat::mcset de {Lock Crosshair WCS} 
::msgcat::mcset de {Lock Frame Amplifier} 
::msgcat::mcset de {Lock Frame Detector} 
::msgcat::mcset de {Lock Frame Image} 
::msgcat::mcset de {Lock Frame None} 
::msgcat::mcset de {Lock Frame Physical} 
::msgcat::mcset de {Lock Frame WCS} 
::msgcat::mcset de {Lock Limits} 
::msgcat::mcset de {Lock Scale} 
::msgcat::mcset de {Lock Slice Image} 
::msgcat::mcset de {Lock Slice None} 
::msgcat::mcset de {Lock Slice WCS} 
::msgcat::mcset de {Lock Smooth} 
::msgcat::mcset de {Lock} {Arretieren}
::msgcat::mcset de {Log Exponent} 
::msgcat::mcset de {Log} 
::msgcat::mcset de {Low High} {Niedrig Hoch}
::msgcat::mcset de {Lower Left Back} 
::msgcat::mcset de {Lower Left Front} 
::msgcat::mcset de {Lower Right Back} 
::msgcat::mcset de {Lower Right Front} 
::msgcat::mcset de {Low} {Niedrig}
::msgcat::mcset de {MIP} 
::msgcat::mcset de {Magenta} 
::msgcat::mcset de {Magnification} 
::msgcat::mcset de {Magnifier} [encoding convertfrom iso8859-1 {Vergrößerungsglas}]
::msgcat::mcset de {Major Radius} 
::msgcat::mcset de {Major Sigma} 
::msgcat::mcset de {Major} [encoding convertfrom iso8859-1 {Groß}]
::msgcat::mcset de {Manual} {Manuell}
::msgcat::mcset de {Mask Parameters} {Maskenparameter}
::msgcat::mcset de {Match Axes} 
::msgcat::mcset de {Match Bin} 
::msgcat::mcset de {Match Catalog requires at least 1 row per catalog} 
::msgcat::mcset de {Match Color} 
::msgcat::mcset de {Match Crop Amplifier} 
::msgcat::mcset de {Match Crop Detector} 
::msgcat::mcset de {Match Crop Image} 
::msgcat::mcset de {Match Crop Physical} 
::msgcat::mcset de {Match Crop WCS} 
::msgcat::mcset de {Match Crosshair Amplifier} 
::msgcat::mcset de {Match Crosshair Detector} 
::msgcat::mcset de {Match Crosshair Image} 
::msgcat::mcset de {Match Crosshair Physical} 
::msgcat::mcset de {Match Crosshair WCS} 
::msgcat::mcset de {Match Frame Amplifier} 
::msgcat::mcset de {Match Frame Detector} 
::msgcat::mcset de {Match Frame Image} 
::msgcat::mcset de {Match Frame Physical} 
::msgcat::mcset de {Match Frame WCS} 
::msgcat::mcset de {Match Limits} 
::msgcat::mcset de {Match Scale} 
::msgcat::mcset de {Match Slice Image} 
::msgcat::mcset de {Match Slice WCS} 
::msgcat::mcset de {Match Smooth} 
::msgcat::mcset de {Match} 
::msgcat::mcset de {Math Function} {Math. Funktion}
::msgcat::mcset de {Matplotlib} 
::msgcat::mcset de {Max Rows} {Max. Reihen}
::msgcat::mcset de {Maximum} 
::msgcat::mcset de {Max} 
::msgcat::mcset de {Menus and Buttons} 
::msgcat::mcset de {Menu} 
::msgcat::mcset de {Message Log} 
::msgcat::mcset de {Method} {Methode}
::msgcat::mcset de {Min Max Parameters} 
::msgcat::mcset de {Min Max} 
::msgcat::mcset de {Minimum} 
::msgcat::mcset de {Minor Radius} 
::msgcat::mcset de {Minor Sigma} 
::msgcat::mcset de {Minor} {Gering}
::msgcat::mcset de {Minutes} 
::msgcat::mcset de {Min} 
::msgcat::mcset de {Mission} 
::msgcat::mcset de {Mode} 
::msgcat::mcset de {Mosaic IRAF Segment} 
::msgcat::mcset de {Mosaic IRAF} 
::msgcat::mcset de {Mosaic WCS Segment} 
::msgcat::mcset de {Mosaic WCS} 
::msgcat::mcset de {Mosaic WFPC2} 
::msgcat::mcset de {Mosaic} 
::msgcat::mcset de {Mouse Click Epsilon} 
::msgcat::mcset de {Mouse Wheel Bin} 
::msgcat::mcset de {Mouse Wheel Zoom} 
::msgcat::mcset de {Move Back} 
::msgcat::mcset de {Move First} 
::msgcat::mcset de {Move Forward} 
::msgcat::mcset de {Move Frame} 
::msgcat::mcset de {Move Last} 
::msgcat::mcset de {Move to Back} {Nach hinten}
::msgcat::mcset de {Move to Front} {Nach vorne} 
::msgcat::mcset de {Movie} 
::msgcat::mcset de {Multiple Extension Cube} 
::msgcat::mcset de {Multiple Extension Frames} 
::msgcat::mcset de {Multiple WCS} {Mehrere WCS}
::msgcat::mcset de {NRRD} 
::msgcat::mcset de {Name Resolution} {Namensbestimmung}
::msgcat::mcset de {Name Server} 
::msgcat::mcset de {Name or Designation} {Name oder Bezeichnung}
::msgcat::mcset de {Name} 
::msgcat::mcset de {Native Dialog} {Systemnativer Dialog}
::msgcat::mcset de {New Features} {Neue Eigenschaften}
::msgcat::mcset de {New Frame 3D} 
::msgcat::mcset de {New Frame RGB} {Neuer RGB rahmen}
::msgcat::mcset de {New Frame each Time} {Neuer rahmen jedes Mal}
::msgcat::mcset de {New Frame} {Neuer rahmen}
::msgcat::mcset de {New Group} {Neue Gruppe}
::msgcat::mcset de {New} {Neu}
::msgcat::mcset de {Next Frame} [encoding convertfrom iso8859-1 {Nächster rahmen}]
::msgcat::mcset de {Next} [encoding convertfrom iso8859-1 {Nächster}]
::msgcat::mcset de {No Catalog specified} {Keine Katalog spezifiziert}
::msgcat::mcset de {No Data Available} 
::msgcat::mcset de {No Items Found} {Keine Objekte gefunden}
::msgcat::mcset de {No current frame} 
::msgcat::mcset de {Non-zero} 
::msgcat::mcset de {None} {Kein}
::msgcat::mcset de {Normal} 
::msgcat::mcset de {North} {Norden}
::msgcat::mcset de {Not Found} 
::msgcat::mcset de {Not Supported} 
::msgcat::mcset de {Number of Samples} {Anzahl der Stichproben}
::msgcat::mcset de {Number of Threads} 
::msgcat::mcset de {Number of Ticks} 
::msgcat::mcset de {Number} {Zahl}
::msgcat::mcset de {Numerics} 
::msgcat::mcset de {OK} 
::msgcat::mcset de {Object} {Objekt}
::msgcat::mcset de {Open File} [encoding convertfrom iso8859-1 {Datei öffnen}]
::msgcat::mcset de {Open TCL Console} 
::msgcat::mcset de {Open URL} [encoding convertfrom iso8859-1 {URL Öffnen}]
::msgcat::mcset de {Open as} 
::msgcat::mcset de {Open} [encoding convertfrom iso8859-1 {Öffnen}]
::msgcat::mcset de {Operator} 
::msgcat::mcset de {Orientation} {Orientierung}
::msgcat::mcset de {Origin} 
::msgcat::mcset de {Oscillate} 
::msgcat::mcset de {Other Color} 
::msgcat::mcset de {Other Font Size} 
::msgcat::mcset de {Other} {Andere}
::msgcat::mcset de {Outer} [encoding convertfrom iso8859-1 {Äußerer}]
::msgcat::mcset de {Overlap} 
::msgcat::mcset de {PS Page Setup} 
::msgcat::mcset de {PS Print} 
::msgcat::mcset de {Page Setup} {Seitensetup}
::msgcat::mcset de {Page Source} {Seitenquelle}
::msgcat::mcset de {Pan To} {Ausrichten auf}
::msgcat::mcset de {Pan Zoom Rotate Parameters} {Ausrichten zoomen rotieren}
::msgcat::mcset de {Pan Zoom} 
::msgcat::mcset de {Pan then Zoom} {Ausrichten dann Zoomen}
::msgcat::mcset de {Panda} 
::msgcat::mcset de {Panner} [encoding convertfrom iso8859-1 {Übersichtsfeld}]
::msgcat::mcset de {Pan} {Ausrichtung}
::msgcat::mcset de {Parameters} {Parameter}
::msgcat::mcset de {Password} {Passwort}
::msgcat::mcset de {Paste Contours} [encoding convertfrom iso8859-1 {Konturen einfügen}]
::msgcat::mcset de {Paste} [encoding convertfrom iso8859-1 {Einfügen}]
::msgcat::mcset de {Physical} {Physikalisch}
::msgcat::mcset de {Pixel Distribution} {Pixelverteilung}
::msgcat::mcset de {Pixel Size} [encoding convertfrom iso8859-1 {Pixelgröße}]
::msgcat::mcset de {Pixel Table} {Pixeltabelle}
::msgcat::mcset de {Pixels} {Pixel}
::msgcat::mcset de {Planets} 
::msgcat::mcset de {Play} {Abspielen}
::msgcat::mcset de {Please Select a Region} 
::msgcat::mcset de {Please change the file's permission to disable other users write access. Use anyway?} 
::msgcat::mcset de {Please specify width, height, and either name or (ra,dec)} [encoding convertfrom iso8859-1 {Bitte Weite, Höhe und entweder Namen oder (RA,Dec) angeben}]
::msgcat::mcset de {Plot 2D} 
::msgcat::mcset de {Plot 3D} 
::msgcat::mcset de {Plot Title} {Titel drucken}
::msgcat::mcset de {Plotting Regions} {Regionen drucken}
::msgcat::mcset de {Plot} 
::msgcat::mcset de {Plus} 
::msgcat::mcset de {Pointer} {Zeiger}
::msgcat::mcset de {Points} {Punkte}
::msgcat::mcset de {Point} {Punkt}
::msgcat::mcset de {Polygon} 
::msgcat::mcset de {Portrait} {Vertikal}
::msgcat::mcset de {Poster} 
::msgcat::mcset de {Postscript Page Setup} 
::msgcat::mcset de {Postscript Print} 
::msgcat::mcset de {Postscript} 
::msgcat::mcset de {Power} {Exp}
::msgcat::mcset de {Precision} 
::msgcat::mcset de {Preferences} {Einstellungen}
::msgcat::mcset de {Preserve During Load} {Beim Laden beibehalten}
::msgcat::mcset de {Previous Frame} {Vorheriger rahmen}
::msgcat::mcset de {Previous} {Vorheriger}
::msgcat::mcset de {Prev} 
::msgcat::mcset de {Print Coordinates} {Koordinaten drucken}
::msgcat::mcset de {Print To} {Drucken}
::msgcat::mcset de {Printer} {Drucker}
::msgcat::mcset de {Print} {Drucken}
::msgcat::mcset de {Projection} {Projektion}
::msgcat::mcset de {Properties} {Eigenschaften}
::msgcat::mcset de {Property} {Eigenschaften}
::msgcat::mcset de {Proxy Host} 
::msgcat::mcset de {Proxy Port} 
::msgcat::mcset de {Publication} [encoding convertfrom iso8859-1 {Veröffentlichung}]
::msgcat::mcset de {Quadratic} {Quadratisch}
::msgcat::mcset de {RGB Array} 
::msgcat::mcset de {RGB Cube} 
::msgcat::mcset de {RGB Image} 
::msgcat::mcset de {RGB} 
::msgcat::mcset de {Radial Profile} 
::msgcat::mcset de {Radial} 
::msgcat::mcset de {Radius} 
::msgcat::mcset de {Raised} 
::msgcat::mcset de {Range} 
::msgcat::mcset de {Redo} {Wiederholen}
::msgcat::mcset de {Red} {Rot}
::msgcat::mcset de {Reference Manual} {Referenzhandbuch}
::msgcat::mcset de {Reference} {Referenz}
::msgcat::mcset de {Refresh Frame} {Rahmen erneuern}
::msgcat::mcset de {Refresh} 
::msgcat::mcset de {Region Parameters} 
::msgcat::mcset de {Region} 
::msgcat::mcset de {Release Notes} {Versionshinweise}
::msgcat::mcset de {Release} {Version}
::msgcat::mcset de {Relief} 
::msgcat::mcset de {Reload} {Wieder laden}
::msgcat::mcset de {Render} 
::msgcat::mcset de {Repeat} 
::msgcat::mcset de {Reset Colormap} [encoding convertfrom iso8859-1 {Farbpalette zurücksetzen}]
::msgcat::mcset de {Reset Frame} [encoding convertfrom iso8859-1 {Rahmen zurücksetzen}]
::msgcat::mcset de {Reset} 
::msgcat::mcset de {Restore} 
::msgcat::mcset de {Retrieve} {Suchen}
::msgcat::mcset de {Return} 
::msgcat::mcset de {Right} 
::msgcat::mcset de {Roman} 
::msgcat::mcset de {Rotate} {Rotieren}
::msgcat::mcset de {Rows} {Reihen}
::msgcat::mcset de {Row} 
::msgcat::mcset de {Ruler} {Lineal}
::msgcat::mcset de {SAMP Image} 
::msgcat::mcset de {SAMP Table} 
::msgcat::mcset de {SAMP: not connected} 
::msgcat::mcset de {SAMP} 
::msgcat::mcset de {Sample Increment} 
::msgcat::mcset de {Sample Parameters} 
::msgcat::mcset de {Samples per Line} {Stichproben pro Linie}
::msgcat::mcset de {Sample} 
::msgcat::mcset de {Save 3D Movie} 
::msgcat::mcset de {Save Color Tags} 
::msgcat::mcset de {Save Colormap} {Farbpalette speichern}
::msgcat::mcset de {Save Configuration} {Konfiguration speichern}
::msgcat::mcset de {Save Contour Levels} {Konturniveaus speichern}
::msgcat::mcset de {Save Contours} {Konturen speichern}
::msgcat::mcset de {Save Contrast/Bias} {Kontrast/Bias speichern}
::msgcat::mcset de {Save Data} {Daten speichern}
::msgcat::mcset de {Save Image on Download} 
::msgcat::mcset de {Save Image} {Bild speichern}
::msgcat::mcset de {Save Regions} {Regionen speichern}
::msgcat::mcset de {Save Template} {Vorlage speichern}
::msgcat::mcset de {Save as} 
::msgcat::mcset de {Save} {Speichern}
::msgcat::mcset de {Scale Parameters} {Skalierungsparameter}
::msgcat::mcset de {Scale and Limits} 
::msgcat::mcset de {Scale} {Skalierung}
::msgcat::mcset de {Scan} {Abtastung}
::msgcat::mcset de {Scatter Plot Tool} 
::msgcat::mcset de {Scope} {Anwendungsbereich}
::msgcat::mcset de {Search for Catalogs} {Nach Katalogen suchen}
::msgcat::mcset de {Searching for catalogs} {Suche nach Katalogen}
::msgcat::mcset de {Seconds} {Sekunden}
::msgcat::mcset de {Segment} 
::msgcat::mcset de {Select All} [encoding convertfrom iso8859-1 {Alle auswählen}]
::msgcat::mcset de {Select Coordinate System }  [encoding convertfrom iso8859-1 {Koordinatensystem auswählen}]
::msgcat::mcset de {Select None} [encoding convertfrom iso8859-1 {Nichts auswählen}]
::msgcat::mcset de {Select} 
::msgcat::mcset de {Send} 
::msgcat::mcset de {Server} 
::msgcat::mcset de {Sexagesimal} 
::msgcat::mcset de {Shape} {Form}
::msgcat::mcset de {Show All} {Alle zeigen}
::msgcat::mcset de {Show Command} 
::msgcat::mcset de {Show Compass} 
::msgcat::mcset de {Show Grid} 
::msgcat::mcset de {Show Text} 
::msgcat::mcset de {Show/Hide Frames} {Rahmen zeigen/verstecken}
::msgcat::mcset de {Show} 
::msgcat::mcset de {Simple Cross} 
::msgcat::mcset de {Simple Plus} 
::msgcat::mcset de {Single Frame} {Einzelner rahmen}
::msgcat::mcset de {Single} {Einzeln}
::msgcat::mcset de {Sites} 
::msgcat::mcset de {Size/Radius} [encoding convertfrom iso8859-1 {Größe/Radius}]
::msgcat::mcset de {Size} [encoding convertfrom iso8859-1 {Größe}]
::msgcat::mcset de {Skip First} [encoding convertfrom iso8859-1 {Erste überspringen}] 
::msgcat::mcset de {Slice} 
::msgcat::mcset de {Smooth Parameters} [encoding convertfrom iso8859-1 {Glättungsparameter}]
::msgcat::mcset de {Smoothness} 
::msgcat::mcset de {Smooth} [encoding convertfrom iso8859-1 {Glätten}]
::msgcat::mcset de {Solid} 
::msgcat::mcset de {Sorry, DS9 does not support} [encoding convertfrom iso8859-1 {Sorry, DS9 unterstützt nicht}]
::msgcat::mcset de {Sorry, DS9 requires a Truecolor8, Truecolor16, Truecolor24 visual be available} 
::msgcat::mcset de {Sort} {Sortieren}
::msgcat::mcset de {Source TCL} 
::msgcat::mcset de {Source} {Quelle}
::msgcat::mcset de {Space Equal Distance} 
::msgcat::mcset de {Space Equal Value} 
::msgcat::mcset de {Spacing} {Intervall}
::msgcat::mcset de {Sqrt} 
::msgcat::mcset de {Square Root} {Wurzel}
::msgcat::mcset de {Squared} {Quadratisch}
::msgcat::mcset de {Square} 
::msgcat::mcset de {Stacked} 
::msgcat::mcset de {Starbase} 
::msgcat::mcset de {Startup} 
::msgcat::mcset de {Start} 
::msgcat::mcset de {Statistics} 
::msgcat::mcset de {Stats} 
::msgcat::mcset de {Status} 
::msgcat::mcset de {Step} {Stufe}
::msgcat::mcset de {Stop} 
::msgcat::mcset de {Story of SAOImageDS9} 
::msgcat::mcset de {Story} 
::msgcat::mcset de {Sum} {Summieren}
::msgcat::mcset de {Sunken} 
::msgcat::mcset de {Symbol Editor} 
::msgcat::mcset de {Symbol} 
::msgcat::mcset de {Tab-Separated-Value} 
::msgcat::mcset de {Table} 
::msgcat::mcset de {Tabloid} 
::msgcat::mcset de {Tag Color} 
::msgcat::mcset de {Task} 
::msgcat::mcset de {Template} 
::msgcat::mcset de {Text Font} 
::msgcat::mcset de {Text} 
::msgcat::mcset de {Then} {dann}
::msgcat::mcset de {Thickness} {Dicke}
::msgcat::mcset de {This analysis task is already running. Do you wish to kill it?} [encoding convertfrom iso8859-1 {Diese Analyse läuft bereits. Soll sie beendet werden?}]
::msgcat::mcset de {This function is not available.} 
::msgcat::mcset de {This function is not currently supported for this port.} 
::msgcat::mcset de {Tickmarks} {Achsenstriche}
::msgcat::mcset de {Tile Frames} {Gekachelte rahmen}
::msgcat::mcset de {Tile Parameters} 
::msgcat::mcset de {Tile} {Kacheln}
::msgcat::mcset de {Times} 
::msgcat::mcset de {Title} {Titel}
::msgcat::mcset de {Tophat} 
::msgcat::mcset de {Topographic} 
::msgcat::mcset de {Top} 
::msgcat::mcset de {To} {Nach}
::msgcat::mcset de {Transparency} 
::msgcat::mcset de {Triangle} 
::msgcat::mcset de {Type} {Typ}
::msgcat::mcset de {URL} 
::msgcat::mcset de {Unable to connect directly: using Web Proxy} 
::msgcat::mcset de {Unable to determine date of observation} 
::msgcat::mcset de {Unable to evaluate filter} [encoding convertfrom iso8859-1 {Nicht möglich Filter zu evaluieren}]
::msgcat::mcset de {Unable to find SIAP window} 
::msgcat::mcset de {Unable to find URL column} 
::msgcat::mcset de {Unable to find catalog window} [encoding convertfrom iso8859-1 {Nicht möglich Katalogfenster zu finden}]
::msgcat::mcset de {Unable to find plot window} [encoding convertfrom iso8859-1 {Nicht möglich Plotfenster zu finden}]
::msgcat::mcset de {Unable to load RGB image into a non-rgb frame} [encoding convertfrom iso8859-1 {Nicht möglich RGB-Bild in nicht-RGB-rahmen zu laden}]
::msgcat::mcset de {Unable to load region file} 
::msgcat::mcset de {Unable to load} [encoding convertfrom iso8859-1 {Nicht möglich zu laden}]
::msgcat::mcset de {Unable to locate URL} [encoding convertfrom iso8859-1 {Nicht möglich URL zu finden}]
::msgcat::mcset de {Unable to match target with XPA Mime request} 
::msgcat::mcset de {Unable to open file} [encoding convertfrom iso8859-1 {Nicht möglich Datei zu öffnen}]
::msgcat::mcset de {Unable to process Analysis file} 
::msgcat::mcset de {Unable to save RGB image from a non-rgb frame} 
::msgcat::mcset de {Undo} [encoding convertfrom iso8859-1 {Rückgängig}]
::msgcat::mcset de {Unique} 
::msgcat::mcset de {Unists} 
::msgcat::mcset de {Units} {Einheiten}
::msgcat::mcset de {Unknown Colormap} 
::msgcat::mcset de {Unknown command} 
::msgcat::mcset de {Update Filter} 
::msgcat::mcset de {Update Group} {Gruppe aktualisieren}
::msgcat::mcset de {Update from Current Crosshair} {Vom aktuellen Fadenkreuz aktualisieren}
::msgcat::mcset de {Update from Current Frame} {Vom aktuellen rahmen aktualisieren}
::msgcat::mcset de {Update} {Aktualisieren}
::msgcat::mcset de {Upper Left Back} 
::msgcat::mcset de {Upper Left Front} 
::msgcat::mcset de {Upper Right Back} 
::msgcat::mcset de {Upper Right Front} 
::msgcat::mcset de {Use Authentication} {Authentifizierung verwenden}
::msgcat::mcset de {Use Current Frame on Download} {Aktuellen rahmen bei Download verwenden}
::msgcat::mcset de {Use Internal Web Browser} {Internen Webbrowser verwenden}
::msgcat::mcset de {Use Original Color/Width} 
::msgcat::mcset de {Use Proxy} {Proxy verwenden}
::msgcat::mcset de {User Manual} 
::msgcat::mcset de {Username} {Login}
::msgcat::mcset de {User} {Benutzer}
::msgcat::mcset de {Use} {Benutze}
::msgcat::mcset de {VO Server} 
::msgcat::mcset de {VO} 
::msgcat::mcset de {Value} {Wert}
::msgcat::mcset de {Vector} {Vektor}
::msgcat::mcset de {Vertical Graph} {Vertikaldarstellung}
::msgcat::mcset de {Vertical Layout} {Vertikales layout}
::msgcat::mcset de {Vertical Text} {Vertikaler text}
::msgcat::mcset de {Vertical} 
::msgcat::mcset de {View} {Ansicht}
::msgcat::mcset de {Virtual Observatory} 
::msgcat::mcset de {WCS Parameters} 
::msgcat::mcset de {WCS} 
::msgcat::mcset de {Wavelength} [encoding convertfrom iso8859-1 {Wellenlänge}]
::msgcat::mcset de {Web Browser} {Webbrowser}
::msgcat::mcset de {White} [encoding convertfrom iso8859-1 {Weiß}]
::msgcat::mcset de {Width} {Breite}
::msgcat::mcset de {Window} 
::msgcat::mcset de {Words matching title, description} {Worte im Titel, Bezeichnung}
::msgcat::mcset de {X Axis Title} 
::msgcat::mcset de {X Grid} 
::msgcat::mcset de {XPA Information} 
::msgcat::mcset de {XPA not initialized} {XPA nicht initialisiert}
::msgcat::mcset de {XPA} 
::msgcat::mcset de {X} 
::msgcat::mcset de {Y Axis Title} 
::msgcat::mcset de {Y Grid} 
::msgcat::mcset de {Yellow} {Gelb}
::msgcat::mcset de {Y} 
::msgcat::mcset de {Z Axis Scale} 
::msgcat::mcset de {ZScale Parameters} 
::msgcat::mcset de {Zero} 
::msgcat::mcset de {Zoom Fit} 
::msgcat::mcset de {Zoom In} {Hineinzoomen}
::msgcat::mcset de {Zoom Out} {Herauszoomen}
::msgcat::mcset de {Zoom} 
::msgcat::mcset de {already connected} 
::msgcat::mcset de {and} 
::msgcat::mcset de {blue} 
::msgcat::mcset de {b} 
::msgcat::mcset de {color} 
::msgcat::mcset de {cool} 
::msgcat::mcset de {green} 
::msgcat::mcset de {grey} 
::msgcat::mcset de {g} 
::msgcat::mcset de {h5utils} 
::msgcat::mcset de {heat} 
::msgcat::mcset de {internal error} 
::msgcat::mcset de {not connected} 
::msgcat::mcset de {not} 
::msgcat::mcset de {only} 
::msgcat::mcset de {or center of data} {oder Zentrum der Daten}
::msgcat::mcset de {rainbow} 
::msgcat::mcset de {red} 
::msgcat::mcset de {rows of data have been downloaded. More may be available. You may wish to adjust the maximum allowed} [encoding convertfrom iso8859-1 {Datenreihen wurden heruntergeladen. Mehr sind vielleicht verfügbar. Sie können die maximale Anzahl anpassen.}]
::msgcat::mcset de {r} 
::msgcat::mcset de {staircase} 
::msgcat::mcset de {standard} 
::msgcat::mcset de {unable to locate HUB} 
::msgcat::mcset de {x} 
::msgcat::mcset de {} 
