::msgcat::mcset es {2D} 
::msgcat::mcset es {3D View} 
::msgcat::mcset es {3D} 
::msgcat::mcset es {A postscript generation error has occurred} [encoding convertfrom iso8859-1 {Un error ha ocurrido en la generación del fichero postscript}]
::msgcat::mcset es {AIP} 
::msgcat::mcset es {Abort} 
::msgcat::mcset es {About SAOImageDS9} 
::msgcat::mcset es {About} {Acerca de}
::msgcat::mcset es {Acknowledgment} {Reconocimientos}
::msgcat::mcset es {Add Bar Graph} 
::msgcat::mcset es {Add Graph} 
::msgcat::mcset es {Add Line Graph} 
::msgcat::mcset es {Add} {Agregar}
::msgcat::mcset es {Advanced} {Avanzado}
::msgcat::mcset es {Align} {Alinear}
::msgcat::mcset es {All Columns} {Todas las columnas}
::msgcat::mcset es {All Rows} {Todas las filas}
::msgcat::mcset es {All} {Todas}
::msgcat::mcset es {Always save files during Backup} 
::msgcat::mcset es {Amplifier} {Amplificador}
::msgcat::mcset es {An error has occurred during backup} 
::msgcat::mcset es {An error has occurred during restore} 
::msgcat::mcset es {An error has occurred invoking the Analysis task} [encoding convertfrom iso8859-1 {Un error ha ocurrido mientras se invocaba la tarea de análisis}]
::msgcat::mcset es {An error has occurred while creating} 
::msgcat::mcset es {An error has occurred while loading} 
::msgcat::mcset es {An error has occurred while printing} {Un error ha ocurrido al imprimir}
::msgcat::mcset es {An error has occurred while saving} {Un error ha ocurrido al guardar}
::msgcat::mcset es {An internal error has been detected} 
::msgcat::mcset es {Analysis Command Log} [encoding convertfrom iso8859-1 {Log de instrucciones de análisis}]
::msgcat::mcset es {Analysis Commands} [encoding convertfrom iso8859-1 {Comandos de análisis}]
::msgcat::mcset es {Analysis File} 
::msgcat::mcset es {Analysis Log} 
::msgcat::mcset es {Analysis} [encoding convertfrom iso8859-1 {Análisis}]
::msgcat::mcset es {Angle Complement} [encoding convertfrom iso8859-1 {Ángulo complementario}]
::msgcat::mcset es {Angles} [encoding convertfrom iso8859-1 {Ángulos}]
::msgcat::mcset es {Angle} [encoding convertfrom iso8859-1 {Ángulo}]
::msgcat::mcset es {Annuli} [encoding convertfrom iso8859-1 {Ánulos}]
::msgcat::mcset es {Annulus} {Corona}
::msgcat::mcset es {Apply} {Aplicar}
::msgcat::mcset es {ArcMin} {MinArc}
::msgcat::mcset es {ArcSec} {SegArc}
::msgcat::mcset es {Architecture} {Arquitectura}
::msgcat::mcset es {Archives} 
::msgcat::mcset es {Array} 
::msgcat::mcset es {Arrow} {Flecha}
::msgcat::mcset es {Asteroids} 
::msgcat::mcset es {Astronomy} 
::msgcat::mcset es {At Startup} 
::msgcat::mcset es {At least 2 different catalogs are required} 
::msgcat::mcset es {Auto Centroid} {Auto Centroide}
::msgcat::mcset es {Auto Plot 2D} 
::msgcat::mcset es {Auto Plot 3D} 
::msgcat::mcset es {Auto Plot Statistics} 
::msgcat::mcset es {Auto Plot} 
::msgcat::mcset es {Autoload FITS Regions} {Autocargar regiones FITS}
::msgcat::mcset es {Autoload} 
::msgcat::mcset es {Automatic} [encoding convertfrom iso8859-1 {Automático}]
::msgcat::mcset es {Average} {Promedio}
::msgcat::mcset es {Axes Number} 
::msgcat::mcset es {Axes Order} 
::msgcat::mcset es {Axes Range} 
::msgcat::mcset es {Axes Title} 
::msgcat::mcset es {Axes} {Ejes}
::msgcat::mcset es {Axis Length} {Longitud del eje}
::msgcat::mcset es {Axis Numbers} [encoding convertfrom iso8859-1 {Números de los ejes}]
::msgcat::mcset es {Axis Title} 
::msgcat::mcset es {Axis} {Eje}
::msgcat::mcset es {Azimuth} 
::msgcat::mcset es {Background Color} {Color de fondo}
::msgcat::mcset es {Background} {Fondo}
::msgcat::mcset es {Backup} 
::msgcat::mcset es {Back} [encoding convertfrom iso8859-1 {Para atrás}]  
::msgcat::mcset es {Bar Dataset} 
::msgcat::mcset es {Bar Plot Tool} 
::msgcat::mcset es {Bar Width} 
::msgcat::mcset es {Bar} 
::msgcat::mcset es {Behavior} 
::msgcat::mcset es {Bias} 
::msgcat::mcset es {Bin 3rd Column} {Bin tercera columna} 
::msgcat::mcset es {Bin Center} {Centro del bin}
::msgcat::mcset es {Bin Columns} {Columnas del bin}
::msgcat::mcset es {Bin Filter} {Filtro del bin} 
::msgcat::mcset es {Bin Fit} 
::msgcat::mcset es {Bin In} 
::msgcat::mcset es {Bin Out} 
::msgcat::mcset es {Binning Parameters} [encoding convertfrom iso8859-1 {Parámetros de resolución}]
::msgcat::mcset es {Bins} 
::msgcat::mcset es {Bin} 
::msgcat::mcset es {Black} {Negro}
::msgcat::mcset es {Blank/Inf/NaN Color} {Color en blanco/Inf/NaN}
::msgcat::mcset es {Blend} 
::msgcat::mcset es {Blink Frames} {Parpadear Marcos}
::msgcat::mcset es {Blink Interval} {Intervalo de parpadeo}
::msgcat::mcset es {Blink} {Parpadear}
::msgcat::mcset es {Block Fit} 
::msgcat::mcset es {Block In} {Bin a} 
::msgcat::mcset es {Block Out} {Bin de}
::msgcat::mcset es {Block Parameters} 
::msgcat::mcset es {Block Pixel} 
::msgcat::mcset es {Block} {Bin}
::msgcat::mcset es {Blue} {Azul}
::msgcat::mcset es {Bold} {Negrilla}
::msgcat::mcset es {Border Color} 
::msgcat::mcset es {Border Width} 
::msgcat::mcset es {Border} {Borde}
::msgcat::mcset es {Bottom} 
::msgcat::mcset es {Box Annulus} {Caja con caja inscrita}
::msgcat::mcset es {Box Panda} {Caja con caja inscrita segmetada}
::msgcat::mcset es {BoxCircle} 
::msgcat::mcset es {Boxcar} 
::msgcat::mcset es {Box} {Casilla}
::msgcat::mcset es {Broadcast} 
::msgcat::mcset es {Browser} 
::msgcat::mcset es {Browse} 
::msgcat::mcset es {Buffer} 
::msgcat::mcset es {Buttonbar} 
::msgcat::mcset es {Buttons} {Teclas} 
::msgcat::mcset es {Bytes} 
::msgcat::mcset es {CMYK} 
::msgcat::mcset es {Can Delete} {Puede suprimir}
::msgcat::mcset es {Can Edit} {Puede editar}
::msgcat::mcset es {Can Move} {Puede mover}
::msgcat::mcset es {Can Rotate} {Puede rotar}
::msgcat::mcset es {Cancelled} 
::msgcat::mcset es {Cancel} {Cancelar}
::msgcat::mcset es {Cap} 
::msgcat::mcset es {Catalog Server} [encoding convertfrom iso8859-1 {Servidor de catálogo}]
::msgcat::mcset es {Catalog Tool} [encoding convertfrom iso8859-1 {Herramienta de catálogo}]
::msgcat::mcset es {Catalogs} [encoding convertfrom iso8859-1 {Catálogos}]
::msgcat::mcset es {Catalog} [encoding convertfrom iso8859-1 {Catálogo}]
::msgcat::mcset es {Catrom} 
::msgcat::mcset es {Cat} 
::msgcat::mcset es {Center Dialogs} 
::msgcat::mcset es {Center Image} {Centrar imagen}
::msgcat::mcset es {Center} {Centrar}
::msgcat::mcset es {Centroid Parameters} [encoding convertfrom iso8859-1 {Párametros del centroide}]
::msgcat::mcset es {Centroid} {Centroide}
::msgcat::mcset es {Circle} [encoding convertfrom iso8859-1 {Círculo}]
::msgcat::mcset es {Clear All} {Despejar todos}
::msgcat::mcset es {Clear Analysis Commands} {Borrar las instrucciones de análisis}
::msgcat::mcset es {Clear Cache} {Limpiar cache}
::msgcat::mcset es {Clear External Analysis Commands?}  [encoding convertfrom iso8859-1 {¿Borrar las instrucciones externas de análisis?}]
::msgcat::mcset es {Clear Filter} {Borrar filtro} 
::msgcat::mcset es {Clear Frame} {Despejar marco}
::msgcat::mcset es {Clear Preferences?} [encoding convertfrom iso8859-1 {¿Limpiar las preferencias?}]
::msgcat::mcset es {Clear Preferences} {Limpiar las preferencias}
::msgcat::mcset es {Clear} {Vaciar}
::msgcat::mcset es {Click to Center} {Clic para centrar}
::msgcat::mcset es {Close} {Cerrar}
::msgcat::mcset es {Colorbar Size} 
::msgcat::mcset es {Colorbar} {Barra de colores}
::msgcat::mcset es {Colormap Parameters} [encoding convertfrom iso8859-1 {Parámetros del mapa de colores}]
::msgcat::mcset es {Colormap} {Mapa de colores}
::msgcat::mcset es {Color} 
::msgcat::mcset es {Columns} {Columnas}
::msgcat::mcset es {Column} {Columna}
::msgcat::mcset es {Comets} 
::msgcat::mcset es {Command not allowed} 
::msgcat::mcset es {Command} 
::msgcat::mcset es {Compass} [encoding convertfrom iso8859-1 {Compás}]
::msgcat::mcset es {Composite Region} 
::msgcat::mcset es {Composite} {Compuesto}
::msgcat::mcset es {Compression} [encoding convertfrom iso8859-1 {Compresión}]
::msgcat::mcset es {Configure} {Configurar}
::msgcat::mcset es {Connect SAMP} 
::msgcat::mcset es {Connect} 
::msgcat::mcset es {Console} 
::msgcat::mcset es {Contacting Server} 
::msgcat::mcset es {Contour Parameters} [encoding convertfrom iso8859-1 {Parámetros de contorno}]
::msgcat::mcset es {Contour Paste} 
::msgcat::mcset es {Contour Save} 
::msgcat::mcset es {Contours} {Contornos}
::msgcat::mcset es {Contour} 
::msgcat::mcset es {Contrast} {Contraste}
::msgcat::mcset es {Control Panel} 
::msgcat::mcset es {Convert to Polygons} [encoding convertfrom iso8859-1 {Convertir a polígonos}]
::msgcat::mcset es {Coordinate Grid Parameters} [encoding convertfrom iso8859-1 {Parámetros de la cuadrícula de coordenadas}]
::msgcat::mcset es {Coordinate Grid} [encoding convertfrom iso8859-1 {Cuadrícula de coordenadas}]
::msgcat::mcset es {Coordinate System} {Sistema de coordenadas} 
::msgcat::mcset es {Coordinates} {Coordenadas}
::msgcat::mcset es {Coordinate} {Coordenada}
::msgcat::mcset es {Copy Contours} {Copiar contornos}
::msgcat::mcset es {Copy to Regions} {Copiar a regiones}
::msgcat::mcset es {Copy} {Copiar}
::msgcat::mcset es {Create Movie} 
::msgcat::mcset es {Create New Frame on Download} {Crear un nuevo marco al transferir}
::msgcat::mcset es {Create} 
::msgcat::mcset es {Crop Parameters} 
::msgcat::mcset es {Crop} 
::msgcat::mcset es {Crosshair Parameters} 
::msgcat::mcset es {Crosshair To} {Localizar con punto de mira} 
::msgcat::mcset es {Crosshair} {Punto de mira}
::msgcat::mcset es {Cross} {Cruz}
::msgcat::mcset es {Cubehelix} 
::msgcat::mcset es {Cube} 
::msgcat::mcset es {Cubic} 
::msgcat::mcset es {Current Frame} {Marco actual}
::msgcat::mcset es {Current Range} {Rango actual}
::msgcat::mcset es {Current} {Actual}
::msgcat::mcset es {Cursor} 
::msgcat::mcset es {Cut} {Corte}
::msgcat::mcset es {Cyan} {Cian}
::msgcat::mcset es {DMS} 
::msgcat::mcset es {DPI} 
::msgcat::mcset es {DS9 has detected a newer version of a backup file and therefore will not process this file.} 
::msgcat::mcset es {DS9 has detected a newer version of a preferences file.} 
::msgcat::mcset es {DS9 has detected an older backup file, do you wish to continue?} 
::msgcat::mcset es {DS9 has detected an older preferences file, do you wish to update?} [encoding convertfrom iso8859-1 {DS9 ha detectado un fichero de preferencias más antiguo, ¿Desea actualizarlo?}]
::msgcat::mcset es {DS9 will complete the initialization process} [encoding convertfrom iso8859-1 {DS9 completará el proceso de inicialización}]
::msgcat::mcset es {Darken} 
::msgcat::mcset es {Dash} [encoding convertfrom iso8859-1 {Guión}]
::msgcat::mcset es {Data Format} {Formato de los datos}
::msgcat::mcset es {Data must be ascii numeric values} 
::msgcat::mcset es {Dataset Name} 
::msgcat::mcset es {Dataset} {Conjunto de datos}
::msgcat::mcset es {Data} 
::msgcat::mcset es {Decrease} [encoding convertfrom iso8859-1 {Disminución}]
::msgcat::mcset es {Default All Files} 
::msgcat::mcset es {Default Format} 
::msgcat::mcset es {Default Length} 
::msgcat::mcset es {Default} {Por defecto}
::msgcat::mcset es {Degrees} {Grados}
::msgcat::mcset es {Delay} 
::msgcat::mcset es {Delete All Frames?} [encoding convertfrom iso8859-1 {¿Borrar todos los marcos?}]
::msgcat::mcset es {Delete All Frames} {Borrar todos los marcos}
::msgcat::mcset es {Delete All Groups?} [encoding convertfrom iso8859-1 {¿Borrar todos los grupos?}]
::msgcat::mcset es {Delete All Groups} {Borrar todos los grupos}
::msgcat::mcset es {Delete All} 
::msgcat::mcset es {Delete Color Tags} 
::msgcat::mcset es {Delete Dataset} 
::msgcat::mcset es {Delete Frame} {Borrar marco}
::msgcat::mcset es {Delete Graph} 
::msgcat::mcset es {Delete Group} {Borrar grupo}
::msgcat::mcset es {Delete Load} 
::msgcat::mcset es {Delete Regions?} 
::msgcat::mcset es {Delete Regions} 
::msgcat::mcset es {Delete Selected Regions} {Borrar regiones seleccionadas}
::msgcat::mcset es {Delete Select} 
::msgcat::mcset es {Delete and Open Regions} 
::msgcat::mcset es {Delete} {Borrar}
::msgcat::mcset es {Depth} {Profundidad}
::msgcat::mcset es {Detector} 
::msgcat::mcset es {Dialog Box} [encoding convertfrom iso8859-1 {Caja de diálogo}]
::msgcat::mcset es {Diameter} 
::msgcat::mcset es {Diamond} {Diamante}
::msgcat::mcset es {Dimensions} 
::msgcat::mcset es {Dimension} [encoding convertfrom iso8859-1 {Dimensión}]
::msgcat::mcset es {Direction} 
::msgcat::mcset es {Disconnect} 
::msgcat::mcset es {Display Size} [encoding convertfrom iso8859-1 {Mostrar el tamaño}]
::msgcat::mcset es {Dissolve} {Disolver}
::msgcat::mcset es {Distance} 
::msgcat::mcset es {Done} 
::msgcat::mcset es {Download Colormap} 
::msgcat::mcset es {Drag to Center} {Arrastrar para centrar} 
::msgcat::mcset es {Duplicate Dataset} 
::msgcat::mcset es {ENVI} 
::msgcat::mcset es {EPS} 
::msgcat::mcset es {East} {Este}
::msgcat::mcset es {Ecliptic} [encoding convertfrom iso8859-1 {Eclíptica}]
::msgcat::mcset es {Edit Group Name} {Editar el nombre del grupo}
::msgcat::mcset es {Edit} {Editar}
::msgcat::mcset es {Elevation}  [encoding convertfrom iso8859-1 {Elevación}]
::msgcat::mcset es {Ellipse Panda} {Elipse con elipse inscrita segmentada}
::msgcat::mcset es {Ellipse} {Elipse} 
::msgcat::mcset es {Elliptical Annulus} {Elipse con elipse inscrita}
::msgcat::mcset es {Elliptical Gaussian} 
::msgcat::mcset es {Elliptical Panda} [encoding convertfrom iso8859-1 {Elipse con elipse inscrita segmentada}]            
::msgcat::mcset es {Enable Confirmation Dialogs} [encoding convertfrom iso8859-1 {Habilitar los diálogos de confirmación}]
::msgcat::mcset es {Enable} 
::msgcat::mcset es {End} 
::msgcat::mcset es {Enter Color} {Entrar color} 
::msgcat::mcset es {Enter Font Size} 
::msgcat::mcset es {Enter Group Name} {Entrar nombre de grupo}
::msgcat::mcset es {Enter Search Expression} [encoding convertfrom iso8859-1 {Entrar expresión de búsqueda}]
::msgcat::mcset es {Enter URL} 
::msgcat::mcset es {Entry} {Entrada}
::msgcat::mcset es {Equal Area} {Misma área}
::msgcat::mcset es {Equal Distance} {Misma distancia}
::msgcat::mcset es {Equal Spacing} 
::msgcat::mcset es {Equal Value} 
::msgcat::mcset es {Error code was returned} [encoding convertfrom iso8859-1 {Error de código fue regresado}]
::msgcat::mcset es {Errorbar} 
::msgcat::mcset es {Error} 
::msgcat::mcset es {Examine Frame} {Examinar marco}
::msgcat::mcset es {Examine} {Examinar}
::msgcat::mcset es {Exam} 
::msgcat::mcset es {Exclude} {Excluir}
::msgcat::mcset es {Exit} {Salir}
::msgcat::mcset es {Export Array} 
::msgcat::mcset es {Export ENVI} 
::msgcat::mcset es {Export GIF} 
::msgcat::mcset es {Export JPEG} 
::msgcat::mcset es {Export NRRD} 
::msgcat::mcset es {Export PNG} 
::msgcat::mcset es {Export RGB Array} 
::msgcat::mcset es {Export TIFF} 
::msgcat::mcset es {Export} 
::msgcat::mcset es {Extension Data} 
::msgcat::mcset es {Extension not found} 
::msgcat::mcset es {Extensions} 
::msgcat::mcset es {Extension} 
::msgcat::mcset es {Exterior Axes} {Ejes exteriores}
::msgcat::mcset es {Exterior Numerics} {Numeración exterior}
::msgcat::mcset es {FAQ} 
::msgcat::mcset es {FITS} 
::msgcat::mcset es {FK4} 
::msgcat::mcset es {FK5} 
::msgcat::mcset es {FP} 
::msgcat::mcset es {Factor} 
::msgcat::mcset es {File not Found or Unable to load FITS data MIME type} {Fichero no hallado o incapaz de cargar datos FITS de tipo MIME}
::msgcat::mcset es {File not found} 
::msgcat::mcset es {Filename} {Nombre del fichero}
::msgcat::mcset es {File} {Fichero}
::msgcat::mcset es {Fill} 
::msgcat::mcset es {Filter} {Filtro}
::msgcat::mcset es {Find Next} {Hallar la siguiente}
::msgcat::mcset es {Find} {Hallar}
::msgcat::mcset es {First Block} 
::msgcat::mcset es {First Frame} {Primer Marco}
::msgcat::mcset es {First} {Primer}
::msgcat::mcset es {Fits} 
::msgcat::mcset es {Fixed in Size} [encoding convertfrom iso8859-1 {Fijado en tamaño}]
::msgcat::mcset es {Flip} 
::msgcat::mcset es {Font} {Fuente}
::msgcat::mcset es {Footprint Servers} 
::msgcat::mcset es {Footprint} 
::msgcat::mcset es {For more information, use --help} 
::msgcat::mcset es {Foreground} 
::msgcat::mcset es {Forground} 
::msgcat::mcset es {Format} {Formato}
::msgcat::mcset es {Forward} {Hacia adelante}
::msgcat::mcset es {Found} {Hallado}
::msgcat::mcset es {Frame Information} [encoding convertfrom iso8859-1 {Información del marco}]
::msgcat::mcset es {Frame Parameters} 
::msgcat::mcset es {Frames} 
::msgcat::mcset es {Frame} {Marco}
::msgcat::mcset es {From} 
::msgcat::mcset es {Front} {Al frente}
::msgcat::mcset es {Full Range} {Rango completo}
::msgcat::mcset es {Function} [encoding convertfrom iso8859-1 {Función}]
::msgcat::mcset es {GIF} 
::msgcat::mcset es {GUI} 
::msgcat::mcset es {Galactic} [encoding convertfrom iso8859-1 {Galáctico}]
::msgcat::mcset es {Gap} 
::msgcat::mcset es {Gaussian} {Gausiana}
::msgcat::mcset es {General} 
::msgcat::mcset es {Generate} {Generar}
::msgcat::mcset es {Generating Regions} {Generando regiones}
::msgcat::mcset es {Get Information} [encoding convertfrom iso8859-1 {Obtener información}]
::msgcat::mcset es {Gist} 
::msgcat::mcset es {Global Properties} 
::msgcat::mcset es {Global} 
::msgcat::mcset es {Goto Frame} 
::msgcat::mcset es {Goto Row} 
::msgcat::mcset es {Goto} 
::msgcat::mcset es {Graph Horz} 
::msgcat::mcset es {Graph Parameters} 
::msgcat::mcset es {Graph Vert} 
::msgcat::mcset es {Graphics} [encoding convertfrom iso8859-1 {Gráficos}]
::msgcat::mcset es {Graphs} 
::msgcat::mcset es {Graph} [encoding convertfrom iso8859-1 {Gráfica}]
::msgcat::mcset es {Grayscale} {Escala de grises}
::msgcat::mcset es {Green} {Verde}
::msgcat::mcset es {Grid Gap} [encoding convertfrom iso8859-1 {Espaciado de la cuadrícula}]
::msgcat::mcset es {Grid} [encoding convertfrom iso8859-1 {Cuadrícula}]
::msgcat::mcset es {Groups} {Grupos}
::msgcat::mcset es {HMS} 
::msgcat::mcset es {HTTP} 
::msgcat::mcset es {Header} {Cabecera}
::msgcat::mcset es {Height} {Altura}
::msgcat::mcset es {Help Desk} {Mesa de ayuda} 
::msgcat::mcset es {Help Me Choose} {Ayudame a escoger}
::msgcat::mcset es {Help} {Ayuda}
::msgcat::mcset es {Hide All} {Ocultar todos}
::msgcat::mcset es {Highlite} 
::msgcat::mcset es {High} {Alto}
::msgcat::mcset es {Histogram Equalization} [encoding convertfrom iso8859-1 {Ecualización de histograma}] 
::msgcat::mcset es {Histogram} {Histograma}
::msgcat::mcset es {Horizontal Graph} [encoding convertfrom iso8859-1 {Gráfica horizontal}]
::msgcat::mcset es {Horizontal Layout} [encoding convertfrom iso8859-1 {Distribución horizontal}]
::msgcat::mcset es {Horizontal} 
::msgcat::mcset es {IAU Location Code} 
::msgcat::mcset es {ICRS} 
::msgcat::mcset es {Identification} {Identificación}
::msgcat::mcset es {If} {Si}
::msgcat::mcset es {Image Servers} 
::msgcat::mcset es {Image} {Imagen}
::msgcat::mcset es {Import Array} 
::msgcat::mcset es {Import ENVI} 
::msgcat::mcset es {Import GIF} 
::msgcat::mcset es {Import JPEG} 
::msgcat::mcset es {Import NRRD} 
::msgcat::mcset es {Import PNG} 
::msgcat::mcset es {Import RGB Array} 
::msgcat::mcset es {Import Slice GIF} 
::msgcat::mcset es {Import Slice JPEG} 
::msgcat::mcset es {Import Slice PNG} 
::msgcat::mcset es {Import Slice TIFF} 
::msgcat::mcset es {Import TIFF} 
::msgcat::mcset es {Import} 
::msgcat::mcset es {Include} {Incluir}
::msgcat::mcset es {Increase} {Aumento}
::msgcat::mcset es {Information Panel} [encoding convertfrom iso8859-1 {Panel de información}]
::msgcat::mcset es {Information} [encoding convertfrom iso8859-1 {Información}] 
::msgcat::mcset es {Initialize XPA} {Inicializar XPA}
::msgcat::mcset es {Inner} {Interior}
::msgcat::mcset es {Instrument FOV} {Campo visual del instrumento}
::msgcat::mcset es {Instrument} 
::msgcat::mcset es {Interior Axes} {Ejes interiores}
::msgcat::mcset es {Interior Numerics} [encoding convertfrom iso8859-1 {Numeración interior}]
::msgcat::mcset es {Internal Parse Error} 
::msgcat::mcset es {Interval} {Intervalo}
::msgcat::mcset es {Invalid Column Name} 
::msgcat::mcset es {Invalid WCS} 
::msgcat::mcset es {Invalid formated multipart/mixed mime type message} 
::msgcat::mcset es {Invert Colormap} {Invertir mapa de colores}
::msgcat::mcset es {Invert Selection} [encoding convertfrom iso8859-1 {Invertir selección}]
::msgcat::mcset es {Invert} {Invertir}
::msgcat::mcset es {Italic} [encoding convertfrom iso8859-1 {Itálica}]
::msgcat::mcset es {Items Found} [encoding convertfrom iso8859-1 {Artículos hallados}]
::msgcat::mcset es {Iteration} [encoding convertfrom iso8859-1 {Iteración}]
::msgcat::mcset es {JPEG Quality Factor} {Factor de calidad JPEG}
::msgcat::mcset es {JPEG} 
::msgcat::mcset es {Keep-Alive} 
::msgcat::mcset es {Keyword} 
::msgcat::mcset es {Labels} {Etiquetas} 
::msgcat::mcset es {Label} {Etiqueta}
::msgcat::mcset es {Landscape} {Apaisado}
::msgcat::mcset es {Language} {Idioma}
::msgcat::mcset es {Last Block} 
::msgcat::mcset es {Last Frame} [encoding convertfrom iso8859-1 {Último marco}]
::msgcat::mcset es {Last} [encoding convertfrom iso8859-1 {Último}]
::msgcat::mcset es {Layout Horz} 
::msgcat::mcset es {Layout Vert} 
::msgcat::mcset es {Layout} 
::msgcat::mcset es {Left} 
::msgcat::mcset es {Legal} 
::msgcat::mcset es {Legend Position} 
::msgcat::mcset es {Legend Title} 
::msgcat::mcset es {Legend} 
::msgcat::mcset es {Length} {Longitud}
::msgcat::mcset es {Letter} 
::msgcat::mcset es {Levels} {Niveles}
::msgcat::mcset es {Level} {Nivel}
::msgcat::mcset es {Lighten} 
::msgcat::mcset es {Limits} [encoding convertfrom iso8859-1 {Límites}]
::msgcat::mcset es {Line Dataset} 
::msgcat::mcset es {Line Plot Tool} 
::msgcat::mcset es {Linear} {Lineal}
::msgcat::mcset es {Line} [encoding convertfrom iso8859-1 {Línea}]
::msgcat::mcset es {List Data} 
::msgcat::mcset es {List Regions} {Listar regiones}
::msgcat::mcset es {List Selected Regions} 
::msgcat::mcset es {List Select} 
::msgcat::mcset es {List} {Listar}
::msgcat::mcset es {Load Analysis Commands} [encoding convertfrom iso8859-1 {Cargar las instrucciones de análisis}]
::msgcat::mcset es {Load Color Tags} 
::msgcat::mcset es {Load Contour Levels} {Cargar niveles de contorno}
::msgcat::mcset es {Load Contrast/Bias} {Cargar contraste/Bias}
::msgcat::mcset es {Load Data} {Cargar datos}
::msgcat::mcset es {Load Mosaic} {Cargar mosaico}
::msgcat::mcset es {Load Template} {Cargar modelo}
::msgcat::mcset es {Load into All} 
::msgcat::mcset es {Load into Current} 
::msgcat::mcset es {Loading Catalog} 
::msgcat::mcset es {Loading} 
::msgcat::mcset es {Load} {Cargar}
::msgcat::mcset es {Local} 
::msgcat::mcset es {Lock Axes} 
::msgcat::mcset es {Lock Bin} 
::msgcat::mcset es {Lock Color} 
::msgcat::mcset es {Lock Crop Amplifier} 
::msgcat::mcset es {Lock Crop Detector} 
::msgcat::mcset es {Lock Crop Image} 
::msgcat::mcset es {Lock Crop None} 
::msgcat::mcset es {Lock Crop Physical} 
::msgcat::mcset es {Lock Crop WCS} 
::msgcat::mcset es {Lock Crosshair Amplifier} 
::msgcat::mcset es {Lock Crosshair Detector} 
::msgcat::mcset es {Lock Crosshair Image} 
::msgcat::mcset es {Lock Crosshair None} 
::msgcat::mcset es {Lock Crosshair Physical} 
::msgcat::mcset es {Lock Crosshair WCS} 
::msgcat::mcset es {Lock Frame Amplifier} 
::msgcat::mcset es {Lock Frame Detector} 
::msgcat::mcset es {Lock Frame Image} 
::msgcat::mcset es {Lock Frame None} 
::msgcat::mcset es {Lock Frame Physical} 
::msgcat::mcset es {Lock Frame WCS} 
::msgcat::mcset es {Lock Limits} 
::msgcat::mcset es {Lock Scale} 
::msgcat::mcset es {Lock Slice Image} 
::msgcat::mcset es {Lock Slice None} 
::msgcat::mcset es {Lock Slice WCS} 
::msgcat::mcset es {Lock Smooth} 
::msgcat::mcset es {Lock} {Bloquear}
::msgcat::mcset es {Log Exponent} 
::msgcat::mcset es {Log} 
::msgcat::mcset es {Low High} {Bajo Alto} 
::msgcat::mcset es {Lower Left Back} 
::msgcat::mcset es {Lower Left Front} 
::msgcat::mcset es {Lower Right Back} 
::msgcat::mcset es {Lower Right Front} 
::msgcat::mcset es {Low} {Bajo}
::msgcat::mcset es {MIP} 
::msgcat::mcset es {Magenta} 
::msgcat::mcset es {Magnification} 
::msgcat::mcset es {Magnifier} {Ventanilla magnificadora} 
::msgcat::mcset es {Major Radius} 
::msgcat::mcset es {Major Sigma} 
::msgcat::mcset es {Major} {Mayor}
::msgcat::mcset es {Manual} 
::msgcat::mcset es {Mask Parameters} [encoding convertfrom iso8859-1 {Parámetros de mascara}]
::msgcat::mcset es {Match Axes} 
::msgcat::mcset es {Match Bin} 
::msgcat::mcset es {Match Catalog requires at least 1 row per catalog} 
::msgcat::mcset es {Match Color} 
::msgcat::mcset es {Match Crop Amplifier} 
::msgcat::mcset es {Match Crop Detector} 
::msgcat::mcset es {Match Crop Image} 
::msgcat::mcset es {Match Crop Physical} 
::msgcat::mcset es {Match Crop WCS} 
::msgcat::mcset es {Match Crosshair Amplifier} 
::msgcat::mcset es {Match Crosshair Detector} 
::msgcat::mcset es {Match Crosshair Image} 
::msgcat::mcset es {Match Crosshair Physical} 
::msgcat::mcset es {Match Crosshair WCS} 
::msgcat::mcset es {Match Frame Amplifier} 
::msgcat::mcset es {Match Frame Detector} 
::msgcat::mcset es {Match Frame Image} 
::msgcat::mcset es {Match Frame Physical} 
::msgcat::mcset es {Match Frame WCS} 
::msgcat::mcset es {Match Limits} 
::msgcat::mcset es {Match Scale} 
::msgcat::mcset es {Match Slice Image} 
::msgcat::mcset es {Match Slice WCS} 
::msgcat::mcset es {Match Smooth} 
::msgcat::mcset es {Match} 
::msgcat::mcset es {Math Function} [encoding convertfrom iso8859-1 {Función matemática}]
::msgcat::mcset es {Matplotlib} 
::msgcat::mcset es {Max Rows} [encoding convertfrom iso8859-1 {Máx filas}] 
::msgcat::mcset es {Maximum} 
::msgcat::mcset es {Max} [encoding convertfrom iso8859-1 {Máx}]
::msgcat::mcset es {Menus and Buttons} 
::msgcat::mcset es {Menu} 
::msgcat::mcset es {Message Log} 
::msgcat::mcset es {Method} [encoding convertfrom iso8859-1 {Método}]
::msgcat::mcset es {Min Max Parameters} 
::msgcat::mcset es {Min Max} [encoding convertfrom iso8859-1 {Mín Máx}]
::msgcat::mcset es {Minimum} 
::msgcat::mcset es {Minor Radius} 
::msgcat::mcset es {Minor Sigma} 
::msgcat::mcset es {Minor} {Menor}
::msgcat::mcset es {Minutes} 
::msgcat::mcset es {Min} [encoding convertfrom iso8859-1 {Mín}]
::msgcat::mcset es {Mission} [encoding convertfrom iso8859-1 {Misión}]
::msgcat::mcset es {Mode} 
::msgcat::mcset es {Mosaic IRAF Segment} 
::msgcat::mcset es {Mosaic IRAF} 
::msgcat::mcset es {Mosaic WCS Segment} 
::msgcat::mcset es {Mosaic WCS} 
::msgcat::mcset es {Mosaic WFPC2} 
::msgcat::mcset es {Mosaic} 
::msgcat::mcset es {Mouse Click Epsilon} 
::msgcat::mcset es {Mouse Wheel Bin} 
::msgcat::mcset es {Mouse Wheel Zoom} 
::msgcat::mcset es {Move Back} [encoding convertfrom iso8859-1 {Mover atrás}]
::msgcat::mcset es {Move First} {Mover al primero}
::msgcat::mcset es {Move Forward} {Mover adelante} 
::msgcat::mcset es {Move Frame} 
::msgcat::mcset es {Move Last} [encoding convertfrom iso8859-1 {Mover al Último}]  
::msgcat::mcset es {Move to Back} [encoding convertfrom iso8859-1 {Poner detrás}]
::msgcat::mcset es {Move to Front} {Poner delante}
::msgcat::mcset es {Movie} 
::msgcat::mcset es {Muliple Extension Cube} 
::msgcat::mcset es {Muliple Extension Frames} 
::msgcat::mcset es {Multiple Extension Cube} 
::msgcat::mcset es {Multiple Extension Frames} 
::msgcat::mcset es {Multiple WCS} [encoding convertfrom iso8859-1 {Múltiple WCS}]
::msgcat::mcset es {NAN} 
::msgcat::mcset es {NRRD} 
::msgcat::mcset es {Name Resolution} [encoding convertfrom iso8859-1 {Conversión a coordenadas}]
::msgcat::mcset es {Name Server} {Nombre del servidor}
::msgcat::mcset es {Name or Designation} [encoding convertfrom iso8859-1 {Nombre o designación}]
::msgcat::mcset es {Name} 
::msgcat::mcset es {Native Dialog} [encoding convertfrom iso8859-1 {Diálogo nativo}]
::msgcat::mcset es {New Features} [encoding convertfrom iso8859-1 {Nuevas características}]
::msgcat::mcset es {New Frame 3D} {Nuevo Marco 3D}
::msgcat::mcset es {New Frame RGB} {Nuevo marco RGB}  
::msgcat::mcset es {New Frame each Time} {Nuevo marco cada vez}
::msgcat::mcset es {New Frame} {Nuevo marco}
::msgcat::mcset es {New Graph} 
::msgcat::mcset es {New Group} {Nuevo grupo}
::msgcat::mcset es {New Plot} 
::msgcat::mcset es {New} {Nuevo}
::msgcat::mcset es {Next Block} 
::msgcat::mcset es {Next Frame} {Siguiente Marco}
::msgcat::mcset es {Next} {Siguiente}
::msgcat::mcset es {No Catalog specified} [encoding convertfrom iso8859-1 {No se ha especificado el catálogo}]
::msgcat::mcset es {No Data Available} 
::msgcat::mcset es {No Items Found} [encoding convertfrom iso8859-1 {Artículos no encontrados}]
::msgcat::mcset es {Non-NAN} 
::msgcat::mcset es {Non-Zero} 
::msgcat::mcset es {None} {Nada}
::msgcat::mcset es {Normal} 
::msgcat::mcset es {North} {Norte}
::msgcat::mcset es {Not Found} 
::msgcat::mcset es {Not Supported} 
::msgcat::mcset es {Not valid export format} 
::msgcat::mcset es {Notes} 
::msgcat::mcset es {Number of Samples} [encoding convertfrom iso8859-1 {Número de muestreos}]
::msgcat::mcset es {Number of Threads} 
::msgcat::mcset es {Number of Ticks} 
::msgcat::mcset es {Number} [encoding convertfrom iso8859-1 {Número}]
::msgcat::mcset es {Numerics} [encoding convertfrom iso8859-1 {Numeración}]
::msgcat::mcset es {OK} {Vale} 
::msgcat::mcset es {Object} {Objeto}
::msgcat::mcset es {ObsId} 
::msgcat::mcset es {Open File} {Abrir fichero}
::msgcat::mcset es {Open ME Cube} 
::msgcat::mcset es {Open ME Frames} 
::msgcat::mcset es {Open Mosaic IRAF Seg} 
::msgcat::mcset es {Open Mosaic IRAF} 
::msgcat::mcset es {Open Mosaic WCS Seg} 
::msgcat::mcset es {Open Mosaic WCS} 
::msgcat::mcset es {Open Mosaic WFPC2} 
::msgcat::mcset es {Open RGB Cube} 
::msgcat::mcset es {Open RGB Image} 
::msgcat::mcset es {Open Regions} 
::msgcat::mcset es {Open Slice} 
::msgcat::mcset es {Open TCL Console} {Abrir consola TCL}
::msgcat::mcset es {Open URL} {Abrir URL}
::msgcat::mcset es {Open as} 
::msgcat::mcset es {Open} {Abrir}
::msgcat::mcset es {Operator} {Operador}
::msgcat::mcset es {Orientation} [encoding convertfrom iso8859-1 {Orientación}]
::msgcat::mcset es {Origin} 
::msgcat::mcset es {Oscillate} 
::msgcat::mcset es {Other Color} 
::msgcat::mcset es {Other Font Size} 
::msgcat::mcset es {Other} {Otro}
::msgcat::mcset es {Outer} {Exterior} 
::msgcat::mcset es {Overplot} 
::msgcat::mcset es {Override Color} 
::msgcat::mcset es {PNG} 
::msgcat::mcset es {PS Page Setup}  [encoding convertfrom iso8859-1 {Setup para Página PS}]
::msgcat::mcset es {PS Print} {Imprimir PS}
::msgcat::mcset es {Page Setup} [encoding convertfrom iso8859-1 {Formato de página}] 
::msgcat::mcset es {Page Source} [encoding convertfrom iso8859-1 {Fuente HTML de la página}]  
::msgcat::mcset es {Pan To} {Trasladar a} 
::msgcat::mcset es {Pan Zoom Rotate Parameters} [encoding convertfrom iso8859-1 {Parámetros de traslación, Zoom y rotación}]
::msgcat::mcset es {Pan Zoom} 
::msgcat::mcset es {Pan then Zoom} [encoding convertfrom iso8859-1 {Trasladar y después Zoom}] 
::msgcat::mcset es {Panda} {Corona segmentada} 
::msgcat::mcset es {Panner} [encoding convertfrom iso8859-1 {Ventanilla panorámica}] 
::msgcat::mcset es {Pan} {Trasladar} 
::msgcat::mcset es {Parameters} [encoding convertfrom iso8859-1 {Parámetros}]
::msgcat::mcset es {Password} [encoding convertfrom iso8859-1 {Contraseña}]
::msgcat::mcset es {Paste Contours} {Pegar contornos}
::msgcat::mcset es {Paste} {Pegar}
::msgcat::mcset es {Physical} [encoding convertfrom iso8859-1 {Física}]
::msgcat::mcset es {Pixel Distribution} [encoding convertfrom iso8859-1 {Distribución por píxeles}]
::msgcat::mcset es {Pixel Size} [encoding convertfrom iso8859-1 {Tamaño del píxel}]
::msgcat::mcset es {Pixel Table} [encoding convertfrom iso8859-1 {Tabla en píxeles}]
::msgcat::mcset es {Pixels} [encoding convertfrom iso8859-1 {Píxeles}]
::msgcat::mcset es {Planets} 
::msgcat::mcset es {Play} 
::msgcat::mcset es {Please Select a Region} 
::msgcat::mcset es {Please change the file's permission to disable other users write access. Use anyway?} 
::msgcat::mcset es {Please specify instruments} 
::msgcat::mcset es {Please specify radius and either name or (ra,dec)} 
::msgcat::mcset es {Please specify width, height, and either name or (ra,dec)} {Por farvor, especifique el ancho, altura, y nombre o (A.R.,Dec.)}
::msgcat::mcset es {Plot 2D} 
::msgcat::mcset es {Plot 3D} 
::msgcat::mcset es {Plot Area} 
::msgcat::mcset es {Plot Control Panel} 
::msgcat::mcset es {Plot Tool} 
::msgcat::mcset es {Plotting Regions} {Dibujando regiones}
::msgcat::mcset es {Plot} 
::msgcat::mcset es {Plus} [encoding convertfrom iso8859-1 {Más}]
::msgcat::mcset es {Pointer} {Indicador}
::msgcat::mcset es {Points} [encoding convertfrom iso8859-1 {Posición}]
::msgcat::mcset es {Point} [encoding convertfrom iso8859-1 {Posición}]
::msgcat::mcset es {Polygon} [encoding convertfrom iso8859-1 {Polígono}]
::msgcat::mcset es {Portrait} 
::msgcat::mcset es {Position} 
::msgcat::mcset es {Poster} [encoding convertfrom iso8859-1 {Póster}]
::msgcat::mcset es {Postscript} 
::msgcat::mcset es {Power} {Potencia}
::msgcat::mcset es {Precision} 
::msgcat::mcset es {Preferences} {Preferencias}
::msgcat::mcset es {Preserve During Load} {Conservar mientras se carga}
::msgcat::mcset es {Previous Block} 
::msgcat::mcset es {Previous Frame} {Marco Previo}
::msgcat::mcset es {Previous} {Previo}
::msgcat::mcset es {Prev} 
::msgcat::mcset es {Print Coordinates} {Imprimir coordenadas}
::msgcat::mcset es {Print To} {Imprimir en}
::msgcat::mcset es {Printer} {Impresora}
::msgcat::mcset es {Print} {Imprimir}
::msgcat::mcset es {Prism Goto} 
::msgcat::mcset es {Prism} 
::msgcat::mcset es {Projection} [encoding convertfrom iso8859-1 {Proyección}]
::msgcat::mcset es {Properties} {Propiedades}
::msgcat::mcset es {Property} {Propiedad}
::msgcat::mcset es {Proxy Host} 
::msgcat::mcset es {Proxy Port} 
::msgcat::mcset es {Publication} [encoding convertfrom iso8859-1 {Publicación}]
::msgcat::mcset es {Quadratic} [encoding convertfrom iso8859-1 {Cuadrático}]
::msgcat::mcset es {RDB} 
::msgcat::mcset es {RGB Array} 
::msgcat::mcset es {RGB Cube} 
::msgcat::mcset es {RGB Image} 
::msgcat::mcset es {RGB} 
::msgcat::mcset es {Radial Profile} 
::msgcat::mcset es {Radius} {Radio}
::msgcat::mcset es {Range} 
::msgcat::mcset es {Redo} {Rehacer}
::msgcat::mcset es {Red} {Rojo}
::msgcat::mcset es {Reference Manual} {Manual de referencia}
::msgcat::mcset es {Reference} {Manual} 
::msgcat::mcset es {Refresh Frame} {Refrescar marco}
::msgcat::mcset es {Refresh} {Refrescar}
::msgcat::mcset es {Region Parameters} 
::msgcat::mcset es {Region} [encoding convertfrom iso8859-1 {Región}]
::msgcat::mcset es {Release Notes} [encoding convertfrom iso8859-1 {Notas de esta versión}]
::msgcat::mcset es {Release} [encoding convertfrom iso8859-1 {Versión}]
::msgcat::mcset es {Reload} {Recargar}
::msgcat::mcset es {Render} 
::msgcat::mcset es {Repeat} 
::msgcat::mcset es {Reset Colormap} {Restaurar el mapa de colores}
::msgcat::mcset es {Reset Frame} {Restaurar Marco}
::msgcat::mcset es {Reset} 
::msgcat::mcset es {Restore} 
::msgcat::mcset es {Retrieve} {Localizar y leer}
::msgcat::mcset es {Return} 
::msgcat::mcset es {Right} 
::msgcat::mcset es {Roman} 
::msgcat::mcset es {Rotate} {Rotar}
::msgcat::mcset es {Rows} {Filas}
::msgcat::mcset es {Row} 
::msgcat::mcset es {Ruler} {Regla}
::msgcat::mcset es {SAMP Image} 
::msgcat::mcset es {SAMP Table} 
::msgcat::mcset es {SAMP: not connected} 
::msgcat::mcset es {SAMP} 
::msgcat::mcset es {Sample Increment} 
::msgcat::mcset es {Sample Parameters} 
::msgcat::mcset es {Samples per Line} [encoding convertfrom iso8859-1 {Muestreos por línea}] 
::msgcat::mcset es {Sample} 
::msgcat::mcset es {Save 3D Movie} 
::msgcat::mcset es {Save Color Tags} 
::msgcat::mcset es {Save Contour Levels} {Guardar niveles de contorno}
::msgcat::mcset es {Save Contrast/Bias} {Guardar contraste/Bias}
::msgcat::mcset es {Save Data} {Guardar datos}
::msgcat::mcset es {Save Image EPS} 
::msgcat::mcset es {Save Image FITS} 
::msgcat::mcset es {Save Image GIF} 
::msgcat::mcset es {Save Image JPEG} 
::msgcat::mcset es {Save Image PNG} 
::msgcat::mcset es {Save Image TIFF} 
::msgcat::mcset es {Save Image on Download} 
::msgcat::mcset es {Save Image} {Guardar imagen}
::msgcat::mcset es {Save ME Cube} 
::msgcat::mcset es {Save Mosaic WCS Seg} 
::msgcat::mcset es {Save Mosaic WCS} 
::msgcat::mcset es {Save RGB Cube} 
::msgcat::mcset es {Save RGB Image} 
::msgcat::mcset es {Save Regions} {Guardar regiones}
::msgcat::mcset es {Save Selected Regions} 
::msgcat::mcset es {Save Select} 
::msgcat::mcset es {Save Slice} 
::msgcat::mcset es {Save Template} {Guardar modelo}
::msgcat::mcset es {Save as} 
::msgcat::mcset es {Save} {Guardar}
::msgcat::mcset es {Scale Parameters} [encoding convertfrom iso8859-1 {Párametros de escala}]
::msgcat::mcset es {Scale and Limits} 
::msgcat::mcset es {Scale} {Escala}
::msgcat::mcset es {Scan} {Escanear} 
::msgcat::mcset es {Scatter Dataset} 
::msgcat::mcset es {Scatter Plot Tool} 
::msgcat::mcset es {Scope} {Alcance}
::msgcat::mcset es {Screen} 
::msgcat::mcset es {Search for Catalogs} [encoding convertfrom iso8859-1 {Buscar por catálogos}]
::msgcat::mcset es {Seconds} {Segundos}
::msgcat::mcset es {Segment} 
::msgcat::mcset es {Select All} {Seleccionar todos}
::msgcat::mcset es {Select Coordinate System } {Seleccionar el sistema de coordenadas}
::msgcat::mcset es {Select Dataset} 
::msgcat::mcset es {Select Datatset} 
::msgcat::mcset es {Select Graph} 
::msgcat::mcset es {Select None} {Seleccionar nada}
::msgcat::mcset es {Send} 
::msgcat::mcset es {Server} {Servidor}
::msgcat::mcset es {Sexagesimal} 
::msgcat::mcset es {Shadow} 
::msgcat::mcset es {Shape} {Forma}
::msgcat::mcset es {Show All} {Mostrarlos todos}
::msgcat::mcset es {Show Command} 
::msgcat::mcset es {Show Compass} 
::msgcat::mcset es {Show Grid} 
::msgcat::mcset es {Show Legend} 
::msgcat::mcset es {Show Text} {Mostrar Texto}
::msgcat::mcset es {Show/Hide Frames} {Mostar/ocultar marcos}
::msgcat::mcset es {Show} {Mostrar}
::msgcat::mcset es {Simple Cross} 
::msgcat::mcset es {Simple Image Access} 
::msgcat::mcset es {Simple Plus} 
::msgcat::mcset es {Single Frame} [encoding convertfrom iso8859-1 {Un único marco}]
::msgcat::mcset es {Single} [encoding convertfrom iso8859-1 {Único}]
::msgcat::mcset es {Sites} 
::msgcat::mcset es {Size/Radius} [encoding convertfrom iso8859-1 {Tamaño/Radio}]
::msgcat::mcset es {Size} [encoding convertfrom iso8859-1 {Tamaño}]
::msgcat::mcset es {Skip First} {Omitir primeros} 
::msgcat::mcset es {Slice} 
::msgcat::mcset es {Smooth Parameters} [encoding convertfrom iso8859-1 {Parámetros de suavizado}]
::msgcat::mcset es {Smoothness} 
::msgcat::mcset es {Smooth} {Suavizar}
::msgcat::mcset es {Sorry, DS9 does not support} {Lo siento, DS9 no admite}
::msgcat::mcset es {Sorry, DS9 requires a Truecolor8, Truecolor16, Truecolor24 visual be available} 
::msgcat::mcset es {Sort} {Clasificar} 
::msgcat::mcset es {Source TCL} [encoding convertfrom iso8859-1 {Leer código TCL}]     
::msgcat::mcset es {Source} {Fuente}
::msgcat::mcset es {Space Equal Distance} 
::msgcat::mcset es {Space Equal Value} 
::msgcat::mcset es {Spacing} {Espaciado} 
::msgcat::mcset es {Sqrt} 
::msgcat::mcset es {Square Root} [encoding convertfrom iso8859-1 {Raíz cuadrada}]
::msgcat::mcset es {Squared} {Al cuadrado}
::msgcat::mcset es {Square} 
::msgcat::mcset es {Starbase} 
::msgcat::mcset es {Startup} 
::msgcat::mcset es {Start} {Empezar}
::msgcat::mcset es {Statistics} 
::msgcat::mcset es {Status} {Estado}
::msgcat::mcset es {Step} {Escalonado}
::msgcat::mcset es {Stop} {Parar} 
::msgcat::mcset es {Story of SAOImageDS9} 
::msgcat::mcset es {Story} 
::msgcat::mcset es {Strip Parameters} 
::msgcat::mcset es {Strip Scale} 
::msgcat::mcset es {Strip} 
::msgcat::mcset es {Sum} {Suma}
::msgcat::mcset es {Symbol Editor} [encoding convertfrom iso8859-1 {Editor de símbolos}]
::msgcat::mcset es {Symbol} [encoding convertfrom iso8859-1 {Símbolo}]
::msgcat::mcset es {TIFF} 
::msgcat::mcset es {TSV} 
::msgcat::mcset es {Tab-Separated-Value} 
::msgcat::mcset es {Table} 
::msgcat::mcset es {Tabloid} 
::msgcat::mcset es {Tag Color} 
::msgcat::mcset es {Template} 
::msgcat::mcset es {Text} {Texto}
::msgcat::mcset es {Theme} 
::msgcat::mcset es {Then} {Entonces} 
::msgcat::mcset es {Thickness} {Grosor}
::msgcat::mcset es {This analysis task is already running. Do you wish to kill it?} [encoding convertfrom iso8859-1 {Esta tarea para el análisis ya está siendo ejecutada. ¿Desea interrumpirla?}]
::msgcat::mcset es {This function is not available.} 
::msgcat::mcset es {This function is not currently supported for this port.} 
::msgcat::mcset es {Tickmarks} {Marcas} 
::msgcat::mcset es {Tile Frames} {Alicatar los marcos}
::msgcat::mcset es {Tile Parameters} [encoding convertfrom iso8859-1 {Parámetros de alicatado}]
::msgcat::mcset es {Tile} {Tejar}
::msgcat::mcset es {Times} 
::msgcat::mcset es {Titles} 
::msgcat::mcset es {Title} [encoding convertfrom iso8859-1 {Título}]
::msgcat::mcset es {Tophat} 
::msgcat::mcset es {Topographic} 
::msgcat::mcset es {Top} 
::msgcat::mcset es {To} {A} 
::msgcat::mcset es {Transparency} 
::msgcat::mcset es {Triangle} 
::msgcat::mcset es {Type} {Clase} 
::msgcat::mcset es {URL} 
::msgcat::mcset es {Unable to connect directly: using Web Proxy} 
::msgcat::mcset es {Unable to create FOV Region, celestial WCS Required} 
::msgcat::mcset es {Unable to determine date of observation} 
::msgcat::mcset es {Unable to evaluate filter} {Incapaz de evaluar el filtro}
::msgcat::mcset es {Unable to find Footprint window} 
::msgcat::mcset es {Unable to find PRISM window} 
::msgcat::mcset es {Unable to find SIAP window} 
::msgcat::mcset es {Unable to find URL column} 
::msgcat::mcset es {Unable to find catalog window} [encoding convertfrom iso8859-1 {Incapaz de hallar la ventana de catálogo}]
::msgcat::mcset es {Unable to find plot window} [encoding convertfrom iso8859-1 {Incapaz de hallar la ventana gráfica}]
::msgcat::mcset es {Unable to find web window} 
::msgcat::mcset es {Unable to generate plot} 
::msgcat::mcset es {Unable to load RGB image into a non-rgb frame} {Incapaz de cargar imagen RGB en un marco no RGB}
::msgcat::mcset es {Unable to load compressed region file} 
::msgcat::mcset es {Unable to load plot data} 
::msgcat::mcset es {Unable to load region file} 
::msgcat::mcset es {Unable to load} {Incapaz de cargar}
::msgcat::mcset es {Unable to locate FOV Region} 
::msgcat::mcset es {Unable to locate URL} {Incapaz de localizar URL}
::msgcat::mcset es {Unable to match target with XPA Mime request} 
::msgcat::mcset es {Unable to open file} {Incapaz de abrir fichero}
::msgcat::mcset es {Unable to save RGB image from a non-rgb frame} 
::msgcat::mcset es {Undo} {Deshacer}
::msgcat::mcset es {Unique} 
::msgcat::mcset es {Unists} 
::msgcat::mcset es {Units} {Unidades}
::msgcat::mcset es {Unknown Colormap} 
::msgcat::mcset es {Unknown command} 
::msgcat::mcset es {Update Filter} 
::msgcat::mcset es {Update Group} {Actualizar grupo}
::msgcat::mcset es {Update from Current Crosshair} {Actualizar a partir del punto de mira actual}
::msgcat::mcset es {Update from Current Frame} {Actualizar a partir del marco actual}
::msgcat::mcset es {Update} {Actualizar}
::msgcat::mcset es {Upper Left Back} 
::msgcat::mcset es {Upper Left Front} 
::msgcat::mcset es {Upper Right Back} 
::msgcat::mcset es {Upper Right Front} 
::msgcat::mcset es {Use Authentication} [encoding convertfrom iso8859-1 {Usa autenticación}]
::msgcat::mcset es {Use Current Frame on Download} {Usar marco actual al transferir}
::msgcat::mcset es {Use Internal Web Browser} {Usar Web Browser interno}
::msgcat::mcset es {Use Original Color/Width} 
::msgcat::mcset es {Use Proxy} {Usar Proxy}
::msgcat::mcset es {Use Theme Colors} 
::msgcat::mcset es {Use background color instead of theme color} 
::msgcat::mcset es {User Manual} 
::msgcat::mcset es {Username} {Nombre de usuario}
::msgcat::mcset es {User} {Usuario}
::msgcat::mcset es {Use} {Usa} 
::msgcat::mcset es {VO Server} 
::msgcat::mcset es {VOTable} 
::msgcat::mcset es {VOT} 
::msgcat::mcset es {VO} 
::msgcat::mcset es {Value} {Valor}
::msgcat::mcset es {Vector} 
::msgcat::mcset es {Vertical Graph} [encoding convertfrom iso8859-1 {Gráfica vertical}]
::msgcat::mcset es {Vertical Layout} [encoding convertfrom iso8859-1 {Distribución vertical}]
::msgcat::mcset es {Vertical Text} {Texto vertical} 
::msgcat::mcset es {Vertical} 
::msgcat::mcset es {View} {Ver}
::msgcat::mcset es {Virtual Observatory} {Observatorio Virtual}
::msgcat::mcset es {WCS Parameters} 
::msgcat::mcset es {WCS} 
::msgcat::mcset es {Wavelength} {Longitud de onda}
::msgcat::mcset es {Web Browser} 
::msgcat::mcset es {White} {Blanco}
::msgcat::mcset es {Width} {Ancho}
::msgcat::mcset es {Window} 
::msgcat::mcset es {Words matching title, description} [encoding convertfrom iso8859-1 {Palabras que coincidan con el título, descripción}]
::msgcat::mcset es {X Axis Title} 
::msgcat::mcset es {X Axis} 
::msgcat::mcset es {X Column} 
::msgcat::mcset es {X Error Column} 
::msgcat::mcset es {XPA Information} [encoding convertfrom iso8859-1 {Información XPA}]
::msgcat::mcset es {XPA not initialized} {XPA no inicializado}
::msgcat::mcset es {XPA} 
::msgcat::mcset es {X} 
::msgcat::mcset es {Y Axis Title} 
::msgcat::mcset es {Y Axis} 
::msgcat::mcset es {Y Column} 
::msgcat::mcset es {Y Error Column} 
::msgcat::mcset es {Yellow} {Amarillo}
::msgcat::mcset es {Y} 
::msgcat::mcset es {Z Axis Scale} 
::msgcat::mcset es {ZScale Parameters} [encoding convertfrom iso8859-1 {Parámetros de la escala Z}]
::msgcat::mcset es {Zero} 
::msgcat::mcset es {Zoom Fit} 
::msgcat::mcset es {Zoom In} {Aumentar}
::msgcat::mcset es {Zoom Out} {Reducir}
::msgcat::mcset es {Zoom} {Zoom}
::msgcat::mcset es {already connected} 
::msgcat::mcset es {and} 
::msgcat::mcset es {b} 
::msgcat::mcset es {g} 
::msgcat::mcset es {h5utils} 
::msgcat::mcset es {hundredths second} 
::msgcat::mcset es {internal error} 
::msgcat::mcset es {not connected} 
::msgcat::mcset es {not} 
::msgcat::mcset es {only} 
::msgcat::mcset es {or center of data} {o centro de los datos}
::msgcat::mcset es {rows of data have been downloaded. More may be available. You may wish to adjust the maximum allowed} [encoding convertfrom iso8859-1 {Filas de datos transferidas. Puede que haya más disponibles. Quizá quiera ajustar el máximo permitido.}]
::msgcat::mcset es {r} 
::msgcat::mcset es {unable to locate HUB} 
::msgcat::mcset es {x} 
