# Clean UTF-8 Translation Catalog for Tcl 9
# Generated automatically from legacy fr.msg

::msgcat::mcset fr 2d 2d
::msgcat::mcset fr 3d 3d
::msgcat::mcset fr {A postscript generation error has occurred} {Une erreur de génération de postscript s'est produite}
::msgcat::mcset fr AIP AIP
::msgcat::mcset fr Abort Abort
::msgcat::mcset fr {About SAOImageDS9} {About SAOImageDS9}
::msgcat::mcset fr About {À propos de}
::msgcat::mcset fr Acknowledgment Remerciement
::msgcat::mcset fr {Add Bar Graph} {Add Bar Graph}
::msgcat::mcset fr {Add Graph} {Add Graph}
::msgcat::mcset fr {Add Line Graph} {Add Line Graph}
::msgcat::mcset fr {Add New Frame} {Add New Frame}
::msgcat::mcset fr Add Ajouter
::msgcat::mcset fr {Advanced Layout} {Advanced Layout}
::msgcat::mcset fr Advanced Avancé
::msgcat::mcset fr {Align North Up} {Align North Up}
::msgcat::mcset fr Align Aligner
::msgcat::mcset fr {All Columns} {Toutes les colonnes}
::msgcat::mcset fr {All Rows} {Toutes les rangées}
::msgcat::mcset fr All Tous
::msgcat::mcset fr {Always save files during Backup} {Always save files during Backup}
::msgcat::mcset fr Amplifier Amplificateur
::msgcat::mcset fr {An error has occurred during backup} {An error has occurred during backup}
::msgcat::mcset fr {An error has occurred during restore} {An error has occurred during restore}
::msgcat::mcset fr {An error has occurred invoking the Analysis task} {Une erreur s'est produite en invoquant la tâche d'analyse}
::msgcat::mcset fr {An error has occurred while creating} {An error has occurred while creating}
::msgcat::mcset fr {An error has occurred while loading} {An error has occurred while loading}
::msgcat::mcset fr {An error has occurred while printing} {Une erreur s'est produite pendant l'impression}
::msgcat::mcset fr {An error has occurred while saving} {Une erreur s'est produite pendant la sauvegarde}
::msgcat::mcset fr {An internal error has been detected} {An internal error has been detected}
::msgcat::mcset fr {Analysis Command Log} {Enregistrement des commandes d'analyse}
::msgcat::mcset fr {Analysis Commands} {Analysis Commands}
::msgcat::mcset fr {Analysis File} {Analysis File}
::msgcat::mcset fr {Analysis Log} {Analysis Log}
::msgcat::mcset fr Analysis Analyse
::msgcat::mcset fr {Angle Complement} {Complément d'angle}
::msgcat::mcset fr Angles Angles
::msgcat::mcset fr Angle Angle
::msgcat::mcset fr Annuli Anneaux
::msgcat::mcset fr Annulus Anneau
::msgcat::mcset fr Apply Appliquer
::msgcat::mcset fr ArcMin ArcMin
::msgcat::mcset fr ArcSec ArcSec
::msgcat::mcset fr Architecture Architecture
::msgcat::mcset fr Archives Archives
::msgcat::mcset fr Array Array
::msgcat::mcset fr Arrow Flèche
::msgcat::mcset fr Asteroids Asteroids
::msgcat::mcset fr Astronomy Astronomy
::msgcat::mcset fr {At Startup} {At Startup}
::msgcat::mcset fr {At least 2 different catalogs are required} {At least 2 different catalogs are required}
::msgcat::mcset fr {Auto Centroid} {Auto Centroid}
::msgcat::mcset fr {Auto Plot 2D} {Auto Plot 2D}
::msgcat::mcset fr {Auto Plot 3D} {Auto Plot 3D}
::msgcat::mcset fr {Auto Plot Statistics} {Auto Plot Statistics}
::msgcat::mcset fr {Auto Plot} {Auto Plot}
::msgcat::mcset fr {Auto Recovery} {Auto Recovery}
::msgcat::mcset fr {Autoload FITS Regions} {Autochargement des régions FITS}
::msgcat::mcset fr Autoload Autoload
::msgcat::mcset fr Automatic Automatique
::msgcat::mcset fr Average Moyenne
::msgcat::mcset fr {Axes Number} {Axes Number}
::msgcat::mcset fr {Axes Order} {Axes Order}
::msgcat::mcset fr {Axes Range} {Axes Range}
::msgcat::mcset fr {Axes Title} {Axes Title}
::msgcat::mcset fr Axes Axes
::msgcat::mcset fr {Axis Length} {Longueur de l'axe}
::msgcat::mcset fr {Axis Numbers} {Échelle de l'axe}
::msgcat::mcset fr {Axis Title} {Axis Title}
::msgcat::mcset fr Axis Axe
::msgcat::mcset fr Azimuth Azimuth
::msgcat::mcset fr {Background Color} {Couleur de fond}
::msgcat::mcset fr Background Fond
::msgcat::mcset fr Backup Backup
::msgcat::mcset fr Back Retour
::msgcat::mcset fr {Bar Dataset} {Bar Dataset}
::msgcat::mcset fr {Bar Plot Tool} {Bar Plot Tool}
::msgcat::mcset fr {Bar Width} {Bar Width}
::msgcat::mcset fr Bar Bar
::msgcat::mcset fr {Basic Layout} {Basic Layout}
::msgcat::mcset fr Basic Basic
::msgcat::mcset fr Behavior Behavior
::msgcat::mcset fr Bias Biais
::msgcat::mcset fr {Bin 3rd Column} {3ème colonne de bin}
::msgcat::mcset fr {Bin Center} {Centre de bin}
::msgcat::mcset fr {Bin Columns} {Colonnes de bin}
::msgcat::mcset fr {Bin Filter} {Filtre de bin}
::msgcat::mcset fr {Bin Fit} {Bin Fit}
::msgcat::mcset fr {Bin In} {Bin In}
::msgcat::mcset fr {Bin Out} {Bin Out}
::msgcat::mcset fr {Binning Parameters} {Paramètres de bin}
::msgcat::mcset fr Bins Bins
::msgcat::mcset fr Bin Bin
::msgcat::mcset fr Black Noir
::msgcat::mcset fr {Blank/Inf/NaN Color} {Blanc/Inf/NaN Couleur}
::msgcat::mcset fr Blend Blend
::msgcat::mcset fr {Blink Frames} {Clignotement des fenêtres}
::msgcat::mcset fr {Blink Interval} {Intervalle de clignotement}
::msgcat::mcset fr Blink Clignotement
::msgcat::mcset fr {Block Fit} {Block Fit}
::msgcat::mcset fr {Block In} {Bin à}
::msgcat::mcset fr {Block Out} {Bin de}
::msgcat::mcset fr {Block Parameters} {Block Parameters}
::msgcat::mcset fr {Block Pixel} {Block Pixel}
::msgcat::mcset fr Block Bin
::msgcat::mcset fr Blue Bleu
::msgcat::mcset fr Bold Gras
::msgcat::mcset fr {Border Color} {Border Color}
::msgcat::mcset fr {Border Width} {Border Width}
::msgcat::mcset fr Border Bordure
::msgcat::mcset fr Bottom Bottom
::msgcat::mcset fr {Box Annulus} {Anneau de boîte}
::msgcat::mcset fr {Box Panda} {Box Panda}
::msgcat::mcset fr BoxCircle BoxCircle
::msgcat::mcset fr Boxcar Boxcar
::msgcat::mcset fr Box Boîte
::msgcat::mcset fr {Bring to Front} {Bring to Front}
::msgcat::mcset fr Broadcast Broadcast
::msgcat::mcset fr Browser Browser
::msgcat::mcset fr Browse Parcourir
::msgcat::mcset fr Buffer Tampon
::msgcat::mcset fr Buttonbar Buttonbar
::msgcat::mcset fr Buttons Boutons
::msgcat::mcset fr Bytes Octets
::msgcat::mcset fr CMYK CMYK
::msgcat::mcset fr {Can Delete} {Peut effacer}
::msgcat::mcset fr {Can Edit} {Peut éditer}
::msgcat::mcset fr {Can Move} {Peut déplacer}
::msgcat::mcset fr {Can Rotate} {Peut tourner}
::msgcat::mcset fr Cancelled Cancelled
::msgcat::mcset fr Cancel Annuler
::msgcat::mcset fr Cap Cap
::msgcat::mcset fr {Catalog Server} {Serveur de catalogue}
::msgcat::mcset fr {Catalog Tool} {Outil de catalogue}
::msgcat::mcset fr Catalogs Catalogues
::msgcat::mcset fr Catalog Catalogue
::msgcat::mcset fr Catrom Catrom
::msgcat::mcset fr Cat Cat
::msgcat::mcset fr {Center Dialogs} {Center Dialogs}
::msgcat::mcset fr {Center Image} {Centrer l'image}
::msgcat::mcset fr Center Centrer
::msgcat::mcset fr {Centroid Parameters} {Centroid Parameters}
::msgcat::mcset fr Centroid Centroid
::msgcat::mcset fr Circle Cercle
::msgcat::mcset fr {Clear All} {Tout effacer}
::msgcat::mcset fr {Clear Analysis Commands} {Effacer les commandes d'analyse}
::msgcat::mcset fr {Clear Cache} {Effacer le cache}
::msgcat::mcset fr {Clear External Analysis Commands?} {Effacer les commandes d'analyse externes ?}
::msgcat::mcset fr {Clear Filter} {Effacer le filtre}
::msgcat::mcset fr {Clear Frame} {Effacer la fenêtre}
::msgcat::mcset fr {Clear Preferences?} {Effacer les préférences ?}
::msgcat::mcset fr {Clear Preferences} {Effacer les préférences}
::msgcat::mcset fr Clear Effacer
::msgcat::mcset fr {Click to Center} {Cliquer pour centrer}
::msgcat::mcset fr Close Fermer
::msgcat::mcset fr {Colorbar Size} {Colorbar Size}
::msgcat::mcset fr Colorbar {Barre de couleurs}
::msgcat::mcset fr {Colormap Parameters} {Paramètres de carte de couleurs}
::msgcat::mcset fr Colormaps Colormaps
::msgcat::mcset fr Colormap {Carte de couleurs}
::msgcat::mcset fr Color Couleur
::msgcat::mcset fr Columns Colonnes
::msgcat::mcset fr Column Colonne
::msgcat::mcset fr Comets Comets
::msgcat::mcset fr {Command not allowed} {Command not allowed}
::msgcat::mcset fr Command Command
::msgcat::mcset fr Compass Boussole
::msgcat::mcset fr {Composite Region} {Composite Region}
::msgcat::mcset fr Composite Composite
::msgcat::mcset fr Compression Compression
::msgcat::mcset fr Configure Configurer
::msgcat::mcset fr Connect Connect
::msgcat::mcset fr Console Console
::msgcat::mcset fr {Contacting Server} {Contacting Server}
::msgcat::mcset fr {Contour Parameters} {Paramètres de contour}
::msgcat::mcset fr {Contour Paste} {Contour Paste}
::msgcat::mcset fr {Contour Save} {Contour Save}
::msgcat::mcset fr Contours Contours
::msgcat::mcset fr Contour Contour
::msgcat::mcset fr Contrast Contraste
::msgcat::mcset fr {Control Panel} {Control Panel}
::msgcat::mcset fr {Convert to Polygons} {Convertir en polygones}
::msgcat::mcset fr {Coordinate Grid Parameters} {Paramètres de grille de coordonnées}
::msgcat::mcset fr {Coordinate Grid} {Grille de coordonnées}
::msgcat::mcset fr {Coordinate System} {Système de coordonnées}
::msgcat::mcset fr Coordinates Coordinates
::msgcat::mcset fr Coordinate Coordonnée
::msgcat::mcset fr {Copy Contours} {Copier les contours}
::msgcat::mcset fr {Copy to Regions} {Copier vers Régions}
::msgcat::mcset fr Copy Copier
::msgcat::mcset fr {Create Composite Region} {Create Composite Region}
::msgcat::mcset fr {Create Movie} {Create Movie}
::msgcat::mcset fr {Create New Frame on Download} {Créer une nouvelle fenêtre au téléchargement}
::msgcat::mcset fr Create Create
::msgcat::mcset fr {Crop Parameters} {Crop Parameters}
::msgcat::mcset fr Crop Crop
::msgcat::mcset fr {Crosshair Parameters} {Crosshair Parameters}
::msgcat::mcset fr {Crosshair To} {Réticule vers}
::msgcat::mcset fr Crosshair Réticule
::msgcat::mcset fr Cross Croisement
::msgcat::mcset fr Cubehelix Cubehelix
::msgcat::mcset fr Cube Cube
::msgcat::mcset fr Cubic Cubic
::msgcat::mcset fr {Current Frame} {Fenêtre courante}
::msgcat::mcset fr {Current Range} {Intervalle courant}
::msgcat::mcset fr Current Courant
::msgcat::mcset fr Cursor Curseur
::msgcat::mcset fr Cut Couper
::msgcat::mcset fr Cyan Cyan
::msgcat::mcset fr DMS DMS
::msgcat::mcset fr DPI DPI
::msgcat::mcset fr {DS9 has detected a newer version of a backup file and therefore will not process this file.} {DS9 has detected a newer version of a backup file and therefore will not process this file.}
::msgcat::mcset fr {DS9 has detected a newer version of a preferences file.} {DS9 has detected a newer version of a preferences file.}
::msgcat::mcset fr {DS9 has detected an older backup file, do you wish to continue?} {DS9 has detected an older backup file, do you wish to continue?}
::msgcat::mcset fr {DS9 has detected an older preferences file, do you wish to update?} {DS9 a détecté une vielle version du fichier de préférences, voulez vous la mettre à jour ?}
::msgcat::mcset fr {DS9 will complete the initialization process} {DS9 va terminer le processus d'initialisation}
::msgcat::mcset fr Darken Darken
::msgcat::mcset fr Dash Tiret
::msgcat::mcset fr {Data Format} {Format de données}
::msgcat::mcset fr {Data must be ascii numeric values} {Data must be ascii numeric values}
::msgcat::mcset fr {Dataset Name} {Dataset Name}
::msgcat::mcset fr Dataset {Ensemble de données}
::msgcat::mcset fr Data Data
::msgcat::mcset fr {Decrease Bin} {Decrease Bin}
::msgcat::mcset fr {Decrease Block} {Decrease Block}
::msgcat::mcset fr {Decrease Magnification} {Decrease Magnification}
::msgcat::mcset fr {Decrease Zoom} {Decrease Zoom}
::msgcat::mcset fr Decrease Diminuer
::msgcat::mcset fr {Default All Files} {Default All Files}
::msgcat::mcset fr {Default Format} {Default Format}
::msgcat::mcset fr {Default Length} {Default Length}
::msgcat::mcset fr Default Defaut
::msgcat::mcset fr Degrees Degrés
::msgcat::mcset fr Delay Delay
::msgcat::mcset fr {Delete All Frames?} {Supprimer toutes les fenêtres ?}
::msgcat::mcset fr {Delete All Frames} {Supprimer toutes les fenêtres}
::msgcat::mcset fr {Delete All Groups?} {Supprimer tous les groupes ?}
::msgcat::mcset fr {Delete All Groups} {Supprimer tous les groupes}
::msgcat::mcset fr {Delete All Load} {Delete All Load}
::msgcat::mcset fr {Delete All and Open} {Delete All and Open}
::msgcat::mcset fr {Delete All} {Delete All}
::msgcat::mcset fr {Delete Color Tags} {Delete Color Tags}
::msgcat::mcset fr {Delete Dataset} {Delete Dataset}
::msgcat::mcset fr {Delete Frame} {Supprimer la fenêtre}
::msgcat::mcset fr {Delete Graph} {Delete Graph}
::msgcat::mcset fr {Delete Group} {Supprimer le groupe}
::msgcat::mcset fr {Delete Selection} {Delete Selection}
::msgcat::mcset fr {Delete Select} {Delete Select}
::msgcat::mcset fr Delete Supprimer
::msgcat::mcset fr Depth Profondeur
::msgcat::mcset fr Detector Detecteur
::msgcat::mcset fr {Dialog Box} {Boîte de dialogue}
::msgcat::mcset fr Diameter Diameter
::msgcat::mcset fr Diamond Losange
::msgcat::mcset fr Dimensions Dimensions
::msgcat::mcset fr Dimension Dimention
::msgcat::mcset fr Direction Direction
::msgcat::mcset fr Disconnect Disconnect
::msgcat::mcset fr {Display Size} {Afficher la taille}
::msgcat::mcset fr {Dissolve Composite Region} {Dissolve Composite Region}
::msgcat::mcset fr Dissolve Dissolve
::msgcat::mcset fr Distance Distance
::msgcat::mcset fr Done Done
::msgcat::mcset fr {Download Colormap} {Download Colormap}
::msgcat::mcset fr {Drag to Center} {Glisser au centre}
::msgcat::mcset fr {Duplicate Dataset} {Duplicate Dataset}
::msgcat::mcset fr ENVI ENVI
::msgcat::mcset fr EPS EPS
::msgcat::mcset fr East Est
::msgcat::mcset fr Ecliptic Ecliptiques
::msgcat::mcset fr {Edit Group Name} {Editer le nom du groupe}
::msgcat::mcset fr {Edit Mode} {Mode édition}
::msgcat::mcset fr Edit Édition
::msgcat::mcset fr Elevation Elevation
::msgcat::mcset fr {Ellipse Panda} {Ellipse Panda}
::msgcat::mcset fr Ellipse Ellipse
::msgcat::mcset fr {Elliptical Annulus} {Anneau elliptique}
::msgcat::mcset fr {Elliptical Gaussian} {Elliptical Gaussian}
::msgcat::mcset fr {Elliptical Panda} {Panda elliptique}
::msgcat::mcset fr {Enable Confirmation Dialogs} {Utiliser les dialogues de confirmation}
::msgcat::mcset fr Enable Enable
::msgcat::mcset fr End Fin
::msgcat::mcset fr {Enter Color} {Enter Color}
::msgcat::mcset fr {Enter Font Size} {Enter Font Size}
::msgcat::mcset fr {Enter Group Name} {Entrer le nom du groupe}
::msgcat::mcset fr {Enter Search Expression} {Enter Search Expression}
::msgcat::mcset fr {Enter URL} {Enter URL}
::msgcat::mcset fr Entry Entry
::msgcat::mcset fr {Equal Area} {Egale surface}
::msgcat::mcset fr {Equal Distance} {Egale distance}
::msgcat::mcset fr {Equal Spacing} {Equal Spacing}
::msgcat::mcset fr {Equal Value} {Equal Value}
::msgcat::mcset fr {Error code was returned} {Un code d'erreur a été renvoyé}
::msgcat::mcset fr Errorbar Errorbar
::msgcat::mcset fr Error Erreur
::msgcat::mcset fr {Examine Frame} {Examiner la fenêtre}
::msgcat::mcset fr Examine Examiner
::msgcat::mcset fr Exam Exam
::msgcat::mcset fr Exclude Exclure
::msgcat::mcset fr Exit Sortie
::msgcat::mcset fr {Export Array} {Export Array}
::msgcat::mcset fr {Export ENVI} {Export ENVI}
::msgcat::mcset fr {Export GIF} {Export GIF}
::msgcat::mcset fr {Export HLS Array} {Export HLS Array}
::msgcat::mcset fr {Export HSV Array} {Export HSV Array}
::msgcat::mcset fr {Export JPEG} {Export JPEG}
::msgcat::mcset fr {Export NRRD} {Export NRRD}
::msgcat::mcset fr {Export PNG} {Export PNG}
::msgcat::mcset fr {Export RGB Array} {Export RGB Array}
::msgcat::mcset fr {Export TIFF} {Export TIFF}
::msgcat::mcset fr Export Export
::msgcat::mcset fr {Extension Data} {Extension Data}
::msgcat::mcset fr {Extension not found} {Extension not found}
::msgcat::mcset fr Extensions Extensions
::msgcat::mcset fr Extension Extension
::msgcat::mcset fr {Exterior Axes} {Axes exterieurs}
::msgcat::mcset fr {Exterior Numerics} {Chiffres exterieurs}
::msgcat::mcset fr FAQ Foire-Aux-Questions
::msgcat::mcset fr FITS FITS
::msgcat::mcset fr FK4 FK4
::msgcat::mcset fr FK5 FK5
::msgcat::mcset fr FP FP
::msgcat::mcset fr Factor Factor
::msgcat::mcset fr {Fade Frames} {Fade Frames}
::msgcat::mcset fr {Fade Interval} {Fade Interval}
::msgcat::mcset fr Fade Fade
::msgcat::mcset fr {File Open} {File Open}
::msgcat::mcset fr {File not Found or Unable to load FITS data MIME type} {Fichier non trouvé, ou impossible d'utiliser le type MIME des données FITS}
::msgcat::mcset fr {File not found} {File not found}
::msgcat::mcset fr {Filename Format} {Filename Format}
::msgcat::mcset fr Filename NomDuFichier
::msgcat::mcset fr File Fichier
::msgcat::mcset fr Fill Fill
::msgcat::mcset fr Filter Filtre
::msgcat::mcset fr {Find Next} {Trouver le suivant}
::msgcat::mcset fr Find Trouver
::msgcat::mcset fr {First Block} {First Block}
::msgcat::mcset fr {First Frame} {Première fenêtre}
::msgcat::mcset fr First Premier
::msgcat::mcset fr Fits Fits
::msgcat::mcset fr {Fixed in Size} {Taille fixée}
::msgcat::mcset fr Flip Flip
::msgcat::mcset fr Font Police
::msgcat::mcset fr {Footprint Servers} {Footprint Servers}
::msgcat::mcset fr Footprint Footprint
::msgcat::mcset fr {For more information, use --help} {For more information, use --help}
::msgcat::mcset fr Foreground Foreground
::msgcat::mcset fr Forground Forground
::msgcat::mcset fr Format Format
::msgcat::mcset fr Forward {En avant}
::msgcat::mcset fr {Found Auto Backup, restore?} {Found Auto Backup, restore?}
::msgcat::mcset fr Found Trouvé
::msgcat::mcset fr {Frame Information} {Information de la fenêtre }
::msgcat::mcset fr {Frame Layout} {Frame Layout}
::msgcat::mcset fr {Frame Parameters} {Frame Parameters}
::msgcat::mcset fr Frames Frames
::msgcat::mcset fr Frame Fenêtre
::msgcat::mcset fr From From
::msgcat::mcset fr Front Avant
::msgcat::mcset fr {Full Range} {Full Range}
::msgcat::mcset fr Function Fonction
::msgcat::mcset fr GIF GIF
::msgcat::mcset fr GUI GUI
::msgcat::mcset fr Galactic Galactiques
::msgcat::mcset fr Gap Gap
::msgcat::mcset fr Gaussian Gaussien
::msgcat::mcset fr General Général
::msgcat::mcset fr Generate Générer
::msgcat::mcset fr {Generating Regions} {Création des régions}
::msgcat::mcset fr {Get Information} {Récuperer l'information}
::msgcat::mcset fr {Get Region Info} {Get Region Info}
::msgcat::mcset fr Gist Gist
::msgcat::mcset fr {Global Properties} {Global Properties}
::msgcat::mcset fr Global Global
::msgcat::mcset fr {Goto First Frame} {Goto First Frame}
::msgcat::mcset fr {Goto Frame} {Aller à la fenêtre}
::msgcat::mcset fr {Goto Last Frame} {Goto Last Frame}
::msgcat::mcset fr {Goto Next Frame} {Goto Next Frame}
::msgcat::mcset fr {Goto Previous Frame} {Goto Previous Frame}
::msgcat::mcset fr {Goto Row} {Goto Row}
::msgcat::mcset fr Goto Goto
::msgcat::mcset fr {Graph Horz} {Graph Horz}
::msgcat::mcset fr {Graph Parameters} {Graph Parameters}
::msgcat::mcset fr {Graph Vert} {Graph Vert}
::msgcat::mcset fr Graphics Graphiques
::msgcat::mcset fr Graphs Graphs
::msgcat::mcset fr Graph Graph
::msgcat::mcset fr Grayscale {Niveaux de gris}
::msgcat::mcset fr Green Vert
::msgcat::mcset fr {Grid Gap} {Espacement de la grille}
::msgcat::mcset fr Grid Grille
::msgcat::mcset fr Groups Groupes
::msgcat::mcset fr {HLS Array} {HLS Array}
::msgcat::mcset fr {HLS Cube} {HLS Cube}
::msgcat::mcset fr {HLS Image} {HLS Image}
::msgcat::mcset fr HLS HLS
::msgcat::mcset fr HMS HMS
::msgcat::mcset fr {HSV Array} {HSV Array}
::msgcat::mcset fr {HSV Cube} {HSV Cube}
::msgcat::mcset fr {HSV Image} {HSV Image}
::msgcat::mcset fr HSV HSV
::msgcat::mcset fr HTTP HTTP
::msgcat::mcset fr Header Entête
::msgcat::mcset fr Height Hauteur
::msgcat::mcset fr {Help Desk} Contacts
::msgcat::mcset fr {Help Me Choose} {Aider moi}
::msgcat::mcset fr Help Aide
::msgcat::mcset fr {Hide All} {Cacher tous}
::msgcat::mcset fr Highlite Highlite
::msgcat::mcset fr High Haut
::msgcat::mcset fr {Histogram Equalization} {Egalisation via Histogramme}
::msgcat::mcset fr Histogram Histogramme
::msgcat::mcset fr {Horizontal Graph} {Graphique Horizontal}
::msgcat::mcset fr {Horizontal Layout} {Mise en page Horizontale}
::msgcat::mcset fr Horizontal Horizontal
::msgcat::mcset fr {Hub not running} {Hub not running}
::msgcat::mcset fr Hue Hue
::msgcat::mcset fr {IAU Location Code} {IAU Location Code}
::msgcat::mcset fr ICRS ICRS
::msgcat::mcset fr Icons Icons
::msgcat::mcset fr Identification Identification
::msgcat::mcset fr If Si
::msgcat::mcset fr Illustrate Illustrate
::msgcat::mcset fr {Image Servers} {Image Servers}
::msgcat::mcset fr Image Image
::msgcat::mcset fr {Import Array} {Import Array}
::msgcat::mcset fr {Import ENVI} {Import ENVI}
::msgcat::mcset fr {Import GIF} {Import GIF}
::msgcat::mcset fr {Import HLS Array} {Import HLS Array}
::msgcat::mcset fr {Import HSV Array} {Import HSV Array}
::msgcat::mcset fr {Import JPEG} {Import JPEG}
::msgcat::mcset fr {Import NRRD} {Import NRRD}
::msgcat::mcset fr {Import PNG} {Import PNG}
::msgcat::mcset fr {Import RGB Array} {Import RGB Array}
::msgcat::mcset fr {Import Slice GIF} {Import Slice GIF}
::msgcat::mcset fr {Import Slice JPEG} {Import Slice JPEG}
::msgcat::mcset fr {Import Slice PNG} {Import Slice PNG}
::msgcat::mcset fr {Import Slice TIFF} {Import Slice TIFF}
::msgcat::mcset fr {Import TIFF} {Import TIFF}
::msgcat::mcset fr Import Import
::msgcat::mcset fr Include Inclure
::msgcat::mcset fr {Increase Bin} {Increase Bin}
::msgcat::mcset fr {Increase Block} {Increase Block}
::msgcat::mcset fr {Increase Magnification} {Increase Magnification}
::msgcat::mcset fr {Increase Zoom} {Increase Zoom}
::msgcat::mcset fr Increase Augmenter
::msgcat::mcset fr {Info Box} {Info Box}
::msgcat::mcset fr {Information Panel} {Panneau de reseignement}
::msgcat::mcset fr Information Reseignement
::msgcat::mcset fr {Initialize XPA} {Initialiser XPA}
::msgcat::mcset fr Inner Intérieur
::msgcat::mcset fr {Instrument FOV} {Profondeur de champ de l'instrument}
::msgcat::mcset fr Instrument Instrument
::msgcat::mcset fr {Interior Axes} {Axes intérieur}
::msgcat::mcset fr {Interior Numerics} {Chiffres intérieur}
::msgcat::mcset fr {Internal Parse Error} {Internal Parse Error}
::msgcat::mcset fr Interval Intervalle
::msgcat::mcset fr {Invalid Column Name} {Invalid Column Name}
::msgcat::mcset fr {Invalid WCS} {Invalid WCS}
::msgcat::mcset fr {Invalid formated multipart/mixed mime type message} {Message invalide de genre mixte/multipart}
::msgcat::mcset fr {Invert Colormap} {Plan de couleur inverti}
::msgcat::mcset fr Invert Invertir
::msgcat::mcset fr Italic Italique
::msgcat::mcset fr {Items Found} {Articles trouvés}
::msgcat::mcset fr Iteration Iteration
::msgcat::mcset fr {JPEG Quality Factor} {Le facteur de qualité JPEG}
::msgcat::mcset fr JPEG JPEG
::msgcat::mcset fr Justify Justify
::msgcat::mcset fr Keep-Alive Keep-Alive
::msgcat::mcset fr Keyword Keyword
::msgcat::mcset fr Labels Étiquettes
::msgcat::mcset fr Label Étiquette
::msgcat::mcset fr Landscape Paysage
::msgcat::mcset fr Language Langue
::msgcat::mcset fr {Last Block} {Last Block}
::msgcat::mcset fr {Last Frame} {Dernière fenêtre}
::msgcat::mcset fr Last Dernier
::msgcat::mcset fr Layout Layout
::msgcat::mcset fr Left Left
::msgcat::mcset fr Legal Legale
::msgcat::mcset fr {Legend Position} {Legend Position}
::msgcat::mcset fr {Legend Title} {Legend Title}
::msgcat::mcset fr Legend Legend
::msgcat::mcset fr Length Longeur
::msgcat::mcset fr Letter Lettre
::msgcat::mcset fr Levels Niveaux
::msgcat::mcset fr Level Niveau
::msgcat::mcset fr Lighten Lighten
::msgcat::mcset fr Lightness Lightness
::msgcat::mcset fr Limits Limites
::msgcat::mcset fr {Line Dataset} {Line Dataset}
::msgcat::mcset fr {Line Plot Tool} {Line Plot Tool}
::msgcat::mcset fr Linear Linéaire
::msgcat::mcset fr Line Ligne
::msgcat::mcset fr {List Data} {List Data}
::msgcat::mcset fr {List Regions} {Énumérer les régions}
::msgcat::mcset fr {List Region} {List Region}
::msgcat::mcset fr {List Selection} {List Selection}
::msgcat::mcset fr {List Select} {List Select}
::msgcat::mcset fr List Énumérer
::msgcat::mcset fr {Load Analysis Commands} {Charger le commandes d'analyse}
::msgcat::mcset fr {Load Color Tags} {Load Color Tags}
::msgcat::mcset fr {Load Contour Levels} {Charger les niveaux de contour}
::msgcat::mcset fr {Load Contrast/Bias} {Charger le contraste/inclination}
::msgcat::mcset fr {Load Data} {Charger les données}
::msgcat::mcset fr {Load Mosaic} {Charger le mosaïque}
::msgcat::mcset fr {Load Template} {Charger le patron}
::msgcat::mcset fr {Load into All} {Load into All}
::msgcat::mcset fr {Load into Current} {Load into Current}
::msgcat::mcset fr {Loading Catalog} {Loading Catalog}
::msgcat::mcset fr Loading Loading
::msgcat::mcset fr Load Charger
::msgcat::mcset fr Local Locale
::msgcat::mcset fr {Lock Axes} {Lock Axes}
::msgcat::mcset fr {Lock Bin} {Lock Bin}
::msgcat::mcset fr {Lock Color} {Lock Color}
::msgcat::mcset fr {Lock Crop Amplifier} {Lock Crop Amplifier}
::msgcat::mcset fr {Lock Crop Detector} {Lock Crop Detector}
::msgcat::mcset fr {Lock Crop Image} {Lock Crop Image}
::msgcat::mcset fr {Lock Crop None} {Lock Crop None}
::msgcat::mcset fr {Lock Crop Physical} {Lock Crop Physical}
::msgcat::mcset fr {Lock Crop WCS} {Lock Crop WCS}
::msgcat::mcset fr {Lock Crosshair Amplifier} {Lock Crosshair Amplifier}
::msgcat::mcset fr {Lock Crosshair Detector} {Lock Crosshair Detector}
::msgcat::mcset fr {Lock Crosshair Image} {Lock Crosshair Image}
::msgcat::mcset fr {Lock Crosshair None} {Lock Crosshair None}
::msgcat::mcset fr {Lock Crosshair Physical} {Lock Crosshair Physical}
::msgcat::mcset fr {Lock Crosshair WCS} {Lock Crosshair WCS}
::msgcat::mcset fr {Lock Frame Amplifier} {Lock Frame Amplifier}
::msgcat::mcset fr {Lock Frame Detector} {Lock Frame Detector}
::msgcat::mcset fr {Lock Frame Image} {Lock Frame Image}
::msgcat::mcset fr {Lock Frame None} {Lock Frame None}
::msgcat::mcset fr {Lock Frame Physical} {Lock Frame Physical}
::msgcat::mcset fr {Lock Frame WCS} {Lock Frame WCS}
::msgcat::mcset fr {Lock Limits} {Lock Limits}
::msgcat::mcset fr {Lock Scale} {Lock Scale}
::msgcat::mcset fr {Lock Slice Image} {Lock Slice Image}
::msgcat::mcset fr {Lock Slice None} {Lock Slice None}
::msgcat::mcset fr {Lock Slice WCS} {Lock Slice WCS}
::msgcat::mcset fr {Lock Smooth} {Lock Smooth}
::msgcat::mcset fr Lock Verrouiller
::msgcat::mcset fr {Log Exponent} {Log Exponent}
::msgcat::mcset fr Log Log
::msgcat::mcset fr {Low High} {Haut bas}
::msgcat::mcset fr {Lower Left Back} {Lower Left Back}
::msgcat::mcset fr {Lower Left Front} {Lower Left Front}
::msgcat::mcset fr {Lower Right Back} {Lower Right Back}
::msgcat::mcset fr {Lower Right Front} {Lower Right Front}
::msgcat::mcset fr Low Bas
::msgcat::mcset fr MIP MIP
::msgcat::mcset fr Magenta Magenta
::msgcat::mcset fr Magnification Magnification
::msgcat::mcset fr Magnifier Magnificateur
::msgcat::mcset fr {Major Radius} {Major Radius}
::msgcat::mcset fr {Major Sigma} {Major Sigma}
::msgcat::mcset fr Major Majeure
::msgcat::mcset fr Manual Manual
::msgcat::mcset fr {Mask Parameters} {Paramètres de masque}
::msgcat::mcset fr {Match Axes} {Match Axes}
::msgcat::mcset fr {Match Bin} {Match Bin}
::msgcat::mcset fr {Match Catalog requires at least 1 row per catalog} {Match Catalog requires at least 1 row per catalog}
::msgcat::mcset fr {Match Color} {Match Color}
::msgcat::mcset fr {Match Crop Amplifier} {Match Crop Amplifier}
::msgcat::mcset fr {Match Crop Detector} {Match Crop Detector}
::msgcat::mcset fr {Match Crop Image} {Match Crop Image}
::msgcat::mcset fr {Match Crop Physical} {Match Crop Physical}
::msgcat::mcset fr {Match Crop WCS} {Match Crop WCS}
::msgcat::mcset fr {Match Crosshair Amplifier} {Match Crosshair Amplifier}
::msgcat::mcset fr {Match Crosshair Detector} {Match Crosshair Detector}
::msgcat::mcset fr {Match Crosshair Image} {Match Crosshair Image}
::msgcat::mcset fr {Match Crosshair Physical} {Match Crosshair Physical}
::msgcat::mcset fr {Match Crosshair WCS} {Match Crosshair WCS}
::msgcat::mcset fr {Match Frame Amplifier} {Match Frame Amplifier}
::msgcat::mcset fr {Match Frame Detector} {Match Frame Detector}
::msgcat::mcset fr {Match Frame Image} {Match Frame Image}
::msgcat::mcset fr {Match Frame Physical} {Match Frame Physical}
::msgcat::mcset fr {Match Frame WCS} {Match Frame WCS}
::msgcat::mcset fr {Match Frames on WCS} {Match Frames on WCS}
::msgcat::mcset fr {Match Limits} {Match Limits}
::msgcat::mcset fr {Match Scale} {Match Scale}
::msgcat::mcset fr {Match Slice Image} {Match Slice Image}
::msgcat::mcset fr {Match Slice WCS} {Match Slice WCS}
::msgcat::mcset fr {Match Smooth} {Match Smooth}
::msgcat::mcset fr Match Match
::msgcat::mcset fr {Math Function} {Fonction mathématique}
::msgcat::mcset fr {Matplotlib Cyclic} {Matplotlib Cyclic}
::msgcat::mcset fr {Matplotlib Diverging} {Matplotlib Diverging}
::msgcat::mcset fr {Matplotlib Sequential} {Matplotlib Sequential}
::msgcat::mcset fr {Matplotlib Uniform} {Matplotlib Uniform}
::msgcat::mcset fr {Max Rows} {Maximum de rangées}
::msgcat::mcset fr Maximum Maximum
::msgcat::mcset fr Max Maximum
::msgcat::mcset fr Median Median
::msgcat::mcset fr {Menus and Buttons} {Menus and Buttons}
::msgcat::mcset fr Menu Menu
::msgcat::mcset fr {Message Log} {Message Log}
::msgcat::mcset fr Metadata Metadata
::msgcat::mcset fr Method Méthode
::msgcat::mcset fr {Min Max Parameters} {Min Max Parameters}
::msgcat::mcset fr {Min Max} {Min Max}
::msgcat::mcset fr Minimum Minimum
::msgcat::mcset fr {Minor Radius} {Minor Radius}
::msgcat::mcset fr {Minor Sigma} {Minor Sigma}
::msgcat::mcset fr Minor Mineure
::msgcat::mcset fr Minutes Minutes
::msgcat::mcset fr Min Minimum
::msgcat::mcset fr Mission Mission
::msgcat::mcset fr Mode Mode
::msgcat::mcset fr {Mosaic IRAF Segment} {Mosaic IRAF Segment}
::msgcat::mcset fr {Mosaic IRAF} {Mosaic IRAF}
::msgcat::mcset fr {Mosaic WCS Segment} {Mosaic WCS Segment}
::msgcat::mcset fr {Mosaic WCS} {Mosaic WCS}
::msgcat::mcset fr {Mosaic WFPC2} {Mosaic WFPC2}
::msgcat::mcset fr Mosaic Mosaic
::msgcat::mcset fr {Mouse Click Epsilon} {Mouse Click Epsilon}
::msgcat::mcset fr {Mouse Wheel Bin} {Mouse Wheel Bin}
::msgcat::mcset fr {Mouse Wheel Zoom} {Mouse Wheel Zoom}
::msgcat::mcset fr {Move Back} {Move Back}
::msgcat::mcset fr {Move First} {Move First}
::msgcat::mcset fr {Move Forward} {Move Forward}
::msgcat::mcset fr {Move Frame} {Move Frame}
::msgcat::mcset fr {Move Front} {Move Front}
::msgcat::mcset fr {Move Last} {Move Last}
::msgcat::mcset fr {Move to Back} {Bouger vers arrière}
::msgcat::mcset fr {Move to Front} {Bouger vers le devant}
::msgcat::mcset fr Movie Movie
::msgcat::mcset fr {Muliple Extension Cube} {Muliple Extension Cube}
::msgcat::mcset fr {Muliple Extension Frames} {Muliple Extension Frames}
::msgcat::mcset fr {Multi Colorbars} {Multi Colorbars}
::msgcat::mcset fr {Multiple Colorbars} {Multiple Colorbars}
::msgcat::mcset fr {Multiple Extension Cube} {Multiple Extension Cube}
::msgcat::mcset fr {Multiple Extension Frames} {Multiple Extension Frames}
::msgcat::mcset fr {Multiple WCS} {Multiple WCS}
::msgcat::mcset fr NAN NAN
::msgcat::mcset fr NRRD NRRD
::msgcat::mcset fr {Name Resolution} {Nom de la résolution}
::msgcat::mcset fr {Name Server} {Nom du Serveur}
::msgcat::mcset fr {Name or Designation} {Nom ou Désignation}
::msgcat::mcset fr Name Name
::msgcat::mcset fr {Native Dialog} {Native Dialog}
::msgcat::mcset fr {New Features} {Nouvelles options}
::msgcat::mcset fr {New Frame 3D} {New Frame 3D}
::msgcat::mcset fr {New Frame HLS} {New Frame HLS}
::msgcat::mcset fr {New Frame HSV} {New Frame HSV}
::msgcat::mcset fr {New Frame RGB} {Nouvelle fenêtre RGB}
::msgcat::mcset fr {New Frame each Time} {Nouvelle fenêtre à chaque fois}
::msgcat::mcset fr {New Frame} {Nouvelle fenêtre}
::msgcat::mcset fr {New Graph} {New Graph}
::msgcat::mcset fr {New Group} {Nouveau groupe}
::msgcat::mcset fr {New Plot} {New Plot}
::msgcat::mcset fr New Nouveau
::msgcat::mcset fr {Next Block} {Next Block}
::msgcat::mcset fr {Next Frame} {Fenêtre suivante}
::msgcat::mcset fr Next Suivant
::msgcat::mcset fr {No Catalog specified} {Pas de Catalogue spécifié}
::msgcat::mcset fr {No Data Available} {No Data Available}
::msgcat::mcset fr {No Items Found} {Pas trouvé}
::msgcat::mcset fr Non-NAN Non-NAN
::msgcat::mcset fr Non-Zero Non-Zero
::msgcat::mcset fr None Rien
::msgcat::mcset fr Normal Normal
::msgcat::mcset fr North Nord
::msgcat::mcset fr {Not Found} {Not Found}
::msgcat::mcset fr {Not Supported} {Not Supported}
::msgcat::mcset fr {Not valid export format} {Not valid export format}
::msgcat::mcset fr Notes Notes
::msgcat::mcset fr {Number of Samples} {Nombre d'échantillons}
::msgcat::mcset fr {Number of Threads} {Number of Threads}
::msgcat::mcset fr {Number of Ticks} {Number of Ticks}
::msgcat::mcset fr Number Nombre
::msgcat::mcset fr Numerics Chiffres
::msgcat::mcset fr OK OK
::msgcat::mcset fr Object Objet
::msgcat::mcset fr ObsId ObsId
::msgcat::mcset fr {Open File} {Ouvrir fichier}
::msgcat::mcset fr {Open HLS Cube} {Open HLS Cube}
::msgcat::mcset fr {Open HLS Image} {Open HLS Image}
::msgcat::mcset fr {Open HSV Cube} {Open HSV Cube}
::msgcat::mcset fr {Open HSV Image} {Open HSV Image}
::msgcat::mcset fr {Open ME Cube} {Open ME Cube}
::msgcat::mcset fr {Open ME Frames} {Open ME Frames}
::msgcat::mcset fr {Open Mosaic IRAF Seg} {Open Mosaic IRAF Seg}
::msgcat::mcset fr {Open Mosaic IRAF} {Open Mosaic IRAF}
::msgcat::mcset fr {Open Mosaic WCS Seg} {Open Mosaic WCS Seg}
::msgcat::mcset fr {Open Mosaic WCS} {Open Mosaic WCS}
::msgcat::mcset fr {Open Mosaic WFPC2} {Open Mosaic WFPC2}
::msgcat::mcset fr {Open Notepad} {Open Notepad}
::msgcat::mcset fr {Open Prism} {Open Prism}
::msgcat::mcset fr {Open RGB Cube} {Open RGB Cube}
::msgcat::mcset fr {Open RGB Image} {Open RGB Image}
::msgcat::mcset fr {Open Region File} {Open Region File}
::msgcat::mcset fr {Open Regions} {Open Regions}
::msgcat::mcset fr {Open Slice} {Open Slice}
::msgcat::mcset fr {Open TCL Console} {Open TCL Console}
::msgcat::mcset fr {Open URL} {Ouvrir un URL}
::msgcat::mcset fr {Open as} {Open as}
::msgcat::mcset fr Open Ouvrir
::msgcat::mcset fr Operator Operateur
::msgcat::mcset fr Orientation Orientation
::msgcat::mcset fr Origin Origin
::msgcat::mcset fr Oscillate Oscillate
::msgcat::mcset fr {Other Color} {Other Color}
::msgcat::mcset fr {Other Font Size} {Other Font Size}
::msgcat::mcset fr Other Autre
::msgcat::mcset fr Outer Externe
::msgcat::mcset fr Overplot Overplot
::msgcat::mcset fr {Override Color} {Override Color}
::msgcat::mcset fr PNG PNG
::msgcat::mcset fr {PS Page Setup} {PS Page Setup}
::msgcat::mcset fr {PS Print} {PS Print}
::msgcat::mcset fr {Page Setup} {Configurer la Page}
::msgcat::mcset fr {Page Source} {Source de la Page}
::msgcat::mcset fr {Pan To} {Pan To}
::msgcat::mcset fr {Pan Zoom Rotate Parameters} {Pan Zoom Rotate Parameters}
::msgcat::mcset fr {Pan Zoom} {Pan Zoom}
::msgcat::mcset fr {Pan then Zoom} {Pan then Zoom}
::msgcat::mcset fr {Pan to Center} {Pan to Center}
::msgcat::mcset fr Panda Panda
::msgcat::mcset fr Panner Panner
::msgcat::mcset fr Pan Pan
::msgcat::mcset fr Parameters Paramètres
::msgcat::mcset fr Password {Mot de passe}
::msgcat::mcset fr {Paste Contours} {Coller les contours}
::msgcat::mcset fr Paste Coller
::msgcat::mcset fr Percent Percent
::msgcat::mcset fr Physical Physique
::msgcat::mcset fr {Pixel Distribution} {Distribution des pixels}
::msgcat::mcset fr {Pixel Size} {Taille des pixels}
::msgcat::mcset fr {Pixel Table} {Table des pixels}
::msgcat::mcset fr Pixels Pixels
::msgcat::mcset fr Planets Planets
::msgcat::mcset fr Play Jouer
::msgcat::mcset fr {Please Select a Region} {Please Select a Region}
::msgcat::mcset fr {Please change the file's permission to disable other users write access. Use anyway?} {Please change the file's permission to disable other users write access. Use anyway?}
::msgcat::mcset fr {Please specify instruments} {Please specify instruments}
::msgcat::mcset fr {Please specify radius and either name or (ra,dec)} {Please specify radius and either name or (ra,dec)}
::msgcat::mcset fr {Please specify width, height, and either name or (ra,dec)} {Specifiez largeur, longeur, et autre noms possibles ou (ra,dec)}
::msgcat::mcset fr {Plot 2D} {Plot 2D}
::msgcat::mcset fr {Plot 3D} {Plot 3D}
::msgcat::mcset fr {Plot Area} {Plot Area}
::msgcat::mcset fr {Plot Control Panel} {Plot Control Panel}
::msgcat::mcset fr {Plot Tool} {Plot Tool}
::msgcat::mcset fr {Plotting Regions} {Tracer les régions}
::msgcat::mcset fr Plot Dessiner
::msgcat::mcset fr Plus Plus
::msgcat::mcset fr Pointer Pointeur
::msgcat::mcset fr Points Points
::msgcat::mcset fr Point Point
::msgcat::mcset fr Polygon Polygone
::msgcat::mcset fr Portrait Portrait
::msgcat::mcset fr Position Position
::msgcat::mcset fr Poster Poster
::msgcat::mcset fr Postscript Postscript
::msgcat::mcset fr Power Puissance
::msgcat::mcset fr Precision Precision
::msgcat::mcset fr Preferences Préférences
::msgcat::mcset fr {Preserve During Load} {Préserver pendant le chargement}
::msgcat::mcset fr {Previous Block} {Previous Block}
::msgcat::mcset fr {Previous Frame} {Fenêtre précédente}
::msgcat::mcset fr Previous Précédent
::msgcat::mcset fr Prev Prev
::msgcat::mcset fr {Print Coordinates} {Imprimer les coordonnees}
::msgcat::mcset fr {Print To} {Imprimer dans}
::msgcat::mcset fr Printer L'imprimante
::msgcat::mcset fr Print Imprimer
::msgcat::mcset fr {Prism Goto} {Prism Goto}
::msgcat::mcset fr Prism Prism
::msgcat::mcset fr Projection Projection
::msgcat::mcset fr Properties Propriétés
::msgcat::mcset fr Property Propriété
::msgcat::mcset fr {Proxy Host} {Proxy Host}
::msgcat::mcset fr {Proxy Port} {Proxy Port}
::msgcat::mcset fr {Public ID} {Public ID}
::msgcat::mcset fr Publication Publication
::msgcat::mcset fr Quadratic Quadratic
::msgcat::mcset fr RDB RDB
::msgcat::mcset fr {RGB Array} {RGB Array}
::msgcat::mcset fr {RGB Cube} {RGB Cube}
::msgcat::mcset fr {RGB Image} {RGB Image}
::msgcat::mcset fr RGB RGB
::msgcat::mcset fr {Radial Profile} {Radial Profile}
::msgcat::mcset fr Radius Radius
::msgcat::mcset fr Range Range
::msgcat::mcset fr Redo Refaire
::msgcat::mcset fr Red Red
::msgcat::mcset fr {Reference Manual} {Reference Manual}
::msgcat::mcset fr Reference Reference
::msgcat::mcset fr {Refresh Frame} {Refresh Frame}
::msgcat::mcset fr Refresh Refresh
::msgcat::mcset fr {Region Color} {Region Color}
::msgcat::mcset fr {Region Line Width} {Region Line Width}
::msgcat::mcset fr {Region Parameters} {Region Parameters}
::msgcat::mcset fr {Region Shape} {Region Shape}
::msgcat::mcset fr Region Région
::msgcat::mcset fr Registration Registration
::msgcat::mcset fr {Release Notes} {Release Notes}
::msgcat::mcset fr Release Release
::msgcat::mcset fr Reload Reload
::msgcat::mcset fr Render Render
::msgcat::mcset fr Repeat Repeat
::msgcat::mcset fr {Reset Colormap} {Reset Colormap}
::msgcat::mcset fr {Reset Frame} {Reset Frame}
::msgcat::mcset fr Reset Reset
::msgcat::mcset fr Restore Restore
::msgcat::mcset fr Retrieve Retrieve
::msgcat::mcset fr Return Return
::msgcat::mcset fr Right Right
::msgcat::mcset fr Roman Roman
::msgcat::mcset fr Rotate Rotate
::msgcat::mcset fr Rows Rows
::msgcat::mcset fr Row Row
::msgcat::mcset fr Ruler Ruler
::msgcat::mcset fr {SAMP Connect} {SAMP Connect}
::msgcat::mcset fr {SAMP Disconnect} {SAMP Disconnect}
::msgcat::mcset fr {SAMP Hub Start} {SAMP Hub Start}
::msgcat::mcset fr {SAMP Hub Stop} {SAMP Hub Stop}
::msgcat::mcset fr {SAMP Hub} {SAMP Hub}
::msgcat::mcset fr {SAMP Table} {SAMP Table}
::msgcat::mcset fr {SAMP WebHub Start} {SAMP WebHub Start}
::msgcat::mcset fr {SAMP: not connected} {SAMP: not connected}
::msgcat::mcset fr SAMP SAMP
::msgcat::mcset fr {Sample Increment} {Sample Increment}
::msgcat::mcset fr {Sample Parameters} {Sample Parameters}
::msgcat::mcset fr {Samples per Line} {Samples per Line}
::msgcat::mcset fr Sample Sample
::msgcat::mcset fr Saturation Saturation
::msgcat::mcset fr {Save 3D Movie} {Save 3D Movie}
::msgcat::mcset fr {Save Color Tags} {Save Color Tags}
::msgcat::mcset fr {Save Contour Levels} {Save Contour Levels}
::msgcat::mcset fr {Save Contrast/Bias} {Save Contrast/Bias}
::msgcat::mcset fr {Save Data} {Save Data}
::msgcat::mcset fr {Save HLS Cube} {Save HLS Cube}
::msgcat::mcset fr {Save HLS Image} {Save HLS Image}
::msgcat::mcset fr {Save HSV Cube} {Save HSV Cube}
::msgcat::mcset fr {Save HSV Image} {Save HSV Image}
::msgcat::mcset fr {Save Image EPS} {Save Image EPS}
::msgcat::mcset fr {Save Image FITS} {Save Image FITS}
::msgcat::mcset fr {Save Image GIF} {Save Image GIF}
::msgcat::mcset fr {Save Image JPEG} {Save Image JPEG}
::msgcat::mcset fr {Save Image PNG} {Save Image PNG}
::msgcat::mcset fr {Save Image TIFF} {Save Image TIFF}
::msgcat::mcset fr {Save Image on Download} {Save Image on Download}
::msgcat::mcset fr {Save Image} {Save Image}
::msgcat::mcset fr {Save ME Cube} {Save ME Cube}
::msgcat::mcset fr {Save Mosaic WCS Seg} {Save Mosaic WCS Seg}
::msgcat::mcset fr {Save Mosaic WCS} {Save Mosaic WCS}
::msgcat::mcset fr {Save RGB Cube} {Save RGB Cube}
::msgcat::mcset fr {Save RGB Image} {Save RGB Image}
::msgcat::mcset fr {Save Region File} {Save Region File}
::msgcat::mcset fr {Save Regions} {Save Regions}
::msgcat::mcset fr {Save Selection} {Save Selection}
::msgcat::mcset fr {Save Select} {Save Select}
::msgcat::mcset fr {Save Slice} {Save Slice}
::msgcat::mcset fr {Save Template} {Save Template}
::msgcat::mcset fr {Save as EPS} {Save as EPS}
::msgcat::mcset fr {Save as PNG} {Save as PNG}
::msgcat::mcset fr {Save as} {Save as}
::msgcat::mcset fr Save Enregistrer
::msgcat::mcset fr {Scale Parameters} {Scale Parameters}
::msgcat::mcset fr {Scale and Limits} {Scale and Limits}
::msgcat::mcset fr Scale Scale
::msgcat::mcset fr {Scaling Option} {Scaling Option}
::msgcat::mcset fr {Scaling Parameters} {Scaling Parameters}
::msgcat::mcset fr Scan Scan
::msgcat::mcset fr {Scatter Dataset} {Scatter Dataset}
::msgcat::mcset fr {Scatter Plot Tool} {Scatter Plot Tool}
::msgcat::mcset fr {Scientific Colour Maps} {Scientific Colour Maps}
::msgcat::mcset fr Scope Scope
::msgcat::mcset fr Screen Screen
::msgcat::mcset fr {Search for Catalogs} {Search for Catalogs}
::msgcat::mcset fr Seconds Seconds
::msgcat::mcset fr Second Second
::msgcat::mcset fr Segment Segment
::msgcat::mcset fr {Select All} {Select All}
::msgcat::mcset fr {Select Coordinate System } {Select Coordinate System }
::msgcat::mcset fr {Select Dataset} {Select Dataset}
::msgcat::mcset fr {Select Datatset} {Select Datatset}
::msgcat::mcset fr {Select Graph} {Select Graph}
::msgcat::mcset fr {Select None} {Select None}
::msgcat::mcset fr {Send to Back} {Send to Back}
::msgcat::mcset fr Send Send
::msgcat::mcset fr Server Server
::msgcat::mcset fr {Set Bin to 1} {Set Bin to 1}
::msgcat::mcset fr {Set Block to 1} {Set Block to 1}
::msgcat::mcset fr {Set Zoom to 1} {Set Zoom to 1}
::msgcat::mcset fr Sexagesimal Sexagesimal
::msgcat::mcset fr Shadow Shadow
::msgcat::mcset fr Shape Shape
::msgcat::mcset fr {Show All} {Montrer tous}
::msgcat::mcset fr {Show Command} {Show Command}
::msgcat::mcset fr {Show Compass} {Show Compass}
::msgcat::mcset fr {Show Legend} {Show Legend}
::msgcat::mcset fr {Show Text} {Show Text}
::msgcat::mcset fr {Show/Hide Frames} {Montrer/Cacher les fenêtres}
::msgcat::mcset fr Show Show
::msgcat::mcset fr {Simple Cross} {Simple Cross}
::msgcat::mcset fr {Simple Image Access} {Simple Image Access}
::msgcat::mcset fr {Simple Plus} {Simple Plus}
::msgcat::mcset fr {Single Frame} {Single Frame}
::msgcat::mcset fr Single Single
::msgcat::mcset fr Sites Sites
::msgcat::mcset fr Size/Radius Size/Radius
::msgcat::mcset fr Size Size
::msgcat::mcset fr {Skip First} {Skip First}
::msgcat::mcset fr Slice Slice
::msgcat::mcset fr {Smooth Parameters} {Smooth Parameters}
::msgcat::mcset fr Smoothness Smoothness
::msgcat::mcset fr Smooth Smooth
::msgcat::mcset fr {Sorry, DS9 does not support} {Sorry, DS9 does not support}
::msgcat::mcset fr {Sorry, DS9 requires a Truecolor8, Truecolor16, Truecolor24 visual be available} {Sorry, DS9 requires a Truecolor8, Truecolor16, Truecolor24 visual be available}
::msgcat::mcset fr Sort Sort
::msgcat::mcset fr {Source TCL} {Source TCL}
::msgcat::mcset fr Source Source
::msgcat::mcset fr {Space Equal Distance} {Space Equal Distance}
::msgcat::mcset fr {Space Equal Value} {Space Equal Value}
::msgcat::mcset fr Spacing Spacing
::msgcat::mcset fr Sqrt Sqrt
::msgcat::mcset fr {Square Root} {Square Root}
::msgcat::mcset fr Squared Squared
::msgcat::mcset fr Square Square
::msgcat::mcset fr Starbase Starbase
::msgcat::mcset fr Startup Startup
::msgcat::mcset fr Start Start
::msgcat::mcset fr Statistics Statistics
::msgcat::mcset fr Status Status
::msgcat::mcset fr Step Step
::msgcat::mcset fr Stop Stop
::msgcat::mcset fr {Story of SAOImageDS9} {Story of SAOImageDS9}
::msgcat::mcset fr Story Story
::msgcat::mcset fr {Strip Parameters} {Strip Parameters}
::msgcat::mcset fr {Strip Scale} {Strip Scale}
::msgcat::mcset fr Strip Strip
::msgcat::mcset fr Subscriptions Subscriptions
::msgcat::mcset fr Sum Sum
::msgcat::mcset fr {Symbol Editor} {Symbol Editor}
::msgcat::mcset fr Symbol Symbol
::msgcat::mcset fr TIFF TIFF
::msgcat::mcset fr TSV TSV
::msgcat::mcset fr Tab-Separated-Value Tab-Separated-Value
::msgcat::mcset fr Table Table
::msgcat::mcset fr Tabloid Tabloid
::msgcat::mcset fr {Tag Color} {Tag Color}
::msgcat::mcset fr {Tag New Region Group} {Tag New Region Group}
::msgcat::mcset fr Template Template
::msgcat::mcset fr Text Texte
::msgcat::mcset fr Theme Theme
::msgcat::mcset fr Then Then
::msgcat::mcset fr Thickness Thickness
::msgcat::mcset fr {This analysis task is already running. Do you wish to kill it?} {This analysis task is already running. Do you wish to kill it?}
::msgcat::mcset fr {This function is not available.} {This function is not available.}
::msgcat::mcset fr {This function is not currently supported for this port.} {This function is not currently supported for this port.}
::msgcat::mcset fr Tickmarks Tickmarks
::msgcat::mcset fr {Tile Frames} {Tile Frames}
::msgcat::mcset fr {Tile Parameters} {Tile Parameters}
::msgcat::mcset fr Tile Tile
::msgcat::mcset fr Times Times
::msgcat::mcset fr Titles Titles
::msgcat::mcset fr Title Title
::msgcat::mcset fr {Toggle Colorbar} {Toggle Colorbar}
::msgcat::mcset fr {Toggle Contour} {Toggle Contour}
::msgcat::mcset fr {Toggle Coordinate Grid} {Toggle Coordinate Grid}
::msgcat::mcset fr {Toggle Horizontal Graph} {Toggle Horizontal Graph}
::msgcat::mcset fr {Toggle Include/Exclude} {Toggle Include/Exclude}
::msgcat::mcset fr {Toggle Smooth} {Toggle Smooth}
::msgcat::mcset fr {Toggle Source/Background} {Toggle Source/Background}
::msgcat::mcset fr {Toggle Vertical Graph} {Toggle Vertical Graph}
::msgcat::mcset fr Tophat Tophat
::msgcat::mcset fr Topographic Topographic
::msgcat::mcset fr Top Top
::msgcat::mcset fr To To
::msgcat::mcset fr Transition Transition
::msgcat::mcset fr Transparency Transparency
::msgcat::mcset fr Triangle Triangle
::msgcat::mcset fr Type Type
::msgcat::mcset fr URL URL
::msgcat::mcset fr {Unable to connect directly: using Web Proxy} {Unable to connect directly: using Web Proxy}
::msgcat::mcset fr {Unable to create FOV Region, celestial WCS Required} {Unable to create FOV Region, celestial WCS Required}
::msgcat::mcset fr {Unable to determine date of observation} {Unable to determine date of observation}
::msgcat::mcset fr {Unable to evaluate filter} {Unable to evaluate filter}
::msgcat::mcset fr {Unable to find Footprint window} {Unable to find Footprint window}
::msgcat::mcset fr {Unable to find PRISM window} {Unable to find PRISM window}
::msgcat::mcset fr {Unable to find SIAP window} {Unable to find SIAP window}
::msgcat::mcset fr {Unable to find URL column} {Unable to find URL column}
::msgcat::mcset fr {Unable to find catalog window} {Unable to find catalog window}
::msgcat::mcset fr {Unable to find plot window} {Unable to find plot window}
::msgcat::mcset fr {Unable to find web window} {Unable to find web window}
::msgcat::mcset fr {Unable to generate plot} {Unable to generate plot}
::msgcat::mcset fr {Unable to load FITS file} {Unable to load FITS file}
::msgcat::mcset fr {Unable to load HLS image into a non-hls frame} {Unable to load HLS image into a non-hls frame}
::msgcat::mcset fr {Unable to load HSV image into a non-hsv frame} {Unable to load HSV image into a non-hsv frame}
::msgcat::mcset fr {Unable to load RGB image into a non-rgb frame} {Unable to load RGB image into a non-rgb frame}
::msgcat::mcset fr {Unable to load compressed region file} {Unable to load compressed region file}
::msgcat::mcset fr {Unable to load plot data} {Unable to load plot data}
::msgcat::mcset fr {Unable to load region file} {Unable to load region file}
::msgcat::mcset fr {Unable to load} {Unable to load}
::msgcat::mcset fr {Unable to locate FOV Region} {Unable to locate FOV Region}
::msgcat::mcset fr {Unable to locate URL} {Unable to locate URL}
::msgcat::mcset fr {Unable to match target with XPA Mime request} {Unable to match target with XPA Mime request}
::msgcat::mcset fr {Unable to open file} {Unable to open file}
::msgcat::mcset fr {Unable to save HLS image from a non-hls frame} {Unable to save HLS image from a non-hls frame}
::msgcat::mcset fr {Unable to save HSV image from a non-hsv frame} {Unable to save HSV image from a non-hsv frame}
::msgcat::mcset fr {Unable to save RGB image from a non-rgb frame} {Unable to save RGB image from a non-rgb frame}
::msgcat::mcset fr Undo Défaire
::msgcat::mcset fr Unique Unique
::msgcat::mcset fr Units Units
::msgcat::mcset fr {Unknown Colormap} {Unknown Colormap}
::msgcat::mcset fr {Unknown command} {Unknown command}
::msgcat::mcset fr {Update Filter} {Update Filter}
::msgcat::mcset fr {Update Group} {Update Group}
::msgcat::mcset fr {Update from Current Crosshair} {Update from Current Crosshair}
::msgcat::mcset fr {Update from Current Frame} {Update from Current Frame}
::msgcat::mcset fr Update Update
::msgcat::mcset fr {Upper Left Back} {Upper Left Back}
::msgcat::mcset fr {Upper Left Front} {Upper Left Front}
::msgcat::mcset fr {Upper Right Back} {Upper Right Back}
::msgcat::mcset fr {Upper Right Front} {Upper Right Front}
::msgcat::mcset fr {Use Authentication} {Use Authentication}
::msgcat::mcset fr {Use Current Frame on Download} {Use Current Frame on Download}
::msgcat::mcset fr {Use Internal Web Browser} {Use Internal Web Browser}
::msgcat::mcset fr {Use Original Color/Width} {Use Original Color/Width}
::msgcat::mcset fr {Use Proxy} {Use Proxy}
::msgcat::mcset fr {Use Theme Colors} {Use Theme Colors}
::msgcat::mcset fr {Use background color instead of theme color} {Use background color instead of theme color}
::msgcat::mcset fr {User Manual} {User Manual}
::msgcat::mcset fr Username Username
::msgcat::mcset fr User User
::msgcat::mcset fr Use Use
::msgcat::mcset fr {VO Server} {VO Server}
::msgcat::mcset fr VOTable VOTable
::msgcat::mcset fr VOT VOT
::msgcat::mcset fr VO VO
::msgcat::mcset fr Value Value
::msgcat::mcset fr Vector Vector
::msgcat::mcset fr {Vertical Graph} {Vertical Graph}
::msgcat::mcset fr {Vertical Layout} {Vertical Layout}
::msgcat::mcset fr {Vertical Text} {Vertical Text}
::msgcat::mcset fr Vertical Vertical
::msgcat::mcset fr View Affichage
::msgcat::mcset fr {Virtual Observatory} {Virtual Observatory}
::msgcat::mcset fr {WCS Parameters} {WCS Parameters}
::msgcat::mcset fr WCS WCS
::msgcat::mcset fr Wavelength Wavelength
::msgcat::mcset fr {Web Browser} {Web Browser}
::msgcat::mcset fr White White
::msgcat::mcset fr Width Width
::msgcat::mcset fr Window Window
::msgcat::mcset fr {Words matching title, description} {Words matching title, description}
::msgcat::mcset fr {X Axis Title} {X Axis Title}
::msgcat::mcset fr {X Axis} {X Axis}
::msgcat::mcset fr {X Column} {X Column}
::msgcat::mcset fr {X Error Column} {X Error Column}
::msgcat::mcset fr {XPA Information} {XPA Information}
::msgcat::mcset fr {XPA not initialized} {XPA not initialized}
::msgcat::mcset fr XPA XPA
::msgcat::mcset fr X X
::msgcat::mcset fr {Y Axis Title} {Y Axis Title}
::msgcat::mcset fr {Y Axis} {Y Axis}
::msgcat::mcset fr {Y Column} {Y Column}
::msgcat::mcset fr {Y Error Column} {Y Error Column}
::msgcat::mcset fr Yellow Yellow
::msgcat::mcset fr Y Y
::msgcat::mcset fr {Z Axis Scale} {Z Axis Scale}
::msgcat::mcset fr {ZScale Parameters} {ZScale Parameters}
::msgcat::mcset fr Zero Zero
::msgcat::mcset fr {Zoom Fit} {Zoom Fit}
::msgcat::mcset fr {Zoom In} {Zoom In}
::msgcat::mcset fr {Zoom Out} {Zoom Out}
::msgcat::mcset fr Zoom Zoom
::msgcat::mcset fr {already connected} {already connected}
::msgcat::mcset fr and and
::msgcat::mcset fr b b
::msgcat::mcset fr {found dead hub file, deleting} {found dead hub file, deleting}
::msgcat::mcset fr {found existing hub} {found existing hub}
::msgcat::mcset fr {full base} {full base}
::msgcat::mcset fr full full
::msgcat::mcset fr g g
::msgcat::mcset fr h5utils h5utils
::msgcat::mcset fr {hundredths second} {hundredths second}
::msgcat::mcset fr h h
::msgcat::mcset fr l l
::msgcat::mcset fr minutes minutes
::msgcat::mcset fr {not connected} {not connected}
::msgcat::mcset fr not not
::msgcat::mcset fr only only
::msgcat::mcset fr {or center of data} {or center of data}
::msgcat::mcset fr {root base} {root base}
::msgcat::mcset fr root root
::msgcat::mcset fr {rows of data have been downloaded. More may be available. You may wish to adjust the maximum allowed} {rows of data have been downloaded. More may be available. You may wish to adjust the maximum allowed}
::msgcat::mcset fr r r
::msgcat::mcset fr s s
::msgcat::mcset fr {unable to create hub file} {unable to create hub file}
::msgcat::mcset fr {unable to locate HUB} {unable to locate HUB}
::msgcat::mcset fr {unable to open hub} {unable to open hub}
::msgcat::mcset fr {unable to open web hub} {unable to open web hub}
::msgcat::mcset fr v v
::msgcat::mcset fr x x
