::msgcat::mcset fr {2D} 
::msgcat::mcset fr {3D View} 
::msgcat::mcset fr {3D} 
::msgcat::mcset fr {A postscript generation error has occurred}  [encoding convertfrom iso8859-1 {Une erreur de génération de postscript s'est produite}]
::msgcat::mcset fr {AIP} 
::msgcat::mcset fr {Abort} 
::msgcat::mcset fr {About SAOImageDS9} 
::msgcat::mcset fr {About} [encoding convertfrom iso8859-1 {À propos de}]
::msgcat::mcset fr {Acknowledgment} {Remerciement}
::msgcat::mcset fr {Add Bar Graph} 
::msgcat::mcset fr {Add Graph} 
::msgcat::mcset fr {Add Line Graph} 
::msgcat::mcset fr {Add} {Ajouter}
::msgcat::mcset fr {Advanced} [encoding convertfrom iso8859-1 {Avancé}]
::msgcat::mcset fr {Align} {Aligner}
::msgcat::mcset fr {All Columns} {Toutes les colonnes}
::msgcat::mcset fr {All Rows} [encoding convertfrom iso8859-1 {Toutes les rangées}]
::msgcat::mcset fr {All} {Tous}
::msgcat::mcset fr {Always save files during Backup} 
::msgcat::mcset fr {Amplifier} {Amplificateur}
::msgcat::mcset fr {An error has occurred during backup} 
::msgcat::mcset fr {An error has occurred during restore} 
::msgcat::mcset fr {An error has occurred invoking the Analysis task} [encoding convertfrom iso8859-1 {Une erreur s'est produite en invoquant la tâche d'analyse}]
::msgcat::mcset fr {An error has occurred while creating} 
::msgcat::mcset fr {An error has occurred while loading} 
::msgcat::mcset fr {An error has occurred while printing} {Une erreur s'est produite pendant l'impression}
::msgcat::mcset fr {An error has occurred while saving} {Une erreur s'est produite pendant la sauvegarde}
::msgcat::mcset fr {An internal error has been detected} 
::msgcat::mcset fr {Analysis Command Log} {Enregistrement des commandes d'analyse}
::msgcat::mcset fr {Analysis Commands} 
::msgcat::mcset fr {Analysis File} 
::msgcat::mcset fr {Analysis Log} 
::msgcat::mcset fr {Analysis} {Analyse}
::msgcat::mcset fr {Angle Complement} [encoding convertfrom iso8859-1 {Complément d'angle}]
::msgcat::mcset fr {Angles} {Angles}
::msgcat::mcset fr {Angle} {Angle}
::msgcat::mcset fr {Annuli} {Anneaux}
::msgcat::mcset fr {Annulus} {Anneau}
::msgcat::mcset fr {Apply} {Appliquer}
::msgcat::mcset fr {ArcMin} 
::msgcat::mcset fr {ArcSec} 
::msgcat::mcset fr {Architecture} 
::msgcat::mcset fr {Archives} 
::msgcat::mcset fr {Array} 
::msgcat::mcset fr {Arrow} [encoding convertfrom iso8859-1 {Flèche}]
::msgcat::mcset fr {Asteroids} 
::msgcat::mcset fr {Astronomy} 
::msgcat::mcset fr {At Startup} 
::msgcat::mcset fr {At least 2 different catalogs are required} 
::msgcat::mcset fr {Auto Centroid} 
::msgcat::mcset fr {Auto Plot 2D} 
::msgcat::mcset fr {Auto Plot 3D} 
::msgcat::mcset fr {Auto Plot Statistics} 
::msgcat::mcset fr {Auto Plot} 
::msgcat::mcset fr {Autoload FITS Regions} [encoding convertfrom iso8859-1 {Autochargement des régions FITS}]
::msgcat::mcset fr {Autoload} 
::msgcat::mcset fr {Automatic} {Automatique}
::msgcat::mcset fr {Average} {Moyenne}
::msgcat::mcset fr {Axes Number} 
::msgcat::mcset fr {Axes Order} 
::msgcat::mcset fr {Axes Range} 
::msgcat::mcset fr {Axes Title} 
::msgcat::mcset fr {Axes} 
::msgcat::mcset fr {Axis Length} {Longueur de l'axe}
::msgcat::mcset fr {Axis Numbers} [encoding convertfrom iso8859-1 {Échelle de l'axe}]
::msgcat::mcset fr {Axis Title} 
::msgcat::mcset fr {Axis} {Axe}
::msgcat::mcset fr {Azimuth} 
::msgcat::mcset fr {Background Color} {Couleur de fond}
::msgcat::mcset fr {Background} {Fond}
::msgcat::mcset fr {Backup} 
::msgcat::mcset fr {Back} {Retour}
::msgcat::mcset fr {Bar Dataset} 
::msgcat::mcset fr {Bar Plot Tool} 
::msgcat::mcset fr {Bar Width} 
::msgcat::mcset fr {Bar} 
::msgcat::mcset fr {Behavior} 
::msgcat::mcset fr {Bias} {Biais}
::msgcat::mcset fr {Bin 3rd Column} [encoding convertfrom iso8859-1 {3ème colonne de bin}]
::msgcat::mcset fr {Bin Center} {Centre de bin}
::msgcat::mcset fr {Bin Columns} {Colonnes de bin}
::msgcat::mcset fr {Bin Filter} {Filtre de bin}
::msgcat::mcset fr {Bin Fit} 
::msgcat::mcset fr {Bin In} 
::msgcat::mcset fr {Bin Out} 
::msgcat::mcset fr {Binning Parameters} [encoding convertfrom iso8859-1 {Paramètres de bin}]
::msgcat::mcset fr {Bins} 
::msgcat::mcset fr {Bin} 
::msgcat::mcset fr {Black} {Noir}
::msgcat::mcset fr {Blank/Inf/NaN Color} {Blanc/Inf/NaN Couleur}
::msgcat::mcset fr {Blend} 
::msgcat::mcset fr {Blink Frames} [encoding convertfrom iso8859-1 {Clignotement des fenêtres}]
::msgcat::mcset fr {Blink Interval} {Intervalle de clignotement}
::msgcat::mcset fr {Blink} {Clignotement}
::msgcat::mcset fr {Block Fit} 
::msgcat::mcset fr {Block In} [encoding convertfrom iso8859-1 {Bin à}]
::msgcat::mcset fr {Block Out} {Bin de}
::msgcat::mcset fr {Block Parameters} 
::msgcat::mcset fr {Block Pixel} 
::msgcat::mcset fr {Block} {Bin}
::msgcat::mcset fr {Blue} {Bleu}
::msgcat::mcset fr {Bold} {Gras}
::msgcat::mcset fr {Border Color} 
::msgcat::mcset fr {Border Width} 
::msgcat::mcset fr {Border} {Bordure}
::msgcat::mcset fr {Bottom} 
::msgcat::mcset fr {Box Annulus} [encoding convertfrom iso8859-1 {Anneau de boîte}]
::msgcat::mcset fr {Box Panda} 
::msgcat::mcset fr {BoxCircle} 
::msgcat::mcset fr {Boxcar} 
::msgcat::mcset fr {Box} [encoding convertfrom iso8859-1 {Boîte}]
::msgcat::mcset fr {Broadcast} 
::msgcat::mcset fr {Browser} 
::msgcat::mcset fr {Browse} {Parcourir}
::msgcat::mcset fr {Buffer} {Tampon}
::msgcat::mcset fr {Buttonbar} 
::msgcat::mcset fr {Buttons} {Boutons}
::msgcat::mcset fr {Bytes} {Octets}
::msgcat::mcset fr {CMYK} 
::msgcat::mcset fr {Can Delete} {Peut effacer}
::msgcat::mcset fr {Can Edit} [encoding convertfrom iso8859-1 {Peut éditer}]
::msgcat::mcset fr {Can Move} [encoding convertfrom iso8859-1 {Peut déplacer}]
::msgcat::mcset fr {Can Rotate} {Peut tourner}
::msgcat::mcset fr {Cancelled} 
::msgcat::mcset fr {Cancel} {Annuler}
::msgcat::mcset fr {Cap} 
::msgcat::mcset fr {Catalog Server} {Serveur de catalogue}
::msgcat::mcset fr {Catalog Tool} {Outil de catalogue}
::msgcat::mcset fr {Catalogs} {Catalogues}
::msgcat::mcset fr {Catalog} {Catalogue}
::msgcat::mcset fr {Catrom} 
::msgcat::mcset fr {Cat} 
::msgcat::mcset fr {Center Dialogs} 
::msgcat::mcset fr {Center Image} {Centrer l'image}
::msgcat::mcset fr {Center} {Centrer}
::msgcat::mcset fr {Centroid Parameters} 
::msgcat::mcset fr {Centroid} 
::msgcat::mcset fr {Circle} {Cercle}
::msgcat::mcset fr {Clear All} {Tout effacer}
::msgcat::mcset fr {Clear Analysis Commands} {Effacer les commandes d'analyse}
::msgcat::mcset fr {Clear Cache} {Effacer le cache}
::msgcat::mcset fr {Clear External Analysis Commands?} {Effacer les commandes d'analyse externes ?}
::msgcat::mcset fr {Clear Filter} {Effacer le filtre}
::msgcat::mcset fr {Clear Frame} [encoding convertfrom iso8859-1 {Effacer la fenêtre}]
::msgcat::mcset fr {Clear Preferences?} [encoding convertfrom iso8859-1 {Effacer les préférences ?}]
::msgcat::mcset fr {Clear Preferences} [encoding convertfrom iso8859-1 {Effacer les préférences}]
::msgcat::mcset fr {Clear} {Effacer}
::msgcat::mcset fr {Click to Center} {Cliquer pour centrer}
::msgcat::mcset fr {Close} {Fermer}
::msgcat::mcset fr {Colorbar Size} 
::msgcat::mcset fr {Colorbar} {Barre de couleurs}
::msgcat::mcset fr {Colormap Parameters} [encoding convertfrom iso8859-1 {Paramètres de carte de couleurs}]
::msgcat::mcset fr {Colormap} {Carte de couleurs}
::msgcat::mcset fr {Color} {Couleur}
::msgcat::mcset fr {Columns} {Colonnes}
::msgcat::mcset fr {Column} {Colonne}
::msgcat::mcset fr {Comets} 
::msgcat::mcset fr {Command not allowed} 
::msgcat::mcset fr {Command} 
::msgcat::mcset fr {Compass} {Boussole}
::msgcat::mcset fr {Composite Region} 
::msgcat::mcset fr {Composite} 
::msgcat::mcset fr {Compression} 
::msgcat::mcset fr {Configure} {Configurer}
::msgcat::mcset fr {Connect SAMP} 
::msgcat::mcset fr {Connect} 
::msgcat::mcset fr {Console} 
::msgcat::mcset fr {Contacting Server} 
::msgcat::mcset fr {Contour Parameters} [encoding convertfrom iso8859-1 {Paramètres de contour}]
::msgcat::mcset fr {Contour Paste} 
::msgcat::mcset fr {Contour Save} 
::msgcat::mcset fr {Contours} 
::msgcat::mcset fr {Contour} 
::msgcat::mcset fr {Contrast} {Contraste}
::msgcat::mcset fr {Control Panel} 
::msgcat::mcset fr {Convert to Polygons} {Convertir en polygones}
::msgcat::mcset fr {Coordinate Grid Parameters} [encoding convertfrom iso8859-1 {Paramètres de grille de coordonnées}]
::msgcat::mcset fr {Coordinate Grid} [encoding convertfrom iso8859-1 {Grille de coordonnées}]
::msgcat::mcset fr {Coordinate System} [encoding convertfrom iso8859-1 {Système de coordonnées}]
::msgcat::mcset fr {Coordinates} 
::msgcat::mcset fr {Coordinate} [encoding convertfrom iso8859-1 {Coordonnée}]
::msgcat::mcset fr {Copy Contours} {Copier les contours}
::msgcat::mcset fr {Copy to Regions} [encoding convertfrom iso8859-1 {Copier vers Régions}]
::msgcat::mcset fr {Copy} {Copier}
::msgcat::mcset fr {Create Movie} 
::msgcat::mcset fr {Create New Frame on Download} [encoding convertfrom iso8859-1 {Créer une nouvelle fenêtre au téléchargement}]
::msgcat::mcset fr {Create} 
::msgcat::mcset fr {Crop Parameters} 
::msgcat::mcset fr {Crop} 
::msgcat::mcset fr {Crosshair Parameters} 
::msgcat::mcset fr {Crosshair To} [encoding convertfrom iso8859-1 {Réticule vers}]
::msgcat::mcset fr {Crosshair} [encoding convertfrom iso8859-1 {Réticule}]
::msgcat::mcset fr {Cross} {Croisement}
::msgcat::mcset fr {Cubehelix} 
::msgcat::mcset fr {Cube} 
::msgcat::mcset fr {Cubic} 
::msgcat::mcset fr {Current Frame} {Fenêtre courante}
::msgcat::mcset fr {Current Range} {Intervalle courant}
::msgcat::mcset fr {Current} {Courant}
::msgcat::mcset fr {Cursor} {Curseur}
::msgcat::mcset fr {Cut} {Couper}
::msgcat::mcset fr {Cyan} 
::msgcat::mcset fr {DMS} 
::msgcat::mcset fr {DPI} 
::msgcat::mcset fr {DS9 has detected a newer version of a backup file and therefore will not process this file.} 
::msgcat::mcset fr {DS9 has detected a newer version of a preferences file.} 
::msgcat::mcset fr {DS9 has detected an older backup file, do you wish to continue?} 
::msgcat::mcset fr {DS9 has detected an older preferences file, do you wish to update?} [encoding convertfrom iso8859-1 {DS9 a détecté une vielle version du fichier de préférences, voulez vous la mettre à jour ?}]
::msgcat::mcset fr {DS9 will complete the initialization process} {DS9 va terminer le processus d'initialisation} 
::msgcat::mcset fr {Darken} 
::msgcat::mcset fr {Dash} {Tiret} 
::msgcat::mcset fr {Data Format} [encoding convertfrom iso8859-1 {Format de données}]
::msgcat::mcset fr {Data must be ascii numeric values} 
::msgcat::mcset fr {Dataset Name} 
::msgcat::mcset fr {Dataset} [encoding convertfrom iso8859-1 {Ensemble de données}]
::msgcat::mcset fr {Data} 
::msgcat::mcset fr {Decrease} {Diminuer} 
::msgcat::mcset fr {Default All Files} 
::msgcat::mcset fr {Default Format} 
::msgcat::mcset fr {Default Length} 
::msgcat::mcset fr {Default} {Defaut} 
::msgcat::mcset fr {Degrees} [encoding convertfrom iso8859-1 {Degrés}]
::msgcat::mcset fr {Delay} 
::msgcat::mcset fr {Delete All Frames?} [encoding convertfrom iso8859-1 {Supprimer toutes les fenêtres ?}]
::msgcat::mcset fr {Delete All Frames} [encoding convertfrom iso8859-1 {Supprimer toutes les fenêtres}] 
::msgcat::mcset fr {Delete All Groups?} {Supprimer tous les groupes ?} 
::msgcat::mcset fr {Delete All Groups} {Supprimer tous les groupes} 
::msgcat::mcset fr {Delete All} 
::msgcat::mcset fr {Delete Color Tags} 
::msgcat::mcset fr {Delete Dataset} 
::msgcat::mcset fr {Delete Frame} [encoding convertfrom iso8859-1 {Supprimer la fenêtre}]
::msgcat::mcset fr {Delete Graph} 
::msgcat::mcset fr {Delete Group} {Supprimer le groupe} 
::msgcat::mcset fr {Delete Load} 
::msgcat::mcset fr {Delete Regions?} 
::msgcat::mcset fr {Delete Regions} 
::msgcat::mcset fr {Delete Selected Regions} [encoding convertfrom iso8859-1 {Supprimer les régions séléctionnées}]
::msgcat::mcset fr {Delete Select} 
::msgcat::mcset fr {Delete and Open Regions} 
::msgcat::mcset fr {Delete} {Supprimer} 
::msgcat::mcset fr {Depth} {Profondeur} 
::msgcat::mcset fr {Detector} {Detecteur} 
::msgcat::mcset fr {Dialog Box} [encoding convertfrom iso8859-1 {Boîte de dialogue}]
::msgcat::mcset fr {Diameter} 
::msgcat::mcset fr {Diamond} {Losange} 
::msgcat::mcset fr {Dimensions} 
::msgcat::mcset fr {Dimension} {Dimention} 
::msgcat::mcset fr {Direction} 
::msgcat::mcset fr {Disconnect} 
::msgcat::mcset fr {Display Size} {Afficher la taille} 
::msgcat::mcset fr {Dissolve} 
::msgcat::mcset fr {Distance} 
::msgcat::mcset fr {Done} 
::msgcat::mcset fr {Download Colormap} 
::msgcat::mcset fr {Drag to Center} {Glisser au centre} 
::msgcat::mcset fr {Duplicate Dataset} 
::msgcat::mcset fr {ENVI} 
::msgcat::mcset fr {EPS} 
::msgcat::mcset fr {East} {Est} 
::msgcat::mcset fr {Ecliptic} {Ecliptiques} 
::msgcat::mcset fr {Edit Group Name} {Editer le nom du groupe} 
::msgcat::mcset fr {Edit} [encoding convertfrom iso8859-1 {Édition}]
::msgcat::mcset fr {Elevation} 
::msgcat::mcset fr {Ellipse Panda} {Ellipse Panda} 
::msgcat::mcset fr {Ellipse} {Ellipse} 
::msgcat::mcset fr {Elliptical Annulus} {Anneau elliptique} 
::msgcat::mcset fr {Elliptical Gaussian} 
::msgcat::mcset fr {Elliptical Panda} {Panda elliptique} 
::msgcat::mcset fr {Enable Confirmation Dialogs} {Utiliser les dialogues de confirmation} 
::msgcat::mcset fr {Enable} 
::msgcat::mcset fr {End} {Fin} 
::msgcat::mcset fr {Enter Color} 
::msgcat::mcset fr {Enter Font Size} 
::msgcat::mcset fr {Enter Group Name} {Entrer le nom du groupe} 
::msgcat::mcset fr {Enter Search Expression} 
::msgcat::mcset fr {Enter URL} 
::msgcat::mcset fr {Entry} 
::msgcat::mcset fr {Equal Area} {Egale surface} 
::msgcat::mcset fr {Equal Distance} {Egale distance} 
::msgcat::mcset fr {Equal Spacing} 
::msgcat::mcset fr {Equal Value} 
::msgcat::mcset fr {Error code was returned} [encoding convertfrom iso8859-1 {Un code d'erreur a été renvoyé}]
::msgcat::mcset fr {Errorbar} 
::msgcat::mcset fr {Error} {Erreur} 
::msgcat::mcset fr {Examine Frame} [encoding convertfrom iso8859-1 {Examiner la fenêtre}]
::msgcat::mcset fr {Examine} {Examiner} 
::msgcat::mcset fr {Exam} 
::msgcat::mcset fr {Exclude} {Exclure} 
::msgcat::mcset fr {Exit} {Sortie} 
::msgcat::mcset fr {Export Array} 
::msgcat::mcset fr {Export ENVI} 
::msgcat::mcset fr {Export GIF} 
::msgcat::mcset fr {Export JPEG} 
::msgcat::mcset fr {Export NRRD} 
::msgcat::mcset fr {Export PNG} 
::msgcat::mcset fr {Export RGB Array} 
::msgcat::mcset fr {Export TIFF} 
::msgcat::mcset fr {Export} 
::msgcat::mcset fr {Extension Data} 
::msgcat::mcset fr {Extension not found} 
::msgcat::mcset fr {Extensions} 
::msgcat::mcset fr {Extension} 
::msgcat::mcset fr {Exterior Axes} {Axes exterieurs} 
::msgcat::mcset fr {Exterior Numerics} {Chiffres exterieurs}
::msgcat::mcset fr {FAQ} {Foire-Aux-Questions} 
::msgcat::mcset fr {FITS} 
::msgcat::mcset fr {FK4} 
::msgcat::mcset fr {FK5} 
::msgcat::mcset fr {FP} 
::msgcat::mcset fr {Factor} 
::msgcat::mcset fr {File not Found or Unable to load FITS data MIME type} [encoding convertfrom iso8859-1 {Fichier non trouvé, ou impossible d'utiliser le type MIME des données FITS}]
::msgcat::mcset fr {File not found} 
::msgcat::mcset fr {Filename} {NomDuFichier} 
::msgcat::mcset fr {File} {Fichier}
::msgcat::mcset fr {Fill} 
::msgcat::mcset fr {Filter} {Filtre} 
::msgcat::mcset fr {Find Next} {Trouver le suivant} 
::msgcat::mcset fr {Find} {Trouver}
::msgcat::mcset fr {First Block} 
::msgcat::mcset fr {First Frame} [encoding convertfrom iso8859-1 {Première fenêtre}]
::msgcat::mcset fr {First} {Premier} 
::msgcat::mcset fr {Fits} 
::msgcat::mcset fr {Fixed in Size} [encoding convertfrom iso8859-1 {Taille fixée}]
::msgcat::mcset fr {Flip} 
::msgcat::mcset fr {Font} {Police}
::msgcat::mcset fr {Footprint Servers} 
::msgcat::mcset fr {Footprint} 
::msgcat::mcset fr {For more information, use --help} 
::msgcat::mcset fr {Foreground} 
::msgcat::mcset fr {Forground} 
::msgcat::mcset fr {Format} 
::msgcat::mcset fr {Forward} {En avant} 
::msgcat::mcset fr {Found} {Trouvé} 
::msgcat::mcset fr {Frame Information} [encoding convertfrom iso8859-1 {Information de la fenêtre }]
::msgcat::mcset fr {Frame Parameters} 
::msgcat::mcset fr {Frames} 
::msgcat::mcset fr {Frame} [encoding convertfrom iso8859-1 {Fenêtre}]
::msgcat::mcset fr {From} 
::msgcat::mcset fr {Front} {Avant} 
::msgcat::mcset fr {Full Range} 
::msgcat::mcset fr {Function} {Fonction} 
::msgcat::mcset fr {GIF} 
::msgcat::mcset fr {GUI} 
::msgcat::mcset fr {Galactic} {Galactiques} 
::msgcat::mcset fr {Gap} 
::msgcat::mcset fr {Gaussian} {Gaussien} 
::msgcat::mcset fr {General} [encoding convertfrom iso8859-1 {Général}]
::msgcat::mcset fr {Generate} [encoding convertfrom iso8859-1 {Générer}]
::msgcat::mcset fr {Generating Regions} [encoding convertfrom iso8859-1 {Création des régions}]
::msgcat::mcset fr {Get Information} [encoding convertfrom iso8859-1 {Récuperer l'information}]
::msgcat::mcset fr {Gist} 
::msgcat::mcset fr {Global Properties} 
::msgcat::mcset fr {Global} {Global} 
::msgcat::mcset fr {Goto Frame} [encoding convertfrom iso8859-1 {Aller à la fenêtre}]
::msgcat::mcset fr {Goto Row} 
::msgcat::mcset fr {Goto} 
::msgcat::mcset fr {Graph Horz} 
::msgcat::mcset fr {Graph Parameters} 
::msgcat::mcset fr {Graph Vert} 
::msgcat::mcset fr {Graphics} {Graphiques} 
::msgcat::mcset fr {Graphs} 
::msgcat::mcset fr {Graph} {Graph} 
::msgcat::mcset fr {Grayscale} {Niveaux de gris} 
::msgcat::mcset fr {Green} {Vert} 
::msgcat::mcset fr {Grid Gap} {Espacement de la grille} 
::msgcat::mcset fr {Grid} {Grille} 
::msgcat::mcset fr {Groups} {Groupes} 
::msgcat::mcset fr {HMS} 
::msgcat::mcset fr {HTTP} 
::msgcat::mcset fr {Header} [encoding convertfrom iso8859-1 {Entête}]
::msgcat::mcset fr {Height} {Hauteur} 
::msgcat::mcset fr {Help Desk} {Contacts} 
::msgcat::mcset fr {Help Me Choose} {Aider moi} 
::msgcat::mcset fr {Help} {Aide}
::msgcat::mcset fr {Hide All} {Cacher tous} 
::msgcat::mcset fr {Highlite} 
::msgcat::mcset fr {High} {Haut} 
::msgcat::mcset fr {Histogram Equalization} {Egalisation via Histogramme} 
::msgcat::mcset fr {Histogram} {Histogramme} 
::msgcat::mcset fr {Horizontal Graph} {Graphique Horizontal} 
::msgcat::mcset fr {Horizontal Layout} {Mise en page Horizontale} 
::msgcat::mcset fr {Horizontal} 
::msgcat::mcset fr {IAU Location Code} 
::msgcat::mcset fr {ICRS} 
::msgcat::mcset fr {Identification} 
::msgcat::mcset fr {If} {Si}
::msgcat::mcset fr {Image Servers} 
::msgcat::mcset fr {Image} 
::msgcat::mcset fr {Import Array} 
::msgcat::mcset fr {Import ENVI} 
::msgcat::mcset fr {Import GIF} 
::msgcat::mcset fr {Import JPEG} 
::msgcat::mcset fr {Import NRRD} 
::msgcat::mcset fr {Import PNG} 
::msgcat::mcset fr {Import RGB Array} 
::msgcat::mcset fr {Import Slice GIF} 
::msgcat::mcset fr {Import Slice JPEG} 
::msgcat::mcset fr {Import Slice PNG} 
::msgcat::mcset fr {Import Slice TIFF} 
::msgcat::mcset fr {Import TIFF} 
::msgcat::mcset fr {Import} 
::msgcat::mcset fr {Include} {Inclure}
::msgcat::mcset fr {Increase} {Augmenter}
::msgcat::mcset fr {Information Panel} {Panneau de reseignement}
::msgcat::mcset fr {Information} {Reseignement}
::msgcat::mcset fr {Initialize XPA} {Initialiser XPA}
::msgcat::mcset fr {Inner} [encoding convertfrom iso8859-1 {Intérieur}]
::msgcat::mcset fr {Instrument FOV} {Profondeur de champ de l'instrument}
::msgcat::mcset fr {Instrument} 
::msgcat::mcset fr {Interior Axes} [encoding convertfrom iso8859-1 {Axes intérieur}]
::msgcat::mcset fr {Interior Numerics} [encoding convertfrom iso8859-1 {Chiffres intérieur}]
::msgcat::mcset fr {Internal Parse Error} 
::msgcat::mcset fr {Interval} {Intervalle}
::msgcat::mcset fr {Invalid Column Name} 
::msgcat::mcset fr {Invalid WCS} 
::msgcat::mcset fr {Invalid formated multipart/mixed mime type message} {Message invalide de genre mixte/multipart}
::msgcat::mcset fr {Invert Colormap} {Plan de couleur inverti}
::msgcat::mcset fr {Invert Selection} {Selection inverti}
::msgcat::mcset fr {Invert} {Invertir}
::msgcat::mcset fr {Italic} {Italique}
::msgcat::mcset fr {Items Found} [encoding convertfrom iso8859-1 {Articles trouvés}]
::msgcat::mcset fr {Iteration} 
::msgcat::mcset fr {JPEG Quality Factor} [encoding convertfrom iso8859-1 {Le facteur de qualité JPEG}]
::msgcat::mcset fr {JPEG} 
::msgcat::mcset fr {Keep-Alive} 
::msgcat::mcset fr {Keyword} 
::msgcat::mcset fr {Labels} {Étiquettes}
::msgcat::mcset fr {Label} {Étiquette}
::msgcat::mcset fr {Landscape} {Paysage}
::msgcat::mcset fr {Language} {Langue}
::msgcat::mcset fr {Last Block} 
::msgcat::mcset fr {Last Frame} [encoding convertfrom iso8859-1 {Dernière fenêtre}]
::msgcat::mcset fr {Last} {Dernier}
::msgcat::mcset fr {Layout Horz} 
::msgcat::mcset fr {Layout Vert} 
::msgcat::mcset fr {Layout} 
::msgcat::mcset fr {Left} 
::msgcat::mcset fr {Legal} {Legale}
::msgcat::mcset fr {Legend Position} 
::msgcat::mcset fr {Legend Title} 
::msgcat::mcset fr {Legend} 
::msgcat::mcset fr {Length} {Longeur}
::msgcat::mcset fr {Letter} {Lettre}
::msgcat::mcset fr {Levels} {Niveaux}
::msgcat::mcset fr {Level} {Niveau}
::msgcat::mcset fr {Lighten} 
::msgcat::mcset fr {Limits} {Limites}
::msgcat::mcset fr {Line Dataset} 
::msgcat::mcset fr {Line Plot Tool} 
::msgcat::mcset fr {Linear} [encoding convertfrom iso8859-1 {Linéaire}]
::msgcat::mcset fr {Line} {Ligne}
::msgcat::mcset fr {List Data} 
::msgcat::mcset fr {List Regions} [encoding convertfrom iso8859-1 {Énumérer les régions}]
::msgcat::mcset fr {List Selected Regions} 
::msgcat::mcset fr {List Select} 
::msgcat::mcset fr {List} [encoding convertfrom iso8859-1 {Énumérer}]
::msgcat::mcset fr {Load Analysis Commands} {Charger le commandes d'analyse}
::msgcat::mcset fr {Load Color Tags} 
::msgcat::mcset fr {Load Contour Levels} {Charger les niveaux de contour}
::msgcat::mcset fr {Load Contrast/Bias} {Charger le contraste/inclination}
::msgcat::mcset fr {Load Data} [encoding convertfrom iso8859-1 {Charger les données}]
::msgcat::mcset fr {Load Mosaic} [encoding convertfrom iso8859-1 {Charger le mosaïque}]
::msgcat::mcset fr {Load Template} {Charger le patron}
::msgcat::mcset fr {Load into All} 
::msgcat::mcset fr {Load into Current} 
::msgcat::mcset fr {Loading Catalog} 
::msgcat::mcset fr {Loading} 
::msgcat::mcset fr {Load} {Charger}
::msgcat::mcset fr {Local} {Locale}
::msgcat::mcset fr {Lock Axes} 
::msgcat::mcset fr {Lock Bin} 
::msgcat::mcset fr {Lock Color} 
::msgcat::mcset fr {Lock Crop Amplifier} 
::msgcat::mcset fr {Lock Crop Detector} 
::msgcat::mcset fr {Lock Crop Image} 
::msgcat::mcset fr {Lock Crop None} 
::msgcat::mcset fr {Lock Crop Physical} 
::msgcat::mcset fr {Lock Crop WCS} 
::msgcat::mcset fr {Lock Crosshair Amplifier} 
::msgcat::mcset fr {Lock Crosshair Detector} 
::msgcat::mcset fr {Lock Crosshair Image} 
::msgcat::mcset fr {Lock Crosshair None} 
::msgcat::mcset fr {Lock Crosshair Physical} 
::msgcat::mcset fr {Lock Crosshair WCS} 
::msgcat::mcset fr {Lock Frame Amplifier} 
::msgcat::mcset fr {Lock Frame Detector} 
::msgcat::mcset fr {Lock Frame Image} 
::msgcat::mcset fr {Lock Frame None} 
::msgcat::mcset fr {Lock Frame Physical} 
::msgcat::mcset fr {Lock Frame WCS} 
::msgcat::mcset fr {Lock Limits} 
::msgcat::mcset fr {Lock Scale} 
::msgcat::mcset fr {Lock Slice Image} 
::msgcat::mcset fr {Lock Slice None} 
::msgcat::mcset fr {Lock Slice WCS} 
::msgcat::mcset fr {Lock Smooth} 
::msgcat::mcset fr {Lock} {Verrouiller}
::msgcat::mcset fr {Log Exponent} 
::msgcat::mcset fr {Log} 
::msgcat::mcset fr {Low High} {Haut bas}
::msgcat::mcset fr {Lower Left Back} 
::msgcat::mcset fr {Lower Left Front} 
::msgcat::mcset fr {Lower Right Back} 
::msgcat::mcset fr {Lower Right Front} 
::msgcat::mcset fr {Low} {Bas}
::msgcat::mcset fr {MIP} 
::msgcat::mcset fr {Magenta} 
::msgcat::mcset fr {Magnification} 
::msgcat::mcset fr {Magnifier} {Magnificateur}
::msgcat::mcset fr {Major Radius} 
::msgcat::mcset fr {Major Sigma} 
::msgcat::mcset fr {Major} {Majeure}
::msgcat::mcset fr {Manual} 
::msgcat::mcset fr {Mask Parameters} [encoding convertfrom iso8859-1 {Paramètres de masque}]
::msgcat::mcset fr {Match Axes} 
::msgcat::mcset fr {Match Bin} 
::msgcat::mcset fr {Match Catalog requires at least 1 row per catalog} 
::msgcat::mcset fr {Match Color} 
::msgcat::mcset fr {Match Crop Amplifier} 
::msgcat::mcset fr {Match Crop Detector} 
::msgcat::mcset fr {Match Crop Image} 
::msgcat::mcset fr {Match Crop Physical} 
::msgcat::mcset fr {Match Crop WCS} 
::msgcat::mcset fr {Match Crosshair Amplifier} 
::msgcat::mcset fr {Match Crosshair Detector} 
::msgcat::mcset fr {Match Crosshair Image} 
::msgcat::mcset fr {Match Crosshair Physical} 
::msgcat::mcset fr {Match Crosshair WCS} 
::msgcat::mcset fr {Match Frame Amplifier} 
::msgcat::mcset fr {Match Frame Detector} 
::msgcat::mcset fr {Match Frame Image} 
::msgcat::mcset fr {Match Frame Physical} 
::msgcat::mcset fr {Match Frame WCS} 
::msgcat::mcset fr {Match Limits} 
::msgcat::mcset fr {Match Scale} 
::msgcat::mcset fr {Match Slice Image} 
::msgcat::mcset fr {Match Slice WCS} 
::msgcat::mcset fr {Match Smooth} 
::msgcat::mcset fr {Match} 
::msgcat::mcset fr {Math Function} {Fonction mathématique}
::msgcat::mcset fr {Matplotlib} 
::msgcat::mcset fr {Max Rows} [encoding convertfrom iso8859-1 {Maximum de rangées}]
::msgcat::mcset fr {Maximum} 
::msgcat::mcset fr {Max} {Maximum}
::msgcat::mcset fr {Menus and Buttons} 
::msgcat::mcset fr {Menu} 
::msgcat::mcset fr {Message Log} 
::msgcat::mcset fr {Method} [encoding convertfrom iso8859-1 {Méthode}]
::msgcat::mcset fr {Min Max Parameters} 
::msgcat::mcset fr {Min Max} 
::msgcat::mcset fr {Minimum} 
::msgcat::mcset fr {Minor Radius} 
::msgcat::mcset fr {Minor Sigma} 
::msgcat::mcset fr {Minor} {Mineure}
::msgcat::mcset fr {Minutes} 
::msgcat::mcset fr {Min} {Minimum}
::msgcat::mcset fr {Mission} 
::msgcat::mcset fr {Mode} 
::msgcat::mcset fr {Mosaic IRAF Segment} 
::msgcat::mcset fr {Mosaic IRAF} 
::msgcat::mcset fr {Mosaic WCS Segment} 
::msgcat::mcset fr {Mosaic WCS} 
::msgcat::mcset fr {Mosaic WFPC2} 
::msgcat::mcset fr {Mosaic} 
::msgcat::mcset fr {Mouse Click Epsilon} 
::msgcat::mcset fr {Mouse Wheel Bin} 
::msgcat::mcset fr {Mouse Wheel Zoom} 
::msgcat::mcset fr {Move Back} 
::msgcat::mcset fr {Move First} 
::msgcat::mcset fr {Move Forward} 
::msgcat::mcset fr {Move Frame} 
::msgcat::mcset fr {Move Last} 
::msgcat::mcset fr {Move to Back} [encoding convertfrom iso8859-1 {Bouger vers arrière}]
::msgcat::mcset fr {Move to Front} {Bouger vers le devant}
::msgcat::mcset fr {Movie} 
::msgcat::mcset fr {Muliple Extension Cube} 
::msgcat::mcset fr {Muliple Extension Frames} 
::msgcat::mcset fr {Multiple Extension Cube} 
::msgcat::mcset fr {Multiple Extension Frames} 
::msgcat::mcset fr {Multiple WCS} 
::msgcat::mcset fr {NAN} 
::msgcat::mcset fr {NRRD} 
::msgcat::mcset fr {Name Resolution} [encoding convertfrom iso8859-1 {Nom de la résolution}]
::msgcat::mcset fr {Name Server} {Nom du Serveur}
::msgcat::mcset fr {Name or Designation} [encoding convertfrom iso8859-1 {Nom ou Désignation}]
::msgcat::mcset fr {Name} 
::msgcat::mcset fr {Native Dialog} 
::msgcat::mcset fr {New Features} {Nouvelles options}
::msgcat::mcset fr {New Frame 3D} 
::msgcat::mcset fr {New Frame RGB} [encoding convertfrom iso8859-1 {Nouvelle fenêtre RGB}]
::msgcat::mcset fr {New Frame each Time} [encoding convertfrom iso8859-1 {Nouvelle fenêtre à chaque fois}]
::msgcat::mcset fr {New Frame} [encoding convertfrom iso8859-1 {Nouvelle fenêtre}]
::msgcat::mcset fr {New Graph} 
::msgcat::mcset fr {New Group} {Nouveau groupe}
::msgcat::mcset fr {New Plot} 
::msgcat::mcset fr {New} {Nouveau}
::msgcat::mcset fr {Next Block} 
::msgcat::mcset fr {Next Frame} [encoding convertfrom iso8859-1 {Fenêtre suivante}]
::msgcat::mcset fr {Next} {Suivant}
::msgcat::mcset fr {No Catalog specified} [encoding convertfrom iso8859-1 {Pas de Catalogue spécifié}]
::msgcat::mcset fr {No Data Available} 
::msgcat::mcset fr {No Items Found} [encoding convertfrom iso8859-1 {Pas trouvé}]
::msgcat::mcset fr {Non-NAN} 
::msgcat::mcset fr {Non-Zero} 
::msgcat::mcset fr {None} {Rien}
::msgcat::mcset fr {Normal} 
::msgcat::mcset fr {North} {Nord}
::msgcat::mcset fr {Not Found} 
::msgcat::mcset fr {Not Supported} 
::msgcat::mcset fr {Not valid export format} 
::msgcat::mcset fr {Notes} 
::msgcat::mcset fr {Number of Samples} [encoding convertfrom iso8859-1 {Nombre d'échantillons}]
::msgcat::mcset fr {Number of Threads} 
::msgcat::mcset fr {Number of Ticks} 
::msgcat::mcset fr {Number} {Nombre}
::msgcat::mcset fr {Numerics} {Chiffres}
::msgcat::mcset fr {OK} 
::msgcat::mcset fr {Object} {Objet}
::msgcat::mcset fr {ObsId} 
::msgcat::mcset fr {Open File} {Ouvrir fichier}
::msgcat::mcset fr {Open ME Cube} 
::msgcat::mcset fr {Open ME Frames} 
::msgcat::mcset fr {Open Mosaic IRAF Seg} 
::msgcat::mcset fr {Open Mosaic IRAF} 
::msgcat::mcset fr {Open Mosaic WCS Seg} 
::msgcat::mcset fr {Open Mosaic WCS} 
::msgcat::mcset fr {Open Mosaic WFPC2} 
::msgcat::mcset fr {Open RGB Cube} 
::msgcat::mcset fr {Open RGB Image} 
::msgcat::mcset fr {Open Regions} 
::msgcat::mcset fr {Open Slice} 
::msgcat::mcset fr {Open TCL Console} 
::msgcat::mcset fr {Open URL} {Ouvrir un URL}
::msgcat::mcset fr {Open as} 
::msgcat::mcset fr {Open} {Ouvrir}
::msgcat::mcset fr {Operator} {Operateur}
::msgcat::mcset fr {Orientation} 
::msgcat::mcset fr {Origin} 
::msgcat::mcset fr {Oscillate} 
::msgcat::mcset fr {Other Color} 
::msgcat::mcset fr {Other Font Size} 
::msgcat::mcset fr {Other} {Autre}
::msgcat::mcset fr {Outer} {Externe}
::msgcat::mcset fr {Overplot} 
::msgcat::mcset fr {Override Color} 
::msgcat::mcset fr {PNG} 
::msgcat::mcset fr {PS Page Setup} 
::msgcat::mcset fr {PS Print} 
::msgcat::mcset fr {Page Setup} {Configurer la Page}
::msgcat::mcset fr {Page Source} {Source de la Page}
::msgcat::mcset fr {Pan To} 
::msgcat::mcset fr {Pan Zoom Rotate Parameters} 
::msgcat::mcset fr {Pan Zoom} 
::msgcat::mcset fr {Pan then Zoom} 
::msgcat::mcset fr {Panda} 
::msgcat::mcset fr {Panner} 
::msgcat::mcset fr {Pan} 
::msgcat::mcset fr {Parameters} [encoding convertfrom iso8859-1 {Paramètres}]
::msgcat::mcset fr {Password} {Mot de passe}
::msgcat::mcset fr {Paste Contours} {Coller les contours}
::msgcat::mcset fr {Paste} {Coller}
::msgcat::mcset fr {Physical} {Physique}
::msgcat::mcset fr {Pixel Distribution} {Distribution des pixels}
::msgcat::mcset fr {Pixel Size} {Taille des pixels}
::msgcat::mcset fr {Pixel Table} {Table des pixels}
::msgcat::mcset fr {Pixels} 
::msgcat::mcset fr {Planets} 
::msgcat::mcset fr {Play} {Jouer}
::msgcat::mcset fr {Please Select a Region} 
::msgcat::mcset fr {Please change the file's permission to disable other users write access. Use anyway?} 
::msgcat::mcset fr {Please specify instruments} 
::msgcat::mcset fr {Please specify radius and either name or (ra,dec)} 
::msgcat::mcset fr {Please specify width, height, and either name or (ra,dec)} {Specifiez largeur, longeur, et autre noms possibles ou (ra,dec)}
::msgcat::mcset fr {Plot 2D} 
::msgcat::mcset fr {Plot 3D} 
::msgcat::mcset fr {Plot Area} 
::msgcat::mcset fr {Plot Control Panel} 
::msgcat::mcset fr {Plot Tool} 
::msgcat::mcset fr {Plotting Regions} [encoding convertfrom iso8859-1 {Tracer les régions}]
::msgcat::mcset fr {Plot} {Dessiner}
::msgcat::mcset fr {Plus} 
::msgcat::mcset fr {Pointer} {Pointeur}
::msgcat::mcset fr {Points} 
::msgcat::mcset fr {Point} 
::msgcat::mcset fr {Polygon} {Polygone}
::msgcat::mcset fr {Portrait} 
::msgcat::mcset fr {Position} 
::msgcat::mcset fr {Poster} 
::msgcat::mcset fr {Postscript} 
::msgcat::mcset fr {Power} {Puissance}
::msgcat::mcset fr {Precision} 
::msgcat::mcset fr {Preferences} [encoding convertfrom iso8859-1 {Préférences}]
::msgcat::mcset fr {Preserve During Load} [encoding convertfrom iso8859-1 {Préserver pendant le chargement}]
::msgcat::mcset fr {Previous Block} 
::msgcat::mcset fr {Previous Frame} [encoding convertfrom iso8859-1 {Fenêtre précédente}]
::msgcat::mcset fr {Previous} [encoding convertfrom iso8859-1 {Précédent}]
::msgcat::mcset fr {Prev} 
::msgcat::mcset fr {Print Coordinates} {Imprimer les coordonnees}
::msgcat::mcset fr {Print To} {Imprimer dans}
::msgcat::mcset fr {Printer} {L'imprimante}
::msgcat::mcset fr {Print} {Imprimer}
::msgcat::mcset fr {Prism Goto} 
::msgcat::mcset fr {Prism} 
::msgcat::mcset fr {Projection} 
::msgcat::mcset fr {Properties} [encoding convertfrom iso8859-1 {Propriétés}]
::msgcat::mcset fr {Property} [encoding convertfrom iso8859-1 {Propriété}]
::msgcat::mcset fr {Proxy Host} 
::msgcat::mcset fr {Proxy Port} 
::msgcat::mcset fr {Publication} 
::msgcat::mcset fr {Quadratic} 
::msgcat::mcset fr {RDB} 
::msgcat::mcset fr {RGB Array} 
::msgcat::mcset fr {RGB Cube} 
::msgcat::mcset fr {RGB Image} 
::msgcat::mcset fr {RGB} 
::msgcat::mcset fr {Radial Profile} 
::msgcat::mcset fr {Radius} 
::msgcat::mcset fr {Range} 
::msgcat::mcset fr {Redo} {Refaire}
::msgcat::mcset fr {Red} 
::msgcat::mcset fr {Reference Manual} 
::msgcat::mcset fr {Reference} 
::msgcat::mcset fr {Refresh Frame} 
::msgcat::mcset fr {Refresh} 
::msgcat::mcset fr {Region Parameters} 
::msgcat::mcset fr {Region} [encoding convertfrom iso8859-1 {Région}]
::msgcat::mcset fr {Release Notes} 
::msgcat::mcset fr {Release} 
::msgcat::mcset fr {Reload} 
::msgcat::mcset fr {Render} 
::msgcat::mcset fr {Repeat} 
::msgcat::mcset fr {Reset Colormap} 
::msgcat::mcset fr {Reset Frame} 
::msgcat::mcset fr {Reset} 
::msgcat::mcset fr {Restore} 
::msgcat::mcset fr {Retrieve} 
::msgcat::mcset fr {Return} 
::msgcat::mcset fr {Right} 
::msgcat::mcset fr {Roman} 
::msgcat::mcset fr {Rotate} 
::msgcat::mcset fr {Rows} 
::msgcat::mcset fr {Row} 
::msgcat::mcset fr {Ruler} 
::msgcat::mcset fr {SAMP Image} 
::msgcat::mcset fr {SAMP Table} 
::msgcat::mcset fr {SAMP: not connected} 
::msgcat::mcset fr {SAMP} 
::msgcat::mcset fr {Sample Increment} 
::msgcat::mcset fr {Sample Parameters} 
::msgcat::mcset fr {Samples per Line} 
::msgcat::mcset fr {Sample} 
::msgcat::mcset fr {Save 3D Movie} 
::msgcat::mcset fr {Save Color Tags} 
::msgcat::mcset fr {Save Contour Levels} 
::msgcat::mcset fr {Save Contrast/Bias} 
::msgcat::mcset fr {Save Data} 
::msgcat::mcset fr {Save Image EPS} 
::msgcat::mcset fr {Save Image FITS} 
::msgcat::mcset fr {Save Image GIF} 
::msgcat::mcset fr {Save Image JPEG} 
::msgcat::mcset fr {Save Image PNG} 
::msgcat::mcset fr {Save Image TIFF} 
::msgcat::mcset fr {Save Image on Download} 
::msgcat::mcset fr {Save Image} 
::msgcat::mcset fr {Save ME Cube} 
::msgcat::mcset fr {Save Mosaic WCS Seg} 
::msgcat::mcset fr {Save Mosaic WCS} 
::msgcat::mcset fr {Save RGB Cube} 
::msgcat::mcset fr {Save RGB Image} 
::msgcat::mcset fr {Save Regions} 
::msgcat::mcset fr {Save Selected Regions} 
::msgcat::mcset fr {Save Select} 
::msgcat::mcset fr {Save Slice} 
::msgcat::mcset fr {Save Template} 
::msgcat::mcset fr {Save as} 
::msgcat::mcset fr {Save} {Enregistrer}
::msgcat::mcset fr {Scale Parameters} 
::msgcat::mcset fr {Scale and Limits} 
::msgcat::mcset fr {Scale} 
::msgcat::mcset fr {Scan} 
::msgcat::mcset fr {Scatter Dataset} 
::msgcat::mcset fr {Scatter Plot Tool} 
::msgcat::mcset fr {Scope} 
::msgcat::mcset fr {Screen} 
::msgcat::mcset fr {Search for Catalogs} 
::msgcat::mcset fr {Seconds} 
::msgcat::mcset fr {Segment} 
::msgcat::mcset fr {Select All} 
::msgcat::mcset fr {Select Coordinate System } 
::msgcat::mcset fr {Select Dataset} 
::msgcat::mcset fr {Select Datatset} 
::msgcat::mcset fr {Select Graph} 
::msgcat::mcset fr {Select None} 
::msgcat::mcset fr {Send} 
::msgcat::mcset fr {Server} 
::msgcat::mcset fr {Sexagesimal} 
::msgcat::mcset fr {Shadow} 
::msgcat::mcset fr {Shape} 
::msgcat::mcset fr {Show All} {Montrer tous}
::msgcat::mcset fr {Show Command} 
::msgcat::mcset fr {Show Compass} 
::msgcat::mcset fr {Show Grid} 
::msgcat::mcset fr {Show Legend} 
::msgcat::mcset fr {Show Text} 
::msgcat::mcset fr {Show/Hide Frames} [encoding convertfrom iso8859-1 {Montrer/Cacher les fenêtres}]
::msgcat::mcset fr {Show} 
::msgcat::mcset fr {Simple Cross} 
::msgcat::mcset fr {Simple Image Access} 
::msgcat::mcset fr {Simple Plus} 
::msgcat::mcset fr {Single Frame} 
::msgcat::mcset fr {Single} 
::msgcat::mcset fr {Sites} 
::msgcat::mcset fr {Size/Radius} 
::msgcat::mcset fr {Size} 
::msgcat::mcset fr {Skip First} 
::msgcat::mcset fr {Slice} 
::msgcat::mcset fr {Smooth Parameters} 
::msgcat::mcset fr {Smoothness} 
::msgcat::mcset fr {Smooth} 
::msgcat::mcset fr {Sorry, DS9 does not support} 
::msgcat::mcset fr {Sorry, DS9 requires a Truecolor8, Truecolor16, Truecolor24 visual be available} 
::msgcat::mcset fr {Sort} 
::msgcat::mcset fr {Source TCL} 
::msgcat::mcset fr {Source} 
::msgcat::mcset fr {Space Equal Distance} 
::msgcat::mcset fr {Space Equal Value} 
::msgcat::mcset fr {Spacing} 
::msgcat::mcset fr {Sqrt} 
::msgcat::mcset fr {Square Root} 
::msgcat::mcset fr {Squared} 
::msgcat::mcset fr {Square} 
::msgcat::mcset fr {Starbase} 
::msgcat::mcset fr {Startup} 
::msgcat::mcset fr {Start} 
::msgcat::mcset fr {Statistics} 
::msgcat::mcset fr {Status} 
::msgcat::mcset fr {Step} 
::msgcat::mcset fr {Stop} 
::msgcat::mcset fr {Story of SAOImageDS9} 
::msgcat::mcset fr {Story} 
::msgcat::mcset fr {Strip Parameters} 
::msgcat::mcset fr {Strip Scale} 
::msgcat::mcset fr {Strip} 
::msgcat::mcset fr {Sum} 
::msgcat::mcset fr {Symbol Editor} 
::msgcat::mcset fr {Symbol} 
::msgcat::mcset fr {TIFF} 
::msgcat::mcset fr {TSV} 
::msgcat::mcset fr {Tab-Separated-Value} 
::msgcat::mcset fr {Table} 
::msgcat::mcset fr {Tabloid} 
::msgcat::mcset fr {Tag Color} 
::msgcat::mcset fr {Template} 
::msgcat::mcset fr {Text} {Texte}
::msgcat::mcset fr {Theme} 
::msgcat::mcset fr {Then} 
::msgcat::mcset fr {Thickness} 
::msgcat::mcset fr {This analysis task is already running. Do you wish to kill it?} 
::msgcat::mcset fr {This function is not available.} 
::msgcat::mcset fr {This function is not currently supported for this port.} 
::msgcat::mcset fr {Tickmarks} 
::msgcat::mcset fr {Tile Frames} 
::msgcat::mcset fr {Tile Parameters} 
::msgcat::mcset fr {Tile} 
::msgcat::mcset fr {Times} 
::msgcat::mcset fr {Titles} 
::msgcat::mcset fr {Title} 
::msgcat::mcset fr {Tophat} 
::msgcat::mcset fr {Topographic} 
::msgcat::mcset fr {Top} 
::msgcat::mcset fr {To} 
::msgcat::mcset fr {Transparency} 
::msgcat::mcset fr {Triangle} 
::msgcat::mcset fr {Type} 
::msgcat::mcset fr {URL} 
::msgcat::mcset fr {Unable to connect directly: using Web Proxy} 
::msgcat::mcset fr {Unable to create FOV Region, celestial WCS Required} 
::msgcat::mcset fr {Unable to determine date of observation} 
::msgcat::mcset fr {Unable to evaluate filter} 
::msgcat::mcset fr {Unable to find Footprint window} 
::msgcat::mcset fr {Unable to find PRISM window} 
::msgcat::mcset fr {Unable to find SIAP window} 
::msgcat::mcset fr {Unable to find URL column} 
::msgcat::mcset fr {Unable to find catalog window} 
::msgcat::mcset fr {Unable to find plot window} 
::msgcat::mcset fr {Unable to find web window} 
::msgcat::mcset fr {Unable to generate plot} 
::msgcat::mcset fr {Unable to load RGB image into a non-rgb frame} 
::msgcat::mcset fr {Unable to load compressed region file} 
::msgcat::mcset fr {Unable to load plot data} 
::msgcat::mcset fr {Unable to load region file} 
::msgcat::mcset fr {Unable to load} 
::msgcat::mcset fr {Unable to locate FOV Region} 
::msgcat::mcset fr {Unable to locate URL} 
::msgcat::mcset fr {Unable to match target with XPA Mime request} 
::msgcat::mcset fr {Unable to open file} 
::msgcat::mcset fr {Unable to save RGB image from a non-rgb frame} 
::msgcat::mcset fr {Undo} [encoding convertfrom iso8859-1 {Défaire}]
::msgcat::mcset fr {Unique} 
::msgcat::mcset fr {Unists} 
::msgcat::mcset fr {Units} 
::msgcat::mcset fr {Unknown Colormap} 
::msgcat::mcset fr {Unknown command} 
::msgcat::mcset fr {Update Filter} 
::msgcat::mcset fr {Update Group} 
::msgcat::mcset fr {Update from Current Crosshair} 
::msgcat::mcset fr {Update from Current Frame} 
::msgcat::mcset fr {Update} 
::msgcat::mcset fr {Upper Left Back} 
::msgcat::mcset fr {Upper Left Front} 
::msgcat::mcset fr {Upper Right Back} 
::msgcat::mcset fr {Upper Right Front} 
::msgcat::mcset fr {Use Authentication} 
::msgcat::mcset fr {Use Current Frame on Download} 
::msgcat::mcset fr {Use Internal Web Browser} 
::msgcat::mcset fr {Use Original Color/Width} 
::msgcat::mcset fr {Use Proxy} 
::msgcat::mcset fr {Use Theme Colors} 
::msgcat::mcset fr {Use background color instead of theme color} 
::msgcat::mcset fr {User Manual} 
::msgcat::mcset fr {Username} 
::msgcat::mcset fr {User} 
::msgcat::mcset fr {Use} 
::msgcat::mcset fr {VO Server} 
::msgcat::mcset fr {VOTable} 
::msgcat::mcset fr {VOT} 
::msgcat::mcset fr {VO} 
::msgcat::mcset fr {Value} 
::msgcat::mcset fr {Vector} 
::msgcat::mcset fr {Vertical Graph} 
::msgcat::mcset fr {Vertical Layout} 
::msgcat::mcset fr {Vertical Text} 
::msgcat::mcset fr {Vertical} 
::msgcat::mcset fr {View} {Affichage}
::msgcat::mcset fr {Virtual Observatory} 
::msgcat::mcset fr {WCS Parameters} 
::msgcat::mcset fr {WCS} 
::msgcat::mcset fr {Wavelength} 
::msgcat::mcset fr {Web Browser} 
::msgcat::mcset fr {White} 
::msgcat::mcset fr {Width} 
::msgcat::mcset fr {Window} 
::msgcat::mcset fr {Words matching title, description} 
::msgcat::mcset fr {X Axis Title} 
::msgcat::mcset fr {X Axis} 
::msgcat::mcset fr {X Column} 
::msgcat::mcset fr {X Error Column} 
::msgcat::mcset fr {XPA Information} 
::msgcat::mcset fr {XPA not initialized} 
::msgcat::mcset fr {XPA} 
::msgcat::mcset fr {X} 
::msgcat::mcset fr {Y Axis Title} 
::msgcat::mcset fr {Y Axis} 
::msgcat::mcset fr {Y Column} 
::msgcat::mcset fr {Y Error Column} 
::msgcat::mcset fr {Yellow} 
::msgcat::mcset fr {Y} 
::msgcat::mcset fr {Z Axis Scale} 
::msgcat::mcset fr {ZScale Parameters} 
::msgcat::mcset fr {Zero} 
::msgcat::mcset fr {Zoom Fit} 
::msgcat::mcset fr {Zoom In} 
::msgcat::mcset fr {Zoom Out} 
::msgcat::mcset fr {Zoom} 
::msgcat::mcset fr {already connected} 
::msgcat::mcset fr {and} 
::msgcat::mcset fr {b} 
::msgcat::mcset fr {g} 
::msgcat::mcset fr {h5utils} 
::msgcat::mcset fr {hundredths second} 
::msgcat::mcset fr {internal error} 
::msgcat::mcset fr {not connected} 
::msgcat::mcset fr {not} 
::msgcat::mcset fr {only} 
::msgcat::mcset fr {or center of data} 
::msgcat::mcset fr {rows of data have been downloaded. More may be available. You may wish to adjust the maximum allowed} 
::msgcat::mcset fr {r} 
::msgcat::mcset fr {unable to locate HUB} 
::msgcat::mcset fr {x} 
