::msgcat::mcset ja {2D} 
::msgcat::mcset ja {3D View} 
::msgcat::mcset ja {3D} [encoding convertfrom euc-jp "\x33\xbc\xa1\xb8\xb5"]
::msgcat::mcset ja {A postscript generation error has occurred} [encoding convertfrom euc-jp "\xa5\xdd\xa5\xb9\xa5\xc8\xa5\xb9\xa5\xaf\xa5\xea\xa5\xd7\xa5\xc8\xa5\xd5\xa5\xa1\xa5\xa4\xa5\xeb\xba\xee\xc0\xae\xa4\xcb\xbc\xba\xc7\xd4\xa4\xb7\xa4\xde\xa4\xb7\xa4\xbf\xa1\xa3"]
::msgcat::mcset ja {AIP} 
::msgcat::mcset ja {Abort} 
::msgcat::mcset ja {About SAOImageDS9} 
::msgcat::mcset ja {About} [encoding convertfrom euc-jp "\x44\x53\x39\x20\xa4\xcb\xa4\xc4\xa4\xa4\xa4\xc6"]
::msgcat::mcset ja {Acknowledgment} [encoding convertfrom euc-jp "\xbc\xd5\xbc\xad"]
::msgcat::mcset ja {Add Bar Graph} 
::msgcat::mcset ja {Add Graph} 
::msgcat::mcset ja {Add Line Graph} 
::msgcat::mcset ja {Add} [encoding convertfrom euc-jp "\xc4\xc9\xb2\xc3"]
::msgcat::mcset ja {Advanced} [encoding convertfrom euc-jp "\xb9\xe2\xc5\xd9\xa4\xca\xc0\xdf\xc4\xea"]
::msgcat::mcset ja {Align} [encoding convertfrom euc-jp "\xc0\xb0\xce\xf3"]
::msgcat::mcset ja {All Columns} [encoding convertfrom euc-jp "\xc1\xb4\xa4\xc6\xa4\xce\xce\xf3"]
::msgcat::mcset ja {All Rows} [encoding convertfrom euc-jp "\xc1\xb4\xa4\xc6\xa4\xce\xb9\xd4"]
::msgcat::mcset ja {All} [encoding convertfrom euc-jp "\xc1\xb4\xa4\xc6"]
::msgcat::mcset ja {Always save files during Backup} 
::msgcat::mcset ja {Amplifier} [encoding convertfrom euc-jp "\xc1\xfd\xc9\xfd\xb4\xef\xba\xc2\xc9\xb8"]
::msgcat::mcset ja {An error has occurred during backup} 
::msgcat::mcset ja {An error has occurred during restore} 
::msgcat::mcset ja {An error has occurred invoking the Analysis task} [encoding convertfrom euc-jp "\xb2\xf2\xc0\xcf\xa5\xbf\xa5\xb9\xa5\xaf\xa4\xce\xb5\xaf\xc6\xb0\xa4\xcb\xbc\xba\xc7\xd4\xa4\xb7\xa4\xde\xa4\xb7\xa4\xbf\xa1\xa3"]
::msgcat::mcset ja {An error has occurred while creating} 
::msgcat::mcset ja {An error has occurred while loading} 
::msgcat::mcset ja {An error has occurred while printing} [encoding convertfrom euc-jp "\xb0\xf5\xba\xfe\xa4\xcb\xbc\xba\xc7\xd4\xa4\xb7\xa4\xde\xa4\xb7\xa4\xbf\xa1\xa3"]
::msgcat::mcset ja {An error has occurred while saving} [encoding convertfrom euc-jp "\xca\xdd\xc2\xb8\xa4\xcb\xbc\xba\xc7\xd4\xa4\xb7\xa4\xde\xa4\xb7\xa4\xbf\xa1\xa3"]
::msgcat::mcset ja {An internal error has been detected} 
::msgcat::mcset ja {Analysis Command Log} [encoding convertfrom euc-jp "\xb2\xf2\xc0\xcf\xa5\xb3\xa5\xde\xa5\xf3\xa5\xc9\xa4\xce\xb5\xad\xcf\xbf"]
::msgcat::mcset ja {Analysis Commands} [encoding convertfrom euc-jp "\xb2\xf2\xc0\xcf\xa5\xb3\xa5\xde\xa5\xf3\xa5\xc9"]
::msgcat::mcset ja {Analysis File} 
::msgcat::mcset ja {Analysis Log} 
::msgcat::mcset ja {Analysis} [encoding convertfrom euc-jp "\xb2\xf2\xc0\xcf"]
::msgcat::mcset ja {Angle Complement} [encoding convertfrom euc-jp "\xca\xe4\xb3\xd1"]
::msgcat::mcset ja {Angles} [encoding convertfrom euc-jp "\xb3\xd1\xc5\xd9"]
::msgcat::mcset ja {Angle} [encoding convertfrom euc-jp "\xb3\xd1\xc5\xd9"]
::msgcat::mcset ja {Annuli} [encoding convertfrom euc-jp "\xc3\xe6\xc8\xb4\xa4\xad\xb1\xdf"]
::msgcat::mcset ja {Annulus} [encoding convertfrom euc-jp "\xc3\xe6\xc8\xb4\xa4\xad\xb1\xdf"]
::msgcat::mcset ja {Apply} [encoding convertfrom euc-jp "\xc5\xac\xcd\xd1"]
::msgcat::mcset ja {ArcMin} [encoding convertfrom euc-jp "\xca\xac"]
::msgcat::mcset ja {ArcSec} [encoding convertfrom euc-jp "\xc9\xc3"]
::msgcat::mcset ja {Architecture} [encoding convertfrom euc-jp "\xa5\xa2\xa1\xbc\xa5\xad\xa5\xc6\xa5\xaf\xa5\xc1\xa5\xe3"]
::msgcat::mcset ja {Archives} 
::msgcat::mcset ja {Array} 
::msgcat::mcset ja {Arrow} [encoding convertfrom euc-jp "\xcc\xf0\xb0\xf5"]
::msgcat::mcset ja {Asteroids} 
::msgcat::mcset ja {Astronomy} [encoding convertfrom euc-jp "\xc5\xb7\xca\xb8\xb3\xd8"]
::msgcat::mcset ja {At Startup} 
::msgcat::mcset ja {At least 2 different catalogs are required} 
::msgcat::mcset ja {Auto Centroid} [encoding convertfrom euc-jp "\xbc\xab\xc6\xb0\xc3\xe6\xbf\xb4\xb9\xe7\xa4\xef\xa4\xbb"]
::msgcat::mcset ja {Auto Plot 2D} 
::msgcat::mcset ja {Auto Plot 3D} 
::msgcat::mcset ja {Auto Plot Statistics} 
::msgcat::mcset ja {Auto Plot} 
::msgcat::mcset ja {Autoload FITS Regions} [encoding convertfrom euc-jp "\xce\xce\xb0\xe8\xa4\xce\xbc\xab\xc6\xb0\xc6\xc9\xa4\xdf\xb9\xfe\xa4\xdf"]
::msgcat::mcset ja {Autoload} 
::msgcat::mcset ja {Automatic} [encoding convertfrom euc-jp "\xbc\xab\xc6\xb0"]
::msgcat::mcset ja {Average} [encoding convertfrom euc-jp "\xca\xbf\xb6\xd1"]
::msgcat::mcset ja {Axes Number} 
::msgcat::mcset ja {Axes Order} 
::msgcat::mcset ja {Axes Range} 
::msgcat::mcset ja {Axes Title} 
::msgcat::mcset ja {Axes} [encoding convertfrom euc-jp "\xbc\xb4"]
::msgcat::mcset ja {Axis Length} [encoding convertfrom euc-jp "\xbc\xb4\xa4\xce\xc4\xb9\xa4\xb5"]
::msgcat::mcset ja {Axis Numbers} [encoding convertfrom euc-jp "\xbc\xb4\xa4\xce\xbf\xf4\xc3\xcd"]
::msgcat::mcset ja {Axis Title} 
::msgcat::mcset ja {Axis} [encoding convertfrom euc-jp "\xbc\xb4"]
::msgcat::mcset ja {Azimuth} [encoding convertfrom euc-jp "\xca\xfd\xb0\xcc\xb3\xd1"]
::msgcat::mcset ja {Background Color} [encoding convertfrom euc-jp "\xc7\xd8\xb7\xca\xbf\xa7"]
::msgcat::mcset ja {Background} [encoding convertfrom euc-jp "\xa5\xd0\xa5\xc3\xa5\xaf\xa5\xb0\xa5\xe9\xa5\xa6\xa5\xf3\xa5\xc9\xce\xce\xb0\xe8"]
::msgcat::mcset ja {Backup} 
::msgcat::mcset ja {Back} [encoding convertfrom euc-jp "\xc1\xb0"]
::msgcat::mcset ja {Bar Dataset} 
::msgcat::mcset ja {Bar Plot Tool} 
::msgcat::mcset ja {Bar Width} 
::msgcat::mcset ja {Bar} 
::msgcat::mcset ja {Behavior} 
::msgcat::mcset ja {Bias} [encoding convertfrom euc-jp "\xa5\xd0\xa5\xa4\xa5\xa2\xa5\xb9"]
::msgcat::mcset ja {Bin 3rd Column} [encoding convertfrom euc-jp "\xc2\xe8\xa3\xb3\xa4\xce\xce\xf3\xa4\xf2\xa5\xd3\xa5\xf3\xa4\xde\xa4\xc8\xa4\xe1"]
::msgcat::mcset ja {Bin Center} [encoding convertfrom euc-jp "\xa5\xd3\xa5\xf3\xa4\xde\xa4\xc8\xa4\xe1\xa4\xce\xc3\xe6\xbf\xb4"]
::msgcat::mcset ja {Bin Columns} [encoding convertfrom euc-jp "\xa5\xd3\xa5\xf3\xa4\xde\xa4\xc8\xa4\xe1\xa4\xb9\xa4\xeb\xce\xf3"]
::msgcat::mcset ja {Bin Filter} [encoding convertfrom euc-jp "\xa5\xd3\xa5\xf3\xa4\xde\xa4\xc8\xa4\xe1\xa4\xce\xb9\xca\xa4\xea\xb9\xfe\xa4\xdf\xbe\xf2\xb7\xef"]
::msgcat::mcset ja {Bin Fit} 
::msgcat::mcset ja {Bin In} 
::msgcat::mcset ja {Bin Out} 
::msgcat::mcset ja {Binning Parameters} [encoding convertfrom euc-jp "\xa5\xd3\xa5\xf3\xa4\xde\xa4\xc8\xa4\xe1\xa4\xce\xc0\xdf\xc4\xea"]
::msgcat::mcset ja {Bins} 
::msgcat::mcset ja {Bin} [encoding convertfrom euc-jp "\xa5\xd3\xa5\xf3\xa4\xde\xa4\xc8\xa4\xe1"]
::msgcat::mcset ja {Black} [encoding convertfrom euc-jp "\xb9\xf5\xbf\xa7"]
::msgcat::mcset ja {Blank/Inf/NaN Color} [encoding convertfrom euc-jp "\xcc\xa4\xc4\xea\xb5\xc1\xc3\xcd\x28\x42\x6c\x61\x6e\x6b\x2f\x49\x6e\x66\x2f\x4e\x61\x4e\x29\xa4\xce\xbf\xa7"]
::msgcat::mcset ja {Blend} 
::msgcat::mcset ja {Blink Frames} [encoding convertfrom euc-jp "\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0\xa4\xf2\xa5\xd6\xa5\xea\xa5\xf3\xa5\xaf"]
::msgcat::mcset ja {Blink Interval} [encoding convertfrom euc-jp "\xa5\xd6\xa5\xea\xa5\xf3\xa5\xaf\xa4\xce\xb4\xd6\xb3\xd6"]
::msgcat::mcset ja {Blink} [encoding convertfrom euc-jp "\xa5\xd6\xa5\xea\xa5\xf3\xa5\xaf"]
::msgcat::mcset ja {Block Fit} 
::msgcat::mcset ja {Block In} [encoding convertfrom euc-jp "\xa5\xd6\xa5\xed\xa5\xc3\xa5\xaf\xa4\xf2\xba\xd9\xa4\xab\xa4\xaf"]
::msgcat::mcset ja {Block Out} [encoding convertfrom euc-jp "\xa5\xd6\xa5\xed\xa5\xc3\xa5\xaf\xa4\xf2\xb9\xd3\xa4\xaf"]
::msgcat::mcset ja {Block Parameters} 
::msgcat::mcset ja {Block Pixel} 
::msgcat::mcset ja {Block} [encoding convertfrom euc-jp "\xa5\xd6\xa5\xed\xa5\xc3\xa5\xaf"]
::msgcat::mcset ja {Blue} [encoding convertfrom euc-jp "\xc0\xc4\xbf\xa7"]
::msgcat::mcset ja {Bold} [encoding convertfrom euc-jp "\xc2\xc0\xbb\xfa"]
::msgcat::mcset ja {Border Color} 
::msgcat::mcset ja {Border Width} 
::msgcat::mcset ja {Border} [encoding convertfrom euc-jp "\xcf\xc8\xc0\xfe"]
::msgcat::mcset ja {Bottom} 
::msgcat::mcset ja {Box Annulus} [encoding convertfrom euc-jp "\xc3\xe6\xc8\xb4\xa4\xad\xbb\xcd\xb3\xd1\xb7\xc1"]
::msgcat::mcset ja {Box Panda} [encoding convertfrom euc-jp "\xc9\xf4\xca\xac\xbb\xcd\xb3\xd1\xb7\xc1"]
::msgcat::mcset ja {BoxCircle} 
::msgcat::mcset ja {Boxcar} [encoding convertfrom euc-jp "\xa5\xdc\xa5\xc3\xa5\xaf\xa5\xb9\xa5\xab\xa1\xbc"]
::msgcat::mcset ja {Box} [encoding convertfrom euc-jp "\xbb\xcd\xb3\xd1\xb7\xc1"]
::msgcat::mcset ja {Broadcast} 
::msgcat::mcset ja {Browser} 
::msgcat::mcset ja {Browse} [encoding convertfrom euc-jp "\xbb\xb2\xbe\xc8"]
::msgcat::mcset ja {Buffer} [encoding convertfrom euc-jp "\xa5\xd0\xa5\xc3\xa5\xd5\xa5\xa1"]
::msgcat::mcset ja {Buttonbar} [encoding convertfrom euc-jp "\xa5\xdc\xa5\xbf\xa5\xf3\xa5\xd0\xa1\xbc"]
::msgcat::mcset ja {Buttons} [encoding convertfrom euc-jp "\xa5\xdc\xa5\xbf\xa5\xf3"]
::msgcat::mcset ja {Bytes} [encoding convertfrom euc-jp "\xa5\xd0\xa5\xa4\xa5\xc8"]
::msgcat::mcset ja {CMYK} [encoding convertfrom euc-jp "\x43\x4d\x59\x4b\xbf\xa7"]
::msgcat::mcset ja {Can Delete} [encoding convertfrom euc-jp "\xba\xef\xbd\xfc\xb2\xc4"]
::msgcat::mcset ja {Can Edit} [encoding convertfrom euc-jp "\xca\xd4\xbd\xb8\xb2\xc4"]
::msgcat::mcset ja {Can Move} [encoding convertfrom euc-jp "\xb0\xdc\xc6\xb0\xb2\xc4"]
::msgcat::mcset ja {Can Rotate} [encoding convertfrom euc-jp "\xb2\xf3\xc5\xbe\xb2\xc4"]
::msgcat::mcset ja {Cancelled} 
::msgcat::mcset ja {Cancel} [encoding convertfrom euc-jp "\xbc\xe8\xa4\xea\xbe\xc3\xa4\xb7"]
::msgcat::mcset ja {Cap} 
::msgcat::mcset ja {Catalog Server} [encoding convertfrom euc-jp "\xa5\xab\xa5\xbf\xa5\xed\xa5\xb0\xb8\xa1\xba\xf7\xa5\xb5\xa1\xbc\xa5\xd0\xa1\xbc"]
::msgcat::mcset ja {Catalog Tool} [encoding convertfrom euc-jp "\xa5\xab\xa5\xbf\xa5\xed\xa5\xb0\xa5\xc4\xa1\xbc\xa5\xeb"]
::msgcat::mcset ja {Catalogs} [encoding convertfrom euc-jp "\xa5\xab\xa5\xbf\xa5\xed\xa5\xb0"]
::msgcat::mcset ja {Catalog} [encoding convertfrom euc-jp "\xa5\xab\xa5\xbf\xa5\xed\xa5\xb0"]
::msgcat::mcset ja {Catrom} 
::msgcat::mcset ja {Cat} 
::msgcat::mcset ja {Center Dialogs} 
::msgcat::mcset ja {Center Image} [encoding convertfrom euc-jp "\xa5\xa4\xa5\xe1\xa1\xbc\xa5\xb8\xa4\xf2\xc3\xe6\xbf\xb4\xa4\xcb"]
::msgcat::mcset ja {Center} [encoding convertfrom euc-jp "\xc3\xe6\xbf\xb4"]
::msgcat::mcset ja {Centroid Parameters} [encoding convertfrom euc-jp "\xc3\xe6\xbf\xb4\xb9\xe7\xa4\xef\xa4\xbb\xc0\xdf\xc4\xea"]
::msgcat::mcset ja {Centroid} 
::msgcat::mcset ja {Circle} [encoding convertfrom euc-jp "\xb1\xdf"]
::msgcat::mcset ja {Clear All} [encoding convertfrom euc-jp "\xc1\xb4\xa4\xc6\xbe\xc3\xb5\xee"]
::msgcat::mcset ja {Clear Analysis Commands} [encoding convertfrom euc-jp "\xb2\xf2\xc0\xcf\xa5\xb3\xa5\xde\xa5\xf3\xa5\xc9\xa4\xf2\xbe\xc3\xb5\xee"]
::msgcat::mcset ja {Clear Cache} [encoding convertfrom euc-jp "\xa5\xad\xa5\xe3\xa5\xc3\xa5\xb7\xa5\xe5\xa4\xf2\xbe\xc3\xb5\xee"]
::msgcat::mcset ja {Clear External Analysis Commands?} [encoding convertfrom euc-jp "\xb3\xb0\xc9\xf4\xb2\xf2\xc0\xcf\xa5\xb3\xa5\xde\xa5\xf3\xa5\xc9\xa4\xf2\xbe\xc3\xb5\xee\xa4\xb7\xa4\xde\xa4\xb9\xa4\xab\x3f"]
::msgcat::mcset ja {Clear Filter} [encoding convertfrom euc-jp "\xb9\xca\xa4\xea\xb9\xfe\xa4\xdf\xbe\xf2\xb7\xef\xa4\xf2\xbe\xc3\xb5\xee"]
::msgcat::mcset ja {Clear Frame} [encoding convertfrom euc-jp "\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0\xa4\xf2\xbe\xc3\xb5\xee"]
::msgcat::mcset ja {Clear Preferences?} [encoding convertfrom euc-jp "\xc0\xdf\xc4\xea\xa4\xf2\xbe\xc3\xb5\xee\xa4\xb7\xa4\xde\xa4\xb9\xa4\xab\x3f"]
::msgcat::mcset ja {Clear Preferences} [encoding convertfrom euc-jp "\xc0\xdf\xc4\xea\xa4\xf2\xbe\xc3\xb5\xee"]
::msgcat::mcset ja {Clear} [encoding convertfrom euc-jp "\xa5\xaf\xa5\xea\xa5\xa2"]
::msgcat::mcset ja {Click to Center} [encoding convertfrom euc-jp "\xa5\xaf\xa5\xea\xa5\xc3\xa5\xaf\xb0\xcc\xc3\xd6\xa4\xf2\xc3\xe6\xbf\xb4"]
::msgcat::mcset ja {Close} [encoding convertfrom euc-jp "\xca\xc4\xa4\xb8\xa4\xeb"]
::msgcat::mcset ja {Colorbar Size} 
::msgcat::mcset ja {Colorbar} [encoding convertfrom euc-jp "\xc7\xdb\xbf\xa7\xcb\xc0"]
::msgcat::mcset ja {Colormap Parameters} [encoding convertfrom euc-jp "\xbf\xa7\xc4\xb4\xa4\xce\xc0\xdf\xc4\xea"]
::msgcat::mcset ja {Colormap} [encoding convertfrom euc-jp "\xbf\xa7\xc4\xb4"]
::msgcat::mcset ja {Color} [encoding convertfrom euc-jp "\xbf\xa7"]
::msgcat::mcset ja {Columns} [encoding convertfrom euc-jp "\xce\xf3"]
::msgcat::mcset ja {Column} [encoding convertfrom euc-jp "\xce\xf3"]
::msgcat::mcset ja {Comets} 
::msgcat::mcset ja {Command not allowed} 
::msgcat::mcset ja {Command} [encoding convertfrom euc-jp "\xa5\xb3\xa5\xde\xa5\xf3\xa5\xc9"]
::msgcat::mcset ja {Compass} [encoding convertfrom euc-jp "\xca\xfd\xb0\xcc\xbc\xa7\xc0\xd0"]
::msgcat::mcset ja {Composite Region} [encoding convertfrom euc-jp "\xca\xa3\xb9\xe7\xce\xce\xb0\xe8"]
::msgcat::mcset ja {Composite} 
::msgcat::mcset ja {Compression} [encoding convertfrom euc-jp "\xb0\xb5\xbd\xcc"]
::msgcat::mcset ja {Configure} [encoding convertfrom euc-jp "\xc0\xdf\xc4\xea"]
::msgcat::mcset ja {Connect SAMP} 
::msgcat::mcset ja {Connect} [encoding convertfrom euc-jp "\xc0\xdc\xc2\xb3"]
::msgcat::mcset ja {Console} 
::msgcat::mcset ja {Contacting Server} 
::msgcat::mcset ja {Contour Parameters} [encoding convertfrom euc-jp "\xa5\xb3\xa5\xf3\xa5\xc8\xa5\xa2\xa4\xce\xc0\xdf\xc4\xea"]
::msgcat::mcset ja {Contour Paste} 
::msgcat::mcset ja {Contour Save} 
::msgcat::mcset ja {Contours} [encoding convertfrom euc-jp "\xa5\xb3\xa5\xf3\xa5\xc8\xa5\xa2"]
::msgcat::mcset ja {Contour} 
::msgcat::mcset ja {Contrast} [encoding convertfrom euc-jp "\xa5\xb3\xa5\xf3\xa5\xc8\xa5\xe9\xa5\xb9\xa5\xc8"]
::msgcat::mcset ja {Control Panel} 
::msgcat::mcset ja {Convert to Polygons} [encoding convertfrom euc-jp "\xc2\xbf\xb3\xd1\xb7\xc1\xa4\xcb\xca\xd1\xb4\xb9"]
::msgcat::mcset ja {Coordinate Grid Parameters} [encoding convertfrom euc-jp "\xba\xc2\xc9\xb8\xa5\xb0\xa5\xea\xa5\xc3\xa5\xc9\xa4\xce\xc0\xdf\xc4\xea"]
::msgcat::mcset ja {Coordinate Grid} [encoding convertfrom euc-jp "\xba\xc2\xc9\xb8\xa5\xb0\xa5\xea\xa5\xc3\xa5\xc9"]
::msgcat::mcset ja {Coordinate System} [encoding convertfrom euc-jp "\xba\xc2\xc9\xb8\xb7\xcf"]
::msgcat::mcset ja {Coordinates} [encoding convertfrom euc-jp "\xba\xc2\xc9\xb8"]
::msgcat::mcset ja {Coordinate} [encoding convertfrom euc-jp "\xba\xc2\xc9\xb8"]
::msgcat::mcset ja {Copy Contours} [encoding convertfrom euc-jp "\xa5\xb3\xa5\xf3\xa5\xc8\xa5\xa2\xa4\xf2\xa5\xb3\xa5\xd4\xa1\xbc"]
::msgcat::mcset ja {Copy to Regions} [encoding convertfrom euc-jp "\xce\xce\xb0\xe8\xa4\xcb\xa5\xb3\xa5\xd4\xa1\xbc"]
::msgcat::mcset ja {Copy} [encoding convertfrom euc-jp "\xa5\xb3\xa5\xd4\xa1\xbc"]
::msgcat::mcset ja {Create Movie} 
::msgcat::mcset ja {Create New Frame on Download} [encoding convertfrom euc-jp "\xa5\xc0\xa5\xa6\xa5\xf3\xa5\xed\xa1\xbc\xa5\xc9\xbb\xfe\xa4\xcb\xbf\xb7\xa4\xb7\xa4\xa4\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0\xa4\xf2\xba\xee\xc0\xae"]
::msgcat::mcset ja {Create} [encoding convertfrom euc-jp "\xba\xee\xc0\xae"]
::msgcat::mcset ja {Crop Parameters} 
::msgcat::mcset ja {Crop} 
::msgcat::mcset ja {Crosshair Parameters} 
::msgcat::mcset ja {Crosshair To} [encoding convertfrom euc-jp "\xa4\xbd\xa4\xb3\xa4\xcb\xbd\xbd\xbb\xfa\xc0\xfe"]
::msgcat::mcset ja {Crosshair} [encoding convertfrom euc-jp "\xbd\xbd\xbb\xfa\xa5\xab\xa1\xbc\xa5\xbd\xa5\xeb"]
::msgcat::mcset ja {Cross} [encoding convertfrom euc-jp "\xbd\xbd\xbb\xfa"]
::msgcat::mcset ja {Cubehelix} 
::msgcat::mcset ja {Cube} 
::msgcat::mcset ja {Cubic} 
::msgcat::mcset ja {Current Frame} [encoding convertfrom euc-jp "\xc1\xaa\xc2\xf2\xc3\xe6\xa4\xce\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0"]
::msgcat::mcset ja {Current Range} [encoding convertfrom euc-jp "\xc1\xaa\xc2\xf2\xc3\xe6\xa4\xce\xc8\xcf\xb0\xcf"]
::msgcat::mcset ja {Current} [encoding convertfrom euc-jp "\xc1\xaa\xc2\xf2\xc3\xe6"]
::msgcat::mcset ja {Cursor} [encoding convertfrom euc-jp "\xa5\xab\xa1\xbc\xa5\xbd\xa5\xeb"]
::msgcat::mcset ja {Cut} [encoding convertfrom euc-jp "\xc0\xda\xa4\xea\xbc\xe8\xa4\xea"]
::msgcat::mcset ja {Cyan} [encoding convertfrom euc-jp "\xbf\xe5\xbf\xa7"]
::msgcat::mcset ja {DMS} 
::msgcat::mcset ja {DPI} 
::msgcat::mcset ja {DS9 has detected a newer version of a backup file and therefore will not process this file.} 
::msgcat::mcset ja {DS9 has detected a newer version of a preferences file.} 
::msgcat::mcset ja {DS9 has detected an older backup file, do you wish to continue?} 
::msgcat::mcset ja {DS9 has detected an older preferences file, do you wish to update?} [encoding convertfrom euc-jp "\xb8\xc5\xa4\xa4\xa5\xd0\xa1\xbc\xa5\xb8\xa5\xe7\xa5\xf3\xa4\xce\xc0\xdf\xc4\xea\xa5\xd5\xa5\xa1\xa5\xa4\xa5\xeb\xa4\xac\xb8\xab\xa4\xc4\xa4\xab\xa4\xea\xa4\xde\xa4\xb7\xa4\xbf\xa1\xa3\xb9\xb9\xbf\xb7\xa4\xb7\xa4\xde\xa4\xb9\xa4\xab\x3f"]
::msgcat::mcset ja {DS9 will complete the initialization process} [encoding convertfrom euc-jp "\xbd\xe9\xb4\xfc\xb2\xbd\xa4\xf2\xb4\xb0\xce\xbb\xa4\xb7\xa4\xde\xa4\xb9\xa1\xa3"]
::msgcat::mcset ja {Darken} 
::msgcat::mcset ja {Dash} [encoding convertfrom euc-jp "\xc7\xcb\xc0\xfe"]
::msgcat::mcset ja {Data Format} [encoding convertfrom euc-jp "\xa5\xc7\xa1\xbc\xa5\xbf\xb7\xc1\xbc\xb0"]
::msgcat::mcset ja {Data must be ascii numeric values} 
::msgcat::mcset ja {Dataset Name} 
::msgcat::mcset ja {Dataset} [encoding convertfrom euc-jp "\xa5\xc7\xa1\xbc\xa5\xbf\xa5\xbb\xa5\xc3\xa5\xc8"]
::msgcat::mcset ja {Data} 
::msgcat::mcset ja {Decrease} [encoding convertfrom euc-jp "\xb9\xdf\xbd\xe7"]
::msgcat::mcset ja {Default All Files} 
::msgcat::mcset ja {Default Format} 
::msgcat::mcset ja {Default Length} 
::msgcat::mcset ja {Default} [encoding convertfrom euc-jp "\xc9\xb8\xbd\xe0"]
::msgcat::mcset ja {Degrees} [encoding convertfrom euc-jp "\xc5\xd9"]
::msgcat::mcset ja {Delay} 
::msgcat::mcset ja {Delete All Frames?} [encoding convertfrom euc-jp "\xc1\xb4\xa4\xc6\xa4\xce\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0\xa4\xf2\xbe\xc3\xb5\xee\xa4\xb7\xa4\xde\xa4\xb9\xa4\xab\x3f"]
::msgcat::mcset ja {Delete All Frames} [encoding convertfrom euc-jp "\xc1\xb4\xa4\xc6\xa4\xce\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0\xa4\xf2\xbe\xc3\xb5\xee"]
::msgcat::mcset ja {Delete All Groups?} [encoding convertfrom euc-jp "\xc1\xb4\xa4\xc6\xa4\xce\xa5\xb0\xa5\xeb\xa1\xbc\xa5\xd7\xa4\xf2\xbe\xc3\xb5\xee\xa4\xb7\xa4\xde\xa4\xb9\xa4\xab\x3f"]
::msgcat::mcset ja {Delete All Groups} [encoding convertfrom euc-jp "\xc1\xb4\xa4\xc6\xa4\xce\xa5\xb0\xa5\xeb\xa1\xbc\xa5\xd7\xa4\xf2\xbe\xc3\xb5\xee"]
::msgcat::mcset ja {Delete All} [encoding convertfrom euc-jp "\xc1\xb4\xa4\xc6\xa4\xf2\xbe\xc3\xb5\xee"]
::msgcat::mcset ja {Delete Color Tags} 
::msgcat::mcset ja {Delete Dataset} 
::msgcat::mcset ja {Delete Frame} [encoding convertfrom euc-jp "\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0\xa4\xf2\xbe\xc3\xb5\xee"]
::msgcat::mcset ja {Delete Graph} 
::msgcat::mcset ja {Delete Group} [encoding convertfrom euc-jp "\xa5\xb0\xa5\xeb\xa1\xbc\xa5\xd7\xa4\xf2\xbe\xc3\xb5\xee"]
::msgcat::mcset ja {Delete Load} 
::msgcat::mcset ja {Delete Regions?} 
::msgcat::mcset ja {Delete Regions} 
::msgcat::mcset ja {Delete Selected Regions} [encoding convertfrom euc-jp "\xc1\xaa\xc2\xf2\xa4\xb7\xa4\xbf\xce\xce\xb0\xe8\xa4\xf2\xba\xef\xbd\xfc"]
::msgcat::mcset ja {Delete Select} 
::msgcat::mcset ja {Delete and Open Regions} 
::msgcat::mcset ja {Delete} [encoding convertfrom euc-jp "\xbe\xc3\xb5\xee"]
::msgcat::mcset ja {Depth} [encoding convertfrom euc-jp "\xbf\xbc\xa4\xb5"]
::msgcat::mcset ja {Detector} [encoding convertfrom euc-jp "\xb8\xa1\xbd\xd0\xb4\xef\xba\xc2\xc9\xb8"]
::msgcat::mcset ja {Dialog Box} [encoding convertfrom euc-jp "\xa5\xdd\xa5\xc3\xa5\xd7\xa5\xa2\xa5\xc3\xa5\xd7\xa5\xe1\xa5\xcb\xa5\xe5\xa1\xbc"]
::msgcat::mcset ja {Diameter} 
::msgcat::mcset ja {Diamond} [encoding convertfrom euc-jp "\xc9\xa9\xb7\xc1"]
::msgcat::mcset ja {Dimensions} 
::msgcat::mcset ja {Dimension} [encoding convertfrom euc-jp "\xbc\xa1\xb8\xb5"]
::msgcat::mcset ja {Direction} 
::msgcat::mcset ja {Disconnect} [encoding convertfrom euc-jp "\xc0\xdc\xc2\xb3\xbd\xaa\xce\xbb"]
::msgcat::mcset ja {Display Size} [encoding convertfrom euc-jp "\xa5\xb5\xa5\xa4\xa5\xba\xa4\xf2\xc9\xbd\xbc\xa8"]
::msgcat::mcset ja {Dissolve} [encoding convertfrom euc-jp "\xca\xac\xb2\xf2"]
::msgcat::mcset ja {Distance} 
::msgcat::mcset ja {Done} 
::msgcat::mcset ja {Download Colormap} 
::msgcat::mcset ja {Drag to Center} [encoding convertfrom euc-jp "\xc3\xe6\xbf\xb4\xa4\xcb\xa5\xc9\xa5\xe9\xa5\xc3\xa5\xb0"]
::msgcat::mcset ja {Duplicate Dataset} 
::msgcat::mcset ja {ENVI} 
::msgcat::mcset ja {EPS} 
::msgcat::mcset ja {East} [encoding convertfrom euc-jp "\xc5\xec"]
::msgcat::mcset ja {Ecliptic} [encoding convertfrom euc-jp "\xb2\xab\xc6\xbb\xba\xc2\xc9\xb8"]
::msgcat::mcset ja {Edit Group Name} [encoding convertfrom euc-jp "\xa5\xb0\xa5\xeb\xa1\xbc\xa5\xd7\xcc\xbe\xa4\xf2\xca\xd1\xb9\xb9"]
::msgcat::mcset ja {Edit} [encoding convertfrom euc-jp "\xca\xd4\xbd\xb8"]
::msgcat::mcset ja {Elevation} [encoding convertfrom euc-jp "\xb9\xe2\xc5\xd9"]
::msgcat::mcset ja {Ellipse Panda} [encoding convertfrom euc-jp "\xc9\xf4\xca\xac\xc2\xca\xb1\xdf"]
::msgcat::mcset ja {Ellipse} [encoding convertfrom euc-jp "\xc2\xca\xb1\xdf"]
::msgcat::mcset ja {Elliptical Annulus} [encoding convertfrom euc-jp "\xc3\xe6\xc8\xb4\xa4\xad\xc2\xca\xb1\xdf"]
::msgcat::mcset ja {Elliptical Gaussian} 
::msgcat::mcset ja {Elliptical Panda} [encoding convertfrom euc-jp "\xc3\xe6\xc8\xb4\xa4\xad\xc9\xf4\xca\xac\xc2\xca\xb1\xdf"]
::msgcat::mcset ja {Enable Confirmation Dialogs} [encoding convertfrom euc-jp "\xb3\xce\xc7\xa7\xa5\xe1\xa5\xc3\xa5\xbb\xa1\xbc\xa5\xb8\xa4\xf2\xc9\xbd\xbc\xa8"]
::msgcat::mcset ja {Enable} 
::msgcat::mcset ja {End} [encoding convertfrom euc-jp "\xbd\xaa\xce\xbb"]
::msgcat::mcset ja {Enter Color} [encoding convertfrom euc-jp "\xbf\xa7\xa4\xf2\xc6\xfe\xce\xcf"]
::msgcat::mcset ja {Enter Font Size} 
::msgcat::mcset ja {Enter Group Name} [encoding convertfrom euc-jp "\xa5\xb0\xa5\xeb\xa1\xbc\xa5\xd7\xcc\xbe\xa4\xf2\xc6\xfe\xce\xcf"]
::msgcat::mcset ja {Enter Search Expression} [encoding convertfrom euc-jp "\xb8\xa1\xba\xf7\xbe\xf2\xb7\xef\xa4\xf2\xc6\xfe\xce\xcf"]
::msgcat::mcset ja {Enter URL} 
::msgcat::mcset ja {Entry} 
::msgcat::mcset ja {Equal Area} [encoding convertfrom euc-jp "\xc5\xf9\xcc\xcc\xc0\xd1"]
::msgcat::mcset ja {Equal Distance} [encoding convertfrom euc-jp "\xc5\xf9\xb5\xf7\xce\xa5"]
::msgcat::mcset ja {Equal Spacing} 
::msgcat::mcset ja {Equal Value} 
::msgcat::mcset ja {Error code was returned} [encoding convertfrom euc-jp "\xa5\xa8\xa5\xe9\xa1\xbc\xa5\xb3\xa1\xbc\xa5\xc9\xa4\xac\xca\xd6\xa4\xb5\xa4\xec\xa4\xde\xa4\xb7\xa4\xbf\xa1\xa3"]
::msgcat::mcset ja {Errorbar} 
::msgcat::mcset ja {Error} [encoding convertfrom euc-jp "\xa5\xa8\xa5\xe9\xa1\xbc"]
::msgcat::mcset ja {Examine Frame} [encoding convertfrom euc-jp "\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0\xa4\xf2\xbe\xdc\xba\xd9\xc9\xbd\xbc\xa8"]
::msgcat::mcset ja {Examine} [encoding convertfrom euc-jp "\xbe\xdc\xba\xd9\xc9\xbd\xbc\xa8"]
::msgcat::mcset ja {Exam} 
::msgcat::mcset ja {Exclude} [encoding convertfrom euc-jp "\xb3\xb0\xc2\xa6"]
::msgcat::mcset ja {Exit} [encoding convertfrom euc-jp "\xbd\xaa\xce\xbb"]
::msgcat::mcset ja {Export Array} 
::msgcat::mcset ja {Export ENVI} 
::msgcat::mcset ja {Export GIF} 
::msgcat::mcset ja {Export JPEG} 
::msgcat::mcset ja {Export NRRD} 
::msgcat::mcset ja {Export PNG} 
::msgcat::mcset ja {Export RGB Array} 
::msgcat::mcset ja {Export TIFF} 
::msgcat::mcset ja {Export} 
::msgcat::mcset ja {Extension Data} 
::msgcat::mcset ja {Extension not found} 
::msgcat::mcset ja {Extensions} 
::msgcat::mcset ja {Extension} 
::msgcat::mcset ja {Exterior Axes} [encoding convertfrom euc-jp "\xbc\xb4\xa4\xf2\xb3\xb0\xc2\xa6\xa4\xcb"]
::msgcat::mcset ja {Exterior Numerics} [encoding convertfrom euc-jp "\xbf\xf4\xc3\xcd\xa4\xf2\xb3\xb0\xc2\xa6\xa4\xcb"]
::msgcat::mcset ja {FAQ} [encoding convertfrom euc-jp "\xa4\xe8\xa4\xaf\xa4\xa2\xa4\xeb\xbc\xc1\xcc\xe4\xa4\xc8\xc5\xfa\xa4\xa8"]
::msgcat::mcset ja {FITS} 
::msgcat::mcset ja {FK4} 
::msgcat::mcset ja {FK5} 
::msgcat::mcset ja {FP} 
::msgcat::mcset ja {Factor} 
::msgcat::mcset ja {File not Found or Unable to load FITS data MIME type} [encoding convertfrom euc-jp "\xa5\xd5\xa5\xa1\xa5\xa4\xa5\xeb\xa4\xac\xb8\xab\xa4\xc4\xa4\xab\xa4\xea\xa4\xde\xa4\xbb\xa4\xf3\xa1\xa3\xa4\xde\xa4\xbf\xa4\xcf\xa1\xa2\x46\x49\x54\x53\x20\xa5\xc7\xa1\xbc\xa5\xbf\xa4\xac\xc6\xc9\xa4\xdf\xb9\xfe\xa4\xe1\xa4\xde\xa4\xbb\xa4\xf3\xa1\xa3"]
::msgcat::mcset ja {File not found} 
::msgcat::mcset ja {Filename} [encoding convertfrom euc-jp "\xa5\xd5\xa5\xa1\xa5\xa4\xa5\xeb\xcc\xbe"]
::msgcat::mcset ja {File} [encoding convertfrom euc-jp "\xa5\xd5\xa5\xa1\xa5\xa4\xa5\xeb"]
::msgcat::mcset ja {Fill} 
::msgcat::mcset ja {Filter} [encoding convertfrom euc-jp "\xb9\xca\xa4\xea\xb9\xfe\xa4\xdf"]
::msgcat::mcset ja {Find Next} [encoding convertfrom euc-jp "\xbc\xa1\xa4\xf2\xb8\xa1\xba\xf7"]
::msgcat::mcset ja {Find} [encoding convertfrom euc-jp "\xb8\xa1\xba\xf7"]
::msgcat::mcset ja {First Block} 
::msgcat::mcset ja {First Frame} [encoding convertfrom euc-jp "\xba\xc7\xbd\xe9\xa4\xce\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0"]
::msgcat::mcset ja {First} [encoding convertfrom euc-jp "\xba\xc7\xbd\xe9"]
::msgcat::mcset ja {Fits} 
::msgcat::mcset ja {Fixed in Size} [encoding convertfrom euc-jp "\xa5\xb5\xa5\xa4\xa5\xba\xb8\xc7\xc4\xea"]
::msgcat::mcset ja {Flip} 
::msgcat::mcset ja {Font} [encoding convertfrom euc-jp "\xa5\xd5\xa5\xa9\xa5\xf3\xa5\xc8"]
::msgcat::mcset ja {Footprint Servers} 
::msgcat::mcset ja {Footprint} 
::msgcat::mcset ja {For more information, use --help} [encoding convertfrom euc-jp "\xbe\xdc\xa4\xb7\xa4\xaf\xa4\xcf\x20\x2d\x2d\x68\x65\x6c\x70\x20\xa5\xaa\xa5\xd7\xa5\xb7\xa5\xe7\xa5\xf3\xa4\xc7\xa1\xa3"]
::msgcat::mcset ja {Foreground} 
::msgcat::mcset ja {Forground} 
::msgcat::mcset ja {Format} [encoding convertfrom euc-jp "\xb7\xc1\xbc\xb0"]
::msgcat::mcset ja {Forward} [encoding convertfrom euc-jp "\xbc\xa1"]
::msgcat::mcset ja {Found} 
::msgcat::mcset ja {Frame Information} [encoding convertfrom euc-jp "\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0\xa4\xce\xbe\xf0\xca\xf3"]
::msgcat::mcset ja {Frame Parameters} [encoding convertfrom euc-jp "\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0\xa4\xce\xc0\xdf\xc4\xea"]
::msgcat::mcset ja {Frames} 
::msgcat::mcset ja {Frame} [encoding convertfrom euc-jp "\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0"]
::msgcat::mcset ja {From} 
::msgcat::mcset ja {Front} [encoding convertfrom euc-jp "\xc1\xb4\xcc\xcc"]
::msgcat::mcset ja {Full Range} [encoding convertfrom euc-jp "\xc1\xb4\xc8\xcf\xb0\xcf"]
::msgcat::mcset ja {Function} [encoding convertfrom euc-jp "\xb4\xd8\xbf\xf4"]
::msgcat::mcset ja {GIF} 
::msgcat::mcset ja {GUI} 
::msgcat::mcset ja {Galactic} [encoding convertfrom euc-jp "\xb6\xe4\xb2\xcf\xba\xc2\xc9\xb8"]
::msgcat::mcset ja {Gap} 
::msgcat::mcset ja {Gaussian} [encoding convertfrom euc-jp "\xa5\xac\xa5\xa6\xa5\xb7\xa5\xa2\xa5\xf3"]
::msgcat::mcset ja {General} [encoding convertfrom euc-jp "\xb0\xec\xc8\xcc"]
::msgcat::mcset ja {Generate} [encoding convertfrom euc-jp "\xc0\xb8\xc0\xae"]
::msgcat::mcset ja {Generating Regions} [encoding convertfrom euc-jp "\xce\xce\xb0\xe8\xa4\xf2\xba\xee\xc0\xae\xc3\xe6"]
::msgcat::mcset ja {Get Information} [encoding convertfrom euc-jp "\xbe\xf0\xca\xf3\xa4\xf2\xbc\xe8\xc6\xc0"]
::msgcat::mcset ja {Gist} 
::msgcat::mcset ja {Global Properties} [encoding convertfrom euc-jp "\xa5\xb0\xa5\xed\xa1\xbc\xa5\xd0\xa5\xeb\xa5\xd7\xa5\xed\xa5\xd1\xa5\xc6\xa5\xa3"]
::msgcat::mcset ja {Global} [encoding convertfrom euc-jp "\xa5\xb0\xa5\xed\xa1\xbc\xa5\xd0\xa5\xeb"]
::msgcat::mcset ja {Goto Frame} [encoding convertfrom euc-jp "\xbb\xd8\xc4\xea\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0\xa4\xcb\xb0\xdc\xc6\xb0"]
::msgcat::mcset ja {Goto Row} 
::msgcat::mcset ja {Goto} 
::msgcat::mcset ja {Graph Horz} [encoding convertfrom euc-jp "\xb2\xa3\xc3\xc7\xcc\xcc\xbf\xde"]
::msgcat::mcset ja {Graph Parameters} 
::msgcat::mcset ja {Graph Vert} [encoding convertfrom euc-jp "\xbd\xc4\xc3\xc7\xcc\xcc\xbf\xde"]
::msgcat::mcset ja {Graphics} 
::msgcat::mcset ja {Graphs} 
::msgcat::mcset ja {Graph} [encoding convertfrom euc-jp "\xa5\xb0\xa5\xe9\xa5\xd5"]
::msgcat::mcset ja {Grayscale} [encoding convertfrom euc-jp "\xa5\xb0\xa5\xec\xa1\xbc\xa5\xb9\xa5\xb1\xa1\xbc\xa5\xeb"]
::msgcat::mcset ja {Green} [encoding convertfrom euc-jp "\xce\xd0\xbf\xa7"]
::msgcat::mcset ja {Grid Gap} [encoding convertfrom euc-jp "\xa5\xb0\xa5\xea\xa5\xc3\xa5\xc9\xa4\xce\xb4\xd6\xb3\xd6"]
::msgcat::mcset ja {Grid} [encoding convertfrom euc-jp "\xa5\xb0\xa5\xea\xa5\xc3\xa5\xc9"]
::msgcat::mcset ja {Groups} [encoding convertfrom euc-jp "\xa5\xb0\xa5\xeb\xa1\xbc\xa5\xd7"]
::msgcat::mcset ja {HMS} 
::msgcat::mcset ja {HTTP} [encoding convertfrom euc-jp "\x48\x54\x54\x50"]
::msgcat::mcset ja {Header} [encoding convertfrom euc-jp "\xa5\xd8\xa5\xc3\xa5\xc0"]
::msgcat::mcset ja {Height} [encoding convertfrom euc-jp "\xb9\xe2\xa4\xb5"]
::msgcat::mcset ja {Help Desk} [encoding convertfrom euc-jp "\xa5\xd8\xa5\xeb\xa5\xd7\xa5\xc7\xa5\xb9\xa5\xaf"]
::msgcat::mcset ja {Help Me Choose} [encoding convertfrom euc-jp "\xc1\xaa\xc2\xf2\xa4\xce\xa5\xd2\xa5\xf3\xa5\xc8"]
::msgcat::mcset ja {Help} [encoding convertfrom euc-jp "\xa5\xd8\xa5\xeb\xa5\xd7"]
::msgcat::mcset ja {Hide All} [encoding convertfrom euc-jp "\xc1\xb4\xa4\xc6\xc8\xf3\xc9\xbd\xbc\xa8"]
::msgcat::mcset ja {Highlite} 
::msgcat::mcset ja {High} [encoding convertfrom euc-jp "\xbe\xe5\xb8\xc2"]
::msgcat::mcset ja {Histogram Equalization} [encoding convertfrom euc-jp "\xa5\xd2\xa5\xb9\xa5\xc8\xa5\xb0\xa5\xe9\xa5\xe0\xc5\xf9\xca\xac\xc9\xdb"]
::msgcat::mcset ja {Histogram} [encoding convertfrom euc-jp "\xa5\xd2\xa5\xb9\xa5\xc8\xa5\xb0\xa5\xe9\xa5\xe0"]
::msgcat::mcset ja {Horizontal Graph} [encoding convertfrom euc-jp "\xb2\xa3\xc3\xc7\xcc\xcc"]
::msgcat::mcset ja {Horizontal Layout} [encoding convertfrom euc-jp "\xb2\xe8\xc1\xfc\xa4\xce\xbe\xe5\xa4\xcb\xc7\xdb\xc3\xd6"]
::msgcat::mcset ja {Horizontal} 
::msgcat::mcset ja {IAU Location Code} 
::msgcat::mcset ja {ICRS} [encoding convertfrom euc-jp "\xb9\xf1\xba\xdd\xc5\xb7\xca\xb8\xbd\xe0\xb5\xf2\xb7\xcf"]
::msgcat::mcset ja {Identification} [encoding convertfrom euc-jp "\xc6\xb1\xc4\xea"]
::msgcat::mcset ja {If} [encoding convertfrom euc-jp "\xa4\xe2\xa4\xb7"]
::msgcat::mcset ja {Image Servers} 
::msgcat::mcset ja {Image} [encoding convertfrom euc-jp "\xcf\xc0\xcd\xfd\xba\xc2\xc9\xb8"]
::msgcat::mcset ja {Import Array} 
::msgcat::mcset ja {Import ENVI} 
::msgcat::mcset ja {Import GIF} 
::msgcat::mcset ja {Import JPEG} 
::msgcat::mcset ja {Import NRRD} 
::msgcat::mcset ja {Import PNG} 
::msgcat::mcset ja {Import RGB Array} 
::msgcat::mcset ja {Import Slice GIF} 
::msgcat::mcset ja {Import Slice JPEG} 
::msgcat::mcset ja {Import Slice PNG} 
::msgcat::mcset ja {Import Slice TIFF} 
::msgcat::mcset ja {Import TIFF} 
::msgcat::mcset ja {Import} 
::msgcat::mcset ja {Include} [encoding convertfrom euc-jp "\xc6\xe2\xc2\xa6"]
::msgcat::mcset ja {Increase} [encoding convertfrom euc-jp "\xbe\xba\xbd\xe7"]
::msgcat::mcset ja {Information Panel} [encoding convertfrom euc-jp "\xbe\xf0\xca\xf3\xa5\xd1\xa5\xcd\xa5\xeb"]
::msgcat::mcset ja {Information} [encoding convertfrom euc-jp "\xbe\xf0\xca\xf3"]
::msgcat::mcset ja {Initialize XPA} [encoding convertfrom euc-jp "\x58\x50\x41\x20\xa4\xf2\xbd\xe9\xb4\xfc\xb2\xbd"]
::msgcat::mcset ja {Inner} [encoding convertfrom euc-jp "\xc6\xe2\xb7\xc2"]
::msgcat::mcset ja {Instrument FOV} [encoding convertfrom euc-jp "\xb8\xa1\xbd\xd0\xb4\xef\xa4\xce\xbb\xeb\xcc\xee"]
::msgcat::mcset ja {Instrument} 
::msgcat::mcset ja {Interior Axes} [encoding convertfrom euc-jp "\xbc\xb4\xa4\xf2\xc6\xe2\xc2\xa6\xa4\xcb"]
::msgcat::mcset ja {Interior Numerics} [encoding convertfrom euc-jp "\xbf\xf4\xc3\xcd\xa4\xf2\xc6\xe2\xc2\xa6\xa4\xcb"]
::msgcat::mcset ja {Internal Parse Error} [encoding convertfrom euc-jp "\xc6\xe2\xc9\xf4\xb2\xf2\xbc\xe1\xa5\xa8\xa5\xe9\xa1\xbc"]
::msgcat::mcset ja {Interval} [encoding convertfrom euc-jp "\xb4\xd6\xb3\xd6"]
::msgcat::mcset ja {Invalid Column Name} 
::msgcat::mcset ja {Invalid WCS} 
::msgcat::mcset ja {Invalid formated multipart/mixed mime type message} 
::msgcat::mcset ja {Invert Colormap} [encoding convertfrom euc-jp "\xbf\xa7\xc4\xb4\xa4\xf2\xc8\xbf\xc5\xbe"]
::msgcat::mcset ja {Invert Selection} [encoding convertfrom euc-jp "\xc1\xaa\xc2\xf2\xa4\xf2\xc8\xbf\xc5\xbe"]
::msgcat::mcset ja {Invert} [encoding convertfrom euc-jp "\xc8\xbf\xc5\xbe"]
::msgcat::mcset ja {Italic} [encoding convertfrom euc-jp "\xa5\xa4\xa5\xbf\xa5\xea\xa5\xc3\xa5\xaf"]
::msgcat::mcset ja {Items Found} 
::msgcat::mcset ja {Iteration} [encoding convertfrom euc-jp "\xb7\xab\xa4\xea\xca\xd6\xa4\xb7"]
::msgcat::mcset ja {JPEG Quality Factor} [encoding convertfrom euc-jp "\x4a\x50\x45\x47\xa4\xce\xc9\xca\xbc\xc1"]
::msgcat::mcset ja {JPEG} 
::msgcat::mcset ja {Keep-Alive} 
::msgcat::mcset ja {Keyword} 
::msgcat::mcset ja {Labels} [encoding convertfrom euc-jp "\xa5\xe9\xa5\xd9\xa5\xeb"]
::msgcat::mcset ja {Label} [encoding convertfrom euc-jp "\xa5\xe9\xa5\xd9\xa5\xeb"]
::msgcat::mcset ja {Landscape} [encoding convertfrom euc-jp "\xb2\xa3\xc4\xb9"]
::msgcat::mcset ja {Language} [encoding convertfrom euc-jp "\xb8\xc0\xb8\xec"]
::msgcat::mcset ja {Last Block} 
::msgcat::mcset ja {Last Frame} [encoding convertfrom euc-jp "\xba\xc7\xb8\xe5\xa4\xce\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0"]
::msgcat::mcset ja {Last} [encoding convertfrom euc-jp "\xba\xc7\xb8\xe5"]
::msgcat::mcset ja {Layout Horz} [encoding convertfrom euc-jp "\xb2\xa3\xc7\xdb\xc3\xd6"]
::msgcat::mcset ja {Layout Vert} [encoding convertfrom euc-jp "\xbd\xc4\xc7\xdb\xc3\xd6"]
::msgcat::mcset ja {Layout} 
::msgcat::mcset ja {Left} 
::msgcat::mcset ja {Legal} [encoding convertfrom euc-jp "\xa5\xea\xa1\xbc\xa5\xac\xa5\xeb"]
::msgcat::mcset ja {Legend Position} 
::msgcat::mcset ja {Legend Title} 
::msgcat::mcset ja {Legend} 
::msgcat::mcset ja {Length} [encoding convertfrom euc-jp "\xc4\xb9\xa4\xb5"]
::msgcat::mcset ja {Letter} [encoding convertfrom euc-jp "\xa5\xec\xa5\xbf\xa1\xbc"]
::msgcat::mcset ja {Levels} [encoding convertfrom euc-jp "\xa5\xec\xa5\xd9\xa5\xeb"]
::msgcat::mcset ja {Level} [encoding convertfrom euc-jp "\xa5\xec\xa5\xd9\xa5\xeb"]
::msgcat::mcset ja {Lighten} 
::msgcat::mcset ja {Limits} [encoding convertfrom euc-jp "\xbe\xe5\xb2\xbc\xb8\xc2"]
::msgcat::mcset ja {Line Dataset} 
::msgcat::mcset ja {Line Plot Tool} 
::msgcat::mcset ja {Linear} [encoding convertfrom euc-jp "\xc0\xfe\xb7\xc1"]
::msgcat::mcset ja {Line} [encoding convertfrom euc-jp "\xc0\xfe"]
::msgcat::mcset ja {List Data} 
::msgcat::mcset ja {List Regions} [encoding convertfrom euc-jp "\xce\xce\xb0\xe8\xa4\xf2\xce\xf3\xb5\xf3"]
::msgcat::mcset ja {List Selected Regions} 
::msgcat::mcset ja {List Select} 
::msgcat::mcset ja {List} [encoding convertfrom euc-jp "\xce\xf3\xb5\xf3"]
::msgcat::mcset ja {Load Analysis Commands} [encoding convertfrom euc-jp "\xb2\xf2\xc0\xcf\xa5\xb3\xa5\xde\xa5\xf3\xa5\xc9\xa4\xce\xc6\xc9\xa4\xdf\xb9\xfe\xa4\xdf"]
::msgcat::mcset ja {Load Color Tags} 
::msgcat::mcset ja {Load Contour Levels} [encoding convertfrom euc-jp "\xa5\xb3\xa5\xf3\xa5\xc8\xa5\xa2\xa5\xec\xa5\xd9\xa5\xeb\xa4\xce\xc6\xc9\xa4\xdf\xb9\xfe\xa4\xdf"]
::msgcat::mcset ja {Load Contrast/Bias} [encoding convertfrom euc-jp "\xa5\xb3\xa5\xf3\xa5\xc8\xa5\xe9\xa5\xb9\xa5\xc8\xa1\xa6\xa5\xd0\xa5\xa4\xa5\xa2\xa5\xb9\xa4\xce\xc6\xc9\xa4\xdf\xb9\xfe\xa4\xdf"]
::msgcat::mcset ja {Load Data} [encoding convertfrom euc-jp "\xa5\xc7\xa1\xbc\xa5\xbf\xa4\xce\xc6\xc9\xa4\xdf\xb9\xfe\xa4\xdf"]
::msgcat::mcset ja {Load Mosaic} [encoding convertfrom euc-jp "\xa5\xe2\xa5\xb6\xa5\xa4\xa5\xaf\xa4\xce\xc6\xc9\xa4\xdf\xb9\xfe\xa4\xdf"]
::msgcat::mcset ja {Load Template} [encoding convertfrom euc-jp "\xbf\xf7\xb7\xc1\xa4\xce\xc6\xc9\xa4\xdf\xb9\xfe\xa4\xdf"]
::msgcat::mcset ja {Load into All} 
::msgcat::mcset ja {Load into Current} 
::msgcat::mcset ja {Loading Catalog} [encoding convertfrom euc-jp "\xa5\xab\xa5\xbf\xa5\xed\xa5\xb0\xa4\xf2\xc6\xc9\xa4\xdf\xb9\xfe\xa4\xdf\xc3\xe6"]
::msgcat::mcset ja {Loading} [encoding convertfrom euc-jp "\xc6\xc9\xa4\xdf\xb9\xfe\xa4\xdf\xc3\xe6"]
::msgcat::mcset ja {Load} [encoding convertfrom euc-jp "\xc6\xc9\xa4\xdf\xb9\xfe\xa4\xdf"]
::msgcat::mcset ja {Local} [encoding convertfrom euc-jp "\xa5\xed\xa1\xbc\xa5\xab\xa5\xeb"]
::msgcat::mcset ja {Lock Axes} 
::msgcat::mcset ja {Lock Bin} 
::msgcat::mcset ja {Lock Color} 
::msgcat::mcset ja {Lock Crop Amplifier} 
::msgcat::mcset ja {Lock Crop Detector} 
::msgcat::mcset ja {Lock Crop Image} 
::msgcat::mcset ja {Lock Crop None} 
::msgcat::mcset ja {Lock Crop Physical} 
::msgcat::mcset ja {Lock Crop WCS} 
::msgcat::mcset ja {Lock Crosshair Amplifier} 
::msgcat::mcset ja {Lock Crosshair Detector} 
::msgcat::mcset ja {Lock Crosshair Image} 
::msgcat::mcset ja {Lock Crosshair None} 
::msgcat::mcset ja {Lock Crosshair Physical} 
::msgcat::mcset ja {Lock Crosshair WCS} 
::msgcat::mcset ja {Lock Frame Amplifier} 
::msgcat::mcset ja {Lock Frame Detector} 
::msgcat::mcset ja {Lock Frame Image} 
::msgcat::mcset ja {Lock Frame None} 
::msgcat::mcset ja {Lock Frame Physical} 
::msgcat::mcset ja {Lock Frame WCS} 
::msgcat::mcset ja {Lock Limits} 
::msgcat::mcset ja {Lock Scale} 
::msgcat::mcset ja {Lock Slice Image} 
::msgcat::mcset ja {Lock Slice None} 
::msgcat::mcset ja {Lock Slice WCS} 
::msgcat::mcset ja {Lock Smooth} 
::msgcat::mcset ja {Lock} [encoding convertfrom euc-jp "\xb8\xc7\xc4\xea"]
::msgcat::mcset ja {Log Exponent} 
::msgcat::mcset ja {Log} [encoding convertfrom euc-jp "\xc2\xd0\xbf\xf4"]
::msgcat::mcset ja {Low High} [encoding convertfrom euc-jp "\xbe\xe5\xb8\xc2\xa1\xa6\xb2\xbc\xb8\xc2"]
::msgcat::mcset ja {Lower Left Back} 
::msgcat::mcset ja {Lower Left Front} 
::msgcat::mcset ja {Lower Right Back} 
::msgcat::mcset ja {Lower Right Front} 
::msgcat::mcset ja {Low} [encoding convertfrom euc-jp "\xb2\xbc\xb8\xc2"]
::msgcat::mcset ja {MIP} 
::msgcat::mcset ja {Magenta} [encoding convertfrom euc-jp "\xc5\xed\xbf\xa7"]
::msgcat::mcset ja {Magnification} 
::msgcat::mcset ja {Magnifier} [encoding convertfrom euc-jp "\xb3\xc8\xc2\xe7\xbf\xde"]
::msgcat::mcset ja {Major Radius} 
::msgcat::mcset ja {Major Sigma} 
::msgcat::mcset ja {Major} [encoding convertfrom euc-jp "\xc4\xb9\xbc\xb4"]
::msgcat::mcset ja {Manual} [encoding convertfrom euc-jp "\xbc\xea\xc6\xb0"]
::msgcat::mcset ja {Mask Parameters} [encoding convertfrom euc-jp "\xa5\xde\xa5\xb9\xa5\xaf\xa4\xce\xc0\xdf\xc4\xea"]
::msgcat::mcset ja {Match Axes} 
::msgcat::mcset ja {Match Bin} 
::msgcat::mcset ja {Match Catalog requires at least 1 row per catalog} 
::msgcat::mcset ja {Match Color} 
::msgcat::mcset ja {Match Crop Amplifier} 
::msgcat::mcset ja {Match Crop Detector} 
::msgcat::mcset ja {Match Crop Image} 
::msgcat::mcset ja {Match Crop Physical} 
::msgcat::mcset ja {Match Crop WCS} 
::msgcat::mcset ja {Match Crosshair Amplifier} 
::msgcat::mcset ja {Match Crosshair Detector} 
::msgcat::mcset ja {Match Crosshair Image} 
::msgcat::mcset ja {Match Crosshair Physical} 
::msgcat::mcset ja {Match Crosshair WCS} 
::msgcat::mcset ja {Match Frame Amplifier} 
::msgcat::mcset ja {Match Frame Detector} 
::msgcat::mcset ja {Match Frame Image} 
::msgcat::mcset ja {Match Frame Physical} 
::msgcat::mcset ja {Match Frame WCS} 
::msgcat::mcset ja {Match Limits} 
::msgcat::mcset ja {Match Scale} 
::msgcat::mcset ja {Match Slice Image} 
::msgcat::mcset ja {Match Slice WCS} 
::msgcat::mcset ja {Match Smooth} 
::msgcat::mcset ja {Match} 
::msgcat::mcset ja {Math Function} [encoding convertfrom euc-jp "\xb4\xd8\xbf\xf4"]
::msgcat::mcset ja {Matplotlib} 
::msgcat::mcset ja {Max Rows} [encoding convertfrom euc-jp "\xba\xc7\xc2\xe7\xb9\xd4\xbf\xf4"]
::msgcat::mcset ja {Maximum} 
::msgcat::mcset ja {Max} [encoding convertfrom euc-jp "\xba\xc7\xc2\xe7"]
::msgcat::mcset ja {Menus and Buttons} 
::msgcat::mcset ja {Menu} [encoding convertfrom euc-jp "\xa5\xe1\xa5\xcb\xa5\xe5\xa1\xbc"]
::msgcat::mcset ja {Message Log} [encoding convertfrom euc-jp "\xa5\xe1\xa5\xc3\xa5\xbb\xa1\xbc\xa5\xb8\xa4\xce\xb5\xad\xcf\xbf"]
::msgcat::mcset ja {Method} [encoding convertfrom euc-jp "\xb7\xd7\xbb\xbb\xcb\xa1"]
::msgcat::mcset ja {Min Max Parameters} 
::msgcat::mcset ja {Min Max} [encoding convertfrom euc-jp "\xba\xc7\xc2\xe7\xa1\xa6\xba\xc7\xbe\xae"]
::msgcat::mcset ja {Minimum} 
::msgcat::mcset ja {Minor Radius} 
::msgcat::mcset ja {Minor Sigma} 
::msgcat::mcset ja {Minor} [encoding convertfrom euc-jp "\xc3\xbb\xbc\xb4"]
::msgcat::mcset ja {Minutes} 
::msgcat::mcset ja {Min} [encoding convertfrom euc-jp "\xba\xc7\xbe\xae"]
::msgcat::mcset ja {Mission} [encoding convertfrom euc-jp "\xa5\xdf\xa5\xc3\xa5\xb7\xa5\xe7\xa5\xf3"]
::msgcat::mcset ja {Mode} 
::msgcat::mcset ja {Mosaic IRAF Segment} 
::msgcat::mcset ja {Mosaic IRAF} 
::msgcat::mcset ja {Mosaic WCS Segment} 
::msgcat::mcset ja {Mosaic WCS} 
::msgcat::mcset ja {Mosaic WFPC2} 
::msgcat::mcset ja {Mosaic} 
::msgcat::mcset ja {Mouse Click Epsilon} 
::msgcat::mcset ja {Mouse Wheel Bin} 
::msgcat::mcset ja {Mouse Wheel Zoom} 
::msgcat::mcset ja {Move Back} [encoding convertfrom euc-jp "\xc1\xb0\xa4\xcb\xb0\xdc\xc6\xb0"]
::msgcat::mcset ja {Move First} [encoding convertfrom euc-jp "\xba\xc7\xbd\xe9\xa4\xcb\xb0\xdc\xc6\xb0"]
::msgcat::mcset ja {Move Forward} [encoding convertfrom euc-jp "\xbc\xa1\xa4\xcb\xb0\xdc\xc6\xb0"]
::msgcat::mcset ja {Move Frame} [encoding convertfrom euc-jp "\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0\xa4\xf2\xb0\xdc\xc6\xb0"]
::msgcat::mcset ja {Move Last} [encoding convertfrom euc-jp "\xba\xc7\xb8\xe5\xa4\xcb\xb0\xdc\xc6\xb0"]
::msgcat::mcset ja {Move to Back} [encoding convertfrom euc-jp "\xc7\xd8\xcc\xcc\xa4\xcb\xb0\xdc\xc6\xb0"]
::msgcat::mcset ja {Move to Front} [encoding convertfrom euc-jp "\xc1\xb0\xcc\xcc\xa4\xcb\xb0\xdc\xc6\xb0"]
::msgcat::mcset ja {Movie} 
::msgcat::mcset ja {Muliple Extension Cube} 
::msgcat::mcset ja {Muliple Extension Frames} 
::msgcat::mcset ja {Multiple Extension Cube} 
::msgcat::mcset ja {Multiple Extension Frames} 
::msgcat::mcset ja {Multiple WCS} [encoding convertfrom euc-jp "\xca\xa3\xbf\xf4\x57\x43\x53"]
::msgcat::mcset ja {NAN} 
::msgcat::mcset ja {NRRD} 
::msgcat::mcset ja {Name Resolution} [encoding convertfrom euc-jp "\xcc\xbe\xc1\xb0\xa4\xc7\xb8\xa1\xba\xf7"]
::msgcat::mcset ja {Name Server} [encoding convertfrom euc-jp "\xc5\xb7\xc2\xce\xcc\xbe\xb8\xa1\xba\xf7\xa5\xb5\xa1\xbc\xa5\xd0\xa1\xbc"]
::msgcat::mcset ja {Name or Designation} [encoding convertfrom euc-jp "\xc5\xb7\xc2\xce\xcc\xbe"]
::msgcat::mcset ja {Name} 
::msgcat::mcset ja {Native Dialog} 
::msgcat::mcset ja {New Features} [encoding convertfrom euc-jp "\xbf\xb7\xa4\xb7\xa4\xa4\xb5\xa1\xc7\xbd"]
::msgcat::mcset ja {New Frame 3D} [encoding convertfrom euc-jp "\xbf\xb7\xa4\xb7\xa4\xa4\x33\x44\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0"]
::msgcat::mcset ja {New Frame RGB} [encoding convertfrom euc-jp "\xbf\xb7\xa4\xb7\xa4\xa4\x52\x47\x42\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0"]
::msgcat::mcset ja {New Frame each Time} [encoding convertfrom euc-jp "\xcb\xe8\xb2\xf3\xbf\xb7\xa4\xb7\xa4\xa4\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0\xba\xee\xc0\xae"]
::msgcat::mcset ja {New Frame} [encoding convertfrom euc-jp "\xbf\xb7\xa4\xb7\xa4\xa4\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0"]
::msgcat::mcset ja {New Graph} 
::msgcat::mcset ja {New Group} [encoding convertfrom euc-jp "\xbf\xb7\xa4\xb7\xa4\xa4\xa5\xb0\xa5\xeb\xa1\xbc\xa5\xd7"]
::msgcat::mcset ja {New Plot} 
::msgcat::mcset ja {New} [encoding convertfrom euc-jp "\xbf\xb7\xb5\xac"]
::msgcat::mcset ja {Next Block} 
::msgcat::mcset ja {Next Frame} [encoding convertfrom euc-jp "\xbc\xa1\xa4\xce\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0"]
::msgcat::mcset ja {Next} [encoding convertfrom euc-jp "\xbf\xca\xa4\xe0"]
::msgcat::mcset ja {No Catalog specified} [encoding convertfrom euc-jp "\xa5\xab\xa5\xbf\xa5\xed\xa5\xb0\xa4\xac\xbb\xd8\xc4\xea\xa4\xb5\xa4\xec\xa4\xc6\xa4\xa4\xa4\xde\xa4\xbb\xa4\xf3\xa1\xa3"]
::msgcat::mcset ja {No Data Available} 
::msgcat::mcset ja {No Items Found} [encoding convertfrom euc-jp "\xb8\xab\xa4\xc4\xa4\xab\xa4\xea\xa4\xde\xa4\xbb\xa4\xf3\xa4\xc7\xa4\xb7\xa4\xbf\xa1\xa3"]
::msgcat::mcset ja {Non-NAN} 
::msgcat::mcset ja {Non-Zero} 
::msgcat::mcset ja {None} [encoding convertfrom euc-jp "\xa4\xca\xa4\xb7"]
::msgcat::mcset ja {Normal} [encoding convertfrom euc-jp "\xc9\xb8\xbd\xe0"]
::msgcat::mcset ja {North} [encoding convertfrom euc-jp "\xcb\xcc"]
::msgcat::mcset ja {Not Found} 
::msgcat::mcset ja {Not Supported} 
::msgcat::mcset ja {Not valid export format} 
::msgcat::mcset ja {Notes} 
::msgcat::mcset ja {Number of Samples} [encoding convertfrom euc-jp "\xa5\xb5\xa5\xf3\xa5\xd7\xa5\xeb\xa4\xce\xbf\xf4"]
::msgcat::mcset ja {Number of Threads} 
::msgcat::mcset ja {Number of Ticks} 
::msgcat::mcset ja {Number} [encoding convertfrom euc-jp "\xc8\xd6\xb9\xe6"]
::msgcat::mcset ja {Numerics} [encoding convertfrom euc-jp "\xbf\xf4\xc3\xcd"]
::msgcat::mcset ja {OK} [encoding convertfrom euc-jp "\xce\xbb\xb2\xf2"]
::msgcat::mcset ja {Object} [encoding convertfrom euc-jp "\xc5\xb7\xc2\xce\xcc\xbe"]
::msgcat::mcset ja {ObsId} 
::msgcat::mcset ja {Open File} [encoding convertfrom euc-jp "\xa5\xd5\xa5\xa1\xa5\xa4\xa5\xeb\xa4\xf2\xb3\xab\xa4\xaf"]
::msgcat::mcset ja {Open ME Cube} 
::msgcat::mcset ja {Open ME Frames} 
::msgcat::mcset ja {Open Mosaic IRAF Seg} 
::msgcat::mcset ja {Open Mosaic IRAF} 
::msgcat::mcset ja {Open Mosaic WCS Seg} 
::msgcat::mcset ja {Open Mosaic WCS} 
::msgcat::mcset ja {Open Mosaic WFPC2} 
::msgcat::mcset ja {Open RGB Cube} 
::msgcat::mcset ja {Open RGB Image} 
::msgcat::mcset ja {Open Regions} 
::msgcat::mcset ja {Open Slice} 
::msgcat::mcset ja {Open TCL Console} [encoding convertfrom euc-jp "\x54\x43\x4c\x20\xa5\xb3\xa5\xf3\xa5\xbd\xa1\xbc\xa5\xeb\xa4\xf2\xb3\xab\xa4\xaf"]
::msgcat::mcset ja {Open URL} [encoding convertfrom euc-jp "\x55\x52\x4c\x20\xa4\xf2\xb3\xab\xa4\xaf"]
::msgcat::mcset ja {Open as} 
::msgcat::mcset ja {Open} [encoding convertfrom euc-jp "\xb3\xab\xa4\xaf"]
::msgcat::mcset ja {Operator} [encoding convertfrom euc-jp "\xb1\xe9\xbb\xbb\xbb\xd2"]
::msgcat::mcset ja {Orientation} [encoding convertfrom euc-jp "\xca\xfd\xb8\xfe"]
::msgcat::mcset ja {Origin} 
::msgcat::mcset ja {Oscillate} 
::msgcat::mcset ja {Other Color} 
::msgcat::mcset ja {Other Font Size} 
::msgcat::mcset ja {Other} [encoding convertfrom euc-jp "\xa4\xbd\xa4\xce\xc2\xbe"]
::msgcat::mcset ja {Outer} [encoding convertfrom euc-jp "\xb3\xb0\xb7\xc2"]
::msgcat::mcset ja {Overplot} 
::msgcat::mcset ja {Override Color} 
::msgcat::mcset ja {PNG} 
::msgcat::mcset ja {PS Page Setup} [encoding convertfrom euc-jp "\x50\x53\xa5\xda\xa1\xbc\xa5\xb8\xc0\xdf\xc4\xea"]
::msgcat::mcset ja {PS Print} [encoding convertfrom euc-jp "\x50\x53\xb0\xf5\xba\xfe"]
::msgcat::mcset ja {Page Setup} [encoding convertfrom euc-jp "\xa5\xda\xa1\xbc\xa5\xb8\xc0\xdf\xc4\xea"]
::msgcat::mcset ja {Page Source} [encoding convertfrom euc-jp "\xa5\xda\xa1\xbc\xa5\xb8\xa4\xce\xa5\xbd\xa1\xbc\xa5\xb9"]
::msgcat::mcset ja {Pan To} [encoding convertfrom euc-jp "\xa4\xbd\xa4\xb3\xa4\xcb\xa5\xd1\xa5\xf3"]
::msgcat::mcset ja {Pan Zoom Rotate Parameters} [encoding convertfrom euc-jp "\xa5\xd1\xa5\xf3\xa1\xa6\xa5\xba\xa1\xbc\xa5\xe0\xa1\xa6\xb2\xf3\xc5\xbe\xa4\xce\xc0\xdf\xc4\xea"]
::msgcat::mcset ja {Pan Zoom} [encoding convertfrom euc-jp "\xa5\xd1\xa5\xf3\xa1\xa6\xa5\xba\xa1\xbc\xa5\xe0"]
::msgcat::mcset ja {Pan then Zoom} [encoding convertfrom euc-jp "\xa5\xd1\xa5\xf3\xa4\xce\xa4\xc1\xa5\xba\xa1\xbc\xa5\xe0"]
::msgcat::mcset ja {Panda} [encoding convertfrom euc-jp "\xc9\xf4\xca\xac\xb1\xdf"]
::msgcat::mcset ja {Panner} [encoding convertfrom euc-jp "\xc1\xb4\xc2\xce\xbf\xde"]
::msgcat::mcset ja {Pan} [encoding convertfrom euc-jp "\xa5\xd1\xa5\xf3"]
::msgcat::mcset ja {Parameters} [encoding convertfrom euc-jp "\xa5\xd1\xa5\xe9\xa5\xe1\xa1\xbc\xa5\xbf"]
::msgcat::mcset ja {Password} [encoding convertfrom euc-jp "\xa5\xd1\xa5\xb9\xa5\xef\xa1\xbc\xa5\xc9"]
::msgcat::mcset ja {Paste Contours} [encoding convertfrom euc-jp "\xa5\xb3\xa5\xf3\xa5\xc8\xa5\xa2\xa4\xf2\xc5\xbd\xa4\xea\xc9\xd5\xa4\xb1"]
::msgcat::mcset ja {Paste} [encoding convertfrom euc-jp "\xc5\xbd\xa4\xea\xc9\xd5\xa4\xb1"]
::msgcat::mcset ja {Physical} [encoding convertfrom euc-jp "\xca\xaa\xcd\xfd\xba\xc2\xc9\xb8"]
::msgcat::mcset ja {Pixel Distribution} [encoding convertfrom euc-jp "\xa5\xd4\xa5\xaf\xa5\xbb\xa5\xeb\xc9\xd1\xc5\xd9\xca\xac\xc9\xdb"]
::msgcat::mcset ja {Pixel Size} [encoding convertfrom euc-jp "\xa5\xd4\xa5\xaf\xa5\xbb\xa5\xeb\xa5\xb5\xa5\xa4\xa5\xba"]
::msgcat::mcset ja {Pixel Table} [encoding convertfrom euc-jp "\xa5\xd4\xa5\xaf\xa5\xbb\xa5\xeb\xc9\xbd"]
::msgcat::mcset ja {Pixels} [encoding convertfrom euc-jp "\xa5\xd4\xa5\xaf\xa5\xbb\xa5\xeb"]
::msgcat::mcset ja {Planets} 
::msgcat::mcset ja {Play} [encoding convertfrom euc-jp "\xba\xc6\xc0\xb8"]
::msgcat::mcset ja {Please Select a Region} [encoding convertfrom euc-jp "\xce\xce\xb0\xe8\xa4\xf2\xbb\xd8\xc4\xea\xa4\xb7\xa4\xc6\xa4\xaf\xa4\xc0\xa4\xb5\xa4\xa4\xa1\xa3"]
::msgcat::mcset ja {Please change the file's permission to disable other users write access. Use anyway?} 
::msgcat::mcset ja {Please specify instruments} 
::msgcat::mcset ja {Please specify radius and either name or (ra,dec)} 
::msgcat::mcset ja {Please specify width, height, and either name or (ra,dec)} [encoding convertfrom euc-jp "\xc9\xfd\xa1\xa2\xb9\xe2\xa4\xb5\xa1\xa2\xcc\xbe\xc1\xb0\xa4\xe2\xa4\xb7\xa4\xaf\xa4\xcf\x20\x28\x72\x61\x2c\x64\x65\x63\x29\x20\xa4\xf2\xbb\xd8\xc4\xea\xa4\xb7\xa4\xc6\xa4\xaf\xa4\xc0\xa4\xb5\xa4\xa4\xa1\xa3"]
::msgcat::mcset ja {Plot 2D} 
::msgcat::mcset ja {Plot 3D} 
::msgcat::mcset ja {Plot Area} 
::msgcat::mcset ja {Plot Control Panel} 
::msgcat::mcset ja {Plot Tool} 
::msgcat::mcset ja {Plotting Regions} [encoding convertfrom euc-jp "\xce\xce\xb0\xe8\xa4\xf2\xa5\xd7\xa5\xed\xa5\xc3\xa5\xc8\xa4\xb7\xa4\xc6\xa4\xa4\xa4\xde\xa4\xb9"]
::msgcat::mcset ja {Plot} [encoding convertfrom euc-jp "\xa5\xd7\xa5\xed\xa5\xc3\xa5\xc8"]
::msgcat::mcset ja {Plus} [encoding convertfrom euc-jp "\xa1\xdc"]
::msgcat::mcset ja {Pointer} [encoding convertfrom euc-jp "\xa5\xdd\xa5\xa4\xa5\xf3\xa5\xbf"]
::msgcat::mcset ja {Points} [encoding convertfrom euc-jp "\xc5\xc0"]
::msgcat::mcset ja {Point} [encoding convertfrom euc-jp "\xc5\xc0"]
::msgcat::mcset ja {Polygon} [encoding convertfrom euc-jp "\xc2\xbf\xb3\xd1\xb7\xc1"]
::msgcat::mcset ja {Portrait} [encoding convertfrom euc-jp "\xbd\xc4\xc4\xb9"]
::msgcat::mcset ja {Position} 
::msgcat::mcset ja {Poster} [encoding convertfrom euc-jp "\xa5\xdd\xa5\xb9\xa5\xbf\xa1\xbc"]
::msgcat::mcset ja {Postscript} [encoding convertfrom euc-jp "\xa5\xdd\xa5\xb9\xa5\xc8\xa5\xb9\xa5\xaf\xa5\xea\xa5\xd7\xa5\xc8"]
::msgcat::mcset ja {Power} [encoding convertfrom euc-jp "\xd1\xd1\xbe\xe8"]
::msgcat::mcset ja {Precision} 
::msgcat::mcset ja {Preferences} [encoding convertfrom euc-jp "\xc0\xdf\xc4\xea"]
::msgcat::mcset ja {Preserve During Load} [encoding convertfrom euc-jp "\xc6\xc9\xa4\xdf\xb9\xfe\xa4\xdf\xc3\xe6\xa4\xcb\xca\xdd\xbb\xfd"]
::msgcat::mcset ja {Previous Block} 
::msgcat::mcset ja {Previous Frame} [encoding convertfrom euc-jp "\xc1\xb0\xa4\xce\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0"]
::msgcat::mcset ja {Previous} [encoding convertfrom euc-jp "\xcc\xe1\xa4\xeb"]
::msgcat::mcset ja {Prev} 
::msgcat::mcset ja {Print Coordinates} [encoding convertfrom euc-jp "\xba\xc2\xc9\xb8\xa4\xf2\xb0\xf5\xba\xfe"]
::msgcat::mcset ja {Print To} [encoding convertfrom euc-jp "\xbd\xd0\xce\xcf\xc0\xe8"]
::msgcat::mcset ja {Printer} [encoding convertfrom euc-jp "\xa5\xd7\xa5\xea\xa5\xf3\xa5\xbf"]
::msgcat::mcset ja {Print} [encoding convertfrom euc-jp "\xb0\xf5\xba\xfe"]
::msgcat::mcset ja {Prism Goto} 
::msgcat::mcset ja {Prism} 
::msgcat::mcset ja {Projection} [encoding convertfrom euc-jp "\xc0\xda\xc3\xc7\xcc\xcc"]
::msgcat::mcset ja {Properties} [encoding convertfrom euc-jp "\xc2\xb0\xc0\xad"]
::msgcat::mcset ja {Property} [encoding convertfrom euc-jp "\xc2\xb0\xc0\xad"]
::msgcat::mcset ja {Proxy Host} [encoding convertfrom euc-jp "\xa5\xd7\xa5\xed\xa5\xad\xa5\xb7\xa5\xb5\xa1\xbc\xa5\xd0\xa1\xbc"]
::msgcat::mcset ja {Proxy Port} [encoding convertfrom euc-jp "\xa5\xd7\xa5\xed\xa5\xad\xa5\xb7\xa5\xdd\xa1\xbc\xa5\xc8"]
::msgcat::mcset ja {Publication} [encoding convertfrom euc-jp "\xcf\xc0\xca\xb8"]
::msgcat::mcset ja {Quadratic} 
::msgcat::mcset ja {RDB} 
::msgcat::mcset ja {RGB Array} 
::msgcat::mcset ja {RGB Cube} 
::msgcat::mcset ja {RGB Image} 
::msgcat::mcset ja {RGB} [encoding convertfrom euc-jp "\x52\x47\x42\xbf\xa7"]
::msgcat::mcset ja {Radial Profile} 
::msgcat::mcset ja {Radius} [encoding convertfrom euc-jp "\xc8\xbe\xb7\xc2"]
::msgcat::mcset ja {Range} 
::msgcat::mcset ja {Redo} [encoding convertfrom euc-jp "\xa4\xe2\xa4\xa6\xb0\xec\xc5\xd9"]
::msgcat::mcset ja {Red} [encoding convertfrom euc-jp "\xc0\xd6\xbf\xa7"]
::msgcat::mcset ja {Reference Manual} [encoding convertfrom euc-jp "\xa5\xea\xa5\xd5\xa5\xa1\xa5\xec\xa5\xf3\xa5\xb9\xa5\xde\xa5\xcb\xa5\xe5\xa5\xa2\xa5\xeb"]
::msgcat::mcset ja {Reference} [encoding convertfrom euc-jp "\xa5\xea\xa5\xd5\xa5\xa1\xa5\xec\xa5\xf3\xa5\xb9"]
::msgcat::mcset ja {Refresh Frame} [encoding convertfrom euc-jp "\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0\xa4\xf2\xba\xc6\xc9\xc1\xb2\xe8"]
::msgcat::mcset ja {Refresh} [encoding convertfrom euc-jp "\xba\xc6\xc9\xc1\xb2\xe8"]
::msgcat::mcset ja {Region Parameters} [encoding convertfrom euc-jp "\xce\xce\xb0\xe8\xa4\xce\xc0\xdf\xc4\xea"]
::msgcat::mcset ja {Region} [encoding convertfrom euc-jp "\xce\xce\xb0\xe8"]
::msgcat::mcset ja {Release Notes} [encoding convertfrom euc-jp "\xa5\xea\xa5\xea\xa1\xbc\xa5\xb9\xa5\xce\xa1\xbc\xa5\xc8"]
::msgcat::mcset ja {Release} [encoding convertfrom euc-jp "\xa5\xea\xa5\xea\xa1\xbc\xa5\xb9"]
::msgcat::mcset ja {Reload} [encoding convertfrom euc-jp "\xba\xc6\xc6\xc9\xa4\xdf\xb9\xfe\xa4\xdf"]
::msgcat::mcset ja {Render} 
::msgcat::mcset ja {Repeat} 
::msgcat::mcset ja {Reset Colormap} [encoding convertfrom euc-jp "\xbf\xa7\xc4\xb4\xa4\xf2\xa5\xea\xa5\xbb\xa5\xc3\xa5\xc8"]
::msgcat::mcset ja {Reset Frame} [encoding convertfrom euc-jp "\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0\xa4\xf2\xa5\xea\xa5\xbb\xa5\xc3\xa5\xc8"]
::msgcat::mcset ja {Reset} [encoding convertfrom euc-jp "\xa5\xea\xa5\xbb\xa5\xc3\xa5\xc8"]
::msgcat::mcset ja {Restore} 
::msgcat::mcset ja {Retrieve} [encoding convertfrom euc-jp "\xb8\xa1\xba\xf7"]
::msgcat::mcset ja {Return} 
::msgcat::mcset ja {Right} 
::msgcat::mcset ja {Roman} 
::msgcat::mcset ja {Rotate} [encoding convertfrom euc-jp "\xb2\xf3\xc5\xbe"]
::msgcat::mcset ja {Rows} [encoding convertfrom euc-jp "\xb9\xd4"]
::msgcat::mcset ja {Row} 
::msgcat::mcset ja {Ruler} [encoding convertfrom euc-jp "\xa4\xe2\xa4\xce\xa4\xb5\xa4\xb7"]
::msgcat::mcset ja {SAMP Image} 
::msgcat::mcset ja {SAMP Table} 
::msgcat::mcset ja {SAMP: not connected} [encoding convertfrom euc-jp "\x53\x41\x4d\x50\x3a\x20\xcc\xa4\xc0\xdc\xc2\xb3"]
::msgcat::mcset ja {SAMP} [encoding convertfrom euc-jp "\x53\x41\x4d\x50"]
::msgcat::mcset ja {Sample Increment} 
::msgcat::mcset ja {Sample Parameters} 
::msgcat::mcset ja {Samples per Line} [encoding convertfrom euc-jp "\xa3\xb1\xb9\xd4\xa4\xa2\xa4\xbf\xa4\xea\xa4\xce\xa5\xb5\xa5\xf3\xa5\xd7\xa5\xeb"]
::msgcat::mcset ja {Sample} 
::msgcat::mcset ja {Save 3D Movie} 
::msgcat::mcset ja {Save Color Tags} 
::msgcat::mcset ja {Save Contour Levels} [encoding convertfrom euc-jp "\xa5\xb3\xa5\xf3\xa5\xc8\xa5\xa2\xa5\xec\xa5\xd9\xa5\xeb\xa4\xf2\xca\xdd\xc2\xb8"]
::msgcat::mcset ja {Save Contrast/Bias} [encoding convertfrom euc-jp "\xa5\xb3\xa5\xf3\xa5\xc8\xa5\xe9\xa5\xb9\xa5\xc8\xa1\xa6\xa5\xd0\xa5\xa4\xa5\xa2\xa5\xb9\xa4\xf2\xca\xdd\xc2\xb8"]
::msgcat::mcset ja {Save Data} [encoding convertfrom euc-jp "\xa5\xc7\xa1\xbc\xa5\xbf\xa4\xf2\xca\xdd\xc2\xb8"]
::msgcat::mcset ja {Save Image EPS} 
::msgcat::mcset ja {Save Image FITS} 
::msgcat::mcset ja {Save Image GIF} 
::msgcat::mcset ja {Save Image JPEG} 
::msgcat::mcset ja {Save Image PNG} 
::msgcat::mcset ja {Save Image TIFF} 
::msgcat::mcset ja {Save Image on Download} 
::msgcat::mcset ja {Save Image} [encoding convertfrom euc-jp "\xa5\xa4\xa5\xe1\xa1\xbc\xa5\xb8\xa4\xf2\xca\xdd\xc2\xb8"]
::msgcat::mcset ja {Save ME Cube} 
::msgcat::mcset ja {Save Mosaic WCS Seg} 
::msgcat::mcset ja {Save Mosaic WCS} 
::msgcat::mcset ja {Save RGB Cube} 
::msgcat::mcset ja {Save RGB Image} 
::msgcat::mcset ja {Save Regions} [encoding convertfrom euc-jp "\xce\xce\xb0\xe8\xa4\xf2\xca\xdd\xc2\xb8"]
::msgcat::mcset ja {Save Selected Regions} 
::msgcat::mcset ja {Save Select} 
::msgcat::mcset ja {Save Slice} 
::msgcat::mcset ja {Save Template} [encoding convertfrom euc-jp "\xbf\xf7\xb7\xc1\xa4\xf2\xca\xdd\xc2\xb8"]
::msgcat::mcset ja {Save as} 
::msgcat::mcset ja {Save} [encoding convertfrom euc-jp "\xca\xdd\xc2\xb8"]
::msgcat::mcset ja {Scale Parameters} [encoding convertfrom euc-jp "\xa5\xb9\xa5\xb1\xa1\xbc\xa5\xeb\xa4\xce\xc0\xdf\xc4\xea"]
::msgcat::mcset ja {Scale and Limits} 
::msgcat::mcset ja {Scale} [encoding convertfrom euc-jp "\xa5\xb9\xa5\xb1\xa1\xbc\xa5\xeb"]
::msgcat::mcset ja {Scan} [encoding convertfrom euc-jp "\xa5\xb9\xa5\xad\xa5\xe3\xa5\xf3"]
::msgcat::mcset ja {Scatter Dataset} 
::msgcat::mcset ja {Scatter Plot Tool} 
::msgcat::mcset ja {Scope} [encoding convertfrom euc-jp "\xa5\xb9\xa5\xb3\xa1\xbc\xa5\xd7"]
::msgcat::mcset ja {Screen} 
::msgcat::mcset ja {Search for Catalogs} [encoding convertfrom euc-jp "\xa5\xab\xa5\xbf\xa5\xed\xa5\xb0\xa4\xf2\xb8\xa1\xba\xf7"]
::msgcat::mcset ja {Seconds} [encoding convertfrom euc-jp "\xc9\xc3"]
::msgcat::mcset ja {Segment} 
::msgcat::mcset ja {Select All} [encoding convertfrom euc-jp "\xc1\xb4\xa4\xc6\xc1\xaa\xc2\xf2"]
::msgcat::mcset ja {Select Coordinate System } [encoding convertfrom euc-jp "\xba\xc2\xc9\xb8\xb7\xcf\xa4\xf2\xc1\xaa\xc2\xf2"]
::msgcat::mcset ja {Select Dataset} 
::msgcat::mcset ja {Select Datatset} 
::msgcat::mcset ja {Select Graph} 
::msgcat::mcset ja {Select None} [encoding convertfrom euc-jp "\xc1\xaa\xc2\xf2\xa4\xf2\xb2\xf2\xbd\xfc"]
::msgcat::mcset ja {Send} [encoding convertfrom euc-jp "\xc1\xf7\xbf\xae"]
::msgcat::mcset ja {Server} [encoding convertfrom euc-jp "\xa5\xb5\xa1\xbc\xa5\xd0\xa1\xbc"]
::msgcat::mcset ja {Sexagesimal} [encoding convertfrom euc-jp "\xbb\xfe\xca\xac\xc9\xc3"]
::msgcat::mcset ja {Shadow} 
::msgcat::mcset ja {Shape} [encoding convertfrom euc-jp "\xb7\xc1"]
::msgcat::mcset ja {Show All} [encoding convertfrom euc-jp "\xc1\xb4\xa4\xc6\xc9\xbd\xbc\xa8"]
::msgcat::mcset ja {Show Command} 
::msgcat::mcset ja {Show Compass} 
::msgcat::mcset ja {Show Grid} 
::msgcat::mcset ja {Show Legend} 
::msgcat::mcset ja {Show Text} [encoding convertfrom euc-jp "\xca\xb8\xbb\xfa\xa4\xf2\xc9\xbd\xbc\xa8"]
::msgcat::mcset ja {Show/Hide Frames} [encoding convertfrom euc-jp "\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0\xa4\xce\xc9\xbd\xbc\xa8\x2f\xc8\xf3\xc9\xbd\xbc\xa8"]
::msgcat::mcset ja {Show} [encoding convertfrom euc-jp "\xc9\xbd\xbc\xa8"]
::msgcat::mcset ja {Simple Cross} 
::msgcat::mcset ja {Simple Image Access} 
::msgcat::mcset ja {Simple Plus} 
::msgcat::mcset ja {Single Frame} [encoding convertfrom euc-jp "\xc3\xb1\xb0\xec\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0"]
::msgcat::mcset ja {Single} [encoding convertfrom euc-jp "\xc3\xb1\xb0\xec"]
::msgcat::mcset ja {Sites} 
::msgcat::mcset ja {Size/Radius} [encoding convertfrom euc-jp "\xc2\xe7\xa4\xad\xa4\xb5\x2f\xc8\xbe\xb7\xc2"]
::msgcat::mcset ja {Size} [encoding convertfrom euc-jp "\xc2\xe7\xa4\xad\xa4\xb5"]
::msgcat::mcset ja {Skip First} 
::msgcat::mcset ja {Slice} 
::msgcat::mcset ja {Smooth Parameters} [encoding convertfrom euc-jp "\xca\xbf\xb3\xea\xb2\xbd\xa4\xce\xc0\xdf\xc4\xea"]
::msgcat::mcset ja {Smoothness} 
::msgcat::mcset ja {Smooth} [encoding convertfrom euc-jp "\xca\xbf\xb3\xea\xb2\xbd"]
::msgcat::mcset ja {Sorry, DS9 does not support} [encoding convertfrom euc-jp "\x44\x53\x39\x20\xa4\xc7\xa5\xb5\xa5\xdd\xa1\xbc\xa5\xc8\xa4\xb5\xa4\xec\xa4\xc6\xa4\xa4\xa4\xde\xa4\xbb\xa4\xf3\xa1\xa3"]
::msgcat::mcset ja {Sorry, DS9 requires a Truecolor8, Truecolor16, Truecolor24 visual be available} 
::msgcat::mcset ja {Sort} [encoding convertfrom euc-jp "\xca\xc2\xa4\xd9\xc2\xd8\xa4\xa8"]
::msgcat::mcset ja {Source TCL} [encoding convertfrom euc-jp "\x54\x43\x4c\x20\xa4\xf2\xc6\xc9\xa4\xdf\xb9\xfe\xa4\xe0"]
::msgcat::mcset ja {Source} [encoding convertfrom euc-jp "\xa5\xbd\xa1\xbc\xa5\xb9\xce\xce\xb0\xe8"]
::msgcat::mcset ja {Space Equal Distance} 
::msgcat::mcset ja {Space Equal Value} 
::msgcat::mcset ja {Spacing} 
::msgcat::mcset ja {Sqrt} 
::msgcat::mcset ja {Square Root} [encoding convertfrom euc-jp "\xca\xbf\xca\xfd\xba\xac"]
::msgcat::mcset ja {Squared} [encoding convertfrom euc-jp "\xca\xbf\xca\xfd"]
::msgcat::mcset ja {Square} 
::msgcat::mcset ja {Starbase} 
::msgcat::mcset ja {Startup} 
::msgcat::mcset ja {Start} [encoding convertfrom euc-jp "\xb3\xab\xbb\xcf"]
::msgcat::mcset ja {Statistics} 
::msgcat::mcset ja {Status} [encoding convertfrom euc-jp "\xbe\xf5\xc2\xd6"]
::msgcat::mcset ja {Step} [encoding convertfrom euc-jp "\xa5\xb9\xa5\xc6\xa5\xc3\xa5\xd7"]
::msgcat::mcset ja {Stop} [encoding convertfrom euc-jp "\xbd\xaa\xce\xbb"]
::msgcat::mcset ja {Story of SAOImageDS9} 
::msgcat::mcset ja {Story} 
::msgcat::mcset ja {Strip Parameters} 
::msgcat::mcset ja {Strip Scale} 
::msgcat::mcset ja {Strip} 
::msgcat::mcset ja {Sum} [encoding convertfrom euc-jp "\xb9\xe7\xb7\xd7"]
::msgcat::mcset ja {Symbol Editor} [encoding convertfrom euc-jp "\xb5\xad\xb9\xe6\xa4\xce\xca\xd4\xbd\xb8"]
::msgcat::mcset ja {Symbol} [encoding convertfrom euc-jp "\xb5\xad\xb9\xe6"]
::msgcat::mcset ja {TIFF} 
::msgcat::mcset ja {TSV} 
::msgcat::mcset ja {Tab-Separated-Value} [encoding convertfrom euc-jp "\xa5\xbf\xa5\xd6\xca\xac\xb3\xe4\xb5\xad\xcb\xa1"]
::msgcat::mcset ja {Table} 
::msgcat::mcset ja {Tabloid} [encoding convertfrom euc-jp "\xa5\xbf\xa5\xd6\xa5\xed\xa5\xa4\xa5\xc9"]
::msgcat::mcset ja {Tag Color} 
::msgcat::mcset ja {Template} [encoding convertfrom euc-jp "\xbf\xf7\xb7\xc1"]
::msgcat::mcset ja {Text} [encoding convertfrom euc-jp "\xca\xb8\xbb\xfa"]
::msgcat::mcset ja {Theme} 
::msgcat::mcset ja {Then} [encoding convertfrom euc-jp "\xa4\xca\xa4\xe9"]
::msgcat::mcset ja {Thickness} [encoding convertfrom euc-jp "\xc2\xc0\xa4\xb5"]
::msgcat::mcset ja {This analysis task is already running. Do you wish to kill it?} [encoding convertfrom euc-jp "\xa4\xb3\xa4\xce\xb2\xf2\xc0\xcf\xa5\xbf\xa5\xb9\xa5\xaf\xa4\xcf\xa4\xb9\xa4\xc7\xa4\xcb\xbc\xc2\xb9\xd4\xc3\xe6\xa4\xc7\xa4\xb9\xa1\xa3\xc3\xe6\xc3\xc7\xa4\xb7\xa4\xde\xa4\xb9\xa4\xab\x3f"]
::msgcat::mcset ja {This function is not available.} 
::msgcat::mcset ja {This function is not currently supported for this port.} 
::msgcat::mcset ja {Tickmarks} [encoding convertfrom euc-jp "\xcc\xdc\xc0\xb9\xa4\xea"]
::msgcat::mcset ja {Tile Frames} [encoding convertfrom euc-jp "\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0\xa4\xf2\xca\xc2\xa4\xd9\xa4\xeb"]
::msgcat::mcset ja {Tile Parameters} [encoding convertfrom euc-jp "\xca\xc2\xa4\xd9\xca\xfd\xa4\xce\xc0\xdf\xc4\xea"]
::msgcat::mcset ja {Tile} [encoding convertfrom euc-jp "\xca\xc2\xa4\xd9\xa4\xc6\xc9\xbd\xbc\xa8"]
::msgcat::mcset ja {Times} 
::msgcat::mcset ja {Titles} 
::msgcat::mcset ja {Title} [encoding convertfrom euc-jp "\xa5\xbf\xa5\xa4\xa5\xc8\xa5\xeb"]
::msgcat::mcset ja {Tophat} [encoding convertfrom euc-jp "\xa5\xc8\xa5\xc3\xa5\xd7\xa5\xcf\xa5\xc3\xa5\xc8"]
::msgcat::mcset ja {Topographic} 
::msgcat::mcset ja {Top} 
::msgcat::mcset ja {To} 
::msgcat::mcset ja {Transparency} [encoding convertfrom euc-jp "\xc6\xa9\xcc\xc0"]
::msgcat::mcset ja {Triangle} 
::msgcat::mcset ja {Type} [encoding convertfrom euc-jp "\xbc\xef\xce\xe0"]
::msgcat::mcset ja {URL} 
::msgcat::mcset ja {Unable to connect directly: using Web Proxy} 
::msgcat::mcset ja {Unable to create FOV Region, celestial WCS Required} 
::msgcat::mcset ja {Unable to determine date of observation} 
::msgcat::mcset ja {Unable to evaluate filter} [encoding convertfrom euc-jp "\xb9\xca\xa4\xea\xb9\xfe\xa4\xdf\xbe\xf2\xb7\xef\xa4\xac\xc9\xbe\xb2\xc1\xa4\xc7\xa4\xad\xa4\xde\xa4\xbb\xa4\xf3\xa1\xa3"]
::msgcat::mcset ja {Unable to find Footprint window} 
::msgcat::mcset ja {Unable to find PRISM window} 
::msgcat::mcset ja {Unable to find SIAP window} 
::msgcat::mcset ja {Unable to find URL column} 
::msgcat::mcset ja {Unable to find catalog window} [encoding convertfrom euc-jp "\xa5\xab\xa5\xbf\xa5\xed\xa5\xb0\xa5\xa6\xa5\xa3\xa5\xf3\xa5\xc9\xa5\xa6\xa4\xac\xb8\xab\xa4\xc4\xa4\xab\xa4\xea\xa4\xde\xa4\xbb\xa4\xf3\xa1\xa3"]
::msgcat::mcset ja {Unable to find plot window} [encoding convertfrom euc-jp "\xa5\xd7\xa5\xed\xa5\xc3\xa5\xc8\xa5\xa6\xa5\xa3\xa5\xf3\xa5\xc9\xa5\xa6\xa4\xac\xb8\xab\xa4\xc4\xa4\xab\xa4\xea\xa4\xde\xa4\xbb\xa4\xf3\xa1\xa3"]
::msgcat::mcset ja {Unable to find web window} 
::msgcat::mcset ja {Unable to generate plot} 
::msgcat::mcset ja {Unable to load RGB image into a non-rgb frame} [encoding convertfrom euc-jp "\x52\x42\x47\xa5\xa4\xa5\xe1\xa1\xbc\xa5\xb8\xa4\xf2\xc8\xf3\x52\x47\x42\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0\xa4\xcb\xc6\xc9\xa4\xdf\xb9\xfe\xa4\xe1\xa4\xde\xa4\xbb\xa4\xf3\xa1\xa3"]
::msgcat::mcset ja {Unable to load compressed region file} 
::msgcat::mcset ja {Unable to load plot data} 
::msgcat::mcset ja {Unable to load region file} [encoding convertfrom euc-jp "\xce\xce\xb0\xe8\xa5\xd5\xa5\xa1\xa5\xa4\xa5\xeb\xa4\xf2\xc6\xc9\xa4\xdf\xb9\xfe\xa4\xe1\xa4\xde\xa4\xbb\xa4\xf3\xa1\xa3"]
::msgcat::mcset ja {Unable to load} [encoding convertfrom euc-jp "\xc6\xc9\xa4\xdf\xb9\xfe\xa4\xe1\xa4\xde\xa4\xbb\xa4\xf3\xa1\xa3"]
::msgcat::mcset ja {Unable to locate FOV Region} 
::msgcat::mcset ja {Unable to locate URL} [encoding convertfrom euc-jp "\x55\x52\x4c\xa4\xf2\xc6\xc3\xc4\xea\xa4\xc7\xa4\xad\xa4\xde\xa4\xbb\xa4\xf3\xa1\xa3"]
::msgcat::mcset ja {Unable to match target with XPA Mime request} 
::msgcat::mcset ja {Unable to open file} [encoding convertfrom euc-jp "\xa5\xd5\xa5\xa1\xa5\xa4\xa5\xeb\xa4\xf2\xb3\xab\xa4\xb1\xa4\xde\xa4\xbb\xa4\xf3\xa1\xa3"]
::msgcat::mcset ja {Unable to save RGB image from a non-rgb frame} 
::msgcat::mcset ja {Undo} [encoding convertfrom euc-jp "\xa4\xe4\xa4\xea\xc4\xbe\xa4\xb7"]
::msgcat::mcset ja {Unique} 
::msgcat::mcset ja {Unists} 
::msgcat::mcset ja {Units} [encoding convertfrom euc-jp "\xc3\xb1\xb0\xcc"]
::msgcat::mcset ja {Unknown Colormap} [encoding convertfrom euc-jp "\xa5\xb5\xa5\xdd\xa1\xbc\xa5\xc8\xa4\xb5\xa4\xec\xa4\xca\xa4\xa4\xc7\xdb\xbf\xa7"]
::msgcat::mcset ja {Unknown command} [encoding convertfrom euc-jp "\xa5\xb5\xa5\xdd\xa1\xbc\xa5\xc8\xa4\xb5\xa4\xec\xa4\xca\xa4\xa4\xa5\xb3\xa5\xde\xa5\xf3\xa5\xc9"]
::msgcat::mcset ja {Update Filter} [encoding convertfrom euc-jp "\xb8\xa1\xba\xf7\xbe\xf2\xb7\xef\xa4\xf2\xb9\xb9\xbf\xb7"]
::msgcat::mcset ja {Update Group} [encoding convertfrom euc-jp "\xa5\xb0\xa5\xeb\xa1\xbc\xa5\xd7\xa4\xf2\xb9\xb9\xbf\xb7"]
::msgcat::mcset ja {Update from Current Crosshair} [encoding convertfrom euc-jp "\xb8\xbd\xba\xdf\xa4\xce\xbd\xbd\xbb\xfa\xa5\xab\xa1\xbc\xa5\xbd\xa5\xeb\xb0\xcc\xc3\xd6\xa4\xab\xa4\xe9\xb9\xb9\xbf\xb7"]
::msgcat::mcset ja {Update from Current Frame} [encoding convertfrom euc-jp "\xb8\xbd\xba\xdf\xa4\xce\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0\xa4\xab\xa4\xe9\xb9\xb9\xbf\xb7"]
::msgcat::mcset ja {Update} [encoding convertfrom euc-jp "\xb9\xb9\xbf\xb7"]
::msgcat::mcset ja {Upper Left Back} 
::msgcat::mcset ja {Upper Left Front} 
::msgcat::mcset ja {Upper Right Back} 
::msgcat::mcset ja {Upper Right Front} 
::msgcat::mcset ja {Use Authentication} [encoding convertfrom euc-jp "\xc7\xa7\xbe\xda\xa4\xf2\xbb\xc8\xcd\xd1"]
::msgcat::mcset ja {Use Current Frame on Download} [encoding convertfrom euc-jp "\xa5\xc0\xa5\xa6\xa5\xf3\xa5\xed\xa1\xbc\xa5\xc9\xbb\xfe\xa4\xcb\xc1\xaa\xc2\xf2\xc3\xe6\xa4\xce\xa5\xd5\xa5\xec\xa1\xbc\xa5\xe0\xa4\xf2\xbb\xc8\xcd\xd1"]
::msgcat::mcset ja {Use Internal Web Browser} [encoding convertfrom euc-jp "\xc6\xe2\xc9\xf4\xa5\xd6\xa5\xe9\xa5\xa6\xa5\xb6\xa4\xf2\xbb\xc8\xcd\xd1"]
::msgcat::mcset ja {Use Original Color/Width} 
::msgcat::mcset ja {Use Proxy} [encoding convertfrom euc-jp "\xa5\xd7\xa5\xed\xa5\xad\xa5\xb7\xa4\xf2\xbb\xc8\xcd\xd1"]
::msgcat::mcset ja {Use Theme Colors} 
::msgcat::mcset ja {Use background color instead of theme color} 
::msgcat::mcset ja {User Manual} [encoding convertfrom euc-jp "\xa5\xe6\xa1\xbc\xa5\xb6\xa1\xbc\xa5\xde\xa5\xcb\xa5\xe5\xa5\xa2\xa5\xeb"]
::msgcat::mcset ja {Username} [encoding convertfrom euc-jp "\xa5\xe6\xa1\xbc\xa5\xb6\xa1\xbc\xcc\xbe"]
::msgcat::mcset ja {User} [encoding convertfrom euc-jp "\xa5\xe6\xa1\xbc\xa5\xb6\xa1\xbc"]
::msgcat::mcset ja {Use} [encoding convertfrom euc-jp "\xbb\xc8\xcd\xd1"]
::msgcat::mcset ja {VO Server} 
::msgcat::mcset ja {VOTable} 
::msgcat::mcset ja {VOT} 
::msgcat::mcset ja {VO} [encoding convertfrom euc-jp "\xb2\xbe\xc1\xdb\xc5\xb7\xca\xb8\xc2\xe6"]
::msgcat::mcset ja {Value} [encoding convertfrom euc-jp "\xc3\xcd"]
::msgcat::mcset ja {Vector} [encoding convertfrom euc-jp "\xa5\xd9\xa5\xaf\xa5\xc8\xa5\xeb"]
::msgcat::mcset ja {Vertical Graph} [encoding convertfrom euc-jp "\xbd\xc4\xc3\xc7\xcc\xcc"]
::msgcat::mcset ja {Vertical Layout} [encoding convertfrom euc-jp "\xb2\xe8\xcc\xcc\xa4\xce\xba\xb8\xa4\xcb\xc7\xdb\xc3\xd6"]
::msgcat::mcset ja {Vertical Text} 
::msgcat::mcset ja {Vertical} 
::msgcat::mcset ja {View} [encoding convertfrom euc-jp "\xc9\xbd\xbc\xa8"]
::msgcat::mcset ja {Virtual Observatory} [encoding convertfrom euc-jp "\xb2\xbe\xc1\xdb\xc5\xb7\xca\xb8\xc2\xe6"]
::msgcat::mcset ja {WCS Parameters} 
::msgcat::mcset ja {WCS} 
::msgcat::mcset ja {Wavelength} [encoding convertfrom euc-jp "\xc7\xc8\xc4\xb9"]
::msgcat::mcset ja {Web Browser} [encoding convertfrom euc-jp "\xa5\xd6\xa5\xe9\xa5\xa6\xa5\xb6"]
::msgcat::mcset ja {White} [encoding convertfrom euc-jp "\xc7\xf2\xbf\xa7"]
::msgcat::mcset ja {Width} [encoding convertfrom euc-jp "\xc9\xfd"]
::msgcat::mcset ja {Window} 
::msgcat::mcset ja {Words matching title, description} 
::msgcat::mcset ja {X Axis Title} 
::msgcat::mcset ja {X Axis} 
::msgcat::mcset ja {X Column} 
::msgcat::mcset ja {X Error Column} 
::msgcat::mcset ja {XPA Information} [encoding convertfrom euc-jp "\x58\x50\x41\xa4\xce\xbe\xf0\xca\xf3"]
::msgcat::mcset ja {XPA not initialized} [encoding convertfrom euc-jp "\x58\x50\x41\x20\xa4\xac\xbd\xe9\xb4\xfc\xb2\xbd\xa4\xb5\xa4\xec\xa4\xc6\xa4\xa4\xa4\xde\xa4\xbb\xa4\xf3\xa1\xa3"]
::msgcat::mcset ja {XPA} [encoding convertfrom euc-jp "\x58\x50\x41"]
::msgcat::mcset ja {X} 
::msgcat::mcset ja {Y Axis Title} 
::msgcat::mcset ja {Y Axis} 
::msgcat::mcset ja {Y Column} 
::msgcat::mcset ja {Y Error Column} 
::msgcat::mcset ja {Yellow} [encoding convertfrom euc-jp "\xb2\xab\xbf\xa7"]
::msgcat::mcset ja {Y} 
::msgcat::mcset ja {Z Axis Scale} 
::msgcat::mcset ja {ZScale Parameters} [encoding convertfrom euc-jp "\x5a\xa5\xb9\xa5\xb1\xa1\xbc\xa5\xeb\xa4\xce\xc0\xdf\xc4\xea"]
::msgcat::mcset ja {Zero} [encoding convertfrom euc-jp "\xce\xed"]
::msgcat::mcset ja {Zoom Fit} 
::msgcat::mcset ja {Zoom In} [encoding convertfrom euc-jp "\xb3\xc8\xc2\xe7"]
::msgcat::mcset ja {Zoom Out} [encoding convertfrom euc-jp "\xbd\xcc\xbe\xae"]
::msgcat::mcset ja {Zoom} [encoding convertfrom euc-jp "\xa5\xba\xa1\xbc\xa5\xe0"]
::msgcat::mcset ja {already connected} 
::msgcat::mcset ja {and} 
::msgcat::mcset ja {b} 
::msgcat::mcset ja {g} 
::msgcat::mcset ja {h5utils} 
::msgcat::mcset ja {hundredths second} 
::msgcat::mcset ja {internal error} 
::msgcat::mcset ja {not connected} 
::msgcat::mcset ja {not} 
::msgcat::mcset ja {only} 
::msgcat::mcset ja {or center of data} [encoding convertfrom euc-jp "\xa4\xe2\xa4\xb7\xa4\xaf\xa4\xcf\xa5\xc7\xa1\xbc\xa5\xbf\xa4\xce\xc3\xe6\xbf\xb4"]
::msgcat::mcset ja {rows of data have been downloaded. More may be available. You may wish to adjust the maximum allowed} [encoding convertfrom euc-jp "\xb9\xd4\xa4\xce\xa5\xc7\xa1\xbc\xa5\xbf\xa4\xac\xa5\xc0\xa5\xa6\xa5\xf3\xa5\xed\xa1\xbc\xa5\xc9\xa4\xb5\xa4\xec\xa4\xde\xa4\xb7\xa4\xbf\xa1\xa3\xa4\xb5\xa4\xe9\xa4\xcb\xa5\xc0\xa5\xa6\xa5\xf3\xa5\xed\xa1\xbc\xa5\xc9\xa4\xb9\xa4\xeb\xbe\xec\xb9\xe7\xa4\xcf\xa1\xa2\xba\xc7\xc2\xe7\xb9\xd4\xbf\xf4\xa4\xf2\xc0\xdf\xc4\xea\xa4\xb7\xa4\xca\xa4\xaa\xa4\xb7\xa4\xc6\xa4\xaf\xa4\xc0\xa4\xb5\xa4\xa4\xa1\xa3"]
::msgcat::mcset ja {r} 
::msgcat::mcset ja {unable to locate HUB} 
::msgcat::mcset ja {x} 
