# Clean UTF-8 Translation Catalog for Tcl 9
# Generated automatically from legacy ja.msg

::msgcat::mcset ja 2d 2d
::msgcat::mcset ja 3d 3d
::msgcat::mcset ja {A postscript generation error has occurred} ポストスクリプトファイル作成に失敗しました。
::msgcat::mcset ja AIP AIP
::msgcat::mcset ja Abort Abort
::msgcat::mcset ja {About SAOImageDS9} {About SAOImageDS9}
::msgcat::mcset ja About {DS9 について}
::msgcat::mcset ja Acknowledgment 謝辞
::msgcat::mcset ja {Add Bar Graph} {Add Bar Graph}
::msgcat::mcset ja {Add Graph} {Add Graph}
::msgcat::mcset ja {Add Line Graph} {Add Line Graph}
::msgcat::mcset ja {Add New Frame} {Add New Frame}
::msgcat::mcset ja Add 追加
::msgcat::mcset ja {Advanced Layout} {Advanced Layout}
::msgcat::mcset ja Advanced 高度な設定
::msgcat::mcset ja {Align North Up} {Align North Up}
::msgcat::mcset ja Align 整列
::msgcat::mcset ja {All Columns} 全ての列
::msgcat::mcset ja {All Rows} 全ての行
::msgcat::mcset ja All 全て
::msgcat::mcset ja {Always save files during Backup} {Always save files during Backup}
::msgcat::mcset ja Amplifier 増幅器座標
::msgcat::mcset ja {An error has occurred during backup} {An error has occurred during backup}
::msgcat::mcset ja {An error has occurred during restore} {An error has occurred during restore}
::msgcat::mcset ja {An error has occurred invoking the Analysis task} 解析タスクの起動に失敗しました。
::msgcat::mcset ja {An error has occurred while creating} {An error has occurred while creating}
::msgcat::mcset ja {An error has occurred while loading} {An error has occurred while loading}
::msgcat::mcset ja {An error has occurred while printing} 印刷に失敗しました。
::msgcat::mcset ja {An error has occurred while saving} 保存に失敗しました。
::msgcat::mcset ja {An internal error has been detected} {An internal error has been detected}
::msgcat::mcset ja {Analysis Command Log} 解析コマンドの記録
::msgcat::mcset ja {Analysis Commands} 解析コマンド
::msgcat::mcset ja {Analysis File} {Analysis File}
::msgcat::mcset ja {Analysis Log} {Analysis Log}
::msgcat::mcset ja Analysis 解析
::msgcat::mcset ja {Angle Complement} 補角
::msgcat::mcset ja Angles 角度
::msgcat::mcset ja Angle 角度
::msgcat::mcset ja Annuli 中抜き円
::msgcat::mcset ja Annulus 中抜き円
::msgcat::mcset ja Apply 適用
::msgcat::mcset ja ArcMin 分
::msgcat::mcset ja ArcSec 秒
::msgcat::mcset ja Architecture アーキテクチャ
::msgcat::mcset ja Archives Archives
::msgcat::mcset ja Array Array
::msgcat::mcset ja Arrow 矢印
::msgcat::mcset ja Asteroids Asteroids
::msgcat::mcset ja Astronomy 天文学
::msgcat::mcset ja {At Startup} {At Startup}
::msgcat::mcset ja {At least 2 different catalogs are required} {At least 2 different catalogs are required}
::msgcat::mcset ja {Auto Centroid} 自動中心合わせ
::msgcat::mcset ja {Auto Plot 2D} {Auto Plot 2D}
::msgcat::mcset ja {Auto Plot 3D} {Auto Plot 3D}
::msgcat::mcset ja {Auto Plot Statistics} {Auto Plot Statistics}
::msgcat::mcset ja {Auto Plot} {Auto Plot}
::msgcat::mcset ja {Auto Recovery} {Auto Recovery}
::msgcat::mcset ja {Autoload FITS Regions} 領域の自動読み込み
::msgcat::mcset ja Autoload Autoload
::msgcat::mcset ja Automatic 自動
::msgcat::mcset ja Average 平均
::msgcat::mcset ja {Axes Number} {Axes Number}
::msgcat::mcset ja {Axes Order} {Axes Order}
::msgcat::mcset ja {Axes Range} {Axes Range}
::msgcat::mcset ja {Axes Title} {Axes Title}
::msgcat::mcset ja Axes 軸
::msgcat::mcset ja {Axis Length} 軸の長さ
::msgcat::mcset ja {Axis Numbers} 軸の数値
::msgcat::mcset ja {Axis Title} {Axis Title}
::msgcat::mcset ja Axis 軸
::msgcat::mcset ja Azimuth 方位角
::msgcat::mcset ja {Background Color} 背景色
::msgcat::mcset ja Background バックグラウンド領域
::msgcat::mcset ja Backup Backup
::msgcat::mcset ja Back 前
::msgcat::mcset ja {Bar Dataset} {Bar Dataset}
::msgcat::mcset ja {Bar Plot Tool} {Bar Plot Tool}
::msgcat::mcset ja {Bar Width} {Bar Width}
::msgcat::mcset ja Bar Bar
::msgcat::mcset ja {Basic Layout} {Basic Layout}
::msgcat::mcset ja Basic Basic
::msgcat::mcset ja Behavior Behavior
::msgcat::mcset ja Bias バイアス
::msgcat::mcset ja {Bin 3rd Column} 第３の列をビンまとめ
::msgcat::mcset ja {Bin Center} ビンまとめの中心
::msgcat::mcset ja {Bin Columns} ビンまとめする列
::msgcat::mcset ja {Bin Filter} ビンまとめの絞り込み条件
::msgcat::mcset ja {Bin Fit} {Bin Fit}
::msgcat::mcset ja {Bin In} {Bin In}
::msgcat::mcset ja {Bin Out} {Bin Out}
::msgcat::mcset ja {Binning Parameters} ビンまとめの設定
::msgcat::mcset ja Bins Bins
::msgcat::mcset ja Bin ビンまとめ
::msgcat::mcset ja Black 黒色
::msgcat::mcset ja {Blank/Inf/NaN Color} 未定義値(Blank/Inf/NaN)の色
::msgcat::mcset ja Blend Blend
::msgcat::mcset ja {Blink Frames} フレームをブリンク
::msgcat::mcset ja {Blink Interval} ブリンクの間隔
::msgcat::mcset ja Blink ブリンク
::msgcat::mcset ja {Block Fit} {Block Fit}
::msgcat::mcset ja {Block In} ブロックを細かく
::msgcat::mcset ja {Block Out} ブロックを荒く
::msgcat::mcset ja {Block Parameters} {Block Parameters}
::msgcat::mcset ja {Block Pixel} {Block Pixel}
::msgcat::mcset ja Block ブロック
::msgcat::mcset ja Blue 青色
::msgcat::mcset ja Bold 太字
::msgcat::mcset ja {Border Color} {Border Color}
::msgcat::mcset ja {Border Width} {Border Width}
::msgcat::mcset ja Border 枠線
::msgcat::mcset ja Bottom Bottom
::msgcat::mcset ja {Box Annulus} 中抜き四角形
::msgcat::mcset ja {Box Panda} 部分四角形
::msgcat::mcset ja BoxCircle BoxCircle
::msgcat::mcset ja Boxcar ボックスカー
::msgcat::mcset ja Box 四角形
::msgcat::mcset ja {Bring to Front} {Bring to Front}
::msgcat::mcset ja Broadcast Broadcast
::msgcat::mcset ja Browser Browser
::msgcat::mcset ja Browse 参照
::msgcat::mcset ja Buffer バッファ
::msgcat::mcset ja Buttonbar ボタンバー
::msgcat::mcset ja Buttons ボタン
::msgcat::mcset ja Bytes バイト
::msgcat::mcset ja CMYK CMYK色
::msgcat::mcset ja {Can Delete} 削除可
::msgcat::mcset ja {Can Edit} 編集可
::msgcat::mcset ja {Can Move} 移動可
::msgcat::mcset ja {Can Rotate} 回転可
::msgcat::mcset ja Cancelled Cancelled
::msgcat::mcset ja Cancel 取り消し
::msgcat::mcset ja Cap Cap
::msgcat::mcset ja {Catalog Server} カタログ検索サーバー
::msgcat::mcset ja {Catalog Tool} カタログツール
::msgcat::mcset ja Catalogs カタログ
::msgcat::mcset ja Catalog カタログ
::msgcat::mcset ja Catrom Catrom
::msgcat::mcset ja Cat Cat
::msgcat::mcset ja {Center Dialogs} {Center Dialogs}
::msgcat::mcset ja {Center Image} イメージを中心に
::msgcat::mcset ja Center 中心
::msgcat::mcset ja {Centroid Parameters} 中心合わせ設定
::msgcat::mcset ja Centroid Centroid
::msgcat::mcset ja Circle 円
::msgcat::mcset ja {Clear All} 全て消去
::msgcat::mcset ja {Clear Analysis Commands} 解析コマンドを消去
::msgcat::mcset ja {Clear Cache} キャッシュを消去
::msgcat::mcset ja {Clear External Analysis Commands?} 外部解析コマンドを消去しますか?
::msgcat::mcset ja {Clear Filter} 絞り込み条件を消去
::msgcat::mcset ja {Clear Frame} フレームを消去
::msgcat::mcset ja {Clear Preferences?} 設定を消去しますか?
::msgcat::mcset ja {Clear Preferences} 設定を消去
::msgcat::mcset ja Clear クリア
::msgcat::mcset ja {Click to Center} クリック位置を中心
::msgcat::mcset ja Close 閉じる
::msgcat::mcset ja {Colorbar Size} {Colorbar Size}
::msgcat::mcset ja Colorbar 配色棒
::msgcat::mcset ja {Colormap Parameters} 色調の設定
::msgcat::mcset ja Colormaps Colormaps
::msgcat::mcset ja Colormap 色調
::msgcat::mcset ja Color 色
::msgcat::mcset ja Columns 列
::msgcat::mcset ja Column 列
::msgcat::mcset ja Comets Comets
::msgcat::mcset ja {Command not allowed} {Command not allowed}
::msgcat::mcset ja Command コマンド
::msgcat::mcset ja Compass 方位磁石
::msgcat::mcset ja {Composite Region} 複合領域
::msgcat::mcset ja Composite Composite
::msgcat::mcset ja Compression 圧縮
::msgcat::mcset ja Configure 設定
::msgcat::mcset ja Connect 接続
::msgcat::mcset ja Console Console
::msgcat::mcset ja {Contacting Server} {Contacting Server}
::msgcat::mcset ja {Contour Parameters} コントアの設定
::msgcat::mcset ja {Contour Paste} {Contour Paste}
::msgcat::mcset ja {Contour Save} {Contour Save}
::msgcat::mcset ja Contours コントア
::msgcat::mcset ja Contour Contour
::msgcat::mcset ja Contrast コントラスト
::msgcat::mcset ja {Control Panel} {Control Panel}
::msgcat::mcset ja {Convert to Polygons} 多角形に変換
::msgcat::mcset ja {Coordinate Grid Parameters} 座標グリッドの設定
::msgcat::mcset ja {Coordinate Grid} 座標グリッド
::msgcat::mcset ja {Coordinate System} 座標系
::msgcat::mcset ja Coordinates 座標
::msgcat::mcset ja Coordinate 座標
::msgcat::mcset ja {Copy Contours} コントアをコピー
::msgcat::mcset ja {Copy to Regions} 領域にコピー
::msgcat::mcset ja Copy コピー
::msgcat::mcset ja {Create Composite Region} {Create Composite Region}
::msgcat::mcset ja {Create Movie} {Create Movie}
::msgcat::mcset ja {Create New Frame on Download} ダウンロード時に新しいフレームを作成
::msgcat::mcset ja Create 作成
::msgcat::mcset ja {Crop Parameters} {Crop Parameters}
::msgcat::mcset ja Crop Crop
::msgcat::mcset ja {Crosshair Parameters} {Crosshair Parameters}
::msgcat::mcset ja {Crosshair To} そこに十字線
::msgcat::mcset ja Crosshair 十字カーソル
::msgcat::mcset ja Cross 十字
::msgcat::mcset ja Cubehelix Cubehelix
::msgcat::mcset ja Cube Cube
::msgcat::mcset ja Cubic Cubic
::msgcat::mcset ja {Current Frame} 選択中のフレーム
::msgcat::mcset ja {Current Range} 選択中の範囲
::msgcat::mcset ja Current 選択中
::msgcat::mcset ja Cursor カーソル
::msgcat::mcset ja Cut 切り取り
::msgcat::mcset ja Cyan 水色
::msgcat::mcset ja DMS DMS
::msgcat::mcset ja DPI DPI
::msgcat::mcset ja {DS9 has detected a newer version of a backup file and therefore will not process this file.} {DS9 has detected a newer version of a backup file and therefore will not process this file.}
::msgcat::mcset ja {DS9 has detected a newer version of a preferences file.} {DS9 has detected a newer version of a preferences file.}
::msgcat::mcset ja {DS9 has detected an older backup file, do you wish to continue?} {DS9 has detected an older backup file, do you wish to continue?}
::msgcat::mcset ja {DS9 has detected an older preferences file, do you wish to update?} 古いバージョンの設定ファイルが見つかりました。更新しますか?
::msgcat::mcset ja {DS9 will complete the initialization process} 初期化を完了します。
::msgcat::mcset ja Darken Darken
::msgcat::mcset ja Dash 破線
::msgcat::mcset ja {Data Format} データ形式
::msgcat::mcset ja {Data must be ascii numeric values} {Data must be ascii numeric values}
::msgcat::mcset ja {Dataset Name} {Dataset Name}
::msgcat::mcset ja Dataset データセット
::msgcat::mcset ja Data Data
::msgcat::mcset ja {Decrease Bin} {Decrease Bin}
::msgcat::mcset ja {Decrease Block} {Decrease Block}
::msgcat::mcset ja {Decrease Magnification} {Decrease Magnification}
::msgcat::mcset ja {Decrease Zoom} {Decrease Zoom}
::msgcat::mcset ja Decrease 降順
::msgcat::mcset ja {Default All Files} {Default All Files}
::msgcat::mcset ja {Default Format} {Default Format}
::msgcat::mcset ja {Default Length} {Default Length}
::msgcat::mcset ja Default 標準
::msgcat::mcset ja Degrees 度
::msgcat::mcset ja Delay Delay
::msgcat::mcset ja {Delete All Frames?} 全てのフレームを消去しますか?
::msgcat::mcset ja {Delete All Frames} 全てのフレームを消去
::msgcat::mcset ja {Delete All Groups?} 全てのグループを消去しますか?
::msgcat::mcset ja {Delete All Groups} 全てのグループを消去
::msgcat::mcset ja {Delete All Load} {Delete All Load}
::msgcat::mcset ja {Delete All and Open} {Delete All and Open}
::msgcat::mcset ja {Delete All} 全てを消去
::msgcat::mcset ja {Delete Color Tags} {Delete Color Tags}
::msgcat::mcset ja {Delete Dataset} {Delete Dataset}
::msgcat::mcset ja {Delete Frame} フレームを消去
::msgcat::mcset ja {Delete Graph} {Delete Graph}
::msgcat::mcset ja {Delete Group} グループを消去
::msgcat::mcset ja {Delete Selection} {Delete Selection}
::msgcat::mcset ja {Delete Select} {Delete Select}
::msgcat::mcset ja Delete 消去
::msgcat::mcset ja Depth 深さ
::msgcat::mcset ja Detector 検出器座標
::msgcat::mcset ja {Dialog Box} ポップアップメニュー
::msgcat::mcset ja Diameter Diameter
::msgcat::mcset ja Diamond 菱形
::msgcat::mcset ja Dimensions Dimensions
::msgcat::mcset ja Dimension 次元
::msgcat::mcset ja Direction Direction
::msgcat::mcset ja Disconnect 接続終了
::msgcat::mcset ja {Display Size} サイズを表示
::msgcat::mcset ja {Dissolve Composite Region} {Dissolve Composite Region}
::msgcat::mcset ja Dissolve 分解
::msgcat::mcset ja Distance Distance
::msgcat::mcset ja Done Done
::msgcat::mcset ja {Download Colormap} {Download Colormap}
::msgcat::mcset ja {Drag to Center} 中心にドラッグ
::msgcat::mcset ja {Duplicate Dataset} {Duplicate Dataset}
::msgcat::mcset ja ENVI ENVI
::msgcat::mcset ja EPS EPS
::msgcat::mcset ja East 東
::msgcat::mcset ja Ecliptic 黄道座標
::msgcat::mcset ja {Edit Group Name} グループ名を変更
::msgcat::mcset ja {Edit Mode} {Edit Mode}
::msgcat::mcset ja Edit 編集
::msgcat::mcset ja Elevation 高度
::msgcat::mcset ja {Ellipse Panda} 部分楕円
::msgcat::mcset ja Ellipse 楕円
::msgcat::mcset ja {Elliptical Annulus} 中抜き楕円
::msgcat::mcset ja {Elliptical Gaussian} {Elliptical Gaussian}
::msgcat::mcset ja {Elliptical Panda} 中抜き部分楕円
::msgcat::mcset ja {Enable Confirmation Dialogs} 確認メッセージを表示
::msgcat::mcset ja Enable Enable
::msgcat::mcset ja End 終了
::msgcat::mcset ja {Enter Color} 色を入力
::msgcat::mcset ja {Enter Font Size} {Enter Font Size}
::msgcat::mcset ja {Enter Group Name} グループ名を入力
::msgcat::mcset ja {Enter Search Expression} 検索条件を入力
::msgcat::mcset ja {Enter URL} {Enter URL}
::msgcat::mcset ja Entry Entry
::msgcat::mcset ja {Equal Area} 等面積
::msgcat::mcset ja {Equal Distance} 等距離
::msgcat::mcset ja {Equal Spacing} {Equal Spacing}
::msgcat::mcset ja {Equal Value} {Equal Value}
::msgcat::mcset ja {Error code was returned} エラーコードが返されました。
::msgcat::mcset ja Errorbar Errorbar
::msgcat::mcset ja Error エラー
::msgcat::mcset ja {Examine Frame} フレームを詳細表示
::msgcat::mcset ja Examine 詳細表示
::msgcat::mcset ja Exam Exam
::msgcat::mcset ja Exclude 外側
::msgcat::mcset ja Exit 終了
::msgcat::mcset ja {Export Array} {Export Array}
::msgcat::mcset ja {Export ENVI} {Export ENVI}
::msgcat::mcset ja {Export GIF} {Export GIF}
::msgcat::mcset ja {Export HLS Array} {Export HLS Array}
::msgcat::mcset ja {Export HSV Array} {Export HSV Array}
::msgcat::mcset ja {Export JPEG} {Export JPEG}
::msgcat::mcset ja {Export NRRD} {Export NRRD}
::msgcat::mcset ja {Export PNG} {Export PNG}
::msgcat::mcset ja {Export RGB Array} {Export RGB Array}
::msgcat::mcset ja {Export TIFF} {Export TIFF}
::msgcat::mcset ja Export Export
::msgcat::mcset ja {Extension Data} {Extension Data}
::msgcat::mcset ja {Extension not found} {Extension not found}
::msgcat::mcset ja Extensions Extensions
::msgcat::mcset ja Extension Extension
::msgcat::mcset ja {Exterior Axes} 軸を外側に
::msgcat::mcset ja {Exterior Numerics} 数値を外側に
::msgcat::mcset ja FAQ よくある質問と答え
::msgcat::mcset ja FITS FITS
::msgcat::mcset ja FK4 FK4
::msgcat::mcset ja FK5 FK5
::msgcat::mcset ja FP FP
::msgcat::mcset ja Factor Factor
::msgcat::mcset ja {Fade Frames} {Fade Frames}
::msgcat::mcset ja {Fade Interval} {Fade Interval}
::msgcat::mcset ja Fade Fade
::msgcat::mcset ja {File Open} {File Open}
::msgcat::mcset ja {File not Found or Unable to load FITS data MIME type} {ファイルが見つかりません。または、FITS データが読み込めません。}
::msgcat::mcset ja {File not found} {File not found}
::msgcat::mcset ja {Filename Format} {Filename Format}
::msgcat::mcset ja Filename ファイル名
::msgcat::mcset ja File ファイル
::msgcat::mcset ja Fill Fill
::msgcat::mcset ja Filter 絞り込み
::msgcat::mcset ja {Find Next} 次を検索
::msgcat::mcset ja Find 検索
::msgcat::mcset ja {First Block} {First Block}
::msgcat::mcset ja {First Frame} 最初のフレーム
::msgcat::mcset ja First 最初
::msgcat::mcset ja Fits Fits
::msgcat::mcset ja {Fixed in Size} サイズ固定
::msgcat::mcset ja Flip Flip
::msgcat::mcset ja Font フォント
::msgcat::mcset ja {Footprint Servers} {Footprint Servers}
::msgcat::mcset ja Footprint Footprint
::msgcat::mcset ja {For more information, use --help} {詳しくは --help オプションで。}
::msgcat::mcset ja Foreground Foreground
::msgcat::mcset ja Forground Forground
::msgcat::mcset ja Format 形式
::msgcat::mcset ja Forward 次
::msgcat::mcset ja {Found Auto Backup, restore?} {Found Auto Backup, restore?}
::msgcat::mcset ja Found Found
::msgcat::mcset ja {Frame Information} フレームの情報
::msgcat::mcset ja {Frame Layout} {Frame Layout}
::msgcat::mcset ja {Frame Parameters} フレームの設定
::msgcat::mcset ja Frames Frames
::msgcat::mcset ja Frame フレーム
::msgcat::mcset ja From From
::msgcat::mcset ja Front 全面
::msgcat::mcset ja {Full Range} 全範囲
::msgcat::mcset ja Function 関数
::msgcat::mcset ja GIF GIF
::msgcat::mcset ja GUI GUI
::msgcat::mcset ja Galactic 銀河座標
::msgcat::mcset ja Gap Gap
::msgcat::mcset ja Gaussian ガウシアン
::msgcat::mcset ja General 一般
::msgcat::mcset ja Generate 生成
::msgcat::mcset ja {Generating Regions} 領域を作成中
::msgcat::mcset ja {Get Information} 情報を取得
::msgcat::mcset ja {Get Region Info} {Get Region Info}
::msgcat::mcset ja Gist Gist
::msgcat::mcset ja {Global Properties} グローバルプロパティ
::msgcat::mcset ja Global グローバル
::msgcat::mcset ja {Goto First Frame} {Goto First Frame}
::msgcat::mcset ja {Goto Frame} 指定フレームに移動
::msgcat::mcset ja {Goto Last Frame} {Goto Last Frame}
::msgcat::mcset ja {Goto Next Frame} {Goto Next Frame}
::msgcat::mcset ja {Goto Previous Frame} {Goto Previous Frame}
::msgcat::mcset ja {Goto Row} {Goto Row}
::msgcat::mcset ja Goto Goto
::msgcat::mcset ja {Graph Horz} 横断面図
::msgcat::mcset ja {Graph Parameters} {Graph Parameters}
::msgcat::mcset ja {Graph Vert} 縦断面図
::msgcat::mcset ja Graphics Graphics
::msgcat::mcset ja Graphs Graphs
::msgcat::mcset ja Graph グラフ
::msgcat::mcset ja Grayscale グレースケール
::msgcat::mcset ja Green 緑色
::msgcat::mcset ja {Grid Gap} グリッドの間隔
::msgcat::mcset ja Grid グリッド
::msgcat::mcset ja Groups グループ
::msgcat::mcset ja {HLS Array} {HLS Array}
::msgcat::mcset ja {HLS Cube} {HLS Cube}
::msgcat::mcset ja {HLS Image} {HLS Image}
::msgcat::mcset ja HLS HLS
::msgcat::mcset ja HMS HMS
::msgcat::mcset ja {HSV Array} {HSV Array}
::msgcat::mcset ja {HSV Cube} {HSV Cube}
::msgcat::mcset ja {HSV Image} {HSV Image}
::msgcat::mcset ja HSV HSV
::msgcat::mcset ja HTTP HTTP
::msgcat::mcset ja Header ヘッダ
::msgcat::mcset ja Height 高さ
::msgcat::mcset ja {Help Desk} ヘルプデスク
::msgcat::mcset ja {Help Me Choose} 選択のヒント
::msgcat::mcset ja Help ヘルプ
::msgcat::mcset ja {Hide All} 全て非表示
::msgcat::mcset ja Highlite Highlite
::msgcat::mcset ja High 上限
::msgcat::mcset ja {Histogram Equalization} ヒストグラム等分布
::msgcat::mcset ja Histogram ヒストグラム
::msgcat::mcset ja {Horizontal Graph} 横断面
::msgcat::mcset ja {Horizontal Layout} 画像の上に配置
::msgcat::mcset ja Horizontal Horizontal
::msgcat::mcset ja {Hub not running} {Hub not running}
::msgcat::mcset ja Hue Hue
::msgcat::mcset ja {IAU Location Code} {IAU Location Code}
::msgcat::mcset ja ICRS 国際天文準拠系
::msgcat::mcset ja Icons Icons
::msgcat::mcset ja Identification 同定
::msgcat::mcset ja If もし
::msgcat::mcset ja Illustrate Illustrate
::msgcat::mcset ja {Image Servers} {Image Servers}
::msgcat::mcset ja Image 論理座標
::msgcat::mcset ja {Import Array} {Import Array}
::msgcat::mcset ja {Import ENVI} {Import ENVI}
::msgcat::mcset ja {Import GIF} {Import GIF}
::msgcat::mcset ja {Import HLS Array} {Import HLS Array}
::msgcat::mcset ja {Import HSV Array} {Import HSV Array}
::msgcat::mcset ja {Import JPEG} {Import JPEG}
::msgcat::mcset ja {Import NRRD} {Import NRRD}
::msgcat::mcset ja {Import PNG} {Import PNG}
::msgcat::mcset ja {Import RGB Array} {Import RGB Array}
::msgcat::mcset ja {Import Slice GIF} {Import Slice GIF}
::msgcat::mcset ja {Import Slice JPEG} {Import Slice JPEG}
::msgcat::mcset ja {Import Slice PNG} {Import Slice PNG}
::msgcat::mcset ja {Import Slice TIFF} {Import Slice TIFF}
::msgcat::mcset ja {Import TIFF} {Import TIFF}
::msgcat::mcset ja Import Import
::msgcat::mcset ja Include 内側
::msgcat::mcset ja {Increase Bin} {Increase Bin}
::msgcat::mcset ja {Increase Block} {Increase Block}
::msgcat::mcset ja {Increase Magnification} {Increase Magnification}
::msgcat::mcset ja {Increase Zoom} {Increase Zoom}
::msgcat::mcset ja Increase 昇順
::msgcat::mcset ja {Info Box} {Info Box}
::msgcat::mcset ja {Information Panel} 情報パネル
::msgcat::mcset ja Information 情報
::msgcat::mcset ja {Initialize XPA} {XPA を初期化}
::msgcat::mcset ja Inner 内径
::msgcat::mcset ja {Instrument FOV} 検出器の視野
::msgcat::mcset ja Instrument Instrument
::msgcat::mcset ja {Interior Axes} 軸を内側に
::msgcat::mcset ja {Interior Numerics} 数値を内側に
::msgcat::mcset ja {Internal Parse Error} 内部解釈エラー
::msgcat::mcset ja Interval 間隔
::msgcat::mcset ja {Invalid Column Name} {Invalid Column Name}
::msgcat::mcset ja {Invalid WCS} {Invalid WCS}
::msgcat::mcset ja {Invalid formated multipart/mixed mime type message} {Invalid formated multipart/mixed mime type message}
::msgcat::mcset ja {Invert Colormap} 色調を反転
::msgcat::mcset ja Invert 反転
::msgcat::mcset ja Italic イタリック
::msgcat::mcset ja {Items Found} {Items Found}
::msgcat::mcset ja Iteration 繰り返し
::msgcat::mcset ja {JPEG Quality Factor} JPEGの品質
::msgcat::mcset ja JPEG JPEG
::msgcat::mcset ja Justify Justify
::msgcat::mcset ja Keep-Alive Keep-Alive
::msgcat::mcset ja Keyword Keyword
::msgcat::mcset ja Labels ラベル
::msgcat::mcset ja Label ラベル
::msgcat::mcset ja Landscape 横長
::msgcat::mcset ja Language 言語
::msgcat::mcset ja {Last Block} {Last Block}
::msgcat::mcset ja {Last Frame} 最後のフレーム
::msgcat::mcset ja Last 最後
::msgcat::mcset ja Layout Layout
::msgcat::mcset ja Left Left
::msgcat::mcset ja Legal リーガル
::msgcat::mcset ja {Legend Position} {Legend Position}
::msgcat::mcset ja {Legend Title} {Legend Title}
::msgcat::mcset ja Legend Legend
::msgcat::mcset ja Length 長さ
::msgcat::mcset ja Letter レター
::msgcat::mcset ja Levels レベル
::msgcat::mcset ja Level レベル
::msgcat::mcset ja Lighten Lighten
::msgcat::mcset ja Lightness Lightness
::msgcat::mcset ja Limits 上下限
::msgcat::mcset ja {Line Dataset} {Line Dataset}
::msgcat::mcset ja {Line Plot Tool} {Line Plot Tool}
::msgcat::mcset ja Linear 線形
::msgcat::mcset ja Line 線
::msgcat::mcset ja {List Data} {List Data}
::msgcat::mcset ja {List Regions} 領域を列挙
::msgcat::mcset ja {List Region} {List Region}
::msgcat::mcset ja {List Selection} {List Selection}
::msgcat::mcset ja {List Select} {List Select}
::msgcat::mcset ja List 列挙
::msgcat::mcset ja {Load Analysis Commands} 解析コマンドの読み込み
::msgcat::mcset ja {Load Color Tags} {Load Color Tags}
::msgcat::mcset ja {Load Contour Levels} コントアレベルの読み込み
::msgcat::mcset ja {Load Contrast/Bias} コントラスト・バイアスの読み込み
::msgcat::mcset ja {Load Data} データの読み込み
::msgcat::mcset ja {Load Mosaic} モザイクの読み込み
::msgcat::mcset ja {Load Template} 雛形の読み込み
::msgcat::mcset ja {Load into All} {Load into All}
::msgcat::mcset ja {Load into Current} {Load into Current}
::msgcat::mcset ja {Loading Catalog} カタログを読み込み中
::msgcat::mcset ja Loading 読み込み中
::msgcat::mcset ja Load 読み込み
::msgcat::mcset ja Local ローカル
::msgcat::mcset ja {Lock Axes} {Lock Axes}
::msgcat::mcset ja {Lock Bin} {Lock Bin}
::msgcat::mcset ja {Lock Color} {Lock Color}
::msgcat::mcset ja {Lock Crop Amplifier} {Lock Crop Amplifier}
::msgcat::mcset ja {Lock Crop Detector} {Lock Crop Detector}
::msgcat::mcset ja {Lock Crop Image} {Lock Crop Image}
::msgcat::mcset ja {Lock Crop None} {Lock Crop None}
::msgcat::mcset ja {Lock Crop Physical} {Lock Crop Physical}
::msgcat::mcset ja {Lock Crop WCS} {Lock Crop WCS}
::msgcat::mcset ja {Lock Crosshair Amplifier} {Lock Crosshair Amplifier}
::msgcat::mcset ja {Lock Crosshair Detector} {Lock Crosshair Detector}
::msgcat::mcset ja {Lock Crosshair Image} {Lock Crosshair Image}
::msgcat::mcset ja {Lock Crosshair None} {Lock Crosshair None}
::msgcat::mcset ja {Lock Crosshair Physical} {Lock Crosshair Physical}
::msgcat::mcset ja {Lock Crosshair WCS} {Lock Crosshair WCS}
::msgcat::mcset ja {Lock Frame Amplifier} {Lock Frame Amplifier}
::msgcat::mcset ja {Lock Frame Detector} {Lock Frame Detector}
::msgcat::mcset ja {Lock Frame Image} {Lock Frame Image}
::msgcat::mcset ja {Lock Frame None} {Lock Frame None}
::msgcat::mcset ja {Lock Frame Physical} {Lock Frame Physical}
::msgcat::mcset ja {Lock Frame WCS} {Lock Frame WCS}
::msgcat::mcset ja {Lock Limits} {Lock Limits}
::msgcat::mcset ja {Lock Scale} {Lock Scale}
::msgcat::mcset ja {Lock Slice Image} {Lock Slice Image}
::msgcat::mcset ja {Lock Slice None} {Lock Slice None}
::msgcat::mcset ja {Lock Slice WCS} {Lock Slice WCS}
::msgcat::mcset ja {Lock Smooth} {Lock Smooth}
::msgcat::mcset ja Lock 固定
::msgcat::mcset ja {Log Exponent} {Log Exponent}
::msgcat::mcset ja Log 対数
::msgcat::mcset ja {Low High} 上限・下限
::msgcat::mcset ja {Lower Left Back} {Lower Left Back}
::msgcat::mcset ja {Lower Left Front} {Lower Left Front}
::msgcat::mcset ja {Lower Right Back} {Lower Right Back}
::msgcat::mcset ja {Lower Right Front} {Lower Right Front}
::msgcat::mcset ja Low 下限
::msgcat::mcset ja MIP MIP
::msgcat::mcset ja Magenta 桃色
::msgcat::mcset ja Magnification Magnification
::msgcat::mcset ja Magnifier 拡大図
::msgcat::mcset ja {Major Radius} {Major Radius}
::msgcat::mcset ja {Major Sigma} {Major Sigma}
::msgcat::mcset ja Major 長軸
::msgcat::mcset ja Manual 手動
::msgcat::mcset ja {Mask Parameters} マスクの設定
::msgcat::mcset ja {Match Axes} {Match Axes}
::msgcat::mcset ja {Match Bin} {Match Bin}
::msgcat::mcset ja {Match Catalog requires at least 1 row per catalog} {Match Catalog requires at least 1 row per catalog}
::msgcat::mcset ja {Match Color} {Match Color}
::msgcat::mcset ja {Match Crop Amplifier} {Match Crop Amplifier}
::msgcat::mcset ja {Match Crop Detector} {Match Crop Detector}
::msgcat::mcset ja {Match Crop Image} {Match Crop Image}
::msgcat::mcset ja {Match Crop Physical} {Match Crop Physical}
::msgcat::mcset ja {Match Crop WCS} {Match Crop WCS}
::msgcat::mcset ja {Match Crosshair Amplifier} {Match Crosshair Amplifier}
::msgcat::mcset ja {Match Crosshair Detector} {Match Crosshair Detector}
::msgcat::mcset ja {Match Crosshair Image} {Match Crosshair Image}
::msgcat::mcset ja {Match Crosshair Physical} {Match Crosshair Physical}
::msgcat::mcset ja {Match Crosshair WCS} {Match Crosshair WCS}
::msgcat::mcset ja {Match Frame Amplifier} {Match Frame Amplifier}
::msgcat::mcset ja {Match Frame Detector} {Match Frame Detector}
::msgcat::mcset ja {Match Frame Image} {Match Frame Image}
::msgcat::mcset ja {Match Frame Physical} {Match Frame Physical}
::msgcat::mcset ja {Match Frame WCS} {Match Frame WCS}
::msgcat::mcset ja {Match Frames on WCS} {Match Frames on WCS}
::msgcat::mcset ja {Match Limits} {Match Limits}
::msgcat::mcset ja {Match Scale} {Match Scale}
::msgcat::mcset ja {Match Slice Image} {Match Slice Image}
::msgcat::mcset ja {Match Slice WCS} {Match Slice WCS}
::msgcat::mcset ja {Match Smooth} {Match Smooth}
::msgcat::mcset ja Match Match
::msgcat::mcset ja {Math Function} 関数
::msgcat::mcset ja {Matplotlib Cyclic} {Matplotlib Cyclic}
::msgcat::mcset ja {Matplotlib Diverging} {Matplotlib Diverging}
::msgcat::mcset ja {Matplotlib Sequential} {Matplotlib Sequential}
::msgcat::mcset ja {Matplotlib Uniform} {Matplotlib Uniform}
::msgcat::mcset ja {Max Rows} 最大行数
::msgcat::mcset ja Maximum Maximum
::msgcat::mcset ja Max 最大
::msgcat::mcset ja Median Median
::msgcat::mcset ja {Menus and Buttons} {Menus and Buttons}
::msgcat::mcset ja Menu メニュー
::msgcat::mcset ja {Message Log} メッセージの記録
::msgcat::mcset ja Metadata Metadata
::msgcat::mcset ja Method 計算法
::msgcat::mcset ja {Min Max Parameters} {Min Max Parameters}
::msgcat::mcset ja {Min Max} 最大・最小
::msgcat::mcset ja Minimum Minimum
::msgcat::mcset ja {Minor Radius} {Minor Radius}
::msgcat::mcset ja {Minor Sigma} {Minor Sigma}
::msgcat::mcset ja Minor 短軸
::msgcat::mcset ja Minutes Minutes
::msgcat::mcset ja Min 最小
::msgcat::mcset ja Mission ミッション
::msgcat::mcset ja Mode Mode
::msgcat::mcset ja {Mosaic IRAF Segment} {Mosaic IRAF Segment}
::msgcat::mcset ja {Mosaic IRAF} {Mosaic IRAF}
::msgcat::mcset ja {Mosaic WCS Segment} {Mosaic WCS Segment}
::msgcat::mcset ja {Mosaic WCS} {Mosaic WCS}
::msgcat::mcset ja {Mosaic WFPC2} {Mosaic WFPC2}
::msgcat::mcset ja Mosaic Mosaic
::msgcat::mcset ja {Mouse Click Epsilon} {Mouse Click Epsilon}
::msgcat::mcset ja {Mouse Wheel Bin} {Mouse Wheel Bin}
::msgcat::mcset ja {Mouse Wheel Zoom} {Mouse Wheel Zoom}
::msgcat::mcset ja {Move Back} 前に移動
::msgcat::mcset ja {Move First} 最初に移動
::msgcat::mcset ja {Move Forward} 次に移動
::msgcat::mcset ja {Move Frame} フレームを移動
::msgcat::mcset ja {Move Front} {Move Front}
::msgcat::mcset ja {Move Last} 最後に移動
::msgcat::mcset ja {Move to Back} 背面に移動
::msgcat::mcset ja {Move to Front} 前面に移動
::msgcat::mcset ja Movie Movie
::msgcat::mcset ja {Muliple Extension Cube} {Muliple Extension Cube}
::msgcat::mcset ja {Muliple Extension Frames} {Muliple Extension Frames}
::msgcat::mcset ja {Multi Colorbars} {Multi Colorbars}
::msgcat::mcset ja {Multiple Colorbars} {Multiple Colorbars}
::msgcat::mcset ja {Multiple Extension Cube} {Multiple Extension Cube}
::msgcat::mcset ja {Multiple Extension Frames} {Multiple Extension Frames}
::msgcat::mcset ja {Multiple WCS} 複数WCS
::msgcat::mcset ja NAN NAN
::msgcat::mcset ja NRRD NRRD
::msgcat::mcset ja {Name Resolution} 名前で検索
::msgcat::mcset ja {Name Server} 天体名検索サーバー
::msgcat::mcset ja {Name or Designation} 天体名
::msgcat::mcset ja Name Name
::msgcat::mcset ja {Native Dialog} {Native Dialog}
::msgcat::mcset ja {New Features} 新しい機能
::msgcat::mcset ja {New Frame 3D} 新しい3Dフレーム
::msgcat::mcset ja {New Frame HLS} {New Frame HLS}
::msgcat::mcset ja {New Frame HSV} {New Frame HSV}
::msgcat::mcset ja {New Frame RGB} 新しいRGBフレーム
::msgcat::mcset ja {New Frame each Time} 毎回新しいフレーム作成
::msgcat::mcset ja {New Frame} 新しいフレーム
::msgcat::mcset ja {New Graph} {New Graph}
::msgcat::mcset ja {New Group} 新しいグループ
::msgcat::mcset ja {New Plot} {New Plot}
::msgcat::mcset ja New 新規
::msgcat::mcset ja {Next Block} {Next Block}
::msgcat::mcset ja {Next Frame} 次のフレーム
::msgcat::mcset ja Next 進む
::msgcat::mcset ja {No Catalog specified} カタログが指定されていません。
::msgcat::mcset ja {No Data Available} {No Data Available}
::msgcat::mcset ja {No Items Found} 見つかりませんでした。
::msgcat::mcset ja Non-NAN Non-NAN
::msgcat::mcset ja Non-Zero Non-Zero
::msgcat::mcset ja None なし
::msgcat::mcset ja Normal 標準
::msgcat::mcset ja North 北
::msgcat::mcset ja {Not Found} {Not Found}
::msgcat::mcset ja {Not Supported} {Not Supported}
::msgcat::mcset ja {Not valid export format} {Not valid export format}
::msgcat::mcset ja Notes Notes
::msgcat::mcset ja {Number of Samples} サンプルの数
::msgcat::mcset ja {Number of Threads} {Number of Threads}
::msgcat::mcset ja {Number of Ticks} {Number of Ticks}
::msgcat::mcset ja Number 番号
::msgcat::mcset ja Numerics 数値
::msgcat::mcset ja OK 了解
::msgcat::mcset ja Object 天体名
::msgcat::mcset ja ObsId ObsId
::msgcat::mcset ja {Open File} ファイルを開く
::msgcat::mcset ja {Open HLS Cube} {Open HLS Cube}
::msgcat::mcset ja {Open HLS Image} {Open HLS Image}
::msgcat::mcset ja {Open HSV Cube} {Open HSV Cube}
::msgcat::mcset ja {Open HSV Image} {Open HSV Image}
::msgcat::mcset ja {Open ME Cube} {Open ME Cube}
::msgcat::mcset ja {Open ME Frames} {Open ME Frames}
::msgcat::mcset ja {Open Mosaic IRAF Seg} {Open Mosaic IRAF Seg}
::msgcat::mcset ja {Open Mosaic IRAF} {Open Mosaic IRAF}
::msgcat::mcset ja {Open Mosaic WCS Seg} {Open Mosaic WCS Seg}
::msgcat::mcset ja {Open Mosaic WCS} {Open Mosaic WCS}
::msgcat::mcset ja {Open Mosaic WFPC2} {Open Mosaic WFPC2}
::msgcat::mcset ja {Open Notepad} {Open Notepad}
::msgcat::mcset ja {Open Prism} {Open Prism}
::msgcat::mcset ja {Open RGB Cube} {Open RGB Cube}
::msgcat::mcset ja {Open RGB Image} {Open RGB Image}
::msgcat::mcset ja {Open Region File} {Open Region File}
::msgcat::mcset ja {Open Regions} {Open Regions}
::msgcat::mcset ja {Open Slice} {Open Slice}
::msgcat::mcset ja {Open TCL Console} {TCL コンソールを開く}
::msgcat::mcset ja {Open URL} {URL を開く}
::msgcat::mcset ja {Open as} {Open as}
::msgcat::mcset ja Open 開く
::msgcat::mcset ja Operator 演算子
::msgcat::mcset ja Orientation 方向
::msgcat::mcset ja Origin Origin
::msgcat::mcset ja Oscillate Oscillate
::msgcat::mcset ja {Other Color} {Other Color}
::msgcat::mcset ja {Other Font Size} {Other Font Size}
::msgcat::mcset ja Other その他
::msgcat::mcset ja Outer 外径
::msgcat::mcset ja Overplot Overplot
::msgcat::mcset ja {Override Color} {Override Color}
::msgcat::mcset ja PNG PNG
::msgcat::mcset ja {PS Page Setup} PSページ設定
::msgcat::mcset ja {PS Print} PS印刷
::msgcat::mcset ja {Page Setup} ページ設定
::msgcat::mcset ja {Page Source} ページのソース
::msgcat::mcset ja {Pan To} そこにパン
::msgcat::mcset ja {Pan Zoom Rotate Parameters} パン・ズーム・回転の設定
::msgcat::mcset ja {Pan Zoom} パン・ズーム
::msgcat::mcset ja {Pan then Zoom} パンのちズーム
::msgcat::mcset ja {Pan to Center} {Pan to Center}
::msgcat::mcset ja Panda 部分円
::msgcat::mcset ja Panner 全体図
::msgcat::mcset ja Pan パン
::msgcat::mcset ja Parameters パラメータ
::msgcat::mcset ja Password パスワード
::msgcat::mcset ja {Paste Contours} コントアを貼り付け
::msgcat::mcset ja Paste 貼り付け
::msgcat::mcset ja Percent Percent
::msgcat::mcset ja Physical 物理座標
::msgcat::mcset ja {Pixel Distribution} ピクセル頻度分布
::msgcat::mcset ja {Pixel Size} ピクセルサイズ
::msgcat::mcset ja {Pixel Table} ピクセル表
::msgcat::mcset ja Pixels ピクセル
::msgcat::mcset ja Planets Planets
::msgcat::mcset ja Play 再生
::msgcat::mcset ja {Please Select a Region} 領域を指定してください。
::msgcat::mcset ja {Please change the file's permission to disable other users write access. Use anyway?} {Please change the file's permission to disable other users write access. Use anyway?}
::msgcat::mcset ja {Please specify instruments} {Please specify instruments}
::msgcat::mcset ja {Please specify radius and either name or (ra,dec)} {Please specify radius and either name or (ra,dec)}
::msgcat::mcset ja {Please specify width, height, and either name or (ra,dec)} {幅、高さ、名前もしくは (ra,dec) を指定してください。}
::msgcat::mcset ja {Plot 2D} {Plot 2D}
::msgcat::mcset ja {Plot 3D} {Plot 3D}
::msgcat::mcset ja {Plot Area} {Plot Area}
::msgcat::mcset ja {Plot Control Panel} {Plot Control Panel}
::msgcat::mcset ja {Plot Tool} {Plot Tool}
::msgcat::mcset ja {Plotting Regions} 領域をプロットしています
::msgcat::mcset ja Plot プロット
::msgcat::mcset ja Plus ＋
::msgcat::mcset ja Pointer ポインタ
::msgcat::mcset ja Points 点
::msgcat::mcset ja Point 点
::msgcat::mcset ja Polygon 多角形
::msgcat::mcset ja Portrait 縦長
::msgcat::mcset ja Position Position
::msgcat::mcset ja Poster ポスター
::msgcat::mcset ja Postscript ポストスクリプト
::msgcat::mcset ja Power 冪乗
::msgcat::mcset ja Precision Precision
::msgcat::mcset ja Preferences 設定
::msgcat::mcset ja {Preserve During Load} 読み込み中に保持
::msgcat::mcset ja {Previous Block} {Previous Block}
::msgcat::mcset ja {Previous Frame} 前のフレーム
::msgcat::mcset ja Previous 戻る
::msgcat::mcset ja Prev Prev
::msgcat::mcset ja {Print Coordinates} 座標を印刷
::msgcat::mcset ja {Print To} 出力先
::msgcat::mcset ja Printer プリンタ
::msgcat::mcset ja Print 印刷
::msgcat::mcset ja {Prism Goto} {Prism Goto}
::msgcat::mcset ja Prism Prism
::msgcat::mcset ja Projection 切断面
::msgcat::mcset ja Properties 属性
::msgcat::mcset ja Property 属性
::msgcat::mcset ja {Proxy Host} プロキシサーバー
::msgcat::mcset ja {Proxy Port} プロキシポート
::msgcat::mcset ja {Public ID} {Public ID}
::msgcat::mcset ja Publication 論文
::msgcat::mcset ja Quadratic Quadratic
::msgcat::mcset ja RDB RDB
::msgcat::mcset ja {RGB Array} {RGB Array}
::msgcat::mcset ja {RGB Cube} {RGB Cube}
::msgcat::mcset ja {RGB Image} {RGB Image}
::msgcat::mcset ja RGB RGB色
::msgcat::mcset ja {Radial Profile} {Radial Profile}
::msgcat::mcset ja Radius 半径
::msgcat::mcset ja Range Range
::msgcat::mcset ja Redo もう一度
::msgcat::mcset ja Red 赤色
::msgcat::mcset ja {Reference Manual} リファレンスマニュアル
::msgcat::mcset ja Reference リファレンス
::msgcat::mcset ja {Refresh Frame} フレームを再描画
::msgcat::mcset ja Refresh 再描画
::msgcat::mcset ja {Region Color} {Region Color}
::msgcat::mcset ja {Region Line Width} {Region Line Width}
::msgcat::mcset ja {Region Parameters} 領域の設定
::msgcat::mcset ja {Region Shape} {Region Shape}
::msgcat::mcset ja Region 領域
::msgcat::mcset ja Registration Registration
::msgcat::mcset ja {Release Notes} リリースノート
::msgcat::mcset ja Release リリース
::msgcat::mcset ja Reload 再読み込み
::msgcat::mcset ja Render Render
::msgcat::mcset ja Repeat Repeat
::msgcat::mcset ja {Reset Colormap} 色調をリセット
::msgcat::mcset ja {Reset Frame} フレームをリセット
::msgcat::mcset ja Reset リセット
::msgcat::mcset ja Restore Restore
::msgcat::mcset ja Retrieve 検索
::msgcat::mcset ja Return Return
::msgcat::mcset ja Right Right
::msgcat::mcset ja Roman Roman
::msgcat::mcset ja Rotate 回転
::msgcat::mcset ja Rows 行
::msgcat::mcset ja Row Row
::msgcat::mcset ja Ruler ものさし
::msgcat::mcset ja {SAMP Connect} {SAMP Connect}
::msgcat::mcset ja {SAMP Disconnect} {SAMP Disconnect}
::msgcat::mcset ja {SAMP Hub Start} {SAMP Hub Start}
::msgcat::mcset ja {SAMP Hub Stop} {SAMP Hub Stop}
::msgcat::mcset ja {SAMP Hub} {SAMP Hub}
::msgcat::mcset ja {SAMP Table} {SAMP Table}
::msgcat::mcset ja {SAMP WebHub Start} {SAMP WebHub Start}
::msgcat::mcset ja {SAMP: not connected} {SAMP: 未接続}
::msgcat::mcset ja SAMP SAMP
::msgcat::mcset ja {Sample Increment} {Sample Increment}
::msgcat::mcset ja {Sample Parameters} {Sample Parameters}
::msgcat::mcset ja {Samples per Line} １行あたりのサンプル
::msgcat::mcset ja Sample Sample
::msgcat::mcset ja Saturation Saturation
::msgcat::mcset ja {Save 3D Movie} {Save 3D Movie}
::msgcat::mcset ja {Save Color Tags} {Save Color Tags}
::msgcat::mcset ja {Save Contour Levels} コントアレベルを保存
::msgcat::mcset ja {Save Contrast/Bias} コントラスト・バイアスを保存
::msgcat::mcset ja {Save Data} データを保存
::msgcat::mcset ja {Save HLS Cube} {Save HLS Cube}
::msgcat::mcset ja {Save HLS Image} {Save HLS Image}
::msgcat::mcset ja {Save HSV Cube} {Save HSV Cube}
::msgcat::mcset ja {Save HSV Image} {Save HSV Image}
::msgcat::mcset ja {Save Image EPS} {Save Image EPS}
::msgcat::mcset ja {Save Image FITS} {Save Image FITS}
::msgcat::mcset ja {Save Image GIF} {Save Image GIF}
::msgcat::mcset ja {Save Image JPEG} {Save Image JPEG}
::msgcat::mcset ja {Save Image PNG} {Save Image PNG}
::msgcat::mcset ja {Save Image TIFF} {Save Image TIFF}
::msgcat::mcset ja {Save Image on Download} {Save Image on Download}
::msgcat::mcset ja {Save Image} イメージを保存
::msgcat::mcset ja {Save ME Cube} {Save ME Cube}
::msgcat::mcset ja {Save Mosaic WCS Seg} {Save Mosaic WCS Seg}
::msgcat::mcset ja {Save Mosaic WCS} {Save Mosaic WCS}
::msgcat::mcset ja {Save RGB Cube} {Save RGB Cube}
::msgcat::mcset ja {Save RGB Image} {Save RGB Image}
::msgcat::mcset ja {Save Region File} {Save Region File}
::msgcat::mcset ja {Save Regions} 領域を保存
::msgcat::mcset ja {Save Selection} {Save Selection}
::msgcat::mcset ja {Save Select} {Save Select}
::msgcat::mcset ja {Save Slice} {Save Slice}
::msgcat::mcset ja {Save Template} 雛形を保存
::msgcat::mcset ja {Save as EPS} {Save as EPS}
::msgcat::mcset ja {Save as PNG} {Save as PNG}
::msgcat::mcset ja {Save as} {Save as}
::msgcat::mcset ja Save 保存
::msgcat::mcset ja {Scale Parameters} スケールの設定
::msgcat::mcset ja {Scale and Limits} {Scale and Limits}
::msgcat::mcset ja Scale スケール
::msgcat::mcset ja {Scaling Option} {Scaling Option}
::msgcat::mcset ja {Scaling Parameters} {Scaling Parameters}
::msgcat::mcset ja Scan スキャン
::msgcat::mcset ja {Scatter Dataset} {Scatter Dataset}
::msgcat::mcset ja {Scatter Plot Tool} {Scatter Plot Tool}
::msgcat::mcset ja {Scientific Colour Maps} {Scientific Colour Maps}
::msgcat::mcset ja Scope スコープ
::msgcat::mcset ja Screen Screen
::msgcat::mcset ja {Search for Catalogs} カタログを検索
::msgcat::mcset ja Seconds 秒
::msgcat::mcset ja Second Second
::msgcat::mcset ja Segment Segment
::msgcat::mcset ja {Select All} 全て選択
::msgcat::mcset ja {Select Coordinate System } 座標系を選択
::msgcat::mcset ja {Select Dataset} {Select Dataset}
::msgcat::mcset ja {Select Datatset} {Select Datatset}
::msgcat::mcset ja {Select Graph} {Select Graph}
::msgcat::mcset ja {Select None} 選択を解除
::msgcat::mcset ja {Send to Back} {Send to Back}
::msgcat::mcset ja Send 送信
::msgcat::mcset ja Server サーバー
::msgcat::mcset ja {Set Bin to 1} {Set Bin to 1}
::msgcat::mcset ja {Set Block to 1} {Set Block to 1}
::msgcat::mcset ja {Set Zoom to 1} {Set Zoom to 1}
::msgcat::mcset ja Sexagesimal 時分秒
::msgcat::mcset ja Shadow Shadow
::msgcat::mcset ja Shape 形
::msgcat::mcset ja {Show All} 全て表示
::msgcat::mcset ja {Show Command} {Show Command}
::msgcat::mcset ja {Show Compass} {Show Compass}
::msgcat::mcset ja {Show Legend} {Show Legend}
::msgcat::mcset ja {Show Text} 文字を表示
::msgcat::mcset ja {Show/Hide Frames} フレームの表示/非表示
::msgcat::mcset ja Show 表示
::msgcat::mcset ja {Simple Cross} {Simple Cross}
::msgcat::mcset ja {Simple Image Access} {Simple Image Access}
::msgcat::mcset ja {Simple Plus} {Simple Plus}
::msgcat::mcset ja {Single Frame} 単一フレーム
::msgcat::mcset ja Single 単一
::msgcat::mcset ja Sites Sites
::msgcat::mcset ja Size/Radius 大きさ/半径
::msgcat::mcset ja Size 大きさ
::msgcat::mcset ja {Skip First} {Skip First}
::msgcat::mcset ja Slice Slice
::msgcat::mcset ja {Smooth Parameters} 平滑化の設定
::msgcat::mcset ja Smoothness Smoothness
::msgcat::mcset ja Smooth 平滑化
::msgcat::mcset ja {Sorry, DS9 does not support} {DS9 でサポートされていません。}
::msgcat::mcset ja {Sorry, DS9 requires a Truecolor8, Truecolor16, Truecolor24 visual be available} {Sorry, DS9 requires a Truecolor8, Truecolor16, Truecolor24 visual be available}
::msgcat::mcset ja Sort 並べ替え
::msgcat::mcset ja {Source TCL} {TCL を読み込む}
::msgcat::mcset ja Source ソース領域
::msgcat::mcset ja {Space Equal Distance} {Space Equal Distance}
::msgcat::mcset ja {Space Equal Value} {Space Equal Value}
::msgcat::mcset ja Spacing Spacing
::msgcat::mcset ja Sqrt Sqrt
::msgcat::mcset ja {Square Root} 平方根
::msgcat::mcset ja Squared 平方
::msgcat::mcset ja Square Square
::msgcat::mcset ja Starbase Starbase
::msgcat::mcset ja Startup Startup
::msgcat::mcset ja Start 開始
::msgcat::mcset ja Statistics Statistics
::msgcat::mcset ja Status 状態
::msgcat::mcset ja Step ステップ
::msgcat::mcset ja Stop 終了
::msgcat::mcset ja {Story of SAOImageDS9} {Story of SAOImageDS9}
::msgcat::mcset ja Story Story
::msgcat::mcset ja {Strip Parameters} {Strip Parameters}
::msgcat::mcset ja {Strip Scale} {Strip Scale}
::msgcat::mcset ja Strip Strip
::msgcat::mcset ja Subscriptions Subscriptions
::msgcat::mcset ja Sum 合計
::msgcat::mcset ja {Symbol Editor} 記号の編集
::msgcat::mcset ja Symbol 記号
::msgcat::mcset ja TIFF TIFF
::msgcat::mcset ja TSV TSV
::msgcat::mcset ja Tab-Separated-Value タブ分割記法
::msgcat::mcset ja Table Table
::msgcat::mcset ja Tabloid タブロイド
::msgcat::mcset ja {Tag Color} {Tag Color}
::msgcat::mcset ja {Tag New Region Group} {Tag New Region Group}
::msgcat::mcset ja Template 雛形
::msgcat::mcset ja Text 文字
::msgcat::mcset ja Theme Theme
::msgcat::mcset ja Then なら
::msgcat::mcset ja Thickness 太さ
::msgcat::mcset ja {This analysis task is already running. Do you wish to kill it?} この解析タスクはすでに実行中です。中断しますか?
::msgcat::mcset ja {This function is not available.} {This function is not available.}
::msgcat::mcset ja {This function is not currently supported for this port.} {This function is not currently supported for this port.}
::msgcat::mcset ja Tickmarks 目盛り
::msgcat::mcset ja {Tile Frames} フレームを並べる
::msgcat::mcset ja {Tile Parameters} 並べ方の設定
::msgcat::mcset ja Tile 並べて表示
::msgcat::mcset ja Times Times
::msgcat::mcset ja Titles Titles
::msgcat::mcset ja Title タイトル
::msgcat::mcset ja {Toggle Colorbar} {Toggle Colorbar}
::msgcat::mcset ja {Toggle Contour} {Toggle Contour}
::msgcat::mcset ja {Toggle Coordinate Grid} {Toggle Coordinate Grid}
::msgcat::mcset ja {Toggle Horizontal Graph} {Toggle Horizontal Graph}
::msgcat::mcset ja {Toggle Include/Exclude} {Toggle Include/Exclude}
::msgcat::mcset ja {Toggle Smooth} {Toggle Smooth}
::msgcat::mcset ja {Toggle Source/Background} {Toggle Source/Background}
::msgcat::mcset ja {Toggle Vertical Graph} {Toggle Vertical Graph}
::msgcat::mcset ja Tophat トップハット
::msgcat::mcset ja Topographic Topographic
::msgcat::mcset ja Top Top
::msgcat::mcset ja To To
::msgcat::mcset ja Transition Transition
::msgcat::mcset ja Transparency 透明
::msgcat::mcset ja Triangle Triangle
::msgcat::mcset ja Type 種類
::msgcat::mcset ja URL URL
::msgcat::mcset ja {Unable to connect directly: using Web Proxy} {Unable to connect directly: using Web Proxy}
::msgcat::mcset ja {Unable to create FOV Region, celestial WCS Required} {Unable to create FOV Region, celestial WCS Required}
::msgcat::mcset ja {Unable to determine date of observation} {Unable to determine date of observation}
::msgcat::mcset ja {Unable to evaluate filter} 絞り込み条件が評価できません。
::msgcat::mcset ja {Unable to find Footprint window} {Unable to find Footprint window}
::msgcat::mcset ja {Unable to find PRISM window} {Unable to find PRISM window}
::msgcat::mcset ja {Unable to find SIAP window} {Unable to find SIAP window}
::msgcat::mcset ja {Unable to find URL column} {Unable to find URL column}
::msgcat::mcset ja {Unable to find catalog window} カタログウィンドウが見つかりません。
::msgcat::mcset ja {Unable to find plot window} プロットウィンドウが見つかりません。
::msgcat::mcset ja {Unable to find web window} {Unable to find web window}
::msgcat::mcset ja {Unable to generate plot} {Unable to generate plot}
::msgcat::mcset ja {Unable to load FITS file} {Unable to load FITS file}
::msgcat::mcset ja {Unable to load HLS image into a non-hls frame} {Unable to load HLS image into a non-hls frame}
::msgcat::mcset ja {Unable to load HSV image into a non-hsv frame} {Unable to load HSV image into a non-hsv frame}
::msgcat::mcset ja {Unable to load RGB image into a non-rgb frame} RBGイメージを非RGBフレームに読み込めません。
::msgcat::mcset ja {Unable to load compressed region file} {Unable to load compressed region file}
::msgcat::mcset ja {Unable to load plot data} {Unable to load plot data}
::msgcat::mcset ja {Unable to load region file} 領域ファイルを読み込めません。
::msgcat::mcset ja {Unable to load} 読み込めません。
::msgcat::mcset ja {Unable to locate FOV Region} {Unable to locate FOV Region}
::msgcat::mcset ja {Unable to locate URL} URLを特定できません。
::msgcat::mcset ja {Unable to match target with XPA Mime request} {Unable to match target with XPA Mime request}
::msgcat::mcset ja {Unable to open file} ファイルを開けません。
::msgcat::mcset ja {Unable to save HLS image from a non-hls frame} {Unable to save HLS image from a non-hls frame}
::msgcat::mcset ja {Unable to save HSV image from a non-hsv frame} {Unable to save HSV image from a non-hsv frame}
::msgcat::mcset ja {Unable to save RGB image from a non-rgb frame} {Unable to save RGB image from a non-rgb frame}
::msgcat::mcset ja Undo やり直し
::msgcat::mcset ja Unique Unique
::msgcat::mcset ja Units 単位
::msgcat::mcset ja {Unknown Colormap} サポートされない配色
::msgcat::mcset ja {Unknown command} サポートされないコマンド
::msgcat::mcset ja {Update Filter} 検索条件を更新
::msgcat::mcset ja {Update Group} グループを更新
::msgcat::mcset ja {Update from Current Crosshair} 現在の十字カーソル位置から更新
::msgcat::mcset ja {Update from Current Frame} 現在のフレームから更新
::msgcat::mcset ja Update 更新
::msgcat::mcset ja {Upper Left Back} {Upper Left Back}
::msgcat::mcset ja {Upper Left Front} {Upper Left Front}
::msgcat::mcset ja {Upper Right Back} {Upper Right Back}
::msgcat::mcset ja {Upper Right Front} {Upper Right Front}
::msgcat::mcset ja {Use Authentication} 認証を使用
::msgcat::mcset ja {Use Current Frame on Download} ダウンロード時に選択中のフレームを使用
::msgcat::mcset ja {Use Internal Web Browser} 内部ブラウザを使用
::msgcat::mcset ja {Use Original Color/Width} {Use Original Color/Width}
::msgcat::mcset ja {Use Proxy} プロキシを使用
::msgcat::mcset ja {Use Theme Colors} {Use Theme Colors}
::msgcat::mcset ja {Use background color instead of theme color} {Use background color instead of theme color}
::msgcat::mcset ja {User Manual} ユーザーマニュアル
::msgcat::mcset ja Username ユーザー名
::msgcat::mcset ja User ユーザー
::msgcat::mcset ja Use 使用
::msgcat::mcset ja {VO Server} {VO Server}
::msgcat::mcset ja VOTable VOTable
::msgcat::mcset ja VOT VOT
::msgcat::mcset ja VO 仮想天文台
::msgcat::mcset ja Value 値
::msgcat::mcset ja Vector ベクトル
::msgcat::mcset ja {Vertical Graph} 縦断面
::msgcat::mcset ja {Vertical Layout} 画面の左に配置
::msgcat::mcset ja {Vertical Text} {Vertical Text}
::msgcat::mcset ja Vertical Vertical
::msgcat::mcset ja View 表示
::msgcat::mcset ja {Virtual Observatory} 仮想天文台
::msgcat::mcset ja {WCS Parameters} {WCS Parameters}
::msgcat::mcset ja WCS WCS
::msgcat::mcset ja Wavelength 波長
::msgcat::mcset ja {Web Browser} ブラウザ
::msgcat::mcset ja White 白色
::msgcat::mcset ja Width 幅
::msgcat::mcset ja Window Window
::msgcat::mcset ja {Words matching title, description} {Words matching title, description}
::msgcat::mcset ja {X Axis Title} {X Axis Title}
::msgcat::mcset ja {X Axis} {X Axis}
::msgcat::mcset ja {X Column} {X Column}
::msgcat::mcset ja {X Error Column} {X Error Column}
::msgcat::mcset ja {XPA Information} XPAの情報
::msgcat::mcset ja {XPA not initialized} {XPA が初期化されていません。}
::msgcat::mcset ja XPA XPA
::msgcat::mcset ja X X
::msgcat::mcset ja {Y Axis Title} {Y Axis Title}
::msgcat::mcset ja {Y Axis} {Y Axis}
::msgcat::mcset ja {Y Column} {Y Column}
::msgcat::mcset ja {Y Error Column} {Y Error Column}
::msgcat::mcset ja Yellow 黄色
::msgcat::mcset ja Y Y
::msgcat::mcset ja {Z Axis Scale} {Z Axis Scale}
::msgcat::mcset ja {ZScale Parameters} Zスケールの設定
::msgcat::mcset ja Zero 零
::msgcat::mcset ja {Zoom Fit} {Zoom Fit}
::msgcat::mcset ja {Zoom In} 拡大
::msgcat::mcset ja {Zoom Out} 縮小
::msgcat::mcset ja Zoom ズーム
::msgcat::mcset ja {already connected} {already connected}
::msgcat::mcset ja and and
::msgcat::mcset ja b b
::msgcat::mcset ja {found dead hub file, deleting} {found dead hub file, deleting}
::msgcat::mcset ja {found existing hub} {found existing hub}
::msgcat::mcset ja {full base} {full base}
::msgcat::mcset ja full full
::msgcat::mcset ja g g
::msgcat::mcset ja h5utils h5utils
::msgcat::mcset ja {hundredths second} {hundredths second}
::msgcat::mcset ja h h
::msgcat::mcset ja l l
::msgcat::mcset ja minutes minutes
::msgcat::mcset ja {not connected} {not connected}
::msgcat::mcset ja not not
::msgcat::mcset ja only only
::msgcat::mcset ja {or center of data} もしくはデータの中心
::msgcat::mcset ja {root base} {root base}
::msgcat::mcset ja root root
::msgcat::mcset ja {rows of data have been downloaded. More may be available. You may wish to adjust the maximum allowed} 行のデータがダウンロードされました。さらにダウンロードする場合は、最大行数を設定しなおしてください。
::msgcat::mcset ja r r
::msgcat::mcset ja s s
::msgcat::mcset ja {unable to create hub file} {unable to create hub file}
::msgcat::mcset ja {unable to locate HUB} {unable to locate HUB}
::msgcat::mcset ja {unable to open hub} {unable to open hub}
::msgcat::mcset ja {unable to open web hub} {unable to open web hub}
::msgcat::mcset ja v v
::msgcat::mcset ja x x
