::msgcat::mcset pt {2D} 
::msgcat::mcset pt {3D View} 
::msgcat::mcset pt {3D} 
::msgcat::mcset pt {A postscript generation error has occurred} {Um erro ocorreu ao gerar o postscript}
::msgcat::mcset pt {AIP} 
::msgcat::mcset pt {Abort} 
::msgcat::mcset pt {About SAOImageDS9} 
::msgcat::mcset pt {About} {Sobre}
::msgcat::mcset pt {Acknowledgment} [encoding convertfrom iso8859-1 {Créditos}]
::msgcat::mcset pt {Add Bar Graph} 
::msgcat::mcset pt {Add Graph} 
::msgcat::mcset pt {Add Line Graph} 
::msgcat::mcset pt {Add} {Adicionar}
::msgcat::mcset pt {Advanced} [encoding convertfrom iso8859-1 {Avançado}]
::msgcat::mcset pt {Align} {Alinhar}
::msgcat::mcset pt {All Columns} {Todas as colunas}
::msgcat::mcset pt {All Rows} {Todas as linhas}
::msgcat::mcset pt {All} {Tudo}
::msgcat::mcset pt {Always save files during Backup} 
::msgcat::mcset pt {Amplifier} {Aplificador}
::msgcat::mcset pt {An error has occurred during backup} 
::msgcat::mcset pt {An error has occurred during restore} 
::msgcat::mcset pt {An error has occurred invoking the Analysis task}  [encoding convertfrom iso8859-1 {Um erro ocorreu ao chamar a tarefa de Análise}]
::msgcat::mcset pt {An error has occurred while creating} 
::msgcat::mcset pt {An error has occurred while loading} 
::msgcat::mcset pt {An error has occurred while printing} {Um erro ocorreu ao imprimir}
::msgcat::mcset pt {An error has occurred while saving} {Um erro ocorreu ao salvar}
::msgcat::mcset pt {An internal error has been detected} 
::msgcat::mcset pt {Analysis Command Log} [encoding convertfrom iso8859-1 {Registro de Comandos de Análise}]
::msgcat::mcset pt {Analysis Commands} 
::msgcat::mcset pt {Analysis File} 
::msgcat::mcset pt {Analysis Log} 
::msgcat::mcset pt {Analysis} [encoding convertfrom iso8859-1 {Análise}]
::msgcat::mcset pt {Angle Complement} [encoding convertfrom iso8859-1 {Complemento do ângulo}]
::msgcat::mcset pt {Angles} [encoding convertfrom iso8859-1 {Ângulos}]
::msgcat::mcset pt {Angle} [encoding convertfrom iso8859-1 {Ângulo}]
::msgcat::mcset pt {Annuli} {Annuli}
::msgcat::mcset pt {Annulus} {Annulus}
::msgcat::mcset pt {Apply} {Aplicar}
::msgcat::mcset pt {ArcMin} 
::msgcat::mcset pt {ArcSec} 
::msgcat::mcset pt {Architecture} {Arquitetura}
::msgcat::mcset pt {Archives} 
::msgcat::mcset pt {Array} 
::msgcat::mcset pt {Arrow} {Seta}
::msgcat::mcset pt {Asteroids} 
::msgcat::mcset pt {Astronomy} 
::msgcat::mcset pt {At Startup} 
::msgcat::mcset pt {At least 2 different catalogs are required} 
::msgcat::mcset pt {Auto Centroid} 
::msgcat::mcset pt {Auto Plot 2D} 
::msgcat::mcset pt {Auto Plot 3D} 
::msgcat::mcset pt {Auto Plot Statistics} 
::msgcat::mcset pt {Auto Plot} 
::msgcat::mcset pt {Autoload FITS Regions} [encoding convertfrom iso8859-1 {Auto-carregar regiões FITS}]
::msgcat::mcset pt {Autoload} 
::msgcat::mcset pt {Automatic} [encoding convertfrom iso8859-1 {Automático}]
::msgcat::mcset pt {Average} [encoding convertfrom iso8859-1 {Média}]
::msgcat::mcset pt {Axes Number} 
::msgcat::mcset pt {Axes Order} 
::msgcat::mcset pt {Axes Range} 
::msgcat::mcset pt {Axes Title} 
::msgcat::mcset pt {Axes} {Eixos}
::msgcat::mcset pt {Axis Length} {Tamanho do eixo}
::msgcat::mcset pt {Axis Numbers} [encoding convertfrom iso8859-1 {Numeração do eixo}]
::msgcat::mcset pt {Axis Title} 
::msgcat::mcset pt {Axis} {Eixo}
::msgcat::mcset pt {Azimuth} 
::msgcat::mcset pt {Background Color} {Cor de fundo}
::msgcat::mcset pt {Background} {Fundo}
::msgcat::mcset pt {Backup} 
::msgcat::mcset pt {Back} {Anterior}
::msgcat::mcset pt {Bar Dataset} 
::msgcat::mcset pt {Bar Plot Tool} 
::msgcat::mcset pt {Bar Width} 
::msgcat::mcset pt {Bar} 
::msgcat::mcset pt {Behavior} 
::msgcat::mcset pt {Bias} 
::msgcat::mcset pt {Bin 3rd Column} {Bin terceira coluna}
::msgcat::mcset pt {Bin Center} {Centro do Bin}
::msgcat::mcset pt {Bin Columns} {Binar colunas}
::msgcat::mcset pt {Bin Filter} {Filtro do Bin}
::msgcat::mcset pt {Bin Fit} 
::msgcat::mcset pt {Bin In} 
::msgcat::mcset pt {Bin Out} 
::msgcat::mcset pt {Binning Parameters} [encoding convertfrom iso8859-1 {Parâmetros de Binning}]
::msgcat::mcset pt {Bins} 
::msgcat::mcset pt {Bin} 
::msgcat::mcset pt {Black} {Preto}
::msgcat::mcset pt {Blank/Inf/NaN Color} {Cor Preto/Inf/NaN}
::msgcat::mcset pt {Blend} 
::msgcat::mcset pt {Blink Frames} {Blinkar quadros}
::msgcat::mcset pt {Blink Interval} {Intervalo de Blink}
::msgcat::mcset pt {Blink} 
::msgcat::mcset pt {Block Fit} 
::msgcat::mcset pt {Block In} {Bin em}
::msgcat::mcset pt {Block Out} {Bin partir}
::msgcat::mcset pt {Block Parameters} 
::msgcat::mcset pt {Block Pixel} 
::msgcat::mcset pt {Block} {Bin}
::msgcat::mcset pt {Blue} {Azul}
::msgcat::mcset pt {Bold} {Negrito}
::msgcat::mcset pt {Border Color} 
::msgcat::mcset pt {Border Width} 
::msgcat::mcset pt {Border} {Borda}
::msgcat::mcset pt {Bottom} 
::msgcat::mcset pt {Box Annulus} {Annulus da Caixa}
::msgcat::mcset pt {Box Panda} {Panda Caixa}
::msgcat::mcset pt {BoxCircle} 
::msgcat::mcset pt {Boxcar} 
::msgcat::mcset pt {Box} {Caixa}
::msgcat::mcset pt {Broadcast} 
::msgcat::mcset pt {Browser} 
::msgcat::mcset pt {Browse} {Navegar}
::msgcat::mcset pt {Buffer} 
::msgcat::mcset pt {Buttonbar} 
::msgcat::mcset pt {Buttons} {Botoes}
::msgcat::mcset pt {Bytes} 
::msgcat::mcset pt {CMYK} 
::msgcat::mcset pt {Can Delete} {Pode Apagar}
::msgcat::mcset pt {Can Edit} {Pode Editar}
::msgcat::mcset pt {Can Move} {Pode Mover}
::msgcat::mcset pt {Can Rotate} {Pode Rodar}
::msgcat::mcset pt {Cancelled} 
::msgcat::mcset pt {Cancel} {Cancelar}
::msgcat::mcset pt {Cap} 
::msgcat::mcset pt {Catalog Server} [encoding convertfrom iso8859-1 {Servidor do Catálogo}]
::msgcat::mcset pt {Catalog Tool} [encoding convertfrom iso8859-1 {Ferramenta de Catálogos}]
::msgcat::mcset pt {Catalogs} [encoding convertfrom iso8859-1 {Catálogos}]
::msgcat::mcset pt {Catalog} [encoding convertfrom iso8859-1 {Catálogo}]
::msgcat::mcset pt {Catrom} 
::msgcat::mcset pt {Cat} 
::msgcat::mcset pt {Center Dialogs} 
::msgcat::mcset pt {Center Image} {Centralizar Imagem}
::msgcat::mcset pt {Center} {Centro}
::msgcat::mcset pt {Centroid Parameters} 
::msgcat::mcset pt {Centroid} 
::msgcat::mcset pt {Circle} {Circulo}
::msgcat::mcset pt {Clear All} {Limpar tudo}
::msgcat::mcset pt {Clear Analysis Commands} [encoding convertfrom iso8859-1 {Limpar Comandos de Análise}]
::msgcat::mcset pt {Clear Cache} {Limpar cache}
::msgcat::mcset pt {Clear External Analysis Commands?} {Limpar Comandos de Análise Externos?}
::msgcat::mcset pt {Clear Filter} {Limpar Filtro}
::msgcat::mcset pt {Clear Frame} {Limpar Frame}
::msgcat::mcset pt {Clear Preferences?} [encoding convertfrom iso8859-1 {Limpar preferências?}]
::msgcat::mcset pt {Clear Preferences} [encoding convertfrom iso8859-1 {Limpar preferências}]
::msgcat::mcset pt {Clear} {Limpar}
::msgcat::mcset pt {Click to Center} {Clique para centralizar}
::msgcat::mcset pt {Close} {Fechar}
::msgcat::mcset pt {Colorbar Size} 
::msgcat::mcset pt {Colorbar} {Barra de Cores}
::msgcat::mcset pt {Colormap Parameters} [encoding convertfrom iso8859-1 {Parâmetros do Mapa de Cores}]
::msgcat::mcset pt {Colormap} {Mapa de Cores}
::msgcat::mcset pt {Color} {Cor}
::msgcat::mcset pt {Columns} {Colunas}
::msgcat::mcset pt {Column} {Coluna}
::msgcat::mcset pt {Comets} 
::msgcat::mcset pt {Command not allowed} 
::msgcat::mcset pt {Command} 
::msgcat::mcset pt {Compass} {Compasso}
::msgcat::mcset pt {Composite Region} 
::msgcat::mcset pt {Composite} 
::msgcat::mcset pt {Compression} [encoding convertfrom iso8859-1 {Compressão}]
::msgcat::mcset pt {Configure} {Configurar}
::msgcat::mcset pt {Connect SAMP} 
::msgcat::mcset pt {Connect} 
::msgcat::mcset pt {Console} 
::msgcat::mcset pt {Contacting Server} 
::msgcat::mcset pt {Contour Parameters} [encoding convertfrom iso8859-1 {Parâmetros de contorno}]
::msgcat::mcset pt {Contour Paste} 
::msgcat::mcset pt {Contour Save} 
::msgcat::mcset pt {Contours} {Contornos}
::msgcat::mcset pt {Contour} 
::msgcat::mcset pt {Contrast} {Contraste}
::msgcat::mcset pt {Control Panel} 
::msgcat::mcset pt {Convert to Polygons} [encoding convertfrom iso8859-1 {Converter para polígonos}]
::msgcat::mcset pt {Coordinate Grid Parameters} [encoding convertfrom iso8859-1 {Parâmetros do Grid de Coordenadas}]
::msgcat::mcset pt {Coordinate Grid} {Grid de Coordenadas}
::msgcat::mcset pt {Coordinate System} {Sistema de Coordenadas}
::msgcat::mcset pt {Coordinates} 
::msgcat::mcset pt {Coordinate} {Coordenada}
::msgcat::mcset pt {Copy Contours} {Copiar Contornos}
::msgcat::mcset pt {Copy to Regions} [encoding convertfrom iso8859-1 {Copiar para Regiões}]
::msgcat::mcset pt {Copy} {Copiar}
::msgcat::mcset pt {Create Movie} 
::msgcat::mcset pt {Create New Frame on Download} {Criar novo Frame ao carregar}
::msgcat::mcset pt {Create} 
::msgcat::mcset pt {Crop Parameters} 
::msgcat::mcset pt {Crop} 
::msgcat::mcset pt {Crosshair Parameters} 
::msgcat::mcset pt {Crosshair To} {Cruz para}
::msgcat::mcset pt {Crosshair} {Cruz}
::msgcat::mcset pt {Cross} {Cruz}
::msgcat::mcset pt {Cubehelix} 
::msgcat::mcset pt {Cube} 
::msgcat::mcset pt {Cubic} 
::msgcat::mcset pt {Current Frame} {Frame atual}
::msgcat::mcset pt {Current Range} {Intervalo atual}
::msgcat::mcset pt {Current} {Atual}
::msgcat::mcset pt {Cursor} 
::msgcat::mcset pt {Cut} {Cortar}
::msgcat::mcset pt {Cyan} {Ciano}
::msgcat::mcset pt {DMS} 
::msgcat::mcset pt {DPI} 
::msgcat::mcset pt {DS9 has detected a newer version of a backup file and therefore will not process this file.} 
::msgcat::mcset pt {DS9 has detected a newer version of a preferences file.} 
::msgcat::mcset pt {DS9 has detected an older backup file, do you wish to continue?} 
::msgcat::mcset pt {DS9 has detected an older preferences file, do you wish to update?} [encoding convertfrom iso8859-1 {O DS9 detectou um arquivo de preferências antigo, você deseja atualizar?}]
::msgcat::mcset pt {DS9 will complete the initialization process} [encoding convertfrom iso8859-1 {O DS9 completou o processo de inicialização}]
::msgcat::mcset pt {Darken} 
::msgcat::mcset pt {Dash} [encoding convertfrom iso8859-1 {Traço}]
::msgcat::mcset pt {Data Format} {Formato de dados}
::msgcat::mcset pt {Data must be ascii numeric values} 
::msgcat::mcset pt {Dataset Name} 
::msgcat::mcset pt {Dataset} {Conjunto de dados}
::msgcat::mcset pt {Data} 
::msgcat::mcset pt {Decrease} {Diminuir}
::msgcat::mcset pt {Default All Files} 
::msgcat::mcset pt {Default Format} 
::msgcat::mcset pt {Default Length} 
::msgcat::mcset pt {Default} [encoding convertfrom iso8859-1 {Padrão}]
::msgcat::mcset pt {Degrees} {Graus}
::msgcat::mcset pt {Delay} 
::msgcat::mcset pt {Delete All Frames?} {Apagar todos Frames?}
::msgcat::mcset pt {Delete All Frames} {Apagar todos Frames}
::msgcat::mcset pt {Delete All Groups?} {Apagar todos os grupos?}
::msgcat::mcset pt {Delete All Groups} {Apagar todos os grupos}
::msgcat::mcset pt {Delete All} 
::msgcat::mcset pt {Delete Color Tags} 
::msgcat::mcset pt {Delete Dataset} 
::msgcat::mcset pt {Delete Frame} {Apague o Frame}
::msgcat::mcset pt {Delete Graph} 
::msgcat::mcset pt {Delete Group} {Apague o Grupo}
::msgcat::mcset pt {Delete Load} 
::msgcat::mcset pt {Delete Regions?} 
::msgcat::mcset pt {Delete Regions} 
::msgcat::mcset pt {Delete Selected Regions} [encoding convertfrom iso8859-1 {Apagar Regiões Selecionadas}]
::msgcat::mcset pt {Delete Select} 
::msgcat::mcset pt {Delete and Open Regions} 
::msgcat::mcset pt {Delete} {Apagar}
::msgcat::mcset pt {Depth} {Profundidade}
::msgcat::mcset pt {Detector} 
::msgcat::mcset pt {Dialog Box} {Box de dialog}
::msgcat::mcset pt {Diameter} 
::msgcat::mcset pt {Diamond} {Diamante}
::msgcat::mcset pt {Dimensions} 
::msgcat::mcset pt {Dimension} [encoding convertfrom iso8859-1 {Dimensão}]
::msgcat::mcset pt {Direction} 
::msgcat::mcset pt {Disconnect} 
::msgcat::mcset pt {Display Size} {Mostar tamanho}
::msgcat::mcset pt {Dissolve} 
::msgcat::mcset pt {Distance} 
::msgcat::mcset pt {Done} 
::msgcat::mcset pt {Download Colormap} 
::msgcat::mcset pt {Drag to Center} {Arrate para centralizar}
::msgcat::mcset pt {Duplicate Dataset} 
::msgcat::mcset pt {ENVI} 
::msgcat::mcset pt {EPS} 
::msgcat::mcset pt {East} {Leste}
::msgcat::mcset pt {Ecliptic} {Ecliptico}
::msgcat::mcset pt {Edit Group Name} {Editar nome do Grupo} 
::msgcat::mcset pt {Edit} {Editar}
::msgcat::mcset pt {Elevation} 
::msgcat::mcset pt {Ellipse Panda} 
::msgcat::mcset pt {Ellipse} {Elipse}
::msgcat::mcset pt {Elliptical Annulus} {Annulus Elipse}
::msgcat::mcset pt {Elliptical Gaussian} 
::msgcat::mcset pt {Elliptical Panda} [encoding convertfrom iso8859-1 {Panda Elíptico}]
::msgcat::mcset pt {Enable Confirmation Dialogs} {}
::msgcat::mcset pt {Enable} 
::msgcat::mcset pt {End} {Fim}
::msgcat::mcset pt {Enter Color} 
::msgcat::mcset pt {Enter Font Size} 
::msgcat::mcset pt {Enter Group Name} {Entre o nome do Grupo}
::msgcat::mcset pt {Enter Search Expression} 
::msgcat::mcset pt {Enter URL} 
::msgcat::mcset pt {Entry} 
::msgcat::mcset pt {Equal Area} [encoding convertfrom iso8859-1 {Área Igual}]
::msgcat::mcset pt {Equal Distance} [encoding convertfrom iso8859-1 {Distância Igual}]
::msgcat::mcset pt {Equal Spacing} 
::msgcat::mcset pt {Equal Value} 
::msgcat::mcset pt {Error code was returned} [encoding convertfrom iso8859-1 {Retornou código de erro}]
::msgcat::mcset pt {Errorbar} 
::msgcat::mcset pt {Error} {Erro}
::msgcat::mcset pt {Examine Frame} {Examinar Frame} 
::msgcat::mcset pt {Examine} {Examinar}
::msgcat::mcset pt {Exam} 
::msgcat::mcset pt {Exclude} {Excluir}
::msgcat::mcset pt {Exit} {Sair}
::msgcat::mcset pt {Export Array} 
::msgcat::mcset pt {Export ENVI} 
::msgcat::mcset pt {Export GIF} 
::msgcat::mcset pt {Export JPEG} 
::msgcat::mcset pt {Export NRRD} 
::msgcat::mcset pt {Export PNG} 
::msgcat::mcset pt {Export RGB Array} 
::msgcat::mcset pt {Export TIFF} 
::msgcat::mcset pt {Export} 
::msgcat::mcset pt {Extension Data} 
::msgcat::mcset pt {Extension not found} 
::msgcat::mcset pt {Extensions} 
::msgcat::mcset pt {Extension} 
::msgcat::mcset pt {Exterior Axes} {Eixos exteriores}
::msgcat::mcset pt {Exterior Numerics} [encoding convertfrom iso8859-1 {Numeração exterior}]
::msgcat::mcset pt {FAQ} 
::msgcat::mcset pt {FITS} 
::msgcat::mcset pt {FK4} 
::msgcat::mcset pt {FK5} 
::msgcat::mcset pt {FP} 
::msgcat::mcset pt {Factor} 
::msgcat::mcset pt {File not Found or Unable to load FITS data MIME type} [encoding convertfrom iso8859-1 {Arquivo não encontrado ou incapaz de carregar dados FITS do tipo MIME}]
::msgcat::mcset pt {File not found} 
::msgcat::mcset pt {Filename} {Nome de Arquivo}
::msgcat::mcset pt {File} {Arquivo}
::msgcat::mcset pt {Fill} 
::msgcat::mcset pt {Filter} {Filtro}
::msgcat::mcset pt {Find Next} [encoding convertfrom iso8859-1 {Encontrar próximo}]
::msgcat::mcset pt {Find} {Encontrado}
::msgcat::mcset pt {First Block} 
::msgcat::mcset pt {First Frame} 
::msgcat::mcset pt {First} {Primeiro}
::msgcat::mcset pt {Fits} 
::msgcat::mcset pt {Fixed in Size} {Fixa em tamanho}
::msgcat::mcset pt {Flip} 
::msgcat::mcset pt {Font} {Fonte}
::msgcat::mcset pt {Footprint Servers} 
::msgcat::mcset pt {Footprint} 
::msgcat::mcset pt {For more information, use --help} 
::msgcat::mcset pt {Foreground} 
::msgcat::mcset pt {Forground} 
::msgcat::mcset pt {Format} {Formato}
::msgcat::mcset pt {Forward} {Frente}
::msgcat::mcset pt {Found} {Encontrado}
::msgcat::mcset pt {Frame Information} [encoding convertfrom iso8859-1 {Informação do Frame}]
::msgcat::mcset pt {Frame Parameters} 
::msgcat::mcset pt {Frames} 
::msgcat::mcset pt {Frame} {Frame}
::msgcat::mcset pt {From} 
::msgcat::mcset pt {Front} {Frente}
::msgcat::mcset pt {Full Range} {Intervalo completo}
::msgcat::mcset pt {Function} [encoding convertfrom iso8859-1 {Função}]
::msgcat::mcset pt {GIF} 
::msgcat::mcset pt {GUI} 
::msgcat::mcset pt {Galactic} [encoding convertfrom iso8859-1 {Galáctico}]
::msgcat::mcset pt {Gap} 
::msgcat::mcset pt {Gaussian} {Gaussiano}
::msgcat::mcset pt {General} {Geral}
::msgcat::mcset pt {Generate} {Gerar}
::msgcat::mcset pt {Generating Regions} [encoding convertfrom iso8859-1 {Gerando regiões}]
::msgcat::mcset pt {Get Information} [encoding convertfrom iso8859-1 {Obter informações}]
::msgcat::mcset pt {Gist} 
::msgcat::mcset pt {Global Properties} 
::msgcat::mcset pt {Global} 
::msgcat::mcset pt {Goto Frame} 
::msgcat::mcset pt {Goto Row} 
::msgcat::mcset pt {Goto} 
::msgcat::mcset pt {Graph Horz} 
::msgcat::mcset pt {Graph Parameters} 
::msgcat::mcset pt {Graph Vert} 
::msgcat::mcset pt {Graphics} [encoding convertfrom iso8859-1 {Gráficos}]
::msgcat::mcset pt {Graphs} 
::msgcat::mcset pt {Graph} [encoding convertfrom iso8859-1 {Gráfico}]
::msgcat::mcset pt {Grayscale} {Tons de cinza}
::msgcat::mcset pt {Green} {Verde}
::msgcat::mcset pt {Grid Gap} 
::msgcat::mcset pt {Grid} {Grade}
::msgcat::mcset pt {Groups} {Grupos}
::msgcat::mcset pt {HMS} 
::msgcat::mcset pt {HTTP} 
::msgcat::mcset pt {Header} [encoding convertfrom iso8859-1 {Cabeçário}]
::msgcat::mcset pt {Height} {Altura}
::msgcat::mcset pt {Help Desk} {Centro de ajuda}
::msgcat::mcset pt {Help Me Choose} {Ajude-me escolher}
::msgcat::mcset pt {Help} {Ajuda}
::msgcat::mcset pt {Hide All} {Esconda tudo}
::msgcat::mcset pt {Highlite} 
::msgcat::mcset pt {High} {Alto}
::msgcat::mcset pt {Histogram Equalization} [encoding convertfrom iso8859-1 {Equalização de Histograma}]
::msgcat::mcset pt {Histogram} {Histograma}
::msgcat::mcset pt {Horizontal Graph} [encoding convertfrom iso8859-1 {Gráfico Horizontal}]
::msgcat::mcset pt {Horizontal Layout} {Layout Horizontal}
::msgcat::mcset pt {Horizontal} 
::msgcat::mcset pt {IAU Location Code} 
::msgcat::mcset pt {ICRS} 
::msgcat::mcset pt {Identification} [encoding convertfrom iso8859-1 {Identificação}]
::msgcat::mcset pt {If} {Se}
::msgcat::mcset pt {Image Servers} 
::msgcat::mcset pt {Image} {Imagem}
::msgcat::mcset pt {Import Array} 
::msgcat::mcset pt {Import ENVI} 
::msgcat::mcset pt {Import GIF} 
::msgcat::mcset pt {Import JPEG} 
::msgcat::mcset pt {Import NRRD} 
::msgcat::mcset pt {Import PNG} 
::msgcat::mcset pt {Import RGB Array} 
::msgcat::mcset pt {Import Slice GIF} 
::msgcat::mcset pt {Import Slice JPEG} 
::msgcat::mcset pt {Import Slice PNG} 
::msgcat::mcset pt {Import Slice TIFF} 
::msgcat::mcset pt {Import TIFF} 
::msgcat::mcset pt {Import} 
::msgcat::mcset pt {Include} {Incluir}
::msgcat::mcset pt {Increase} {Aumento}
::msgcat::mcset pt {Information Panel} [encoding convertfrom iso8859-1 {Painel de informação}]
::msgcat::mcset pt {Information} [encoding convertfrom iso8859-1 {Informação}]
::msgcat::mcset pt {Initialize XPA} {Inicialize XPA}
::msgcat::mcset pt {Inner} {Interno}
::msgcat::mcset pt {Instrument FOV} {FOV do instrumento}
::msgcat::mcset pt {Instrument} 
::msgcat::mcset pt {Interior Axes} {Eixos Interiores}
::msgcat::mcset pt {Interior Numerics} [encoding convertfrom iso8859-1 {Numeração Interior}]
::msgcat::mcset pt {Internal Parse Error} 
::msgcat::mcset pt {Interval} {Intervalo}
::msgcat::mcset pt {Invalid Column Name} 
::msgcat::mcset pt {Invalid WCS} 
::msgcat::mcset pt {Invalid formated multipart/mixed mime type message} [encoding convertfrom iso8859-1 {Mensagem tipo MIME multiparte/mista em formato inválido}]
::msgcat::mcset pt {Invert Colormap} {Inverter mapa de cores}
::msgcat::mcset pt {Invert Selection} [encoding convertfrom iso8859-1 {Inverter Seleção}]
::msgcat::mcset pt {Invert} {Inverter}
::msgcat::mcset pt {Italic} [encoding convertfrom iso8859-1 {Itálico}]
::msgcat::mcset pt {Items Found} [encoding convertfrom iso8859-1 {Ítens Encontrados}]
::msgcat::mcset pt {Iteration} 
::msgcat::mcset pt {JPEG Quality Factor} {Fator de qualidade JPEG}
::msgcat::mcset pt {JPEG} 
::msgcat::mcset pt {Keep-Alive} 
::msgcat::mcset pt {Keyword} 
::msgcat::mcset pt {Labels} {Legendas}
::msgcat::mcset pt {Label} {Legenda}
::msgcat::mcset pt {Landscape} {Paisagem}
::msgcat::mcset pt {Language} [encoding convertfrom iso8859-1 {Língua}]
::msgcat::mcset pt {Last Block} 
::msgcat::mcset pt {Last Frame} 
::msgcat::mcset pt {Last} [encoding convertfrom iso8859-1 {Último}]
::msgcat::mcset pt {Layout Horz} 
::msgcat::mcset pt {Layout Vert} 
::msgcat::mcset pt {Layout} 
::msgcat::mcset pt {Left} 
::msgcat::mcset pt {Legal} 
::msgcat::mcset pt {Legend Position} 
::msgcat::mcset pt {Legend Title} 
::msgcat::mcset pt {Legend} 
::msgcat::mcset pt {Length} {Comprimento}
::msgcat::mcset pt {Letter} {Carta}
::msgcat::mcset pt {Levels} [encoding convertfrom iso8859-1 {Níveis}]
::msgcat::mcset pt {Level} {Nível}
::msgcat::mcset pt {Lighten} 
::msgcat::mcset pt {Limits} {Limiter}
::msgcat::mcset pt {Line Dataset} 
::msgcat::mcset pt {Line Plot Tool} 
::msgcat::mcset pt {Linear} 
::msgcat::mcset pt {Line} {Linha}
::msgcat::mcset pt {List Data} 
::msgcat::mcset pt {List Regions} [encoding convertfrom iso8859-1 {Listar Regiões}]
::msgcat::mcset pt {List Selected Regions} 
::msgcat::mcset pt {List Select} 
::msgcat::mcset pt {List} {Listar}
::msgcat::mcset pt {Load Analysis Commands} [encoding convertfrom iso8859-1 {Ler Comandos de Análise}]
::msgcat::mcset pt {Load Color Tags} 
::msgcat::mcset pt {Load Contour Levels} [encoding convertfrom iso8859-1 {Carregar Níveis de Contorno}]
::msgcat::mcset pt {Load Contrast/Bias} {Carregar Contraste/Bias}
::msgcat::mcset pt {Load Data} {Carregar Dados}
::msgcat::mcset pt {Load Mosaic} {Carregar Mosaico}
::msgcat::mcset pt {Load Template} {Carregar Template}
::msgcat::mcset pt {Load into All} 
::msgcat::mcset pt {Load into Current} 
::msgcat::mcset pt {Loading Catalog} 
::msgcat::mcset pt {Loading} 
::msgcat::mcset pt {Load} {Carregar}
::msgcat::mcset pt {Local} 
::msgcat::mcset pt {Lock Axes} 
::msgcat::mcset pt {Lock Bin} 
::msgcat::mcset pt {Lock Color} 
::msgcat::mcset pt {Lock Crop Amplifier} 
::msgcat::mcset pt {Lock Crop Detector} 
::msgcat::mcset pt {Lock Crop Image} 
::msgcat::mcset pt {Lock Crop None} 
::msgcat::mcset pt {Lock Crop Physical} 
::msgcat::mcset pt {Lock Crop WCS} 
::msgcat::mcset pt {Lock Crosshair Amplifier} 
::msgcat::mcset pt {Lock Crosshair Detector} 
::msgcat::mcset pt {Lock Crosshair Image} 
::msgcat::mcset pt {Lock Crosshair None} 
::msgcat::mcset pt {Lock Crosshair Physical} 
::msgcat::mcset pt {Lock Crosshair WCS} 
::msgcat::mcset pt {Lock Frame Amplifier} 
::msgcat::mcset pt {Lock Frame Detector} 
::msgcat::mcset pt {Lock Frame Image} 
::msgcat::mcset pt {Lock Frame None} 
::msgcat::mcset pt {Lock Frame Physical} 
::msgcat::mcset pt {Lock Frame WCS} 
::msgcat::mcset pt {Lock Limits} 
::msgcat::mcset pt {Lock Scale} 
::msgcat::mcset pt {Lock Slice Image} 
::msgcat::mcset pt {Lock Slice None} 
::msgcat::mcset pt {Lock Slice WCS} 
::msgcat::mcset pt {Lock Smooth} 
::msgcat::mcset pt {Lock} {Travar}
::msgcat::mcset pt {Log Exponent} 
::msgcat::mcset pt {Log} 
::msgcat::mcset pt {Low High} {Baixo Alto}
::msgcat::mcset pt {Lower Left Back} 
::msgcat::mcset pt {Lower Left Front} 
::msgcat::mcset pt {Lower Right Back} 
::msgcat::mcset pt {Lower Right Front} 
::msgcat::mcset pt {Low} {Baixo}
::msgcat::mcset pt {MIP} 
::msgcat::mcset pt {Magenta} {Magenta}
::msgcat::mcset pt {Magnification} 
::msgcat::mcset pt {Magnifier} {Lente}
::msgcat::mcset pt {Major Radius} 
::msgcat::mcset pt {Major Sigma} 
::msgcat::mcset pt {Major} 
::msgcat::mcset pt {Manual} 
::msgcat::mcset pt {Mask Parameters} [encoding convertfrom iso8859-1 {Parâmetros da máscara}]
::msgcat::mcset pt {Match Axes} 
::msgcat::mcset pt {Match Bin} 
::msgcat::mcset pt {Match Catalog requires at least 1 row per catalog} 
::msgcat::mcset pt {Match Color} 
::msgcat::mcset pt {Match Crop Amplifier} 
::msgcat::mcset pt {Match Crop Detector} 
::msgcat::mcset pt {Match Crop Image} 
::msgcat::mcset pt {Match Crop Physical} 
::msgcat::mcset pt {Match Crop WCS} 
::msgcat::mcset pt {Match Crosshair Amplifier} 
::msgcat::mcset pt {Match Crosshair Detector} 
::msgcat::mcset pt {Match Crosshair Image} 
::msgcat::mcset pt {Match Crosshair Physical} 
::msgcat::mcset pt {Match Crosshair WCS} 
::msgcat::mcset pt {Match Frame Amplifier} 
::msgcat::mcset pt {Match Frame Detector} 
::msgcat::mcset pt {Match Frame Image} 
::msgcat::mcset pt {Match Frame Physical} 
::msgcat::mcset pt {Match Frame WCS} 
::msgcat::mcset pt {Match Limits} 
::msgcat::mcset pt {Match Scale} 
::msgcat::mcset pt {Match Slice Image} 
::msgcat::mcset pt {Match Slice WCS} 
::msgcat::mcset pt {Match Smooth} 
::msgcat::mcset pt {Match} 
::msgcat::mcset pt {Math Function} [encoding convertfrom iso8859-1 {Função Matemática}]
::msgcat::mcset pt {Matplotlib} 
::msgcat::mcset pt {Max Rows} [encoding convertfrom iso8859-1 {Máximas linhas}]
::msgcat::mcset pt {Maximum} 
::msgcat::mcset pt {Max} [encoding convertfrom iso8859-1 {Máximo}]
::msgcat::mcset pt {Menus and Buttons} 
::msgcat::mcset pt {Menu} 
::msgcat::mcset pt {Message Log} 
::msgcat::mcset pt {Method} [encoding convertfrom iso8859-1 {Método}]
::msgcat::mcset pt {Min Max Parameters} 
::msgcat::mcset pt {Min Max} [encoding convertfrom iso8859-1 {Min Máx}]
::msgcat::mcset pt {Minimum} 
::msgcat::mcset pt {Minor Radius} 
::msgcat::mcset pt {Minor Sigma} 
::msgcat::mcset pt {Minor} {Menor}
::msgcat::mcset pt {Minutes} 
::msgcat::mcset pt {Min} 
::msgcat::mcset pt {Mission} [encoding convertfrom iso8859-1 {Missão}]
::msgcat::mcset pt {Mode} 
::msgcat::mcset pt {Mosaic IRAF Segment} 
::msgcat::mcset pt {Mosaic IRAF} 
::msgcat::mcset pt {Mosaic WCS Segment} 
::msgcat::mcset pt {Mosaic WCS} 
::msgcat::mcset pt {Mosaic WFPC2} 
::msgcat::mcset pt {Mosaic} 
::msgcat::mcset pt {Mouse Click Epsilon} 
::msgcat::mcset pt {Mouse Wheel Bin} 
::msgcat::mcset pt {Mouse Wheel Zoom} 
::msgcat::mcset pt {Move Back} 
::msgcat::mcset pt {Move First} 
::msgcat::mcset pt {Move Forward} 
::msgcat::mcset pt {Move Frame} 
::msgcat::mcset pt {Move Last} 
::msgcat::mcset pt {Move to Back} [encoding convertfrom iso8859-1 {Move para trás}]
::msgcat::mcset pt {Move to Front} {Mover para frente}
::msgcat::mcset pt {Movie} 
::msgcat::mcset pt {Muliple Extension Cube} 
::msgcat::mcset pt {Muliple Extension Frames} 
::msgcat::mcset pt {Multiple Extension Cube} 
::msgcat::mcset pt {Multiple Extension Frames} 
::msgcat::mcset pt {Multiple WCS} {Multiplos WCS}
::msgcat::mcset pt {NAN} 
::msgcat::mcset pt {NRRD} 
::msgcat::mcset pt {Name Resolution} {Resolver o Nome}
::msgcat::mcset pt {Name Server} {Servidor de Nomes}
::msgcat::mcset pt {Name or Designation} [encoding convertfrom iso8859-1 {Nome ou designação}]
::msgcat::mcset pt {Name} 
::msgcat::mcset pt {Native Dialog} {Dialog Nativo}
::msgcat::mcset pt {New Features} {Novo}
::msgcat::mcset pt {New Frame 3D} 
::msgcat::mcset pt {New Frame RGB} {Novo Frame RGB}
::msgcat::mcset pt {New Frame each Time} 
::msgcat::mcset pt {New Frame} {Novo frame}
::msgcat::mcset pt {New Graph} 
::msgcat::mcset pt {New Group} {Novo grupo}
::msgcat::mcset pt {New Plot} 
::msgcat::mcset pt {New} {Novo}
::msgcat::mcset pt {Next Block} 
::msgcat::mcset pt {Next Frame} 
::msgcat::mcset pt {Next} [encoding convertfrom iso8859-1 {Próximo}]
::msgcat::mcset pt {No Catalog specified} [encoding convertfrom iso8859-1 {Nenhum catálogo especificado}]
::msgcat::mcset pt {No Data Available} 
::msgcat::mcset pt {No Items Found} [encoding convertfrom iso8859-1 {Nenhum ítem encontrado}]
::msgcat::mcset pt {Non-NAN} 
::msgcat::mcset pt {Non-Zero} 
::msgcat::mcset pt {None} {Nenhum}
::msgcat::mcset pt {Normal} 
::msgcat::mcset pt {North} {Norte}
::msgcat::mcset pt {Not Found} 
::msgcat::mcset pt {Not Supported} 
::msgcat::mcset pt {Not valid export format} 
::msgcat::mcset pt {Notes} 
::msgcat::mcset pt {Number of Samples} 
::msgcat::mcset pt {Number of Threads} 
::msgcat::mcset pt {Number of Ticks} 
::msgcat::mcset pt {Number} [encoding convertfrom iso8859-1 {Número}]
::msgcat::mcset pt {Numerics} 
::msgcat::mcset pt {OK} 
::msgcat::mcset pt {Object} {Objeto}
::msgcat::mcset pt {ObsId} 
::msgcat::mcset pt {Open File} {Abrir Arquivo}
::msgcat::mcset pt {Open ME Cube} 
::msgcat::mcset pt {Open ME Frames} 
::msgcat::mcset pt {Open Mosaic IRAF Seg} 
::msgcat::mcset pt {Open Mosaic IRAF} 
::msgcat::mcset pt {Open Mosaic WCS Seg} 
::msgcat::mcset pt {Open Mosaic WCS} 
::msgcat::mcset pt {Open Mosaic WFPC2} 
::msgcat::mcset pt {Open RGB Cube} 
::msgcat::mcset pt {Open RGB Image} 
::msgcat::mcset pt {Open Regions} 
::msgcat::mcset pt {Open Slice} 
::msgcat::mcset pt {Open TCL Console} 
::msgcat::mcset pt {Open URL} {Abrir URL}
::msgcat::mcset pt {Open as} 
::msgcat::mcset pt {Open} {Abrir}
::msgcat::mcset pt {Operator} {Operador}
::msgcat::mcset pt {Orientation} [encoding convertfrom iso8859-1 {Orientação}]
::msgcat::mcset pt {Origin} 
::msgcat::mcset pt {Oscillate} 
::msgcat::mcset pt {Other Color} 
::msgcat::mcset pt {Other Font Size} 
::msgcat::mcset pt {Other} {Outro}
::msgcat::mcset pt {Outer} {Fora}
::msgcat::mcset pt {Overplot} 
::msgcat::mcset pt {Override Color} 
::msgcat::mcset pt {PNG} 
::msgcat::mcset pt {PS Page Setup} 
::msgcat::mcset pt {PS Print} 
::msgcat::mcset pt {Page Setup} [encoding convertfrom iso8859-1 {Configuracoes de página}]
::msgcat::mcset pt {Page Source} [encoding convertfrom iso8859-1 {Fonte da página}]
::msgcat::mcset pt {Pan To} 
::msgcat::mcset pt {Pan Zoom Rotate Parameters} 
::msgcat::mcset pt {Pan Zoom} 
::msgcat::mcset pt {Pan then Zoom} 
::msgcat::mcset pt {Panda} {Panda}
::msgcat::mcset pt {Panner} 
::msgcat::mcset pt {Pan} 
::msgcat::mcset pt {Parameters} [encoding convertfrom iso8859-1 {Parâmetros}]
::msgcat::mcset pt {Password} {Senha}
::msgcat::mcset pt {Paste Contours} {Colar Contornos}
::msgcat::mcset pt {Paste} {Colar}
::msgcat::mcset pt {Physical} [encoding convertfrom iso8859-1 {Físico}]
::msgcat::mcset pt {Pixel Distribution} [encoding convertfrom iso8859-1 {Distribuição de Pixels}]
::msgcat::mcset pt {Pixel Size} {Tamanho do Pixel}
::msgcat::mcset pt {Pixel Table} {Tabela de Pixels}
::msgcat::mcset pt {Pixels} 
::msgcat::mcset pt {Planets} 
::msgcat::mcset pt {Play} {Execute}
::msgcat::mcset pt {Please Select a Region} 
::msgcat::mcset pt {Please change the file's permission to disable other users write access. Use anyway?} 
::msgcat::mcset pt {Please specify instruments} 
::msgcat::mcset pt {Please specify radius and either name or (ra,dec)} 
::msgcat::mcset pt {Please specify width, height, and either name or (ra,dec)} 
::msgcat::mcset pt {Plot 2D} 
::msgcat::mcset pt {Plot 3D} 
::msgcat::mcset pt {Plot Area} 
::msgcat::mcset pt {Plot Control Panel} 
::msgcat::mcset pt {Plot Tool} 
::msgcat::mcset pt {Plotting Regions} 
::msgcat::mcset pt {Plot} 
::msgcat::mcset pt {Plus} {Mais}
::msgcat::mcset pt {Pointer} {Ponteiro}
::msgcat::mcset pt {Points} {Pntos}
::msgcat::mcset pt {Point} {Ponto}
::msgcat::mcset pt {Polygon} [encoding convertfrom iso8859-1 {Polígono}]
::msgcat::mcset pt {Portrait} {Retrato}
::msgcat::mcset pt {Position} 
::msgcat::mcset pt {Poster} 
::msgcat::mcset pt {Postscript} 
::msgcat::mcset pt {Power} [encoding convertfrom iso8859-1 {Potência}]
::msgcat::mcset pt {Precision} 
::msgcat::mcset pt {Preferences} [encoding convertfrom iso8859-1 {Preferências}]
::msgcat::mcset pt {Preserve During Load} {Preservar durante a carga}
::msgcat::mcset pt {Previous Block} 
::msgcat::mcset pt {Previous Frame} 
::msgcat::mcset pt {Previous} {Anterior}
::msgcat::mcset pt {Prev} 
::msgcat::mcset pt {Print Coordinates} {Imprimir Coordenadas}
::msgcat::mcset pt {Print To} {Imprimir Para}
::msgcat::mcset pt {Printer} {Impressora}
::msgcat::mcset pt {Print} {Imprimir}
::msgcat::mcset pt {Prism Goto} 
::msgcat::mcset pt {Prism} 
::msgcat::mcset pt {Projection} [encoding convertfrom iso8859-1 {Projeção}]
::msgcat::mcset pt {Properties} {Propriedades}
::msgcat::mcset pt {Property} {Propriedade}
::msgcat::mcset pt {Proxy Host} {Host Proxy}
::msgcat::mcset pt {Proxy Port} {Porta do Proxy}
::msgcat::mcset pt {Publication} [encoding convertfrom iso8859-1 {Publicação}]
::msgcat::mcset pt {Quadratic} [encoding convertfrom iso8859-1 {Quadrático}]
::msgcat::mcset pt {RDB} 
::msgcat::mcset pt {RGB Array} 
::msgcat::mcset pt {RGB Cube} 
::msgcat::mcset pt {RGB Image} 
::msgcat::mcset pt {RGB} 
::msgcat::mcset pt {Radial Profile} 
::msgcat::mcset pt {Radius} {Raio}
::msgcat::mcset pt {Range} 
::msgcat::mcset pt {Redo} {Refazer}
::msgcat::mcset pt {Red} {Vermelho}
::msgcat::mcset pt {Reference Manual} [encoding convertfrom iso8859-1 {Manual de referência}]
::msgcat::mcset pt {Reference} [encoding convertfrom iso8859-1 {Referência}]
::msgcat::mcset pt {Refresh Frame} {Recarregar Frame}
::msgcat::mcset pt {Refresh} 
::msgcat::mcset pt {Region Parameters} 
::msgcat::mcset pt {Region} [encoding convertfrom iso8859-1 {Região}]
::msgcat::mcset pt {Release Notes} [encoding convertfrom iso8859-1 {Notas das Versão}]
::msgcat::mcset pt {Release} [encoding convertfrom iso8859-1 {Versão}]
::msgcat::mcset pt {Reload} {Recarregar}
::msgcat::mcset pt {Render} 
::msgcat::mcset pt {Repeat} 
::msgcat::mcset pt {Reset Colormap} {Reiniciar mapa de cores}
::msgcat::mcset pt {Reset Frame} {Reiniciar Frame}
::msgcat::mcset pt {Reset} 
::msgcat::mcset pt {Restore} 
::msgcat::mcset pt {Retrieve} {Receber}
::msgcat::mcset pt {Return} 
::msgcat::mcset pt {Right} 
::msgcat::mcset pt {Roman} 
::msgcat::mcset pt {Rotate} {Rodar}
::msgcat::mcset pt {Rows} {Linhas}
::msgcat::mcset pt {Row} 
::msgcat::mcset pt {Ruler} [encoding convertfrom iso8859-1 {Régua}]
::msgcat::mcset pt {SAMP Image} 
::msgcat::mcset pt {SAMP Table} 
::msgcat::mcset pt {SAMP: not connected} 
::msgcat::mcset pt {SAMP} 
::msgcat::mcset pt {Sample Increment} 
::msgcat::mcset pt {Sample Parameters} 
::msgcat::mcset pt {Samples per Line} {Amostras por Linha}
::msgcat::mcset pt {Sample} 
::msgcat::mcset pt {Save 3D Movie} 
::msgcat::mcset pt {Save Color Tags} 
::msgcat::mcset pt {Save Contour Levels} {Salvar Níveis de Contorno}
::msgcat::mcset pt {Save Contrast/Bias} {Salvar Contraste/Bias}
::msgcat::mcset pt {Save Data} {Salvar Dados}
::msgcat::mcset pt {Save Image EPS} 
::msgcat::mcset pt {Save Image FITS} 
::msgcat::mcset pt {Save Image GIF} 
::msgcat::mcset pt {Save Image JPEG} 
::msgcat::mcset pt {Save Image PNG} 
::msgcat::mcset pt {Save Image TIFF} 
::msgcat::mcset pt {Save Image on Download} 
::msgcat::mcset pt {Save Image} {Salvar Imagem}
::msgcat::mcset pt {Save ME Cube} 
::msgcat::mcset pt {Save Mosaic WCS Seg} 
::msgcat::mcset pt {Save Mosaic WCS} 
::msgcat::mcset pt {Save RGB Cube} 
::msgcat::mcset pt {Save RGB Image} 
::msgcat::mcset pt {Save Regions} [encoding convertfrom iso8859-1 {Salvar Regiões}]
::msgcat::mcset pt {Save Selected Regions} 
::msgcat::mcset pt {Save Select} 
::msgcat::mcset pt {Save Slice} 
::msgcat::mcset pt {Save Template} 
::msgcat::mcset pt {Save as} 
::msgcat::mcset pt {Save} {Salvar}
::msgcat::mcset pt {Scale Parameters} [encoding convertfrom iso8859-1 {Parâmetros da Escala}]
::msgcat::mcset pt {Scale and Limits} 
::msgcat::mcset pt {Scale} {Escala}
::msgcat::mcset pt {Scan} 
::msgcat::mcset pt {Scatter Dataset} 
::msgcat::mcset pt {Scatter Plot Tool} 
::msgcat::mcset pt {Scope} {Escopo}
::msgcat::mcset pt {Screen} 
::msgcat::mcset pt {Search for Catalogs} [encoding convertfrom iso8859-1 {Buscar Catálogos}]
::msgcat::mcset pt {Seconds} {Segundos}
::msgcat::mcset pt {Segment} 
::msgcat::mcset pt {Select All} {Selecionar tudo}
::msgcat::mcset pt {Select Coordinate System } {Selecionar Sistema de Coordenadas}
::msgcat::mcset pt {Select Dataset} 
::msgcat::mcset pt {Select Datatset} 
::msgcat::mcset pt {Select Graph} 
::msgcat::mcset pt {Select None} {Selecionar Nada}
::msgcat::mcset pt {Send} 
::msgcat::mcset pt {Server} {Servidor}
::msgcat::mcset pt {Sexagesimal} 
::msgcat::mcset pt {Shadow} 
::msgcat::mcset pt {Shape} {Formato}
::msgcat::mcset pt {Show All} {Mostre todos}
::msgcat::mcset pt {Show Command} 
::msgcat::mcset pt {Show Compass} 
::msgcat::mcset pt {Show Grid} 
::msgcat::mcset pt {Show Legend} 
::msgcat::mcset pt {Show Text} 
::msgcat::mcset pt {Show/Hide Frames} {Mostra/Esconde Frames}
::msgcat::mcset pt {Show} {Mostrar}
::msgcat::mcset pt {Simple Cross} 
::msgcat::mcset pt {Simple Image Access} 
::msgcat::mcset pt {Simple Plus} 
::msgcat::mcset pt {Single Frame} [encoding convertfrom iso8859-1 {Frame Único}]
::msgcat::mcset pt {Single} [encoding convertfrom iso8859-1 {Único}]
::msgcat::mcset pt {Sites} 
::msgcat::mcset pt {Size/Radius} {Tamanho/Raio}
::msgcat::mcset pt {Size} {Tamanho}
::msgcat::mcset pt {Skip First} {Pular Primeiro}
::msgcat::mcset pt {Slice} 
::msgcat::mcset pt {Smooth Parameters} [encoding convertfrom iso8859-1 {Parâmetros da Suavização}]
::msgcat::mcset pt {Smoothness} 
::msgcat::mcset pt {Smooth} {Suavizar}
::msgcat::mcset pt {Sorry, DS9 does not support} [encoding convertfrom iso8859-1 {Perdão, o DS9 não suporta}]
::msgcat::mcset pt {Sorry, DS9 requires a Truecolor8, Truecolor16, Truecolor24 visual be available} 
::msgcat::mcset pt {Sort} {Organizar}
::msgcat::mcset pt {Source TCL} [encoding convertfrom iso8859-1 {Código TCL}]
::msgcat::mcset pt {Source} {Fonte}
::msgcat::mcset pt {Space Equal Distance} 
::msgcat::mcset pt {Space Equal Value} 
::msgcat::mcset pt {Spacing} [encoding convertfrom iso8859-1 {Espaçamento}]
::msgcat::mcset pt {Sqrt} 
::msgcat::mcset pt {Square Root} {Raiz Quadrada}
::msgcat::mcset pt {Squared} {Quadrado}
::msgcat::mcset pt {Square} 
::msgcat::mcset pt {Starbase} 
::msgcat::mcset pt {Startup} 
::msgcat::mcset pt {Start} {Iniciar}
::msgcat::mcset pt {Statistics} 
::msgcat::mcset pt {Status} {Estado}
::msgcat::mcset pt {Step} {Passo}
::msgcat::mcset pt {Stop} {Parar}
::msgcat::mcset pt {Story of SAOImageDS9} 
::msgcat::mcset pt {Story} 
::msgcat::mcset pt {Strip Parameters} 
::msgcat::mcset pt {Strip Scale} 
::msgcat::mcset pt {Strip} 
::msgcat::mcset pt {Sum} {Soma}
::msgcat::mcset pt {Symbol Editor} 
::msgcat::mcset pt {Symbol} [encoding convertfrom iso8859-1 {Símbolo}]
::msgcat::mcset pt {TIFF} 
::msgcat::mcset pt {TSV} 
::msgcat::mcset pt {Tab-Separated-Value} 
::msgcat::mcset pt {Table} 
::msgcat::mcset pt {Tabloid} [encoding convertfrom iso8859-1 {Tablóide}]
::msgcat::mcset pt {Tag Color} 
::msgcat::mcset pt {Template} 
::msgcat::mcset pt {Text} {Texto}
::msgcat::mcset pt {Theme} 
::msgcat::mcset pt {Then} [encoding convertfrom iso8859-1 {Então}]
::msgcat::mcset pt {Thickness} {Expessura}
::msgcat::mcset pt {This analysis task is already running. Do you wish to kill it?} [encoding convertfrom iso8859-1 {Esta análise já está sendo executada. Você deseja parar?}]
::msgcat::mcset pt {This function is not available.} 
::msgcat::mcset pt {This function is not currently supported for this port.} 
::msgcat::mcset pt {Tickmarks} 
::msgcat::mcset pt {Tile Frames} 
::msgcat::mcset pt {Tile Parameters} 
::msgcat::mcset pt {Tile} 
::msgcat::mcset pt {Times} 
::msgcat::mcset pt {Titles} 
::msgcat::mcset pt {Title} [encoding convertfrom iso8859-1 {Título}]
::msgcat::mcset pt {Tophat} 
::msgcat::mcset pt {Topographic} 
::msgcat::mcset pt {Top} 
::msgcat::mcset pt {To} {Para}
::msgcat::mcset pt {Transparency} 
::msgcat::mcset pt {Triangle} 
::msgcat::mcset pt {Type} {Tipo}
::msgcat::mcset pt {URL} 
::msgcat::mcset pt {Unable to connect directly: using Web Proxy} 
::msgcat::mcset pt {Unable to create FOV Region, celestial WCS Required} 
::msgcat::mcset pt {Unable to determine date of observation} 
::msgcat::mcset pt {Unable to evaluate filter} {Incapaz de calcular filtro}
::msgcat::mcset pt {Unable to find Footprint window} 
::msgcat::mcset pt {Unable to find PRISM window} 
::msgcat::mcset pt {Unable to find SIAP window} 
::msgcat::mcset pt {Unable to find URL column} 
::msgcat::mcset pt {Unable to find catalog window} [encoding convertfrom iso8859-1 {Incapaz de encontrar janela do catálogo}]
::msgcat::mcset pt {Unable to find plot window} [encoding convertfrom iso8859-1 {Incapaz de encontrar janela de gráfico}]
::msgcat::mcset pt {Unable to find web window} 
::msgcat::mcset pt {Unable to generate plot} 
::msgcat::mcset pt {Unable to load RGB image into a non-rgb frame} [encoding convertfrom iso8859-1 {Incapaz de carregar imagem RGB em um frame não RGB}]
::msgcat::mcset pt {Unable to load compressed region file} 
::msgcat::mcset pt {Unable to load plot data} 
::msgcat::mcset pt {Unable to load region file} 
::msgcat::mcset pt {Unable to load} {Incapaz de carregar}
::msgcat::mcset pt {Unable to locate FOV Region} 
::msgcat::mcset pt {Unable to locate URL} {Incapaz de localizar URL}
::msgcat::mcset pt {Unable to match target with XPA Mime request} 
::msgcat::mcset pt {Unable to open file} {Incapaz de abrir arquivo}
::msgcat::mcset pt {Unable to save RGB image from a non-rgb frame} 
::msgcat::mcset pt {Undo} {Voltar}
::msgcat::mcset pt {Unique} 
::msgcat::mcset pt {Unists} 
::msgcat::mcset pt {Units} {Unidades}
::msgcat::mcset pt {Unknown Colormap} 
::msgcat::mcset pt {Unknown command} 
::msgcat::mcset pt {Update Filter} 
::msgcat::mcset pt {Update Group} {Atualizar Grupo}
::msgcat::mcset pt {Update from Current Crosshair} {Atualizar da Cruz Atual}
::msgcat::mcset pt {Update from Current Frame} {Atualizar do Frame Atual}
::msgcat::mcset pt {Update} {Atualizar}
::msgcat::mcset pt {Upper Left Back} 
::msgcat::mcset pt {Upper Left Front} 
::msgcat::mcset pt {Upper Right Back} 
::msgcat::mcset pt {Upper Right Front} 
::msgcat::mcset pt {Use Authentication} [encoding convertfrom iso8859-1 {Utilizar Autenticação}]
::msgcat::mcset pt {Use Current Frame on Download} {Utilizar Frame Atual ao Descarregar}
::msgcat::mcset pt {Use Internal Web Browser} {Utilizar Navegador Web Interno}
::msgcat::mcset pt {Use Original Color/Width} 
::msgcat::mcset pt {Use Proxy} {Utilizar Proxy}
::msgcat::mcset pt {Use Theme Colors} 
::msgcat::mcset pt {Use background color instead of theme color} 
::msgcat::mcset pt {User Manual} 
::msgcat::mcset pt {Username} [encoding convertfrom iso8859-1 {Nome de usuário}]
::msgcat::mcset pt {User} [encoding convertfrom iso8859-1 {Usuário}]
::msgcat::mcset pt {Use} {Usar}
::msgcat::mcset pt {VO Server} 
::msgcat::mcset pt {VOTable} 
::msgcat::mcset pt {VOT} 
::msgcat::mcset pt {VO} 
::msgcat::mcset pt {Value} {Valor} 
::msgcat::mcset pt {Vector} {Vetor}
::msgcat::mcset pt {Vertical Graph} [encoding convertfrom iso8859-1 {Gráfico Vertical}]
::msgcat::mcset pt {Vertical Layout} {Layout Vertical}
::msgcat::mcset pt {Vertical Text} {Texto Vertical}
::msgcat::mcset pt {Vertical} 
::msgcat::mcset pt {View} {Visualizar}
::msgcat::mcset pt {Virtual Observatory} [encoding convertfrom iso8859-1 {Observatório Virtual}]
::msgcat::mcset pt {WCS Parameters} 
::msgcat::mcset pt {WCS} 
::msgcat::mcset pt {Wavelength} {Comprimento de Onda}
::msgcat::mcset pt {Web Browser} {Navegador Web}
::msgcat::mcset pt {White} {Branco}
::msgcat::mcset pt {Width} {Largura}
::msgcat::mcset pt {Window} 
::msgcat::mcset pt {Words matching title, description} 
::msgcat::mcset pt {X Axis Title} 
::msgcat::mcset pt {X Axis} 
::msgcat::mcset pt {X Column} 
::msgcat::mcset pt {X Error Column} 
::msgcat::mcset pt {XPA Information} [encoding convertfrom iso8859-1 {Informação sobre o XPA}]
::msgcat::mcset pt {XPA not initialized} [encoding convertfrom iso8859-1 {XPA não inicializado}]
::msgcat::mcset pt {XPA} 
::msgcat::mcset pt {X} 
::msgcat::mcset pt {Y Axis Title} 
::msgcat::mcset pt {Y Axis} 
::msgcat::mcset pt {Y Column} 
::msgcat::mcset pt {Y Error Column} 
::msgcat::mcset pt {Yellow} {Amarelo}
::msgcat::mcset pt {Y} 
::msgcat::mcset pt {Z Axis Scale} 
::msgcat::mcset pt {ZScale Parameters} [encoding convertfrom iso8859-1 {Parâmetros da escala Z}]
::msgcat::mcset pt {Zero} 
::msgcat::mcset pt {Zoom Fit} 
::msgcat::mcset pt {Zoom In} {Aumentar}
::msgcat::mcset pt {Zoom Out} {Diminuir}
::msgcat::mcset pt {Zoom} {Fator}
::msgcat::mcset pt {already connected} 
::msgcat::mcset pt {and} 
::msgcat::mcset pt {b} 
::msgcat::mcset pt {g} 
::msgcat::mcset pt {h5utils} 
::msgcat::mcset pt {hundredths second} 
::msgcat::mcset pt {internal error} 
::msgcat::mcset pt {not connected} 
::msgcat::mcset pt {not} 
::msgcat::mcset pt {only} 
::msgcat::mcset pt {or center of data} {ou centro dos dados}
::msgcat::mcset pt {rows of data have been downloaded. More may be available. You may wish to adjust the maximum allowed} [encoding convertfrom iso8859-1 {colunas de dados foram descarregadas. Mais podem estar disponíveis. Você pode querer ajustar o máximo permitido}]
::msgcat::mcset pt {r} 
::msgcat::mcset pt {unable to locate HUB} 
::msgcat::mcset pt {x} 
