::msgcat::mcset zh {2D} 
::msgcat::mcset zh {3D View} 
::msgcat::mcset zh {3D} 
::msgcat::mcset zh {A postscript generation error has occurred} 
::msgcat::mcset zh {AIP} 
::msgcat::mcset zh {Abort} 
::msgcat::mcset zh {About SAOImageDS9} 
::msgcat::mcset zh {About} [encoding convertfrom big5 "\xC3\xF6 \xA9\xF3"]
::msgcat::mcset zh {Acknowledgment} 
::msgcat::mcset zh {Add Bar Graph} 
::msgcat::mcset zh {Add Graph} 
::msgcat::mcset zh {Add Line Graph} 
::msgcat::mcset zh {Add} 
::msgcat::mcset zh {Advanced} 
::msgcat::mcset zh {Align} [encoding convertfrom big5 "\xB9\xEF \xBB\xF4 \xA4\xE8 \xA6\xEC"]
::msgcat::mcset zh {All Columns} 
::msgcat::mcset zh {All Rows} 
::msgcat::mcset zh {All} 
::msgcat::mcset zh {Always save files during Backup} 
::msgcat::mcset zh {Amplifier} 
::msgcat::mcset zh {An error has occurred during backup} 
::msgcat::mcset zh {An error has occurred during restore} 
::msgcat::mcset zh {An error has occurred invoking the Analysis task} 
::msgcat::mcset zh {An error has occurred while creating} 
::msgcat::mcset zh {An error has occurred while loading} 
::msgcat::mcset zh {An error has occurred while printing} 
::msgcat::mcset zh {An error has occurred while saving} 
::msgcat::mcset zh {An internal error has been detected} 
::msgcat::mcset zh {Analysis Command Log} 
::msgcat::mcset zh {Analysis Commands} 
::msgcat::mcset zh {Analysis File} 
::msgcat::mcset zh {Analysis Log} 
::msgcat::mcset zh {Analysis} [encoding convertfrom big5 "\xA4\xC0 \xAA\x52"]
::msgcat::mcset zh {Angle Complement} 
::msgcat::mcset zh {Angles} 
::msgcat::mcset zh {Angle} 
::msgcat::mcset zh {Annuli} 
::msgcat::mcset zh {Annulus} [encoding convertfrom big5 "\xB6\xEA \xB0\xE9"]
::msgcat::mcset zh {Apply} 
::msgcat::mcset zh {ArcMin} 
::msgcat::mcset zh {ArcSec} 
::msgcat::mcset zh {Architecture} 
::msgcat::mcset zh {Archives} 
::msgcat::mcset zh {Array} 
::msgcat::mcset zh {Arrow} 
::msgcat::mcset zh {Asteroids} 
::msgcat::mcset zh {Astronomy} 
::msgcat::mcset zh {At Startup} 
::msgcat::mcset zh {At least 2 different catalogs are required} 
::msgcat::mcset zh {Auto Centroid} 
::msgcat::mcset zh {Auto Plot 2D} 
::msgcat::mcset zh {Auto Plot 3D} 
::msgcat::mcset zh {Auto Plot Statistics} 
::msgcat::mcset zh {Auto Plot} 
::msgcat::mcset zh {Autoload FITS Regions} 
::msgcat::mcset zh {Autoload} 
::msgcat::mcset zh {Automatic} 
::msgcat::mcset zh {Average} 
::msgcat::mcset zh {Axes Number} 
::msgcat::mcset zh {Axes Order} 
::msgcat::mcset zh {Axes Range} 
::msgcat::mcset zh {Axes Title} 
::msgcat::mcset zh {Axes} 
::msgcat::mcset zh {Axis Length} 
::msgcat::mcset zh {Axis Numbers} 
::msgcat::mcset zh {Axis Title} 
::msgcat::mcset zh {Axis} 
::msgcat::mcset zh {Azimuth} 
::msgcat::mcset zh {Background Color} 
::msgcat::mcset zh {Background} 
::msgcat::mcset zh {Backup} 
::msgcat::mcset zh {Back} 
::msgcat::mcset zh {Bar Dataset} 
::msgcat::mcset zh {Bar Plot Tool} 
::msgcat::mcset zh {Bar Width} 
::msgcat::mcset zh {Bar} 
::msgcat::mcset zh {Behavior} 
::msgcat::mcset zh {Bias} 
::msgcat::mcset zh {Bin 3rd Column} 
::msgcat::mcset zh {Bin Center} 
::msgcat::mcset zh {Bin Columns} 
::msgcat::mcset zh {Bin Filter} 
::msgcat::mcset zh {Bin Fit} 
::msgcat::mcset zh {Bin In} 
::msgcat::mcset zh {Bin Out} 
::msgcat::mcset zh {Binning Parameters} 
::msgcat::mcset zh {Bins} 
::msgcat::mcset zh {Bin} 
::msgcat::mcset zh {Black} [encoding convertfrom big5 "\xB6\xC2 \xA6\xE2"]
::msgcat::mcset zh {Blank/Inf/NaN Color} 
::msgcat::mcset zh {Blend} 
::msgcat::mcset zh {Blink Frames} 
::msgcat::mcset zh {Blink Interval} 
::msgcat::mcset zh {Blink} 
::msgcat::mcset zh {Block Fit} 
::msgcat::mcset zh {Block In} 
::msgcat::mcset zh {Block Out} 
::msgcat::mcset zh {Block Parameters} 
::msgcat::mcset zh {Block Pixel} 
::msgcat::mcset zh {Block} 
::msgcat::mcset zh {Blue} 
::msgcat::mcset zh {Bold} 
::msgcat::mcset zh {Border Color} 
::msgcat::mcset zh {Border Width} 
::msgcat::mcset zh {Border} 
::msgcat::mcset zh {Bottom} 
::msgcat::mcset zh {Box Annulus} [encoding convertfrom big5 "\xA4\xE8 \xA7\xCE \xB0\xE9"]
::msgcat::mcset zh {Box Panda} 
::msgcat::mcset zh {BoxCircle} 
::msgcat::mcset zh {Boxcar} 
::msgcat::mcset zh {Box} [encoding convertfrom big5 "\xA4\xE8 \xA7\xCE"]
::msgcat::mcset zh {Broadcast} 
::msgcat::mcset zh {Browser} 
::msgcat::mcset zh {Browse} 
::msgcat::mcset zh {Buffer} 
::msgcat::mcset zh {Buttonbar} 
::msgcat::mcset zh {Buttons} [encoding convertfrom big5 "\xAB\xF6 \xB6\x73 \xA6\x43"]
::msgcat::mcset zh {Bytes} 
::msgcat::mcset zh {CMYK} 
::msgcat::mcset zh {Can Delete} [encoding convertfrom big5 "\xA5\x69 \xA5\x48 \xA7\x52 \xB0\xA3"]
::msgcat::mcset zh {Can Edit} [encoding convertfrom big5 "\xA5\x69 \xA5\x48 \xBD\x73 \xBF\xE8"]
::msgcat::mcset zh {Can Move} [encoding convertfrom big5 "\xA5\x69 \xA5\x48 \xB2\xBE \xB0\xCA"]
::msgcat::mcset zh {Can Rotate} [encoding convertfrom big5 "\xA5\x69 \xA5\x48 \xB1\xDB \xC2\xE0"]
::msgcat::mcset zh {Cancelled} 
::msgcat::mcset zh {Cancel} 
::msgcat::mcset zh {Cap} 
::msgcat::mcset zh {Catalog Server} 
::msgcat::mcset zh {Catalog Tool} 
::msgcat::mcset zh {Catalogs} [encoding convertfrom big5 "\xB8\xEA \xAE\xC6 \xAA\xED"]
::msgcat::mcset zh {Catalog} 
::msgcat::mcset zh {Catrom} 
::msgcat::mcset zh {Cat} 
::msgcat::mcset zh {Center Dialogs} 
::msgcat::mcset zh {Center Image} [encoding convertfrom big5 "\xBC\x76 \xB9\xB3 \xB8\x6D \xA4\xA4"]
::msgcat::mcset zh {Center} 
::msgcat::mcset zh {Centroid Parameters} [encoding convertfrom big5 "\xA4\xA4 \xA4\xDF \xB0\xD1 \xBC\xC6"]
::msgcat::mcset zh {Centroid} 
::msgcat::mcset zh {Circle} [encoding convertfrom big5 "\xB6\xEA \xA7\xCE"]
::msgcat::mcset zh {Clear All} 
::msgcat::mcset zh {Clear Analysis Commands} 
::msgcat::mcset zh {Clear Cache} 
::msgcat::mcset zh {Clear External Analysis Commands?} 
::msgcat::mcset zh {Clear Filter} 
::msgcat::mcset zh {Clear Frame} [encoding convertfrom big5 "\xB2\x4D \xB0\xA3 \xBC\x76 \xB9\xB3 \xB5\xF8 \xB5\xA1"]
::msgcat::mcset zh {Clear Preferences?} 
::msgcat::mcset zh {Clear Preferences} 
::msgcat::mcset zh {Clear} [encoding convertfrom big5 "\xB2\x4D \xB0\xA3"]
::msgcat::mcset zh {Click to Center} 
::msgcat::mcset zh {Close} 
::msgcat::mcset zh {Colorbar Size} 
::msgcat::mcset zh {Colorbar} [encoding convertfrom big5 "\xA6\xE2 \xB6\xA5 \xB9\xCF \xA8\xD2"]
::msgcat::mcset zh {Colormap Parameters} [encoding convertfrom big5 "\xC3\x43 \xA6\xE2 \xB0\xD1 \xBC\xC6"]
::msgcat::mcset zh {Colormap} 
::msgcat::mcset zh {Color} [encoding convertfrom big5 "\xC3\x43 \xA6\xE2"]
::msgcat::mcset zh {Columns} [encoding convertfrom big5 "\xA4\xE8 \xA6\xEC"]
::msgcat::mcset zh {Column} 
::msgcat::mcset zh {Comets} 
::msgcat::mcset zh {Command not allowed} 
::msgcat::mcset zh {Command} 
::msgcat::mcset zh {Compass} 
::msgcat::mcset zh {Composite Region} [encoding convertfrom big5 "\xB2\x56 \xA6\x58 \xB0\xCF \xB0\xEC"]
::msgcat::mcset zh {Composite} 
::msgcat::mcset zh {Compression} 
::msgcat::mcset zh {Configure} 
::msgcat::mcset zh {Connect SAMP} 
::msgcat::mcset zh {Connect} 
::msgcat::mcset zh {Console} 
::msgcat::mcset zh {Contacting Server} 
::msgcat::mcset zh {Contour Parameters} [encoding convertfrom big5 "\xB5\xA5 \xAD\xC8 \xBD\x75 \xB0\xD1 \xBC\xC6"]
::msgcat::mcset zh {Contour Paste} 
::msgcat::mcset zh {Contour Save} 
::msgcat::mcset zh {Contours} [encoding convertfrom big5 "\xB5\xA5 \xAD\xC8 \xBD\x75"]
::msgcat::mcset zh {Contour} 
::msgcat::mcset zh {Contrast} 
::msgcat::mcset zh {Control Panel} 
::msgcat::mcset zh {Convert to Polygons} 
::msgcat::mcset zh {Coordinate Grid Parameters} [encoding convertfrom big5 "\xAE\x79 \xBC\xD0 \xAE\xE6 \xBD\x75 \xB0\xD1 \xBC\xC6"]
::msgcat::mcset zh {Coordinate Grid} [encoding convertfrom big5 "\xAE\x79 \xBC\xD0 \xAE\xE6 \xBD\x75"]
::msgcat::mcset zh {Coordinate System} 
::msgcat::mcset zh {Coordinates} 
::msgcat::mcset zh {Coordinate} 
::msgcat::mcset zh {Copy Contours} 
::msgcat::mcset zh {Copy to Regions} 
::msgcat::mcset zh {Copy} 
::msgcat::mcset zh {Create Movie} 
::msgcat::mcset zh {Create New Frame on Download} 
::msgcat::mcset zh {Create} [encoding convertfrom big5 "\xBB\x73 \xB3\x79"]
::msgcat::mcset zh {Crop Parameters} 
::msgcat::mcset zh {Crop} 
::msgcat::mcset zh {Crosshair Parameters} 
::msgcat::mcset zh {Crosshair To} 
::msgcat::mcset zh {Crosshair} 
::msgcat::mcset zh {Cross} 
::msgcat::mcset zh {Cubehelix} 
::msgcat::mcset zh {Cube} 
::msgcat::mcset zh {Cubic} 
::msgcat::mcset zh {Current Frame} 
::msgcat::mcset zh {Current Range} 
::msgcat::mcset zh {Current} 
::msgcat::mcset zh {Cursor} 
::msgcat::mcset zh {Cut} 
::msgcat::mcset zh {Cyan} [encoding convertfrom big5 "\xAB\x43 \xA6\xE2"]
::msgcat::mcset zh {DMS} 
::msgcat::mcset zh {DPI} 
::msgcat::mcset zh {DS9 has detected a newer version of a backup file and therefore will not process this file.} 
::msgcat::mcset zh {DS9 has detected a newer version of a preferences file.} 
::msgcat::mcset zh {DS9 has detected an older backup file, do you wish to continue?} 
::msgcat::mcset zh {DS9 has detected an older preferences file, do you wish to update?} 
::msgcat::mcset zh {DS9 will complete the initialization process} 
::msgcat::mcset zh {Darken} 
::msgcat::mcset zh {Dash} [encoding convertfrom big5 "\xB5\xEA \xBD\x75"]
::msgcat::mcset zh {Data Format} 
::msgcat::mcset zh {Data must be ascii numeric values} 
::msgcat::mcset zh {Dataset Name} 
::msgcat::mcset zh {Dataset} 
::msgcat::mcset zh {Data} 
::msgcat::mcset zh {Decrease} 
::msgcat::mcset zh {Default All Files} 
::msgcat::mcset zh {Default Format} 
::msgcat::mcset zh {Default Length} 
::msgcat::mcset zh {Default} 
::msgcat::mcset zh {Degrees} 
::msgcat::mcset zh {Delay} 
::msgcat::mcset zh {Delete All Frames?} 
::msgcat::mcset zh {Delete All Frames} [encoding convertfrom big5 "\xA7\x52 \xB0\xA3 \xA9\xD2 \xA6\xB3 \xBC\x76 \xB9\xB3 \xB5\xF8 \xB5\xA1"]
::msgcat::mcset zh {Delete All Groups?} 
::msgcat::mcset zh {Delete All Groups} 
::msgcat::mcset zh {Delete All} 
::msgcat::mcset zh {Delete Color Tags} 
::msgcat::mcset zh {Delete Dataset} 
::msgcat::mcset zh {Delete Frame} [encoding convertfrom big5 "\xA7\x52 \xB0\xA3 \xBC\x76 \xB9\xB3 \xB5\xF8 \xB5\xA1"]
::msgcat::mcset zh {Delete Graph} 
::msgcat::mcset zh {Delete Group} 
::msgcat::mcset zh {Delete Load} 
::msgcat::mcset zh {Delete Regions?} 
::msgcat::mcset zh {Delete Regions} 
::msgcat::mcset zh {Delete Selected Regions} [encoding convertfrom big5 "\xA7\x52 \xB0\xA3 \xBF\xEF \xA8\xFA \xB0\xCF \xB0\xEC"]
::msgcat::mcset zh {Delete Select} 
::msgcat::mcset zh {Delete and Open Regions} 
::msgcat::mcset zh {Delete} [encoding convertfrom big5 "\xA7\x52 \xB0\xA3"]
::msgcat::mcset zh {Depth} 
::msgcat::mcset zh {Detector} 
::msgcat::mcset zh {Dialog Box} 
::msgcat::mcset zh {Diameter} 
::msgcat::mcset zh {Diamond} 
::msgcat::mcset zh {Dimensions} 
::msgcat::mcset zh {Dimension} 
::msgcat::mcset zh {Direction} 
::msgcat::mcset zh {Disconnect} 
::msgcat::mcset zh {Display Size} 
::msgcat::mcset zh {Dissolve} [encoding convertfrom big5 "\xB8\xD1 \xB4\xB2"]
::msgcat::mcset zh {Distance} 
::msgcat::mcset zh {Done} 
::msgcat::mcset zh {Download Colormap} 
::msgcat::mcset zh {Drag to Center} 
::msgcat::mcset zh {Duplicate Dataset} 
::msgcat::mcset zh {ENVI} 
::msgcat::mcset zh {EPS} 
::msgcat::mcset zh {East} 
::msgcat::mcset zh {Ecliptic} 
::msgcat::mcset zh {Edit Group Name} 
::msgcat::mcset zh {Edit} [encoding convertfrom big5 "\xBD\x73 \xBF\xE8"]
::msgcat::mcset zh {Elevation} 
::msgcat::mcset zh {Ellipse Panda} 
::msgcat::mcset zh {Ellipse} [encoding convertfrom big5 "\xBE\xF2 \xB6\xEA \xA7\xCE"]
::msgcat::mcset zh {Elliptical Annulus} [encoding convertfrom big5 "\xBE\xF2 \xB6\xEA \xB0\xE9"]
::msgcat::mcset zh {Elliptical Gaussian} 
::msgcat::mcset zh {Elliptical Panda} 
::msgcat::mcset zh {Enable Confirmation Dialogs} 
::msgcat::mcset zh {Enable} 
::msgcat::mcset zh {End} 
::msgcat::mcset zh {Enter Color} 
::msgcat::mcset zh {Enter Font Size} 
::msgcat::mcset zh {Enter Group Name} 
::msgcat::mcset zh {Enter Search Expression} 
::msgcat::mcset zh {Enter URL} 
::msgcat::mcset zh {Entry} 
::msgcat::mcset zh {Equal Area} 
::msgcat::mcset zh {Equal Distance} 
::msgcat::mcset zh {Equal Spacing} 
::msgcat::mcset zh {Equal Value} 
::msgcat::mcset zh {Error code was returned} 
::msgcat::mcset zh {Errorbar} 
::msgcat::mcset zh {Error} 
::msgcat::mcset zh {Examine Frame} 
::msgcat::mcset zh {Examine} [encoding convertfrom big5 "\xA9\xF1 \xA4\x6A \xC0\xCB \xB5\xF8"]
::msgcat::mcset zh {Exam} 
::msgcat::mcset zh {Exclude} 
::msgcat::mcset zh {Exit} [encoding convertfrom big5 "\xC2\xF7 \xB6\x7D"]
::msgcat::mcset zh {Export Array} 
::msgcat::mcset zh {Export ENVI} 
::msgcat::mcset zh {Export GIF} 
::msgcat::mcset zh {Export JPEG} 
::msgcat::mcset zh {Export NRRD} 
::msgcat::mcset zh {Export PNG} 
::msgcat::mcset zh {Export RGB Array} 
::msgcat::mcset zh {Export TIFF} 
::msgcat::mcset zh {Export} 
::msgcat::mcset zh {Extension Data} 
::msgcat::mcset zh {Extension not found} 
::msgcat::mcset zh {Extensions} 
::msgcat::mcset zh {Extension} 
::msgcat::mcset zh {Exterior Axes} 
::msgcat::mcset zh {Exterior Numerics} 
::msgcat::mcset zh {FAQ} 
::msgcat::mcset zh {FITS} 
::msgcat::mcset zh {FK4} 
::msgcat::mcset zh {FK5} 
::msgcat::mcset zh {FP} 
::msgcat::mcset zh {Factor} 
::msgcat::mcset zh {File not Found or Unable to load FITS data MIME type} 
::msgcat::mcset zh {File not found} 
::msgcat::mcset zh {Filename} [encoding convertfrom big5 "\xC0\xC9 \xAE\xD7 \xA6\x57 \xBA\xD9"]
::msgcat::mcset zh {File} [encoding convertfrom big5 "\xC0\xC9 \xAE\xD7"]
::msgcat::mcset zh {Fill} 
::msgcat::mcset zh {Filter} 
::msgcat::mcset zh {Find Next} 
::msgcat::mcset zh {Find} 
::msgcat::mcset zh {First Block} 
::msgcat::mcset zh {First Frame} [encoding convertfrom big5 "\xB3\xCC \xA4\x57 \xBC\x68 \xBC\x76 \xB9\xB3 \xB5\xF8 \xB5\xA1"]
::msgcat::mcset zh {First} 
::msgcat::mcset zh {Fits} 
::msgcat::mcset zh {Fixed in Size} [encoding convertfrom big5 "\xA9\x54 \xA9\x77 \xA4\x6A \xA4\x70"]
::msgcat::mcset zh {Flip} 
::msgcat::mcset zh {Font} 
::msgcat::mcset zh {Footprint Servers} 
::msgcat::mcset zh {Footprint} 
::msgcat::mcset zh {For more information, use --help} 
::msgcat::mcset zh {Foreground} 
::msgcat::mcset zh {Forground} 
::msgcat::mcset zh {Format} 
::msgcat::mcset zh {Forward} 
::msgcat::mcset zh {Found} 
::msgcat::mcset zh {Frame Information} [encoding convertfrom big5 "\xBC\x76 \xB9\xB3 \xB5\xF8 \xB5\xA1 \xB8\xEA \xB0\x54"]
::msgcat::mcset zh {Frame Parameters} [encoding convertfrom big5 "\xBC\x76 \xB9\xB3 \xB5\xF8 \xB5\xA1 \xB0\xD1 \xBC\xC6"]
::msgcat::mcset zh {Frames} 
::msgcat::mcset zh {Frame} [encoding convertfrom big5 "\xBC\x76 \xB9\xB3 \xB5\xF8 \xB5\xA1"]
::msgcat::mcset zh {From} 
::msgcat::mcset zh {Front} 
::msgcat::mcset zh {Full Range} 
::msgcat::mcset zh {Function} 
::msgcat::mcset zh {GIF} 
::msgcat::mcset zh {GUI} 
::msgcat::mcset zh {Galactic} 
::msgcat::mcset zh {Gap} 
::msgcat::mcset zh {Gaussian} 
::msgcat::mcset zh {General} 
::msgcat::mcset zh {Generate} 
::msgcat::mcset zh {Generating Regions} 
::msgcat::mcset zh {Get Information} [encoding convertfrom big5 "\xB8\xFC \xA4\x4A \xB0\x54 \xAE\xA7"]
::msgcat::mcset zh {Gist} 
::msgcat::mcset zh {Global Properties} 
::msgcat::mcset zh {Global} 
::msgcat::mcset zh {Goto Frame} [encoding convertfrom big5 "\xA8\xEC \xBC\x76 \xB9\xB3 \xB5\xF8 \xB5\xA1"]
::msgcat::mcset zh {Goto Row} 
::msgcat::mcset zh {Goto} 
::msgcat::mcset zh {Graph Horz} 
::msgcat::mcset zh {Graph Parameters} 
::msgcat::mcset zh {Graph Vert} 
::msgcat::mcset zh {Graphics} 
::msgcat::mcset zh {Graphs} 
::msgcat::mcset zh {Graph} 
::msgcat::mcset zh {Grayscale} 
::msgcat::mcset zh {Green} 
::msgcat::mcset zh {Grid Gap} 
::msgcat::mcset zh {Grid} 
::msgcat::mcset zh {Groups} 
::msgcat::mcset zh {HMS} 
::msgcat::mcset zh {HTTP} 
::msgcat::mcset zh {Header} 
::msgcat::mcset zh {Height} 
::msgcat::mcset zh {Help Desk} 
::msgcat::mcset zh {Help Me Choose} 
::msgcat::mcset zh {Help} [encoding convertfrom big5 "\xBB\xA1 \xA9\xFA"]
::msgcat::mcset zh {Hide All} [encoding convertfrom big5 "\xC1\xF4 \xC2\xC3 \xA5\xFE \xB3\xA1"]
::msgcat::mcset zh {Highlite} 
::msgcat::mcset zh {High} 
::msgcat::mcset zh {Histogram Equalization} 
::msgcat::mcset zh {Histogram} 
::msgcat::mcset zh {Horizontal Graph} 
::msgcat::mcset zh {Horizontal Layout} 
::msgcat::mcset zh {Horizontal} [encoding convertfrom big5 "\xA4\xF4 \xA5\xAD"]
::msgcat::mcset zh {IAU Location Code} 
::msgcat::mcset zh {ICRS} 
::msgcat::mcset zh {Identification} 
::msgcat::mcset zh {If} 
::msgcat::mcset zh {Image Servers} 
::msgcat::mcset zh {Image} 
::msgcat::mcset zh {Import Array} 
::msgcat::mcset zh {Import ENVI} 
::msgcat::mcset zh {Import GIF} 
::msgcat::mcset zh {Import JPEG} 
::msgcat::mcset zh {Import NRRD} 
::msgcat::mcset zh {Import PNG} 
::msgcat::mcset zh {Import RGB Array} 
::msgcat::mcset zh {Import Slice GIF} 
::msgcat::mcset zh {Import Slice JPEG} 
::msgcat::mcset zh {Import Slice PNG} 
::msgcat::mcset zh {Import Slice TIFF} 
::msgcat::mcset zh {Import TIFF} 
::msgcat::mcset zh {Import} 
::msgcat::mcset zh {Include} 
::msgcat::mcset zh {Increase} 
::msgcat::mcset zh {Information Panel} [encoding convertfrom big5 "\xB8\xEA \xB0\x54 \xA6\x43"]
::msgcat::mcset zh {Information} [encoding convertfrom big5 "\xB8\xEA \xB0\x54"]
::msgcat::mcset zh {Initialize XPA} 
::msgcat::mcset zh {Inner} 
::msgcat::mcset zh {Instrument FOV} 
::msgcat::mcset zh {Instrument} 
::msgcat::mcset zh {Interior Axes} 
::msgcat::mcset zh {Interior Numerics} 
::msgcat::mcset zh {Internal Parse Error} 
::msgcat::mcset zh {Interval} 
::msgcat::mcset zh {Invalid Column Name} 
::msgcat::mcset zh {Invalid WCS} 
::msgcat::mcset zh {Invalid formated multipart/mixed mime type message} 
::msgcat::mcset zh {Invert Colormap} [encoding convertfrom big5 "\xA6\xE2 \xB1\x6D \xA4\xCF \xA6\x56"]
::msgcat::mcset zh {Invert Selection} [encoding convertfrom big5 "\xA4\xCF \xA6\x56 \xBF\xEF \xA8\xFA"]
::msgcat::mcset zh {Invert} 
::msgcat::mcset zh {Italic} 
::msgcat::mcset zh {Items Found} 
::msgcat::mcset zh {Iteration} 
::msgcat::mcset zh {JPEG Quality Factor} 
::msgcat::mcset zh {JPEG} 
::msgcat::mcset zh {Keep-Alive} 
::msgcat::mcset zh {Keyword} 
::msgcat::mcset zh {Labels} 
::msgcat::mcset zh {Label} 
::msgcat::mcset zh {Landscape} 
::msgcat::mcset zh {Language} 
::msgcat::mcset zh {Last Block} 
::msgcat::mcset zh {Last Frame} [encoding convertfrom big5 "\xB3\xCC \xA9\xB3 \xBC\x68 \xBC\x76 \xB9\xB3 \xB5\xF8 \xB5\xA1"]
::msgcat::mcset zh {Last} 
::msgcat::mcset zh {Layout Horz} 
::msgcat::mcset zh {Layout Vert} 
::msgcat::mcset zh {Layout} 
::msgcat::mcset zh {Left} 
::msgcat::mcset zh {Legal} 
::msgcat::mcset zh {Legend Position} 
::msgcat::mcset zh {Legend Title} 
::msgcat::mcset zh {Legend} 
::msgcat::mcset zh {Length} 
::msgcat::mcset zh {Letter} 
::msgcat::mcset zh {Levels} 
::msgcat::mcset zh {Level} 
::msgcat::mcset zh {Lighten} 
::msgcat::mcset zh {Limits} 
::msgcat::mcset zh {Line Dataset} 
::msgcat::mcset zh {Line Plot Tool} 
::msgcat::mcset zh {Linear} [encoding convertfrom big5 "\xBD\x75 \xA9\xCA"]
::msgcat::mcset zh {Line} [encoding convertfrom big5 "\xAA\xBD \xBD\x75"]
::msgcat::mcset zh {List Data} 
::msgcat::mcset zh {List Regions} [encoding convertfrom big5 "\xA6\x43 \xA5\x58 \xB0\xCF \xB0\xEC"]
::msgcat::mcset zh {List Selected Regions} 
::msgcat::mcset zh {List Select} 
::msgcat::mcset zh {List} 
::msgcat::mcset zh {Load Analysis Commands} 
::msgcat::mcset zh {Load Color Tags} 
::msgcat::mcset zh {Load Contour Levels} 
::msgcat::mcset zh {Load Contrast/Bias} 
::msgcat::mcset zh {Load Data} 
::msgcat::mcset zh {Load Mosaic} 
::msgcat::mcset zh {Load Template} 
::msgcat::mcset zh {Load into All} 
::msgcat::mcset zh {Load into Current} 
::msgcat::mcset zh {Loading Catalog} 
::msgcat::mcset zh {Loading} 
::msgcat::mcset zh {Load} [encoding convertfrom big5 "\xB8\xFC \xA4\x4A"]
::msgcat::mcset zh {Local} 
::msgcat::mcset zh {Lock Axes} 
::msgcat::mcset zh {Lock Bin} 
::msgcat::mcset zh {Lock Color} 
::msgcat::mcset zh {Lock Crop Amplifier} 
::msgcat::mcset zh {Lock Crop Detector} 
::msgcat::mcset zh {Lock Crop Image} 
::msgcat::mcset zh {Lock Crop None} 
::msgcat::mcset zh {Lock Crop Physical} 
::msgcat::mcset zh {Lock Crop WCS} 
::msgcat::mcset zh {Lock Crosshair Amplifier} 
::msgcat::mcset zh {Lock Crosshair Detector} 
::msgcat::mcset zh {Lock Crosshair Image} 
::msgcat::mcset zh {Lock Crosshair None} 
::msgcat::mcset zh {Lock Crosshair Physical} 
::msgcat::mcset zh {Lock Crosshair WCS} 
::msgcat::mcset zh {Lock Frame Amplifier} 
::msgcat::mcset zh {Lock Frame Detector} 
::msgcat::mcset zh {Lock Frame Image} 
::msgcat::mcset zh {Lock Frame None} 
::msgcat::mcset zh {Lock Frame Physical} 
::msgcat::mcset zh {Lock Frame WCS} 
::msgcat::mcset zh {Lock Limits} 
::msgcat::mcset zh {Lock Scale} 
::msgcat::mcset zh {Lock Slice Image} 
::msgcat::mcset zh {Lock Slice None} 
::msgcat::mcset zh {Lock Slice WCS} 
::msgcat::mcset zh {Lock Smooth} 
::msgcat::mcset zh {Lock} 
::msgcat::mcset zh {Log Exponent} 
::msgcat::mcset zh {Log} [encoding convertfrom big5 "\xB9\xEF \xBC\xC6"]
::msgcat::mcset zh {Low High} 
::msgcat::mcset zh {Lower Left Back} 
::msgcat::mcset zh {Lower Left Front} 
::msgcat::mcset zh {Lower Right Back} 
::msgcat::mcset zh {Lower Right Front} 
::msgcat::mcset zh {Low} 
::msgcat::mcset zh {MIP} 
::msgcat::mcset zh {Magenta} [encoding convertfrom big5 "\xAC\xF5 \xB5\xB5 \xA6\xE2"]
::msgcat::mcset zh {Magnification} 
::msgcat::mcset zh {Magnifier} [encoding convertfrom big5 "\xA9\xF1 \xA4\x6A \xC3\xE8 \xB5\xF8 \xB5\xA1"]
::msgcat::mcset zh {Major Radius} 
::msgcat::mcset zh {Major Sigma} 
::msgcat::mcset zh {Major} 
::msgcat::mcset zh {Manual} 
::msgcat::mcset zh {Mask Parameters} 
::msgcat::mcset zh {Match Axes} 
::msgcat::mcset zh {Match Bin} 
::msgcat::mcset zh {Match Catalog requires at least 1 row per catalog} 
::msgcat::mcset zh {Match Color} 
::msgcat::mcset zh {Match Crop Amplifier} 
::msgcat::mcset zh {Match Crop Detector} 
::msgcat::mcset zh {Match Crop Image} 
::msgcat::mcset zh {Match Crop Physical} 
::msgcat::mcset zh {Match Crop WCS} 
::msgcat::mcset zh {Match Crosshair Amplifier} 
::msgcat::mcset zh {Match Crosshair Detector} 
::msgcat::mcset zh {Match Crosshair Image} 
::msgcat::mcset zh {Match Crosshair Physical} 
::msgcat::mcset zh {Match Crosshair WCS} 
::msgcat::mcset zh {Match Frame Amplifier} 
::msgcat::mcset zh {Match Frame Detector} 
::msgcat::mcset zh {Match Frame Image} 
::msgcat::mcset zh {Match Frame Physical} 
::msgcat::mcset zh {Match Frame WCS} 
::msgcat::mcset zh {Match Limits} 
::msgcat::mcset zh {Match Scale} 
::msgcat::mcset zh {Match Slice Image} 
::msgcat::mcset zh {Match Slice WCS} 
::msgcat::mcset zh {Match Smooth} 
::msgcat::mcset zh {Match} 
::msgcat::mcset zh {Math Function} 
::msgcat::mcset zh {Matplotlib} 
::msgcat::mcset zh {Max Rows} 
::msgcat::mcset zh {Maximum} 
::msgcat::mcset zh {Max} 
::msgcat::mcset zh {Menus and Buttons} 
::msgcat::mcset zh {Menu} 
::msgcat::mcset zh {Message Log} 
::msgcat::mcset zh {Method} 
::msgcat::mcset zh {Min Max Parameters} 
::msgcat::mcset zh {Min Max} 
::msgcat::mcset zh {Minimum} 
::msgcat::mcset zh {Minor Radius} 
::msgcat::mcset zh {Minor Sigma} 
::msgcat::mcset zh {Minor} 
::msgcat::mcset zh {Minutes} 
::msgcat::mcset zh {Min} 
::msgcat::mcset zh {Mission} 
::msgcat::mcset zh {Mode} 
::msgcat::mcset zh {Mosaic IRAF Segment} 
::msgcat::mcset zh {Mosaic IRAF} 
::msgcat::mcset zh {Mosaic WCS Segment} 
::msgcat::mcset zh {Mosaic WCS} 
::msgcat::mcset zh {Mosaic WFPC2} 
::msgcat::mcset zh {Mosaic} 
::msgcat::mcset zh {Mouse Click Epsilon} 
::msgcat::mcset zh {Mouse Wheel Bin} 
::msgcat::mcset zh {Mouse Wheel Zoom} 
::msgcat::mcset zh {Move Back} 
::msgcat::mcset zh {Move First} 
::msgcat::mcset zh {Move Forward} 
::msgcat::mcset zh {Move Frame} [encoding convertfrom big5 "\xBC\x76 \xB9\xB3 \xB5\xF8 \xB5\xA1 \xB6\xB6 \xA7\xC7"]
::msgcat::mcset zh {Move Last} 
::msgcat::mcset zh {Move to Back} 
::msgcat::mcset zh {Move to Front} 
::msgcat::mcset zh {Movie} 
::msgcat::mcset zh {Muliple Extension Cube} 
::msgcat::mcset zh {Muliple Extension Frames} 
::msgcat::mcset zh {Multiple Extension Cube} 
::msgcat::mcset zh {Multiple Extension Frames} 
::msgcat::mcset zh {Multiple WCS} 
::msgcat::mcset zh {NAN} 
::msgcat::mcset zh {NRRD} 
::msgcat::mcset zh {Name Resolution} 
::msgcat::mcset zh {Name Server} 
::msgcat::mcset zh {Name or Designation} 
::msgcat::mcset zh {Name} 
::msgcat::mcset zh {Native Dialog} 
::msgcat::mcset zh {New Features} 
::msgcat::mcset zh {New Frame 3D} 
::msgcat::mcset zh {New Frame RGB} 
::msgcat::mcset zh {New Frame each Time} 
::msgcat::mcset zh {New Frame} [encoding convertfrom big5 "\xB7\x73 \xBC\x76 \xB9\xB3 \xB5\xF8 \xB5\xA1"]
::msgcat::mcset zh {New Graph} 
::msgcat::mcset zh {New Group} 
::msgcat::mcset zh {New Plot} 
::msgcat::mcset zh {New} 
::msgcat::mcset zh {Next Block} 
::msgcat::mcset zh {Next Frame} [encoding convertfrom big5 "\xAB\xE1 \xA4\x40 \xBC\x68 \xBC\x76 \xB9\xB3 \xB5\xF8 \xB5\xA1"]
::msgcat::mcset zh {Next} 
::msgcat::mcset zh {No Catalog specified} 
::msgcat::mcset zh {No Data Available} 
::msgcat::mcset zh {No Items Found} 
::msgcat::mcset zh {Non-NAN} 
::msgcat::mcset zh {Non-Zero} 
::msgcat::mcset zh {None} 
::msgcat::mcset zh {Normal} 
::msgcat::mcset zh {North} 
::msgcat::mcset zh {Not Found} 
::msgcat::mcset zh {Not Supported} 
::msgcat::mcset zh {Not valid export format} 
::msgcat::mcset zh {Notes} 
::msgcat::mcset zh {Number of Samples} 
::msgcat::mcset zh {Number of Threads} 
::msgcat::mcset zh {Number of Ticks} 
::msgcat::mcset zh {Number} 
::msgcat::mcset zh {Numerics} [encoding convertfrom big5 "\xBC\xC6 \xAD\xC8"]
::msgcat::mcset zh {OK} 
::msgcat::mcset zh {Object} [encoding convertfrom big5 "\xA4\xD1 \xC5\xE9 \xA6\x57 \xBA\xD9"]
::msgcat::mcset zh {ObsId} 
::msgcat::mcset zh {Open File} 
::msgcat::mcset zh {Open ME Cube} 
::msgcat::mcset zh {Open ME Frames} 
::msgcat::mcset zh {Open Mosaic IRAF Seg} 
::msgcat::mcset zh {Open Mosaic IRAF} 
::msgcat::mcset zh {Open Mosaic WCS Seg} 
::msgcat::mcset zh {Open Mosaic WCS} 
::msgcat::mcset zh {Open Mosaic WFPC2} 
::msgcat::mcset zh {Open RGB Cube} 
::msgcat::mcset zh {Open RGB Image} 
::msgcat::mcset zh {Open Regions} 
::msgcat::mcset zh {Open Slice} 
::msgcat::mcset zh {Open TCL Console} 
::msgcat::mcset zh {Open URL} 
::msgcat::mcset zh {Open as} 
::msgcat::mcset zh {Open} [encoding convertfrom big5 "\xB6\x7D \xB1\xD2"]
::msgcat::mcset zh {Operator} 
::msgcat::mcset zh {Orientation} [encoding convertfrom big5 "\xA4\xE8 \xA6\x56"]
::msgcat::mcset zh {Origin} 
::msgcat::mcset zh {Oscillate} 
::msgcat::mcset zh {Other Color} 
::msgcat::mcset zh {Other Font Size} 
::msgcat::mcset zh {Other} [encoding convertfrom big5 "\xA8\xE4 \xA5\xA6"]
::msgcat::mcset zh {Outer} 
::msgcat::mcset zh {Overplot} 
::msgcat::mcset zh {Override Color} 
::msgcat::mcset zh {PNG} 
::msgcat::mcset zh {PS Page Setup} 
::msgcat::mcset zh {PS Print} 
::msgcat::mcset zh {Page Setup} 
::msgcat::mcset zh {Page Source} 
::msgcat::mcset zh {Pan To} 
::msgcat::mcset zh {Pan Zoom Rotate Parameters} [encoding convertfrom big5 "\xC1\x59 \xA9\xF1 \xB1\xDB \xC2\xE0 \xB0\xD1 \xBC\xC6"]
::msgcat::mcset zh {Pan Zoom} 
::msgcat::mcset zh {Pan then Zoom} 
::msgcat::mcset zh {Panda} 
::msgcat::mcset zh {Panner} [encoding convertfrom big5 "\xC1\x59 \xB9\xCF"]
::msgcat::mcset zh {Pan} 
::msgcat::mcset zh {Parameters} 
::msgcat::mcset zh {Password} 
::msgcat::mcset zh {Paste Contours} 
::msgcat::mcset zh {Paste} 
::msgcat::mcset zh {Physical} 
::msgcat::mcset zh {Pixel Distribution} 
::msgcat::mcset zh {Pixel Size} 
::msgcat::mcset zh {Pixel Table} 
::msgcat::mcset zh {Pixels} 
::msgcat::mcset zh {Planets} 
::msgcat::mcset zh {Play} 
::msgcat::mcset zh {Please Select a Region} 
::msgcat::mcset zh {Please change the file's permission to disable other users write access. Use anyway?} 
::msgcat::mcset zh {Please specify instruments} 
::msgcat::mcset zh {Please specify radius and either name or (ra,dec)} 
::msgcat::mcset zh {Please specify width, height, and either name or (ra,dec)} 
::msgcat::mcset zh {Plot 2D} 
::msgcat::mcset zh {Plot 3D} 
::msgcat::mcset zh {Plot Area} 
::msgcat::mcset zh {Plot Control Panel} 
::msgcat::mcset zh {Plot Tool} 
::msgcat::mcset zh {Plotting Regions} 
::msgcat::mcset zh {Plot} 
::msgcat::mcset zh {Plus} 
::msgcat::mcset zh {Pointer} 
::msgcat::mcset zh {Points} 
::msgcat::mcset zh {Point} 
::msgcat::mcset zh {Polygon} [encoding convertfrom big5 "\xA6\x68 \xA8\xA4 \xA7\xCE"]
::msgcat::mcset zh {Portrait} 
::msgcat::mcset zh {Position} 
::msgcat::mcset zh {Poster} 
::msgcat::mcset zh {Postscript} 
::msgcat::mcset zh {Power} [encoding convertfrom big5 "\xAB\xFC \xBC\xC6"]
::msgcat::mcset zh {Precision} 
::msgcat::mcset zh {Preferences} [encoding convertfrom big5 "\xB0\xBE \xA6\x6E \xB3\x5D \xA9\x77"]
::msgcat::mcset zh {Preserve During Load} 
::msgcat::mcset zh {Previous Block} 
::msgcat::mcset zh {Previous Frame} [encoding convertfrom big5 "\xAB\x65 \xA4\x40 \xBC\x68 \xBC\x76 \xB9\xB3 \xB5\xF8 \xB5\xA1"]
::msgcat::mcset zh {Previous} 
::msgcat::mcset zh {Prev} 
::msgcat::mcset zh {Print Coordinates} 
::msgcat::mcset zh {Print To} 
::msgcat::mcset zh {Printer} 
::msgcat::mcset zh {Print} [encoding convertfrom big5 "\xA6\x43 \xA6\x4C"]
::msgcat::mcset zh {Prism Goto} 
::msgcat::mcset zh {Prism} 
::msgcat::mcset zh {Projection} 
::msgcat::mcset zh {Properties} [encoding convertfrom big5 "\xA6\x43 \xA6\x4C"]
::msgcat::mcset zh {Property} 
::msgcat::mcset zh {Proxy Host} 
::msgcat::mcset zh {Proxy Port} 
::msgcat::mcset zh {Publication} 
::msgcat::mcset zh {Quadratic} 
::msgcat::mcset zh {RDB} 
::msgcat::mcset zh {RGB Array} 
::msgcat::mcset zh {RGB Cube} 
::msgcat::mcset zh {RGB Image} 
::msgcat::mcset zh {RGB} 
::msgcat::mcset zh {Radial Profile} 
::msgcat::mcset zh {Radius} 
::msgcat::mcset zh {Range} 
::msgcat::mcset zh {Redo} 
::msgcat::mcset zh {Red} 
::msgcat::mcset zh {Reference Manual} 
::msgcat::mcset zh {Reference} 
::msgcat::mcset zh {Refresh Frame} [encoding convertfrom big5 "\xAD\xAB \xB7\x73 \xBE\xE3 \xB2\x7A \xBC\x76 \xB9\xB3 \xB5\xF8 \xB5\xA1"]
::msgcat::mcset zh {Refresh} 
::msgcat::mcset zh {Region Parameters} [encoding convertfrom big5 "\xB0\xCF \xB0\xEC \xB0\xD1\xBC\xC6"]
::msgcat::mcset zh {Region} [encoding convertfrom big5 "\xB0\xCF \xB0\xEC"]
::msgcat::mcset zh {Release Notes} 
::msgcat::mcset zh {Release} 
::msgcat::mcset zh {Reload} 
::msgcat::mcset zh {Render} 
::msgcat::mcset zh {Repeat} 
::msgcat::mcset zh {Reset Colormap} [encoding convertfrom big5 "\xAD\xAB \xB3\x5D \xC3\x43 \xA6\xF2"]
::msgcat::mcset zh {Reset Frame} [encoding convertfrom big5 "\xAD\xAB \xB3\x5D \xBC\x76 \xB9\xB3 \xB5\xF8 \xB5\xA1"]
::msgcat::mcset zh {Reset} 
::msgcat::mcset zh {Restore} 
::msgcat::mcset zh {Retrieve} 
::msgcat::mcset zh {Return} 
::msgcat::mcset zh {Right} 
::msgcat::mcset zh {Roman} 
::msgcat::mcset zh {Rotate} [encoding convertfrom big5 "\xB1\xDB \xC2\xE0"]
::msgcat::mcset zh {Rows} 
::msgcat::mcset zh {Row} 
::msgcat::mcset zh {Ruler} [encoding convertfrom big5 "\xA4\xD8 \xB3\x57"]
::msgcat::mcset zh {SAMP Image} 
::msgcat::mcset zh {SAMP Table} 
::msgcat::mcset zh {SAMP: not connected} 
::msgcat::mcset zh {SAMP} 
::msgcat::mcset zh {Sample Increment} 
::msgcat::mcset zh {Sample Parameters} 
::msgcat::mcset zh {Samples per Line} 
::msgcat::mcset zh {Sample} 
::msgcat::mcset zh {Save 3D Movie} 
::msgcat::mcset zh {Save Color Tags} 
::msgcat::mcset zh {Save Contour Levels} 
::msgcat::mcset zh {Save Contrast/Bias} 
::msgcat::mcset zh {Save Data} 
::msgcat::mcset zh {Save Image EPS} 
::msgcat::mcset zh {Save Image FITS} 
::msgcat::mcset zh {Save Image GIF} 
::msgcat::mcset zh {Save Image JPEG} 
::msgcat::mcset zh {Save Image PNG} 
::msgcat::mcset zh {Save Image TIFF} 
::msgcat::mcset zh {Save Image on Download} 
::msgcat::mcset zh {Save Image} [encoding convertfrom big5 "\xC0\x78 \xA6\x73 \xBC\x76 \xB9\xB3"]
::msgcat::mcset zh {Save ME Cube} 
::msgcat::mcset zh {Save Mosaic WCS Seg} 
::msgcat::mcset zh {Save Mosaic WCS} 
::msgcat::mcset zh {Save RGB Cube} 
::msgcat::mcset zh {Save RGB Image} 
::msgcat::mcset zh {Save Regions} [encoding convertfrom big5 "\xC0\x78 \xA6\x73 \xB0\xCF \xB0\xEC"]
::msgcat::mcset zh {Save Selected Regions} 
::msgcat::mcset zh {Save Select} 
::msgcat::mcset zh {Save Slice} 
::msgcat::mcset zh {Save Template} 
::msgcat::mcset zh {Save as} 
::msgcat::mcset zh {Save} [encoding convertfrom big5 "\xC0\x78 \xA6\x73"]
::msgcat::mcset zh {Scale Parameters} [encoding convertfrom big5 "\xA6\xE2 \xB6\xA5 \xB0\xD1 \xBC\xC6"]
::msgcat::mcset zh {Scale and Limits} 
::msgcat::mcset zh {Scale} [encoding convertfrom big5 "\xA6\xE2 \xB6\xA5"]
::msgcat::mcset zh {Scan} 
::msgcat::mcset zh {Scatter Dataset} 
::msgcat::mcset zh {Scatter Plot Tool} 
::msgcat::mcset zh {Scope} 
::msgcat::mcset zh {Screen} 
::msgcat::mcset zh {Search for Catalogs} 
::msgcat::mcset zh {Seconds} 
::msgcat::mcset zh {Segment} 
::msgcat::mcset zh {Select All} [encoding convertfrom big5 "\xBF\xEF \xA8\xFA \xA5\xFE \xB3\xA1"]
::msgcat::mcset zh {Select Coordinate System } 
::msgcat::mcset zh {Select Dataset} 
::msgcat::mcset zh {Select Datatset} 
::msgcat::mcset zh {Select Graph} 
::msgcat::mcset zh {Select None} [encoding convertfrom big5 "\xA8\xFA \xAE\xF8 \xBF\xEF \xA8\xFA"]
::msgcat::mcset zh {Send} 
::msgcat::mcset zh {Server} 
::msgcat::mcset zh {Sexagesimal} 
::msgcat::mcset zh {Shadow} 
::msgcat::mcset zh {Shape} [encoding convertfrom big5 "\xA7\xCE \xAA\xAC"]
::msgcat::mcset zh {Show All} [encoding convertfrom big5 "\xC5\xE3 \xA5\xDC \xA5\xFE \xB3\xA1"]
::msgcat::mcset zh {Show Command} 
::msgcat::mcset zh {Show Compass} 
::msgcat::mcset zh {Show Grid} 
::msgcat::mcset zh {Show Legend} 
::msgcat::mcset zh {Show Text} 
::msgcat::mcset zh {Show/Hide Frames} 
::msgcat::mcset zh {Show} [encoding convertfrom big5 "\xC5\xE3 \xA5\xDC"]
::msgcat::mcset zh {Simple Cross} 
::msgcat::mcset zh {Simple Image Access} 
::msgcat::mcset zh {Simple Plus} 
::msgcat::mcset zh {Single Frame} [encoding convertfrom big5 "\xB3\xE6 \xA4\x40 \xBC\x76 \xB9\xB3 \xB5\xF8 \xB5\xA1"]
::msgcat::mcset zh {Single} [encoding convertfrom big5 "\xB3\xE6 \xA4\x40"]
::msgcat::mcset zh {Sites} 
::msgcat::mcset zh {Size/Radius} 
::msgcat::mcset zh {Size} 
::msgcat::mcset zh {Skip First} 
::msgcat::mcset zh {Slice} 
::msgcat::mcset zh {Smooth Parameters} 
::msgcat::mcset zh {Smoothness} 
::msgcat::mcset zh {Smooth} 
::msgcat::mcset zh {Sorry, DS9 does not support} 
::msgcat::mcset zh {Sorry, DS9 requires a Truecolor8, Truecolor16, Truecolor24 visual be available} 
::msgcat::mcset zh {Sort} 
::msgcat::mcset zh {Source TCL} 
::msgcat::mcset zh {Source} 
::msgcat::mcset zh {Space Equal Distance} 
::msgcat::mcset zh {Space Equal Value} 
::msgcat::mcset zh {Spacing} 
::msgcat::mcset zh {Sqrt} 
::msgcat::mcset zh {Square Root} 
::msgcat::mcset zh {Squared} 
::msgcat::mcset zh {Square} 
::msgcat::mcset zh {Starbase} 
::msgcat::mcset zh {Startup} 
::msgcat::mcset zh {Start} 
::msgcat::mcset zh {Statistics} 
::msgcat::mcset zh {Status} 
::msgcat::mcset zh {Step} 
::msgcat::mcset zh {Stop} 
::msgcat::mcset zh {Story of SAOImageDS9} 
::msgcat::mcset zh {Story} 
::msgcat::mcset zh {Strip Parameters} 
::msgcat::mcset zh {Strip Scale} 
::msgcat::mcset zh {Strip} 
::msgcat::mcset zh {Sum} 
::msgcat::mcset zh {Symbol Editor} 
::msgcat::mcset zh {Symbol} 
::msgcat::mcset zh {TIFF} 
::msgcat::mcset zh {TSV} 
::msgcat::mcset zh {Tab-Separated-Value} 
::msgcat::mcset zh {Table} 
::msgcat::mcset zh {Tabloid} 
::msgcat::mcset zh {Tag Color} 
::msgcat::mcset zh {Template} [encoding convertfrom big5 "\xBC\xCB \xA5\xBB"]
::msgcat::mcset zh {Text} [encoding convertfrom big5 "\xA4\xE5 \xA6\x72"]
::msgcat::mcset zh {Theme} 
::msgcat::mcset zh {Then} 
::msgcat::mcset zh {Thickness} 
::msgcat::mcset zh {This analysis task is already running. Do you wish to kill it?} 
::msgcat::mcset zh {This function is not available.} 
::msgcat::mcset zh {This function is not currently supported for this port.} 
::msgcat::mcset zh {Tickmarks} 
::msgcat::mcset zh {Tile Frames} [encoding convertfrom big5 "\xA6\x58 \xAD\xAB \xBC\x76 \xB9\xB3 \xB5\xF8 \xB5\xA1"]
::msgcat::mcset zh {Tile Parameters} 
::msgcat::mcset zh {Tile} [encoding convertfrom big5 "\xA6\x58 \xAD\xAB"]
::msgcat::mcset zh {Times} 
::msgcat::mcset zh {Titles} 
::msgcat::mcset zh {Title} 
::msgcat::mcset zh {Tophat} 
::msgcat::mcset zh {Topographic} 
::msgcat::mcset zh {Top} 
::msgcat::mcset zh {To} 
::msgcat::mcset zh {Transparency} 
::msgcat::mcset zh {Triangle} 
::msgcat::mcset zh {Type} 
::msgcat::mcset zh {URL} 
::msgcat::mcset zh {Unable to connect directly: using Web Proxy} 
::msgcat::mcset zh {Unable to create FOV Region, celestial WCS Required} 
::msgcat::mcset zh {Unable to determine date of observation} 
::msgcat::mcset zh {Unable to evaluate filter} 
::msgcat::mcset zh {Unable to find Footprint window} 
::msgcat::mcset zh {Unable to find PRISM window} 
::msgcat::mcset zh {Unable to find SIAP window} 
::msgcat::mcset zh {Unable to find URL column} 
::msgcat::mcset zh {Unable to find catalog window} 
::msgcat::mcset zh {Unable to find plot window} 
::msgcat::mcset zh {Unable to find web window} 
::msgcat::mcset zh {Unable to generate plot} 
::msgcat::mcset zh {Unable to load RGB image into a non-rgb frame} 
::msgcat::mcset zh {Unable to load compressed region file} 
::msgcat::mcset zh {Unable to load plot data} 
::msgcat::mcset zh {Unable to load region file} 
::msgcat::mcset zh {Unable to load} 
::msgcat::mcset zh {Unable to locate FOV Region} 
::msgcat::mcset zh {Unable to locate URL} 
::msgcat::mcset zh {Unable to match target with XPA Mime request} 
::msgcat::mcset zh {Unable to open file} 
::msgcat::mcset zh {Unable to save RGB image from a non-rgb frame} 
::msgcat::mcset zh {Undo} 
::msgcat::mcset zh {Unique} 
::msgcat::mcset zh {Unists} 
::msgcat::mcset zh {Units} 
::msgcat::mcset zh {Unknown Colormap} 
::msgcat::mcset zh {Unknown command} 
::msgcat::mcset zh {Update Filter} 
::msgcat::mcset zh {Update Group} 
::msgcat::mcset zh {Update from Current Crosshair} 
::msgcat::mcset zh {Update from Current Frame} 
::msgcat::mcset zh {Update} 
::msgcat::mcset zh {Upper Left Back} 
::msgcat::mcset zh {Upper Left Front} 
::msgcat::mcset zh {Upper Right Back} 
::msgcat::mcset zh {Upper Right Front} 
::msgcat::mcset zh {Use Authentication} 
::msgcat::mcset zh {Use Current Frame on Download} 
::msgcat::mcset zh {Use Internal Web Browser} 
::msgcat::mcset zh {Use Original Color/Width} 
::msgcat::mcset zh {Use Proxy} 
::msgcat::mcset zh {Use Theme Colors} 
::msgcat::mcset zh {Use background color instead of theme color} 
::msgcat::mcset zh {User Manual} 
::msgcat::mcset zh {Username} 
::msgcat::mcset zh {User} 
::msgcat::mcset zh {Use} 
::msgcat::mcset zh {VO Server} 
::msgcat::mcset zh {VOTable} 
::msgcat::mcset zh {VOT} 
::msgcat::mcset zh {VO} 
::msgcat::mcset zh {Value} 
::msgcat::mcset zh {Vector} [encoding convertfrom big5 "\xA6\x56 \xB6\x71"]
::msgcat::mcset zh {Vertical Graph} 
::msgcat::mcset zh {Vertical Layout} 
::msgcat::mcset zh {Vertical Text} 
::msgcat::mcset zh {Vertical} [encoding convertfrom big5 "\xAB\xAB \xAA\xBD"]
::msgcat::mcset zh {View} [encoding convertfrom big5 "\xC0\xCB \xB5\xF8"]
::msgcat::mcset zh {Virtual Observatory} 
::msgcat::mcset zh {WCS Parameters} 
::msgcat::mcset zh {WCS} [encoding convertfrom big5 "\xA7\x79 \xBC\xD0"]
::msgcat::mcset zh {Wavelength} 
::msgcat::mcset zh {Web Browser} 
::msgcat::mcset zh {White} [encoding convertfrom big5 "\xA5\xD5 \xA6\xE2"]
::msgcat::mcset zh {Width} [encoding convertfrom big5 "\xBC\x65 \xAB\xD7"]
::msgcat::mcset zh {Window} 
::msgcat::mcset zh {Words matching title, description} 
::msgcat::mcset zh {X Axis Title} 
::msgcat::mcset zh {X Axis} 
::msgcat::mcset zh {X Column} 
::msgcat::mcset zh {X Error Column} 
::msgcat::mcset zh {XPA Information} 
::msgcat::mcset zh {XPA not initialized} 
::msgcat::mcset zh {XPA} 
::msgcat::mcset zh {X} 
::msgcat::mcset zh {Y Axis Title} 
::msgcat::mcset zh {Y Axis} 
::msgcat::mcset zh {Y Column} 
::msgcat::mcset zh {Y Error Column} 
::msgcat::mcset zh {Yellow} [encoding convertfrom big5 "\xB6\xC0 \xA6\xE2"]
::msgcat::mcset zh {Y} 
::msgcat::mcset zh {Z Axis Scale} 
::msgcat::mcset zh {ZScale Parameters} 
::msgcat::mcset zh {Zero} 
::msgcat::mcset zh {Zoom Fit} 
::msgcat::mcset zh {Zoom In} [encoding convertfrom big5 "\xA9\xF1 \xA4\x6A"]
::msgcat::mcset zh {Zoom Out} [encoding convertfrom big5 "\xC1\x59 \xA4\x70"]
::msgcat::mcset zh {Zoom} [encoding convertfrom big5 "\xC1\x59 \xA9\xF1"]
::msgcat::mcset zh {already connected} 
::msgcat::mcset zh {and} 
::msgcat::mcset zh {b} 
::msgcat::mcset zh {g} 
::msgcat::mcset zh {h5utils} 
::msgcat::mcset zh {hundredths second} 
::msgcat::mcset zh {internal error} 
::msgcat::mcset zh {not connected} 
::msgcat::mcset zh {not} 
::msgcat::mcset zh {only} 
::msgcat::mcset zh {or center of data} 
::msgcat::mcset zh {rows of data have been downloaded. More may be available. You may wish to adjust the maximum allowed} 
::msgcat::mcset zh {r} 
::msgcat::mcset zh {unable to locate HUB} 
::msgcat::mcset zh {x} 
