# -*- tcl -*-
namespace eval ::widget::listentry {
    msgcat::mcset de wle.add             Hinzufuegen
    msgcat::mcset de wle.remove          Entfernen
    msgcat::mcset de wle.up              Rauf
    msgcat::mcset de wle.down            Runter
    msgcat::mcset de wle.browse          Suche...
    msgcat::mcset de wle.tip.add         {Fuege neues Element in die Liste ein}
    msgcat::mcset de wle.tip.remove      {Entferne die ausgewaehlten Elemente aus der Liste}
    msgcat::mcset de wle.tip.up          {Schiebe die ausgewaehlten Elemente hoch}
    msgcat::mcset de wle.tip.down        {Schiebe die ausgewaehlten Elemente runter}
    msgcat::mcset de wle.tip.browse      {Suche nach neuen Elementen}
    msgcat::mcset de wle.tip.main        {Liste}
    msgcat::mcset de wle.tip.entry       {Eingabefeld fuer neues Element}
    msgcat::mcset de wle.tip.list        {Liste}
    msgcat::mcset de wle.tip.empty       Leer
    msgcat::mcset de wle.tip.dup         {Die Liste enthaelt dieses Element bereits}
    msgcat::mcset de wle.tip.add-none    {Nichts vorhanden zum Hinzufuegen}
    msgcat::mcset de wle.tip.remove-none {Keine Elemente zum Entfernen ausgewaehlt}
}
