package provide DS9 1.0

######
# Begin autogenerated taccle (version 1.3) routines.
# Although taccle itself is protected by the GNU Public License (GPL)
# all user-supplied functions are protected by their respective
# author's license.  See http://mini.net/tcl/taccle for other details.
######

namespace eval colorbarsend {
    variable yylval {}
    variable table
    variable rules
    variable token {}
    variable yycnt 0
    variable yyerr 0
    variable save_state 0

    namespace export yylex
}

proc colorbarsend::YYABORT {} {
    return -code return 1
}

proc colorbarsend::YYACCEPT {} {
    return -code return 0
}

proc colorbarsend::YYERROR {} {
    variable yyerr
    set yyerr 1
}

proc colorbarsend::yyclearin {} {
    variable token
    variable yycnt
    set token {}
    incr yycnt -1
}

proc colorbarsend::yyerror {s} {
    puts stderr $s
}

proc colorbarsend::setupvalues {stack pointer numsyms} {
    upvar 1 1 y
    set y {}
    for {set i 1} {$i <= $numsyms} {incr i} {
        upvar 1 $i y
        set y [lindex $stack $pointer]
        incr pointer
    }
}

proc colorbarsend::unsetupvalues {numsyms} {
    for {set i 1} {$i <= $numsyms} {incr i} {
        upvar 1 $i y
        unset y
    }
}

array set colorbarsend::table {
  0:257 shift
  0:258 shift
  5:0,target 13
  0:259 shift
  0:260 shift
  15:0,target 18
  9:0 reduce
  0:266,target 10
  0:261 shift
  11:0 reduce
  0:276,target 19
  0:262 shift
  0:263 shift
  0:264 shift
  0:265 shift
  15:0 reduce
  0:266 shift
  0:267 shift
  0:265,target 9
  0:268 shift
  6:0,target 16
  0:269 shift
  0:270 shift
  0:275,target 18
  20:0 reduce
  19:0 accept
  16:0,target 19
  0:271 shift
  2:0 reduce
  0:273 shift
  0:274 shift
  6:0 reduce
  0:275 shift
  0:264,target 8
  0:276 goto
  0:274,target 17
  17:0,target 10
  12:0 reduce
  0:0,target 1
  10:0,target 4
  0:263,target 7
  16:0 reduce
  0:273,target 16
  8:0,target 2
  3:0 reduce
  18:0,target 9
  1:0,target 11
  11:0,target 5
  0:262,target 6
  13:0 reduce
  9:0,target 7
  0:261,target 5
  20:0,target 6
  19:0,target 0
  0:271,target 15
  2:0,target 12
  12:0,target 17
  17:0 reduce
  0:0 reduce
  7:267,target 20
  0:259,target 3
  0:260,target 4
  0:269,target 13
  0:270,target 14
  4:0 reduce
  7:267 shift
  3:0,target 14
  13:0,target 3
  8:0 reduce
  10:0 reduce
  0:258,target 2
  0:268,target 12
  14:0 reduce
  4:0,target 15
  14:0,target 8
  18:0 reduce
  0:257,target 1
  1:0 reduce
  0:267,target 11
  5:0 reduce
}

array set colorbarsend::rules {
  9,l 276
  11,l 276
  15,l 276
  19,l 276
  2,l 276
  6,l 276
  12,l 276
  16,l 276
  3,l 276
  7,l 276
  13,l 276
  0,l 277
  17,l 276
  4,l 276
  8,l 276
  10,l 276
  14,l 276
  18,l 276
  1,l 276
  5,l 276
}

array set colorbarsend::rules {
  5,dc 1
  0,dc 1
  17,dc 1
  12,dc 1
  8,dc 1
  3,dc 1
  15,dc 1
  10,dc 1
  6,dc 2
  18,dc 1
  1,dc 0
  13,dc 1
  9,dc 1
  4,dc 1
  16,dc 1
  11,dc 1
  7,dc 1
  19,dc 1
  2,dc 1
  14,dc 1
}

array set colorbarsend::rules {
  13,line 45
  7,line 39
  10,line 42
  4,line 36
  18,line 51
  1,line 33
  15,line 48
  9,line 41
  12,line 44
  6,line 38
  3,line 35
  17,line 50
  14,line 47
  8,line 40
  11,line 43
  5,line 37
  19,line 52
  2,line 34
  16,line 49
}

array set colorbarsend::lr1_table {
  13,trans {}
  17 {{10 0 1}}
  0 {{0 0 0} {1 0 0} {2 0 0} {3 0 0} {4 0 0} {5 0 0} {6 0 0} {7 0 0} {8 0 0} {9 0 0} {10 0 0} {11 0 0} {12 0 0} {13 0 0} {14 0 0} {15 0 0} {16 0 0} {17 0 0} {18 0 0} {19 0 0}}
  14,trans {}
  18 {{9 0 1}}
  1 {{11 0 1}}
  15,trans {}
  20 {{6 0 2}}
  19 {{0 0 1}}
  2 {{12 0 1}}
  16,trans {}
  3 {{14 0 1}}
  17,trans {}
  0,trans {{257 1} {258 2} {259 3} {260 4} {261 5} {262 6} {263 7} {264 8} {265 9} {266 10} {267 11} {268 12} {269 13} {270 14} {271 15} {273 16} {274 17} {275 18} {276 19}}
  4 {{15 0 1}}
  18,trans {}
  1,trans {}
  5 {{13 0 1}}
  20,trans {}
  19,trans {}
  2,trans {}
  6 {{16 0 1}}
  3,trans {}
  7 {{6 0 1}}
  4,trans {}
  8 {{2 0 1}}
  5,trans {}
  9 {{7 0 1}}
  10 {{4 0 1}}
  6,trans {}
  11 {{5 0 1}}
  7,trans {{267 20}}
  12 {{17 0 1}}
  8,trans {}
  13 {{3 0 1}}
  10,trans {}
  9,trans {}
  14 {{8 0 1}}
  11,trans {}
  15 {{18 0 1}}
  12,trans {}
  16 {{19 0 1}}
}

array set colorbarsend::token_id_table {
  264,line 17
  270,t 0
  269,t 0
  276,line 32
  265,title NUMERICS
  274,t 0
  261,line 11
  257,t 0
  270,title SPACE
  269,title SHOW
  273,line 26
  257,line 7
  262,t 0
  274,title BACKGROUND
  270,line 23
  269,line 22
  259,title FONTSLANT
  260,title FONTSTYLE
  266,t 0
  error error
  271,t 0
  264,title LOCK
  266,line 19
  error,line 31
  275,t 0
  268,title SIZE
  258,t 0
  263,line 16
  error,title {}
  275,line 28
  273,title WIDTH
  263,t 0
  259,line 9
  260,line 10
  258,title FONTSIZE
  277,title {}
  272,line 25
  267,t 0
  263,title LABEL
  272,t 0
  268,line 21
  267,title POSITION
  257 FONT_
  276,t 1
  258 FONTSIZE_
  259,t 0
  259 FONTSLANT_
  260 FONTSTYLE_
  260,t 0
  272,title VALUE
  261 FONTWEIGHT_
  265,line 18
  262 CENTER_
  263 LABEL_
  277,line 53
  257,title FONT
  264 LOCK_
  264,t 0
  276,title {}
  265 NUMERICS_
  262,line 15
  266 ORIENTATION_
  267 POSITION_
  0,t 0
  0 {$}
  262,title CENTER
  268 SIZE_
  268,t 0
  274,line 27
  270 SPACE_
  269 SHOW_
  error,t 0
  271 TICKS_
  272 VALUE_
  258,line 8
  273,t 0
  273 WIDTH_
  266,title ORIENTATION
  274 BACKGROUND_
  275 FOREGROUND_
  271,line 24
  276 colorbarsend
  277,t 1
  277 start'
  271,title TICKS
  261,t 0
  267,line 20
  275,title FOREGROUND
  265,t 0
  261,title FONTWEIGHT
}

proc colorbarsend::yyparse {} {
    variable yylval
    variable table
    variable rules
    variable token
    variable yycnt
    variable lr1_table
    variable token_id_table
    variable yyerr
    variable save_state

    set yycnt 0
    set state_stack {0}
    set value_stack {{}}
    set token ""
    set accepted 0
    set yyerr 0
    set save_state 0

    while {$accepted == 0} {
        set state [lindex $state_stack end]
        if {$token == ""} {
            set yylval ""
            set token [yylex]
            set buflval $yylval
	    if {$token>0} {
	        incr yycnt
            }
        }
        if {![info exists table($state:$token)] || $yyerr} {
	    if {!$yyerr} {
	        set save_state $state
	    }
            # pop off states until error token accepted
            while {[llength $state_stack] > 0 && \
                       ![info exists table($state:error)]} {
                set state_stack [lrange $state_stack 0 end-1]
                set value_stack [lrange $value_stack 0 \
                                       [expr {[llength $state_stack] - 1}]]
                set state [lindex $state_stack end]
            }
            if {[llength $state_stack] == 0} {
 
	        set rr { }
                if {[info exists lr1_table($save_state,trans)] && [llength $lr1_table($save_state,trans)] >= 1} {
                    foreach trans $lr1_table($save_state,trans) {
                        foreach {tok_id nextstate} $trans {
			    set ss $token_id_table($tok_id,title)
			    if {$ss != {}} {
			        append rr "$ss, "
                            }
                        }
                    }
                }
		set rr [string trimleft $rr { }]
		set rr [string trimright $rr {, }]
                yyerror "parse error, expecting: $rr"


                return 1
            }
            lappend state_stack [set state $table($state:error,target)]
            lappend value_stack {}
            # consume tokens until it finds an acceptable one
            while {![info exists table($state:$token)]} {
                if {$token == 0} {
                    yyerror "end of file while recovering from error"
                    return 1
                }
                set yylval {}
                set token [yylex]
                set buflval $yylval
            }
            continue
        }
        switch -- $table($state:$token) {
            shift {
                lappend state_stack $table($state:$token,target)
                lappend value_stack $buflval
                set token ""
            }
            reduce {
                set rule $table($state:$token,target)
                set ll $rules($rule,l)
                if {[info exists rules($rule,e)]} {
                    set dc $rules($rule,e)
                } else {
                    set dc $rules($rule,dc)
                }
                set stackpointer [expr {[llength $state_stack]-$dc}]
                setupvalues $value_stack $stackpointer $dc
                set _ $1
                set yylval [lindex $value_stack end]
                switch -- $rule {
                    1 { ProcessSendCmdYesNo view colorbar }
                    2 { ProcessSendCmdYesNo colorbar lock }
                    3 { ProcessSendCmdYesNo colorbar show }
                    4 { ColorbarSendCmdOrientation }
                    5 { ColorbarSendCmdPosition }
                    6 { ColorbarSendCmdLabelPosition }
                    7 { ProcessSendCmdYesNo colorbar numerics }
                    8 { ColorbarSendCmdSpace }
                    9 { ProcessSendCmdGet colorbar foreground }
                    10 { ProcessSendCmdGet colorbar background }
                    11 { ProcessSendCmdGet colorbar font }
                    12 { ProcessSendCmdGet colorbar font,size }
                    13 { ProcessSendCmdGet colorbar font,weight }
                    14 { ProcessSendCmdGet colorbar font,slant }
                    15 { ProcessSendCmdGet colorbar font,weight }
                    16 { ProcessSendCmdGet colorbar center }
                    17 { ProcessSendCmdGet colorbar size }
                    18 { ProcessSendCmdGet colorbar ticks }
                    19 { ProcessSendCmdGet colorbar width }
                }
                unsetupvalues $dc
                # pop off tokens from the stack if normal rule
                if {![info exists rules($rule,e)]} {
                    incr stackpointer -1
                    set state_stack [lrange $state_stack 0 $stackpointer]
                    set value_stack [lrange $value_stack 0 $stackpointer]
                }
                # now do the goto transition
                lappend state_stack $table([lindex $state_stack end]:$ll,target)
                lappend value_stack $_
            }
            accept {
                set accepted 1
            }
            goto -
            default {
                puts stderr "Internal parser error: illegal command $table($state:$token)"
                return 2
            }
        }
    }
    return 0
}

######
# end autogenerated taccle functions
######

proc colorbarsend::yyerror {msg} {
     variable yycnt
     variable yy_current_buffer
     variable index_

     ParserError $msg $yycnt $yy_current_buffer $index_
}
