package provide DS9 1.0

######
# Begin autogenerated taccle (version 1.3) routines.
# Although taccle itself is protected by the GNU Public License (GPL)
# all user-supplied functions are protected by their respective
# author's license.  See http://mini.net/tcl/taccle for other details.
######

namespace eval illustrate {
    variable yylval {}
    variable table
    variable rules
    variable token {}
    variable yycnt 0
    variable yyerr 0
    variable save_state 0

    namespace export yylex
}

proc illustrate::YYABORT {} {
    return -code return 1
}

proc illustrate::YYACCEPT {} {
    return -code return 0
}

proc illustrate::YYERROR {} {
    variable yyerr
    set yyerr 1
}

proc illustrate::yyclearin {} {
    variable token
    variable yycnt
    set token {}
    incr yycnt -1
}

proc illustrate::yyerror {s} {
    puts stderr $s
}

proc illustrate::setupvalues {stack pointer numsyms} {
    upvar 1 1 y
    set y {}
    for {set i 1} {$i <= $numsyms} {incr i} {
        upvar 1 $i y
        set y [lindex $stack $pointer]
        incr pointer
    }
}

proc illustrate::unsetupvalues {numsyms} {
    for {set i 1} {$i <= $numsyms} {incr i} {
        upvar 1 $i y
        unset y
    }
}

array set illustrate::table {
  30:281 reduce
  29:281 reduce
  13:322,target 47
  68:281 reduce
  38:281,target 12
  27:0 reduce
  12:312 goto
  48:0 reduce
  20:304,target 68
  14:274,target 39
  38:281 reduce
  21:277,target 42
  70:0 reduce
  69:0 reduce
  27:281,target 3
  73:281,target 40
  21:312 goto
  2:0 reduce
  72:0,target 24
  64:0,target 55
  16:281,target 53
  62:281,target 57
  56:0,target 33
  47:281 reduce
  24:0 reduce
  48:0,target 26
  41:0,target 16
  45:0 reduce
  33:0,target 4
  22:279,target 74
  25:0,target 1
  0:294,target 17
  20:302,target 66
  66:0 reduce
  51:281,target 63
  21:275,target 40
  17:283 shift
  56:281 reduce
  6:279 shift
  17:283,target 54
  40:281,target 13
  39:281,target 15
  26:281 reduce
  21:0 reduce
  17:290 shift
  65:281 reduce
  42:0 reduce
  7:310,target 32
  28:281,target 29
  0:292,target 15
  19:290,target 62
  74:281,target 27
  63:0 reduce
  24:315,target 75
  21:273,target 38
  35:281 reduce
  74:281 reduce
  63:281,target 56
  14:273 shift
  14:274 shift
  44:281 reduce
  38:0 reduce
  14:275 shift
  14:276 shift
  17:318 goto
  52:281,target 36
  14:277 shift
  60:0 reduce
  59:0 reduce
  0:300,target 21
  0:289,target 14
  3:0,target 45
  14:278 shift
  76:0,target 22
  14:281 reduce
  68:0,target 48
  61:0,target 58
  53:281 reduce
  53:0,target 39
  41:281,target 16
  45:0,target 68
  37:0,target 41
  14:0 reduce
  30:0,target 6
  29:0,target 30
  3:281 reduce
  5:267,target 26
  8:309,target 35
  35:0 reduce
  14:0,target 11
  30:281,target 6
  29:281,target 30
  75:281,target 76
  62:281 reduce
  56:0 reduce
  13:282,target 45
  0:287,target 12
  0:257 shift
  12:277,target 42
  0:258 shift
  18:281,target 59
  64:281,target 55
  32:281 reduce
  0:260 shift
  0:259 shift
  0:261 shift
  9:0 reduce
  0:262 shift
  71:281 reduce
  0:263 shift
  14:312 goto
  32:0 reduce
  0:265 shift
  0:316,target 24
  53:281,target 39
  9:281,target 38
  53:0 reduce
  41:281 reduce
  0:285,target 10
  19:283,target 61
  74:0 reduce
  42:281,target 14
  12:275,target 40
  7:272,target 31
  11:281 shift
  50:281 reduce
  49:281 reduce
  8:269 shift
  8:270 shift
  31:281,target 7
  28:0 reduce
  13:298,target 46
  0:314,target 23
  0:0,target 23
  0:281 shift
  73:0,target 40
  50:0 reduce
  49:0 reduce
  65:0,target 34
  19:282 shift
  57:0,target 61
  0:285 shift
  19:283 shift
  71:0 reduce
  58:281 reduce
  50:0,target 65
  49:0,target 64
  0:286 shift
  65:281,target 34
  42:0,target 14
  0:287 shift
  34:0,target 5
  0:288 shift
  12:273,target 38
  26:0,target 2
  0:300 shift
  0:289 shift
  3:0 reduce
  0:301 shift
  18:0,target 59
  28:281 reduce
  0:292 shift
  0:262,target 6
  19:290 shift
  0:293 shift
  19:291 shift
  54:281,target 53
  25:0 reduce
  0:294 shift
  15:284,target 50
  20:302 shift
  67:281 reduce
  20:303 shift
  20:304 shift
  46:0 reduce
  20:305 shift
  0:297 shift
  19:295 shift
  20:306 shift
  0:298 shift
  20:307 shift
  0:299 shift
  67:0 reduce
  43:281,target 17
  37:281 reduce
  0:281,target 9
  0:314 goto
  0:0 reduce
  0:316 goto
  32:281,target 32
  0:260,target 4
  0:259,target 3
  5:266 shift
  21:312,target 73
  5:267 shift
  8:309 goto
  46:281 reduce
  5:268 shift
  15:282,target 49
  20:317 goto
  43:0 reduce
  20:307,target 71
  0:299,target 20
  19:319 goto
  14:277,target 42
  21:281,target 11
  66:281,target 46
  64:0 reduce
  16:281 shift
  5:308,target 28
  8:269,target 33
  8:270,target 34
  55:281 reduce
  4:0,target 42
  10:281,target 36
  55:281,target 52
  0:257,target 1
  18:0 reduce
  70:0,target 50
  69:0,target 49
  25:281 reduce
  62:0,target 57
  54:0,target 53
  40:0 reduce
  39:0 reduce
  64:281 reduce
  46:0,target 67
  20:305,target 69
  0:297,target 18
  19:295,target 64
  44:281,target 28
  38:0,target 12
  14:275,target 40
  61:0 reduce
  31:0,target 7
  21:278,target 43
  1:281,target 43
  23:0,target 0
  15:0,target 62
  34:281 reduce
  6:279,target 29
  33:281,target 4
  15:298,target 51
  73:281 reduce
  15:0 reduce
  5:308 goto
  36:0 reduce
  18:320,target 59
  43:281 reduce
  67:281,target 47
  20:303,target 67
  57:0 reduce
  14:273,target 38
  21:276,target 41
  13:281 reduce
  11:281,target 37
  13:282 shift
  56:281,target 33
  52:281 reduce
  12:0 reduce
  2:281 reduce
  33:0 reduce
  22:279 shift
  45:281,target 68
  2:281,target 44
  54:0 reduce
  0:293,target 16
  19:291,target 63
  61:281 reduce
  21:274,target 39
  1:0,target 43
  34:281,target 5
  74:0,target 27
  66:0,target 46
  31:281 reduce
  13:298 shift
  58:0,target 60
  51:0,target 63
  70:281 reduce
  69:281 reduce
  43:0,target 17
  19:319,target 65
  35:0,target 31
  30:0 reduce
  29:0 reduce
  68:281,target 48
  27:0,target 3
  12:312,target 44
  51:0 reduce
  12:0,target 11
  40:281 reduce
  39:281 reduce
  0:301,target 22
  72:0 reduce
  12:281,target 11
  57:281,target 61
  13:322 goto
  4:0 reduce
  10:281 shift
  48:281 reduce
  46:281,target 67
  26:0 reduce
  5:268,target 27
  20:317,target 72
  3:281,target 45
  7:271 shift
  7:272 shift
  47:0 reduce
  18:281 reduce
  0:288,target 13
  18:282 shift
  68:0 reduce
  35:281,target 31
  57:281 reduce
  12:278,target 43
  15:321,target 52
  18:282,target 57
  1:0 reduce
  27:281 reduce
  24:281,target 21
  70:281,target 50
  69:281,target 49
  23:0 accept
  5:266,target 25
  66:281 reduce
  44:0 reduce
  13:281,target 66
  71:0,target 51
  65:0 reduce
  58:281,target 60
  0:286,target 11
  63:0,target 56
  36:281 reduce
  18:298 shift
  55:0,target 52
  12:276,target 41
  47:0,target 37
  75:281 shift
  40:0,target 13
  39:0,target 15
  32:0,target 32
  0:265,target 8
  47:281,target 37
  24:0,target 20
  4:281,target 42
  7:310 goto
  45:281 reduce
  41:0 reduce
  18:320 goto
  36:281,target 25
  18:298,target 58
  62:0 reduce
  15:281 reduce
  19:282,target 60
  15:282 shift
  12:274,target 39
  54:281 reduce
  7:271,target 30
  15:284 shift
  25:281,target 1
  71:281,target 51
  0:263,target 7
  14:312,target 48
  4:281 reduce
  24:281 reduce
  37:0 reduce
  14:281,target 11
  63:281 reduce
  60:281,target 54
  59:281,target 35
  58:0 reduce
  33:281 reduce
  15:298 shift
  48:281,target 26
  72:281 reduce
  0:261,target 5
  9:0,target 38
  13:0 reduce
  2:0,target 44
  34:0 reduce
  12:273 shift
  67:0,target 47
  37:281,target 41
  12:274 shift
  60:0,target 54
  59:0,target 35
  42:281 reduce
  12:275 shift
  14:278,target 43
  55:0 reduce
  52:0,target 36
  12:276 shift
  44:0,target 28
  12:277 shift
  36:0,target 25
  12:278 shift
  15:321 goto
  76:0 reduce
  28:0,target 29
  26:281,target 2
  21:0,target 11
  12:281 reduce
  17:290,target 55
  72:281,target 24
  24:315 goto
  21:273 shift
  13:0,target 66
  21:274 shift
  51:281 reduce
  21:275 shift
  21:276 shift
  0:258,target 2
  21:277 shift
  31:0 reduce
  21:278 shift
  1:281 reduce
  15:281,target 62
  61:281,target 58
  21:281 reduce
  20:306,target 70
  0:298,target 19
  52:0 reduce
  14:276,target 41
  17:318,target 56
  60:281 reduce
  59:281 reduce
  73:0 reduce
  50:281,target 65
  49:281,target 64
  9:281 reduce
}

array set illustrate::rules {
  9,l 311
  11,l 312
  32,l 316
  53,l 318
  6,l 310
  28,l 316
  50,l 317
  49,l 317
  3,l 308
  25,l 316
  46,l 317
  67,l 322
  0,l 323
  22,l 314
  43,l 316
  64,l 321
  18,l 313
  40,l 316
  39,l 316
  61,l 320
  15,l 312
  36,l 316
  57,l 319
  12,l 312
  33,l 316
  54,l 319
  7,l 310
  29,l 316
  30,l 316
  51,l 317
  4,l 309
  26,l 316
  47,l 317
  68,l 322
  1,l 308
  23,l 316
  44,l 316
  65,l 321
  19,l 313
  20,l 314
  41,l 316
  62,l 321
  16,l 312
  37,l 316
  58,l 319
  13,l 312
  34,l 316
  55,l 319
  8,l 311
  10,l 311
  31,l 316
  52,l 318
  5,l 309
  27,l 316
  48,l 317
  2,l 308
  24,l 316
  45,l 316
  66,l 322
  21,l 315
  42,l 316
  63,l 321
  17,l 312
  38,l 316
  60,l 320
  59,l 320
  14,l 312
  35,l 316
  56,l 319
}

array set illustrate::rules {
  63,dc 1
  12,dc 1
  26,dc 2
  3,dc 1
  41,dc 2
  55,dc 1
  18,dc 1
  33,dc 2
  9,dc 1
  47,dc 1
  62,dc 0
  11,dc 0
  25,dc 2
  2,dc 1
  40,dc 2
  39,dc 2
  54,dc 1
  68,dc 1
  17,dc 1
  32,dc 2
  8,dc 1
  46,dc 1
  61,dc 1
  10,dc 1
  24,dc 2
  1,dc 1
  38,dc 1
  53,dc 1
  67,dc 1
  16,dc 1
  31,dc 2
  7,dc 1
  45,dc 1
  60,dc 1
  59,dc 0
  23,dc 0
  0,dc 1
  37,dc 2
  52,dc 1
  66,dc 0
  15,dc 1
  29,dc 2
  30,dc 2
  6,dc 1
  44,dc 1
  58,dc 1
  22,dc 3
  36,dc 2
  51,dc 1
  65,dc 1
  14,dc 1
  28,dc 2
  5,dc 1
  43,dc 1
  57,dc 1
  21,dc 0
  35,dc 2
  50,dc 1
  49,dc 1
  64,dc 1
  13,dc 1
  27,dc 2
  4,dc 1
  42,dc 1
  56,dc 1
  19,dc 1
  20,dc 1
  34,dc 2
  48,dc 1
}

array set illustrate::rules {
  41,line 157
  7,line 110
  37,line 152
  4,line 105
  34,line 149
  1,line 100
  31,line 144
  27,line 138
  24,line 135
  21,line 130
  17,line 124
  14,line 121
  11,line 118
  66,line 194
  63,line 189
  60,line 184
  59,line 183
  56,line 178
  53,line 173
  50,line 168
  49,line 167
  46,line 164
  43,line 159
  9,line 114
  40,line 155
  39,line 154
  6,line 109
  36,line 151
  3,line 102
  33,line 148
  29,line 140
  30,line 142
  26,line 137
  23,line 134
  19,line 127
  20,line 130
  16,line 123
  13,line 120
  68,line 196
  10,line 115
  65,line 191
  62,line 188
  58,line 180
  55,line 177
  52,line 172
  48,line 166
  45,line 161
  42,line 158
  8,line 113
  38,line 153
  5,line 106
  35,line 150
  2,line 101
  32,line 147
  28,line 139
  25,line 136
  22,line 131
  18,line 126
  15,line 122
  21,e 1
  12,line 119
  67,line 195
  64,line 190
  61,line 185
  57,line 179
  54,line 176
  51,line 169
  47,line 165
  44,line 160
}

array set illustrate::lr1_table {
  66,trans {}
  35 {{31 {0 281} 2}}
  14,trans {{273 38} {274 39} {275 40} {276 41} {277 42} {278 43} {312 48}}
  36 {{25 {0 281} 2}}
  33,trans {}
  37 {{41 {0 281} 2}}
  52,trans {}
  38 {{12 {0 281} 1}}
  71,trans {}
  40 {{13 {0 281} 1}}
  39 {{15 {0 281} 1}}
  18,trans {{282 57} {298 58} {320 59}}
  41 {{16 {0 281} 1}}
  1,trans {}
  37,trans {}
  42 {{14 {0 281} 1}}
  56,trans {}
  43 {{17 {0 281} 1}}
  75,trans {{281 76}}
  44 {{28 {0 281} 2}}
  23,trans {}
  45 {{68 {0 281} 1}}
  5,trans {{266 25} {267 26} {268 27} {308 28}}
  42,trans {}
  46 {{67 {0 281} 1}}
  61,trans {}
  47 {{37 {0 281} 2}}
  48 {{26 {0 281} 2}}
  27,trans {}
  50 {{65 {0 281} 1}}
  49 {{64 {0 281} 1}}
  9,trans {}
  46,trans {}
  51 {{63 {0 281} 1}}
  65,trans {}
  52 {{36 {0 281} 2}}
  53 {{39 {0 281} 2}}
  13,trans {{282 45} {298 46} {322 47}}
  32,trans {}
  54 {{53 {0 281} 1}}
  51,trans {}
  55 {{52 {0 281} 1}}
  70,trans {}
  69,trans {}
  56 {{33 {0 281} 2}}
  57 {{61 {0 281} 1}}
  17,trans {{283 54} {290 55} {318 56}}
  0,trans {{257 1} {258 2} {259 3} {260 4} {261 5} {262 6} {263 7} {265 8} {281 9} {285 10} {286 11} {287 12} {288 13} {289 14} {292 15} {293 16} {294 17} {297 18} {298 19} {299 20} {300 21} {301 22} {314 23} {316 24}}
  36,trans {}
  58 {{60 {0 281} 1}}
  55,trans {}
  60 {{54 {0 281} 1}}
  59 {{35 {0 281} 2}}
  74,trans {}
  61 {{58 {0 281} 1}}
  22,trans {{279 74}}
  62 {{57 {0 281} 1}}
  4,trans {}
  41,trans {}
  63 {{56 {0 281} 1}}
  60,trans {}
  59,trans {}
  64 {{55 {0 281} 1}}
  65 {{34 {0 281} 2}}
  26,trans {}
  66 {{46 {0 281} 1}}
  8,trans {{269 33} {270 34} {309 35}}
  45,trans {}
  67 {{47 {0 281} 1}}
  64,trans {}
  68 {{48 {0 281} 1}}
  70 {{50 {0 281} 1}}
  69 {{49 {0 281} 1}}
  12,trans {{273 38} {274 39} {275 40} {276 41} {277 42} {278 43} {312 44}}
  31,trans {}
  71 {{51 {0 281} 1}}
  50,trans {}
  49,trans {}
  72 {{24 {0 281} 2}}
  68,trans {}
  73 {{40 {0 281} 2}}
  74 {{27 {0 281} 2}}
  16,trans {{281 53}}
  35,trans {}
  75 {{22 0 2}}
  76 {{22 0 3}}
  54,trans {}
  73,trans {}
  21,trans {{273 38} {274 39} {275 40} {276 41} {277 42} {278 43} {312 73}}
  3,trans {}
  40,trans {}
  39,trans {}
  58,trans {}
  10 {{25 {0 281} 1}}
  11 {{41 {0 281} 1}}
  25,trans {}
  12 {{28 {0 281} 1} {11 {0 281} 0} {12 {0 281} 0} {13 {0 281} 0} {14 {0 281} 0} {15 {0 281} 0} {16 {0 281} 0} {17 {0 281} 0}}
  7,trans {{271 30} {272 31} {310 32}}
  44,trans {}
  13 {{37 {0 281} 1} {66 {0 281} 0} {67 {0 281} 0} {68 {0 281} 0}}
  63,trans {}
  14 {{26 {0 281} 1} {11 {0 281} 0} {12 {0 281} 0} {13 {0 281} 0} {14 {0 281} 0} {15 {0 281} 0} {16 {0 281} 0} {17 {0 281} 0}}
  11,trans {{281 37}}
  15 {{36 {0 281} 1} {62 {0 281} 0} {63 {0 281} 0} {64 {0 281} 0} {65 {0 281} 0}}
  30,trans {}
  29,trans {}
  16 {{39 {0 281} 1}}
  48,trans {}
  0 {{0 0 0} {20 0 0} {22 0 0} {23 {0 281} 0} {24 {0 281} 0} {25 {0 281} 0} {26 {0 281} 0} {27 {0 281} 0} {28 {0 281} 0} {29 {0 281} 0} {30 {0 281} 0} {31 {0 281} 0} {32 {0 281} 0} {33 {0 281} 0} {34 {0 281} 0} {35 {0 281} 0} {36 {0 281} 0} {37 {0 281} 0} {38 {0 281} 0} {39 {0 281} 0} {40 {0 281} 0} {41 {0 281} 0} {42 {0 281} 0} {43 {0 281} 0} {44 {0 281} 0} {45 {0 281} 0}}
  17 {{33 {0 281} 1} {52 {0 281} 0} {53 {0 281} 0}}
  67,trans {}
  1 {{43 {0 281} 1}}
  18 {{35 {0 281} 1} {59 {0 281} 0} {60 {0 281} 0} {61 {0 281} 0}}
  15,trans {{282 49} {284 50} {298 51} {321 52}}
  2 {{44 {0 281} 1}}
  19 {{34 {0 281} 1} {54 {0 281} 0} {55 {0 281} 0} {56 {0 281} 0} {57 {0 281} 0} {58 {0 281} 0}}
  20 {{24 {0 281} 1} {46 {0 281} 0} {47 {0 281} 0} {48 {0 281} 0} {49 {0 281} 0} {50 {0 281} 0} {51 {0 281} 0}}
  34,trans {}
  3 {{45 {0 281} 1}}
  21 {{40 {0 281} 1} {11 {0 281} 0} {12 {0 281} 0} {13 {0 281} 0} {14 {0 281} 0} {15 {0 281} 0} {16 {0 281} 0} {17 {0 281} 0}}
  53,trans {}
  4 {{42 {0 281} 1}}
  22 {{27 {0 281} 1}}
  72,trans {}
  5 {{29 {0 281} 1} {1 {0 281} 0} {2 {0 281} 0} {3 {0 281} 0}}
  23 {{0 0 1}}
  20,trans {{302 66} {303 67} {304 68} {305 69} {306 70} {307 71} {317 72}}
  19,trans {{282 60} {283 61} {290 62} {291 63} {295 64} {319 65}}
  6 {{30 {0 281} 1}}
  24 {{20 0 1} {22 0 1} {21 281 0}}
  2,trans {}
  38,trans {}
  7 {{32 {0 281} 1} {6 {0 281} 0} {7 {0 281} 0}}
  25 {{1 {0 281} 1}}
  57,trans {}
  8 {{31 {0 281} 1} {4 {0 281} 0} {5 {0 281} 0}}
  26 {{2 {0 281} 1}}
  76,trans {}
  9 {{38 {0 281} 1}}
  27 {{3 {0 281} 1}}
  24,trans {{315 75}}
  28 {{29 {0 281} 2}}
  6,trans {{279 29}}
  43,trans {}
  29 {{30 {0 281} 2}}
  30 {{6 {0 281} 1}}
  62,trans {}
  31 {{7 {0 281} 1}}
  32 {{32 {0 281} 2}}
  10,trans {{281 36}}
  28,trans {}
  33 {{4 {0 281} 1}}
  47,trans {}
  34 {{5 {0 281} 1}}
}

array set illustrate::token_id_table {
  286 COMMAND_
  286,t 0
  287 DASH_
  292,line 49
  302,line 61
  288 DELETE_
  317,t 1
  265,title FONTWEIGHT
  289 FILL_
  290 FRONT_
  300 SHOW_
  284,title CLOSE
  291 INVERT_
  301 WIDTH_
  313,title {}
  292 LIST_
  302 CIRCLE_
  288,line 45
  293 LOAD_
  303 ELLIPSE_
  294 MOVE_
  304 BOX_
  305 POLYGON_
  295 NONE_
  306 LINE_
  296 OPEN_
  307 TEXT_
  262,t 0
  297 SAVE_
  308 font
  285,line 42
  298 SELECT_
  310 fontSlant
  309 fontWeight
  299 SHAPE_
  311 fontStyle
  283,t 0
  312 yesno
  313 numeric
  314,t 1
  314 command
  282,line 39
  315 @PSEUDO1
  316 illustrate
  264,title FONTSTYLE
  317 shape
  283,title BACK
  318 move
  312,title {}
  320 save
  319 select
  278,line 30
  321 list
  error,line 98
  322 delete
  258,t 0
  323 start'
  275,line 27
  279,t 0
  280,t 0
  311,t 1
  272,line 23
  263,title FONTSLANT
  282,title ALL
  311,title {}
  268,line 19
  276,t 0
  265,line 16
  307,t 0
  297,t 0
  262,line 13
  0,t 0
  0 {$}
  262,title FONTSIZE
  281,title string
  310,title {}
  309,title {}
  error,t 0
  299,title SHAPE
  258,line 8
  273,t 0
  294,t 0
  304,t 0
  321,line 187
  317,line 163
  261,title FONT
  279,title integer
  280,title float
  308,title {}
  269,t 0
  270,t 0
  298,title SELECT
  314,line 129
  291,t 0
  301,t 0
  322,t 1
  311,line 112
  307,line 66
  266,t 0
  260,title UNDO
  259,title PASTE
  297,line 55
  278,title FALSE
  307,title TEXT
  297,title SAVE
  287,t 0
  294,line 51
  304,line 63
  318,t 1
  error,title {}
  291,line 48
  301,line 59
  263,t 0
  258,title COPY
  287,line 44
  277,title TRUE
  284,t 0
  306,title LINE
  296,title OPEN
  315,t 1
  284,line 41
  281,line 35
  260,t 0
  259,t 0
  281,t 0
  257,title CUT
  277,line 29
  276,title OFF
  312,t 1
  305,title POLYGON
  295,title NONE
  274,line 26
  271,line 22
  277,t 0
  308,t 1
  267,line 18
  298,t 0
  275,title ON
  294,title MOVE
  304,title BOX
  323,title {}
  264,line 15
  261,line 12
  274,t 0
  305,t 0
  295,t 0
  257,line 7
  274,title NO
  323,line 197
  293,title LOAD
  303,title ELLIPSE
  322,title {}
  320,line 182
  319,line 175
  error error
  271,t 0
  292,t 0
  302,t 0
  316,line 133
  323,t 1
  273,title YES
  313,line 125
  292,title LIST
  302,title CIRCLE
  321,title {}
  267,t 0
  310,line 108
  309,line 104
  299,line 57
  288,t 0
  320,t 1
  319,t 1
  306,line 65
  296,line 53
  272,title ITALIC
  291,title INVERT
  293,line 50
  301,title WIDTH
  303,line 62
  320,title {}
  319,title {}
  264,t 0
  285,t 0
  289,line 46
  290,line 47
  300,line 58
  316,t 1
  286,line 43
  271,title ROMAN
  261,t 0
  283,line 40
  289,title FILL
  290,title FRONT
  300,title SHOW
  318,title {}
  282,t 0
  279,line 32
  280,line 33
  313,t 1
  276,line 28
  257,t 0
  269,title NORMAL
  270,title BOLD
  273,line 25
  288,title DELETE
  317,title {}
  278,t 0
  310,t 1
  309,t 1
  299,t 0
  269,line 20
  270,line 21
  266,line 17
  268,title COURIER
  275,t 0
  263,line 14
  287,title DASH
  316,title {}
  306,t 0
  296,t 0
  260,line 10
  259,line 54
  322,line 193
  272,t 0
  267,title HELVETICA
  257 CUT_
  286,title COMMAND
  293,t 0
  303,t 0
  315,title {}
  258 COPY_
  318,line 171
  260 UNDO_
  259 PASTE_
  261 FONT_
  262 FONTSIZE_
  263 FONTSLANT_
  264 FONTSTYLE_
  315,line 130
  265 FONTWEIGHT_
  266 TIMES_
  267 HELVETICA_
  268,t 0
  268 COURIER_
  269 NORMAL_
  270 BOLD_
  312,line 117
  271 ROMAN_
  272 ITALIC_
  289,t 0
  290,t 0
  300,t 0
  266,title TIMES
  273 YES_
  274 NO_
  285,title COLOR
  321,t 1
  314,title {}
  275 ON_
  308,line 99
  276 OFF_
  298,line 56
  277 TRUE_
  278 FALSE_
  279 INT_
  280 REAL_
  281 STRING_
  305,line 64
  282 ALL_
  295,line 52
  265,t 0
  283 BACK_
  284 CLOSE_
  285 COLOR_
}

proc illustrate::yyparse {} {
    variable yylval
    variable table
    variable rules
    variable token
    variable yycnt
    variable lr1_table
    variable token_id_table
    variable yyerr
    variable save_state

    set yycnt 0
    set state_stack {0}
    set value_stack {{}}
    set token ""
    set accepted 0
    set yyerr 0
    set save_state 0

    while {$accepted == 0} {
        set state [lindex $state_stack end]
        if {$token == ""} {
            set yylval ""
            set token [yylex]
            set buflval $yylval
	    if {$token>0} {
	        incr yycnt
            }
        }
        if {![info exists table($state:$token)] || $yyerr} {
	    if {!$yyerr} {
	        set save_state $state
	    }
            # pop off states until error token accepted
            while {[llength $state_stack] > 0 && \
                       ![info exists table($state:error)]} {
                set state_stack [lrange $state_stack 0 end-1]
                set value_stack [lrange $value_stack 0 \
                                       [expr {[llength $state_stack] - 1}]]
                set state [lindex $state_stack end]
            }
            if {[llength $state_stack] == 0} {
 
	        set rr { }
                if {[info exists lr1_table($save_state,trans)] && [llength $lr1_table($save_state,trans)] >= 1} {
                    foreach trans $lr1_table($save_state,trans) {
                        foreach {tok_id nextstate} $trans {
			    set ss $token_id_table($tok_id,title)
			    if {$ss != {}} {
			        append rr "$ss, "
                            }
                        }
                    }
                }
		set rr [string trimleft $rr { }]
		set rr [string trimright $rr {, }]
                yyerror "parse error, expecting: $rr"


                return 1
            }
            lappend state_stack [set state $table($state:error,target)]
            lappend value_stack {}
            # consume tokens until it finds an acceptable one
            while {![info exists table($state:$token)]} {
                if {$token == 0} {
                    yyerror "end of file while recovering from error"
                    return 1
                }
                set yylval {}
                set token [yylex]
                set buflval $yylval
            }
            continue
        }
        switch -- $table($state:$token) {
            shift {
                lappend state_stack $table($state:$token,target)
                lappend value_stack $buflval
                set token ""
            }
            reduce {
                set rule $table($state:$token,target)
                set ll $rules($rule,l)
                if {[info exists rules($rule,e)]} {
                    set dc $rules($rule,e)
                } else {
                    set dc $rules($rule,dc)
                }
                set stackpointer [expr {[llength $state_stack]-$dc}]
                setupvalues $value_stack $stackpointer $dc
                set _ $1
                set yylval [lindex $value_stack end]
                switch -- $rule {
                    1 { set _ times }
                    2 { set _ helvetica }
                    3 { set _ courier }
                    4 { set _ normal }
                    5 { set _ bold }
                    6 { set _ roman }
                    7 { set _ italic }
                    8 { set _ normal }
                    9 { set _ bold }
                    10 { set _ italic }
                    11 { set _ 1 }
                    12 { set _ 1 }
                    13 { set _ 1 }
                    14 { set _ 1 }
                    15 { set _ 0 }
                    16 { set _ 0 }
                    17 { set _ 0 }
                    18 { set _ $1 }
                    19 { set _ $1 }
                    21 { global ds9; if {!$ds9(init)} {YYERROR} else {yyclearin; YYACCEPT} }
                    23 { IllustrateCmdLoad }
                    24 { ProcessCmdSet illustrate shape $2 {} }
                    25 { ProcessCmdSet illustrate color $2 IllustrateUpdateGraphic }
                    26 { ProcessCmdSet illustrate fill $2 IllustrateUpdateGraphic }
                    27 { ProcessCmdSet illustrate width $2 IllustrateUpdateGraphic }
                    28 { ProcessCmdSet illustrate dash $2 IllustrateUpdateGraphic }
                    29 { ProcessCmdSet illustrate font $2 IllustrateUpdateGraphic }
                    30 { ProcessCmdSet illustrate font,size $2 IllustrateUpdateGraphic }
                    31 { ProcessCmdSet illustrate font,weight $2 IllustrateUpdateGraphic }
                    32 { ProcessCmdSet illustrate font,slant $2 IllustrateUpdateGraphic }
                    38 { IllustrateLoadFn $1 }
                    39 { IllustrateLoadFn $2 }
                    40 { ProcessCmdSet illustrate show $2 IllustrateShow }
                    41 { IllustrateCmdCommand $2 }
                    42 { IllustrateUndo }
                    43 { IllustrateCut }
                    44 { IllustrateCopy }
                    45 { IllustratePaste }
                    46 { set _ circle }
                    47 { set _ ellipse }
                    48 { set _ box }
                    49 { set _ polygon }
                    50 { set _ line }
                    51 { set _ text }
                    52 { IllustrateMoveFront }
                    53 { IllustrateMoveBack }
                    54 { IllustrateSelectAll }
                    55 { IllustrateSelectNone }
                    56 { IllustrateInvertSelect }
                    57 { IllustrateSelectFront }
                    58 { IllustrateSelectBack }
                    59 { IllustrateSaveAll }
                    60 { IllustrateSaveSelect }
                    61 { IllustrateSaveAll }
                    62 { IllustrateListAll }
                    63 { IllustrateListSelect }
                    64 { IllustrateListAll }
                    65 { SimpleTextDestroy illustratetxt }
                    66 { IllustrateDeleteAll }
                    67 { IllustrateDeleteSelect }
                    68 { IllustrateDeleteAll }
                }
                unsetupvalues $dc
                # pop off tokens from the stack if normal rule
                if {![info exists rules($rule,e)]} {
                    incr stackpointer -1
                    set state_stack [lrange $state_stack 0 $stackpointer]
                    set value_stack [lrange $value_stack 0 $stackpointer]
                }
                # now do the goto transition
                lappend state_stack $table([lindex $state_stack end]:$ll,target)
                lappend value_stack $_
            }
            accept {
                set accepted 1
            }
            goto -
            default {
                puts stderr "Internal parser error: illegal command $table($state:$token)"
                return 2
            }
        }
    }
    return 0
}

######
# end autogenerated taccle functions
######

proc illustrate::yyerror {msg} {
     variable yycnt
     variable yy_current_buffer
     variable index_

     ParserError $msg $yycnt $yy_current_buffer $index_
}
