=pod

=head1 NAME



B<FunClose - close a Funtools data file>



=head1 SYNOPSIS





  #include <funtools.h>

  void FunClose(Fun fun)





=head1 DESCRIPTION




The B<FunClose()> routine closes a previously-opened Funtools data
file, freeing control structures. If a 
Funtools reference handle
was passed to
the FunOpen() call for this file,
and if copy mode also was specified for that file, then 
FunClose() also will copy the
remaining extensions from the input file to the output file (if the
input file still is open).  Thus, we recommend always closing the
output Funtools file B<before> the input file.  (Alternatively,
you can call FunFlush()
explicitly).




=head1 SEE ALSO



See funtools(n) for a list of Funtools help pages


=cut
