=pod

=head1 NAME



B<Funtools: FITS Users Need Tools>



=head1 SYNOPSIS




This document is the Table of Contents for Funtools.



=head1 DESCRIPTION




Funtools, is a "minimal buy-in" FITS library and utility package developed
at the the High Energy Astrophysics Division of SAO.  The Funtools
library provides simplified access to a wide array of file types:
standard astronomical FITS images and binary tables, raw arrays and
binary event lists, and even tables of ASCII column data.  A
sophisticated region filtering library (compatible with ds9) filters
images and tables using boolean operations between geometric shapes,
support world coordinates, etc.  Funtools also supports advanced
capabilities such as optimized data searching using index files.

The main goal of the Funtools project has been to develop a minimal buy-in
FITS library for researchers who are occasional (but serious) coders.  In
this case, "minimal buy-in" means "easy to learn, easy to use, and easy to
re-learn next month". We have tried to achieve this goal by emphasizing two
essential capabilities.  The first is the ability to develop FITS programs
without knowing much about FITS, i.e., without having to deal with the
arcane rules for generating a properly formatted FITS file.  The second is
to support the use of already-familiar C/Unix facilities, especially C
structs and Unix stdio. Taken together, these two capabilities should allow
researchers to leverage their existing programming expertise while
minimizing the need to learn new and complex coding rules.




Choose from the following topics:




=over 4




=item *

Funtools User Programs


=over 4




=item *

funcalc: Funtools calculator (for binary tables)
[funcalc(1)]


=item *

funcen: find centroid (for binary tables)
[funcen(1)]


=item *

funcnts: count photons in specified regions
[funcnts(1)]


=item *

funcone: cone search on RA, Dec columns
[funcone(1)]


=item *

fundisp: display data in a Funtools data file
[fundisp(1)]


=item *

funhead: display a header in a Funtools file
[funhead(1)]


=item *

funhist: create a 1D histogram of a column
[funhist(1)]


=item *

funimage: create a FITS image from a Funtools data file
[funimage(1)]


=item *

funindex: create an index on a column in a binary table
[funindex(1)]


=item *

funjoin: join two or more FITS binary tables on specified columns
[funjoin(1)]


=item *

funmerge: merge one or more Funtools table files
[funmerge(1)]


=item *

funsky: convert between image and sky coordinates, using WCS info from a FITS header
[funsky(1)]


=item *

funtable: copy selected rows from a Funtools file to a FITS binary table
[funtable(1)]


=item *

funtbl: extract a table from
Funtools ASCII output
[funtbl(1)]


=item *

funtools and ds9 image display
[funds9(n)]


=back





=item *

Funtools Programming


=over 4




=item *

Funtools Programming Summary
[funlib(3)]


=item *

Funtools Programming Tutorial
[funlib(3)]


=item *

A Short Digression on Subroutine Order
[funlib(3)]


=item *

Compiling and Linking
[funlib(3)]


=item *

The Funtools Reference Handle
[funlib(3)]


=item *

The Funtools Programming Reference Manual


=over 4




=item *

FunOpen: open a Funtools file
[funopen(3)]


=item *

FunImageGet: retrieve image data
[funimageget(3)]


=item *

FunImagePut: output image data
[funimageput(3)]


=item *

FunImageRowGet: retrieve image data by row
[funimagerowget(3)]


=item *

FunImageRowPut: output image data by row
[funimagerowput(3)]


=item *

FunTableRowGet: retrieve rows from a table
[funtablerowget(3)]


=item *

FunTableRowPut: output rows to a table
[funtablerowput(3)]


=item *

FunColumnSelect: select columns in a table for access
[funcolumnselect(3)]


=item *

FunColumnActivate: activate columns in a table for read/write
[funcolumnactivate(3)]


=item *

FunColumnLookup: lookup info about  the columns in a table
[funcolumnlookup(3)]


=item *

FunInfoGet: get info about an image or table
[funinfoget(3)]


=item *

FunInfoPut: put info about an image or table
[funinfoput(3)]


=item *

FunParamGet: get header param
[funparamget(3)]


=item *

FunParamPut: put header param
[funparamput(3)]


=item *

FunFlush: flush I/O in a Funtools file
[funflush(3)]


=item *

FunClose: close a Funtools file
[funclose(3)]


=back





=item *

Funtools Programming Examples
[funlib(3)]


=over 4

 


=item *

evmerge: merge new columns with existing columns


=item *

evcols: add column and rows to binary tables


=item *

imblank: blank out image values below a threshold


=back




=back





=item *

Funtools Data Files
[funfiles(n)]


=over 4

 


=item *

Supported Data Formats


=over 4




=item *

FITS File and Extensions


=item *

Non-FITS Raw Event Files


=item *

Non-FITS Array Files


=item *

Column-based Text (ASCII) Files


=item *

Database Views of Tables


=back




=item *

Image Sections and Blocking


=item *

Binning FITS Binary Tables and Non-FITS Event Files


=item *

Disk Files and Other Supported File Types


=back





=item *

Funtools Data Filtering


=over 4




=item *

Table Filtering
[funfilters(n)]


=item *

Fast Table Filtering using Indexes
[funidx(n)]


=item *

Spatial Region Filtering
[funregions(n)]


=over 4




=item *

Region Geometry
[reggeometry(n)]


=item *

Region Algebra
[regalgebra(n)]


=item *

Region Coordinates
[regcoords(n)]


=item *

Region Boundaries
[regbounds(n)]


=item *

Differences Between Funtools and IRAF Regions
[regdiff(n)]


=back




=item *

Combining Table and Region Filters
[funcombine(n)]


=back





=item *

Miscellaneous


=over 4




=item *

Funtools Environment Variables
[funenv(n)]


=item *

Funtools ChangeLog


=back





=back

 




=cut
