name: build-aqua
run-name: Build Aqua

on:
  push:
    branches:
    - master
    tags:
    - '*'
  pull_request:

#Reduces GH Action duplication:
# Cancels the previous pipeline for this ref it is still running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-builds:
    defaults:
      run:
        shell: bash

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: macOS Latest ARM
            os: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # 6.0.2

    - name: Install dependencies
      env:
        DS9_BUILD_OS: ${{ matrix.os }}
      run: |
        source .github/scripts/setup.sh

    - name: Configure
      run: |
        macos/configure

    - name: Build
      run: |
        make && make dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: binary-${{ matrix.os }}
        path: dist/SAOImage*dmg
        archive: false
